### ISSUE TITLE
[BUG][FormTribe 🔥][100 Points] The responsiveness of the card for smaller screen gets overlaped 

### ISSUE THREAD

**Issue by itzabhinavarya** [formbricks/formbricks#1001]
### Issue Summary

Card design is little unresponsive for the smaller screen, I would like to fix this issue. Please assign this task to me.
<img width="590" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/87ebc628-b63d-48cf-bd92-d51727435638">

### Steps to Reproduce

Navigate to the card section of the website (width > 787px & < 950px).

### Expected behavior

It should be aligned perfectly and decreases it's size to prevent overlapping

### Screenshots

<img width="590" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/9dbf0223-672d-4d70-ba43-d627136f4ae9">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Don't matter
- Node: Don't matter
- npm: Don't matter
```

**Comment by jobenjada** [comment]
+50 points for flagging :)

**Comment by jobenjada** [comment]
its solved
