### ISSUE TITLE
[BUG] FormTribe Hackathon banner broken on smaller screens

### ISSUE THREAD

**Issue by zaCKoZAck0** [formbricks/formbricks#1002]
### Issue Summary

FormTribe hackathon banner is broken on smaller screens on [formbricks.com](https://formbricks.com/)

### Steps to Reproduce

1. Go to [formbricks.com](https://formbricks.com/), Turn on responsive view.
2. See FormTribe banner breaking itself.

### Expected behavior

1. Banner Should be responsive

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/69889382/97920750-071e-427f-a2de-f0fe85539356)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:none
- Node:none
- npm:none
```

**Comment by Saga-sanga** [comment]
Tried replicating your issue and it seems the component breaks only for screen widths smaller than 322px which might not really be an issue since most device screens are bigger than that.

**Comment by zaCKoZAck0** [comment]
> Tried replicating your issue and it seems the component breaks only for screen widths smaller than 322px which might not really be an issue since most device screens are bigger than that.

Ya I got it, It was breaking for galaxy fold.
