### ISSUE TITLE
[BUG][150 Points] In Multi select, removeItem doesn't work and adds multiple strings in values array

### ISSUE THREAD

**Issue by rohan9896** [formbricks/formbricks#1003]
### Issue Summary

In Multi select, multiple otherValue keeps getting added in values array, and after coming back from next question, it prefills back the first otherValue added in values.

### Steps to Reproduce

1. (for example) go to https://formbricks.com/clleljrog0050my0h1dn9kcrh
2. Select Other option and add some string (let's say - asd)
3. Go to the next question and come back.
4. asd will be prefilled on other option (which is expected behaviour).
5. Change the value to some other string (let's say - mnb).
6. Again, go to the next question and comeback.
7. You will see asd prefilled instead of mnb.

### Expected behavior

Only one `otherValue` should be added in values array.

### Other information

https://www.loom.com/share/2d769ab1648245dbaab7f1c4e148ebc0?sid=f8d47c33-0f31-4bca-bb1b-b91622d29bb9

**Comment by rohan9896** [comment]
@mattinannt @jobenjada I can work on this since I am already working on #995.

**Comment by zaCKoZAck0** [comment]
I would like to work on it.

**Comment by mattinannt** [comment]
@rohan9896 thank you 😊 I assigned you to this issue.

**Comment by jobenjada** [comment]
+50 points for flagging it 🎏  🙏

**Comment by rohan9896** [comment]
Hi @jobenjada @mattinannt, I have added a fix of this issue in #995's pull request since this was added as a review comment by @ShubhamPalriwala
