### ISSUE TITLE
[BUG][FormTribe 🔥][100 Points] Cannot move to next question until the first value is selected in Multi-Select Question

### ISSUE THREAD

**Issue by ShubhamPalriwala** [formbricks/formbricks#1008]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Issue Summary

When submitting a multi-select question, a user cannot proceed until they select the first value in the list

https://www.loom.com/share/c1e3fcb01f8743c48609686b4bd5f782?sid=81b58868-a2c2-4823-8b8f-9c8f01633eba

### Steps to Reproduce

1. Create a Survey with a multi-select question
2. Try to submit this question without selecting the first option in the survey preview section or publish the survey and then try.

### Expected behavior

The Multi-select question should allow any value(s) to be selected irrespective of their position/order in the question

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by KapadiaNaitik** [comment]
@ShubhamPalriwala I would like to work on this

**Comment by gupta-piyush19** [comment]
Hey @ShubhamPalriwala, can I pick this up?

**Comment by ShubhamPalriwala** [comment]
Thanks @KapadiaNaitik! assigning it to you :rocket: make sure you push your work in under 24 hours 🤞🏼

**Comment by PratikAwaik** [comment]
Hey @ShubhamPalriwala This issue was already fixed. Seems like someone approved the previous changes during merge conflict. Here's the PR that was already merged and fixed the issue.

https://github.com/formbricks/formbricks/pull/913
