### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Try it now button does not look right and text is very light 

### ISSUE THREAD

**Issue by ratishjain12** [formbricks/formbricks#1012]
### Issue Summary

I want to fix this button @jobenjada 

![image](https://github.com/formbricks/formbricks/assets/43003421/a7ba3a27-709d-403d-abed-1238e107d99c)

As you can see the text is very light

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...
-

### Expected behavior

-

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by jobenjada** [comment]
Where is this button?

**Comment by ratishjain12** [comment]
> Where is this button?

Every features for example in feature chaser

**Comment by mittalsam98** [comment]
Can I work on this?

**Comment by jobenjada** [comment]
Got it! +50 points for flaggin and +50 to get it solved @ratishjain12 the issue is yours :)

**Comment by ratishjain12** [comment]
![image](https://github.com/formbricks/formbricks/assets/43003421/d3d45daf-66c9-4131-ac16-eae59cba7304)
@jobenjada this works?
