### ISSUE TITLE
[BUG][FormTribe 🔥][150 Points] Buttons Margin issue across Docs

### ISSUE THREAD

**Issue by ShubhamPalriwala** [formbricks/formbricks#1016]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Issue Summary

In the `apps/formbricks-com/app/docs`, the margins and width got a little messy and have resulted in the following render:
![Screenshot_2023-10-08-19-04-36_1920x1080](https://github.com/formbricks/formbricks/assets/55556994/8c9187c7-5127-414c-a31b-ebd4806a02ad)

As you can see, the **Quickstart** and the **Try Formbricks Cloud** should come with the same left margin/padding as that of the text.

Its similar for the Code snippets as well:
![image](https://github.com/formbricks/formbricks/assets/55556994/ef336824-16d6-4aef-aa22-e26d6520755b)

### Steps to Reproduce

1. Visit any of our documentation page: https://formbricks.com/docs/getting-started/framework-guides and you'll be able to notice the full width components that aren't aligned with the text components.
2. Since this a part of the `formbricks-com` repo, you can run it using:
```
cd apps/formbricks-com && npm run dev
```

### Expected behavior

All the components in the docs should have a standard margin and follow uniformity. Focus on finding out the fundamental issue rather than setting margins/padding to each component. It should ideally be a neat fix.

### Other information

Please make sure that your changes do not affect the formbricks-com _landing page_ since this and the _app/docs/_ are under the same package and closely packed.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by adityadeshlahre** [comment]
i would love to take this ! :smile:

**Comment by JiyaGupta-cs** [comment]
Please assign this to me!!!!

**Comment by ShubhamPalriwala** [comment]
Alright, please remember to open a draft PR (or even a ready PR) in the next 24 hours! Let me know if you need help in any way! 🤞🏼

**Comment by JiyaGupta-cs** [comment]
Please add hacksquad tag also

**Comment by JiyaGupta-cs** [comment]
I want to assign this to @bilalmirza74
He is my team member.
