### ISSUE TITLE
[FEATURE][FormTribe 🔥][250 Points] Use Brand Color Overwrite in Link Survey Embedding Modal

### ISSUE THREAD

**Issue by ShubhamPalriwala** [formbricks/formbricks#1022]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Is your feature request related to a problem? Please describe.

In the Link Survey embedding modal, we currently only show their product brand colors.

![image (1)](https://github.com/formbricks/formbricks/assets/55556994/53e91686-9a2c-4237-8ac1-716b649cd4bf)

### Describe the solution you'd like

We should respect if the person has overwritten the brand colors for the given survey and if, then show that so that we can get even closer to the actual surveys.

![image (2)](https://github.com/formbricks/formbricks/assets/55556994/0d643bab-8c56-4e95-bfb0-99b7c1aabba5)

![image (3)](https://github.com/formbricks/formbricks/assets/55556994/32072832-e70c-4e7d-af64-7567b6db2f14)

### Additional context

Do let know if you're interested and need any help with this! 😊

**Comment by gupta-piyush19** [comment]
Hi! I want to pick this up

**Comment by mittalsam98** [comment]
I would like to pick this up
