### ISSUE TITLE
[BUG][FormTribe 🔥][150 Points] SURVEY_BASE_URL in env.example is wrong.

### ISSUE THREAD

**Issue by rohan9896** [formbricks/formbricks#1039]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Issue Summary

On Creating new survey link on localhost, the url created is giving 404 error page. While if we change the SURVEY_BASE_URL to http://localhost:3000/s, it starts working.

### Steps to Reproduce

1. Setup project locally
2. Copy the .env.example file to .env file
3. Notice that in .env.example file, SURVEY_BASE_URL has a value = http://localhost:3000/i
4. Create a survey by adding some questions.
5. Publish the survey and copy the survey URL.
6. The survey url generated navigates to 404 page.

### Expected behavior

If we change the SURVEY_BASE_URL to http://localhost:3000/s, it will start working.

### Screenshots

Loom recording - 
https://www.loom.com/share/22f9c952c6e246ef850cdc77ed146187?sid=594bdd07-c58b-4def-bbb6-595840af11e2

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by ShubhamPalriwala** [comment]
Hey @rohan9896, thanks a lot for pointing this out and creating an issue! +100 points for it! It'd be great if you can work on it.

One thing I'd like to point out is that it works with the `/s/` because that's the default value as well. So to fix this aptly, figure out why the the SURVEY_BASE_URL is giving a 404 and it should work with whatever URL a user sets as the env var.

**Comment by rohan9896** [comment]
> Hey @rohan9896, thanks a lot for pointing this out and creating an issue! +100 points for it! It'd be great if you can work on it. +150 points for successfully solving it!
> 
> One thing I'd like to point out is that it works with the `/s/` because that's the default value as well. So to fix this aptly, figure out why the the SURVEY_BASE_URL is giving a 404 and it should work with whatever URL a user sets as the env var.

@ShubhamPalriwala I guess it is because of the URL shortener feature that was deployed a few days ago. It is coming inside this if block highlighted in the screenshot.
<img width="1440" alt="Screenshot 2023-10-09 at 11 45 33 PM" src="https://github.com/formbricks/formbricks/assets/56235204/afea2d18-a720-449e-9183-03cc45de451f">

**Comment by ShubhamPalriwala** [comment]
Continuing the discussion on the PR
