### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by aMySour** [formbricks/formbricks#104]
### Is your proposal related to a problem?

There are no example snoopForms, making you need to create an account just to test it out

### Describe the solution you'd like

Examples in the `README` and website

### Describe alternatives you've considered

Dealing with it

**Comment by matthiasnannt** [comment]
@aMySour What kind of examples would you like to see? screenshots/videos of how it works or examples of final forms like "built with snoopForms"?

**Comment by aMySour** [comment]
examples of finished forms would be great
