### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Image and page responsiveness in Docs section 

### ISSUE THREAD

**Issue by itzabhinavarya** [formbricks/formbricks#1044]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Issue Summary

In the Docs -> Best Practices -> Interview Prompt 
URL : https://formbricks.com/docs/best-practices/interview-prompt

The image is not flex and coming out of the box which makes the whole page unresponsive, It also creates a X-axis scroll bar in the page which overlaps and intersect the side section of the website 

Issue  Image : 
<img width="886" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/7fd6fa9c-fe91-4c46-a5b7-c032aded9870">

<img width="959" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/b9529c80-d666-4cbd-989c-0852123d1831">

### Steps to Reproduce

URL : https://formbricks.com/docs/best-practices/interview-prompt

### Expected behavior

The x-axis scroll bar should not shows and any of the section doesn't intersect with each other.
1. By fixing/resizing the image and its container can resolve this problem .

### Other information

Assign this task to me.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Not required
- Node: Not required
- npm: Not required
```

**Comment by itzabhinavarya** [comment]
@jobenjada / @ShubhamPalriwala Sir, Please assign this task to me.

**Comment by ShubhamPalriwala** [comment]
Thanks for pointing this out! +50 points for finding the bug and a quick +50 points on fixing it as well! Assigning it to you

**Comment by itzabhinavarya** [comment]
@ShubhamPalriwala Sir, Please review the PR #1048 .

**Comment by ShubhamPalriwala** [comment]
Completed via #1078
