### ISSUE TITLE
[FEATURE]add minimal mode to frontend integration

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#1052]
### Is your feature request related to a problem? Please describe.

Formbricks in its current implementation is not really suitable for large sites. The main reason for this is that a lot of unnecessary events are generated, so you need an extremely expensive and highly scaled database to support this load.

### Describe the solution you'd like

My suggestion would be to add an option in the frontend integration (e.g. minimal=true). If this is set, only the really absolutely necessary events are sent to the server, e.g. only if a survey was really displayed. You lose the nice listing of all users on the website, but with so many users this is not really practical anyway.

### Describe alternatives you've considered

Alternatively, you could drop all the events server-side and just not store them in the database. However, this solution is not really elegant and generates a lot of unnecessary traffic.

**Comment by jobenjada** [comment]
Hey! I assume, you're using Formbricks on a publicly available page?

We have painfully experienced the issues with our current approach when someone embedded the widget on a page with 400k daily visits (: So we are aware of the issue and have conceptualized a solution for it which is similar to what you're suggesting.

However, we are a small team and have a few topics open, which we want to wrap up first :) So what you're asking for will come, but it's not entirely clear, when!

Can you share some more info on where you plan to embed Formbricks? If you prefer, also via email to johannes@formbricks.com

**Comment by OMPOL1705** [comment]
Looks like a great issue to work on. Please assign it to me.

**Comment by jobenjada** [comment]
@OMPOL1705 its quite a complex issue, we will cover it within the team :)

**Comment by mattinannt** [comment]
We have just released `@formbricks-js` version 1.2.0 with optional user authentication.
https://formbricks.com/docs/attributes/identify-users

Without user identification, formbricks-js is suitable for public-facing websites because we don't create a person in Formbricks, don't store events, and do all calculations for displaying the survey in the user's browser.
