### ISSUE TITLE
[FEATURE][FormTribe 🔥][50 Points] Fixing Navbar to top on Scroll

### ISSUE THREAD

**Issue by Kritika30032002** [formbricks/formbricks#1054]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Is your feature request related to a problem? Please describe.

Yes, if while scrolling user want to navigate to any other route like docs or pricing, he/she will not be able to do it after scrolling down .

### Describe the solution you'd like

Fixing Navbar to top on Scroll

**Comment by Kritika30032002** [comment]
Assign me this

**Comment by mittalsam98** [comment]
I would like to pick this up

**Comment by jobenjada** [comment]
Hey Kritika! Thanks a lot for your suggestion :)

Feel free to open a PR with your solution - thanks 🙏

**Comment by kalkeshwar** [comment]
Hi @jobenjada  I want to work on this issue, can you please assign this issue
Solution: just adding classes in tailwind like fixed or sticky based on requirement in the layout.tsx

**Comment by shyamraghu** [comment]
Hi @kalkeshwar you are using sticky navbar or you are creating a button for go the the top when user click on it?

**Comment by shyamraghu** [comment]
@jobenjada can i work on this?

**Comment by kalkeshwar** [comment]
Hi @shyamraghu , I think problem here is navbar is missing while scrolling , so sticky is enough

**Comment by abhayv290** [comment]
Ok let me pick this issue

**Comment by rohitmak** [comment]
Would like to work on it.
