### ISSUE TITLE
[FEATURE][FormTribe 🔥][750 Points] Question Type: Welcome Screen

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1055]
### Is your feature request related to a problem? Please describe.

Users want to add a Welcome Message to their link survey.

### Describe the solution you'd like

Essentially, its the CTA question type with bells and whistles:

<img width="701" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/97b709f5-6fb0-4462-b45c-527b12f0233d">

### Tasks

1. Add a new question type Welcome Screen with Hero Icon "HandRaised". You can copy the CTA Question type as a starting point:
<img width="717" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/46c568e6-bb0f-4f53-ab66-93eeeb2873a2">

2. Add question card with the following settings:
<img width="814" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/6ef2a38c-4512-4eb4-9b74-2a073017f127">

3. Make sure that the welcome card is always the first in the Survey Editor (alike the Thank You card always being the last element)
4. The welcome card does not need any UI in the survey summary

### Technical Notes

- Calculate Time to finish and display in preview as follows: 4 questions = 1 minute
- If survey contains branching: Take the shortest route for your calculation (the logic for that is in the Progress Bar calculation). To not repeat ourselves, create a helper function for that and use it in the ProgressBar and for the time calculation
- If it would take more than 6 minutes to complete the survey, just display "6+ minutes". Calculate this value in the editor and store it with the survey object to then display it in the end user facing UI.
- Use "corner-down-left" for the "Enter" hint from lucid icon set (already installed). In a different ticket we're solving keyboard accessibility

### File Upload API Specification

Formbricks provides two distinct categories of file storage:

**Public Files:** Accessible to everyone.

**Private Files:** Accessible only to users with proper authentication and authorization.

For this feature, we only need public files.

------

### Public File Upload

**Purpose:**
Public files primarily serve survey creators who wish to embed assets such as company logos in their surveys or use images for specific question types.

**Endpoint:**
`POST /api/v1/management/storage`

**Request Body:**

`fileName`: Name of the file to be uploaded.

`contentType`: MIME type of the file.

`environmentId`: Identifier for the environment the file belongs to.

`fileBuffer`: Binary data of the file.

`allowedFileExtensions`: List of permissible file extensions for the upload.

**Authentication:**
This route requires user authentication and the user must have access rights to the specified environmentId.

**Retrieving Files**

Purpose: To fetch either public or private files.

Endpoint:` GET /storage/[environmentId]/[accessType]/[fileName]/route.ts`

**Query Parameters:** 
environmentId: Each file, whether on S3 or local storage, will reside inside a directory named after its environmentId.

`accessType`: Denotes if the file is public (public) or private (private).

`fileName`: The name of the file being requested.

A**uthentication and Authorization:**
The GET endpoint will validate the authentication and authorization if necessary. If unauthorized, it will throw an authentication error.

-----

If things re upload functionality are unclear, reach out to @pandeymangg on Discord :)

**Comment by prasoonmhwr** [comment]
May I Work on this

**Comment by jobenjada** [comment]
Hey @prasoonmhwr I think you didnt yet gather enough relevant experience to ship this! Have you built something as complex before?

**Comment by prasoonmhwr** [comment]
@jobenjada In formbricks I haven't but in other companies yes, maybe I can give it a try

**Comment by KapadiaNaitik** [comment]
Can I work on this?

**Comment by jobenjada** [comment]
@KapadiaNaitik You got it! :)

**Comment by jobenjada** [comment]
@prasoonmhwr We'll be releasing more tickets today, I'll ping you with one I think is suitable ok? :)
