### ISSUE TITLE
[FEATURE][FormTribe 🔥][500 Points] Dynamic Link Previews

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1064]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Is your feature request related to a problem? Please describe.

Link previews are not optimized:

<img width="487" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/5c79d754-9393-4555-8ac1-7d244afe2604">

### Describe the solution you'd like

Leverage next.js dynamic link preview feature for better link previews:

<img width="744" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/bb1d092a-d2db-47dd-871d-c76b43d9a4d1">

### Tasks

- Use nextJS [dynamic image generation](https://cruip.com/generate-dynamic-open-graph-and-twitter-images-in-next-js/#:~:text=In%20summary%2C%20it%20involves%20generating,in%20just%20a%20few%20milliseconds!) to create the thumbnail for each survey
- When generating it, make sure that the color of the "Begin" button is set to the brandColor value of the product.
- The "Complete in ~4 Minutes" is static for now, the calculation will be done in a different ticket next week :) We will then update it here, but it shouldn't stop us from shipping 🚢

### Technical Details 
- Utilize the next/head component to insert these tags into the head of the rendered page. You need to add some meta tags like :

- `og:title:` Reflecting the survey's name.
- `og:description:` The "Complete in 4 Minutes"

You can dynamically add these in 

`apps/web/app/s/[surveyId]/page.tsx`

You wont be able to test this on localhost. So you can use something like **ngrok** .

ngrok grants a public URL, mapped to our local server, perfect for real-time testing. Sharing links via this URL on various platforms can help verify the dynamic generation of our meta tags. 

You can test the previews here : https://link-previews.stephanbogner.de/

Please follow [this tutorial](https://cruip.com/generate-dynamic-open-graph-and-twitter-images-in-next-js/#:~:text=In%20summary%2C%20it%20involves%20generating,in%20just%20a%20few%20milliseconds!) for more context on how to get it done :)

**Comment by anjy7** [comment]
I would like to take this one @jobenjada

**Comment by jobenjada** [comment]
Go for it :)

**Comment by heysagnik** [comment]
.take

**Comment by nepomuc** [comment]
Is "Complete in 4 Minutes" really hardcoded?! I got a tini-tiny survey which takes about 10 seconds with only one question and now my users see a big preview-image telling them that the survey is going to take 4 minutes. :/

**Comment by jobenjada** [comment]
ohhh in the Link Preview 😬 We need to double check, we'll have a look at it and @Dhruwang will likely be able to push a fix tomorrow morning.
