### ISSUE TITLE
[FEATURE][FormTribe 🔥][100 Points] Fix the label on the connections indicator

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1066]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Is your feature request related to a problem? Please describe.

The Webhook counter says "Zaps" instead of "Webhooks"

<img width="841" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/a8c902c1-363c-42ad-b881-7fb13a7bb510">

### Describe the solution you'd like

Update it so that for Zapier it says _Zaps_ and for Webhooks it says _Webhooks_

**Comment by SiR-PENt** [comment]
I will like to work on this @jobenjada

**Comment by ShubhamPalriwala** [comment]
Completed via #1068
