### ISSUE TITLE
[BUG][FormTribe 🔥][100 Points] "X" button overlapping with "optional" tag in widget

### ISSUE THREAD

**Issue by Dhruwang** [formbricks/formbricks#1067]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------
### Issue Summary

In our JS widget, for the questions that are optional, "X" button over laps with "optional" tag

### Steps to Reproduce

1. Make an in-app survey with optional questions
2. Open demo app on [http://localhost:3002/app](http://localhost:3002/app)
3. Try to take that survey

### Expected behavior

There should be a little space between "x" and "optional" tag

### Other information

Please make sure, that widget doesn't get too much bigger. Try decreasing size of "X" button a bit and give it a very little margin on the bottom.

### Screenshots

<img width="436" alt="Screenshot 2023-10-10 at 3 05 05 PM" src="https://github.com/formbricks/formbricks/assets/67850763/165ea11a-4fc0-4a29-9612-274a55c7a1f5">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: MacOS
- Browser: Brave
```
### Thanks!

**Comment by AnushDeokar** [comment]
Hi, I would like to work on this

**Comment by RajuGangitla** [comment]
@jobenjada only assigned people are allowed to work on the issue because i am also interested to solve issues
