### ISSUE TITLE
[BUG][FormTribe 🔥][100 Points]  formbricks.com landing page has a horizontal scrollbar in small viewport devices - Bad CSS.

### ISSUE THREAD

**Issue by Bitnagar** [formbricks/formbricks#1071]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Issue Summary

[formbricks.com](https://www.formbricks.com) landing page has a horizontal scrollbar in smaller viewport devices which could be due to bad CSS code. Multiple elements starts overflowing when the screen size becomes. <=380px.

### Steps to Reproduce

1. Go to [formbricks.com](https://www.formbricks.com)
2. Change the window size to ~380px
3. Observer the horizontal scrollbar occurring due to an element is overflowing at the bottom part of the page.
4. If using a smartphone, visit the website and observe the issue.

See below:

https://github.com/formbricks/formbricks/assets/88842947/af1ca53d-7c4a-496f-ade0-a0f4a1d102e6

### Expected behavior

This should be the expect behaviour. No horizontal scrollbar should be seen.

https://github.com/formbricks/formbricks/assets/88842947/377c157d-fb01-4ad0-a748-7b68163c2936

### Other information

Tested on:
- Latest Chrome
- Latest Firefox
- Latest Mobile Chrome browser. (on a device having ~360px viewport)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Window 11 Latest
- Node: v18.18.0 (Gitpod)
- npm: 9.8.1 (Gitpod)
```

**Comment by Bitnagar** [comment]
Hey Formbricks Team. If you consider this issue, I would definitely love to work on this one.

**Comment by ShubhamPalriwala** [comment]
Hey @Bitnagar, thanks for pointing out the bug +50 points for it! +100 points for fixing it as well! 

Assigning it to you. Please make sure you open a PR (atleast a draft one) in 24 hours
