### ISSUE TITLE
[BUG] MultiChoiceMultiSelect is breaking

### ISSUE THREAD

**Issue by gupta-piyush19** [formbricks/formbricks#1085]
### Issue Summary

Question type: MultiChoiceMultiSelect is breaking.
The optional question throws an error if proceeding without selecting any option.

### Steps to Reproduce

1. Create a survey with ques of type: `MultiChoiceMultiSelect`
2. Click on next without selecting any option.

### Expected behavior

It should move to the next question.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by adityadeshlahre** [comment]
![image](https://github.com/formbricks/formbricks/assets/132184385/c213ae98-9554-4cdc-8713-34b679ed1f2e)

hey @gupta-piyush19 this error ??
