### ISSUE TITLE
[FEATURE][FormTribe 🔥][500 Points] PIN protected surveys

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1089]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Is your feature request related to a problem? Please describe.

Some users want to protect their survey with a code

### Describe the solution you'd like

Enable protected surveys:

<img width="492" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/4e3b52b6-df17-4319-8991-017af6084e2a">

### Tasks

1. Add a new setting to the Response Options card, which is only visible if surveyType = link:
<img width="692" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/73cfbd98-ffc8-4780-9ba6-87033d3103cb">

**Name**: Protect survey with a PIN
**Subheadline**: Only users who have the PIN can access the survey

<img width="587" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/bc8d718d-b4ea-4b36-88df-4817fdae8385">

2. Validate that only numbers are added and not more than 4. You can validate on blur and if it doesnt match, delete the input and display a Toast with the following error message "Please set four numbers as PIN"

3. Create the needed UI and import it to the LinkSurvey.tsx. The mockup above is from our upcoming UI revamp and only meant as guidance. No need to build it 1:1

4. Build the logic needed to load the survey only in case the PIN was correct. The PIN does not help a lot if the survey object is completely loaded in the client before the PIN was entered 😃 

### Technical Challenge

Consult with chatGPT on how to implement this best. You have to find a way to check the PIN without previously exposing it in the public survey object. If you have questions, please reach out in our Discord!

**Comment by piyushgarg-dev** [comment]
Let's do it 💪🏻

**Comment by anjy7** [comment]
Hey @piyushgarg-dev, are you still working on this ? If not then I would like to :smile:

**Comment by rohan9896** [comment]
@jobenjada If no one is working on this, I would like to pick this up!
