### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Typo on main page

### ISSUE THREAD

**Issue by vedant-z** [formbricks/formbricks#1117]
### Issue Summary

"users" word have been used twice which seems to be incorrect.

![image](https://github.com/formbricks/formbricks/assets/93431609/f127d017-5d3e-47cb-9683-eb1101751cd1)

### Steps to Reproduce

Go to main page
Look first card under "Get started with Best Practices" section

### Expected behavior

Correct sentence: Ask only power users to book a time in your calendar.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: Chrome
```

**Comment by vedant-z** [comment]
@jobenjada I would like to fix this. Please assign me.

**Comment by Vivek-04022001** [comment]
@jobenjada  Please assign me.

**Comment by ShubhamPalriwala** [comment]
@vedant-z all yours! Thanks for finding out the typo. 50 point for fixing it 😎

**Comment by ShubhamPalriwala** [comment]
Hey @vedant-z, this was already fixed by somebody else! I'll still award you 50 points for finding the bug and the effort for opening the PR. Please see if you can find something else to work on
