### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Overflow of body across leaderboard on mobile screen

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1120]
### Issue Summary

Website on mobile screen was not fix in horizontal 

### Steps to Reproduce

1. Went to ... 
https://formbricks.com/formtribe#leaderboard

### Expected behavior

Body overflow 

### Screenshots

![Screenshot_2023-10-13-11-46-27-35_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/formbricks/formbricks/assets/84387676/280e2145-62c4-4a2b-8551-414bd9e69ab1)
![Screenshot_2023-10-13-11-46-15-47_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/formbricks/formbricks/assets/84387676/abc99a85-f223-411c-9499-b983d0b176f9)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Android 
- Node: 
- npm:
```

**Comment by ShubhamPalriwala** [comment]
Thanks or pointing out the bug! +50 points for fixing the bug! Assigning it to you

**Comment by KrishayNair** [comment]
assign it to me please
