### ISSUE TITLE
[FEATURE][FormTribe 🔥][50 Points] Scroll to Top

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1122]
### Is your feature request related to a problem? Please describe.

After reaching the footer, instead of scrolling back up by rotating the mouse wheel or swiping on mobile, we can simply click on the scroll-to-top button.

![image](https://github.com/formbricks/formbricks/assets/84387676/30da5ac8-aa2e-4304-bd6a-d49bd5d8a8b6)

### Additional context

Users can scroll to the top easily 
after scrolling down

**Comment by jobenjada** [comment]
@bilalmirza74 you'll get 50 Points for mentioning this! Will check the open PR by impolska now.
