### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Doc's navbar was not responsive

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1129]
### Issue Summary

Documentation navbar was not responsive

### Steps to Reproduce

1. (for example) Went to:- https://formbricks.com/docs/introduction/what-is-formbricks
2. the Navbar tablet/iPad screen size was not responsive 

### Expected behavior

.

### Other information

.

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/84387676/56de4e86-2f1e-4199-9e06-d773eae44053)

![image](https://github.com/formbricks/formbricks/assets/84387676/63067bb2-f18f-450d-94be-47730c68216e)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: windows 11
```

**Comment by Kamna16** [comment]
please assign me with this issue

**Comment by jobenjada** [comment]
@bilalmirza74 you got it! Thanks for flagging this :)

**Comment by zaidhussain2k6** [comment]
Please assigned to me #1123
