### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Schedule Fee Kick Off button text is very light and does not look right

### ISSUE THREAD

**Issue by ratishjain12** [formbricks/formbricks#1139]
### Issue Summary

Schedule Free Kick Off Call Button does not look right 

![image](https://github.com/formbricks/formbricks/assets/43003421/13beb31f-b119-4a1d-9483-2e689dfb8ef6)

I want to fix this issue kindly assign it to me @jobenjada 

### Steps to Reproduce

-

### Expected behavior

Button colors need to be fixed.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by bibaswan7** [comment]
Please assign it to me, I am interested

**Comment by ratishjain12** [comment]
> Please assign it to me, I am interested

@bibaswan7 i am not the maintainer,I want to solve this issue thats why I have opened it :)

**Comment by Srijan-Baniyal** [comment]
Where is the button situated ?? What is the route for it ??

**Comment by DarshanBorse** [comment]
@bibaswan7 I am genuinely interested in seeing this issue resolved. Visual consistency is paramount for a seamless user experience, and I would like to offer my assistance in tackling this problem.

**Comment by sahilraj-developer** [comment]
let's  do this.

**Comment by agrahari10** [comment]
hi please assign to me this issue #1139

**Comment by jobenjada** [comment]
@ratishjain12 its yours, go for it :)

**Comment by ratishjain12** [comment]
> @ratishjain12 its yours, go for it :)

Alright @jobenjada on it
