### ISSUE TITLE
[BUG]NO DISCORD

### ISSUE THREAD

**Issue by MOHDZAMA** [formbricks/formbricks#1147]
### Issue Summary

No Discord icon in main site. but their is in docs

### Steps to Reproduce

1. Went to ...
2. https://formbricks.com/
3. then for docs Went to
4. https://formbricks.com/docs/introduction/what-is-formbricks

### Expected behavior

not showing

### Screenshots

![Capture](https://github.com/formbricks/formbricks/assets/106185773/ce0c74b2-cb58-46ee-a015-65ddbf89d3ac)
![Capture1](https://github.com/formbricks/formbricks/assets/106185773/3e97339f-83da-44a1-aa89-4e635a4215ab)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by MOHDZAMA** [comment]
Assign me this...
If I can get point here

**Comment by jobenjada** [comment]
@MOHDZAMA you will get +50 points for flagging this

@Sha1kh4 will get +50 points for solving this
