### ISSUE TITLE
[BUG] Loading state spinner overlaps button text.

### ISSUE THREAD

**Issue by Bitnagar** [formbricks/formbricks#1148]
### Issue Summary

Currently, when buttons are in loading state, the loading spinner `svg` overlaps the text of the button. See below:

https://github.com/formbricks/formbricks/assets/88842947/0a5fc76d-c2fd-4166-a17b-aa5613f8d9ee

### Steps to Reproduce

1. Go to your Formbricks App,
2. Go to `settings`.
3. Go to Look and Feel` section.
4. Change the `Brand Color` or anything else and click on `Save` button.
5. Observe the issue when the loading spinner occurs. 

This issue happens on every button that is there and has a loading state. 

### Expected behavior

There should be no overlapping of the loading state spinner `svg` and the button text as shown below:

https://github.com/formbricks/formbricks/assets/88842947/5cc8dc75-0298-456d-9056-384224a9376d

### Other information

@mattinannt If the team considers this issue, Kindly assign it to me.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11 Latest
- Node: v18.16.1
- npm: v9.5.1
```

**Comment by vishalkhoje** [comment]
Please assign to me this bug, interested to work on this

**Comment by Bitnagar** [comment]
> Please assign to me this bug, interested to work on this

@vishalkhoje I can understand your enthusiasm. Please re-read the issue. I have asked the team to assign me this. We have other issues as well. You can look into that.

**Comment by maverox** [comment]
Please assign this to me, I am trying to work on this.

**Comment by Bitnagar** [comment]
@maverox We can maintain professionalism. Respect other Contributors as well. It takes efforts to spot a bug and to fix it. Please try testing the app. You may find something else. It will be a win win for everyone.

**Comment by maverox** [comment]
I am really sorry if it came off like that, I am a new contributor. what i meant was that even though i might not be assigned i would still like to work on this locally and just in case i get assigned in future. also i changed the code a bit and it seems to be working but after doing this i found another bug. so trying to work on that

**Comment by Dhruwang** [comment]
Hey @maverox, that loading state for the button is intentional 😊

**Comment by maverox** [comment]
> Hey @Bitnagar , that loading state for the button is intentional 😊

it seemed so, because why would someone encapsulate in a div and then set position absolute which would lead it to come out of  document flow and lead to overlap

**Comment by Bitnagar** [comment]
> Hey @Bitnagar , that loading state for the button is intentional 😊

Oh snap! It looked odd to me at first. Should have confirmed this on discord😂.
