### ISSUE TITLE
[BUG] Image on login page is not aligned inside box

### ISSUE THREAD

**Issue by Amogh-Nivaskar** [formbricks/formbricks#1149]
### Issue Summary

On the login page, there is an image on the left side. I think that there is some misalignment in this image. It would look better if this image was inside the box, rather than having a part of it overflowing outside of it.

### Steps to Reproduce

1. Go to login page
2. Look at the image on the left hand side, it is not aligned properly

### Expected behavior

I think that it would look better if this image was completely inside the box.

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/99811918/ca700851-ae14-48e2-b27b-edd0e2a05c21)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Amogh-Nivaskar** [comment]
hey can this issue be assigned to me?

**Comment by Dhruwang** [comment]
Hey @Amogh-Nivaskar, that image alignment is intentional 😊.
