### ISSUE TITLE
Enhancement : Add Animation to FAQ Question Toggles

### ISSUE THREAD

**Issue by saipranay47** [formbricks/formbricks#1151]
### Issue Summary

The current state of the FAQ question toggles in Form Bricks lacks visual appeal and user engagement. To enhance the user experience, it is proposed to incorporate animation effects when toggling FAQ questions. This will not only make the interface more interactive but also provide visual cues to users, improving the overall usability of the product.

### Steps to Reproduce

1. Navigate to the FAQ section of Form Bricks.
2. Observe the current static state of the FAQ question toggles.
3. Toggle one or more FAQ questions to expand or collapse the answers.
4. Note the absence of any animation effects during the toggling process.

### Expected behavior

When toggling FAQ questions, there should be a subtle and smooth animation effect applied to the question container. This animation should provide a visually pleasing transition, such as a fade-in or slide-down effect, to indicate the expansion or collapse of the answer section. The animation should be responsive and not introduce any lag or visual artifacts.

### Screenshots

https://github.com/formbricks/formbricks/assets/70259716/524c8162-6658-49b0-9474-b0e82363f6b2

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by saipranay47** [comment]
Can you please assign the issue to me so I can get started on adding the FAQ toggle animations?

**Comment by jobenjada** [comment]
We like it snappy without animation, but thanks! :)
