### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Fix Pricing Link in mobile menu on LP

### ISSUE THREAD

**Issue by rohitmondal03** [formbricks/formbricks#1157]
### Issue Summary

Clicking on `pricing` menu is not working

### Steps to Reproduce

1. Head to website [https://formbricks.com/](https://formbricks.com/).
2. Right click on web page, select inspect then head for checking the website for various screen sizes.
3. Make the screen to mobile size.
4. Click on hamburger menu
5. Then click on pricing section
6. You'll see that the pricing section is not taking us to correct section. 

### Expected behavior

On clicking the pricing section it should take us to `/pricing` route.

### Screenshots

https://github.com/formbricks/formbricks/assets/107113353/5d9d87ee-dd62-41e5-a6d2-bc3213a41aca

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Node: v18.17.0
- npm: 9.8.1
```

**Comment by rohitmondal03** [comment]
Please assign me this issue.

**Comment by 3xp10it3r** [comment]
@rohitmondal03 Are you started working on this ? If anytime if you feel unsure then I can take up.

**Comment by sundaram2021** [comment]
hey i have fixed this bug 
please merge this  -> #1163  pull request

**Comment by rohitmondal03** [comment]
````
✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ package.json — 1 file
    ❯ (apps|packages)/**/*.{js,ts,jsx,tsx} — 1 file
      ✖ prettier --write [FAILED]
      ◼ eslint --fix
    ↓ *.json — no files
    ↓ packages/database/schema.prisma — no files
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ prettier --write:
[error] require() of ES Module /workspace/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs not supported.
[error] Instead change the require of /workspace/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
husky - pre-commit hook exited with code 1 (error)
```

@jobenjada @3xp10it3r why git commit is giving me this error and not committing my changes ?

**Comment by rohitmondal03** [comment]
> ```
> ✔ Preparing lint-staged...
> ⚠ Running tasks for staged files...
>   ❯ package.json — 1 file
>     ❯ (apps|packages)/**/*.{js,ts,jsx,tsx} — 1 file
>       ✖ prettier --write [FAILED]
>       ◼ eslint --fix
>     ↓ *.json — no files
>     ↓ packages/database/schema.prisma — no files
> ↓ Skipped because of errors from tasks.
> ✔ Reverting to original state because of errors...
> ✔ Cleaning up temporary files...
> 
> ✖ prettier --write:
> [error] require() of ES Module /workspace/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs not supported.
> [error] Instead change the require of /workspace/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
> husky - pre-commit hook exited with code 1 (error)
> ``` 
> ```

@3xp10it3r @jobenjada why commiting the issue is giving me this error ?
