### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Grammatical mistake

### ISSUE THREAD

**Issue by moheyt** [formbricks/formbricks#1159]
### Issue Summary

Your sentences have a few minor issues:

"heared" should be "heard."

The word "heared" is not standard English, which is why it should be corrected to "heard." "Heared" is a non-standard or incorrect form of the past tense of the verb "hear." The correct past tense and past participle of "hear" is "heard."

So, in the sentence, you want to use "heard" to convey that users feel that their feedback is acknowledged or listened to. "Heared" is not grammatically correct in this context.

Here's the corrected version:

"Offering a direct channel for feedback helps you build a better product. Users feel heard, and with Formbricks automations, you'll be able to react to feedback rapidly. Lastly, critical feedback can be acted upon quickly so that it doesn't end up on social media."

![Screenshot (334)](https://github.com/formbricks/formbricks/assets/85775976/804a6034-6cb1-423b-8f6f-49868db94874)

### Steps to Reproduce

1. Go to homepage.
2. Clicked on "Best Practices".
3. Then, click on "Feedback box".

### Expected behavior

"Users feel heared" should be "Users feel heard."

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Brower: Chrome
```

**Comment by RajuGangitla** [comment]
@jobenjada can u assign this issue to me

**Comment by Rishikesh63** [comment]
can u assign it to me

**Comment by 3xp10it3r** [comment]
Started working
will raise PR in 5 min.
Please assign

**Comment by Sha1kh4** [comment]
I think this type of small issues should be solved by the issuer himself immediately after submitting one as this are very minor problem , just my opnion

**Comment by moheyt** [comment]
@Sha1kh4  +1

**Comment by jobenjada** [comment]
I agree, @moheyt pls open a PR with a fix today to get the points. If not, i'll merge the first one opened :)

**Comment by moheyt** [comment]
Hey @jobenjada thanks man! but i'm getting some sort of errors while commiting please help. 

gitpod /workspace/formbricks (fix-typo) $ git commit -m "Fix typo in Feedback box"
✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ package.json — 1 file
    ❯ (apps|packages)/**/*.{js,ts,jsx,tsx} — 1 file
      ✖ prettier --write [FAILED]
      ◼ eslint --fix
    ↓ *.json — no files
    ↓ packages/database/schema.prisma — no files
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ prettier --write:
[error] require() of ES Module /workspace/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs not supported.
[error] Instead change the require of /workspace/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
husky - pre-commit hook exited with code 1 (error)

**Comment by anjy7** [comment]
Hi @moheyt , it’s because we have a pre commit hook that checks whether the commit message is in correct format. :)
In your case you should write it as “fix : commit message“

**Comment by moheyt** [comment]
thanks brother but getting same error again :) 

gitpod /workspace/formbricks (fix-typo) $ git commit -m "fix: typo in Feedback box"
✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ package.json — 2 files
    ❯ (apps|packages)/**/*.{js,ts,jsx,tsx} — 1 file
      ✖ prettier --write [FAILED]
      ◼ eslint --fix
    ↓ *.json — no files
    ↓ packages/database/schema.prisma — no files
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ prettier --write:
[error] require() of ES Module /workspace/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs not supported.
[error] Instead change the require of /workspace/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
husky - pre-commit hook exited with code 1 (error)

**Comment by anjy7** [comment]
Could you please try doing this change in your `prettier-preset.js` file - ` "plugins": [require('prettier-plugin-tailwindcss')]
` @moheyt

**Comment by moheyt** [comment]
getting same error! :)

**Comment by anjy7** [comment]
Join the discord server and post the error over there, someone who might have had faced the same might be able to help you @moheyt

**Comment by moheyt** [comment]
fix : typo in feedback box. #1192
