### ISSUE TITLE
[BUG] Link for "Pricing" Not Working on Mobile Mode

### ISSUE THREAD

**Issue by moheyt** [formbricks/formbricks#1161]
### Issue Summary

The "Pricing" link on the website is not functioning as expected when accessed on a mobile device. When accessing the website on a mobile device, users cannot navigate to the pricing page. The "Pricing" link appears to be unresponsive. On the desktop version, the link works as expected, leading users to the pricing information. I also tried accessing the website on both iOS and Android devices to ensure that the issue is not specific to a particular mobile operating system.

@jobenjada , I would like to fix this. Please assign me. #FormTribe🔥#Hacktoberfest

https://github.com/formbricks/formbricks/assets/85775976/481c5502-a612-48af-b7f0-e3ce377d4ae8

### Steps to Reproduce

1. Go to homepage.
2. Click on "Upper-left icon"
3. Then, click on "Pricing"

### Expected behavior

The "Pricing" link should be functional in both desktop and mobile modes. Users should be able to navigate to the pricing page when clicking the link on a mobile device.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: Chrome
```

**Comment by mittalsam98** [comment]
You can assign the issue to me

**Comment by sundaram2021** [comment]
This is already been issued out
issue link #1157 
and i have fixed that

**Comment by moheyt** [comment]
oh! just saw that @sundaram2021

**Comment by jobenjada** [comment]
already fixed
