### ISSUE TITLE
[BUG] hover effect issue on button- "best Practices"

### ISSUE THREAD

**Issue by khanjanSanghavi** [formbricks/formbricks#1171]
### Issue Summary

The hover effect on the button "Best Practices" stays even after we press in twice which is an UI bug

https://github.com/formbricks/formbricks/assets/75749613/a23618d4-1521-4542-ae5e-a6b2673719b7

### Steps to Reproduce

1. Go To :- https://formbricks.com/
2. find a dropdown/button named "Best Practices" in navbar
3. Click on it twice
4. the hover effect will still visible

### Expected behavior

It should appear when we click on it once and then should vanish when we click on it the second time 

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Browser: chrome
```

**Comment by 3xp10it3r** [comment]
I will be taking this Up.
Please assign me @jobenjada

**Comment by khanjanSanghavi** [comment]
I am already working on it and that was the reason to open it @3xp10it3r

**Comment by 3xp10it3r** [comment]
Duplicate Issue #1158 

Hey @khanjanSanghavi , It's duplicate issue. I have already raised PR for this in another Issue #1176

**Comment by DarshanBorse** [comment]
Please assign me @jobenjada

**Comment by jobenjada** [comment]
Duplicate issues, closing this one - thanks anyways!
