### ISSUE TITLE
[BUG] Suggestion for Improved User Experience

### ISSUE THREAD

**Issue by moheyt** [formbricks/formbricks#1174]
### Issue Summary

There is a user experience issue with the text placement related to the "Try it now" button and the statement "It's free" beneath it. The current presentation doesn't align well with good user experience principles.  It's crucial to have a clear and concise message that conveys that trying the service is free. This simple change will enhance the user experience and make it more user-friendly.

![Screenshot 2023-10-15 013509](https://github.com/formbricks/formbricks/assets/85775976/abd5613b-92d2-4e01-8937-857b91b745f9)

### Steps to Reproduce

1. Go to homepage.
2. Click on "Best Practices".
3. Then, click on "Interview Prompt" and other options.

### Expected behavior

To address this issue, I recommend updating the button "Try it now"  to "Try it now, it's free!".

![Screenshot 2023-10-15 012011](https://github.com/formbricks/formbricks/assets/85775976/adbbddc2-296e-4671-8f74-d917da7603a2)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Brower: Chrome
```

**Comment by jobenjada** [comment]
We designed it as it was on purpose :)  but thanks for your suggestion!
