### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Discord Logo in settings and Left-Side Navigation Menu Alignment

### ISSUE THREAD

**Issue by moheyt** [formbricks/formbricks#1182]
### Issue Summary

Issue 1:
In the settings menu, there is an instance of an incorrect or outdated Discord logo being used. This could potentially lead to confusion among users and may not represent the brand accurately. 

Issue 2:
The left-side navigation menu in the Discord application exhibits alignment issues. The menu elements do not appear to be consistently aligned or may suffer from layout problems, making the navigation experience less intuitive. Proper alignment and consistency within the left-side menu are crucial for a smoother and more user-friendly experience.

@jobenjada , I would like to fix this. Please assign me. #FormTribe🔥#Hacktoberfest

![Screenshot 2023-10-15 105359](https://github.com/formbricks/formbricks/assets/85775976/7d9326bc-296b-4bb5-8c66-d8ce403a4dd0)

### Steps to Reproduce

1. Sign-in Formbricks
2. Clicked on Settings 

### Expected behavior

I recommend that the Discord logo in the settings should be  replaced with a orignal logo that assists users in navigating the settings. This change would improve the overall user experience by eliminating a redundant element. Also, I kindly request that investigate and rectify the alignment issues in the left-side navigation menu to ensure a visually pleasing and efficient navigation experience for all users.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: Chrome
```

**Comment by shakthi2003-ice** [comment]
Can i work on this issue?

**Comment by 3xp10it3r** [comment]
I have started working on this @jobenjada Can you please assign this to me. Raising PR in an hour.

**Comment by moheyt** [comment]
> I have started working on this @jobenjada Can you please assign this to me. Raising PR in an hour.

 I have already done it, I'm just waiting to get assigned so that I can raise a PR.

**Comment by 3xp10it3r** [comment]
> > I have started working on this @jobenjada Can you please assign this to me. Raising PR in an hour.
> 
> @3xp10it3r I have already done it, I'm just waiting to get assigned so that I can raise a PR.

Hey you don't need to wait for assignment, You can raise your PR so other will not put effort. or make the comment that I have already did it.

**Comment by jobenjada** [comment]
@bilalmirza74 if you open such a small issue, you can open the PR along with it :)

Please replace the icon with the Discord icon from lucide icon set.

**Comment by 3xp10it3r** [comment]
If assigned person  will not submit pr and you want to assign someone else. then please assign this to me.

**Comment by moheyt** [comment]
@3xp10it3r bro, why don't you spend little amount of your time to find these kinda minor issues rather than asking to get assigned for a issue that someone find out. If you really that desperate to do contributions then i'll suggest you to go for big issues. Skip Fixing logos, typos errors, allignments, positionining for newbies like me.

**Comment by moheyt** [comment]
"Hey @jobenjada, original Discord logo not exist in the Lucide icon set? What should I do now? Should I use a different icon set?"
