### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Icons not aligned properly on Pricings page on Firefox

### ISSUE THREAD

**Issue by thevinitgupta** [formbricks/formbricks#1185]
### Issue Summary

Head on to the pricing page where the paid and unpaid versions are being compared in the table.

### The ticks and crosses are not aligned in the center 👇🏻
![image](https://github.com/formbricks/formbricks/assets/65801700/9bd8b3e3-1576-4e36-8a49-f7aa4f4993e7)

### Steps to Reproduce

1. Open the main website
2. Head on to the Pricing Tab
3. Scroll down to the comparing section for free and paid plans

### Expected behavior

The icon should look like the top one in the image below, instead it looks like the version below :
![image](https://github.com/formbricks/formbricks/assets/65801700/6eb08e8f-5b8c-4fd3-aea5-fff78d5a4a10)

### Other information

I would like to work on this!!

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- Browser : Firefox
```

**Comment by RajuGangitla** [comment]
@jobenjada can u assign this issue to me

**Comment by thevinitgupta** [comment]
> @thevinitgupta
> 
> ![image](https://user-images.githubusercontent.com/84387676/275314261-2553652d-98d5-4712-a127-2ba73058eb22.png)
> 
> ![image](https://user-images.githubusercontent.com/84387676/275314240-1cdfed4e-5ce4-4fa2-9bef-288b60580766.png)
> 
> everything is fine there

Do check in the Firefox browser

**Comment by jobenjada** [comment]
@thevinitgupta pls open a PR with a fix within 24h :)

**Comment by rijuoddusual1999** [comment]
![image](https://github.com/formbricks/formbricks/assets/113231164/37160297-66db-475f-90cf-50d5373ad058)
hey guys I am getting this database failure for multiple runs now. I have docker running and I have done everthing mentioned in the docs to host locally. Do anyone has any fix ?

**Comment by jobenjada** [comment]
Pls try pnpm clean and pnpm i and if that doesn’t help, we’ll help you in Discord :)

**Comment by manugovindv** [comment]
Hi, can I try to solve this as well?

**Comment by Aryan-git-13** [comment]
@jobenjada I can fix cross browser issue for these icons.
Do consider me for this task.
Thanks.

**Comment by OwaisOss** [comment]
> ![image](https://user-images.githubusercontent.com/113231164/275321137-37160297-66db-475f-90cf-50d5373ad058.png) hey guys I am getting this database failure for multiple runs now. I have docker running and I have done everthing mentioned in the docs to host locally. Do anyone has any fix ?

I have successfully resolved this issue! 😎

Follow these steps:

1: Install Docker Compose using the following command:


sudo apt install docker-compose

2: Run Docker Compose and check running containers:

docker-compose up -d && docker ps

3: Run the pnpm go command. If it fails, run pnpm go again:

pnpm go

Do repeat 3: step if it fails again...!!!

This will set up Docker properly and resolve the issue. 🛠️

**Comment by rijuoddusual1999** [comment]
> > ![image](https://user-images.githubusercontent.com/113231164/275321137-37160297-66db-475f-90cf-50d5373ad058.png) hey guys I am getting this database failure for multiple runs now. I have docker running and I have done everthing mentioned in the docs to host locally. Do anyone has any fix ?
> 
> I have successfully resolved this issue! 😎
> 
> Follow these steps:
> 
> 1: Install Docker Compose using the following command:
> 
> sudo apt install docker-compose
> 
> 2: Run Docker Compose and check running containers:
> 
> docker-compose up -d && docker ps
> 
> 3: Run the pnpm go command. If it fails, run pnpm go again:
> 
> pnpm go
> 
> Do repeat 3: step if it fails again...!!!
> 
> This will set up Docker properly and resolve the issue. 🛠️

I must say some part of Terry Davis still reside in you. Thanks a lot brother time to hustle

**Comment by rijuoddusual1999** [comment]
> Pls try pnpm clean and pnpm i and if that doesn’t help, we’ll help you in Discord :)

Thanks a lot, Yes I switched to the discord server

**Comment by AliYar-Khan** [comment]
I would like to do it

**Comment by ShubhamPalriwala** [comment]
Hey @thevinitgupta any update on the PR? Let's get this shipped ASAP
