### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Page width issue of LP on mobile phones

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1186]
### Issue Summary

on mobile screen the whole UI is getting stick to left side after reloading

### Steps to Reproduce

1. Go to: https://formbricks.com/ on mobile phone
2. Reload the page

### Expected behavior

some elements are not responsive on mobile screen

### Screenshots

https://github.com/formbricks/formbricks/assets/84387676/a07f572e-59fe-420b-88b6-30be40492342

https://github.com/formbricks/formbricks/assets/84387676/e271570d-12e2-4e51-9048-6f9dbbf3743e

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Android 12
- Browser: chrome
```

**Comment by Bitnagar** [comment]
Hi @bilalmirza74 . I fixed similar issue on landing page. Components were overflowing in my case.

**Comment by jobenjada** [comment]
@bilalmirza74 pls find a pure Tailwind and look for the culprit instead of patching it over :)

**Comment by RonankiDinesh** [comment]
Lemme Do it

**Comment by Tooba-Amjad** [comment]
Let's do it

**Comment by NilanjanPramanik** [comment]
@bilalmirza74 con you working on it otherwise i want to...
