### ISSUE TITLE
[BUG]: whenever an update action is taken, the ui elements seem to scale way up for the loading phase

### ISSUE THREAD

**Issue by maverox** [formbricks/formbricks#1187]
### Issue Summary

Noticing a weird behaviour when trying to save changes in settings, where the ui elements seem to become really big for a moment.

### Steps to Reproduce

1. setup dev environment in gitpod 
2. go to settings
3.go to look and feel 
4. try to change the color and hit save 

### Expected behavior

this shouldn't happen, instead we should see a loading state on just the button.

### Screenshots

https://github.com/formbricks/formbricks/assets/29498864/d9812d01-fff6-4069-81c1-c075eeea70e7

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by vineetjk** [comment]
I would like to work on this.

**Comment by jobenjada** [comment]
Tbh I think its not really worth spending time on since it only happens on Gitpod - at least I dont see it on prod.

@maverox do you want to work on this anyways?

**Comment by tarunclub** [comment]
@jobenjada sure please assign that issue to me

**Comment by ShubhamPalriwala** [comment]
Hey @maverox any updates here? Else we can close this for now

**Comment by ShubhamPalriwala** [comment]
Since, we have not received any response! The next person who commented was @vineetjk, would you like to work on this? If not then we'll assign it to the next person. Please revert back at the earliest with a possible PR fixing this 🤞🏼

**Comment by ShubhamPalriwala** [comment]
Hey @Shyam-Raghuwanshi yeah I'll reassign this to you since there hasn't been much activity around this

**Comment by Shyam-Raghuwanshi** [comment]
Hi, @ShubhamPalriwala i see got the issue on gitpod when we send post request everytime a Get request done by gitpod name as layout.css or 
`https://3000-shyamraghuwa-formbricks-q4xk24gcv61.ws-us105.gitpod.io/_next/static/css/app/layout.css?v=1698336289095`
i don't know how can i disable this can you help me. This thing is only happend only when we using gitpod
more info
its load time approx  0.4s 
![image](https://github.com/formbricks/formbricks/assets/94217498/18f5f5ec-14a8-4d68-bd9d-0b7de0272209)
![image](https://github.com/formbricks/formbricks/assets/94217498/9e8b9c40-4468-4421-b120-5eeb3475f4d8)
![image](https://github.com/formbricks/formbricks/assets/94217498/2c198f01-2456-40e6-93f3-1fd08913ee0a)

**Comment by mattinannt** [comment]
As this only seems to be a nextjs dev server issue and not something we see in production I'm closing this for now.
