### ISSUE TITLE
[FEATURE]: Right align the nav text

### ISSUE THREAD

**Issue by NilanjanPramanik** [formbricks/formbricks#1191]
### Is your feature request related to a problem? Please describe.

In the mobile screen the nav text can be align and could be under a box button. This will enhance the look and UI
![image](https://github.com/formbricks/formbricks/assets/121485018/1c02c163-85ca-4054-9d3a-fa261660dc7d)

### Describe the solution you'd like

I am wanting to align them right and make a button box around them.

### Additional context

Can I work on this enhancement

**Comment by NilanjanPramanik** [comment]
I want to work this issue

**Comment by jobenjada** [comment]
hey! this isnt relevant for us, but thanks for checking Formbricks out :)
