### ISSUE TITLE
[BUG] Copyright year update required in footer of formbricks.com

### ISSUE THREAD

**Issue by tmsagarofficial** [formbricks/formbricks#1194]
### Issue Summary

I would like to point out that in the footer of the `formbricks.com`  which has **copyright year seems to be old.**

<img width="293" alt="image" src="https://github.com/formbricks/formbricks/assets/110724849/101aa7f7-e135-4ffc-bf27-ab6f24151a0c">
Hence a fix would be required.

### Steps to Reproduce

1.Go to `formbricks.com`
2. Scroll till the end of the website 
3. Note the footer at the bottom of the website as shown in the image below
4. 
<img width="293" alt="image" src="https://github.com/formbricks/formbricks/assets/110724849/40f0dc70-54f2-4e95-9ffb-476e2a2799b5">

### Expected behavior

It will be perfect if this year is updated with the year we are in.

### Screenshots

<img width="293" alt="image" src="https://github.com/formbricks/formbricks/assets/110724849/96e6c7d1-9790-4f0d-b10d-c78f3811bc76">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Win11
- Browser: Opera
- Version: LVL5 (core: 102.0.4880.90)
```

**Comment by gauravp-dev** [comment]
I would like to fix this issue. if possible please assign to me.

**Comment by nayakswadhin** [comment]
Please Assign this issue to me, I would like to work in this.

**Comment by jobenjada** [comment]
duplicate issue, already addressed in a pending PR :)
