### ISSUE TITLE
[BUG][50 Points] Scale up live demo button

### ISSUE THREAD

**Issue by singodiyashubham87** [formbricks/formbricks#1200]
### Issue Summary

When I hovered on the Live create survey button it scaled up but when hovered on the live demo button it didn't which creates an inconsistency in the web app, I want to add a scale-up effect on the live demo button too on hover.

### Steps to Reproduce

I will add the transition: scale() property to the live demo button

### Expected behavior

Scaling up of the live demo button like the create survey button

### Screenshots

![Screenshot from 2023-10-15 21-59-13](https://github.com/formbricks/formbricks/assets/93720428/4e7dd3fe-c851-4ae0-b7f3-c365f2342352)
![Screenshot from 2023-10-15 21-59-12](https://github.com/formbricks/formbricks/assets/93720428/6e817b68-0629-4f50-a1c9-2ca90be53761)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Linux
- Node:18.30
- npm: 9.2.0
```

Kindly assign me this issue.

**Comment by mrkirthi-24** [comment]
I would like to work on this issue

**Comment by avinashtare** [comment]
i will solve this issue

**Comment by Aadish1233** [comment]
i would like to work on it

**Comment by hemantmm** [comment]
Let's do it!

**Comment by jobenjada** [comment]
@singodiyashubham87 do you want to take this up? 

The difference is that one of them is variant="highlight" which comes with the scale animation.

Feel free to unify them in a PR.

**Comment by sohamtembhurne** [comment]
I am ready to work on this issue, you can assign it to me

**Comment by Aadish1233** [comment]
Lets do it

**Comment by Ahsankhalid618** [comment]
Let's do it

**Comment by jobenjada** [comment]
Its intentional, but thanks!
