### ISSUE TITLE
[BUG][FormTribe 🔥][150 Points] Pre-commit hook throwing errors

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1201]
### Issue Summary

Sometimes when pushing you see an error in the pre-commit hook:

<img width="890" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/c699b18e-36fd-4e97-9f41-8ea9542c2da6">

### Steps to Reproduce

hard to reproduce

### Expected behavior

just commit

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Aadish1233** [comment]
Could u please assign me this issue

**Comment by aniket-singh-01** [comment]
Hello jobenjada, Can you please assign this to me. I want to fix this.

**Comment by tarunclub** [comment]
I think there is some problem with linting, I got a prettier error while commiting my code.

<img width="654" alt="Screenshot 2023-10-16 002008" src="https://github.com/formbricks/formbricks/assets/102040059/bde01eee-70ef-4ee0-bf9c-fa238e2bab9f">
