### ISSUE TITLE
[BUG] 🚨 Loading resources Error while customising Survey fields

### ISSUE THREAD

**Issue by piyushgarg-dev** [formbricks/formbricks#1202]
### Issue Summary

When a user tries to create a form/survey from a template (Eg. Churn Survey) and tries to customize fields, the frontend throws the following error. 
```bash
Error loading resources
This resource doesn't exist or you don't have the necessary rights to access it.
```
Video Attached Below📹necessary

### Steps to Reproduce

1. Go to [https://app.formbricks.com/](https://app.formbricks.com/)
2. Create a new Survey
3. Choose the "Churn Survey" template for the survey. 
4. Wait for Survey to load and the editor to open up.
5. Try to edit Step number 3 "Get 30% OFF for the next year".

### Expected behavior

The Step should open and let the user customize the fields instead of throwing the error.

### Screenshots

https://github.com/formbricks/formbricks/assets/44976328/55527235-66b7-439e-b822-0fac1e836cd4

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: MacOS 14.0
- Node: Not Required
- npm: Not Required
```

**Comment by adityadeshlahre** [comment]
Would like to get it assigned ! 
thank you :smile:

**Comment by piyushgarg-dev** [comment]
I guess this is due to IDs being hardcoded here. Replacing this with `id: createId()` could solve this issue.
https://github.com/formbricks/formbricks/blob/accd977ddcafee5cd527e924f33e408768c17d5d/apps/web/app/(app)/environments/%5BenvironmentId%5D/surveys/templates/templates.ts#L269

**Comment by adityadeshlahre** [comment]
Hey @piyushgarg-dev 
this error seems like this in localhost !

https://www.loom.com/share/226b6d699dbe4f7490f939c98bc2117e?sid=6cd3f587-8b8f-4c19-b6fb-c25ed17cfa1b

**Comment by jobenjada** [comment]
@ShubhamPalriwala please have a look, its related to what you've worked on last week 🤓

**Comment by ShubhamPalriwala** [comment]
Update: Was not able to reproduce this locally! Need to keep an eye on this
