### ISSUE TITLE
[Enhancement] After Clicking Best Practices if we hover to it, then its not looking good, also Arrow and text color mismatch

### ISSUE THREAD

**Issue by 3xp10it3r** [formbricks/formbricks#1213]
### Issue Summary

- After Clicking Best Practices if we hover to it, then its not looking good
- Arrow and text color mismatch

### Steps to Reproduce

1. Open Formbricks.com
2. Clicked on Best Practices in Navbar
3. Hover Best Practices text

### Expected behavior

Hover should not work when opened, it should be colored to look like selected

### Screenshots

Current : 
    https://github.com/formbricks/formbricks/assets/65729055/830cc5c4-0f73-4838-89f8-12e4b238e93b
   
Expected (Suggestion) : 
     https://github.com/formbricks/formbricks/assets/65729055/8bf17092-9bb6-4a90-9605-cd554cddd8a6

 

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: MacOS, Windows
- Node:
- npm:
```

**Comment by 3xp10it3r** [comment]
If the issue gets approved, would love to work.

**Comment by jobenjada** [comment]
@3xp10it3r Our landing page isnt really the interesting part of our repo :) Please spend more time in our actual product at app.formbricks.com - we are really thankful for any issues detected there! 🙏

**Comment by ItZmEkAtHiR** [comment]
Hi @jobenjada ,
Can i work on this ?

**Comment by Himanshu-Dhawale** [comment]
Can I work on this issue?

**Comment by jobenjada** [comment]
closing this, not relevant enough to justify the overhead 🙏 

Please focus on the core product or docs
