### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Page not found in Actions and Attribute's  attribute settings

### ISSUE THREAD

**Issue by 3xp10it3r** [formbricks/formbricks#1217]
### Issue Summary

On click Read Docs leading to wrong url which shows page not found.
https://formbricks.com/docs/getting-started/identify-users this url doesn't exists.

### Steps to Reproduce

1. Open app.formbricks.com.
2. Click actions and attributes
3. Click attributes tab
4. Click on any attribute (email or userid)
5. Click on settings tab
6. Click on Read docs button

### Expected behavior

It should redirect to "https://formbricks.com/docs/attributes/identify-users" , it exists.

### Screenshots

<img width="1456" alt="Screenshot 2023-10-16 at 5 08 38 PM" src="https://github.com/formbricks/formbricks/assets/65729055/3a8f2485-a4ad-45a9-9834-e418dc2aab53">

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows, MacOS
- Node:
- npm:
```

**Comment by 3xp10it3r** [comment]
Would like to fix.

**Comment by jobenjada** [comment]
Go for it :)
