### ISSUE TITLE
[BUG]The Navbar options  in Formbricks Demo doesnot   opens new link or page

### ISSUE THREAD

**Issue by Aadish1233** [formbricks/formbricks#1218]
### Issue Summary

If you try to click the navbar  options in Formbricks Demo they donot work

### Steps to Reproduce

1. Go to https://formbricks.com/demo
2. Click on any Navbar options
4. The buttons dont work

### Expected behavior

On clicking the button new link or page should open

### Screenshots

Current:

https://github.com/formbricks/formbricks/assets/120332757/390e7185-3aeb-4270-9332-6bfc69028920

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Windows, MacOS
- Node:
- npm:
```

**Comment by Aadish1233** [comment]
I would like to fix this

**Comment by NilanjanPramanik** [comment]
I am working on it

**Comment by Aadish1233** [comment]
Hey @jobenjada  can  u please consider this issue

**Comment by ShubhamPalriwala** [comment]
Hey, the navbar is supposed to not be there in the first place! We'll award you +50 points for catching the bug! However, we'll fix it up ourselves quickly.
