### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Landing page UI styles is not correct in dark mode

### ISSUE THREAD

**Issue by vineetjk** [formbricks/formbricks#1219]
### Issue Summary

In the landing page example for step 4:  Set segment and trigger UI is not proper in dark mode. Light theme border is shown around the dropdown.
![image](https://github.com/formbricks/formbricks/assets/42497152/1f1c32cc-681d-4ca3-bef0-abae04c63382)

in the same UI the alignment is not correct
![image](https://github.com/formbricks/formbricks/assets/42497152/d90bcd06-ebc9-4227-ac1b-f0bc2b7b827d)

### Steps to Reproduce

1. Open https://formbricks.com/
2. Toggle dark mode
3. Scroll down to Step4: Set segment and trigger
4. Try to add Events

### Expected behavior

1. In dark theme the border of the dropdown should not be in light theme. 
2. Alignment should be correct

### Other information

- I would like to work on this.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by SmitDasadia** [comment]
can you assign to me this issue?

**Comment by vineetjk** [comment]
> can you assign to me this issue?

I am working on that :)

**Comment by ShubhamPalriwala** [comment]
Hey @vineetjk thanks for finding out the bug! Assigning it to you for atleast the next 24 hours. Please ping when the PR is ready so we can merge it soon.

**Comment by vineetjk** [comment]
Hey @ShubhamPalriwala , 
PR is ready
