### ISSUE TITLE
[BUG][FormTribe 🔥][100 Points] Unable to Update & Delete Product

### ISSUE THREAD

**Issue by 3xp10it3r** [formbricks/formbricks#1224]
### Issue Summary

Products setting try to update product name, it will not update shows error in console but shows in toast that it is updated, try multiple times it gets updated but in nav bar product name still be older one,
same for the recontact waiting time,
also cant delete a product.

### Steps to Reproduce

1. Go to app.formbricks.com
2. Clicked on settings
3. click on product settings
4. try to update product name or recontact waiting time, or try to delete the product.

### Expected behavior

Should be able update the product name and recontact time with loading buttons.
product name should be same in navbar (profile section),
delete product should work.

### Screenshots

https://github.com/formbricks/formbricks/assets/65729055/83a392f7-cc41-4e29-bb6f-973743c66049

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows, MacOS
- Node:
- npm:
```

**Comment by 3xp10it3r** [comment]
would love to try and fix.

**Comment by ShubhamPalriwala** [comment]
Hey @3xp10it3r, +100 points for finding a critical bug! +100 points for fixing it as well! Let me know if you need any help with this, we would like to close this at the earliest.

**Comment by 3xp10it3r** [comment]
Working on it. @ShubhamPalriwala

**Comment by 3xp10it3r** [comment]
Please check, I have raised the PR #1260 , It fixes the issue. @ShubhamPalriwala
