### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Typo on Main page

### ISSUE THREAD

**Issue by vedant-z** [formbricks/formbricks#1231]
### Issue Summary

The apostrophe in **Dont'** is wrongly placed.

![image](https://github.com/formbricks/formbricks/assets/93431609/4e22efde-daaa-4179-b350-c0b81b35c974)

### Steps to Reproduce

Navigate to home page of Formbricks.

### Expected behavior

**Dont'** should be corrected to **Don't**

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/93431609/5f908d83-f642-476f-9c27-9b69aacef3eb)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: chrome
```

**Comment by Yashgupta9330** [comment]
i want to wor on it pls assign it to me

**Comment by vedant-z** [comment]
@ShubhamPalriwala Can't this issue be assigned to me? I created the issue but looks like two PRs were merged related to this issue even when they were not assigned. Previously the same thing happened I opened a issue and you assigned me but it was already fixed so my PR was closed.

I am not getting any issue to contribute as all beginner friendly issues are already taken. Sorry if I am misunderstanding something here.

**Comment by ShubhamPalriwala** [comment]
Hey @vedant-z, we do have 3 open PRs for the same, however **none** of them is merged in our repository! You can still open a PR and we will prioritise for you to open and get it merged since you found the issue for the first 24 hours! You still have around 8 hours to open a PR for the same. If you are unable to open, only then will we look at other PRs

Looking forward to your PR 🚀

**Comment by vedant-z** [comment]
@ShubhamPalriwala Thanks for understanding my concern. But is it allowed to make a PR even if I am not assigned as I thought that only after I am assigned an issue I am allowed to make PR.

If that is the case then I won't wait for being assigned from next time.

Btw I made a PR to fix the above issue.

Thanks :)

**Comment by ShubhamPalriwala** [comment]
If its a tiny issue like this, you can open an issue and a PR at the same time without being assigned! But if its a bigger feature that would require considerable time and effort, its better to confirm by getting assigned to make sure that the efforts do not go null. Thanks for the quick PR, will take a look 🚀
