### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] web: dropdown menu not accessible from keyboard.

### ISSUE THREAD

**Issue by Bitnagar** [formbricks/formbricks#1234]
### Issue Summary

Right now we can't access dropdown menu in the survey dashboard. See below:

https://github.com/formbricks/formbricks/assets/88842947/b39bb092-59e7-4256-bec3-bb17e9bbfdcf

### Steps to Reproduce

- Login and go your surveys.
- Try to access the drop down menu with your keyboard.
- Observe that we can't access it.

### Expected behavior

It should be accessible from the keyboard as well. Shown below:

https://github.com/formbricks/formbricks/assets/88842947/2d48048c-ea69-40c1-88ac-1cf65c47de5b

### Other information

@mattinannt @jobenjada If the team considers this. I can raise a PR. Thank you.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows Latest
- Node:
- npm:
```

**Comment by Bitnagar** [comment]
@mattinannt @jobenjada If the team considers this. I can raise a PR. Thank you.

**Comment by ShubhamPalriwala** [comment]
Hey, thanks a lot for opening the issue! This adds accessibility so definitely a great addition! +50 points for suggesting and building the feature!
