### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Concierge Kick Off Call Card Not aligned properly on resize

### ISSUE THREAD

**Issue by ratishjain12** [formbricks/formbricks#1238]
### Issue Summary

Currently this is not looking nice 
![image](https://github.com/formbricks/formbricks/assets/43003421/e910e9eb-8b1f-4f24-b210-9ef355c2c232)

I want to fix this by proper alignment and margins @jobenjada 

### Steps to Reproduce

-

### Expected behavior

Alignment should be proper with margin

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by DarshanBorse** [comment]
I'm ready to work on the issue; please assign it to me.

**Comment by ShubhamPalriwala** [comment]
@ratishjain12 thanks for finding the bug! +50 points for both finding and fixing it! Assigning it to you for the next 24 hours and request you to open a PR in the same duration. If not, then we'll open it up for other interested contributors 💯

**Comment by ratishjain12** [comment]
> @ratishjain12 thanks for finding the bug! +50 points for both finding and fixing it! Assigning it to you for the next 24 hours and request you to open a PR in the same duration. If not, then we'll open it up for other interested contributors 💯 

On it @ShubhamPalriwala

**Comment by NilanjanPramanik** [comment]
Hay can i work on this issue
