### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Formbricks logo in Dark mode

### ISSUE THREAD

**Issue by JanumalaAkhilendra** [formbricks/formbricks#1249]
### Issue Summary

For the Dark Theme, The FormTribe Logo is merged with the background, it seems as if it is not there.
![Screenshot 2023-10-17 122057](https://github.com/formbricks/formbricks/assets/82641474/dd66d65c-fb98-43b9-bb6c-91fc1ee7c2e0)

For the Light Theme, It is working fine.
![Screenshot 2023-10-17 122131](https://github.com/formbricks/formbricks/assets/82641474/5678ffcc-db3b-4d0a-958a-78da4ba4befe)

### Steps to Reproduce

1. If you are using Chrome, set it to Dark Mode 
2. Go to https://formbricks.com/demo
3. On the top left corner Observe the Logo.

### Expected behavior

For the Dark Mode, The FormTribe Logo Should be replaced with a Logo of a light theme Color, then it will be visible on the website.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [x] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: Chrome
```

**Comment by JanumalaAkhilendra** [comment]
Can I Work on this Issue?

**Comment by mayurphumatiya** [comment]
Hey! Would love to take this on.

**Comment by ShubhamPalriwala** [comment]
Hey @JanumalaAkhilendra, thanks for finding the bug! +50 points for finding as well as fixing it! Assigning it to you for the next 24 hours. Looking forward to the PR
