### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Add action UI issue on mobile screen

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1254]
### Issue Summary

1. Add Action not aligned in the center 

2. URL field got overlap 

3. Page URL button tick design  issue

### Steps to Reproduce

1.  https://formbricks.com/ on mobile phone device
2.  go to No-Code: Track User Action (section)
3.  click on Add Action

### Expected behavior

.

### Other information

.

### Screenshots

![a](https://github.com/formbricks/formbricks/assets/84387676/219ab6e2-5104-46a3-8281-d9333691b4ee)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Android 
- Browser: chrome
```

**Comment by PiyushXmishra** [comment]
@ShubhamPalriwala @bilalmirza74  
 Formbricks is not supported in smaller resolution devices. 
![image](https://github.com/formbricks/formbricks/assets/110087602/d426b5d8-923e-4f42-88f2-dcb364893a74)

So how can we reproduce this issue?

**Comment by jobenjada** [comment]
It's on the landing page
