### ISSUE TITLE
[BUG] side panel in the app.formbricks -> setting is not scrollable.

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1255]
### Issue Summary

app.formbricks setting side panel is not scrollable 

### Steps to Reproduce

1. Go to: https://app.formbricks.com/
2. Clicked on: settings
3. minimize the window 50% vertically 

### Expected behavior

.

### Other information

.

### Screenshots

https://github.com/formbricks/formbricks/assets/84387676/8bd85778-a65b-4d1a-93fd-6c0124b5c555

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Browser: chrome, edge, firefox
```

**Comment by gauravp-dev** [comment]
Would like to fix this💪

**Comment by priyanshu2k3** [comment]
hey i have solved it just need some idea how to raise the pr

**Comment by priyanshu2k3** [comment]
hey i have raised the pr  @bilalmirza74 thanks for the video

**Comment by priyanshu2k3** [comment]
@bilalmirza74  how to reopen then ??

**Comment by jobenjada** [comment]
This is a duplicate issue to this: https://github.com/formbricks/formbricks/issues/1190

Closing this :)
