### ISSUE TITLE
[FEATURE][FormTribe 🔥][750 Points] Question Type: Picture Choice

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1256]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Is your feature request related to a problem? Please describe.

Users want to let their respondents pick 1 of several images

### Describe the solution you'd like

Offer the corresponding question type:

<img width="686" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/e1ff0a68-af85-4a29-b5dc-06666bec7da5">

Note: This mockup is stemming from our upcoming UI revamp. The UI you will build should match the current look of our surveys 🤓

### Tasks

1. Create a new question type called "Picture Selection" with HeroIcon "Photo"
<img width="570" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/687673ce-223b-478e-98dc-4df69f3f9921">

2. Create the corresponding question settings card with the following settings. We do have a reusable component for the file upload UI being used in the Welcome Card:

<img width="739" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/460b4589-b3a4-4f47-a4a5-f063d2833bea">
<img width="741" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/289ad689-4765-4058-b9e8-78c69dd5402d">

The Allow Multi Select toggle switches the type from a Radio button functionality (pick one) to a Checkbox functionality (pick many). **Please have a look at the question types Single and Multi Select, you will be able to adopt most of the logic from there.**

3. Create a UI to display the results in the Survey Summary: 
<img width="740" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/cd678e82-58d5-42f7-a1e4-b8122df74bac">

4. Create a UI to display the results in the Response Card: Its pretty straightforward, just do it consistent with the others responses 😃 

5. Test extensively in:
- Survey editor preview
- Link Surveys
- Web app surveys

**Comment by gupta-piyush19** [comment]
Hey! looks interesting!!
 can i work on this?

**Comment by jobenjada** [comment]
Sure thing, give it a go 🚀

**Comment by ShubhamPalriwala** [comment]
Hey @gupta-piyush19 any updates on this? Could you help with your progress here please

**Comment by gupta-piyush19** [comment]
Hi @ShubhamPalriwala, Apologies for the delay, I've made significant progress on this issue and will be shipping this soon. creating a draft PR.

**Comment by gupta-piyush19** [comment]
Hey! @jobenjada, I've pushed the complete feature. Can you please assign someone to review this?
