### ISSUE TITLE
[FEATURE][FormTribe 🔥][1000 Points] Question Type: File Upload

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1257]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Is your feature request related to a problem? Please describe.

Users want to enable respondents to upload files

### Describe the solution you'd like

Add question type "File Upload".

### Tasks

1. Add a new question type called File Upload with Hero Icon "ArrowUpTray": 
<img width="710" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/1ef0dcda-e2e8-4847-870c-54f32165168a">

 The file type has the following settings:
<img width="757" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/6609fd3f-0dc0-4629-a1a8-dd7543c1f5d7">

The UI component for the toggle + card can be taken from the Survey Settings page

The Combobox component can be taken from the Filter:

<img width="500" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/e161422f-20d9-4735-bdce-3e2e259c50ae">

2. Add a new component to the survey package to display file upload questions in surveys. The following mockups don't have to be rebuilt pixel-perfect, the font-size, colors etc are predetermined in the survey package - please stick to those:

<img width="473" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/cba9063d-eee1-4aaf-adab-4e5e42066035">

3. Add logic: This new question type requires specific logic rules:

- Is empty
- Is not empty

Since this is binary, you can look at the logic rules for question type Consent. Make sure to adjust the logic options dependent on the Required toggle. If question is required, it should not be possible to select "Is empty" for a logic rule.

4. Test extensively :)

If you run into questions, please reach out to @pandeymangg on Discord - he is our Upload Guy 😎 

### Thanks!

**Comment by KapadiaNaitik** [comment]
Can I work on this ?

**Comment by ameeetgaikwad** [comment]
Would like to work on this.

**Comment by vineetjk** [comment]
I would like to work on this..

**Comment by jobenjada** [comment]
Quick one, go for it @KapadiaNaitik  !
