### ISSUE TITLE
[FEATURE][FormTribe 🔥][750 Points] Add Image to every question

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1258]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Is your feature request related to a problem? Please describe.

Users want to add images and videos to have a richer context.

### Describe the solution you'd like

Allow adding images to every question (video will follow).

### Note
This PR will touch a lot of files because you have to embed the image adding and displaying functionality for almost every question type.

**Please only do it for 1 question type at first, ship it and get it approved! Otherwise you will have to deal with a loooot of merge conflicts all the time :)**

### Tasks

1. At the end of the question input field, add Lucide icon 'image-plus'
<img width="747" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/68a97cca-5c1f-4fc4-9a2a-53896d135997">

Note: This can be a bit hacky for now, placing it there with absolute positioning. We are rewriting the question input field into a custom component for the Recall information functionality anyways. So we will refactor this anyways :)

------

2. On click, it adds this upload window above the question input field: 
<img width="1015" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/9c56f75d-1aad-4056-97d0-195d03761bba">

------

3. On drag (or click) the native file manager of the client opens and the user can add an image. Please reuse the File Upload component used in the Welcome Card 🙏

------

4. When the image is added, it looks like this:
<img width="738" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/d67a363a-49c4-4eb7-bc79-7989d4af3dd1">

------

5. Create a new reusable component to update the question types in the survey editor to display the images:

**Link survey:**
<img width="855" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/a3dabe3c-094b-4f42-b034-f7e0da3df577">

**In app survey:**
<img width="411" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/1557b771-01df-421d-b184-22cc705ae089">

------

If question come up, please reach out in Discord! :)

### Thanks!

**Comment by anjy7** [comment]
I would like to take this one

**Comment by jobenjada** [comment]
Its yours! @anjy7 :)

**Comment by anjy7** [comment]
Hi @mukulpythondev, welcome to the community 😄. Appreciate your enthusiasm. I would request you to go through the contributing guidelines and join the discord 🤓. I’m sure soon their would be new issues that you would get a chance to work on 🚀

**Comment by Aadish1233** [comment]
can i contribute to this issue
