### ISSUE TITLE
Unable to view responses for a form

### ISSUE THREAD

**Issue by deepjyoti30** [formbricks/formbricks#126]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I created a form using the app and published it. I have 3 responses as of now, for the form, based on what I can see from the network response but I am unable to view the responses for the form as of now.

I get the following error:

<img width="1414" alt="Screenshot 2022-10-29 at 5 35 33 PM" src="https://user-images.githubusercontent.com/33604454/198830436-565a62a6-6a7e-4604-b970-1dd9093de895.png">

 

### Steps to Reproduce

Steps I did:

- Created the form
- Published it and shared it
- Got a few responses
- Went to check responses (faced the issue)

## Environment

- [x] snoopForms Cloud (app.snoopforms.com)
- [ ] self-hosted snoopForms, version/commit: [please provide]

**Comment by mattinannt** [comment]
@deepjyoti30 Sorry for the problems you are facing. We found a bug in the data handling that is now fixed. Could you please make another submission and check if that also solved your issue?
