### ISSUE TITLE
[BUG]:  Gitpod web initiation fails

### ISSUE THREAD

**Issue by anjy7** [formbricks/formbricks#1262]
### Issue Summary

env.mjs has validation for ENCRYPTION_KEY to be of length 32 but .env.example says that it should be of length 24

### Steps to Reproduce

1.Open formbricks with gitpod ( issue should be same in local dev setup as well )

### Expected behavior

example .env should specify the correct length

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/92802904/257634ef-0995-45ed-8cc6-3c37f71a3126)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by ShubhamPalriwala** [comment]
Hey, I just tried locally with the 24 key length and it worked locally! Did you verify your key length?

**Comment by anjy7** [comment]
> Hey, I just tried locally with the 24 key length and it worked locally! Did you verify your key length?

yeah my bad, it failed for some reason with the above error once then when I ran it again, it started working @ShubhamPalriwala
