### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Logo is not visible in edge search

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1265]
### Issue Summary

The logo cannot be seen when searching using the Microsoft Edge browser search results.

### Steps to Reproduce

1.  open: Microsoft Edge browser
2.  search formbricks

### Expected behavior

.

### Other information

.

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/84387676/aaa4022e-ebc8-4255-875b-8fe22e8ee038)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Browser: Microsoft Edge
```

**Comment by hemantsinghhere** [comment]
please assign me this. i have already started working on it.

**Comment by jobenjada** [comment]
Wanna open a PR at Edge Search to fix this? :D 

jokes aside, curious to see your solution @bilalmirza74

**Comment by myselfprincee** [comment]
Hey, @bilalmirza74 I am new to Coding, would you like to assign it to me, It will help me in getting into open source :)
