### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Request for Improved User Experience: Simplify Theme Selection with Toggle Button

### ISSUE THREAD

**Issue by moheyt** [formbricks/formbricks#1267]
### Issue Summary

Please bring attention to an issue in application's user experience that I believe could greatly benefit from an improvement. Currently, users are presented with a dropdown menu to select their preferred theme, which includes options for "Light," "Dark," and "System (Default)" themes. While providing theme customization is essential, we believe there is room for enhancement in how we offer this choice.

Reasons for the Change:

1. Streamlined User Experience: A toggle button is an intuitive way for users to switch between light and dark themes quickly without navigating through a dropdown menu. It simplifies the process, making it more user-friendly.

2. Aesthetic Consistency: Toggle buttons have become a standard design element in many modern applications and websites. Transitioning to a toggle button will provide a more consistent and visually appealing user interface.

3. Improved Accessibility: A toggle button is more accessible for all users, including those with disabilities. It offers a clear and straightforward method of theme selection.

4. Alignment with User Preferences: Users often prefer having only the option to choose between light and dark themes, as "System (Default)" may not always align with their preferences. Providing a toggle for light and dark themes respects user choice.

I would like to fix this. Please assign me. #Hacktoberfest

![Screenshot 2023-10-17 194721](https://github.com/formbricks/formbricks/assets/85775976/67985baa-2a62-4377-a33c-a38d80927057)

### Steps to Reproduce

1. Go to formbricks.com

### Expected behavior

I propose simplifying the theme selection process by replacing the existing dropdown menu with a toggle button for "Light" and "Dark" themes. This adjustment will not only make the user experience more intuitive but also align with contemporary design trends and user expectations.

Benefits:

1. Enhanced User Experience: Users will find it easier to customize their experience with our application.
2. Improved User Satisfaction: By accommodating user preferences and expectations, we can enhance overall user satisfaction.
3. Consistency and Accessibility: The updated design will adhere to best practices and make our application more accessible to a wider audience.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Browser: Chrome
```

**Comment by chaturrved** [comment]
I would like to work on this.

**Comment by jobenjada** [comment]
I agree this could be better: Default is system and then they can change it with the toggle.

Please test extensively though also changing your system mode to see if your toggle reacts accordingly. Also, the FormTribe page is only available in light mode.

**Comment by jobenjada** [comment]
On a side note: Please spend more time in our actual product than the landing page 🙏  we have bugs there as well and finding them is of bigger help and will lead to more points :)

**Comment by moheyt** [comment]
sure @jobenjada 🫡

**Comment by NilanjanPramanik** [comment]
Hey @moheyt  do you working on this issue if not I want to work

**Comment by moheyt** [comment]
on it @NilanjanPramanik just working on default system mode.
