### ISSUE TITLE
[BUG] dark, light theam switching issue

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1268]
### Issue Summary

Whenever I set my theme to dark and visit https://formbricks.com/formtribe, which only has a light theme, my theme does not switch back to dark when I return to the home page.

### Steps to Reproduce

1. go to: https://formbricks.com/
2.  set theam: dark
3.  go to: https://formbricks.com/formtribe
4.  get back: https://formbricks.com/

### Expected behavior

.

### Other information

.

### Screenshots

https://github.com/formbricks/formbricks/assets/84387676/c37ca72a-ad44-45cd-a107-0119822b6ec2

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Browser: chrome, edge
```

**Comment by rjangid9080** [comment]
Please assign this to me

**Comment by Aadish1233** [comment]
please assign me this task

**Comment by jobenjada** [comment]
its known and not an issue working on :)
