### ISSUE TITLE
[FEATURE] Rework responsiveness of menu for small screens

### ISSUE THREAD

**Issue by shrikantpardhi** [formbricks/formbricks#1270]
### Is your feature request related to a problem? Please describe.

I have created a survey. Once I open the survey responses, there must be a back button so I can navigate to survey  lists screen. 

### Describe the solution you'd like

Add a  button to Navigate to survey list screen.

Expected a back button in given screen.

![image](https://github.com/formbricks/formbricks/assets/26996069/c06b31b0-7d7e-40a3-877c-164d2e415787)

Expected screen after click on Back button.

![image](https://github.com/formbricks/formbricks/assets/26996069/15bd9e21-7f61-469e-8efa-aeef31fe7547)

**Comment by mrkirthi-24** [comment]
I would like to work on this issue

**Comment by mattinannt** [comment]
<img width="1533" alt="Screenshot 2023-10-17 at 18 26 23" src="https://github.com/formbricks/formbricks/assets/675065/4e97201e-6de1-4ad2-8ee4-d62d59f179ca">
<img width="971" alt="Screenshot 2023-10-17 at 18 26 50" src="https://github.com/formbricks/formbricks/assets/675065/f05c9be7-d0de-4751-b139-bbb91fa566b9">

@shrikantpardhi I think your screen resolution is so low that the navigation went behind the burger menu.
Would it have helped you if you would have seen the navigation as it is on the first screenshot?

**Comment by jobenjada** [comment]
Played around with responsiveness and its good enough :) The switch to the dropdown couldn't happen later otherwise the top bar breaks. Closing it
