### ISSUE TITLE
[FEATURE][FormTribe 🔥][50 Points] In preview survey while selecting an option for a question, it is better the next button should be change color to #14a3b8

### ISSUE THREAD

**Issue by meakashdash** [formbricks/formbricks#1275]
### Is your feature request related to a problem? Please describe.

No, its a UI advancement.

### Describe the solution you'd like

open formbricks.com and go to the live demo section. In the preview survey questions, after selecting an option for a question. The next button should change color.

![image](https://github.com/formbricks/formbricks/assets/78552411/e4f7da68-e8ee-4ab4-af58-35f5f421b44e)

**Comment by meakashdash** [comment]
I would like to work on this issue.:)

**Comment by jobenjada** [comment]
Have a go at it @meakashdash :)

**Comment by ShubhamPalriwala** [comment]
Hey @meakashdash since you havn't opened a PR for the issue, we'll now assign it to @venk404! Remember, you have 24 hours to open the PR 🚀

**Comment by venk404** [comment]
@ShubhamPalriwala Can I raise PR for this issue.

**Comment by meakashdash** [comment]
Hey @ShubhamPalriwala. I have opened a PR for this issue last night.

**Comment by mattinannt** [comment]
Since this issue is an nice to have and haven't been successfully solved by now, I will close this for now.
