### ISSUE TITLE
[FEATURE][FormTribe 🔥][250 Points] Group Events of same type in event timeline

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1282]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Is your feature request related to a problem? Please describe.

As a user, I want to have an overview of the events tracked in the Acivity Timeline on the Person Detail page. The Exit Intent event spams the timeline.

### Describe the solution you'd like

If the same event is fired repeatedly, group it and display a count indicator instead:

<img width="802" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/e97c4169-7916-4406-a4fb-0c96c6ac9a27">

### Tasks

1. If 3 or more events are of the same type, group them
2. Show a count indicator
3. Show the timeSince of the most recent event recorded

### Note
We do have an open PR for it, it's almost done actually - quick and easy points ;)

https://github.com/formbricks/formbricks/pull/731

Please go through the comments in the PR carefully 🤓

**Comment by Dhoni77** [comment]
Hi @jobenjada I would like to work on this

**Comment by mittalsam98** [comment]
Hey, if @Dhoni77 is not working on this, I would like to pick this up

**Comment by Dhoni77** [comment]
Hi @mittalsam98  I am working on it

**Comment by mattinannt** [comment]
Closing this as based on performance issues we needed to take a different approach where we load fewer actions in the person detail view.
