### ISSUE TITLE
[BUG][FormTribe 🔥][150 Points] Data is not being sent webhook api on trigger

### ISSUE THREAD

**Issue by HananMehmood5** [formbricks/formbricks#1285]
### Issue Summary

Currently, we are able to trigger webhook api but we are not sending any survey data with it. There are possible use cases where we want pipeline our data from formbricks to other source but we are unable to do it as data is not send along with request.

### Steps to Reproduce

1. Create a survey
2. Create a POST API endpoint
3. Set this POST API endpoint as a webhook and select the new survey
4. Now publish the form and fill it through a link
5. Webhook API is triggered but no data is sent with it

### Expected behavior

There should be data in the request to webhook API

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: MacOS
- Node: lts/hydrogen
- npm: lts/hydrogen
```

**Comment by jobenjada** [comment]
Up for grabs, if anyone wants :) @rohan9896 you were looking right?

**Comment by rohan9896** [comment]
@jobenjada Yes. Please assign it to me!

**Comment by United1l** [comment]
I go next in case @rohan9896 isn't able to create a PR.

**Comment by rohan9896** [comment]
@United1l Fixed the issue! Raising PR in a few minutes.

**Comment by United1l** [comment]
@rohan9896 🙌🏽 Excellent bro.

**Comment by HananMehmood5** [comment]
@ShubhamPalriwala I can see that there is still issue on Docker image that i download. Can you share when will be docker image updated?
