### ISSUE TITLE
[BUG] correct use of <label for=FORM_ELEMENT>

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1286]
### Issue Summary

The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.

### Steps to Reproduce

1. Go to: https://formbricks.com/
2. scroll down:  Step 3 Create your survey
3. open console

### Expected behavior

.

### Other information

To fix this issue, make sure the label's for attribute references the correct id of a form field

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/84387676/fd211e96-9548-4df4-8c24-737060bd04f6)

![image](https://github.com/formbricks/formbricks/assets/84387676/ba41d605-3839-4b61-a6aa-f2f49dff687d)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Browser: chrome
```

**Comment by jobenjada** [comment]
@bilalmirza74 this is alright! But if you want to work on a bigger issue (250 Points) you could replace the hacked together solution on the Demo page with our Survey Package in `packages/surveys`

Are you up for this? Happy to write it up for you

**Comment by mittalsam98** [comment]
@jobenjada can you explain the issue more bit, I would like to take it up

**Comment by Prashant04627** [comment]
Can i work on this issue?

**Comment by sujithyadav998** [comment]
Can You assign this to me ?
