### ISSUE TITLE
[BUG][FormTribe 🔥][200 Points] Disabling Welcome Card & Thank You card leads to buggy preview

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1289]
### Issue Summary

When you currently inspect the Welcome Card and then disable it, the Preview should jump to the first question of the survey instead of showing an empty card:

<img width="1412" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/121fc989-5290-4c13-b2c5-e86093b597c3">

### Steps to Reproduce

1. Enable Welcome Card
2. Clicked on it to preview it
3. Disable it via Toggle

### Expected behavior

Jump to first question

**Comment by HarshitVashisht11** [comment]
i can fix this issue, pls assign this issue to me

**Comment by gauravp-dev** [comment]
If possible, please assign it to me i want to fix this issue.

**Comment by priyanshu2k3** [comment]
i would like to work on this

**Comment by varundhand** [comment]
@jobenjada I'd like to work on this issue, please assign it to me.

**Comment by NilanjanPramanik** [comment]
Hey i want to work on this issue

**Comment by lalitkumawat1m** [comment]
I want to work on this issue please assign to me

**Comment by MeenuyD** [comment]
Hello @jobenjada I would like to work on this issue can you please assign it to me

**Comment by JaspalSingh1998** [comment]
Hi there, I would like to work on this issue. Could you please assign it to me?

**Comment by sundaram2021** [comment]
so you are saying 
this should be 
![image](https://github.com/formbricks/formbricks/assets/93595231/4f8fbd78-ed78-4ab1-98ae-ddc56f931a62)

changed to this when disabled
![image](https://github.com/formbricks/formbricks/assets/93595231/0b87a6ef-e1ca-44d4-85d8-09293041c71d)

Right ??

If that's right then I would like to add on that 
the welcome section should be closed automaitcally after disabling it
and the question section should be opened in place of that and their preview should be displayed 

I will be more than happy to work on this issue

Thanks.

**Comment by jobenjada** [comment]
@HarshitVashisht11 you were the first :) Please check @sundaram2021 comment, it contains all further info you need :)
