### ISSUE TITLE
[BUG] During Processing, The Button Text Doesn't get Hidden, And Shows both Button TEXT and Loading Animation

### ISSUE THREAD

**Issue by myselfprincee** [formbricks/formbricks#1292]
### Issue Summary

<img width="121" alt="image" src="https://github.com/formbricks/formbricks/assets/114233864/ddc33a3d-58e3-4832-be71-792df23635ba">

I just went to make an account, and Found this issue 

Here is the Video 👇

https://github.com/formbricks/formbricks/assets/114233864/775976e2-c1e8-4b62-8167-d16783360605

### Steps to Reproduce

1. Go to https://app.formbricks.com/onboarding
2. Click on **Next** 

### Expected behavior

It can be fixed by hiding the written Text, when the Loading Animation appears. It will not be too hard to solve.

### Screenshots

<img width="121" alt="image" src="https://github.com/formbricks/formbricks/assets/114233864/30390837-5a1a-4755-bd9d-bd3aa9e9bc20">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Browser: Chrome Regular Version
```

**Comment by Bitnagar** [comment]
Hey @myselfprincee, That loading state is intentional! Read this: https://github.com/formbricks/formbricks/issues/1148#issuecomment-1762888355
Duplicate of #1148

**Comment by myselfprincee** [comment]
@Bitnagar  Thank you so much. **I am closing this issue.**

**Comment by myselfprincee** [comment]
@Bitnagar Thank you so much. **I am closing this issue.**
