### ISSUE TITLE
[FEATURE] Question Type: Question Array/Group

### ISSUE THREAD

**Issue by HananMehmood5** [formbricks/formbricks#1293]
### Is your feature request related to a problem? Please describe.

There are some use cases:

- Enter your references
- Enter your skills
- Enter Work History

Above all requires a dynamic number of fields to give an answer 

### Describe the solution you'd like

- There would be 1 question:
- The answer would be a group of 1 or more fields having text-related inputs
- There will be a plus button
- Clicking on plus will create the same group as above but with the empty fields

### Describe alternatives you've considered

It has multiple fields in the same hierarchy following the current structure but it is not efficient and not a good experience.

**Comment by mrkirthi-24** [comment]
I would like to work on this issue

**Comment by tbleiker** [comment]
I am looking for a survey platform which allows this. For brainstorming, a user should bei able to give multiple answers/ideas per question. Any plan to provide this feature in the near gute?
