### ISSUE TITLE
[BUG][FormTribe 🔥][100 Points] Display appropriate error message when uploading image

### ISSUE THREAD

**Issue by Olaleye-Blessing** [formbricks/formbricks#1294]
### Issue Summary

Users shouldn't be kept waiting due to wrong UI message. When uploading company logo while creating a survey, I think there's a maximum size that could be uploaded. The UI keeps showing `uploading` even tho there is an error from the API. This could keep users waiting without knowing what to do next.

### Steps to Reproduce

1. Go to [https://app.formbricks.com/](https://app.formbricks.com/)
2. Navigate to to the `surveys` page
3. Create new Survey
4. Open the `Network` tab in order to confirm the next steps
5. Try to upload around `6.6 MB` image as company logo
6. Wait till it resolves in the `Network` tab 
7. Notice the infinite `uploading` message even tho there's an error

### Expected behavior

1. Show appropriate error message after API resolves

## Better Approach
1. Update the label message to include the maximum data that could be uploaded
2. Check the image before uploading at all.

### Other information

I see the issue is in the [FileInput Component](https://github.com/formbricks/formbricks/blob/main/packages/ui/FileInput/index.tsx).

I will like to work on it

### Screenshots

<img width="1462" alt="Screenshot 2023-10-18 at 14 58 48" src="https://github.com/formbricks/formbricks/assets/70102539/566c161b-9aed-4820-963f-b075ddfcbf24">

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- Browser: Brave
```

**Comment by adityadeshlahre** [comment]
i would like to work on this.
Thank You :smile:

**Comment by Olaleye-Blessing** [comment]
> i would like to work on this. if @Olaleye-Blessing don't want to work on this ! Thank You 😄

I would like to work on it, thanks😀

**Comment by ShubhamPalriwala** [comment]
Hey @Olaleye-Blessing, good work finding the bug +50 points! +100 points for solving it cleanly! Assigning it to you! Please try to open a PR within 24 hours as it'll be assigned to you 🚀
