### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] href/hyperlink to switch ENVIRONMENTS not working

### ISSUE THREAD

**Issue by adityadeshlahre** [formbricks/formbricks#1296]
### Issue Summary

This text/href/hyperlink **_Switch to Development now._** is not switching as user would expect to work.

LOCALHOST 

![image](https://github.com/formbricks/formbricks/assets/132184385/eace2744-ff5e-45e3-b707-0659f46d8f5a)

APP.FORMBRICKS.COM

![image](https://github.com/formbricks/formbricks/assets/132184385/8b0307cb-c545-4f26-8ab2-3ed40a196f91)

### Steps to Reproduce

On Api keys page is the text written **_Switch to Development now._** 
if click on that then there will be no response.

https://www.loom.com/share/149555d89fb74cedaa6ae35368160f19?sid=10183a31-74bd-4fef-a047-5557f3b5e8a8

### Expected behavior

As the text says **_Switch to Development now._** 
Development/Productions should be switched on click on that.

### Other information

I am working on fix of it so please ASSIGNE this issue to me !

### Screenshots

Above mentioned 
Thank You :smile: 

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Arch linux
- Node: v18.18.0
- npm: v10.2.0
```

**Comment by aniket-singh-01** [comment]
HI can you assign this to me, I can fix this

**Comment by ShubhamPalriwala** [comment]
Hey @adityadeshlahre, thanks for finding the bug! +50 points for finding as well as fixing the bug! Assigning it to you 🚀
