### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Demo App: Toggle button text not changing & Incomplete Background 

### ISSUE THREAD

**Issue by shyamraghu** [formbricks/formbricks#1308]
### Issue Summary

Toggle button text not changing when we toggle between light mode and dark mode

### Steps to Reproduce

1. Go to the http://localhost:3002/app
2. Clicked on "Toggle Dark Mode" button
3. You can see the text of the button is not changing
![image](https://github.com/formbricks/formbricks/assets/94217498/d535a209-8425-4a8d-a049-8ea274eb6d94)

### Expected behavior

The text of the button should be changed when we click on the toggle dark mode button. When the dark mode is on the text should be "Toggle Light mode" and the light mode is on the button text should be "Toggle dark mode"

https://www.loom.com/share/3cbad3c9c078416bbbda65a10e125b39?sid=7edde619-6e1c-4625-8268-531914b53ef6

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Node: v18.18.0
- npm: 9.8.1
```

**Comment by ShubhamPalriwala** [comment]
Hey @shyamraghu, thanks for pointing out the bug! I noticed another bug while testing the bug:
![image](https://github.com/formbricks/formbricks/assets/55556994/450cd80e-96dc-40ea-a4c5-559b42a8491c)


If you see, the background does not load up on the entire page! Can you add this as well in the PR? 

We'll provide you with +50 points for finding the bug as well as opening the PR with both the fixes combined 💪🏼

**Comment by shyamraghu** [comment]
@ShubhamPalriwala Ok

**Comment by shyamraghu** [comment]
Hi @ShubhamPalriwala should i make new issue? because i was deleted the branch or any other option
