### ISSUE TITLE
[FEATURE][FormTribe 🔥][150 Points] Create dark mode version of Code Block on landing page

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1311]
### Is your feature request related to a problem? Please describe.

Currently, our code embed on the landing page doesnt look good on dark mode:

<img width="334" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/f53c8220-222f-46e0-9c2e-18201cfe1b93">

Pls also add rounded corners :)

### Describe the solution you'd like

Make it look nice with dark mode. Please use only colors from Tailwind `slate` color palette.

You'll work in this file: `apps > formbricks-com > components > shared > CodeBlock.tsx`

<img width="831" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/7b22d7d8-75d4-4a16-8dbf-a7968fa79b6e">

**Comment by aman44444** [comment]
@jobenjada hey can i work on this?

**Comment by Subhrajit-Dutta** [comment]
Can I work on this?

**Comment by itzabhinavarya** [comment]
I would like to work on the same. 
@jobenjada @ShubhamPalriwala Sir, Kindly Assign this to me.

**Comment by SumanKisku** [comment]
I would like to work on this issue

**Comment by ShubhamPalriwala** [comment]
@aman44444 since you were the first one, assigning it to you! Try to open a PR within 24 hours 🚀

**Comment by itzabhinavarya** [comment]
@aman44444 Kindly update the status within 24hrs, If not done then, i will open a PR for the same.

**Comment by RonankiDinesh** [comment]
I Want to do this @jobenjada

**Comment by rijuoddusual1999** [comment]
Hey, can you pls assign me this
