### ISSUE TITLE
[BUG][FormTribe 🔥][100 Points] Share Modal not opening

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1315]
### Issue Summary

The share modal does not open:

<img width="1076" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/d633d72a-cc32-4c5c-84f6-79bec448a5bd">

### Steps to Reproduce

1. Go to a link survey
2. Try to open the Share modal by clicking on the Share icon

### Expected behavior

Share modal opening

**Comment by Mohak973** [comment]
I want to solve this issue.can u assign it to me?

**Comment by aamani98** [comment]
I want to fix this issue. Please assign it to me.

**Comment by gupta-piyush19** [comment]
Also, styling for single-use links is breaking. please fix this along.
![image](https://github.com/formbricks/formbricks/assets/56182734/418b9803-c191-4c9d-9958-98c3ecef93e2)

**Comment by Vidhanvyrs** [comment]
hey @jobenjada i would like to work on this issue can you please assign it to me

**Comment by ssingh3856** [comment]
Can i work on this issue?

**Comment by vashukashyap** [comment]
can i work on this issue?

**Comment by jobenjada** [comment]
@Mohak973 you were the first to respond, please also take note of @gupta-piyush19 comment re styling of single link surveys.

I have increased the number of points to 100 to add the needed truncation in the link box.

**Comment by SumanKisku** [comment]
I would like to work on this issue too.

**Comment by Aadish1233** [comment]
i would like to work on it

**Comment by vikaspatil0021** [comment]
@gupta-piyush19
@jobenjada 
works fine for me
![Screenshot 2023-10-20 093341](https://github.com/formbricks/formbricks/assets/112180774/fdc96088-abc2-42bb-8146-3b77961954be)

**Comment by gupta-piyush19** [comment]
Hey @vikaspatil0021! Thanks for checking it out. Though this issue is assigned to @Mohak973 , please let him either complete this issue or drop before you start on it. 
Also, click on Regenerate to get new Set of links, which may contain overflowing link.

**Comment by vikaspatil0021** [comment]
@gupta-piyush19 
No issue with regeneration of new links

**Comment by gupta-piyush19** [comment]
Okay cool, someone might have fixed it already.

**Comment by jobenjada** [comment]
@vikaspatil0021 it doenst work for me :(

@mohak973 are you doing this? Would love to have the fix live asap 🚀

**Comment by vikaspatil0021** [comment]
@jobenjada could you share a video and give some more information about the issue

Also If Mohak973 is not doing it then i have a solution to the issue and would like to open a PR

**Comment by Mohak973** [comment]
@jobenjada  I am doing it.
Will let u know the progress shortly

**Comment by gupta-piyush19** [comment]
Hey, @Mohak973! Can you please prioritize this fix? Users might face issues opening the modal as it's already live on prod. It's a minor fix. Hit me up on Discord if you need any help.

**Comment by Mohak973** [comment]
@gupta-piyush19 hey , provide me ur discord link or something?

**Comment by gupta-piyush19** [comment]
Join formbricks [discord](https://discord.com/invite/scsuwVnW), if you haven't yet.
My discord username is piyush0_0

**Comment by ShubhamPalriwala** [comment]
Hey, love the collaboration here! Do let us know the status of this whenever you both have one 💪🏼

**Comment by aarjun8060** [comment]
Hello everyone, I want to work on this issue. Would you be able to assign to me?

**Comment by jobenjada** [comment]
Its done :)
