### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Copy button working while it's value is null

### ISSUE THREAD

**Issue by shyamraghu** [formbricks/formbricks#1327]
### Issue Summary

The copy button is working while it's value is null and the Shorten button should be disabled when its input value is null

https://www.loom.com/share/dc9b842106dd4b13832509782320539f?sid=949737e7-07bf-43a5-ae8d-b2cdc7463ff4

### Steps to Reproduce

1. Go to https://app.formbricks.com/
2. then go to settings
3. then click on the Link shortener

![image](https://github.com/formbricks/formbricks/assets/94217498/4acbfcd2-41e2-433a-88d9-940e8e3745bb)

### Expected behavior

The copy button should be disabled till the value is null

https://www.loom.com/share/3600d3c4013d484182858eaf099f8dcb?sid=9928b20f-9b12-4282-b7a4-2a1d8db2a824

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/94217498/fd2e96d0-d87a-4e46-b7b0-b9f8879bbe35)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Node: v18.18.0
- npm: 9.8.1
```

**Comment by aamani98** [comment]
Can I fix this issue

**Comment by vs-29** [comment]
@shyamraghu I want to contribute to this, please assign me this issue.

**Comment by ShubhamPalriwala** [comment]
Hey @shyamraghu, thanks for spotting the bug! +50 points for finding as well as fixing it! 🚀
