### ISSUE TITLE
[FEATURE][FormTribe 🔥][100 Points] Add twitter title, description and keywords for SEO

### ISSUE THREAD

**Issue by aashishpanthi** [formbricks/formbricks#1333]
### Is your feature request related to a problem? Please describe.

I saw the meta tags missing for Twitter. These are certainly helpful for SEO.  Also, I've heard keywords aren't helpful for SEO, and search engines like Google don't look at them. But I guess they do and keywords are certainly helpful for other search engines also.

### Twitter title and description
```
<meta name="twitter:title" content="Formbricks | Privacy-first Experience Management">
<meta name="twitter:description" content="Build qualitative user research into your product. Leverage Best practices to increase Product-Market Fit.">
```

### Keywords
```
<meta name="keywords" content="Formbricks, Privacy-first Experience Management, user research, GDPR compliant, open-source, self-hosting, pricing">
```

**Comment by krishanu7** [comment]
please assign me this issue

**Comment by jobenjada** [comment]
@aashishpanthi it's yours, please go ahead :)

**Comment by aashishpanthi** [comment]
I've added the tags. Can you merge it @jobenjada?
