### ISSUE TITLE
[BUG][FormTribe 🔥][100 Points] Every template starts with Welcome Card

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1336]
### Issue Summary

Every template now starts with the welcome card:

<img width="1416" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/5e7d9eef-3937-464d-bd5c-3d340fa3d1fe">

This isn't great UX, the users want to dive right into the survey.

### Steps to Reproduce

1. Go to Formbricks Cloud and go through the different templates

### Expected behavior

The survey should start with the first question

### Tasks

1. Change the default for all templates.
2. If it makes sense to change the overall default of the Welcome Card not being active by default, that might be the best solution :)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by RajuGangitla** [comment]
@jobenjada can I start working on this

**Comment by jobenjada** [comment]
@RajuGangitla go for it :)

**Comment by SumanKisku** [comment]
I would love to work on this issue

**Comment by RajuGangitla** [comment]
@ShubhamPalriwala can u add the lables hacktoberfest
