### ISSUE TITLE
[BUG][FormTribe 🔥][150 Points] Prefilling broke after welcome card

### ISSUE THREAD

**Issue by gupta-piyush19** [formbricks/formbricks#1337]
### Issue Summary

Prefiling is not working for the welcome card, not skipping the first question.

### Steps to Reproduce

1. Create a new survey with a welcome card.
2. Open survey URL with prefiling for question in it.
3. It will skip the welcome screen only and not the first question.

### Expected behavior

It should skip both the welcome card and the first question.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by gupta-piyush19** [comment]
I'd love to fix this, @jobenjada.

**Comment by jobenjada** [comment]
true that!

**Comment by gauravp-dev** [comment]
I would like to pick this. If possible please assign it to me
