### ISSUE TITLE
[BUG][FormTribe 🔥][100 Points] Delete and Save Buttons Remain Clickable After Click on Delete or Save button

### ISSUE THREAD

**Issue by shyamraghu** [formbricks/formbricks#1338]
### Issue Summary

Upon clicking the "Delete" button in the DeleteDialog component, the button does not become disabled as expected. Consequently, users can click the "Delete" button multiple times, leading to potential issues. The same behavior is observed with the "Save" button. 

Multiple time click create error also 

![image](https://github.com/formbricks/formbricks/assets/94217498/067997c0-fbd6-4a13-88bf-8c570a1e4632)

### Steps to Reproduce

1. Open the DeleteDialog component.
2. Click the "Delete" button.
3. Observe that the button does not become disabled.
4. Attempt to click the "Delete" button again. Note that it remains clickable.
5. Repeat the above steps for the "Save" button.
![image](https://github.com/formbricks/formbricks/assets/94217498/4395a3a5-d8ae-4521-894b-d10ef184cb6e)

https://www.loom.com/share/9b9980e2125b443589acd6c0a11f55e4?sid=71ec4b52-033b-4674-bfff-8a20330f7437

### Expected behavior

After clicking the "Delete" button, it should be disabled to prevent multiple consecutive clicks until the action is completed.
The "Save" button should exhibit the same behavior, becoming disabled temporarily after being clicked to avoid multiple rapid clicks.

https://www.loom.com/share/c4973ca8c83a4f289e8b63b0a8c9dad2?sid=aa956af4-9871-4e10-bd16-370ef253f6d9

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/94217498/dc322be0-0265-4db9-9f4f-aeb1f0319036)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Node: v18.18.0
- npm: 9.8.1
```

**Comment by jobenjada** [comment]
Good catch! Will comment in the PR :)

**Comment by shyamraghu** [comment]
@jobenjada please assign this to me

**Comment by vs-29** [comment]
@jobenjada I wish to solve this issue.plz, assign it to me.

**Comment by jobenjada** [comment]
@shyamraghu is on it, thanks @vs-29 tho :)

**Comment by shyamraghu** [comment]
@jobenjada Publish button already have a loader
