### ISSUE TITLE
[BUG][FormTribe 🔥][150 Points] First submission in "Other" option not stored

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1341]
### Issue Summary

When you have an Other option in a single or multi select question, the first time it is filled out it does not store the value:

https://tella.video/first-other-submission-not-working-fdsc

Additionally, the response count is off:

<img width="1320" alt="Screenshot 2023-10-20 at 11 28 06" src="https://github.com/formbricks/formbricks/assets/72809645/5b3ff8e8-2153-43d7-af36-35e939d76d73">

I filled it out 3 times but since the first one got missed by the first question with "Other" it displays 2. In the Multi Select however shows 6 responses (maybe the Other and the regular both get counted?)

### Steps to Reproduce

1. Create a new survey with a single or multi select question incl. "Other" answer option
2. Fill it out using the Other option
3. Notice that the first time your using it, it wont store (or display) the value in the summary

### Expected behavior

1. The "Other" answer should always be stored and displayed
2. The response counts should match the KPIs at the top

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

**Comment by vs-29** [comment]
@jobenjada  plz assign me this issue. I can resolve it.

**Comment by jobenjada** [comment]
@vs-29 it's yours, curious to see your solution :)

**Comment by vs-29** [comment]
@jobenjada    Sir, I checked the issue on the site, but it was working fine.

**Comment by venk404** [comment]
@jobenjada - It is also working for me, and it is correctly storing the values of other options. The response count is also accurate.

![image](https://github.com/formbricks/formbricks/assets/61042520/18dd454e-3165-452b-adaf-d0bb64c7c444)
![image](https://github.com/formbricks/formbricks/assets/61042520/cb6f19d9-d146-4a14-b184-a23a221e89d2)
