### ISSUE TITLE
[FEATURE][FormTribe 🔥][150 Points] Prepare Tailwind for UI Revamp

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1342]
### Is your feature request related to a problem? Please describe.

We're planning to overhaul our UI to give you guys the slick look & feel you're craving 🤤 

In the preparation of it, we need to update out Tailwind config with the new colors you find here:

https://www.figma.com/file/Wt5hBzsBCkGqzLyC3ytNVy/Formbricks-Design?type=design&node-id=411%3A12072&mode=design&t=FrgmUGmpwbu7Hbif-1

### Describe the solution you'd like

1. In the `tailwind.config.js` in the `packages/tailwind-config` folder, please add the new colors.
2. Find a naming convention which makes the colors easily recognizable and usable.

Notes
- Please have a look how [other repos ](https://github.com/calcom/cal.com/blob/main/packages/config/tailwind-preset.js)do it and learn from them :) At this point we don't need templating, but get some ideas!
- This is a fairly quick task for 150 points: Please take some time to ship a proper solution vs. winging it :pray

**Comment by tajbaba999** [comment]
Hey @jobenjada Can you please assign me this issue?
Can you please explain me some in detail about what to do?

**Comment by jobenjada** [comment]
Hey @tajbaba999 I think the ticket contains all the info you need :)

If you have any specific questions, I am happy to answer them

**Comment by tajbaba999** [comment]
Thanks, @jobenjada I got it now I have some doubt should I need to change only one single tailwind.config.js file which is present in the web folder or should I change all the files present in the repo?

**Comment by jobenjada** [comment]
@tajbaba999 im really sorry but I dont think you are up for the challenge :( In the ticket its clearly written which tailwind config you are supposed to change...

**Comment by Prashant04627** [comment]
Hi @jobenjada it seems like the figma link is not opening? Can you fix that or send another link so that i can see it

**Comment by tajbaba999** [comment]
Hey @jobenjada I don't any much experience with tailwind can you please give me some time so that so  that I can learn and work on this issue thanks for understanding.

**Comment by Prashant04627** [comment]
Is this ticket still on? Can i work on it?

**Comment by git-init-priyanshu** [comment]
I think I can work on this. Please assign me. Thanks.

**Comment by shyamraghu** [comment]
Done

**Comment by gauravkharel** [comment]
Hey @jobenjada
I was reviewing the issue and, the solution from @Shyam-Raghuwanshi have the solution which has 50 to 900 shades for each color group. Isn't we only require the listed colors only from figma file in the tailwind.config.js in the packages/tailwind-config folder?

If that's the case, I am eager to work on the issue as per the advice in the #1368 issue.

Example implementation:
`const colors = {
  primaryDark: "#0f172a",
  primaryLight: "#038178",
  // add more colors as needed
};

module.exports = {
  // ...
  light: {
    accent: {
      primary: {
        darkest: colors.primaryDark,
        default: colors.primaryLight,
        // ...
      },
    },
    // ...
  },
  // ...
};`
