### ISSUE TITLE
[FEATURE][FormTribe 🔥][100 Points] Add font "Jost" to repository

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1343]
### Is your feature request related to a problem? Please describe.

We're not having a recognizable font

### Describe the solution you'd like

We're planning a UI revamp incl. a new font: Jost

https://fonts.google.com/specimen/Jost

Please download and convert the files for web and add them to the repository. Make sure to see if we have to add any kind of license reference in the code :)

**Comment by aamani98** [comment]
I want to work on this.

**Comment by SumanKisku** [comment]
I would like to take this issue @jobenjada

**Comment by krishanu7** [comment]
@jobenjada please assign me this issue

**Comment by tajbaba999** [comment]
@jobenjada I tried to work on this issue by using the "@import" method in the CSS file can you please tell me if is this the right approach to work on this issue?

**Comment by lalitkumawat1m** [comment]
Hey @jobenjada, I want to work on this issue please assign it to me

**Comment by shyamraghu** [comment]
@jobenjada done

**Comment by ShubhamPalriwala** [comment]
Closed via #1346
