### ISSUE TITLE
[BUG] ❌ Invalid environment variables:

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1348]
### Issue Summary

error on windows '❌ Invalid environment variables'

### Steps to Reproduce

while running web app locally as dev on Windows 

### Expected behavior

environment variables are not getting pass before defining them

### Other information

.

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/84387676/ff8178bb-3a2c-4c60-ba80-7966d90f9ef1)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Node: v18.15.0
- npm: 9.6.2
- pnpm: 8.1.1
```

**Comment by git-init-priyanshu** [comment]
I can work on this issue. Please assign. Thanks.

**Comment by mandharet** [comment]
For Instance to make it build. copy your .env file content from the root and paste it to the .env file in apps/web directory.

**Comment by amitshuklabag** [comment]
Same issue with Linux Machines.

**Comment by beortner** [comment]
I cloned the repo two days ago, and its still open.

**Comment by mattinannt** [comment]
@beortner Unfortunately we needed to revert the fix because it led do issues on certain production deployments, e.g. on Vercel. Please use GItpod or Github Codespaces for development: https://formbricks.com/docs/contributing/gitpod
