### ISSUE TITLE
[BUG][FormTribe 🔥][100 Points} Invalid PIN Allows Survey to be Published

### ISSUE THREAD

**Issue by piyushgarg-dev** [formbricks/formbricks#1353]
### Issue Summary

The issue is that if you try to set an invalid PIN, it throws an error on UI but still allows the user to save and publish the survey.

### Steps to Reproduce

1. Go to Survey
2. Navigate to settings and Scroll to "Response Options"
3. Toggle PIN
4. Enter invalid PIN
5. Publish the survey

### Expected behavior

Save and Published button must be disabled.

### Screenshots

https://github.com/formbricks/formbricks/assets/44976328/e3bab7b2-5065-4103-a621-05fb6bf3ebcb

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: MacOs
- Node: N/A
- npm: N/A
```

**Comment by jatingodnani** [comment]
Interested

**Comment by venk404** [comment]
Interested

**Comment by sidxh** [comment]
can you pls assign this to me?

**Comment by lalitkumawat1m** [comment]
Hey @jonas-hoebenreich, I want to work on this issue please assign to me

**Comment by animeshMondal-crypto** [comment]
I want to work on this issue.

**Comment by jobenjada** [comment]
@piyushgarg-dev do you want to push a fix? :)

**Comment by ChaudharyPradip** [comment]
Hey, I would love to solve this issue. Please assign it to me.

**Comment by piyushgarg-dev** [comment]
Thanks @jobenjada for asking out 😄. I don't have the fix ready tho but was thinking if we can give others this opportunity 😉

**Comment by trickyj** [comment]
Working on it.

**Comment by jobenjada** [comment]
@jatingodnani its yours then :)

**Comment by jatingodnani** [comment]
hey @jobenjada,after running pnpm go,it showing this error
![Screenshot 2023-10-20 201027](https://github.com/formbricks/formbricks/assets/97869761/d7104fa9-e07d-4db7-9bf3-03890f6f3f32)

**Comment by vikaspatil0021** [comment]
@jobenjada can i  attempt?

**Comment by SumanKisku** [comment]
I will try to work on it after others.
