### ISSUE TITLE
[FEATURE][FormTribe 🔥][500 Points] Publish Results Page

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1354]
### Is your feature request related to a problem? Please describe.

Users want to share the summary and response pages of select surveys with people who do not have access to their Formbricks instance.

https://github.com/formbricks/formbricks/issues/984

### Describe the solution you'd like

We allow to publicly share results pages similar to how Notion allows users to release pages to be accessible by anyone without a Notion account

### Technical Context
Currently, all insights are hidden behind auth so that no data is leaked to the public. However, with our Management API it is possible to pull answers of specific surveys from the Servers as long as you have a valid API key to authenticate your request.

We are now building something similar where the URL functions as the auth key. To do that, we create a new model in the Prisma schema which has an ID which cannot be guessed, especially not in combination with the correct survey Id. So only when the user has released survey data and the ResponseSharing ID and the survey ID in the URL match, the website visitor has access to the survey data.

### Tasks
1. Add a new model ResponseSharing to the Prisma schema (sketched out above). While you're building this and you  notice that you need to make changes to the model, then please do ;)
2. Update the Share button in the survey summary page as follows - for **Link Surveys**:
- It opens a dropdown (look at the Download dropdown for stying)
- Share Survey → Opens the Share modal which currently opens by default
- Publish Results → Opens a new Publish Results Modal
3. For **In App Surveys**: Change the Button text from "Share" to "Publish Results" and display the Publish Results modals right away (skip the Dropdown)

<img width="1410" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/00215ade-b312-449e-95ae-d70181a503b3">

<img width="659" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/baa09153-221e-41ac-b775-8427022f25fc">

The UI should explain what you have to build 😃 

If not, please reach out on [Discord ✌️](https://formbricks.com/discord)

**Comment by sidxh** [comment]
hey @jobenjada, would absolutely love to contribute on this issue, can you please assign this to me?

**Comment by anjy7** [comment]
I would like to take this one @jobenjada

**Comment by jobenjada** [comment]
perfect, happy to have you ship it! :)

**Comment by krishanu7** [comment]
Please assign me @jobenjada
