### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Team name input not validated before submission

### ISSUE THREAD

**Issue by adityadeshlahre** [formbricks/formbricks#1355]
### Issue Summary

**Only " " Spaces can be submitted on team and product name.**

### Steps to Reproduce

https://www.loom.com/share/b3ddab3649684ff1b50c0d992d03e2b5?sid=002a7a45-4d34-43f3-9a9d-6ae647320c01

### Expected behavior

doesn't let user enter " " spacy names and throw error on invalid names

### Other information

I m working on this issue please assign this to me.

### Screenshots

Above mentioned !
Thank You :smile: 

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Archlinux
- Browser: Brave
- Node: 18.18.0
- npm: 9.8.1
```

**Comment by sundaram2021** [comment]
Hey @adityadeshlahre  I would like to work on it 
can you assign it to me

**Comment by jobenjada** [comment]
@adityadeshlahre good catch! 😎 

Please validate before submitting. Please disable the Submit button when the input is not valid.

**Comment by krishanu7** [comment]
Hey @adityadeshlahre I would like to work on this issue
