### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Button text not visible on white background.

### ISSUE THREAD

**Issue by git-init-priyanshu** [formbricks/formbricks#1357]
### Issue Summary

The "Next" button of Survery is not visible on white background.

### Steps to Reproduce

1. Make a new account on formbricks.
2. Fill out the details of first two sets.
3. When you get to third set of details, Set the primary color field to complete white.
4. You will see that the next button in survey below is completely invisible now.

### Expected behavior

The button should be at least partially visible.

### Screenshots

<img width="376" alt="image" src="https://github.com/formbricks/formbricks/assets/110045644/2fbc6885-0a96-4c46-9c8b-2fc21596703b">

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Node: v18.13.0
- npm: 8.19.3
```

**Comment by krishanu7** [comment]
please assign me this issue

**Comment by aniket-singh-01** [comment]
Hi , can i take this issue?

**Comment by krishanu7** [comment]
Please add hectoberfest tag

**Comment by krishanu7** [comment]
@jobenjada the code is working fine . Should i create different file to define the function ? or it is okay ?
