### ISSUE TITLE
Red asterisk for required fields does not show

### ISSUE THREAD

**Issue by choeunlee** [formbricks/formbricks#136]
**Issue Summary**

when a user click the '*'(red asterisk) button to make a required filed, the form does not show.

**Steps to Reproduce**

1. Creates form with 'No-Code Builder'.
2. Click the 'add' button to add a question.
3. In the question, click the 'click to tune' button to edit the question.

If a user click the red asterisk button to describe that the question need to get an answer, only the type of 'Long Text Question' shows red asterisk. 
And Other types of questions do not show red asterisk even though a user click the red asterisk button.

**Comment by choeunlee** [comment]
I am going to handle this issue.

**Comment by mattinannt** [comment]
@choeunlee We are currently rebuilding our codebase and focus our work for now on the react lib for form creation and form piping with the web platform. that means the nocode editor will temporarily disappear from the product until we also build this part from scratch to be able provide a certain level of quality and reliabilty.
If you use the current version of snoopForms yourself and want to solve this issue that's great but just wanted to give you a heads up, that it can be that the nocode editor no longer exists when you want to merge the code and that we will temporarily discontinue that part of the product.
