### ISSUE TITLE
[BUG] formbricks.com/demo was not responsive 

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1364]
### Issue Summary

UI of Demo page is not responsive

### Steps to Reproduce

1. Go to: https://formbricks.com/demo on mobile phone

### Expected behavior

.

### Other information

.

### Screenshots

![demo](https://github.com/formbricks/formbricks/assets/84387676/d306238d-3d02-4c17-86d4-4b9331cb4f6f)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: android
- Browser: chrome
```

**Comment by krishanu7** [comment]
assign me this

**Comment by vs-29** [comment]
@bilalmirza74 I am interested in working on this issue.plz, assign me this issue.

**Comment by ShubhamPalriwala** [comment]
Hey @bilalmirza74, thanks a lot for finding the issue! However, since this is the last week of the Formtribe hackathon, we'd now be focusing only on the core product and it's bugs/features. We'd hence request you to focus your efforts on our web-app rather than the landing page 🙏🏼
