### ISSUE TITLE
[BUG] every from is not in center across demo 

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1369]
### Issue Summary

on demo page the form is not in center

### Steps to Reproduce

1. Go to: https://formbricks.com/demo

### Expected behavior

.

### Other information

.

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/84387676/0f87b52a-2a38-4f67-9863-a8fc4822f8cc)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
= Browser: chrome
```

**Comment by vikaspatil0021** [comment]
There are only two lines to fix just raise a PR :)

**Comment by vikaspatil0021** [comment]
@bilalmirza74  can you share a picture of how it looks now
