### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] 404 Error Page: Back to Home Button Fails to Redirect Users to Homepage

### ISSUE THREAD

**Issue by shyamraghu** [formbricks/formbricks#1380]
### Issue Summary

Clicking the "Back to Home" button on the 404 Error page does not successfully redirect users to the homepage. Instead, users remain on the 404 page, impeding navigation back to the main site. This issue requires investigation and resolution to ensure a seamless user experience.

https://www.loom.com/share/5e507697ada14eaa9247a7e3d39ecdc6?sid=c0e1feb0-af45-422d-9387-524805a05f2d

### Steps to Reproduce

1. Navigate to any page on the website.
2. Intentionally input an incorrect URL or access a non-existent page to trigger a 404 Error.
3. Observe the appearance of the 404 Error page.
4. Attempt to use the "Back to Home" button on the 404 page.
5. Note that the expected redirection to the homepage does not occur, and users remain on the 404 page.

![image](https://github.com/formbricks/formbricks/assets/94217498/8874ac71-7325-4ab0-80cd-75dac8a46670)

### Expected behavior

Upon clicking the "Back to Home" button on the 404 Error page, users should be promptly redirected to the homepage, allowing for a smooth transition from the error state to the main site.

https://www.loom.com/share/1de478248da24d30833a18dbf13788af?sid=33a26a56-4990-4fba-b358-1debb17fb2f4

### Other information

The url got changed for home page but not redirect to home page

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Node: v18.18.0
- npm: 9.8.1
```

**Comment by ShubhamPalriwala** [comment]
Thanks for finding the bug! +50 points for flagging as well as fixing it combined 🚀

**Comment by shyamraghu** [comment]
> Thanks for finding the bug! +50 points for flagging as well as fixing it combined 🚀

Thankyou very much sir

**Comment by shyamraghu** [comment]
hi @ShubhamPalriwala the `<Link></Link> ` is not working in production but working in locally. may be i should use `router.refresh` when user click on the Back to home button
