### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Button Enablement Precedes Component Rendering on Publish/Save Click

### ISSUE THREAD

**Issue by shyamraghu** [formbricks/formbricks#1399]
### Issue Summary

When clicking on the "Publish" or "Save" button, the button state transitions to enabled before the associated component has completed rendering. This premature button enablement occurs despite the ongoing rendering process, leading to an inconsistent user experience. And When we click on any one of both the both buttons got loding

![Screenshot 2023-10-21 110604](https://github.com/formbricks/formbricks/assets/94217498/b614839c-f963-4dc5-9497-560b49109766)

https://www.loom.com/share/e87af8e51473431eb2358e583921a6a6?sid=f2e6b59c-2724-4eb8-a99f-fbc9e8d30997

### Steps to Reproduce

1. Create a survey
2. Click on the "Publish" or "Save" button.
3. Observe that the button transitions to an enabled state.
4. Notice that the enabled state occurs before the associated component has fully rendered.
5. Verify that this behavior consistently happens on multiple attempts.

![image](https://github.com/formbricks/formbricks/assets/94217498/a0357bb3-45f5-49ef-89ec-e439a7558587)

### Expected behavior

Clicking on the "Publish" or "Save" button initiates the corresponding action.
The button transitions to an enabled state only after the associated component has fully rendered.
Users observe a synchronized and consistent experience where button enablement aligns with the completion of the rendering process.
The user interface remains responsive during the rendering phase, and the button's enabled state accurately reflects the current state of the component.

https://www.loom.com/share/0d0cff1f53f14ac189498d8c712ef940?sid=dfe60229-4236-43fe-bd81-9bf978bc2c5f

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Node: v18.18.0
- npm: 9.8.1
```

**Comment by ShubhamPalriwala** [comment]
Thanks for finding the bug! +50 for catching it and +50 for solving it as well once the PR is approved and gtg🚀
