### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] In Review Prompt Lower and Upper labels are not showing in dummyUi/Preview

### ISSUE THREAD

**Issue by itzabhinavarya** [formbricks/formbricks#1401]
### Issue Summary

In Review Prompt Lower and Upper labels are not showing in dummyUi/Preview.

<img width="960" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/34d4f64b-e611-404b-852f-1c5154076496">

For Reference , The above issue should be fixed as following.
Fake-Door Follow-Up Survey.

<img width="959" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/1c5123ff-afef-4b06-a1b8-a9d0d383fe43">

### Steps to Reproduce

1. Go to the app
2.  Head over new survey
3. Select Review Prompt Survey
4. Check the Lower Label & Upper Label. (Also in the preview section)

### Expected behavior

Review Prompt After fixing.

<img width="960" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/d389b57e-5594-474f-a2a0-512c1a9e0555">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Not required
- Node: Not required
- npm: Not required
```

**Comment by itzabhinavarya** [comment]
@jobenjada @ShubhamPalriwala Sir, Kindly assign this issue to me. Thanks :)

**Comment by ShubhamPalriwala** [comment]
Hey @itzabhinavarya, thanks a lot for finding this out! +50 points for flagging as well as fixing a PR combined 🚀

**Comment by itzabhinavarya** [comment]
@ShubhamPalriwala Thanks a lot:)
