### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Overflowing CodeBlock in "Share or embed your survey" modal

### ISSUE THREAD

**Issue by mandharet** [formbricks/formbricks#1403]
### Issue Summary

Issue Summary

1. In our "Share or embed your survey" modal >> "Embed in an Email" tab when user clicks on  "View Embed Code"
HTML CodeBlock gets visible, but it's **overflowing on x-axis and HTML code is partially visible**.

2. On "Share or embed your survey" modal, some scrollbars are set as mandatory.

Please, refer attached video for reference.
https://youtu.be/fQTkMUyVFN8

### Steps to Reproduce

1. Make an in-app survey with multiple questions
    try to upload images as image URL's are huge to fit in CodeBlock's normal width
2. Save Form and click on Share or Publish
3. Will open "Share or embed your survey" modal
4. Click on Embed in an Email tab
5. then click on View Embed Code tab
6. try to pay around with displayed codeblock and try to scroll

### Expected behavior

Entire Code should be visible and readable from CodeBlock with simple scroll operation if needed

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/45624147/834e97bb-77c6-482e-8f29-ef7cac1aabfb)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mandharet** [comment]
Please, review and approve
https://github.com/formbricks/formbricks/pull/1404

**Comment by ShubhamPalriwala** [comment]
Hey @mandharet can you please share your screen resolution once?

I tried to replicate the same issue but it's working pretty fine for me:
![image](https://github.com/formbricks/formbricks/assets/55556994/a42d486e-bff4-4445-8e80-f922c9472536)

**Comment by mandharet** [comment]
Hi @ShubhamPalriwala ,
Try to upload images as image URL is long to fit in CodeBlock's normal width.
I was able to replicate same issue on local as well as on codeBlock.
My monitor's resolution is 1360 X 768. But, I have adjusted screen resolution to 1920 X 1080 with 125% Scale on Windows 10.

**Comment by ShubhamPalriwala** [comment]
Hey, by image do you mean the Welcome card? Yeah I tried that and even when it expands the screen width for me, it wraps itself up with a scrollbar. Would need some more context here to replicate it haha

**Comment by mandharet** [comment]
I have tried with 1080P monitor with 1080P resolution and 100% scaled on windows 11 (edge).
![image](https://github.com/formbricks/formbricks/assets/45624147/b5b7c8ea-2aec-4f43-bd2c-bc3d739c6914)


I was able to replicate same issue.
![image](https://github.com/formbricks/formbricks/assets/45624147/6f5dd47a-9ce1-44d0-89b1-fbfdd79c6e94)

**Comment by mandharet** [comment]
Yes @ShubhamPalriwala , please try to add welcome card with Image.

**Comment by ShubhamPalriwala** [comment]
Ahh, I see! Was just able to replicate it now a template! Nice catch! +50 points for catching and another +50 points for fixing the bug! 🚀
