### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'init') while widget load

### ISSUE THREAD

**Issue by Edd-G** [formbricks/formbricks#1409]
### Issue Summary

1. Run Formbricks with Docker locally and initial setup in dashboard.
2. Add this code to local html page in `<head>` tag:
```
<!-- START Formbricks Surveys -->
<script type="text/javascript">
!function(){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src="https://unpkg.com/@formbricks/js@^1.0.0/dist/index.umd.js";var e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(t,e),setTimeout(function(){window.formbricks=window.js;window.formbricks.init({environmentId: "clo0n171n000pov01lckewbam", apiHost: "http://localhost:3000"})},500)}();
</script>
<!-- END Formbricks Surveys -->
```
and getting error in browser console:

Chromium
```
Uncaught TypeError: Cannot read properties of undefined (reading 'init')
```
Firefox
```
Uncaught TypeError: window.formbricks is undefined
```

### Steps to Reproduce

1. Setup Formbricks from Docker
2. Connect Formbricks to your app. From dashboard (Setup checklist -> HTML tab) copy code
3. Paste code to <head> tag your local html page.

### Expected behavior

Frombricks widget will be load whitout javascript error.

### Other information

Tested in:
1. Chromium 116.0.5845.180
2. Firefox 102.15.0esr x64

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Linux Debian 11
- Node:not applicable
- npm: not applicable
```

**Comment by adityadeshlahre** [comment]
hey @Edd-G :wave: 
can u record a video about this error and share here for more clearity. 
about this issue
Thank You :smile:

**Comment by Edd-G** [comment]
https://github.com/formbricks/formbricks/assets/5066751/e9412f1b-0e6e-453b-a46b-c251a1104c5a

Hi, @adityadeshlahre

**Comment by adityadeshlahre** [comment]
hey @Edd-G i have tried doing it in my setup locally it seems to working fine!

https://drive.google.com/file/d/1NxufzSC7wmcTZyw4nCXbPl8hfahBvF1o/view?usp=sharing

**Comment by Edd-G** [comment]
@adityadeshlahre thanks for your help.

But my widget code copied from dashboard different whit yours. 
This is ny code:
```
<!-- START Formbricks Surveys -->
<script type="text/javascript">
!function(){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src="https://unpkg.com/@formbricks/js@^1.0.0/dist/index.umd.js";var e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(t,e),setTimeout(function(){window.formbricks=window.js;window.formbricks.init({environmentId: "clo0n171n000pov01lckewbam", apiHost: "http://localhost:3000"})},500)}();
</script>
<!-- END Formbricks Surveys -->
```
I tried change code same as yours, but no effect. Console clear, but define debug: true.
I was able to get the module to load use this init code:

```
<!-- START Formbricks Surveys -->
	<script type="text/javascript">
	var fbi = function() {
		window.formbricks.init({
			environmentId: "clo0n171n000pov01lckewbam",
			apiHost: "http://localhost:3000",
			debug: true,
		});
	};
	!function() {
		var t=document.createElement("script");
		t.type="text/javascript";
		t.async=!0;
		t.onload=function(){fbi();};
		t.src="https://unpkg.com/@formbricks/js@^1.1.2/dist/index.umd.js";
		var e=document.getElementsByTagName("script")[0];
		e.parentNode.insertBefore(t,e);
	}();
<!-- END Formbricks Surveys -->
```
Now i see debug info in console.
Hahah, but widget not fired up)
In console:
```
Formbricks - 2023-10-22T23:48:12.372Z [DEBUG] - Fetched 1 surveys during sync: Form2Bricks Sign Up Barriers
```
What is is? I'm confused.

**Comment by ShubhamPalriwala** [comment]
Hey @Edd-G, What I could infer from the discussion above is:
- The code snippet that @adityadeshlahre shared uses our latest formbricks/js package 1.1.2 (you were using 1.0.0) which we'd also recommend so that could've helped in fixing the bug
- And now since in console you can see that the survey has been fetched, that log means that the js package has fetched the widget and now based on the triggering action you have in your Formbricks app, it will display the widget accordingly!

So please see what action have you set for the survey `Form2Bricks Sign Up Barriers` to display and then it should be visible 🚀

**Comment by Edd-G** [comment]
Hi, @ShubhamPalriwala !
I used widget code from dashboard whitout any changes. Copy & Paste.
Small notice: I used docker image as described in documentation.

No, widget not displayed now. In cosole shown message:
Formbricks - 2023-10-22T23:48:12.372Z [DEBUG] - Fetched 1 surveys during sync: Form2Bricks Sign Up Barriers

1. I see users in dashboard
2. Survey status "In-progress"
3. Survey trigger "New session"

Now, i see another error in console:

`
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'enabled')
`
![ksnip_20231023-163235](https://github.com/formbricks/formbricks/assets/5066751/80b8a6ed-9f58-47c6-897d-a0edf5b87398)
![ksnip_20231023-163311](https://github.com/formbricks/formbricks/assets/5066751/20fc79de-eb1b-4e5e-be62-79abf01bc20d)
![ksnip_20231023-164814](https://github.com/formbricks/formbricks/assets/5066751/6518286f-9f33-4343-b85e-07d1ce1a01fa)

**Comment by dudztroyer** [comment]
Having the same issue. The code generated on the Setup Checklist tutorial hands out v1.0.0 JS file. After changing manually to the newest one (found on docs) it gets the error @Edd-G is getting. Any news?

**Comment by dudztroyer** [comment]
Found the issue.

Recently it was added a welcomeCard functionality (1.1.13+), but the docker image didn't update it yet, being the last one 1.1.12. The docs at https://formbricks.com/docs/getting-started/framework-guides#html has https://unpkg.com/@formbricks/js@^1.1.2/dist/index.umd.js as the url. As a silent feature from unpkg, it automatically redirects the JS file to the newest one (1.1.14). So while we are running the backend on 1.1.12 without the welcomeCard functionality, 1.1.14 frontend expects the welcomeCard property, thus not loading our survey.

**Comment by Edd-G** [comment]
@dudztroyer thanks!
I didn't think to check the real version from unpkg.com
