### ISSUE TITLE
[BUG] Button alignment isn't right

### ISSUE THREAD

**Issue by SumanKisku** [formbricks/formbricks#1412]
### Issue Summary

Button alignment isn't right in "Add Action" Button on the landing page
![Screenshot from 2023-10-23 01-47-21](https://github.com/formbricks/formbricks/assets/7936345/97aa686c-4dae-4a6a-84a1-19a3b26b89ca)

### Steps to Reproduce

1. Go to homepage
2. Scrolldown to Step 2
3. Click "Add Action"

### Expected behavior

![Screenshot from 2023-10-23 01-57-40](https://github.com/formbricks/formbricks/assets/7936345/fd514ced-a20a-44e8-96fb-c3591fc70463)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Linux - Fedora 38
- Node: v21.0.0
- npm: 10.2.0
```

**Comment by ShubhamPalriwala** [comment]
Hey @SumanKisku, thanks a lot for finding the issue! 🚀 However, since this is the last week of the Formtribe hackathon, we'd now be focusing only on the core product and it's bugs/features. We'd hence request you to focus your efforts on our web-app rather than the landing page 🙏🏼

**Comment by SumanKisku** [comment]
Sure, I will check out. But it is a small layout fix, sooner or later it's have to be fixed I guess. So, you can think of considering it. And you don't have to add hacktoberfest tag for it.

**Comment by Rjchauhan18** [comment]
Hello @SumanKisku 
Can you please assign this issue to me?

While setup my environment i got this error ,

- According to guideline When i use the following  command `pnpm go`

![image](https://github.com/formbricks/formbricks/assets/113838908/d4b23d1f-fbc3-4386-85b3-3303715b1c30)

**Comment by SumanKisku** [comment]
@Rjchauhan18 This issue is closed bro.
