### ISSUE TITLE
[BUG][FormTribe 🔥][100 Points] Are you Sure modal Missing

### ISSUE THREAD

**Issue by ShubhamPalriwala** [formbricks/formbricks#1419]
### Issue Summary

Whenever a user made changes to a survey and the clicked on the Back button, we'd send them a modal popover confirming if they want to Discard their changes or save them. Looks like our modal is lost somewhere now haha! Please see the attached video that reproduces the bug.

### Steps to Reproduce

1. Create any survey
2. Publish it
3. Now Edit the Survey (make 1+ changes)
4. Now click on the Back Button
5. You will be taken back with your changes discarded

### Expected behavior

Before Step 5 above, the user should be popped with a confirmation Are you Sure message 

### Screenshots

https://tella.video/are-you-sure-modal-missing-18o5

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by adityadeshlahre** [comment]
i would like to take this ! :smile:

**Comment by RajuGangitla** [comment]
can u assign this to me

**Comment by ShubhamPalriwala** [comment]
Yours @adityadeshlahre for the next 24 hours atleast!

**Comment by SumanKisku** [comment]
I would like to work on this too

**Comment by venk404** [comment]
I would like to work on this too

**Comment by adityadeshlahre** [comment]
Hey @ShubhamPalriwala 
thank you for previous 24 hours to solve this issue
Maybe i am over-complicating things i am sure other contributers
will present more optimal solution i will dive into code more thoroughly
Thank You :smile: 

@RajuGangitla is next in a row !
you can start working on this issue.

**Comment by ShubhamPalriwala** [comment]
Thanks! Over to you now

**Comment by karthiknadar1204** [comment]
@ShubhamPalriwala of this issue is not resolved yet,i would like to work on it

**Comment by ShubhamPalriwala** [comment]
This has been fixed! Apologies for not closing this earlier :/
