### ISSUE TITLE
[FEATURE][FormTribe 🔥][150 Points] Dynamic metadata for new Docs

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1428]
### Is your feature request related to a problem? Please describe.

The page title (and other meta data) on the Docs subpages is always the same:

<img width="240" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/568b06e0-41f5-4d05-a2e1-a4934fb96b30">

### Describe the solution you'd like

Use nextJS metadata API to create dynamic page title and description for each page.

**Comment by KapadiaNaitik** [comment]
I would like to work on this

**Comment by shyamraghu** [comment]
Can i work on this

**Comment by SumanKisku** [comment]
I would like to work on this issue

**Comment by ruhani2** [comment]
I would like to work on this.

**Comment by PentesterPriyanshu** [comment]
please assign this to me  @jobenjada  i am making pr on this thank you

**Comment by guptaG1410** [comment]
Hey @jobenjada, 
I hope you're doing well. So, It looks like you want to make the page title and other meta data on the Docs subpages dynamic by using Next.js's metadata API. To achieve this, you can follow these steps:

1. Create a Custom Layout Component:
You can create a custom layout component for your Docs subpages where you set the dynamic metadata. For example, you could create a file like components/DocLayout.js:
```
import Head from 'next/head';

function DocLayout({ title, description, children }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        {/* Add other meta tags as needed */}
      </Head>
      {children}
    </div>
  );
}

export default DocLayout;
```

2. Use the Custom Layout in Your Pages:
In your Doc subpages, import and use this custom layout component, passing the appropriate title and description for each page. For example:

```
import DocLayout from '../components/DocLayout';

function DocPage() {
  const pageTitle = 'Your Page Title';
  const pageDescription = 'Description for your page';

  return (
    <DocLayout title={pageTitle} description={pageDescription}>
      {/* Your page content */}
    </DocLayout>
  );
}

export default DocPage;
```

**Comment by Shub3am** [comment]
@jobenjada PR request submitted

**Comment by Shub3am** [comment]
Now We need to define the title in individual page.mdx and pass it in the exported metadata object or manually add the title

**Comment by vikaspatil0021** [comment]
@Shub3am Add few screenshots or videos of title changing with pages

**Comment by thanmaisai** [comment]
can i work on this ?

**Comment by kurayami07734** [comment]
May I work on this?

**Comment by raghavnagar7** [comment]
Hey @jobenjada,
I hope you're doing well. So, It looks like you want to make the page title and other meta data on the Docs subpages dynamic by using Next.js's metadata API. To achieve this, we can follow these steps:

Create a Custom Layout Component:
We can create a custom layout component for your Docs subpages where you set the dynamic metadata. For example, we could create a file like components/DocLayout.js:
import Head from 'next/head';

function DocLayout({ title, description, children }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        {/* Add other meta tags as needed */}
      </Head>
      {children}
    </div>
  );
}

export default DocLayout;
Use the Custom Layout in our Pages:
In our Doc subpages, import and use this custom layout component, passing the appropriate title and description for each page. For example:
import DocLayout from '../components/DocLayout';

function DocPage() {
  const pageTitle = 'Your Page Title';
  const pageDescription = 'Description for your page';

  return (
    <DocLayout title={pageTitle} description={pageDescription}>
      {/* Your page content */}
    </DocLayout>
  );
}

export default DocPage;
