### ISSUE TITLE
[BUG] Theme is not persisted on main website

### ISSUE THREAD

**Issue by Olaleye-Blessing** [formbricks/formbricks#1437]
### Issue Summary

The theme selected by a user is not being persisted after refreshing the page.

### Steps to Reproduce

1. Go to the [https://formbricks.com/](https://formbricks.com/)
2. Switch to light mode
3. Refresh the page
4. Notice it goes back to dark mode

### Expected behavior

Theme shouldn't switch back to default theme after refreshing the page.

### Other information

The issue could be resolved by either updating the [theme script](https://github.com/formbricks/formbricks/blob/main/apps/formbricks-com/pages/_document.tsx#L3) or making use of [next-themes package](https://www.npmjs.com/package/next-themes)

#
I'll like to work on it

### Screenshots

https://github.com/formbricks/formbricks/assets/70102539/96ae22c1-35ac-475c-b557-a5c2d364ab71

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- Browser: Brave
```

**Comment by lokeshvasnik** [comment]
I would like to work on this issue.

**Comment by ShubhamPalriwala** [comment]
Hey @Olaleye-Blessing, thanks for opening the issue! I'd like to inform you and @lokeshvasnik that we're not taking anymore PRs regarding the landing page,  as we want to focus on the core product during the last week of the Formtribe hackathon.

Please focus your efforts on finding bugs in the core product 🙏
