### ISSUE TITLE
[FEATURE] Dark Mode toggle switch not persisted below medium breakpoint 

### ISSUE THREAD

**Issue by professssor** [formbricks/formbricks#1442]
### Is your feature request related to a problem? Please describe.

The Dark mode toggle switch isn't accessible when the viewport breakpoint goes below medium.
The hamburger navigation is neat but a dark mode toggle can still be rendered alongside it without causing any hindrance to the UI.

### Describe the solution you'd like

we can remove the CSS that hides the DARK MODE toggle below a certain breakpoint.

I can work on this if is recognized as an issue by Mods

**Comment by ShubhamPalriwala** [comment]
Hey @professssor, thanks for opening an issue! Hope you are enjoying Formbricks! You are correct about the toggle not being available for smaller screens. However, we'll be soon going through a landing page revamp so we'll keep this in mind there! Thanks again 🚀 

If you do catch any bugs inside our app, definitely let us know and we'd be super responsive in helping you fix that

**Comment by professssor** [comment]
cool
