### ISSUE TITLE
[BUG] In Concierge, Dark mode not applying on the Concierge Card section

### ISSUE THREAD

**Issue by itzabhinavarya** [formbricks/formbricks#1447]
### Issue Summary

In Concierge, Dark mode not applying on the Concierge Card section
This section theme should be dark when the dark mode applied.

Issue:
<img width="960" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/582886e9-08a4-4e7b-bf3d-868b4ed7863e">

### Steps to Reproduce

Navigate to Concierge
URL : https://formbricks.com/concierge
 Look at the first section/card.

### Expected behavior

In Dark Mode : 
<img width="960" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/b672dd14-48cd-491d-b322-879f9c77af7e">

In Light Mode : 
<img width="960" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/50f92b0d-f1a4-49d3-a799-a319b797949f">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Not required
- Node:Not required
- npm: Not required
```

**Comment by itzabhinavarya** [comment]
@ShubhamPalriwala @jobenjada Kindly assign this issue to me, I'll take care of it.
Thanks :)

**Comment by jobenjada** [comment]
hey hey! 

The dark mode does not apply to the Cal card either and so it looks kind of odd if only once card is dark mode compatible. And we're not taking anymore PRs regarding the LP, we gotta focus on the core product during the last week. 

Please focus your efforts on finding bugs in the core product 🙏

**Comment by itzabhinavarya** [comment]
@jobenjada Understood, Thanks.
