### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Enhancing Formbricks Documentation: Clear Steps for Configuring Environment ID

### ISSUE THREAD

**Issue by thanmaisai** [formbricks/formbricks#1472]
### Issue Summary

```NEXT_PUBLIC_FORMBRICKS_ENVIRONMENT_ID``` in the documentation was a bit unclear, leading you to seek additional information in Discord chats. To improve the documentation, I'd suggest adding a note or a dedicated page that provides clear instructions and possibly includes screenshots to guide users through the process of changing the ```NEXT_PUBLIC_FORMBRICKS_ENVIRONMENT_ID```. This enhancement would likely help users navigate this specific configuration more easily. Feel free to share any specific details or steps you think would be helpful, and I can help you draft a concise and informative note or page for the documentation.

### Steps to Reproduce

1. Visit [Formbricks](https://formbricks.com/docs/contributing/gitpod)
2. Go through **Initialization of formbricks section**.

### Expected behavior

To improve the documentation, I'd suggest adding a note or a dedicated page that provides clear instructions and possibly includes screenshots to guide users through the process of changing the ```NEXT_PUBLIC_FORMBRICKS_ENVIRONMENT_ID```

### Screenshots

<img width="817" alt="Screenshot 2023-10-27 at 7 53 09 AM" src="https://github.com/formbricks/formbricks/assets/91474486/c6c2eed4-8558-4973-85b2-e62f0fc941fa">

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: MacOS
- Node: v18.18.1
- npm: 9.8.1
```

**Comment by thanmaisai** [comment]
Hey @ShubhamPalriwala, could you please assign me to this issue so that I can get started on it?

**Comment by jobenjada** [comment]
@thanmaisai it's yours, pls go ahead :)

**Comment by thanmaisai** [comment]
Hey @jobenjada, i am facing some issues with dev setup, once i fix it, i will fix the issue and  raise the PR.

**Comment by SahilDahekar** [comment]
hey , Can i work on this issue ?

**Comment by jobenjada** [comment]
adjusted points due to small change :)
