### ISSUE TITLE
[BUG] Formbricks settings sidebar is not scrollable 

### ISSUE THREAD

**Issue by ratishjain12** [formbricks/formbricks#1476]
### Issue Summary

![image](https://github.com/formbricks/formbricks/assets/43003421/8bec6ad0-bde9-43d5-8abc-e7ea856533fc)
@jobenjada @ShubhamPalriwala currently sidebar is not scrollable and the text is getting cut 
I want to fix this kindly assign it to me :)

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

-

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by devuser200** [comment]
@ratishjain12  I think this is similar issue to this: #1190
