### ISSUE TITLE
[Enhancement]  Improve UI Design of AddNoCodeEventModalDummy Component

### ISSUE THREAD

**Issue by moheyt** [formbricks/formbricks#1478]
### Is your feature request related to a problem? Please describe.

The "AddNoCodeEventModalDummy" component in application currently lacks an optimal user interface (UI) design, which may lead to user confusion and a subpar user experience. This issue report highlights the problems with the existing design and proposes solutions for improvement.

![Screenshot 2023-10-27 205251](https://github.com/formbricks/formbricks/assets/85775976/d61e9bde-0ee7-4b61-8e1c-92062cb61853)

### Describe the solution you'd like

Improved the visual design of the AddNoCodeEventModalDummy component to enhance its overall appearance without altering its functionality.

**Comment by jobenjada** [comment]
hey! As mentioned before, please focus your efforts on finding bugs in our core product, not our landing page. 

We have no capacity to handle these PRs. Thanks!! :)
