### ISSUE TITLE
[BUG] Email Preview: Skip welcome card for preview

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1491]
### Issue Summary

Currently, the Welcome Card gets displayed in the email preview.

Instead, we want to display the first question of the survey to optimize conversion. If the user just wants to link to the survey, she could create a button in their email tool which would keep the look and feel of their email more consistent. I doesn't add a lot of value to prefill the Welcome Card start button.

### Steps to Reproduce

Look at email preview for link survey with Welcome card

### Expected behavior

Skip Welcome Card in email preview, instead display first acutal question

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by RajuGangitla** [comment]
@jobenjada can i work on this

**Comment by kundan766** [comment]
I want to work on this issue .please assign me this issue
