### ISSUE TITLE
[BUG] Unable to update Profile Avatar

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1499]
### Issue Summary

https://github.com/formbricks/formbricks/assets/84387676/1a7fa5f8-d006-41c5-90db-2682c5b99355

Unable to change my profile avatar.

### Steps to Reproduce

1. Go to: https://app.formbricks.com/
2. Clicked on: Profile 
3. Avatar
Assist your team in identifying you on Formbricks.

### Expected behavior

.

### Other information

.

### Screenshots

.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Node: v18.15.0
- npm: 9.6.2
```

**Comment by mattinannt** [comment]
Will be solved with #1546
