### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SankarshanMishra** [formbricks/formbricks#1503]
### Issue Summary

After I have opened dark mode in Bestpractices and I have to open concierge, The dark mode is automatically turned off.

### Steps to Reproduce

1.  Went to home page of frombricks
2. Clicked on darkmode
3. Clicked on concierge 

### Expected behavior

Expected to show dark mode when opening concierge.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11 Home Single Language
- Node:18.14.1
- npm: 9.3.1
```

**Comment by neilchauhan2** [comment]
Hi @SankarshanMishra, thank you for taking the time to looking into this issue, but currently we are only focusing on the issues that directly impact the formbricks app and not the landing page. So, I'm closing this issue for now. If you find some other issue related to the formbricks app will be happy to look into it.
