### ISSUE TITLE
[BUG] Able to create multiple Team with same name

### ISSUE THREAD

**Issue by mittalsam98** [formbricks/formbricks#1512]
### Issue Summary

I am able to create multiple team with same name. This will create confusion for user

Loom video for the bug
https://www.loom.com/share/852dba6a9c424989b1b654bf3222ef97

### Steps to Reproduce

1. Do to Dashbaord
2. Clicked on User Icon on the top right side
3. Go to Team section and click on create team 
OR
3. Go to profile and create team from there

### Expected behavior

Ideally, this shouldn't happen and it should throw error while creating team with existing team name. This way user will get to know how the different team are distinguished

### Other information

I would like to raise a fix if this is approved

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Linux
- Node:
- npm:
```

**Comment by jobenjada** [comment]
We discussed this and are allowing teams with the same names - thanks anyways! :)
