### ISSUE TITLE
[BUG] Error in Docs navigation

### ISSUE THREAD

**Issue by bilalmirza74** [formbricks/formbricks#1518]
### Issue Summary

when clicking on From Source it's going back to Docker/Updating Formbricks 

https://github.com/formbricks/formbricks/assets/84387676/0ea4bfe1-336b-475b-95cb-5264ab87c1f1

### Steps to Reproduce

1. Go to : https://formbricks.com/docs/self-hosting/docker
2. Clicked on: From Source

### Expected behavior

.

### Other information

.

### Screenshots

.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@bilalmirza74 please remove the link in the navigation :-)
