### ISSUE TITLE
[BUG] Text fields with different validations get wrongfully prefilled

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1520]
### Issue Summary

When a URL input follows an email input, the filled in data is not getting removed:

https://github.com/formbricks/formbricks/assets/72809645/23af6dff-b0cc-4ad4-8dbf-5dec2ef753ef

Same is true for phone number questions following on number questions - and vice versa.

### Steps to Reproduce

1. Create a survey with the questions mentioned above
2. Go through it (see video)

### Expected behavior

The input should reset to 0

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Shyam-Raghuwanshi** [comment]
Hi, can i work on this

**Comment by yatharth1706** [comment]
@jobenjada would love to fix this.
