### ISSUE TITLE
[BUG] Unable to add member if not providing the Role field

### ISSUE THREAD

**Issue by mittalsam98** [formbricks/formbricks#1523]
### Issue Summary

1. When I am adding a member without providing the Role ,getting some weird error.
2. When adding same email again, error should be more specific.
https://www.loom.com/share/7345a333ed614b7ca772f105e4595dcf

### Steps to Reproduce

1. Go to Member page under settings
2. Try to add the member with Empty Role field 

### Expected behavior

Ideally either disable the button if Field is required or make the error more specific for better user experience.

### Other information

I would love to pick this up

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by adityadeshlahre** [comment]
wth bro u steel the bug i talked about this in discord !

chat : https://discord.com/channels/979077669410979880/979079530524344390/1168444273444794418

@mattinannt look :rofl:

**Comment by mattinannt** [comment]
@adityadeshlahre No need to rush conclusions and accuse contributors ;-) @mittalsam98 could also stumbed over this himself while testing Formbricks and it seems like the bug wasn't raised on Github before. Regarding formtribe points we can find a solution here.

@jobenjada fyi

**Comment by mittalsam98** [comment]
> wth bro u steel the bug i talked about this in discord !
> 
> chat : https://discord.com/channels/979077669410979880/979079530524344390/1168444273444794418
> 
> @mattinannt look 🤣

@adityadeshlahre I found this myself while testing. I have raised few other bugs as well today and I don't have that xtra time to look into chats of other people

**Comment by mittalsam98** [comment]
@mattinannt I was working on this issue 🥺

**Comment by adityadeshlahre** [comment]
Sorry @mittalsam98 this was imeance confusion from my side thing can be done is splitting of points !
