### ISSUE TITLE
[BUG] Progress bar appears as mostly full when still towards the beginning of the survey

### ISSUE THREAD

**Issue by Kyle-Alongside** [formbricks/formbricks#1525]
### Issue Summary

![image](https://github.com/formbricks/formbricks/assets/128392447/120ee6e8-0db6-4e88-8c94-78da0826248c)

### Steps to Reproduce

1. Went to https://app.formbricks.com/s/cloczsbjo0rc4qc0fijms1f21
2. Clicked through a few questions
3. Saw that the progress bar reached a mostly full state a few questions in and stayed in the same place as I clicked through more questions

### Expected behavior

The progress bar accurately reflects how many questions I've completed vs. how many I have left

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Macbook
- Node: Chrome
- npm:
```

**Comment by adityadeshlahre** [comment]
This looks like feature ! 
[ if founded as bug i would like to give a try ]
Thank you :smile:

**Comment by admehta01** [comment]
How does this feature work?

It feels like a bug (can repro it on the link provided). The progress bar looks 95% full when the user is only half done with the survey.

**Comment by ksushant6566** [comment]
Hey @mattinannt, I just raised a PR #1638 that fixed this issue, please have a look.
