### ISSUE TITLE
[BUG] After deleting account we can't able to login or signup from the email 

### ISSUE THREAD

**Issue by Shyam-Raghuwanshi** [formbricks/formbricks#1526]
### Issue Summary

When we delete our account we can able to continue with the deleted account email they shows a error "email is already exit"

https://www.loom.com/share/b5fe0dae080345eb9f1582e083362f2e?sid=6f70d157-e356-4878-a330-e0242d21f39b

### Steps to Reproduce

1. delete account
2. try sign in or sign up

### Expected behavior

Expected behavior should be the login or signup should working with the deleted account's email

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: windows
- Node:
- npm:
```

**Comment by Sukomal07** [comment]
@Shyam-Raghuwanshi everything is fine , after delete account i can  login or signup  with the deleted account's email
