### ISSUE TITLE
[BUG] Autoclose on inactivity not displayed properly

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1529]
### Issue Summary

When you set "Auto Close on Inactivity" the time tracker only opens for a split second:

<img width="1305" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/ded9c4c8-a043-4c64-a015-2bcab31aa46b">

### Steps to Reproduce

1. Create a web app survey
2. Toggle "Auto Close on Inactivity"

### Expected behavior

1. Display the countdown indicator correctly
2. Animate the survey out and in again to indicate in the preview that the auto close worked.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by adityadeshlahre** [comment]
I would like to give it a try :smile: !

**Comment by mattinannt** [comment]
@adityadeshlahre what's the current status on the issue?

**Comment by mattinannt** [comment]
@adityadeshlahre No worries, thanks for the update 😊

**Comment by SaiSawant1** [comment]
Is this issue still open? I would like to work on it.

**Comment by mattinannt** [comment]
@SaiSawant1 thank you. I will assign the issue to you.
We previously had a autoclose progressbar that went from 100% to 0% in the specified amount of time unless the user hovers over the survey.
https://github.com/formbricks/formbricks/blob/a74037dca18ac2f65dea1700ada66ca08c386ad8/packages/js/src/components/SurveyView.tsx#L281
This behaviour got lost when we moved to the new surveys package. The task is to readd this functionality to the new surveys package 😊

**Comment by SaiSawant1** [comment]
@mattinannt is this issue on a specific branch? I am on the main branch where I am not able to reproduce the issue.

**Comment by SaiSawant1** [comment]
@mattinannt I checked and the autoClose progress bar at the top of the survey is working fine. It is going 100% to 0% in time. Am I missing something.
