### ISSUE TITLE
[BUG] widgetSetupIndicator not working

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1531]
### Issue Summary

As you see here, the Formbricks app received an event and an attribute but it's still indicating that the widget has not been connected yet:

<img width="1264" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/64e8cefc-1dbd-4755-96cb-e15c8937af6c">

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

Update the widgetSetupIndicator (or so) variable works as supposed :)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
Is now fixed with formbricks 1.3.0
