### ISSUE TITLE
[BUG] self-hosting gets Too many requests, Please try after a while! error on login page

### ISSUE THREAD

**Issue by hmmftg** [formbricks/formbricks#1533]
### Issue Summary

Hi, I've followed all steps in [quick start guide](https://formbricks.com/docs/self-hosting/docker) to start an self-hosted formbricks server, after successful install I was able to open site on browser, but any attempt to login or signup(at remote client or even on server) is failed displaying this message:
```
An error occurred when signing you up
Too many requests, Please try after a while!
```

### Steps to Reproduce

1. docker compose up -d
2. open http://server:3000
3. try to login or signup

### Expected behavior

successful signup and login

### Other information

logs:
```
~/formbricks-quickstart$ docker compose up
[+] Running 3/3
 ✔ Network formbricks-quickstart_default         Created                                                                              1.3s 
 ✔ Container formbricks-quickstart-postgres-1    Created                                                                              3.4s 
 ✔ Container formbricks-quickstart-formbricks-1  Created                                                                              3.9s 
Attaching to formbricks-quickstart-formbricks-1, formbricks-quickstart-postgres-1
formbricks-quickstart-postgres-1    | 
formbricks-quickstart-postgres-1    | PostgreSQL Database directory appears to contain a database; Skipping initialization
formbricks-quickstart-postgres-1    | 
formbricks-quickstart-postgres-1    | 2023-10-31 06:21:10.620 UTC [1] LOG:  starting PostgreSQL 15.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
formbricks-quickstart-postgres-1    | 2023-10-31 06:21:10.620 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
formbricks-quickstart-postgres-1    | 2023-10-31 06:21:10.620 UTC [1] LOG:  listening on IPv6 address "::", port 5432
formbricks-quickstart-postgres-1    | 2023-10-31 06:21:10.867 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
formbricks-quickstart-postgres-1    | 2023-10-31 06:21:11.142 UTC [24] LOG:  database system was shut down at 2023-10-31 06:20:56 UTC
formbricks-quickstart-postgres-1    | 2023-10-31 06:21:11.252 UTC [1] LOG:  database system is ready to accept connections
formbricks-quickstart-formbricks-1  |  WARN  The "workspaces" field in package.json is not supported by pnpm. Create a "pnpm-workspace.yaml" file instead.
formbricks-quickstart-formbricks-1  | .local/share/pnpm/store/v3/tmp/dlx-8     | Progress: resolved 1, reused 0, downloaded 0, added 0
formbricks-quickstart-formbricks-1  | .local/share/pnpm/store/v3/tmp/dlx-8     | Progress: resolved 1, reused 0, downloaded 1, added 0
formbricks-quickstart-formbricks-1  | .local/share/pnpm/store/v3/tmp/dlx-8     |   +2 +
formbricks-quickstart-formbricks-1  | .../node_modules/@prisma/engines postinstall$ node scripts/postinstall.js
formbricks-quickstart-formbricks-1  | .local/share/pnpm/store/v3/tmp/dlx-8     | Progress: resolved 2, reused 0, downloaded 2, added 2, done
formbricks-quickstart-formbricks-1  | .../node_modules/@prisma/engines postinstall: Done
formbricks-quickstart-formbricks-1  | .../prisma@5.5.2/node_modules/prisma preinstall$ node scripts/preinstall-entry.js
formbricks-quickstart-formbricks-1  | .../prisma@5.5.2/node_modules/prisma preinstall: Done
formbricks-quickstart-formbricks-1  | Environment variables loaded from .env
formbricks-quickstart-formbricks-1  | Prisma schema loaded from packages/database/schema.prisma
formbricks-quickstart-formbricks-1  | Datasource "db": PostgreSQL database "formbricks", schema "public" at "postgres:5432"
formbricks-quickstart-postgres-1    | 2023-10-31 06:21:25.602 UTC [28] LOG:  could not receive data from client: Connection reset by peer
formbricks-quickstart-formbricks-1  | 
formbricks-quickstart-formbricks-1  | 50 migrations found in prisma/migrations
formbricks-quickstart-formbricks-1  | 
formbricks-quickstart-formbricks-1  | 
formbricks-quickstart-formbricks-1  | No pending migrations to apply.
formbricks-quickstart-formbricks-1  |    ▲ Next.js 14.0.0
formbricks-quickstart-formbricks-1  |    - Local:        http://localhost:3000
formbricks-quickstart-formbricks-1  |    - Network:      http://0.0.0.0:3000
formbricks-quickstart-formbricks-1  | 
formbricks-quickstart-formbricks-1  |  ✓ Ready in 93ms
```

### Screenshots

![formbricks-login-error](https://github.com/formbricks/formbricks/assets/7557453/7cab15f1-abee-4d1d-b110-f9ea352ad6e2)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Ubuntu 22.04.3 LTS (GNU/Linux 6.2.0-36-generic x86_64)
- Node: v12.22.9
- npm: 8.5.1
```

**Comment by ShubhamPalriwala** [comment]
Hey @hmmftg, is your `process.env.NODE_ENV` set to "production"? We currently skip rate limiting if its set to anything but production. Please let me know on this

**Comment by vanphuoc3012** [comment]
hey I have the same issue. Here is the logs from docker 
`[next-auth][error][JWT_SESSION_ERROR] 
https://next-auth.js.org/errors#jwt_session_error Invalid Compact JWE {
  message: 'Invalid Compact JWE',
  stack: 'JWEInvalid: Invalid Compact JWE\n' +
    '    at compactDecrypt (/home/nextjs/apps/web/.next/server/chunks/8743.js:6:6932)\n' +
    '    at jwtDecrypt (/home/nextjs/apps/web/.next/server/chunks/8743.js:6:35214)\n' +
    '    at Object.decode (/home/nextjs/apps/web/.next/server/chunks/8743.js:30:17298)\n' +
    '    at async Object.session (/home/nextjs/apps/web/.next/server/chunks/8743.js:30:6991)\n' +
    '    at async AuthHandler (/home/nextjs/apps/web/.next/server/chunks/8743.js:6:108501)\n' +
    '    at async getServerSession (/home/nextjs/apps/web/.next/server/chunks/8743.js:30:20700)\n' +
    '    at async AuthLayout (/home/nextjs/apps/web/.next/server/chunks/1448.js:1:9245)',
  name: 'JWEInvalid'
}`

**Comment by ShubhamPalriwala** [comment]
Can reproduce this locally, on it!

**Comment by ShubhamPalriwala** [comment]
Hey, thanks for the patience! We have found the bug and are now working on the pipeline to get it out to y'all! Thanks for reporting. Will ping here once its up and you can go ahead

**Comment by alcnsahin** [comment]
I have the same problem after installing the production version.

formbricks-formbricks-1  | Environment variables loaded from .env
formbricks-formbricks-1  | Prisma schema loaded from packages/database/schema.prisma
formbricks-formbricks-1  | Datasource "db": PostgreSQL database "formbricks", schema "public" at "postgres:5432"
formbricks-formbricks-1  | 
formbricks-formbricks-1  | 50 migrations found in prisma/migrations
formbricks-formbricks-1  | 
formbricks-formbricks-1  | 
formbricks-formbricks-1  | No pending migrations to apply.
formbricks-formbricks-1  |    ▲ Next.js 14.0.0
formbricks-formbricks-1  |    - Local:        http://localhost:3000
formbricks-formbricks-1  |    - Network:      http://0.0.0.0:3000
formbricks-formbricks-1  | 
formbricks-formbricks-1  |  ✓ Ready in 367ms
formbricks-formbricks-1  | **Rate Limiting IP:  82.3.-.-**


![image](https://github.com/formbricks/formbricks/assets/7150214/7669e4ba-bd12-46d9-8514-89315800fe49)

**Comment by pedrofnts** [comment]
Same problem here.

**Comment by stupidoes** [comment]
> Same problem here.
> 
> @ShubhamPalriwala any way to skip rate limit in production?

If you use One-Click Setup method, there's RATE_LIMITING_DISABLED=1 inside docker-compose.yml that you need to uncomment.
