### ISSUE TITLE
[BUG] cURL example for "Create Survey" API endpoint is wrong

### ISSUE THREAD

**Issue by salim-b** [formbricks/formbricks#1555]
### Issue Summary

See the cURL example for [Create Survey](https://formbricks.com/docs/api/management/surveys#create-survey) in the docs.

It correctly states

> `POST /api/v1/management/surveys`

but then below uses HTTP `DELETE` instead of `POST`:

> ```
> curl -X DELETE \
> 'https://app.formbricks.com/api/v1/management/surveys' \
> --header \
> 'x-api-key: <your-api-key>'
> ```

Just wanted to let you know. ☺️

### Steps to Reproduce

Visit  [Create Survey](https://formbricks.com/docs/api/management/surveys#create-survey)  and see for yourself.

### Expected behavior

A correct cURL example.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- Documentation
```

**Comment by shashankshet** [comment]
Hello Team,
can you please assign this issue to me? I'd love to fix this issue

**Comment by ShubhamPalriwala** [comment]
Hey @salim-b, thanks for pointing it out 🙏🏼 @shashankshet looking forward to your quick fix today 🤞🏼
