### ISSUE TITLE
[BUG]  Not Getting verification email for sign up while running locally 

### ISSUE THREAD

**Issue by lalitkumawat1m** [formbricks/formbricks#1557]
### Issue Summary

When I setup the project locally run it on localhost:3000 and try to sign up with email I'm not getting a verification email.

### Steps to Reproduce

1. (for example) Went to ... signup page 
2. Clicked on the signup button 
3. ... check if you getting a verification email

### Expected behavior

I should receive a verification email for signup locally

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Node:18.16.0
- npm: 9.5.1
```

**Comment by priyanshu2k3** [comment]
@lalitkumawat1m you need to keep the docker up and running you will recieve the mail in the mail hogger at the localhost:8025

**Comment by lalitkumawat1m** [comment]
@priyanshu2k3 Thank you, Let me try it first.

**Comment by lalitkumawat1m** [comment]
@priyanshu2k3 Thanks brother you are a legend it's working 

Finally I setup formbricks locally after facing lots of errors.
