### ISSUE TITLE
Misleading pricing page: File Upload and potentially other features?

### ISSUE THREAD

**Issue by DitlevHB** [formbricks/formbricks#1565]
### Issue Summary

I was surprised to see that the File Upload feature is included on the pricing page https://formbricks.com/pricing, but it's not ready to use in the product. This is misleading and left me with a poor experience. I now wonder if there are other items in the feature list of the pricing page that is not implemented. I suggest to only include implemented features in the pricing page for the sake of transparency.

Regarding the File Upload feature, I found that it is being worked on here:
https://github.com/formbricks/formbricks/pull/1277

### Steps to Reproduce

1. Go to https://formbricks.com/pricing and look for File Upload in "Link Link Surveys" column.
2. Login to the app, make a new form, add question, and notice that there is no File Upload option.

### Expected behavior

Fileupload should not be there until implemented and released.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
Windows
```

**Comment by ShubhamPalriwala** [comment]
Hey @DitlevHB, thanks for opening an issue! First of all, I'd like to deeply apologise for the inconsistency in the pricing table outside and inside the app! We'll fix it at the highest priority.
