### ISSUE TITLE
[BUG] Error when building docker image from source

### ISSUE THREAD

**Issue by rhortal** [formbricks/formbricks#1571]
### Issue Summary

When building the docker image from source using `docker compose`, an error informs us that the ENCRYPTION_KEY environment variable must be exactly 64 characters. 
The placeholder in docker-compose.yml is 32, as are the instructions on how to generate a new key

### Steps to Reproduce

1. `git clone` this repo.
2. `cd repo-folder` 
3. `docker compose up -d`
4. Error: @formbricks/web:build: ❌ Invalid environment variables: { ENCRYPTION_KEY: [ 'String must contain exactly 64 character(s)' ] }

### Expected behavior

Image is created and container started

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Mac OS ventura (Intel)
- Node: 
- npm:
```

**Comment by mattinannt** [comment]
@rhortal thanks for the report, can you maybe share the full logs as the error might be a different one.
By the way we don't officially support building Formbricks from source anymore and only use this for testing in development. Please use our official Docker images:
https://formbricks.com/docs/self-hosting/deployment

**Comment by rhortal** [comment]
In that case I guess best to close it.
