### ISSUE TITLE
[FEATURE] If text field is short answer, ENTER should submit

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1573]
### Is your feature request related to a problem? Please describe.

<img width="649" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/52fe9b92-b7dd-4f83-9f38-faffecbf170e">

When a text field is not a long answer, ENTER should submit the form:

<img width="943" alt="Screenshot 2023-11-03 at 19 07 41" src="https://github.com/formbricks/formbricks/assets/72809645/afd21ce2-208d-48dc-95d6-9a97fd2cec97">

### Describe the solution you'd like

When a text field is not a long answer, ENTER should submit the form

**Comment by mittalsam98** [comment]
Hey @jobenjada can I work on this?

**Comment by venk404** [comment]
Hey @jobenjada can I work on this?
