### ISSUE TITLE
[BUG] Invalid `prisma.user.create()` invocation for google & github signup

### ISSUE THREAD

**Issue by ksushant6566** [formbricks/formbricks#1610]
### Issue Summary

Invalid `prisma.user.create()` invocation throws following error: 

_Unknown argument `eventClasses`. Available options are marked with ?._

### Cause of error:
Model **_EventClass_** doesn't exist anymore in the current schema but this invocation expects it.

This happens because EventClass was recently replaced by ActionClass in the #1470, but the `prisma.user.create` invocation in  **_signin_** callback of authOptions still sends EventClasses instead of ActionClasses

And hence while signing up using google/github, a 400 bad request screen appears.
<img width="1438" alt="image" src="https://github.com/formbricks/formbricks/assets/50081688/bc0c3590-2018-4e1a-be43-f0caf040a193">

### Steps to Reproduce

1. Register using github or google

### Expected behavior

Usual registration without any errors

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@ksushant6566 thanks for pointing that out 😊 we will fix this asap 💪

**Comment by ksushant6566** [comment]
Happy to help!
I have also raised a PR #1611  that fixes this issue, please check it out.
