### ISSUE TITLE
[BUG] unable to copy links on use single links feature 

### ISSUE THREAD

**Issue by hmmftg** [formbricks/formbricks#1614]
### Issue Summary

when we choose to create single use links, in publish window copy button does not work(clipboard is empty) and logs this error in console:

```
caught TypeError: Cannot read properties of undefined (reading 'writeText')
    at handleLinkOnClick (1103-e0a21fb869396bb6.js:1:32885)
    at onClick (1103-e0a21fb869396bb6.js:1:34308)
    at Object.Ii (bf6a786c-e2d916e5746737a3.js:9:71635)
    at Oi (bf6a786c-e2d916e5746737a3.js:9:71789)
    at bf6a786c-e2d916e5746737a3.js:9:138255
    at Pn (bf6a786c-e2d916e5746737a3.js:9:138354)
    at an (bf6a786c-e2d916e5746737a3.js:9:138768)
    at bf6a786c-e2d916e5746737a3.js:9:144901
    at Ck (bf6a786c-e2d916e5746737a3.js:9:92613)
    at nl (bf6a786c-e2d916e5746737a3.js:9:121897)
```

## Scenario1:
1. create new survey 
2. in settings menu on **Response Options** select **Single-Use Survey Links**
3.  go to publish window
4. click on copy
## Scenario2:
1. edit any survey 
2. in settings menu on **Response Options** select **Single-Use Survey Links**
3.  save survey
4. click on share button
5. click on copy

### Expected behavior

clipboard should contain link data

### Screenshots

![Screenshot_20231114_162826](https://github.com/formbricks/formbricks/assets/7557453/2579eb38-4d13-493e-946e-96aab1e6a5b5)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Ubuntu 22.04.3 LTS (GNU/Linux 6.2.0-36-generic x86_64)
- Node: v12.22.9
- npm: 8.5.1
```

**Comment by mattinannt** [comment]
@hmmftg thanks for reporting this :-) 
@Dhruwang Can you maybe take a look at this?

**Comment by mattinannt** [comment]
@hmmftg Unfortunately we weren't able to reproduce the issue. Are you running the latest version of Formbricks? And does this issue occur with and without encryption for single use links enabled?

**Comment by hmmftg** [comment]
Hi again, thanks for your response, encryption for single use links is **enabled** and we're using: **formbricks:1.2.2**

**Comment by gupta-piyush19** [comment]
Hey @hmmftg, it seems like you're running the app on Gitlab(on HTTP protocol). Clipboard API only works on secure browsing(on HTTPS protocol) for safety purposes. We can look for a polyfill, though.
More context: https://bobbyhadz.com/blog/navigator-clipboard-is-undefined-in-javascript

**Comment by ShubhamPalriwala** [comment]
Hey @hmmftg, I just tried all 3 scenarios:
- Local Setup
- Advanced Docker Setup
- GitPod Setup

And in all 3 cases, the copying is working fine!

1 possible reason that I can think of is that you are on **Node v12.22** and we now build on top of **atleast v18** (recommended is Node 20 though). So can you upgrade your Node instance and give this another try?

**Comment by hmmftg** [comment]
Hi, as I'm trying to suggest formbricks to company managers, it's not possible to use company's https proxy, I need time to do that and report here, or we can close this and reopen on next step.
thanks for your support

**Comment by jobenjada** [comment]
@hmmftg any updates on your side? :)

**Comment by mattinannt** [comment]
@hmmftg We also revamped the Survey Link sharing experience in the meantime. If the error still exists on the current release, please reach out and we will reopen this issue 😊
