### ISSUE TITLE
[BUG]Correction in the Preview section

### ISSUE THREAD

**Issue by asif-reh** [formbricks/formbricks#1642]
### Issue Summary

![Formbricks - Google Chrome 11_20_2023 9_00_07 PM](https://github.com/formbricks/formbricks/assets/59223152/dae9a56e-c1d1-4153-b7fc-104af0695628)

### Steps to Reproduce

There is a small mistake in the preview section just a correction to be done.

### Expected behavior

What is the main benefit you receive from Demo Product?

### Screenshots

![Formbricks - Google Chrome 11_20_2023 9_00_07 PM](https://github.com/formbricks/formbricks/assets/59223152/a42449e4-74a8-4465-b9c0-34c517f04f6f)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@asif-reh thanks for pointing this out :-) Do you want to correct the mistake yourself or should I assign someone from the team? :-)

**Comment by Mudit-Jxin7** [comment]
@asif-reh If you are not solving this issue , Can I ?

**Comment by asif-reh** [comment]
> @asif-reh thanks for pointing this out :-) Do you want to correct the mistake yourself or should I assign someone from the team? :-) 

I will solve this issue.

**Comment by asif-reh** [comment]
@mattinannt assign the issue to me.I have fixed the bug also.

**Comment by asif-reh** [comment]
@mattinannt did you accept the pull request of mine and merge it?

**Comment by mattinannt** [comment]
No, if you had only fixed the typo it would have been easier. Now I need to check back with the team if this change of wording affects the template ;-)

**Comment by mattinannt** [comment]
@asif-reh Please fix only the typo `your` -> `you` and we are able to merge it pretty quickly :-)

**Comment by asif-reh** [comment]
@mattinannt Done

**Comment by mattinannt** [comment]
thank you 😊🙏

**Comment by asif-reh** [comment]
Thank you @mattinannt This is my first open source issue.Thank you for your support. I hope to contribute more to feature development soon.
