### ISSUE TITLE
[BUG] Support Arm

### ISSUE THREAD

**Issue by danielehrhardt** [formbricks/formbricks#1664]
### Issue Summary

I tried to install Formbricks on a Arm Ubuntu Server from Hetzner i get this message:
```
/bin/sh: 109: [[: not found
📥 Downloading docker-compose.yml from Formbricks GitHub repository...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2791  100  2791    0     0  11169      0 --:--:-- --:--:-- --:--:-- 11208
🚙 Updating docker-compose.yml with your custom inputs...
🚗 NEXTAUTH_SECRET updated successfully!
🚗 ENCRYPTION_KEY updated successfully!
/bin/sh: 153: [[: not found
awk: cmd. line:9: warning: escape sequence `\`' treated as plain ``'
[+] Running 0/3
 ⠸ formbricks Pulling                                                                                                             1.3s 
 ⠸ traefik Pulling                                                                                                                1.3s 
 ⠸ postgres Pulling                                                                                                               1.3s 
no matching manifest for linux/arm64/v8 in the manifest list entries
```

### Steps to Reproduce

1. Install Formbricks on a Arm Server:
2. https://formbricks.com/docs/self-hosting/production

### Expected behavior

As far as i can see in the code it can also work on arm servers.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Ubuntu 22 / Arm
```

**Comment by mattinannt** [comment]
Thanks for the issue :-) 
We are currently building a new docker build pipeline for images and will for this also add images for arm architecture. I hope this will be ready for the next release beginning of next week :-)

**Comment by danielehrhardt** [comment]
> Thanks for the issue :-) We are currently building a new docker build pipeline for images and will for this also add images for arm architecture. I hope this will be ready for the next release beginning of next week :-)

ok, great. Let me know if i should test something.

**Comment by Inder782** [comment]
Me too, always interested to learn Dev-ops stuff

> > Thanks for the issue :-) We are currently building a new docker build pipeline for images and will for this also add images for arm architecture. I hope this will be ready for the next release beginning of next week :-)
> 
> ok, great. Let me know if i should test something.

**Comment by danielehrhardt** [comment]
@mattinannt have you pushed it already?

**Comment by mattinannt** [comment]
Update: We have provided a Github action that also builds an image for ARM architecture, but unfortunately the build process took 6 hours, which is not suitable for production. We will experiment further and see if we can build this with Github Actions in an acceptable timeframe.
Until then, building the image from source on ARM architecture seems to be the only choice.

**Comment by danielehrhardt** [comment]
> Update: We have provided a Github action that also builds an image for ARM architecture, but unfortunately the build process took 6 hours, which is not suitable for production. We will experiment further and see if we can build this with Github Actions in an acceptable timeframe.
> Until then, building the image from source on ARM architecture seems to be the only choice.

Why does it take so long?

**Comment by mattinannt** [comment]
@danielehrhardt I ran the build again on our current codebase and now it's at least "only" taking about an hour. But this also very long compared to the ~8min that the amd64 build takes.
You can find the Github Action run here: https://github.com/formbricks/formbricks/actions/runs/7207961431/job/19635892919

I would guess it has to do with some kind of emulation that the Github Action needs to do for arm architecture, but not sure about this.

**Comment by mattinannt** [comment]
@danielehrhardt Did you found out anything how this Github action can be improved? 😊

**Comment by danielehrhardt** [comment]
> https://github.com/formbricks/formbricks/actions/runs/7207961431/job/19635892919

Not really, i asked a friend he will also check.

**Comment by kymppi** [comment]
Yep. Github Actions do not natively support ARM building so it has to be emulated. One solution to this would be self-hosting a github action runner on ARM for the ARM builds.

However Github is planning on adding native arm. Currently in private beta. https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/

**Comment by danielehrhardt** [comment]
If you want i can provide a arm github self hosting server. Send me a Mail to daniel.ehrhardt@codext.de and we can configure it.

**Comment by mattinannt** [comment]
@danielehrhardt We now got the new release workflow live in production (using a third party builder).
Formbricks v1.5.0 is the first release where we offer an official ARM build 😊🚀
https://github.com/formbricks/formbricks/pkgs/container/formbricks/171539806?tag=v1.5.0

**Comment by danielehrhardt** [comment]
> @danielehrhardt We now got the new release workflow live in production (using a third party builder). Formbricks v1.5.0 is the first release where we offer an official ARM build 😊🚀 https://github.com/formbricks/formbricks/pkgs/container/formbricks/171539806?tag=v1.5.0

Awesome!! Thank you.
