### ISSUE TITLE
[FEATURE] Date Picker Field

### ISSUE THREAD

**Issue by Glassback** [formbricks/formbricks#1711]
### Is your feature request related to a problem? Please describe.

I was wondering how to use Formbricks for an onboarding form connected to N8N for new employees.

I'm looking to have a date picker field...

### Describe the solution you'd like

A date picker to validate the type of data

### Describe alternatives you've considered

I can use text field but not the best way...

**Comment by Vishrut19** [comment]
Can I work on this issue?

**Comment by karthiknadar1204** [comment]
@Glassback if this issue is up for grabs,I would like to work on it,please assign it to me

**Comment by mattinannt** [comment]
The issue was a bit more complex due to the required sideloading functionality to not bloat the formbricks-js library. Now merged and closed with https://github.com/formbricks/formbricks/pull/1660
