### ISSUE TITLE
[BUG] Drop Off Analyser does not work for surveys with conditional fields

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#1713]
### Issue Summary

Currently the drop-off rate is calculated using the view count of the previous row which is not necessarily the actual previous question when having a conditional logic.

## Current bahaviour
Depending on their answer to question 1, the users see either question 2 or 3. The drop-off rate is obviously way off:
![image](https://github.com/formbricks/formbricks/assets/64426524/7fa65abe-8585-4fcd-9a5d-985fa50c3ded)

## Solution
To me it seems logical to calculate it with this formula: (#drop-offs)/(#views)
![image](https://github.com/formbricks/formbricks/assets/64426524/de58c3b5-8d4d-4afe-8bbe-14ac1d7451ee)

Alternative solution using the number of times this survey was displayed / opened:
![image](https://github.com/formbricks/formbricks/assets/64426524/989e5a64-322d-4181-bd9f-c8b5320368be)

### Steps to Reproduce

1. create a survey with a conditional logic
2. get some responses
3. check drop-off rate

### Expected behavior

The drop-off rate is determined by dividing the number of users who exited at this question by the frequency at which this question was shown.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
Independent of platform
```

**Comment by mattinannt** [comment]
Thanks for reporting this :-) 
@Dhruwang Can you please take a look 😊
