### ISSUE TITLE
[BUG] App is stuck at welcome screen after first login

### ISSUE THREAD

**Issue by tvankith** [formbricks/formbricks#1741]
### Issue Summary

After logging to app, app freezes at welcome screen. please watch attached video

https://github.com/formbricks/formbricks/assets/22615249/be10d274-a1b0-4383-9bf5-b9ca894abf81

### Steps to Reproduce

1. Login to the app
2. At 66% completion of welcome screen, app is stuck, Also button animation is broken

### Expected behavior

Successfully navigate to app

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Ubuntu 20
- Browser: Brave
```

**Comment by mattinannt** [comment]
@tvankith thanks for reporting the bug :-) Is it working if you reload the page or go again to https://app.formbricks.com/onboarding ?
Do you see error messages in the browsers inspect console? (right click, inspect -> console)

**Comment by tvankith** [comment]
@mattinannt Now it is working, except "I'll do it later" option

https://github.com/formbricks/formbricks/assets/22615249/9cc71ee0-e7cd-4025-9916-0a39b392f956

https://github.com/formbricks/formbricks/assets/22615249/73052d30-24f9-4bda-ae6d-86fc49ae8808
