### ISSUE TITLE
[BUG] Mobile preview is broken

### ISSUE THREAD

**Issue by tvankith** [formbricks/formbricks#1743]
### Issue Summary

Mobile preview is broken, but actual form preview is fine

### Steps to Reproduce

1. Upload a company logo image in welcome card
2. Compare Actual Mobile form preview & Mobile preview

### Expected behavior

Mobile preview and actual form look same

### Screenshots

![actual-mobile-view](https://github.com/formbricks/formbricks/assets/22615249/4cdb2862-39e9-41fe-a9b3-2b96d7c1d73e)
![Screenshot from 2023-12-05 15-16-49](https://github.com/formbricks/formbricks/assets/22615249/1ee66bf7-a6a7-4762-9ed8-a1ab04fc02e9)
![pepsi-vertical-logo-72846897FF-seeklogo com](https://github.com/formbricks/formbricks/assets/22615249/8528a3b8-f090-4de6-862e-2eb369a8a975)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Ubuntu 20
- Browser:Chrome
```

**Comment by deepanshimarsha** [comment]
Hello, @pandeymangg, kindly upload the logo within the question and refrain from including it in the welcome card. Thank you.

**Comment by jobenjada** [comment]
closing this, seems like its solved :)
