### ISSUE TITLE
[BUG] After you remove a user from their only team, they can no longer log in

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#1816]
### Issue Summary

When you remove a member from a team (and it was the only team the user was in), this user can no longer log in and is redirected to the login page without an error message.

### Steps to Reproduce

1. Team owner invites new user 
2. This user registers using the invite link (make sure this user is only in one team)
3. Team owner removes this user from the team
4. The new user can no longer log in (when logging in, he is redirected to the log in page without getting any error message)

### Expected behavior

Option a) If the user is removed from their only team, the entire account is deleted so that no orphaned account is created
Option b) The orphaned user is treated as a new user and can create a new team, delete their account, etc.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- Browser: chrome, firefox
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich Thanks for raising the issue :-) 
Yes, maybe it makes sense now that we build some kind of "create first team" onboarding that appears when no team is found.
Currently, as a workaround for leaving a team, we show a separate warning that they need to create another team first, but this obviously doesn't work for removing someone from a team.
With a separate onboarding, we can remove this workaround as well.

**Comment by ksushant6566** [comment]
> @jonas-hoebenreich Thanks for raising the issue :-) Yes, maybe it makes sense now that we build some kind of "create first team" onboarding that appears when no team is found. Currently, as a workaround for leaving a team, we show a separate warning that they need to create another team first, but this obviously doesn't work for removing someone from a team. With a separate onboarding, we can remove this workaround as well.

"Create first team" seems like the correct approach. I'll be open to building it!

**Comment by mattinannt** [comment]
@ksushant6566 Thanks for the offer 💪 We should design the feature first to make sure the user flow works as expected and the design fits with the rest of the Formbricks UI.

@jobenjada Can you create a UI mockup for the create team (onboarding) flow we use when the user does not have a team?

**Comment by ksushant6566** [comment]
Cool I'll wait for the UI mockup

**Comment by jobenjada** [comment]
oh hey! Sorry I missed this over the holidays, will provide the needed UI asap @ksushant6566 @jonas-hoebenreich

**Comment by ksushant6566** [comment]
No worries,just lmk when the mock up is ready and I'll start working on it.

**Comment by jobenjada** [comment]
hey @ksushant6566 looked into it now and we have a bigger Onboarding revamp planned, to support three different cases:

- Link Survey: Get to published survey asap to shorten viral loop
- In app survey: Assist in setting up SDK to get users activated properly
- Sign up for self-hosting license: Helps us measure self-hosted instances

from a product perspective, I don't think it makes sense to build a separate onboarding flow for people who don't have a team yet. And since they don't have any "own" surveys or submissions which would get lost, so I would rather go with Option A and just delete the account. The user would then just create a new account and go through the regular onboarding - imo the pareto solution.

Will double check with Matti on Monday and update you!

**Comment by ksushant6566** [comment]
Understood, option A of deleting the account might get confusing for people as this isn't an action that the user is taking themselves , causing them to loose their account. I think creating a default/personal team (undeletable) at signup would be the right way for new users. For existing users this can be created when they are removed from their only team or preferably on their next login.

**Comment by mattinannt** [comment]
@ksushant6566 We now decided to go with the following approach:
• When a user gets removed from their only team their account still exists (but they are not part of any team)
• When they login the next time they get redirected to `/create-first-team` where they can create their first team
![image](https://github.com/formbricks/formbricks/assets/675065/d93e0c83-b8f3-4d29-8a17-c0e2af4d1580)
• After clicking `Create team` a new team is created using a server action
• Please also update the workflow for deleting a team: A user should now also be able to delete their only team. After this they will get redirected to the `/create-first-team` route as they don't have a team yet.

Thank you for tackling this issue! I will assign the issue to you :-) When do you think you can open a PR for this? 💪

**Comment by ksushant6566** [comment]
Cool, I am a bit occupied today so it'll probably take till tmrw. Does that work?

**Comment by mattinannt** [comment]
> Cool, I am a bit occupied today so it'll probably take till tmrw. Does that work?

sure :-)

**Comment by jobenjada** [comment]
@ksushant6566 any updates? :)

**Comment by ksushant6566** [comment]
Hey sorry this slipped, will try to raise a PR by tmrw. :)

**Comment by mattinannt** [comment]
@ksushant6566 Thanks for solving this issue 😊💪

@jonas-hoebenreich The changes are now live in main and will be also included in the next release tomorrow :-)
