### ISSUE TITLE
[BUG][🕹️] Dynamic Link Preview broken incl. shortened links

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1819]
### Issue Summary

This issue has two elements:

1. The Dynamic Link Preview does not work anymore:

_// solved_

2. The Link Preview does not (and maybe never did) work for Shortened URLs.

In Formbricks, you can shorten URLs via the top right menu:

<img width="258" alt="Screenshot 2023-12-21 at 14 43 34" src="https://github.com/formbricks/formbricks/assets/72809645/091d94cf-d68b-44c4-a269-37a3fc7b69d0">

The shortened links do not have a preview:

<img width="363" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/d076e7e4-01c1-471a-899e-0224d8e46881">

Please fix it :)

### Steps to Reproduce

1. Create a link survey
2. Share URL in any service which creates link previews
3. Shorten URL and try again

### Expected behavior

Same dynamic link preview for both

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by adityadeshlahre** [comment]
i would like to give it a try :smiley: !

**Comment by Dhruwang** [comment]
Sure, go for it @adityadeshlahre 😊🚀

**Comment by adityadeshlahre** [comment]
Seems like 

1 Dynamic Link Preview works fine 
![previewWorking](https://github.com/formbricks/formbricks/assets/132184385/6b0c48d0-0154-4339-9f95-92628ffc0305)


2 Shortened URLs Link Previews are dead 
![previewDead](https://github.com/formbricks/formbricks/assets/132184385/b93be004-f3ba-4b92-9752-52a5081bb63d)


on the way to fix :smiley:

**Comment by jobenjada** [comment]
@adityadeshlahre any updates? :)

**Comment by adityadeshlahre** [comment]
Hey @jobenjada @Dhruwang 
really sorry for late replay 
i am still trying to fix the bug !

I got to know which component is responsable for image generation [[file]](https://github.com/formbricks/formbricks/blob/main/apps/web/app/api/v1/og/route.tsx)
but stuck on how the file is getting called at time of publishing New Survey

For now preview image generation is only happening for main /s/[surveyId] link only
and not for the short URL /[shortUrlId] link.

need more lights on the bug !

**Comment by jobenjada** [comment]
hmm @mattinannt maybe you have an idea?

**Comment by mattinannt** [comment]
@adityadeshlahre Yes, this is the right endpoint for generating the image :-)
The image from the og endpoint is used in the `generateMetadata` function of the  `/s/[surveyId]` page:
https://github.com/formbricks/formbricks/blob/be4534da2d8d7bd197a40a87fc9d32ed2bf06fac/apps/web/app/s/%5BsurveyId%5D/page.tsx#L63

So one thing you could try is to also add a generateMetadata` function to `apps/web/app/[shortUrlId]/page.tsx`.

**Comment by jobenjada** [comment]
@adityadeshlahre will you pick this up again? :)

**Comment by adityadeshlahre** [comment]
Hey @jobenjada sorry for not responding for way long !

would like get this issue unassigned for now .

I think i will take back seat and learn from the changes if anyone 
contributes on this issue :slightly_smiling_face: 

Thank You

**Comment by mattinannt** [comment]
No worries, thanks for trying to solve it 😊💪
