### ISSUE TITLE
WordPress Plugin UX Update

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1820]
### Issue Summary

Currently, it's really non confusing to setup the Formbricks Plugin correctly.

### Steps to Reproduce

1. Watch someone try setting it up :)

### Expected behavior

Here is a revamped Formbricks Plugin UI:

<img width="1027" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/ea47a04a-6631-4e20-8450-e2be9a66f3e5">

Notes:

**Setup Checklist Section** 

1. In the Setup Checklist in Step 1 we link to `https://app.formbricks.com/auth/signup`
2. Step 4 the Step by Step guide I can add once the plugin UI is updated bc I want to include pics

**Configure Formbricks Section**

1. The API Host Field should be prefilled with `https://app.formbricks.com`
2. Debug Mode: It doesnt have to be a toggle ;) Checkbox would also work

**Enable Formbricks Section**
1. The text should also toggle between "Formbricks is running ✅" and "Formbricks is deactivated"
2. Same with the step by step guide like above - I can write it

That should make it much more straight forward to get started with Formbricks :)

# Thanks 🙏 🙏 🙏 

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mcnaveen** [comment]
Done: https://github.com/formbricks/wordpress/pull/3

**Comment by ShubhamPalriwala** [comment]
Hey, just reviewing the plugin now, here are my 2 cents:

- In the navbar, can we restrict the size of our logo on scale with the other icons to make it look uniform? It currently looks out of place
![image](https://github.com/formbricks/formbricks/assets/55556994/75fe8a01-f961-400f-a865-e9a00149013e)

- Is the bottom placeholder "Thank you for creating with [WordPress](https://wordpress.org/)." necessary? Can it be removed?

- You missed the "What now" section from the prototyping given above by Johannes.

Rest all looks good to me now, thanks again! 💪🏼 

These changes will make it pretty solid imo 🤞🏼

**Comment by mcnaveen** [comment]
Everything is resolved and merged. [PR#4](https://github.com/formbricks/wordpress/pull/4)

> Thank you for creating with WordPress is not injected by our plugin. It's done by the WordPress itself. t's better if our styles aren't conflicting with the default WP styles.
