### ISSUE TITLE
[FEATURE] Status or Healthcheck Endpoint 

### ISSUE THREAD

**Issue by abebars** [formbricks/formbricks#1840]
### Is your feature request related to a problem? Please describe.

Looking to deploy this on K8s and I am not sure that I was able to find a status check or health check endpoint for the container.

### Describe the solution you'd like

Provide `/healthz` or `/status` that will return 200.

If required we may any additional checks that might be needed.

**Comment by jobenjada** [comment]
hey @abebars 

thanks for your request - and sorry for the slower response over the holidays 🎆 

Matti will get back to you asap.

Thanks!

**Comment by mattinannt** [comment]
@abebars Yes, that might make sense. For now, you can go the `/auth/login` route for this.
I will write a ticket to create a proper health check endpoint that also checks the database connection and thus gives a better picture of the full availability and readiness of the system.

**Comment by ShubhamPalriwala** [comment]
Hey @abebars, feel free to use the `/health` endpoint now that handles the health check! For our cloud instance, its available at: https://app.formbricks.com/health

**Comment by abebars** [comment]
@ShubhamPalriwala Awesome, thank you
