### ISSUE TITLE
[FEATURE] Hover over multiple-choice entry to see more information

### ISSUE THREAD

**Issue by antoneklund** [formbricks/formbricks#1862]
### Is your feature request related to a problem? Please describe.

Hello! I think this is an amazing tool since I can add some custom functionality. Maybe someone can point me in the right direction here.

I want to create a survey that contains a multiple-choice question where I basically want the participant to error-label articles from classification. Each choice is a title of an article (as shown in the first image).  However, sometimes more information than the title is needed to make a decision.

![formbricks_weather](https://github.com/formbricks/formbricks/assets/17433481/9785cb60-1676-4b19-8a86-8c6ce60eec21)

### Describe the solution you'd like

 I want the text body to be shown when hovering over the title (second image). Alternatively have a little "read text" button next to the title that expands the text or show it in a text box on the side.

I don't want to simply add all the text body to the choice as that will quickly become messy and annoying for the participant to scroll and read.

Is there a built-in solution for this or some place in the code where I can edit to get this functionality?

![formbricks_weather_hover](https://github.com/formbricks/formbricks/assets/17433481/9722a0cb-9dda-4c5c-9c31-ba310787ebf2)

**Comment by mattinannt** [comment]
@antoneklund Thanks for reaching out. We don't currently have a solution like that, and I'm not sure about the tooltip solution since hovers don't work well on mobile.
We also don't have something on the roadmap for this yet, as this hasn't been requested before. Maybe you can split it into multiple questions that you solve with a call-to-action question:

<img width="564" alt="Screenshot 2024-01-10 at 12 03 01" src="https://github.com/formbricks/formbricks/assets/675065/3cd493e8-a9f2-4a3f-9352-05ea3e9c25c1">

**Comment by antoneklund** [comment]
Thank you for your response! 
I see! Your solution would be good for a general error-labeling task. However, with the study I want to do, I need the participant to see the other articles on the same screen to put them into context with each other. I realize the hover-function might not be of general use to motivate it being an added feature. 

If I would like to attempt this for my own branch, is it possible to do? Would I look into MultipleChoiceSingleQuestion?

**Comment by mattinannt** [comment]
@antoneklund Yes, you would need to edit the form in the editor as well as the multi language survey component.

multiple choice form: https://github.com/formbricks/formbricks/blob/main/apps/web/app/(app)/environments/%5BenvironmentId%5D/surveys/%5BsurveyId%5D/edit/components/MultipleChoiceMultiForm.tsx
multiple choice survey component: https://github.com/formbricks/formbricks/blob/main/packages/surveys/src/components/questions/MultipleChoiceMultiQuestion.tsx

You might also update the Question type to support the new option: https://github.com/formbricks/formbricks/blob/ff864e3c82e6a80a67fc50fb4bd4de83b708c052/packages/types/surveys.ts#L281C1-L281C1

**Comment by mattinannt** [comment]
Closing this for now. Please reach out if we can assist more :-)
