### ISSUE TITLE
[BUG] process.env exported in formbricks pixel

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#1889]
### Issue Summary

The compiled Formbricks pixel includes process.env values. While it seems not to contain security-related information, there are notable concerns:
a) It includes potentially confidential details, such as file paths from the system of the person compiling the code.
b) It introduces unnecessary bloat (about 6kb) to a pixel that should ideally be as compact as possible.
c) Future modifications to process.env might result in the inadvertent leakage of secret values.

![image](https://github.com/formbricks/formbricks/assets/64426524/dd78d22d-13af-4982-b45d-d71e732df46c)

### Steps to Reproduce

1. search **https://unpkg.com/@formbricks/js@1.4.1/dist/index.umd.js** for "matthiasnannt" 

### Expected behavior

This issue is resolved when you hardcode the src in DateQuestion.tsx. I would suggest to find a solution that evaluates the mode on build time.

![image](https://github.com/formbricks/formbricks/assets/64426524/72c34e81-6abe-4083-b60f-c830caf40f80)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich thanks for reporting. We will tackle the issue asap :-) 💪

**Comment by jonas-hoebenreich** [comment]
I guess https://github.com/formbricks/formbricks/pull/1893 resolved this issue, right?

**Comment by mattinannt** [comment]
@jonas-hoebenreich Yes, that's right :-) Seems like it wasn't linked to this issue. Since this is resolved, I will close the issue 😊
