### ISSUE TITLE
[BUG] Error 500 Occurs When Adding Code Action with Duplicate Identifier

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#1895]
### Issue Summary

When attempting to add a code action with an identifier that is already assigned to another action, the server returns a 500 error. The accompanying error message is uninformative and does not provide meaningful guidance. This issue needs to be addressed more gracefully to enhance user experience.

Note: I apologize for the numerous bug reports; my intention is solely to contribute to the improvement of the product :)

### Steps to Reproduce

1. create a code action with identifier "aaa"
2. try to create a second code action with identifier "aaa"
3. see error

![image](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/87d2f0cd-97ba-469f-bc87-18862d2fa78f/450c8686-4283-44c8-a3ee-8e24998a92e9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC84N2QyZjBjZC05N2JhLTQ2OWYtYmM4Ny0xODg2MmQyZmE3OGYvNDUwYzg2ODYtNDI4My00NGM4LWEzZWUtOGUyNDk5OGE5MmU5IiwiaWF0IjoxNzA1MDUyOTExLCJleHAiOjE3MDUxMzkzMTF9.AgFb9ifQIp-1YkAiGH3oFVgIKcY2rk7KOtPVJ8Bwfzg)

### Expected behavior

Upon attempting to add a code action with a duplicate identifier, Formbricks should handle the situation gracefully by providing a clear and informative error message. Instead of a server error, the user should receive a prompt indicating that the identifier is already in use, along with guidance on how to resolve the naming conflict (e.g. "The identifier 'your_identifier' is already in use for another code action. Please choose a unique identifier for the new action to avoid conflicts.").

### Other information

*No response*

### Screenshots

*No response*

### Environment

- [X] Formbricks Cloud ([app.formbricks.com](http://app.formbricks.com))
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```
- OS:
- Node:
- npm:
```

<sub>From [SyncLinear.com](https://synclinear.com) | [FOR-1682](https://linear.app/formbricks/issue/FOR-1682/[bug]-error-500-occurs-when-adding-code-action-with-duplicate)</sub>

**Comment by mattinannt** [comment]
@jonas-hoebenreich No worries, your bug reports are very welcome 🤗.
I will write a ticket to the team for this 💪

**Comment by mattinannt** [comment]
@jonas-hoebenreich we just merged the fix into main 😊 
thanks to @Dhruwang for the quick turnaround 💪🚀
