### ISSUE TITLE
[FEATURE] Multi-language interface

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1909]
### Is your feature request related to a problem? Please describe.

Not everyone is comfortable using a product in English

### Describe the solution you'd like

Offer different languages

### Additional context

User request

**Comment by jobenjada** [comment]
At of now, we've postponed a multi language user interface because it slow iteration speed.

**Comment by Khaan25** [comment]
This would take up some time to add support for the whole app.

Don't you think we should do in steps?
For example,

I can handle the landing page
Another guy can handle dashboard pages etc.

Don't you think it's a good idea?

**Comment by mattinannt** [comment]
We just shipped support for English, German and Portuguese. French is currently in the translation process :-) 💪🚀
