### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'ok')

### ISSUE THREAD

**Issue by danilofuchs** [formbricks/formbricks#1916]
### Issue Summary

Found this issue on Sentry after upgrading to @formbricks/js 1.4.2:

![image](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/c3ae8ee5-808d-4834-b23d-d307e3adeb50/c5ba4649-3936-4084-a9bb-79c74f44d1cb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC9jM2FlOGVlNS04MDhkLTQ4MzQtYjIzZC1kMzA3ZTNhZGViNTAvYzViYTQ2NDktMzkzNi00MDg0LWE5YmItNzljNzRmNDRkMWNiIiwiaWF0IjoxNzA1NTY4MzgxLCJleHAiOjMzMjc2MTI4MzgxfQ.ev89Z0OOVG6GHArksi8Ufpajvt5UJ2WhDP49peYAt8o)

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

No error thrown

### Other information

@formbricks/js 1.4.2

### Screenshots

*No response*

### Environment

- [X] Formbricks Cloud ([app.formbricks.com](http://app.formbricks.com))
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```
- OS:
- Node:
- npm:
```

**Comment by jobenjada** [comment]
we'll look into it, thanks for surfacing this! :)

**Comment by mattinannt** [comment]
@danilofuchs We solved this issue today with this PR https://github.com/formbricks/formbricks/pull/1937/files (Thanks @pandeymangg for solving this 🔥💪)
