### ISSUE TITLE
[BUG] Missing link in navigation toolbar

### ISSUE THREAD

**Issue by gschnaub** [formbricks/formbricks#1917]
### Issue Summary

The navigation toolbar on the left-hand side of the docs is missing a link for `Responses API` under the `Management API` section

### Steps to Reproduce

1. Navigate to https://formbricks.com/docs/api/client/overview#management-api
2. Compare the list in the body of the page to the links on the left-hand side in the navigation toolbar

### Expected behavior

All API docs should be discoverable from the navigation toolbar

### Other information

https://github.com/formbricks/formbricks/blob/main/apps/formbricks-com/components/docs/Navigation.tsx#L282

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/16309512/19185ff3-58dd-4169-a01a-f54597320a68)
![image](https://github.com/formbricks/formbricks/assets/16309512/468abe54-6ddb-4fff-b0e4-e39320082d8c)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Browser: Firefox
```

**Comment by jobenjada** [comment]
thanks a lot! will push the fix in 5 minutes - good catch 🤓
