### ISSUE TITLE
[BUG] Share Feature Prone to Misunderstanding

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#1926]
### Issue Summary

We recently encountered an incident where a user unintentionally exposed survey results to the public while intending to share the survey link internally. This inadvertent action poses a significant risk of data leakage. Fortunately, the survey was not yet live at the time. To enhance the share feature and mitigate such risks, we propose the following adjustments:

- Precise Wording:
Current: "Publish Results"
Proposed: Change to "Publicly Publish Results"
Rationale: Adding the term "Publicly" helps to clarify the nature of the action, reducing the likelihood of unintentional data exposure.
- Additional Option for Internal Sharing:
Proposed: Introduce a second option - "Copy Link for Internal Sharing"
Rationale: Providing a dedicated option for internal sharing aligns with user expectations and minimizes the risk of accidental public disclosure.
- Warning for Unauthenticated Access:
Proposed: Include a warning that clarifies results can be accessed without authentication when shared via the link.
Rationale: Alerting users about potential risks associated with unauthenticated access ensures informed decision-making during the sharing process.
- Enhanced Visibility of Public Results:
Proposed: Make the public status of results more visible by adding a prominent warning, such as "Results Currently Set to Public."
Rationale: Improved visibility ensures users are aware of the current sharing status, reducing the likelihood of unintentional public sharing.

I can open a pull request to address this if you want.

### Steps to Reproduce

1. Click in "Share"

### Expected behavior

Nobody accidentally publishes results when they just want to share the survey internally.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich thank your for creating the issue. This makes sense 😊
It would be very cool if you could open a pull request for this 🚀💪

**Comment by jobenjada** [comment]
hey Jonas! I had some objections re your wording but picked up your suggestions (i.e. adding a Copy Link CTA). I also separated Sharing Survey from Sharing Results to make it more clear. 

The changes are merging, let me know if that works for you - happy to tweak it if not!
