### ISSUE TITLE
[BUG] when uploading certain files the file upload question breaks the whole survey

### ISSUE THREAD

**Issue by Nick-v-L** [formbricks/formbricks#1930]
### Issue Summary

After doing a file upload for a video with the size of 43 MB it gives a 400 error. It seems to break with everything of a size that is bigger them 10MB (which is the limit if I am looking into the code). This also happens when uploading a file that has a type that is nog supported (for example .txt).
![image](https://github.com/formbricks/formbricks/assets/12459538/092b2884-6d91-4a04-bca9-fb15a93891cf)

After I then complete the survey it keeps on saying uploading.
![image](https://github.com/formbricks/formbricks/assets/12459538/11fb8946-3f5f-4286-ac0c-4625d88666e9)

Because of the failed file upload I am unable to see all past responses from the survey.
![image](https://github.com/formbricks/formbricks/assets/12459538/bfa577b4-7e64-4bc5-8501-d72e125981ed)

### Steps to Reproduce

1. Create a new survey with a file upload. (Don't change any question settings).
2. Upload a file which is larger then 10 MB or an unsupported file type (for example .txt) and finish the survey.
3. Try to access the responses of the survey.

### Expected behavior

The video uploads, or it gives a message that it failed to upload. But this should never be able to break the whole survey which restricts access to the previous responses.

### Other information

Also experiencing this issue on my self hosted instance. Temporary work around is to set the max file upload to 10MB. This prevents the uploading from files that are bigger then 10MB. This does not fix the wrong file type issue because this only puts a filter on the input file (which off course can be disabled by selecting "all file types *.*).

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: Chrome 
- Version: 1.4.2
```

**Comment by Nick-v-L** [comment]
Did some more investigation, same result when uploading an unsupported file type, for example .txt.

**Comment by mattinannt** [comment]
@Nick-v-L Thanks for reporting this. We will look into it asap and try to reproduce the issue :-)

**Comment by mattinannt** [comment]
@Nick-v-L We merged a PR today that tackle this issue 😊
https://github.com/formbricks/formbricks/pull/1936

Thanks to @pandeymangg for the quick turnaround 🤗🔥
