### ISSUE TITLE
[BUG] Comments Not Immediately Displayed When Added to Response

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#1945]
### Issue Summary

When attempting to add a comment to a response, the comment does not appear immediately. It only becomes visible after reloading the page.
While not critical, this bug is still annoying and impacts the user experience.

### Steps to Reproduce

1. Open the Responses Tab of a survey.
2. Attempt to add a comment to the response.
3. Observe that the comment is not immediately displayed.
4. Reload the page.
5. Notice that the comment now appears as expected.

### Expected behavior

Adding a comment to a response should dynamically update the display without requiring a page reload, providing a seamless user experience.

### Screenshots

[scrnli_23_01_2024_12-59-16.webm](https://github.com/formbricks/formbricks/assets/64426524/d59cacfa-0892-4c81-b718-a36b445753b1)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- Chrome 120
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich This was fixed in https://github.com/formbricks/formbricks/pull/1957 and is included in the v1.5.0 release 😊
