### ISSUE TITLE
[FEATURE] Enhance Export: Include Response Tags and Comments in Downloads

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#1946]
### Is your feature request related to a problem? Please describe.

In the current export functionality, response tags and comments are not included in CSV/Excel files. This absence complicates the analysis process and diminishes the exported data's richness.

### Describe the solution you'd like

We propose adding the capability to incorporate response tags and comments in the exported files. This improvement would empower users to maintain context and insights associated with each response, streamlining the analysis process.

Benefits:
- Context Retention: Including response tags and comments ensures that the exported data retains valuable contextual information, facilitating a more comprehensive understanding of responses.
- Efficient Analysis: Users can seamlessly conduct detailed analysis and reporting without the need to cross-reference with the platform.

**Comment by mattinannt** [comment]
@jonas-hoebenreich makes sense :-) I write tickets for this to add both tags and response notes to the export 👍

**Comment by mattinannt** [comment]
@jonas-hoebenreich We have a PR open for this. Should get merged very soon after some tweaks :-) 
https://github.com/formbricks/formbricks/pull/1968
