### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'ok') after 1.4.2

### ISSUE THREAD

**Issue by hudovisk** [formbricks/formbricks#1959]
### Issue Summary

After we upgraded to 1.4.2 we started to see the following error in Sentry:

<img width="916" alt="image" src="https://github.com/formbricks/formbricks/assets/5161722/7720a223-010e-4eb1-b5f5-7d8e1826051e">

<img width="319" alt="image" src="https://github.com/formbricks/formbricks/assets/5161722/17e8e6ce-618c-4c77-9632-6fe2451b88fc">

I think it is related to this PR: https://github.com/formbricks/formbricks/pull/1863

I believe this is a bug since it started only after the upgrade but could also be a mi-use from our side. Not sure if it helps but this are the logs we got from sentry:
<img width="907" alt="image" src="https://github.com/formbricks/formbricks/assets/5161722/942ff00e-362d-406b-9c2b-86b8ccf0f0eb">

Let me know if you need more info.

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

Should not throw exception

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@hudovisk This is now fixed with `@formbricks/js` 1.5.0 😊
https://github.com/formbricks/formbricks/pull/1937/files
