### ISSUE TITLE
[BUG] Phone Field Usability

### ISSUE THREAD

**Issue by starlight-akouri** [formbricks/formbricks#1963]
### Issue Summary

The phone field type is strangely difficult to use. It does validation that requires a country code, which, in the USA is very uncommon for non-technical people to enter. As a result it causes a lot of churn when people can't figure out how to get past this validation pattern.

Maybe the phone validatino pattern shouldn't be so strict, or alternatively allow the form creator to specify whether or not they want to collect country code

### Steps to Reproduce

1. Create any survey with a Phone Number input
2. Attempt to complete the survey by entering a 10-digit phone number with area code.

### Expected behavior

Validation should pass

### Other information

*No response*

### Screenshots

*No response*

### Environment

- [X] Formbricks Cloud ([app.formbricks.com](http://app.formbricks.com))
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```
- OS: Mac OS X Chrome
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@starlight-akouri This is a great suggestion. We will check on this issue and come up with a solution to solve this for all international phone numbers 😊

**Comment by jobenjada** [comment]
@Dhruwang please take away the validation for the phone number to make this field easier to fill :) Later on, we might sideload a selection field where people can type in the country and the country code is prefilled.

**Comment by mattinannt** [comment]
@starlight-akouri The validation has now been modified and loosened up a bit to work with phone numbers without country code 😊.
