### ISSUE TITLE
[FEATURE] Enhance Action/Trigger Management for Scalability

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#1967]
### Is your feature request related to a problem? Please describe.

The current approach for defining actions and triggers lacks scalability, particularly in cases where actions are predominantly single-use and specific to individual surveys. To address this, we propose an enhancement that combines reusable actions on a dedicated Actions page with the ability to create on-the-fly, single-use triggers directly within survey settings.

### Describe the solution you'd like

The proposed solution aims to improve the scalability of action and trigger management by introducing the following features:

**Reusable Actions/Triggers:**
Users can define and manage reusable actions/triggers on the Actions page, streamlining the process for scenarios where actions are shared across multiple surveys.

**Single-Use Triggers On-the-Fly:**
On the survey settings page, users can create single-use triggers specific to that survey, eliminating clutter by keeping survey-specific actions isolated.
![image](https://github.com/formbricks/formbricks/assets/64426524/d84ad655-9a74-48b6-881e-cb7b8bc65fab)
On-the-Fly targeting in Hotjar

**Ideal Solution:**
Balancing flexibility and scalability, the ideal implementation includes:
- An Actions page for defining and managing reusable actions.
- On-the-fly creation of single-use triggers within the survey settings for survey-specific needs.

**Comment by ksushant6566** [comment]
This does make sense, I'll be open to building this  🛠️

**Comment by mattinannt** [comment]
jonas-hoebenreich Thanks for the issue, this makes sense :-) We need some time to plan this better from a UX perspective.

@ksushant6566 Thanks for offering your help :-) We will also come back to this thread once we have further planned the feature.

**Comment by ksushant6566** [comment]
Cool

**Comment by jobenjada** [comment]
@jonas-hoebenreich we've taken this out of the bigger Targeting Revamp and will ship it sooner - the big one in the other ticket might take a bit longer so we wanted to ship this sooner 🚢

**Comment by mattinannt** [comment]
Closed with https://github.com/formbricks/formbricks/pull/2110 and released with Formbricks v1.6.0
