### ISSUE TITLE
[FEATURE][🕹️] Hidden Fields Docs Page

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1975]
### Is your feature request related to a problem? Please describe.

so far hidden fields are not explained in the docs:

<img width="265" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/fcafd2a7-d1d4-4123-9651-dd5f0a605b83">

### Describe the solution you'd like

- write a concise explanation incl. screenshot how they work
- test hidden fields with the other link survey settings: verify email, PIN protect, single use surveys
- If something doesnt work, open a bug ticket

**Comment by Amandixit10** [comment]
Hi @jobenjada, can you please describe the issue in detail.

**Comment by vidhikapadia2799** [comment]
Hi @jobenjada , can you please describe the issue in detail. I am new to formbricks and excited to work on this.

**Comment by vidhikapadia2799** [comment]
Hi @jobenjada,  hidden fields explanations are already there in docs. 
![image](https://github.com/formbricks/formbricks/assets/59463984/b164fd90-5182-48a0-9016-7c3145944053)

If you want any further addition, then please do let me know

**Comment by jobenjada** [comment]
It got shipped in the meanwhile, thanks @vidhikapadia2799 for checking :)
