### ISSUE TITLE
[FEATURE] Add Azure SSO to Docs

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#1994]
### Is your feature request related to a problem? Please describe.

Its not in the docs

### Describe the solution you'd like

It should be :) Add as much information as possible incl. how to set it up for self-hosters

**Comment by jonas-hoebenreich** [comment]
@ShubhamPalriwala if you want to hand over this task, I can do it too, as the original PR for this feature came from me 👌

**Comment by ShubhamPalriwala** [comment]
Hey @jonas-hoebenreich, apologies for the delay! I did try to set it up on my own but could not make much progress with Azure AD :/ It'd be super helpful 😊 if you can just lay the barebones and I can pick it up from there to do the redundant tasks / cleanup / formatting / etc!
