### ISSUE TITLE
[FEATURE] Introduce Frontend-Exclusive Attributes for Enhanced User Interaction

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#1999]
### Is your feature request related to a problem? Please describe.

We propose the implementation of frontend-only attributes to enhance user customization and interaction. This feature will empower developers to dynamically set attributes specific to the frontend, enabling targeted survey triggers based on user-defined criteria. Additionally, metadata from these attributes can be added to survey responses from frontend to backend, facilitating a smoother integration between the two.

### Describe the solution you'd like

Introduce a method, perhaps named `formbricks.setFrontendAttribute(key, value)`, to enable the definition of frontend-only attributes. These attributes will be applicable only during the current page view, providing a localized and dynamic user experience.
With frontend-only attributes, developers can leverage these key-value pairs to finely tune survey triggers. For instance, a survey could be triggered based on specific conditions, such as displaying it only when the 'bucket' attribute is equal to '0' and the 'language' attribute equals 'EN'. This granular control enhances the precision of user engagement strategies.
When a user responds to a survey, the current set of frontend attributes should be automatically included as metadata in the survey response. This integration ensures that valuable user context is seamlessly passed from the frontend to the backend, facilitating further analysis and decision-making.

**Comment by mattinannt** [comment]
@jonas-hoebenreich thanks for the issue :-) We have already created a design proposal that is currently under internal review. We will keep you updated.
Hopefully we can start development on this as early as next week, once we have successfully merged Advanced Attribute Filtering, which handles attribute filtering and user segmentation for identified users (non-public websites)

**Comment by jonas-hoebenreich** [comment]
Hi @jobenjada,

thank you so much for sharing this, I really appreciate that you want to add website survey attributes and on the fly triggers 💚 
From my first read through, I noticed the following points:
1. This mockup does not have an option to set on-the-fly code triggers. I would suggest to add that (since especially code triggers are mostly single use and specific to a certain survey):
![image](https://github.com/formbricks/formbricks/assets/64426524/8f120938-0ae5-4617-b4e6-6d205e223adf)
2. My personal opinion on AttributeClasses: I would only allow class creation in the backend. Then you could simply send an array with all valid classes during the survey sync and save yourself all the fuss with inbox/review etc. And you don't really save any time either, because then you have to verify the attributes in the backend instead. I believe that "Easy UX/DX: No matter how users add an attribute, it works (via UI & code)" doesn't really solve a real problem.

Best,
Jonas

**Comment by jobenjada** [comment]
Hey Jonas!

1. Good point, will add!
2. Will take into account, thanks :)

Cheers!

**Comment by mattinannt** [comment]
We discussed frontend attributes internally, iterated over different concepts but decided to stay with the current approach only supporting attributes and filtering based on them when user identification with Formbricks contact management is used.

As a workaround for everyone looking for a solution, actions could be triggered conditionally in the application code
```
if (request.browser.language === "de") {
   formbricks.track("onboarding-de");
}
```
