### ISSUE TITLE
[FOR-1823] [FEATURE] Support other S3-compatible storage solutions

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#2000]
### Is your feature request related to a problem? Please describe.

Formbricks currently only supports local file storage or AWS S3. But even though there are a lot other S3-compatible storage solutions (like MinIO), it can't be configured in Formbricks because the endpoint is not customizable in the S3 connection setup ( https://github.com/formbricks/formbricks/blob/main/packages%2Flib%2Fstorage%2Fservice.ts#L33-L39 )

### Describe the solution you'd like

Add a new optional environment variable `S3_ENDPOINT_URL` that when set, customises the endpoint in the s3 config, e.g.
```
const s3Client = new S3Client({
  credentials: {
    accessKeyId: S3_ACCESS_KEY,
    secretAccessKey: S3_SECRET_KEY!,
  },
  endpoint: S3_ENDPOINT_URL,
  region: AWS_REGION!,
});
```

### Additional context

Based on Discord Request: https://discord.com/channels/979077669410979880/1202861147561402438

<sub>[FOR-1823](https://linear.app/formbricks/issue/FOR-1823/[feature]-support-other-s3-compatible-storage-solutions)</sub>

**Comment by kymppi** [comment]
I can take a look soon (tomorrow or the day after)

**Comment by htcnokia** [comment]
Yes,it still not working  under 4.9.7
