### ISSUE TITLE
[FOR-1825] [FEATURE] Question Type: Ranking

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#2001]
### Is your feature request related to a problem? Please describe.

Let's say that I have a list of 10 features and I would like the respondent to rank the features in order of importance for them. 

Example questions:
"If i have a set of features, e.g. responsive forms, flexible respondent pricing, embedding, emailing, etc. could you please rank which are most important for you?"

"Based on your own time management, please rank in order of importance: design, coding, internal communication, team management, etc."

### Describe the solution you'd like

We need a question type: Ranking

Build a new Formbricks Question type for Ranking Questions (in the Editor as well as the Surveys package).

## UX Notes
To start with, we will enable a way of sorting which does not include Drag and Drop. I find DnD to break easily and often it's not really well done. Also, the surveys will run on a lot of different devices and platforms so solving it without an additional library should be preferred. We do the following:

### Click to sort
When a respondent is asked to sort something, they do it in two steps: Initial sorting and fine-tuning. Our sorting needs to allow both.

![image](https://github.com/user-attachments/assets/0f4898e3-20d8-4142-90fd-9838e710826c)

**Initial sorting**
Very straight forward: The first element you click on is sorted first, the next you click on becomes second, etc.

The new option has two new elements: A circle on the right (which is a bit bigger and has a dashed stroke then single choice) and two arrow buttons:
![image](https://github.com/user-attachments/assets/b702ba81-a8b3-413b-afd9-6d819d051302)

If clicked, it looks like this:
![image](https://github.com/user-attachments/assets/9a00c4ce-787f-47c1-9b22-0815023273ac)

Here is the UX:
1. Once the respondent clicks on the first option, we mark it with 1 on the left hand side, **but do not yet resort cause it would confuse the respondents.**
2. Once the respondent clicks on the second option, we sort the first option to the top and the second  below the first. This assures that they understand how the click-to-sort-thing works.
3. For all following elements we sort them up right after the click on it.
4. The arrows are very straight-forward: Once the user clicked on up or down, the option moves up or down and gets a number.

Please make sure to properly test the different edge cases of which there are quite a few.

**CSS Animations**
- Make sure to use CSS Animations to make the resorting look nicer.

**Error messages**
If the question is required, all options need to be sorted.

### RankingQuestionForm
The form to create a ranking type question should be identical to the one for Single Select incl. the option to randomize:

<img width="696" alt="image" src="https://github.com/user-attachments/assets/cc0cd2ac-1595-45b1-918d-605c19f5b9b9">

### Summary and Response Card
The summary should follow this pattern:
<img width="536" alt="image" src="https://github.com/user-attachments/assets/232e189d-108b-4858-a660-add3806ded24">

The Response card this pattern:
<img width="84" alt="image" src="https://github.com/user-attachments/assets/a1d98e44-d243-4172-977c-4e6abc59ecb3">

**Please refer to the guide on new question types:**
https://formbricks.notion.site/

### Describe alternatives you've considered
Drag and Drop

### Additional context

Based on Discord Request: [https://discord.com/channels/979077669410979880/1202940689353285683/1202940689353285683](https://discord.com/channels/979077669410979880/1202940689353285683/1202940689353285683)

**Comment by manish-singh-bisht** [comment]
i will give this a shot.

/assign

**Comment by manish-singh-bisht** [comment]
i will give this a shot.

**Comment by manish-singh-bisht** [comment]
formbricks already uses "react-beautiful-dnd" ,will be using this again. Is that fine to use?
