### ISSUE TITLE
[FEATURE] Allow scoring of answers

### ISSUE THREAD

**Issue by ursinsaluz** [formbricks/formbricks#2004]
### Is your feature request related to a problem? Please describe.

If I want to do a quiz or a test (e.g. Mulitple and Single Choice Questions) I would like to set a score for each possible answer. In the end the sum of the scores can be weighted and set for a pass or fail.

Obviously the logic should be able to handle the value.

### Describe the solution you'd like

For every Multiple Choice or Single Choice Answer, allow setting a numeric value as the answer score.

Allow setting a logic depending on the scoring value:
e.g. go to welcome screen if total value < 80 and go to final screen if value > 80

Allow logic routing based on given answers or points, Ideally there can be two different final screens depending on the logic, if failed.

Filling out the form:
Automatically add the scoring values of the selected the answers along the way. 

### Describe alternatives you've considered

Routing based on answers is also possible. But that would result in immediate feedback if the the wrong answer was given and the test can not be completed without knowing all answers.

Alternatively the scoring of answers can also be used to calculate things like engagement value, for scoring of leads in a sales process or such things.

### Additional context

Typeform has this logic. I think they initially used it for scoring the users engagement or lead value in order to prioritize them for contact.

**Comment by mattinannt** [comment]
@ursinsaluz Thanks for creating this feature request 😊 Yes, scoring and advanced logic for this could be a great feature for various quiz and advanced logic jump use cases.

Our current focus is on supporting the various survey and insight generation use cases our users have, so quizzes are on the roadmap, but not a high priority. We will probably approach this as a community feature to improve link surveys (like we did with a lot of tickets in the hackathon a few months ago).

Unfortunately, I can't give you a timeframe for this. The next steps for us would be to come up with a first design proposal for this feature.

**Comment by ursinsaluz** [comment]
No worries, thanks a lot for acknowledging the feature request.

**Comment by mattinannt** [comment]
Update: we already shipped multiple end cards in the last release and are currently working on advanced survey logic where we will also support scoring :-)

**Comment by mattinannt** [comment]
Variables and advanced logic has now been shipped enabling users to define variables, set them based on question responses and show the right ending screen based on the variable value.
![image](https://github.com/user-attachments/assets/c6a05d7a-f08e-4f13-976b-8733c762af85)
