### ISSUE TITLE
[BUG] Cannot use REST API to create new survey

### ISSUE THREAD

**Issue by Haven4LivingMenu** [formbricks/formbricks#2006]
### Issue Summary

I'm encountering an issue with the REST API for creating new surveys, it keeps returning error 500.
Other endpoints are functioning correctly. 
Could you please assist in identifying and resolving this problem promptly?
It's critical to our operational workflow. Thank you.

### Steps to Reproduce

![image](https://github.com/formbricks/formbricks/assets/88300429/dde38532-3b04-4118-a2e1-78ec8af36d63)
![image](https://github.com/formbricks/formbricks/assets/88300429/ed002b27-ebea-4366-8823-0111aebc9145)

### Expected behavior

will create new survey

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: MacOS
```

**Comment by mattinannt** [comment]
Solved in https://github.com/formbricks/formbricks/pull/2007 😊
