### ISSUE TITLE
[FEATURE] add debug mode to in-app pixel

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2016]
### Is your feature request related to a problem? Please describe.

When debugging in-app surveys & triggers it would be helpful to have an option to enable the debug mode on the fly by adding a parameter to the URL.

### Describe the solution you'd like

In Hotjar you can just add ?hjDebug=1 to the URL to achieve this and I think it would be helpful to have something similar in Formbricks (e.g. ?formbricksDebug=1).
see https://help.hotjar.com/hc/en-us/articles/13084088916631-Hotjar-Debug-Mode
If you want, I can prepare a PR for this feature.

**Comment by mattinannt** [comment]
@jonas-hoebenreich Yeah, that sounds great. Would be cool, if you can prepare a PR for this 😊🤗
