### ISSUE TITLE
[BUG] Deleted responses are returned with the API

### ISSUE THREAD

**Issue by Nick-v-L** [formbricks/formbricks#2021]
### Issue Summary

When a response is deleted in the GUI it is returned in the API.

### Steps to Reproduce

1. Create a new survey
2. Fill in a reponses
3. Delete the response
4. Request the responses with the management API
5. Deleted response is returned

### Expected behavior

1. Create a new survey
2. Fill in a reponses
3. Delete the response
4. Request the responses with the management API
5. Deleted response is not returned

### Other information

*No response*

### Screenshots

![image](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/50f54615-7d87-4799-8284-f6ce0d8b442c/7dc9cec7-d4a6-4a60-b9ea-0d1159c07dcf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC81MGY1NDYxNS03ZDg3LTQ3OTktODI4NC1mNmNlMGQ4YjQ0MmMvN2RjOWNlYzctZDRhNi00YTYwLWI5ZWEtMGQxMTU5YzA3ZGNmIiwiaWF0IjoxNzA3MjExNDIzLCJleHAiOjMzMjc3NzcxNDIzfQ.Na48EaawK55STTeUc2jbvQ-3Nt_KezlVJ4e-pJGkzv4)

[https://url/api/v1/management/responses?surveyId=clsa31jau0002ii4r6ilclgxx](https://url/api/v1/management/responses?surveyId=clsa31jau0002ii4r6ilclgxx)

![image](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/20adb1cb-e28d-42ca-a513-dfbf1febf4b8/fad1673a-3d46-4f2b-802b-f34c9e434b3e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC8yMGFkYjFjYi1lMjhkLTQyY2EtYTUxMy1kZmJmMWZlYmY0YjgvZmFkMTY3M2EtM2Q0Ni00ZjJiLTgwMmItZjM0YzllNDM0YjNlIiwiaWF0IjoxNzA3MjExNDIzLCJleHAiOjMzMjc3NzcxNDIzfQ.-SdXCkA36glYITDkxC6xrKcI5sPkB3htYYQ-V1-3rwI)

### Environment

- [ ] Formbricks Cloud ([app.formbricks.com](http://app.formbricks.com))
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Version: mls branch (found this while checking out the MLS branch)
```

**Comment by mattinannt** [comment]
@Nick-v-L Thank you for raising an issue. I will look into it 😊
Are you using Formbricks self-hosted on a single machine or are you scaling it in any way (Kubernetes cluster, etc.)?

**Comment by Nick-v-L** [comment]
@mattinannt, this this is self hosted on a single machine

**Comment by mattinannt** [comment]
@Nick-v-L I was able to reproduce the issue and come up with a fix :-) 
There was a caching issue in the response service, so in the special case of the API, the response is still displayed because this cache wasn't revalidated when the response was deleted.
