### ISSUE TITLE
[BUG] Pressing enter after filling out a simple text question circumvents url and email validation

### ISSUE THREAD

**Issue by hantusk** [formbricks/formbricks#2038]
### Issue Summary

Pressing enter after filling out a simple text question circumvents url and email validation

### Steps to Reproduce

1. Create a survey with text questions of type email and url
2. Fill out survey, but press enter after filling out the input text field instead of clicking the Next button
3. Survey can complete without email or url validation

### Expected behavior

The form should prevent me from advancing to the next question upon invalid input

### Other information

*No response*

### Screenshots

*No response*

### Environment

- [X] Formbricks Cloud ([app.formbricks.com](http://app.formbricks.com))
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Mac
```

**Comment by jobenjada** [comment]
@Dhruwang please investigate and ship a fix for it :)
