### ISSUE TITLE
[BUG] Account not removed from team on delete

### ISSUE THREAD

**Issue by kymppi** [formbricks/formbricks#2044]
### Issue Summary

After a user deletes their account. It's not removed from the member list for a specific team. I'm guessing that it's related to caching since there's no reference to the deleted user in the database.

### Steps to Reproduce

1. Invited new user to team
2. Accepted invite and created account
3. Deleted the newly created account
4. the account is still present in the team member list

### Expected behavior

It should be automatically removed from there too.

### Other information

*No response*

### Screenshots

![image](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/49a07779-8148-49ab-94cb-5ea41a766ba2/79732ae2-9f21-45c6-af04-0cbea85b8fa4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC80OWEwNzc3OS04MTQ4LTQ5YWItOTRjYi01ZWE0MWE3NjZiYTIvNzk3MzJhZTItOWYyMS00NWM2LWFmMDQtMGNiZWE4NWI4ZmE0IiwiaWF0IjoxNzA3NjQ0Njg0LCJleHAiOjMzMjc4MjA0Njg0fQ.Mi3JD7fkSb_ja2SZMB2o2ETG5GsJVu10t36XpNbvH8Y)

There should be only 3 rows, the "Midka" account has been deleted and it still shows after a page refresh.

### Environment

- [ ] Formbricks Cloud ([app.formbricks.com](http://app.formbricks.com))
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
- Formbricks Docker: v1.5.1
```

**Comment by kymppi** [comment]
Someone may try to remove the user again since it still shows it being in the team. In that case it shows a generic error to the end-user and logs more errors to console.

![image](https://github.com/formbricks/formbricks/assets/48528700/e714e05b-2796-4304-88b8-66db2bcd7f81)
![image](https://github.com/formbricks/formbricks/assets/48528700/a0dcdfeb-8f6e-45d8-a469-fa3a7874c28c)

**Comment by jobenjada** [comment]
@Dhruwang please reproduce and fix :)

**Comment by Nathan-Roberts123** [comment]
To me when I refresh the teams page, the deleted account on a members list is removed, but it happends when I refresh the page on the teams page not on any other page. I am using gitpod though.
