### ISSUE TITLE
[BUG] User ____ has no teams

### ISSUE THREAD

**Issue by kymppi** [formbricks/formbricks#2045]
### Issue Summary

After removing a user from the single team it was in. The user cannot access formbricks at all and there's an error printed to the logs. My suggestion is that the user would be able to delete the account or create a new team and being the owner of the team.

### Steps to Reproduce

1. Revoke user access from team
2. Open formbricks as the revoked user
3. See photo 1
4. Cannot do anything, not even delete or logout

### Expected behavior

A: It would create a new team automatically
B: it would allow the user to delete the account
C: a selection with options A and B

And in any case it should not log errors to console (photo 2)

### Other information

*No response*

### Screenshots

Photo 1:

![image](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/c6c03c58-6f1d-47c8-9661-cd8a0c800883/aba8c4d3-f24a-4a87-8b57-a0b62cdc22df?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC9jNmMwM2M1OC02ZjFkLTQ3YzgtOTY2MS1jZDhhMGM4MDA4ODMvYWJhOGM0ZDMtZjI0YS00YTg3LThiNTctYTBiNjJjZGMyMmRmIiwiaWF0IjoxNzA3NjQ0NjM2LCJleHAiOjMzMjc4MjA0NjM2fQ.0Rru3pmUe6jh1AVj7ErHXE2txetIhkbcwzXmwRYjIx0)

Photo 2:

![image](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/8e392d75-43cc-40b6-b8b1-d2145045ada2/c5775b93-8c8c-4c21-88b3-052f507bff1f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC84ZTM5MmQ3NS00M2NjLTQwYjYtYjhiMS1kMjE0NTA0NWFkYTIvYzU3NzViOTMtOGM4Yy00YzIxLTg4YjMtMDUyZjUwN2JmZjFmIiwiaWF0IjoxNzA3NjQ0NjM2LCJleHAiOjMzMjc4MjA0NjM2fQ.q8Gr_UgENbvwiPlWIobTY1KmBJEJCkcgRBF_a53-vzw)

### Environment

- [ ] Formbricks Cloud ([app.formbricks.com](http://app.formbricks.com))
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
- Formbricks Docker: v1.5.1
```

**Comment by jobenjada** [comment]
hey Midka! We've solved this already, there is a "Let's create a team for you" screen if we cannot detect a team for a user.

Are you on the newest release? 🤓

**Comment by kymppi** [comment]
Yep! I'm on this https://github.com/formbricks/formbricks/releases/tag/v1.5.1 release (currently the latest).

**Comment by ShubhamPalriwala** [comment]
Hey @kymppi, thanks for reporting the bug! We are able to reproduce it and are working on a fix! Regarding the console errors, is your env var `NODE_ENV` set to something other than "production"? If then try setting it to this and then you should not see these errors in the client console hopefully.
