### ISSUE TITLE
[FEATURE]The self-hosted version to integrate with windows active directory

### ISSUE THREAD

**Issue by NetworkJBM** [formbricks/formbricks#2055]
### Is your feature request related to a problem? Please describe.

Form bricks cannot be integrated with active directory

### Describe the solution you'd like

I'd like to have the formbricks with an active directory integration so that the responders can sign in with Windows active directory and then even edit the responses if they require it.

### Describe alternatives you've considered

I've tried LimeSurvey but its UI is very old

**Comment by mattinannt** [comment]
Thanks for the feature request. We already support Azure Active Directory. Is the Active Directory support you need different from this? 😊

**Comment by NetworkJBM** [comment]
Thanks for the reply. I was searching for something that supports Windows active directory which is different from Azure AD.

**Comment by NetworkJBM** [comment]
@mattinannt. I think windows AD can be connected with LDAP

**Comment by NetworkJBM** [comment]
Hi, is there an update on this please?

**Comment by mattinannt** [comment]
@NetworkJBM We are looking into this feature and seeing how it might be solved with the planned configurable OAuth support. Unfortunately, I can't give you an estimate on when we might ship this, but once we have all the details specified, it might also be picked up by a contributor, which usually increases the shipping speed of community features and thus might be shipped within a few weeks.
If you know how to solve this and want to get ahead of our internal roadmap, please feel free to build it and open a PR for it 😊.

**Comment by NetworkJBM** [comment]
Noted with thanks

**Comment by mattinannt** [comment]
@NetworkJBM We shipped the OAuth / OpenId Connect Support in the meantime. Can you please check if you are able to get Windows AD working with this?
https://formbricks.com/docs/self-hosting/external-auth-providers#open-id-integration

**Comment by NetworkJBM** [comment]
Hi, thank you very much for the follow up but unfortunately I’m not able to
achieve what I need with the OAuth/ Open ID

**Comment by mattinannt** [comment]
Closing this for now because of inactivity. We will allocate more resources into SSO soon to support more providers and make sure all of them are well tested and documented.
