### ISSUE TITLE
[BUG] Subsequent NPS / rating questions do not reset form state

### ISSUE THREAD

**Issue by starlight-akouri** [formbricks/formbricks#2060]
### Issue Summary

When filling out a form on a mobile device (iPhone iOS 17 in Safari), if you ask several NPS (and also rating) questions in a row it keeps the last selected option highlighted even in the next question.

For example, if Question 2 is a NPS question with option 1-10 and the user selects value "7," the survey advances to question 3, but value "7" is already selected.

### Steps to Reproduce

See above

### Expected behavior

I would expect that the selected value is reset so that the user's choice isn't influenced by their previous answer..

### Other information

*No response*

### Screenshots

[https://github.com/formbricks/formbricks/assets/124310793/4d75bb99-a82c-4b91-99c0-440ac4445b42](https://github.com/formbricks/formbricks/assets/124310793/4d75bb99-a82c-4b91-99c0-440ac4445b42)

### Environment

- [X] Formbricks Cloud ([app.formbricks.com](http://app.formbricks.com))
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@starlight-akouri Thanks for pointing this out. I created a ticket for the team and we will come up with a fix 😊

**Comment by starlight-akouri** [comment]
FYI I looked into this last night. I think it might have something to do with the tailwind on line 68 of `NPSQuestion.tsx` I believe that the "active" state is somehow not being reset on mobile

**Comment by jobenjada** [comment]
@starlight-akouri do you still have the issue? We had a similar issue and added keys to each question, which solved it.

**Comment by starlight-akouri** [comment]
Was still happening as of the time I posted. I can check again, but didn't see anything committed
