### ISSUE TITLE
[BUG] Avatar is not showing

### ISSUE THREAD

**Issue by raphaeldeux** [formbricks/formbricks#2068]
### Issue Summary

The avatar image is showing a standard image, not mine. I think this a local problem but I can't find out what is the specific issue.

### Steps to Reproduce

1. I click on "Upload image"
2. Then it is uploading my image
3. And doesn't show the image properly

### Expected behavior

Show the image that I am uploading

### Other information

Formbricks is installed with docker-composer.yml

### Screenshots

![Capture d’écran 2024-02-13 à 22 29 08](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/680f650b-1207-40b6-87f5-96db2dddc393/4176d426-13ad-4e7c-bfc5-830d03741786?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC82ODBmNjUwYi0xMjA3LTQwYjYtODdmNS05NmRiMmRkZGMzOTMvNDE3NmQ0MjYtMTNhZC00ZTdjLWJmYzUtODMwZDAzNzQxNzg2IiwiaWF0IjoxNzA4MDA2NTA4LCJleHAiOjMzMjc4NTY2NTA4fQ.kE64RIBu0kDV9RD26q19EfTjd66pAxWmuh40wNYMXCk "=1440x")

### Environment

- [ ] Formbricks Cloud ([app.formbricks.com](http://app.formbricks.com))
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Ubuntu 20.04
- Node: 20.11.0
- npm: 10.4.0
```

**Comment by mattinannt** [comment]
@raphaeldeux Thanks for reporting this 😊 We are currently experiencing some caching issues with the uploaded images and are working on a fix which will be ready soon 😊.

**Comment by KazeroG** [comment]
@mattinannt Issue related too to #2046 I have the same issues, on my side I use Railway.app

Console error : Failed to load resource the server responded with a status of 500 on /api/v1/management/storage/local:1

maybe problems with the mounted volume : 
![image](https://github.com/formbricks/formbricks/assets/17680194/7df9428d-e1f3-4393-8553-351356729e2a)

We should merge both issues #2046 and #2068.

**Comment by mattinannt** [comment]
@raphaeldeux @KazeroG we merged a first fix for this issue: https://github.com/formbricks/formbricks/pull/2071
It will be included in the next release 😊

**Comment by raphaeldeux** [comment]
@mattinannt I confirm that it works in the current release :) thanks for your job !
