### ISSUE TITLE
How to run this code ?   

### ISSUE THREAD

**Issue by AmeniChakroun** [formbricks/formbricks#2088]
### Issue Summary

Please the steps

### Steps to Reproduce

1. database
2.frontend
3.backend

### Expected behavior

runing the code

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by jobenjada** [comment]
Hey!

Contribution docs: https://formbricks.com/docs/contributing/introduction

Self hosting docs: https://formbricks.com/docs/self-hosting/deployment

If you need more info, check out our Discord: formbricks.com/discord

Thanks!
