### ISSUE TITLE
[FEATURE][🕹️] Question Type: Address

### ISSUE THREAD

**Issue by starlight-akouri** [formbricks/formbricks#2089]
### Is your feature request related to a problem? Please describe.

It is hard to collect addresses because each question must be on a new page. Typeform has a single Address input type which resembles a standard address input. 

### Describe the solution you'd like

The solution that Typeform takes is fine, but an optimization would be to allow the user to enter in a GOOGLE_MAPS_API_KEY so that you can have autocomplete

### Additional context

I am happy to help contribute

**Comment by mattinannt** [comment]
@starlight-akouri thanks for opening the issue 😊 Yes, a address input can make sense here 😊
We will add this to our internal backlog. The next step for us would be to design a solution for this so we can start development.
To give you a heads up, we currently have a few high priority items on the list for the next releases that we need to get done first before we can add any new features.

(related to https://github.com/formbricks/formbricks/issues/1738 )

**Comment by jobenjada** [comment]
Here is the ticket

**Issue**: It's hard to gather addresses with Formbricks

**Solution**: Build question type Address

**Tasks**

Follow the current approach in the survey editor and create a new AddressQuestionForm with the following settings:

- Icon: HeroIcon House
- Reuse the toggle we use in the other creation forms

<img width="723" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/323f7921-d4ff-4f9a-9478-32d2a0fb4a5f">

In the survey package (packages/survey), add a new survey question type called "address". It should have these corresponding fields which can be set the "required" individually. Here is a mockup of it (keep the current UI as it is, this mock up uses our upcoming design already):

<img width="543" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/9db97fcd-a9fc-4dc5-bfd0-4a2399611fe0">


**Summary View**
In the summary view, please display the addresses like so:
<img width="1008" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/ceab38e7-0c9c-4e26-98b5-7963ba15c3dc">


**Response View:**
<img width="1032" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/31b89e4a-9570-43a5-af83-dad1d562b039">
