### ISSUE TITLE
[FEATURE] make docker image not require internet on start

### ISSUE THREAD

**Issue by paulceli** [formbricks/formbricks#2093]
### Is your feature request related to a problem? Please describe.

In Dockerfile 

CMD ... pnpm dlx prisma migrate deploy && \

The launch command downloads a prisma package, and thus requires some internet access.
This is not ideal for an on-premise "enterprise" deployment.

### Describe the solution you'd like

Add the necessary prisma package during the image build.?
Only exec the necessary prisma commands.?

### Describe alternatives you've considered

We can open a hole in our proxy.
Which is bad.

**Comment by mattinannt** [comment]
@paulceli thanks for pointing that out :-) I think it should be easy to fix, since should already have all the dependencies during the build process.

**Comment by nesherofek** [comment]
hey, is this part of the 1.6.1 version? tried to update but still encounter an internet connection required to download pnpm on docker run..is it only me?
