### ISSUE TITLE
[FEATURE] Enhance List View for better UX

### ISSUE THREAD

**Issue by MaxWohlers** [formbricks/formbricks#2101]
### Is your feature request related to a problem? Please describe.

* list view is never the default setting, only grid view, which results in an annoying click every time to change the view
* For monitoring multiple surveys at the same time, I am missing key infos in the list view, like number of responses, created by person, or position (e.g. bottom right, center, bottom left)
* it is important for me to know at which date exactly a survey was created, instead of knowing that it was created 'X days ago'

### Describe the solution you'd like

As a user, I want the List view to:

1. **Remember** my view settings
2. add number of **responses**, **created by** person, and **position** as new columns to the list view
3. show **actual date** under 'created at'

### Describe alternatives you've considered

*No response*

### Additional context

Mockup:

![Bildschirmfoto 2024-02-19 um 20 03 53](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/a55a55dd-62c1-435c-b527-53fcdaddf87e/c1cfba25-41b8-4e91-a24e-816940efe6e1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC9hNTVhNTVkZC02MmMxLTQzNWMtYjUyNy01M2ZjZGFkZGY4N2UvYzFjZmJhMjUtNDFiOC00ZTkxLWEyNGUtODE2OTQwZWZlNmUxIiwiaWF0IjoxNzA5ODEyMTQxLCJleHAiOjMzMjgwMzcyMTQxfQ.QdQKDJKzirCGVJMCsBCU1fq2pKeN8YVrckIv8u1FMN4 "=736x")

**Comment by jobenjada** [comment]
Hey Max!

Thanks for the feedback. Will write up the corresponding tickets right away.

FYI: We're also working on a data table for the Response View based on your feedback. Would love to send the mock up over for your feedback before we get to the implementation. Can you ping me on johannes@formbricks.com ?

Thanks!
Johannes

**Comment by jobenjada** [comment]
Hey!

The orientation selection is now persisted in localStorage and the Created At date is updated.

The rest will follow soon - thanks for your feedback :)

Cheers
Johannes

**Comment by mattinannt** [comment]
Internal tickets created for the team and will start development soon :-)

**Comment by MaxWohlers** [comment]
@mattinannt hey wondering what the status on "add number of responses, created by person" and the like is? :)

**Comment by MaxWohlers** [comment]
@mattinannt
