### ISSUE TITLE
[FEATURE] make widget not depend on internet access

### ISSUE THREAD

**Issue by paulceli** [formbricks/formbricks#2104]
### Is your feature request related to a problem? Please describe.

For on-premise deployment on a "isolated" network, the widget is not working.
It seems to try to fetch a package from the internet defined here : packages/js/vite.config.ts 

```
  const formbricksSurveysScriptSrc = isDevelopment
    ? "http://localhost:3003/index.umd.js"
    : `https://unpkg.com/@formbricks/surveys@^${surveysPackageJson.version}/dist/index.umd.js`;

```

### Describe the solution you'd like

make it not link to an internet URL

### Describe alternatives you've considered

I don't see any

**Comment by mattinannt** [comment]
@paulceli thanks for the feature request 😊
There was also a PR solving the basics of it:
https://github.com/formbricks/formbricks/pull/2015

But we need to make sure this is also working with the surveys package out of the box. Unfortunately this approach is not working on serverless environments like Vercel or AWS Amplify. We need to test this a bit further and build a fallback for serverless environments before switching this on by default 😊

**Comment by paulceli** [comment]
This could be solve by simply allowing this URL to be parameterized at initialization (so enterprise can point to its proxy).
Also by default jsdelivr.com might be a better alternative to unpkg.com.

**Comment by nesherofek** [comment]
Have encountered the same problem with my self hosting instance. 
On init configuration sound like the suitable solution 🙏🏻

**Comment by mattinannt** [comment]
We are now in the process of revamping the `@formbricks/js` package to load all required code directly from the Formbricks server (with support for serverless environments). @pandeymangg is building the basis for this next week; so we should have a solution soon 😊

**Comment by mattinannt** [comment]
@paulceli The PR has only done the technical foundation and we are currently testing this on Formbricks Cloud. The documentation is still for the "old" unpkg approach. The new package pulls everything from endpoints on the Formbricks instance.
We will publish this on npm soon and then also update the docs.
