### ISSUE TITLE
[BUG] Show an error 'Email verification is pending' when logging in

### ISSUE THREAD

**Issue by Nathan-Roberts123** [formbricks/formbricks#2116]
### Issue Summary

If I start formbricks with EMAIL_VERIFICATION_DISABLED and create an account, then stop formbricks and set EMAIL_VERIFICATION_DISABLED to 1, and start formbricks, when i try to login with the account i created when email verification was disabled i get an error 'Email verification is pending'. It because the account is not verified but formbricks does not send an email for me to verify the account.

### Steps to Reproduce

1. Set `EMAIL_VERIFICATION_DISABLED=1` in the .env file and create an account.
2. Then set `EMAIL_VERIFICATION_DISABLED=0` and restart formbricks.
3. Try to login with the account you created.

### Expected behavior

Maybe send an email for a user to verify email so a user can verify that email.

### Other information

*No response*

### Screenshots

*No response*

### Environment

- [ ] Formbricks Cloud ([app.formbricks.com](http://app.formbricks.com))
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
 
```

**Comment by mattinannt** [comment]
@Nathan-Roberts123 Isn't there a `Request a new verification mail` button for this case so the user can request a new verification email?

**Comment by Nathan-Roberts123** [comment]
No There is no `Request a new verification mail` button, I only see that button when i am creating a new account.

![Screenshot (149)](https://github.com/formbricks/formbricks/assets/138929167/c51f1292-3dcc-4477-b05c-fc53d4b39d0c)

**Comment by mattinannt** [comment]
@Nathan-Roberts123 I have created a ticket for the team for this to solve this and redirect the user to the verification page if they haven't verified their email address.
