### ISSUE TITLE
[FEATURE][🕹️] Branded Link Surveys

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2119]
### Is your feature request related to a problem? Please describe.

**Issue**: 
People want to brand surveys with a logo that is always visible

### Describe the solution you'd like

**Solution**: 
We allow people to add a company logo to their product:

- They can adjust the background color
- They can toggle it on and off for link surveys

**Survey Editor UI**
Add a field to the top left corner which prompts users to upload their company logo:

<img width="669" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/fd947e33-e8c9-4d3c-977f-3fc6a65dbb54">

<img width="469" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/b347eab3-bf76-471f-9e2e-44148195c862">

On click, the upload mask opens which only allows .png and .jpeg files. 

**Logo Settings**

Once an image file was selected and uploaded, this modal opens:
<img width="777" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/b06abb9f-2a6d-4d95-90ae-487040b0aabd">

1. Replace logo: Opens the upload modal again to replace logo
2. Remove logo: Replaces the preview with our standard file upload UI (find it in `packages/ui`). However, the logo file is not deleted on button click, this happens only on "Save". Otherwise "Cancel" cannot undo it.
3. Background color: Default #ffffff, affects the background color of the container holding the logo

The rest of the UI should be self-explanatory. On SAVE the logo is displayed accordingly in the top left corner of the link survey preview. 

On HOVER on the logo, we see an EDIT icon button which opens the same settings modal:

<img width="998" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/3b6a3efe-7e00-4f2d-beae-adb00ffda0c4">

In the Styling Card in the survey settings, we add a "Hide logo" toggle if the product has a logo:

<img width="548" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/09feb38e-1e97-4cde-9400-1824b127d1e3">

The toggle hides the logo in this specific survey :)

----------

**Product Settings > Look & Feel Page**
We also allow to add the logo on the Look & Feel page in the Product Settings. The card looks like this at first:

<img width="701" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/9b4938e8-f65a-4da2-84aa-75bc75ea548c">

Once the user uploaded an image we see the editor:

<img width="669" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/9c5bba77-7422-428c-b481-66dde2d258ce">

After save, we can see the preview and the color but cannot make changes without hitting "Edit":

<img width="667" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/6135b322-3550-4c5f-bb00-0a68e74118a3">

--------

In the `LinkSurvey.tsx` display the logo if there is one for the product and the survey styling has showLogo enabled. It should be displayed in the top left corner of the page. Make sure it works well responsively.

--------

**Data Model**

Please extend the `Product` model in prisma with a new JSON object `brand`:

```
"brand": {
  "logoUrl": "...",
  "bgColor": "#ffffff",
}
```

In the styling JSON in the `Survey` model we set the variable `showLogo` to true for all new surveys. If  the variable is not set, we don't display the logo. In the settings in the Styling card we can set it to false by toggling off.

---------

**Team Roles**
We have team roles with different rights. Only render the card in the look and feel settings as well as the "Add logo here" indicator in the survey editor when the logged in user is a Developer, Editor or Admin (so not a Viewer).

---------

**How we code at Formbricks**
1. To keep our code DRY, create the UI we need both in the survey editor and the settings page in the `packages/ui` folder and import it back into the Formbricks app to use it.
2. Upload functionality: We're using it in several place in the app, stick to the same process to keep it consistent.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by ksushant6566** [comment]
Picking this up 💪

**Comment by manish-singh-bisht** [comment]
I want to work on this.

Sorry if this is not the way of asking for issue assignment, i couldn't find instructions for that.

**Comment by manish-singh-bisht** [comment]
@jobenjada  the logo should be in all survey forms or just link surveys?

**Comment by manish-singh-bisht** [comment]
@jobenjada i have few questions-
1. how will the background look like in the actual survey? an image showing that will help.
2. any specific length for the logo?
3.what should be the object-fit for image? current taking object-fit:cover 

4.how is the toggle button working? i have created the toggle button but i cannot understand how it will hide the logo. i tried looking for hideProgressBar toggle button functionality ,couldn't find.

5. what are these files "formbricks/packages/surveys/src/components/general/Survey.tsx"? my guess is that these are actual surveys that are displayed to users and i will have to make a change here also for showing the logo? correct me if wrong?

**Comment by jobenjada** [comment]
Hey!

1. The backgrounds can change in the survey: color, animation, image. Just play around with it :)
2. max width: max-w-64 (Tailwind)
3. object fit: contain (to make sure the complete logo is shown)
4. The hide progress bar functions differently, because it is part of the survey package. So the logo is stored in the Product model. I'll ask @mattinannt to provide you with the correct naming for the changes you need to make to the product model. You then update the value in the product model via the Toggle and in the `LinkSurvey.tsx` you consume this value to either hide or show the logo. 
5. This is our survey package. They render the survey.
6. Just for link surveys
7. Don't get your question

How much experience do you have with full-stack development approximately?

Thanks!

**Comment by mattinannt** [comment]
@jobenjada @manish-singh-bisht The logo should be stored in the product model as stated in the ticket description:
```
"brand": {
  "logoUrl": "...",
  "bgColor": "#ffffff",
}
```
For hiding the logo in the survey we add `hideLogo` to the `styling` object inside the survey model 😊

**Comment by manish-singh-bisht** [comment]
@mattinannt  , @jobenjada  so i couldnt question in a better way,my fault, because of that many questions were misinterpreted.Sorry for not asking better questions.(i am not being rude, i am filled with guilt right now,sorry)

@mattinannt  yes i read it in the ticket and it was the first thing i implemented.

@jobenjada  thank you for answering . 2,3 ,5 ,6 i got my answers.  

7. these are the membership roles ["owner" ,"admin" ,"editor" ,"developer" ,"viewer"] , in the ticket above you told to not allow users with membershipRole as "viewers" and allow "admin" ,"editor" ,"developer". what about the users with membershipRole as "owner", should users with "owner" role be allowed ? **reference**:**Team Roles section in ticket.**

4. (the process you told above in the answer, i already did that,before putting the question)  i created a toggle button in the survey setting ,styling card section that is visible only if logo is set, this was mentioned in the ticket. How can **i remove that logo in the preview** and NOT in the actual survey? For example: if we toggle on higeProgressBar in edit ,the progressBar hides in the preview.How can i remove the logo in preview if hideLog0 is toggle on? i couldn't understand this.

1. yes we can change the background in the survey setting , i did play around it. My question is you asked to add a background to the **container** of image, logo at max be max-w-64 ,so the rest of the space in the conatiner will be filled with background color?OR the background color here changes the background of whole survey?   what is length of the conatiner?

thank you


(now i think i became verbose with my questions)

**Comment by manish-singh-bisht** [comment]
i am ready for multiple iteration of the pr, if there is anything wrong or doesnt go with the standards of Formbricks.

the background color for container is something i dont  understand yet.My question is you asked to add a background to the container of image, logo at max be max-w-64 ,so the rest of the space in the conatiner will be filled with background color?OR the background color here changes the background of whole survey? what is length of the container?

**Comment by manish-singh-bisht** [comment]
pr is almost ready for review,added a loom video ,that that background question still remain?

My question is you asked to add a background to the container of image, logo at max be max-w-64 ,so the rest of the space in the conatiner will be filled with background color?OR the background color here changes the background of whole survey? what is length of the container?

**Comment by manish-singh-bisht** [comment]
@jobenjada  attaching 2 screenshots of how the background of the container of the image will look in the actual survey ,which one do you prefer? or if it is not how the background should look ,then how it should look?
![Screenshot from 2024-03-16 13-25-35](https://github.com/formbricks/formbricks/assets/114493480/a6360da7-40bc-4d28-a70b-611300a9f064)
![Screenshot from 2024-03-16 13-27-18](https://github.com/formbricks/formbricks/assets/114493480/1d2ae3b9-41c2-4ca3-a880-6640e95ef1e0)

**Comment by manish-singh-bisht** [comment]
or 
![Screenshot from 2024-03-18 14-14-36](https://github.com/formbricks/formbricks/assets/114493480/f7508296-daff-404d-9e84-7153cbf3c14e)

@jobenjada
