### ISSUE TITLE
Dockerfile not present

### ISSUE THREAD

**Issue by lpadula** [formbricks/formbricks#214]
### Issue Summary

Dockerfile not present. 
docker-compose.yml has a defined path: apps/web/Dockerfile but Docker file is not present on the repository.

### Steps to Reproduce

1. docker-compose pull
2. docker-compose up -d

error message:

unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /var/www/forms.broobe.net/apps/web/Dockerfile: no such file or directory

## Environment

- [ ] self-hosted formbricks with docker

**Comment by mattinannt** [comment]
@lpadula thanks for pointing that out. I re-added the Dockerfile now 💪
