### ISSUE TITLE
[BUG] Profile image showing incorrectly

### ISSUE THREAD

**Issue by sebiweise** [formbricks/formbricks#2141]
### Issue Summary

The profile image in the top right corner isn´t showing correctly. It is stretched.

### Steps to Reproduce

1. Upload a profile image

### Expected behavior

The profile image should be displayed like it was uploaded.

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/22999200/03aca2a3-e83f-4d45-aa6c-32d26f20ee6d)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows/Vercel
- Node: 18 and 20
```

**Comment by AshutoshViramgama** [comment]
Where the profile photo api is called try givinq quality parameter q = 100 for  eg

https://domain/_next/image?url=file.png&w=96&**q=100**

Ref to code:
FileName: EditAvatar.tsx->Line no59

![image](https://github.com/formbricks/formbricks/assets/38667700/22f74d76-1158-43a3-97a4-f36d210220cb)

**Comment by nik132-eng** [comment]
can I work on this issue?

**Comment by mattinannt** [comment]
@nik132-eng Thanks for offering your support. I assigned the issue to you :-)
