### ISSUE TITLE
[FEATURE] Quiz-Support

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2146]
### Is your feature request related to a problem? Please describe.

Has been requested several times now, adding this issue to keep track.

Formbricks is currently not fully suitable for running quizzes. This is mainly due to two missing features:
- multiple end-card / thank you cards than can be the results for the quiz
- points-logic for survey questions where participants can collect points and based on the number of points they will see a different ending.

### Describe the solution you'd like

Implement solutions for these two missing features.

**Comment by Hoss3770** [comment]
Hello
did points / scoring logic get shipped?
