### ISSUE TITLE
[FEATURE] Add multiple Custom Actions to survey

### ISSUE THREAD

**Issue by MaxWohlers** [formbricks/formbricks#2152]
### Is your feature request related to a problem? Please describe.

I highly appreciate being able to create custom actions on the fly with the newest update. The problem arrises that as a user I cannot add multiple custom actions (like multiple URLs) to the same survey (which is possible with Saved Actions btw). This hinders me in combining multiple sources/urls within the same survey, for which I have to resort back to saved actions (which I wanted to avoid). 

### Describe the solution you'd like

In the same manner as with Saved Actions, in which you can simple add mutliple conditions to the same survey, I like to have the option to add multiple custom actions to the same survey. 

Mockup:
<img width="276" alt="Bildschirmfoto 2024-02-28 um 11 45 38" src="https://github.com/formbricks/formbricks/assets/37698250/72cf40c8-b3ca-4b01-9ed9-5d32321990a5">

**Comment by jobenjada** [comment]
Hey and thanks for the feedback!

We designed this initially but scoped it out:

<img width="738" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/74862053-8939-48e8-8a3a-9dff0b95fcf7">

Not exactly what you requested and wouldn't work for css classes or ids.

Have you used multiple saved actions which are non URL before? 🤓

**Comment by MaxWohlers** [comment]
Hi Joannes, 
actually looks pretty good. If it means that I can add multiple URLs to the same survey as targets, I am happy :) Thanks for the quick update!

**Comment by jobenjada** [comment]
Hey @MaxWohlers - just a quick notice that we have this on the plate and are looking to ship as solution as quickly as possible :)
