### ISSUE TITLE
[BUG] Connectivity Issue: Response Handling via Network Connection

### ISSUE THREAD

**Issue by arghaffari** [formbricks/formbricks#2157]
### Issue Summary

First of all thanks for your great product. I have run Formbricks on Docker on my PC and then I connect to it using my laptop over the network, it can be launched successfully but at the time of sending the responses it calls the localhost address instead of the actual IP.the 

### Expected behavior

like other pages, it could have called the actual IP.

### Other information

This problem exists even at the time of sharing the survey, showing the localhost address.
![image](https://github.com/formbricks/formbricks/assets/8070577/ac2e4705-d809-41cf-b812-bb938955f83b)

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/8070577/1a70463a-b4c2-4daa-87d0-745d04969ba8)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Ubuntu 22.04
- Node:
- npm:
```

**Comment by ShubhamPalriwala** [comment]
Hey, glad that you liked the product!

Did you change the `WEBAPP_URL` & `NEXTAUTH_URL` in your env variables to your Public Facing IP?
cc: https://formbricks.com/docs/self-hosting/external-auth-providers#important-run-time-variables
