### ISSUE TITLE
[BUG] thank you can never shown after clicking finish button

### ISSUE THREAD

**Issue by pravi** [formbricks/formbricks#2172]
### Issue Summary

On our form https://pirates.org.in/elections/2024/ the finish button never shows the thank you card. The Finish button just greyed out. The data gets submitted anyway, but it is confusing. It allows clicking the button multiple times and that causes duplicate submissions. I have ublock origin in firefox, so that could be an issue. Disabling ublock origin did not fix it though. 

### Steps to Reproduce

1. [On our survey](https://pirates.org.in/elections/2024/)
2. Entered all fields
3. Upon clicking Finish
4. ...

### Expected behavior

It should should show the thank you card.

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/708222/e1608d33-6f96-447c-8492-b688193f3e4c)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Debian GNU/Linux sid, Firefox 121.0.1
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@pravi thanks for the bug report. I think there is currently an issue with our iFrames. We try to reproduce this and come up with a fix asap!

**Comment by pravi** [comment]
Thanks, that seems to have fixed the issue. I can now see the thank you card at the end.
