### ISSUE TITLE
[BUG] logic jump misses an option to chose Thank You card

### ISSUE THREAD

**Issue by pravi** [formbricks/formbricks#2173]
### Issue Summary

When choosing a logic jump, only end of survey is available, not thank you card. This results in people clicking on next button multiple times and resulting duplicate submissions. Option to choose thank you can will allow us to end the survey gracefully.

### Steps to Reproduce

1. Add a question
2. Add logic
3. Look for thank you card as option
4. ...

### Expected behavior

We should be able to jump to thank you card. This may be a result of thank you card never appearing, which is reported as #thank

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Debian GNU/Linux sid, Firefox 121.0.1
- Node:
- npm:
```

**Comment by jobenjada** [comment]
Hey! 

Could you make a screen recording? Because "End of Survey" should work like this:

1. In app survey without Thank You Card: Close survey
2. In app survey with Thank You Card: Show TY card
3. Link surveys always have TY Card on so it jumps there

What am I missing?

Cheers!

**Comment by pravi** [comment]
This was related to https://github.com/formbricks/formbricks/issues/2172 which is now fixed. So we can close this.
