### ISSUE TITLE
[BUG] S3 storage isn´t used when S3_REGION isn´t defined

### ISSUE THREAD

**Issue by sebiweise** [formbricks/formbricks#2181]
### Issue Summary

S3 storage isn´t used when S3_REGION isn´t defined

### Steps to Reproduce

1. Add S3 storage without S3_REGION var

### Expected behavior

S3 storage should be used not local storage

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Vercel
- Node: 18.x
```

**Comment by mattinannt** [comment]
Solved in https://github.com/formbricks/formbricks/pull/2144
