### ISSUE TITLE
[FEATURE] Increase size of attached images

### ISSUE THREAD

**Issue by MaxWohlers** [formbricks/formbricks#2193]
### Is your feature request related to a problem? Please describe.

I have the need to ask survey respondents for either their rating or preference of an image (e.g. website screenshot). The problem is that these images are small in scale and cannot be increased in size. Any detailed information (for example asking a preference for two prototypes with a small visual change) cannot be comprehended by respondents. Most (all) image related questions are thus not feasible for me.

### Describe the solution you'd like

Allow respondents to increase the size of the image. Could be feasible by a larger popup window, or a new tab (desktop) when picture is clicked. 

Example: in Hotjar, if you hover over the image, you see the CTA to open in new tab. 
<img width="405" alt="Bildschirmfoto 2024-03-05 um 17 10 56" src="https://github.com/formbricks/formbricks/assets/37698250/b73d0be1-3986-4a6b-a6fe-8d84ecbeb312">

**Comment by mattinannt** [comment]
@MaxWohlers Thanks for bringing this up. We have created a ticket for the team 😊

**Comment by mattinannt** [comment]
Implemented in https://github.com/formbricks/formbricks/pull/2228 and will be included in the next patch release today 😊
