### ISSUE TITLE
[BUG] Font not displayed correctly ( in Angular project )

### ISSUE THREAD

**Issue by paulceli** [formbricks/formbricks#2196]
### Issue Summary

Fonts are not the same in the App as to what is shown in the preview ( which is much nicer ).
It seems like its missing attributes..

This problem has been discussed and reproduced on the discord here : [https://discord.com/channels/979077669410979880/1207799730537635842](https://discord.com/channels/979077669410979880/1207799730537635842)

### Steps to Reproduce

To reproduce the problem, simply generate a new angular project from the angular-cli and add the formbricks lib and component.
A stackblitz link is also available in the discord chat linked above

### Expected behavior

Have the same Font and general render from what can be seen in the preview panel.

### Other information

*No response*

### Screenshots

![image](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/d4424c97-e3ac-4804-9050-c3643afa6404/55d4a769-11a3-4836-ba39-3f1a0e370c40?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC9kNDQyNGM5Ny1lM2FjLTQ4MDQtOTA1MC1jMzY0M2FmYTY0MDQvNTVkNGE3NjktMTFhMy00ODM2LWJhMzktM2YxYTBlMzcwYzQwIiwiaWF0IjoxNzA5OTAxMDY5LCJleHAiOjMzMjgwNDYxMDY5fQ.ofKHno43I42HcuU2K-AhC6hz-yTsNptolFt8yS0BgQM)

### Environment

- [ ] Formbricks Cloud ([app.formbricks.com](http://app.formbricks.com))
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: windows
- browser: firefox:latest
```

**Comment by mattinannt** [comment]
@paulceli thanks for raising this issue 😊 As @ShubhamPalriwala was already able to reproduce this, we will now come up with a solution to fix this 😊
