### ISSUE TITLE
[BUG] Downloads not working

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2199]
### Issue Summary

Downloads stopped working for us in 1.6.0 (even for surveys without any responses).
We are not using S3 yet (waiting for https://github.com/formbricks/formbricks/pull/2144). In the k8s logs I see the following errors:

[Error: ENOENT: no such file or directory, open './uploads/clth7dw2k000008k16ak2dd1f/private/export-in/test-survey.xlsx'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './uploads/clth7dw2k000008k16ak2dd1f/private/export-in/test-survey.xlsx'
}
[Error: ENOENT: no such file or directory, open './uploads/clth7dw2k000008k16ak2dd1f/private/export-in/test-survey.csv'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './uploads/clth7dw2k000008k16ak2dd1f/private/export-in/test-survey.csv'
}

### Steps to Reproduce

1. open a survey that received answers
2. Click on Download -> All responses (CSV)
3. download not starting, toast error appears
![image](https://github.com/formbricks/formbricks/assets/64426524/a9f8fcdd-2fd6-4888-97c6-ffd0be848c9d)

### Expected behavior

you can download the responses

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- version 1.6.0, S3 not configured
```

**Comment by ikbalarslann** [comment]
i can take this one if you didn't started working on it
