### ISSUE TITLE
 form pre-filling via url-parameter

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#22]
Add values via URL-parameter to prefill fields of nocode forms.
e.g. snoopforms.com/f/abcd?email=matti@snoopforms.com to prefill field with id email field.

**Comment by alokthakur142** [comment]
+1

**Comment by Glassback** [comment]
+1

It would be useful to be able to fill hidden fields with the URL to enter for example the user id and then update it with workflows.

Example: Following an action on my site, I solicit feedback from the user by sending him a link with his account id or a temporary token in the URL.

As soon as he fills the form, I update my database with his ID.

**Comment by mattinannt** [comment]
I am closing this issue due to the ongoing migration to Formbricks with a completely new code base. Surveys are now integrated directly into the websites of our customers (inline or popups) and so url parameters are no longer an option.
