### ISSUE TITLE
[BUG] Images continuously fail to load

### ISSUE THREAD

**Issue by SirHazza** [formbricks/formbricks#2230]
### Issue Summary

Images I've uploaded to formbricks don't always load.

### Steps to Reproduce

1. Go to formbricks account
2. Profile image doesn't load

or

1. Start a survey I've created
2. Images uploaded to the survey don't load

### Expected behavior

Images should always load correctly

### Other information

I started using the cloud instance yesterday, and unfortunately I've had continuous intermittent issues with images I've uploaded not loading in various places. For example, even my profile picture doesn't load now, console error `Failed to load resource: the server responded with a status of 502 ()`.

Or the survey I created for people to pick between different pictures doesn't always load images, this has occurred on android, ios and desktop devices. I even recreated the survey a second time, uploading the images again and also compressing them down, still having this issue.

### Screenshots

* Profile image not loading

![Screenshot 2024-03-13 at 11 43 27 am](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/395644a9-d4e0-4fe5-a772-23f3fd9dd19b/d7576991-4938-401b-a38d-41b4319deda8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC8zOTU2NDRhOS1kNGUwLTRmZTUtYTc3Mi0yM2YzZmQ5ZGQxOWIvZDc1NzY5OTEtNDkzOC00MDFiLWEzOGQtNDFiNDMxOWRlZGE4IiwiaWF0IjoxNzEwNDE2NzcwLCJleHAiOjMzMjgwOTc2NzcwfQ.a7chJk11p4b7FYaLFkznfGjSJnrJ_QkfZ-lUwoRxnt0 "=129x")

* Survey images not loading on android

![signal-2024-03-13-083212](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/782cb358-8eae-4eb1-b93e-f338a3ac38cc/fc1aa4ec-ddaa-47a6-a802-8c08d015b015?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC83ODJjYjM1OC04ZWFlLTRlYjEtYjkzZS1mMzM4YTNhYzM4Y2MvZmMxYWE0ZWMtZGRhYS00N2E2LWE4MDItOGMwOGQwMTViMDE1IiwiaWF0IjoxNzEwNDE2NzcwLCJleHAiOjMzMjgwOTc2NzcwfQ.61Cve0GKgGTy1rzbwEYeEf19lHFLrx73Clii-V0wGBw)

* Survey images not loading on iOS

![signal-2024-03-13-114450_002](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/b38ee9cc-3a1f-47e3-aef2-ac268cdfed69/20a8d1ef-0de9-49f8-825e-51437a8c1e42?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNmZTk3MzIyLWQzZWMtNDcwNy05NDA1LTgzYWEwYjZjMDYxZC9iMzhlZTljYy0zYTFmLTQ3ZTMtYWVmMi1hYzI2OGNkZmVkNjkvMjBhOGQxZWYtMGRlOS00OWY4LTgyNWUtNTE0MzdhOGMxZTQyIiwiaWF0IjoxNzEwNDE2NzcwLCJleHAiOjMzMjgwOTc2NzcwfQ.HMl1nnNnCFPBbt72y2dzu9lHaFao-xgxzZMXriNJpns)

### Environment

- [X] Formbricks Cloud ([app.formbricks.com](http://app.formbricks.com))
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: windows, macos, ios, android
- browser: chrome latest
```

**Comment by mattinannt** [comment]
@SirHazza thanks for reporting this. We will try to reproduce this and come up with a fix asap :-)

**Comment by SirHazza** [comment]
Just tested it again myself and it remains an issue. Here's what it looks like on Windows Chromium: 122.0.6261.128 (private browsing).

![Screenshot 2024-03-13 234737](https://github.com/formbricks/formbricks/assets/31993698/46ff05b0-3d18-4a59-836f-155755692dd5)

And more of my users have reported this issue, but not everyone encountered it.

**Comment by mattinannt** [comment]
@SirHazza We are currently continuing to improve the image resolution to solve the bug once and for all :-) 

@pandeymangg Can you please remove the next-cache from the S3 images and only work with cache-headers for the response?
