### ISSUE TITLE
[BUG] Summary view proportions don't add up to 100%

### ISSUE THREAD

**Issue by MaxWohlers** [formbricks/formbricks#2233]
### Issue Summary

In the summary view for Multiple-Choice Single-Select Question, the proportions do not always add up to 100%, but to 101% for example, most likely due to an rounding error. 

### Steps to Reproduce

1. Have Multiple-Choice Single-Select Question
2. Get numerous responses with various choice proportions
3. Go to Summary tab
4. Get wrong total proportions due to rounding error

### Expected behavior

No rounding error

### Screenshots

<img width="477" alt="Bildschirmfoto 2024-03-13 um 21 08 09" src="https://github.com/formbricks/formbricks/assets/37698250/87ae13a9-9282-4c25-9702-dbe9851e47ad">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by jonas-hoebenreich** [comment]
How would you fix that? By using more decimal places (and thus reducing the rounding error, but it may still not add up to 100%). Or by deliberately rounding incorrectly to force 100% (but then displaying mathematically incorrect numbers)?

**Comment by mattinannt** [comment]
@MaxWohlers @jonas-hoebenreich We will add another decimal to make the numbers more accurate :-)
