### ISSUE TITLE
[DOC] Add a side note for the WSL2 dev setup

### ISSUE THREAD

**Issue by dragos-cojocaru** [formbricks/formbricks#2234]
### Issue Summary

This is not a bug. This is a documentation improvement suggestion.

[Some contributors](https://discord.com/channels/979077669410979880/1165191112177233970/1165191112177233970) are facing issues when trying to get Prisma to connect to the database (as part of running the `pnpm go`) running in the Docker's container on WSL2. This happens if WSL2 has its own PostgreSQL service up and running. 

To fix this, before running `pnpm go`, WSL2 contributors should make sure they stop the WSL2 Postgres service running: `sudo systemctl stop postgresql`

I suggest adding a side note for the WSL2 in the documentation around the `pnpm go` command: Contributing > Setup Dev Environment > Local Machine Setup.

### Steps to Reproduce

1. Have a postgres service installed and running in WSL2
2. Follow the steps on https://formbricks.com/docs/contributing/setup#local-machine-setup
3. After running `pnpm go` you will receive the following error: `Error: P1000: Authentication failed against database server at 'localhost', the provided database credentials for 'postgres' are not valid.`

### Expected behavior

N/A

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
N/A
```

**Comment by mattinannt** [comment]
@dragos-cojocaru thanks for pointing this out. We will update the docs :-)
