### ISSUE TITLE
[FEATURE] Easypanel Template

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#2260]
### Is your feature request related to a problem? Please describe.

Easypanel makes deploying an application easier. They have templates for many different technologies (Node.js, Postgres,..) and also open source software products (e.g. Budibase). But a Formbricks Template is still missing.

### Describe the solution you'd like

Add a Formbricks Template to the Easypanel templates directory: https://github.com/easypanel-io/templates

**Comment by ShubhamPalriwala** [comment]
PR has been opened: https://github.com/easypanel-io/templates/pull/514
