### ISSUE TITLE
[FEATURE] Add dark mode 

### ISSUE THREAD

**Issue by nik132-eng** [formbricks/formbricks#2267]
### Is your feature request related to a problem? Please describe.

Using dark mode will cut the glare from your screen significantly for comfortable viewing. Users also can dim their screen manually in light mode or set their brightness to adjust automatically based on the surrounding lighting. Either option will effectively reduce glare if you prefer not to use dark mode.

### Describe the solution you'd like

In Formbricks doc there is dark mode button i want to put same logic in to main form bricks app
![image](https://github.com/formbricks/formbricks/assets/77881638/795b881e-96b9-4a27-b54f-a1504e6839a4)
![image](https://github.com/formbricks/formbricks/assets/77881638/666d6f99-018a-4bda-ab34-790204d3c753)

**Comment by shubh0709** [comment]
Hi @nik132-eng, can you assign this to me?

**Comment by nik132-eng** [comment]
> Hi @nik132-eng, can you assign this to me?

I am not a maintainer but a contributor if maintainers allow this feature happy to work on this by myself.

**Comment by jobenjada** [comment]
hey @shubh0709 and @nik132-eng - thanks for your excitement around dark mode :)

We have it on the roadmap but do not deem this a game-changing feature, so we postpone it. I'll keep this issue open for other community members to see that we have it on the map 🤓

**Comment by mattinannt** [comment]
Closing this due to development complexity and lack of demand for the feature. We may reopen it if demand increases 😊
