### ISSUE TITLE
[FEATURE] Explain question types with tooltip

### ISSUE THREAD

**Issue by nik132-eng** [formbricks/formbricks#2268]
### Is your feature request related to a problem? Please describe.

When the user first time came it took some time to understand the product. If we show the use of each functionality their time to understand the feature by doc got reduced and the product became more user-friendly.

### Describe the solution you'd like

I want to add a tooltip for each question which shows what it does and the user will adopt for their use.

| ![image](https://github.com/formbricks/formbricks/assets/77881638/7e48de15-44a6-4acb-9d80-7fcb1c1ef08e) | ![image](https://github.com/formbricks/formbricks/assets/77881638/ae08b1e9-3061-4a2b-bb3d-d41061ffd3c9) | ![image](https://github.com/formbricks/formbricks/assets/77881638/e5c9968b-9b6d-46b3-89e3-b2a21ab535ae) |
|----------|----------|----------|

**Comment by jobenjada** [comment]
Hey! Thanks for your feature suggestions.

Which question types did you find confusing?

Cheers
Johannes

**Comment by nik132-eng** [comment]
> Hey! Thanks for your feature suggestions.
> 
> Which question types did you find confusing?
> 
> Cheers Johannes

I was confused about NPS, CTA, and Consent after clicking on the button understood but I think if a tooltip is given it will be easier.
