### ISSUE TITLE
[FEATURE] make preview's tab mac buttons workable 

### ISSUE THREAD

**Issue by nik132-eng** [formbricks/formbricks#2269]
### Is your feature request related to a problem? Please describe.

These buttons do nothing in preview mode so we can add the functionality of making tab size maximize or minimize
![image](https://github.com/formbricks/formbricks/assets/77881638/a73606de-abe7-4835-a0c0-9f89cb848607)

### Describe the solution you'd like

we can make this right side maximize the button into left side yellow button
![image](https://github.com/formbricks/formbricks/assets/77881638/c838af7b-f02a-426d-a53c-777028654f80)

on red button remove preview window 

on green button make it small/start mobile mode

**Comment by jobenjada** [comment]
hey nik! Thanks for your suggestion, but we will remove the these buttons when we revamp our survey editor. So it does not make sense to rework these at this point.

I will close the issue for now.

Cheers
Johannes
