### ISSUE TITLE
Display user Email instead of ID when available

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#227]
### Is your proposal related to a problem?

On the survey summary and response pages, users are referred to via unique ID.

### Describe the solution you'd like

When the user object has an email address display the email address instead of the cryptic ID.

![grafik](https://user-images.githubusercontent.com/72809645/231459074-3a819d3f-665a-4109-a8b8-3cb895dc4fc6.png)

**Comment by poudyalamit** [comment]
I may do this

**Comment by Ankan-cyber** [comment]
@jobenjada can you give some more context where to find the file and which endpoint the issue is occurring

**Comment by nc1337** [comment]
@jobenjada I am able to figure out where the changes are needed to be done. I am figuring out how to setup the project.

**Comment by jobenjada** [comment]
@Ankan-cyber and @nc1337 thanks a lot for your interest in contributing! @poudyalamit is already working on the issue. Feel free to join our Discord and I'm happy to find a good first issue for you to contribuet :) 

https://formbricks.com/discord

**Comment by jobenjada** [comment]
@nc1337 and @Ankan-cyber I've added another good first issue here:

https://github.com/formbricks/formbricks/issues/234
