### ISSUE TITLE
[FEATURE][🕹️] Add Unsplash API for image backgrounds

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2279]
### Is your feature request related to a problem? Please describe.

People have to be aware of Unsplash and comparable platforms to find good background images for their surveys.

### Describe the solution you'd like

Build an integration with the free Unsplash API.

--------
### Status Quo:
<img width="647" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/10a282b4-5c9a-426e-aa26-dae5043b49e6">

### Tasks:

1. Rename "Image" to "Upload
2. Add a new tab called "Image" with a Search bar at the top and three columns of pictures, like so:

<img width="449" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/c223c2fd-0bb2-4c39-8591-0a276a9abe1c">

### Technical Considerations

- Most images on Unsplash have a very high resolution (4000x6000 pixels). Since we do not resize images, the size effects the loading time of the survey. To keep the loading times short, please make sure to not request the images not in full size but  in 1920x1080 pixels (or what Unsplash calls "M").

- The feature should only be enabled if a UNSPLASH_API_KEY is present in the environment variables.

Here is all the info you need to create a free Unsplash Account to get Demo access to their API:

[Unsplash API](https://unsplash.com/developers): here's where you can sign up and check out the API

[API Guidelines](https://help.unsplash.com/en/collections/1451694-api-guidelines)

[API Documentation](https://unsplash.com/documentation)

Thanks!

**Comment by raysubham** [comment]
@jobenjada Can I pick this ?

**Comment by vidhikapadia2799** [comment]
@jobenjada I would like to work on this. Assign this.


Thanks

**Comment by vidhikapadia2799** [comment]
@jobenjada I just read how to assign issue. It is okay if I start work on this ?

**Comment by jobenjada** [comment]
you got it exactly right @vidhikapadia2799  - the issue is yours :))

**Comment by ShubhamPalriwala** [comment]
Thanks @vidhikapadia2799 for shipping this 🚀

Completed in #2341
