### ISSUE TITLE
[FEATURE] Promote survey from "Development" to "Production" environment and vice versa

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#228]
### Is your proposal related to a problem?

As a user, I have to create surveys twice: First in the development environment to test and then in the production environment. Having to set up surveys twice incl. logic is time-consuming and tedious, because I have to switch environments back and forth or be logged in in two browsers.

### Describe the solution you'd like

I'd like to have an option which says "Copy to Development" when I'm in the production environment and  "Copy to Production" when I'm in the development environment.

## Tasks

1. Add a dynamic item to the survey component in the SurveyList.tsx **(done)**
![grafik](https://github.com/formbricks/formbricks/assets/72809645/9c52b168-2a0d-4baf-95ff-3fb9d7516283)

And in the production environment:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/ce08236e-3337-442e-9aa4-f0f4c684d766)

2. On click, copy the survey to the other environment (from prod to dev and vice versa).

3. Forward to the new environment

4. Display success toast (as drafted in the branch) **after** the user got forwarded to the new environment. 

## Hints
- There already is a "Duplicate" function in the SurveyList.tsx which you can use.
- There already is "Switching Environment" functionality in the rop right menu ( EnvironmentNavBar.tsx ) which you can use.
- I have added the UI in the branch "feature/copy-to-prod" which already adapts to the current environment.
- Make sure you only copy the plain survey and none of the responses or metadata (displays, etc.)
- Make sure to generate a new unique ID for the survey

**Comment by Ankur-Datta-4** [comment]
@jobenjada I'd like to work on this
