### ISSUE TITLE
add: new headless sdk

### ISSUE THREAD

**Issue by kymppi** [formbricks/formbricks#229]
### Is your proposal related to a problem?

I have a "strict" design style for a project I'm working on and I'd like to add formbricks to it. Current problem is that I cannot override formbrick's styling.

### Describe the solution you'd like

Possibly a function on the formbricks SDK to get the form settings and disable the modal provided by the SDK.

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by mattinannt** [comment]
@kymppi What parts of the UI do you want to change?

**Comment by kymppi** [comment]
Not really the UI, just the CSS styling of the components when showing them inside a next.js website. I thought that the easiest way to achieve this would be to allow the developer to make a custom form component that would render the form based on the settings provided by formbricks.

**Comment by kymppi** [comment]
This would be really useful when using a component library. Then the form would match the style of the rest of the website.

**Comment by kymppi** [comment]
I'm talking about this

![image](https://user-images.githubusercontent.com/48528700/231497694-7309b5c5-a492-4f99-a8fd-859ebd1c3171.png)

**Comment by mattinannt** [comment]
Oh, you have darkmode, right? The dots shouldn't be all black. But that's another issue to fix.
I think the easiest way to provide more customisability would be to be to enable developers to overwrite the styling. This way it works in all different web-frameworks including plain HTML/CSS/JS.
We could also think about providing a headless JS widget where developers can build the survey themselves using components. But at the moment the functionality, surveys and questions types are changing so fast that this could be something for later.

**Comment by kymppi** [comment]
Yeah, my idea was more towards to the headless widget 👍

**Comment by kymppi** [comment]
Interesting thought that came to my mind is: it would be probably the easiest to maintain if the current SDK would use the headless SDK as a dependency and add the stylings on top of that. 

This would allow for more flexibility

**Comment by mattinannt** [comment]
@kymppi Sounds good. Internally we need to migrate the Widget (UI) into a separate package soon, because we need to use it (with modifications) both in the Formbricks-app (Preview, Survey Builder, Templates,...) as well as the client Widget itself.
So maybe in that step we can also make preparations for a headless JS lib. But I would postpone that a bit because our current focus now is on better stability and more questions types to enable users to build the surveys they need.
