### ISSUE TITLE
[FEATURE] - Multiple Thank-You Cards for different form outcomes

### ISSUE THREAD

**Issue by eoanodea** [formbricks/formbricks#2294]
### Issue Summary

I have a form that has many outcomes. Some of them are brought to Call to Action, which are then brought to external links. When you click the external link, the form also goes to the next form field. Is there a way to prevent this behaviour?

I have tried to add logic to prevent this, but it will never save

### Steps to Reproduce

1. Create a form
2. Add two fields (first one being a CTA), second one whatever you like
3. Set the first field (CTA) to have an external link
4. Test the form and click the button that should bring you to an external link
5. The link will open in a new tab. Go back to the previous tab and you'll see the form now shows the next field

### Expected behavior

Don't bring the form to the next field, or allow logic so I can redirect the form to the ending page

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Mac OS X
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@eoanodea So your call-to-action questions are essentially an end card for the survey?
In general, the behavior you're seeing is not a bug, it's how it's supposed to be, but it may not be the best for your use case.
We don't currently support multiple end cards/thank you cards, so for now the only solution for you would be to use logic jumps to redirect users to the thank you card and prevent them from seeing multiple call-to-action cards in a row.

We will come up with a feature proposal internally to support multiple thank you cards that solves your problem :-)

**Comment by jobenjada** [comment]
shipped :)
