### ISSUE TITLE
[FEATURE][🕹️] Store display URL for in-app surveys as meta data

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2305]
### Is your feature request related to a problem? Please describe.

users want to know on which URL a (in-app) survey was displayed.

### Describe the solution you'd like

It seems a meta data field `url` is already present, but unused. Get the current browser URL when a survey response is created in the `@formbricks/js` package, include it in the payload for the response create endpoint and store it in the metadata as `url`.

display the URL here in the SingleResponseCard.tsx

<img width="442" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/d27fd211-9f79-4afd-bb30-2c852a922c20">

**Comment by jonas-hoebenreich** [comment]
Please also make sure to include the display URL in data exports and expose it via API :)

**Comment by nik132-eng** [comment]
![hoverprofile](https://github.com/formbricks/formbricks/assets/77881638/10d7157d-6a8b-4436-8409-b2f254ebf276)

Is this proper?

**Comment by mattinannt** [comment]
@nik132-eng looks good :-)
