### ISSUE TITLE
add: ability to handle errors on the SDK

### ISSUE THREAD

**Issue by kymppi** [formbricks/formbricks#231]
### Is your proposal related to a problem?

I don't see currently a way to use a custom error handler for any errors that might occur when submitting the form. For ex: network errors

### Describe the solution you'd like

I actually made a PR (#201) a while back adding this functionality. I think it could be done kinda the same way by having a function on `formbricks.init` that gets called with the error.

### Additional context

This is really a must since the website developer needs to have a way of notifying the end user if anything goes wrong.

**Comment by kymppi** [comment]
I can handle, if you agree how it should be implemented :p

**Comment by mattinannt** [comment]
@kymppi Sounds great. Can you share a suggestion how you would implement it and what the developer experience would look like?

**Comment by kymppi** [comment]
I would implement it as I did before (see PR #201) and the usage of it would be:

```ts
formbricks.init({
// options
handleError: (err) => {//run code}
})
```

If the developer would like to turn off errors they can just make the handleError an empty function. By default, the function is going to log them to the console.

How does that sound?

**Comment by mattinannt** [comment]
@kymppi sounds great! 💪
If you like please start implementing 🤗
