### ISSUE TITLE
[FEATURE] Add auto-refresh to the analysis view

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#2312]
### Is your feature request related to a problem? Please describe.

Currently a users needs to do a hard refresh to see new results in the summary and responses view. While for example doing a live survey in front of an audience this isn't ideal.

### Describe the solution you'd like

Let's make periodic requests to the server checking for new responses (e.g. every 10 seconds) and display them when they come in. Since we already have caching built into the services this should only produce a new database call when the responses changed.

### Additions

1. Update the auto-refresh function on modal close

We're refreshing the data when the user closes this modal:
<img width="1169" alt="image" src="https://github.com/user-attachments/assets/c568171f-3ceb-40e8-9bd9-63e1e66e232f">

Currently, it only refreshes the survey count in the Responses tab:
<img width="338" alt="image" src="https://github.com/user-attachments/assets/4eeb8022-fa15-4100-8271-3d31b5caf017">

Please make sure to update the Summary page as well.

2. Filtering does not effect the count in the tab:
<img width="588" alt="image" src="https://github.com/user-attachments/assets/1597f628-8016-44ba-a9e1-475f966445e9">

No matter which filters are set, it shows the total number of responses.

Instead, it  should show "Responses (3 of 5)" to indicate that the Response view currently does not show the total number of responses but the filtered down selection (like it actually does).

### Describe alternatives you've considered

We still need to check how complex this is with the current implementation of filtering and pagination. If it's still causing too many server calls that we want to avoid by default we might also add a `live view` toggle which is off by default and can be turned on. 

### Additional context

-

**Comment by sohan9819** [comment]
I think making a nextjs router.refresh() inside a setInterval with some required interval set can work.
