### ISSUE TITLE
[BUG] Unsaved Changes Confirm even though changes were saved

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#2320]
### Issue Summary

Even though changes were just saved, sometimes it still asks if the changes should be saved or discarded.

https://github.com/formbricks/formbricks/assets/675065/9828bcde-95fb-45e0-98ad-e0dc1fe5094f

### Steps to Reproduce

1. Open an existing survey
2. Make a change
3. Save the changes
4. Go "Back"

### Expected behavior

When the changes are already saved, don't show the confirmation modal

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by nik132-eng** [comment]
can I take this issue? @mattinannt
