### ISSUE TITLE
[FEATURE] Allow survey participants to self-select a language on link surveys

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2326]
### Is your feature request related to a problem? Please describe.

the auto assigned language might not be right (user request, twitter)

### Describe the solution you'd like

Allow survey participants to self-select a language on link surveys.

**Comment by joyal007** [comment]
https://www.loom.com/share/53c2f8fd8b3447e2b382b856b63cda5e?sid=c0223e38-b437-4f3f-8b62-35312766128a

The language switching dropdown doesn't seem to fit well with the UI. I reused the Language Switch component from multiLanguage. Any suggestions for improving the UI?

**Comment by Dhruwang** [comment]
Hey @joyal007 , this looks good but it should be in the top right corner and not in the middle 😊
