### ISSUE TITLE
[BUG] Surveys fail to load after migration to 1.6.1

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2330]
### Issue Summary

After I pulled the latest docker image and tried to run it, the surveys won't load anymore. In the browser console I get the following error:

Uncaught (in promise) TypeError: cannot read properties of undefined (reading 'length')
![image](https://github.com/formbricks/formbricks/assets/64426524/76edb6e0-3687-4454-a742-2da815eb1179)
It seems like the issue is in this line: https://github.com/formbricks/formbricks/blob/1a21f40e5d16f7e987a585e97612f72de99733d9/packages/ui/SurveysList/index.tsx#L51
![image](https://github.com/formbricks/formbricks/assets/64426524/c40fe178-5176-4184-b86a-8fdedb0cb15c)

### Steps to Reproduce

1. upgrade to 1.6.1 and run migrations
2. surveys do not load anymore

### Expected behavior

no error, surveys visible

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
v1.6.1
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich thanks for reporting; I will take a look :-)

**Comment by jonas-hoebenreich** [comment]
sorry, I found the issue: I made some terraform changes that unfortunately had the side effect that some headers changed in a way that nextjs could not handle 🙈 
Sorry for stealing your time

**Comment by mattinannt** [comment]
No worries; still a good point that we maybe should improve the error handling around server actions 😉
