### ISSUE TITLE
[FEATURE] underscore for hidden fields because its norm but enabled camelCase only

### ISSUE THREAD

**Issue by bnmg** [formbricks/formbricks#2332]
### Is your feature request related to a problem? Please describe.

The problem is that - so i cant deliver normal `utm_*` absoluely, or any other underscored attr's we have in our solution
But  it is the standart.

### Describe the solution you'd like

just allow in your  curernt `regex` for `hidden fields` the underscore `_` symbol in that namespace characters  

### Describe alternatives you've considered

no alternatives to underscore, unfortunately ;)

**Comment by mattinannt** [comment]
Hey @bnmg, we already have a PR open for this and will merge it soon :-) 
https://github.com/formbricks/formbricks/pull/2250
