### ISSUE TITLE
[BUG] Unnecessary loader in Actions tab

### ISSUE THREAD

**Issue by shash68i** [formbricks/formbricks#2335]
### Issue Summary

When tapping on the Actions tab in the Actions & Attribute nav item, there's a CLS because of the appearance of a tiny loader which is not required. We see the "Add Action" button then have the loader and again see the "Add Action" button.

### Steps to Reproduce

1. Click on the Actions and Attributes item from the navbar
2. Click on the Actions tab
3. Click on the Attributes tab
4. Click again on the Actions tab

### Expected behavior

The loader should be removed and the "Add Action" button should be shown directly like there's  "How to add attributes" button in the Attributes tab. Or we can have a loader inside the button for "Add Action" the same as we have in "How to add attributes" button.

### Other information

https://www.loom.com/share/1a33806677854d3da9de320e95939b8e?sid=9b78a458-b054-476d-98cf-5f8be4428fdf

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Mac OS Sonoma 14.4
```

**Comment by mattinannt** [comment]
Thanks for reporting this :-) I think it's a small issue with the `loading.tsx` inside the action route and can be changed easily :-)

**Comment by shash68i** [comment]
@mattinannt I would like to work on this.
