### ISSUE TITLE
[FEATURE] Node Red Integration

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2337]
### Is your feature request related to a problem? Please describe.

No Node-Red integration

### Describe the solution you'd like

<img width="504" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/c79e8ed5-2fe7-4c1d-b440-d82a31937712">

**Comment by mattinannt** [comment]
Doesn't look like a fit for the current Formbricks product strategy
