### ISSUE TITLE
[BUG] Recall does not work with prefilled answers

### ISSUE THREAD

**Issue by jfbus** [formbricks/formbricks#2338]
### Issue Summary

I have a link survey with a first question that I want to prefill. Il the next question tries to recall the response of the first question, the prefilled response is not recalled, and the empty value is used instead.

If I display the survey without prefilling and answer all questions, the first response the correctly recalled.

### Steps to Reproduce

1. create a link survey
2. add a text based question
3. add another question and add a recall of the first question in the title
4. call the survey with a prefill url parameter

### Expected behavior

The second question should be displayed with the prefilled response in the title.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- Client OS: Mac
- Brower: Arc 1.35.0
- Server: standard Docker image (v1.6.1)
```

**Comment by mattinannt** [comment]
@jfbus thanks for opening an issue for this 👍

@Dhruwang Can you please try to reproduce this and find a solution for this if it's an problem? 😊

**Comment by jobenjada** [comment]
hey @jfbus just added the fix to the merge queue :) 

Thanks for letting us know! Feel free to share more feedback as use Formbricks more 🤸
