### ISSUE TITLE
[BUG] JS Exception while tagging a response

### ISSUE THREAD

**Issue by jfbus** [formbricks/formbricks#2339]
### Issue Summary

I have a brand new self-hosted installation, and I have created my first survey, and have some responses.

I'm trying to add my first tags by clicking on Add tag:

![Capture d’écran 2024-03-26 à 15 59 02](https://github.com/formbricks/formbricks/assets/808338/97b6ef39-7264-42af-a4a5-0db3a48649a6)

When I start typing a new tag, the following exception appears in the console:

```
9997-855a7025e8810cc0.js:1 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at H (9822-0183831d87520c3b.js:1:9718)
    at L (9822-0183831d87520c3b.js:1:8259)
    at Object.setState (9822-0183831d87520c3b.js:1:6942)
    at 9822-0183831d87520c3b.js:1:13374
    at aI (1dd3208c-e5f8207d2ef6f0e0.js:1:72883)
    at a3 (1dd3208c-e5f8207d2ef6f0e0.js:1:84324)
    at a5 (1dd3208c-e5f8207d2ef6f0e0.js:1:84962)
    at a8 (1dd3208c-e5f8207d2ef6f0e0.js:1:84846)
    at a5 (1dd3208c-e5f8207d2ef6f0e0.js:1:85907)
```

and the screen displays:

![Capture d’écran 2024-03-26 à 15 58 41](https://github.com/formbricks/formbricks/assets/808338/7e598446-e24a-45e6-a307-77fe6bf717e7)

### Steps to Reproduce

1. Select my survey
2. Click on responses
3. Click on "Add tag"
4. Type anything in the "Add tag" text field

### Expected behavior

A new tag is added...

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- Client OS: Mac
- Client browser: Arc 1.35.0
- Server: standard Docker image v1.6.1
```

**Comment by ckeboss** [comment]
I also have the same issue. It was from an upgrade from 1.5 => 1.6.1

**Comment by Dhruwang** [comment]
Thank you for reporting the issue 😊
It has been solved in this PR https://github.com/formbricks/formbricks/pull/2249 , and will be included in our next release ! 🤗
