### ISSUE TITLE
[FEATURE]: better error responses in the API

### ISSUE THREAD

**Issue by kymppi** [formbricks/formbricks#235]
**Is your feature request related to a problem? Please describe.**
I think that the API responses could be formatted differently, so they all use the same style and provide the necessary info on how to fix the error. Currently, the single `message` field is not enough for proper error handling.

**Describe the solution you'd like**
This is an example I implemented on my own API project, it doesn't have to be just the same but something like this 🙂 
![image](https://user-images.githubusercontent.com/48528700/232092702-820d2d1c-70ae-45a6-8988-d65a62907bc8.png)

Your error response could be: 
```
{
	"status": number
	"message": string
	"code": string // unique for every different error, for e.x: MISSING_ENVIRONMENT_ID, MISSING_SESSION_ID
}
```

**Describe alternatives you've considered**

**Additional context**
With proper error responses, the clients (SDKs and ppl's own projects) could understand the errors more easily and it would improve the code quality by always returning response in a known structure.

**Comment by kymppi** [comment]
Something that ChatGPT suggested:
```
HTTP/1.1 404 Not Found
Content-Type: application/json

{
  "error": "not_found",
  "message": "The resource you requested could not be found.",
  "details": {
    "resource_type": "user",
    "resource_id": "1234"
  }
}
```

**Comment by mattinannt** [comment]
@kymppi sounds great. what do you think about API responses in general (status code 200). should we change them to a specific format, too?

**Comment by kymppi** [comment]
You should use the correct status code depending on the action (for example 201 Created) and use the same format everywhere. I sent some examples of the format in earlier messages.

**Comment by kymppi** [comment]
The format could be 

success:
```
{
	"code": <code>,
	"data": {
		"some_field": "123"
	}
}
```

error:
something lol, good examples in earlier message

**Comment by kymppi** [comment]
Or probably the success format isn't needed, just return the data as before. But a format for errors is crucial

**Comment by mattinannt** [comment]
I think a structured format for all API calls would be great.

```
type ApiResponse = ApiSuccessResponse | ApiErrorResponse;

interface ApiSuccessResponse {
  code: "success",
  data: any;
}

interface ApiErrorResponse {
  code: "not_found" | "bad_request" | "internal_error" | "not_authorised";
  message: string;
  details: { [key: string]: string }
}
```

It would be even better if we can get to an approach for the Data-Field. But maybe we can also do something like:

```
import {SurveyData} from '@formbricks/types/api`

const response = await fetch(.....);
if (!res.ok) throw Error(...);
const payload = await  res.json();
const survey = payload.data as SurveyData;
...
```

And return the right typed data with the api-wrapper.

**Comment by kymppi** [comment]
If there's a unique code for every error, the API wrapper can easily just check that and return the error with the correct type.

**Comment by kymppi** [comment]
With successful requests they can be typed just fine without any codes or smth like that

**Comment by mattinannt** [comment]
Right, sound good!
And after thinking about it more I think it's important to also change the response in success case to a new format and return the data within a `data` object to avoid conflicts (e.g. the returned object from the database could also include a `code` field and so on the user side this could potentially lead to conflicts while parsing the data (and not checking the http status code)).

**Comment by kymppi** [comment]
@mattinannt Hey! I created a draft PR proposing a solution. Could you please check it and tell me if there's something that should be changed 😄
