### ISSUE TITLE
[FEATURE] Advanced Logic Editor

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2352]
### Is your feature request related to a problem? Please describe.

A user would like to jump questions based on a hidden field value to be set or not.

> User: "For example, if the user chooses the template on the landing page, I need to skip one of the survey's questions about templates. In Typeform we send this parameter to Hidden fields and then I use it in logic.  On my screen I set the condition that if the hidden field "framework" is not equal emptiness then I skip the question. How can I use custom parameters and use them in Logic? "

<img width="646" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/d161e772-7fd1-429b-a38d-55b1609d7c6b">

### Describe the solution you'd like

Rethink the logic editor to support more advanced logic:

<img width="402" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/9ef1f773-2df7-4c3a-a3a3-8436da5f90f0">

**Comment by jobenjada** [comment]
<img width="613" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/1fc737df-62e3-4705-b3e3-68252073a085">

**Comment by mattinannt** [comment]
In development, PR will be opened soon :-)
