### ISSUE TITLE
[BUG] Search Broken in Documentation

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2357]
### Issue Summary

The search functionality is broken, making it difficult to find the relevant information quickly.
![image](https://github.com/formbricks/formbricks/assets/64426524/50f96671-75db-4938-a15f-51d0bfe47245)

### Steps to Reproduce

1. Open https://formbricks.com/docs/introduction/what-is-formbricks
2. Enter search term.
3. You do not get a single result.

### Expected behavior

Search functionality returns results.

### Environment

- [x] Formbricks Cloud (app.formbricks.com)
- [ ] #2358

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich thanks for pointing this out :-) We will work on a fix and will likely also switch back to Algolia since the search results were much better.

**Comment by ShubhamPalriwala** [comment]
Hey, thanks again for the bug report! I went back in the git history to find out that this began when we upgraded our dependencies in formbricks-com! We'll soon come up with a fix 🤞🏼
