### ISSUE TITLE
[FEATURE] Add Zapier app

### ISSUE THREAD

**Issue by jonathimer** [formbricks/formbricks#236]
**Is your feature request related to a problem? Please describe.**
Get Formbricks into other apps (Linear, Slack, etc)

**Describe the solution you'd like**
Zapier app

**Comment by mattinannt** [comment]
Our Formbricks Zapier Integration is now in Review and will be available in the Zapier directory soon 😊
Until it's released in the official Zapier directory, it can be activated using this link: https://zapier.com/developer/public-invite/182792/75979deabe208aeb93cb13461e20ac05/

<img width="766" alt="Screenshot 2023-07-06 at 14 47 51" src="https://github.com/formbricks/formbricks/assets/675065/c90da03b-77c1-4b08-b062-831b84f18d80">

**Comment by jobenjada** [comment]
Its live! :)

https://formbricks.com/docs/integrations/zapier
