### ISSUE TITLE
[BUG] In-App sync request - Error 500

### ISSUE THREAD

**Issue by saenzramiro** [formbricks/formbricks#2365]
### Issue Summary

Since a few days, I started to experience an internal server error when trying to sync the configurations from https://app.formbricks.com. I tested this using the npm package and also the CDN library.

### Steps to Reproduce

1. Initialize a base project.
2. Add the HTML CDN library using the Formbricks Cloud services.

### Expected behavior

To work as expected.

### Other information

The response of the request:

https://app.formbricks.com/api/v1/client/{envId}/in-app/sync/{idHidden}?version=1.6.5
```
{
    "code": "internal_server_error",
    "message": "Unable to handle the request: [\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"date\",\n    \"received\": \"string\",\n    \"path\": [\n      \"segment\",\n      \"createdAt\"\n    ],\n    \"message\": \"Expected date, received string\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"date\",\n    \"received\": \"string\",\n    \"path\": [\n      \"segment\",\n      \"updatedAt\"\n    ],\n    \"message\": \"Expected date, received string\"\n  }\n]",
    "details": {}
}
```

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/2694669/64fb7c16-fcf1-40c5-b5cc-0bafbc47def7)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 10
- Node: v18.16.0
- npm: v9.5.1
```

**Comment by mattinannt** [comment]
@saenzramiro thanks for pointing this out 😊 I just pushed a fix that should solve the issue :-)
