### ISSUE TITLE
[BUG] Responsiveness Results page

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#237]
### Issue Summary

The results summary page specifically (and many other pages generally) are not responsive.

(Write your answer here.)

### Expected behavior

Look good on all screens

#### Screenshots

![grafik](https://user-images.githubusercontent.com/72809645/232102398-ed40e4b1-ed44-449f-bab6-9b131c16989e.png)

#### Environment

- [ X] Formbricks Cloud (app.formbricks.com)
- [ X] self-hosted Formbricks, version/commit: [please provide]

**Comment by Daggerhub** [comment]
We would have to maintain few breakpoints and configure our taildwind config for the same,
Example:- 
sm: 468px
md: 640px
lg: 1024px

This is something which design team can decide and we would have to start from making more used components to be responsive at the starting like **Navbar** which is frequently used in the webapp, then we can move forward towards the standalone pages to be responsive.

Looking forward to hear from the team what else or where I am basically lagging in my approach.

**Comment by jobenjada** [comment]
Hey! We would work with the default breakpoints from Tailwind. I previous projects I have added another breakpoint XS but maybe we should just build everything up to "sm" the same so it fits with all mobile phones.

Generally, responsiveness does not have a high priority right now as the vast majority of people use Formbricks on a large screen. We prefer to ship features faster over going through the loop of making it look good on all screen sizes.

Same is true for dark mode - it has to wait a bit :) 

Thanks for your comment!
