### ISSUE TITLE
[BUG] Search by survey name not working with 'Load More'

### ISSUE THREAD

**Issue by MaxWohlers** [formbricks/formbricks#2377]
### Issue Summary

20 surveys are shown by default in the list view, with more surveys able to be visible by clicking 'Load more'. The problem is that when the surveys are hidden behind 'Load more', you cannot search for the surveys by name in the search field. 

### Steps to Reproduce

1. Have +20 surveys, with more surveys hiding behind 'Load more'
2. Search for a survey in the search field that is not part of the first 20 surveys being shown
3. Survey is not found

### Expected behavior

All surveys, irregardless of being part of the first 20 surveys being shown or not, should be able to be searched by in the search field

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@MaxWohlers thanks for raising the issue :-) We are aware of this and have already opened a PR: https://github.com/formbricks/formbricks/pull/2277
