### ISSUE TITLE
[BUG] Other field on windows Firefox not fillable

### ISSUE THREAD

**Issue by johanvanmol** [formbricks/formbricks#2391]
### Issue Summary

I added an "Other" option to a survey:
![afbeelding](https://github.com/formbricks/formbricks/assets/820474/bdf03dfc-20a5-4402-bdc2-166a55dca5c2)

This can't be filled in the published survey.
I use Windows 11 + Firefox + a 1920x1080 px resolution.

![firefox_hfjysps7Jw](https://github.com/formbricks/formbricks/assets/820474/f63efb65-a845-4946-b990-5799e1395b51)

You can test the survey here:
https://app.formbricks.com/s/clu9o00ju04x6962ilq8w8o4u

### Steps to Reproduce

1. Open the link
2. Try to fill the other field

### Expected behavior

Being able to fill the "other" field

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Windows 11
- Browser: Firefox 124.0.1
- Node:
- npm:
```

**Comment by jobenjada** [comment]
Thanks for letting us know :) @ShubhamPalriwala will have a look at this tomorrow and fix this asap 🚀

**Comment by ShubhamPalriwala** [comment]
Hey @johanvanmol I just tested the bug specifically with your survey 😅 on a Windows 11 + Firefox environment and was able to fill the Other options with spaced text as well! @Dhruwang's fix works nicely 💪🏼! I'm closing this for now, please open it if you still face it or have any other questions!

**Comment by johanvanmol** [comment]
Thank you for fixing this.  I also tested it, and it is working now.
