### ISSUE TITLE
[BUG] Won’t start if npmjs is not reachable

### ISSUE THREAD

**Issue by mark-kubacki** [formbricks/formbricks#2435]
### Issue Summary

Using the container image, Formbricks App won’t start when npmjs is not reachable.

### Steps to Reproduce

1. Follow the tutorial for use with `docker-compose`: https://formbricks.com/docs/self-hosting/docker
2. … but stop short of bringing the pod up.
3. Disconnect from the internet. (For example, because you work offline, in an segmented local network, an ad-hoc network with people in the room, or behind a restrictive corporate firewall.)
4. `docker compose up`

### Expected behavior

The container images should come with everything needed, i.e. no outside dependencies yet to be loaded.

- No container gets restarted.
- The formbricks setup works.

### Screenshots

```bash
docker compose up
```

![image](https://github.com/formbricks/formbricks/assets/191736/84cda110-e001-4713-8d1b-39c13014ff63)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
(self-hosted using Docker)
```

**Comment by mattinannt** [comment]
@mark-kubacki thanks for opening the ticket :-) We already solved this in the current main branch in this will get included in the next release :-) 
I'm not sure if this was already part of the last release; are you on Formbricks 1.6.1?

**Comment by mark-kubacki** [comment]
I’m at whatever is the latest according the docker-compose config I’ve downloaded today. :-)
Unfortunately it pulls `ghcr.io/formbricks/formbricks:latest` and that’s not annotated.

Let me regenerate the container image real quick, assuming that’s how you’d do it:
```bash
git clone --single-branch \
  --recurse-submodules \
  --filter=blob:none --also-filter-submodules \
  "https://github.com/formbricks/formbricks.git" fb-repo
cd $_

docker build \
  -t "ghcr.io/formbricks/formbricks:latest" \
  -f apps/web/Dockerfile \
  .
```

**Comment by mattinannt** [comment]
@mark-kubacki You need an internet connection to build the image. But for starting the container you don't need an internet connection anymore 😊

**Comment by mark-kubacki** [comment]
Please point me to your scripts that build the container image, for my attempts and above command, now that the site is reachable, remain unsuccessful:  
![image](https://github.com/formbricks/formbricks/assets/191736/c592c00f-941d-4ba5-b85c-c0a5759256c3)

Separately I’d propose introducing annotations.  
https://specs.opencontainers.org/image-spec/annotations/?v=v1.0.1

**Comment by mattinannt** [comment]
Solved in latest versions of Formbricks :-)
