### ISSUE TITLE
[BUG] Single-select question returns error when using "includes one of"

### ISSUE THREAD

**Issue by rwrz** [formbricks/formbricks#2439]
### Issue Summary

When using the single-select question and a conditional logic with "includes one of", it returns an ERROR when saving the survey.

### Steps to Reproduce

1. Create a new survey
2. Add a Single-select question
3. Add conditional logic, and choose "includes one of".
4. Choose any of the options or even all of them.
5. Save

### Expected behavior

It should save.

### Other information

It works with several conditional logic using EQUAL instead of "includes one of", so the same behavior can be done, just more verbose.

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/2169309/5e81b5d3-4e2c-430a-939e-fbe60b6534a2)
![image](https://github.com/formbricks/formbricks/assets/2169309/d48298d8-645a-4267-9c31-4b27d3a3dc4d)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: https://github.com/formbricks/formbricks/pkgs/container/formbricks/191047699?tag=v1.6.1
```

**Comment by rwrz** [comment]
Connected to the PR: https://github.com/formbricks/formbricks/pull/2052

**Comment by mattinannt** [comment]
@Dhruwang Can you please check if you are able to reproduce this issue and come up with a solution?

@rwrz thanks for opening the issue. Can you please share the server logs that appear when you try to save the survey? :-)
