### ISSUE TITLE
Allow links to impress/contact and data privacy 

### ISSUE THREAD

**Issue by saschafoerster** [formbricks/formbricks#244]
When using the direct link, the survey needs to show at least the links to a contact page (Impressum) and to the data privacy page (Datenschutzerklärung), as these are requirements by law for all online services of companies.

**Comment by mattinannt** [comment]
@saschafoerster Yes, good point. I updated the Link Survey in https://github.com/formbricks/formbricks/commit/ce0179a2c7b515ce9deaff15f39487afb7467a30 to be able to display a footer with imprint and/or privacy policy.
The cloud now displays both and for self-hosted instances you can set the environment variables `NEXT_PUBLIC_PRIVACY_URL` and `NEXT_PUBLIC_IMPRINT_URL`

**Comment by saschafoerster** [comment]
Thank you so much! That was quick. 🙂
