### ISSUE TITLE
[BUG] Local storage always used even if S3 configuration is set

### ISSUE THREAD

**Issue by GuillaumeDerivery** [formbricks/formbricks#2447]
### Issue Summary

The local storage is always use even if a valid S3 configuration has been set.

Local storage is used even when passing this configuration.
    S3_ACCESS_KEY: 
    S3_SECRET_KEY: 
    S3_REGION: 
    S3_BUCKET: 
    
Local storage is used even when passing this configuration.
   AWS_ACCESS_KEY_ID:
   AWS_SECRET_ACCESS_KEY:
   AWS_REGION:
   S3_BUCKET: 
  
It seems there's a flow in isS3Configured (packages/lib/constants.ts:106)

### Steps to Reproduce

1. Setup all S3 env variables
2. Upload a logo in a survey
3. The logo is not uploaded to S3 but stored locally only.

### Expected behavior

All pictures should be uploaded to S3 when all S3 env vars are set.

### Other information

POST https://formbricks-staging.pety.fr/api/v1/management/storage always returns {signedUrl: "https://formbricks-staging.pety.fr/api/v1/management/storage/local"...} where it should in fact return the S3 presigned URL.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by GuillaumeDerivery** [comment]
FIX : 

The key S3_BUCKET from the documentation is wrong.

<img width="993" alt="image" src="https://github.com/formbricks/formbricks/assets/2812617/862c360d-cb90-49da-939d-e75464057fd1">

It is S3_BUCKET_NAME instead.

**Comment by mattinannt** [comment]
hi @GuillaumeDerivery thanks for pointing that out 😊
@ShubhamPalriwala can you please fix this in our documentation? 😊

**Comment by ShubhamPalriwala** [comment]
Hey, apologies that you had to face the issue and dive deep into it! Have opened a PR immediately to fix the docs! Thanks again for your help ;)

**Comment by htcnokia** [comment]
I use docker minio，but can't upload anything,it return upload failure.
the version:4.9.7

      S3_BUCKET_NAME: formbricks
      S3_ACCESS_KEY: aaminioadmin
      S3_SECRET_KEY: a8aJsbVbLlI4sd6t52AufiR8egqsG9RkBF8wWxSdU78odvqr34=
      S3_REGION: us-east-1
      S3_ENDPOINT_URL: http://formbricks-minio:9000
      S3_FORCE_PATH_STYLE: 1
      S3_USE_SSL: "false"
      S3_PUBLIC_URL_OVERRIDE: https://q.avakkp.com:3990/minio-api

  minio:
    image: minio/minio:latest
    container_name: formbricks-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s    
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: aaminioadmin
      MINIO_ROOT_PASSWORD: a8aJsbVbLlI4sd6t52AufiR8egqsG9RkBF8wWxSdU78odvqr34=
      MINIO_SERVER_URL: https://q.avakkp.com:3990/minio-api
      MINIO_CORS_ALLOW_ORIGIN: "*"
      MINIO_CORS_ALLOW_METHODS: "POST,GET,HEAD,DELETE,PUT"
      MINIO_CORS_ALLOW_HEADERS: "*"
      MINIO_CORS_EXPOSE_HEADERS: "ETag,x-amz-meta-custom-header"
      MINIO_CORS_MAX_AGE_SECONDS: "3000"      
    volumes:
      - minio_data:/data
