### ISSUE TITLE
[BUG] Call-to-Action statistics do not work as expected

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2450]
### Issue Summary

The following test survey contains a single Call-to-Action question:
![image](https://github.com/formbricks/formbricks/assets/64426524/9050c77b-3bc8-4ee3-829f-590f2790e94f)

- the survey was displayed 730 times
- the survey was ignored 501 times
- the survey was dismissed 164 times
- users clicked the button 65 times

Out of this I would expect the following numbers:
- Displays: 730
- Starts: 65
- Completions/Responses: 65
- CTR: 8.9%
- Drop Offs: 665
- maybe display the additional number "Dismissals: 164"

Personally, I find it a bit strange that users who close the survey on the first question are counted as "response". In addition, the time to complete does not work at all in this case. Unfortunately, the CTR doesn't really work for surveys with conditional logic either.
~~I would also like the option to mark the CTA question as required.~~
Additionally, I would like to take this opportunity to suggest switching to the term "Impression" instead of "Displays / Views". This is currently not yet used consistently and the term "Impression" is the most prevalent in the industry.

### Steps to Reproduce

1. run survey with CTA question
2. check response count and CTR

### Expected behavior

Clicks on the button are counted as responses to that question, the CTR is calculated as (clicks) / (number of impressions).

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v1.6.1
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich thanks for the issue :-) 
- We will look into the computation of the CTR. @gupta-piyush19 Can you please take a look? :-) 
- Do you have the Welcome Card activated in your survey? (might be relevant to what counts as response)
- Also the CTA question can be configured to be required. In this case the "Skip" button is not visible. Isn't this working for you?
- The proposed "Impressions" term sounds good, I will discuss this with @jobenjada

**Comment by gupta-piyush19** [comment]
@jonas-hoebenreich  Thanks for the issue.
I checked that we only record responses when there is a response to at least one question (or hidden field). In the above image, there are 229 responses because we consider a skip CTA as a response. Therefore, the starts value is `229`.
I found one issue related to the `time to complete` that was not being recorded and have added a fix for that.
I understand the ambiguity in the number of CTA clicked responses when showing it as `65 responses`.

![image](https://github.com/formbricks/formbricks/assets/56182734/55cd66ab-4ac3-4956-9ae6-5cefafd44290)
We currently show that there are 229 responses, of which 65 contribute to CTR. We can add one more bar to show the skipped response count too.

Also, the starts, drop-off, and CTR should remain the same as:
starts: It is the number of responses for any survey (229 here, because skipping a CTA question is also a response).
dropoff: We count a question as dropoff only when it is unanswered; here, the first question is not answered 501 times, so that is the dropoff.
CTR: we are calculating CTR as [clicked/(clicked + skipped)]*100, then it also makes sense to be 28%. 

Is there anything you think doesn't make sense? I'd be happy to recheck the logic of summary again.

**Comment by jonas-hoebenreich** [comment]
Thank you very much for the explanation, please excuse me, I hadn't quite thought through the logic with required & optional CTA questions.
However, I still think that the CTA should be calculated differently:
baseline: Number of people who have seen the question.
CTR: (clicks) / (number of views)
new KPI (only for optional CTA): Number of skips

Current design for question with required CTA question:
![image](https://github.com/formbricks/formbricks/assets/64426524/cbd636d8-3e67-42da-9eb9-1a2744c118a4)

Suggested design for question with required CTA question:
![image](https://github.com/formbricks/formbricks/assets/64426524/c02cb212-c4ff-4fcf-bb6c-987d08aa101c)


Current design for question with optional CTA question:
![image](https://github.com/formbricks/formbricks/assets/64426524/5c1c1290-7625-474c-ab31-4b627949324a)

Suggested design for question with optional CTA question:
![image](https://github.com/formbricks/formbricks/assets/64426524/474c9eaa-9c43-4e71-9b5c-68873ebfc6c8)

(I haven't bothered to look for suitable icons for the pills)
And I would suggest that you also display the number of impressions for all other question types.

**Comment by gupta-piyush19** [comment]
This makes sense.
Though we already show views in the dropoff table
![image](https://github.com/formbricks/formbricks/assets/56182734/19ac7ba6-55e8-4bd7-bf56-b240f8d59042)
Also, the number of responses represents the impressions, and the separate bars shows the individual selected values.

@jobenjada can you please check how can we incorporate these changes?
cc: @mattinannt

**Comment by jobenjada** [comment]
Hey Jonas!

As always, thanks for thinking along and your suggestions - many of which make a lot of sense :)

1. Impressions vs. Displays / Views:  I know the term "Impression" from ads and that they are handled quite inflationary (e.g. a user having an ad on the screen half a second would count as an impression). What I like is that it takes the visitors perspective similar to "response" whereas "display" is a technical term. I'll think about it for a moment and make sure to use one term consistently going forward.

2. Dismissing a survey shouldn't be a response: I agree, we should group it conceptionally with ignoring a survey and not with responding to it. I'll look for a good place to put this information somewhere on the survey level.

3. Skipping the CTA should remain being considered a response but can be taken out of the CTR calculation

4. Displaying the impressions of the CTA questions in the CTA card also makes sense. It's not very intuitive to go up to the drop off analyzer to find out how many people saw the CTA question.

5. Adding both a `Skip` and `Click` KPI also makes sense to me: The easier the data is available, the better.

6. CTR Calculation as suggested also makes sense ( clicks / displays )

-------------

### Sorting it out

@gupta-piyush19 please do the following

1. Rename "Views" to "Displays" for consistency
2. Change the CTA card as follows:
 - Add KPI "Displays" - refer to the Drop Off Analyzer to see how to calculate it
 - Add KPI "Clicks" - the actual Clicks on the CTA
 - Add KPI "Skips" - if optional, display how many people skipped
3. Calculate CTR as Clicks / Displays

I'll write up another ticket to check if we should update the top KPIs to take `dismissals` out of "Starts" count. I remember thinking it through quite well but have to find my notes again 🤓

### Thanks @jonas-hoebenreich and @gupta-piyush19  🙏
