### ISSUE TITLE
[FEATURE] Add metadata & hidden fields to Airtable integration

### ISSUE THREAD

**Issue by mo6zes** [formbricks/formbricks#2455]
### Is your feature request related to a problem? Please describe.

The CSV export contains all the information: answers to questions + metadata (user agent, time etc..) + hidden fields. These last two are missing in the Airtable integration. This information is very useful so it would be great to have it in Airtable.

### Describe the solution you'd like

The Airtable integration should provide options for including the metadata and hidden fields, it would even be fine to always include it since you can easily hide unused columns in Airtable. That would save us from having to change anything to the UI and the integration config.

### Additional context

I would love to contribute if you see this issue fit for a first contribution to this project.

**Comment by mo6zes** [comment]
Any updates?

**Comment by jobenjada** [comment]
@mo6zes it's shipped now 🚢  - thanks for your patience!
