### ISSUE TITLE
[FEATURE]: wrapper for fetch

### ISSUE THREAD

**Issue by kymppi** [formbricks/formbricks#247]
**Is your feature request related to a problem? Please describe.**
When I was working on error handling on the `@formbricks/js` package. I noticed a lot of code duplication with `fetch()` calls. 

**Describe the solution you'd like**
I think a custom function could automatically parse the returned errors (when #235 is implemented) and simplify making requests to the API in other parts of the code.

The function could be `fetch<T, E>(url: string, <request body>, <any options you can pass to fetch>): Result<T, E | NetworkError>`
Any other common errors such as `InvalidPermissions` could be added to that `E | NetworkError` union type.

**Describe alternatives you've considered**

**Additional context**

**Comment by mattinannt** [comment]
@kymppi We also have users who only use the Formbricks API (e.g. for docs feedback buttons with own frontend).
So maybe it would be great to have a good Typescript API Wrapper for the Formbricks API (mainly client API atm).

So together with our discussions about the headless widget we can maybe split in multiple packages that depend on another:

- `@formbricks/api`: Typescript API-Wrapper for Formbricks (Client) API
- `@formbricks/js-headless`: Headless Logic for SDK/Widget (create events, attributes, identify users,..)
- `@formbricks/js`: Add micro-survey frontend for browsers

what do you think?

**Comment by kymppi** [comment]
Sounds good, when can this be started?

**Comment by kymppi** [comment]
Sounds good, when can this be started? Im thinking that this could be split into 2 parts:
- Create the API wrapper
- Create headless sdk

So everything doesnt need to be added in a single PR

**Comment by mattinannt** [comment]
Sounds good. API Wrapper (at least for client API endpoints) can be started now also because it's a requested feature from a few users. I think we can expect Formbricks 1.0 at the end of May with a more stable API and then we can expand the package with user API endpoints for functionality that currently is only accessible via the frontend.
The headless widget should be pushed back a bit until the question types and workflows within the widget stop changing every few weeks.
@kymppi Do you want to contribute to the API wrapper? 😊

**Comment by mattinannt** [comment]
@kymppi That's cool, I'm assigning this issue to you. I would prefer we get to the API wrapper in small steps. 
The most used API endpoints are `create response` and `update reponse`
https://formbricks.com/docs/api/create-response
https://formbricks.com/docs/api/update-response

I suggest we start with these and get the developer experience right before expanding to more endpoints. I think there are different approaches for that and feel free to come up with an approach / typescript api interface that you consider the best from a developer perspective. The we can test this with different usecases and expand to more endpoints 😊
