### ISSUE TITLE
[FEATURE] Randomise the options in the form

### ISSUE THREAD

**Issue by igniteram** [formbricks/formbricks#248]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to randomise the form options

**Describe the solution you'd like**
Allow users to randomise the options in forms

**Describe alternatives you've considered**
Currently we have to edit the live survey and change the order of options

**Comment by mattinannt** [comment]
@igniteram This feature is already planned and shouldn't be very complex to build. I would propose a dropdown in multiple choice (single & multi) questions with these choices:

- Always keep choices in current order `default`
- Randomize all choices
- Keep last choice in order, randomize others

Also tagging this issue as `help wanted` if somebody wants to contribute 🤗

**Comment by Shubhdeep12** [comment]
Hey @mattinannt 
I would love to contribute to this feature. 
Thanks

**Comment by Shubhdeep12** [comment]
we can add this setting under **Advanced Settings**
