### ISSUE TITLE
[Tweak] Add drag and drop to options on single- and multi-select questions

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2481]
Add drag and drop to options in single- and multi-select question forms:

![Image](https://github.com/formbricks/formbricks/assets/72809645/e6af8bd0-adfd-41c3-9e05-29e48d7308f2)

1. Align the icons on the left side of the input field to be horizontally centered
2. Add this icon on the left hand side of the input field as a handle to drag and drop:
https://lucide.dev/icons/grip-vertical

Use this drag and drop library:
https://drag-and-drop.formkit.com/

It's a bit of a test run, since we also want to use this lib for the ranking type question as well as the overall survey editor 🤓 So please pay close attention if it's stable :)

**Comment by pandeymangg** [comment]
> /assign

hey! sorry for the confusion there, but this is has been already completed and merged, pls chose issues that have the `oss.gg` label 
https://github.com/formbricks/formbricks/issues?q=is:open+is:issue+label:%22%F0%9F%95%B9%EF%B8%8F+oss.gg%22
