### ISSUE TITLE
Add option to copy invite link in team settings

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#249]
When using Formbricks without SMTP server the team functionality doesn't work because the invite link cannot be shared.

Add an option to display and copy the invite link in the members overview.

**Comment by Daggerhub** [comment]
Hey @mattinannt,
I would like to work on this issue,
Please assign it to me

**Comment by jobenjada** [comment]
@Daggerhub any news? ;)

**Comment by ty-kerr** [comment]
Hello, looking to pick this up. Any suggestions for how the invite link should be displayed?

**Comment by mattinannt** [comment]
@ty-kerr Sorry for the late reply. Sure, we would be happy if you could solve this.
Currently invited users are displayed like this:
<img width="832" alt="Screenshot 2023-06-27 at 13 14 49" src="https://github.com/formbricks/formbricks/assets/675065/6dbcf07e-1a75-4b6b-a23d-263267dbcd41">

I think as a first step it would be great to have a share icon between `pending` and the `delete` icon:
<img width="121" alt="Screenshot 2023-06-27 at 13 15 45" src="https://github.com/formbricks/formbricks/assets/675065/93b13568-07c5-46b8-9d86-5560ce058774">
After clicking on the share icon a modal should be shown that displays the link. Similar to the survey share functionality we already have (but without the other buttons at the bottom)
<img width="608" alt="Screenshot 2023-06-27 at 13 15 28" src="https://github.com/formbricks/formbricks/assets/675065/9d324a62-2106-48fb-9449-ea7e07cd4234">
