### ISSUE TITLE
[BUG] Docs: Incorrectly formatted Note in API Key Setup Page

### ISSUE THREAD

**Issue by ShubhamPalriwala** [formbricks/formbricks#2497]
### Issue Summary

On the API Key Setup page of our documentation here: https://formbricks.com/docs/api/management/api-key-setup
After Step 4, the note has incorrectly formatted text as seen below:
![image](https://github.com/formbricks/formbricks/assets/55556994/5065cf20-65f7-43d9-b12e-52b2a5b5ad58)

### Steps to Reproduce

1. Visit https://formbricks.com/docs/api/management/api-key-setup
2. Scroll down to Step 4
3. See the note below it

### Expected behavior

It should rather read as:

### Store your API key safely!
Anyone who has your API key has full control over your account. For security reasons, you cannot view the API key again.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Arch Linux
- Node: v20.1.0
- npm: v9.6.4
```

**Comment by vidhikapadia2799** [comment]
Hi @ShubhamPalriwala, can you please assign this to me. I would like to work on this.

Thanks.

**Comment by ShubhamPalriwala** [comment]
Hey Vidhi, amazed to see your enthusiasm! Since you've already worked on a much bigger feature of the Unsplash Image integration, we'd like this to be taken up by a new contributor as their stepping stone.

This would also motivate them to ship bigger features like you have done and also allow more people a chance to contribute! Thanks again 🚀

**Comment by ShubhamPalriwala** [comment]
yes please! since this is an oss.gg issue, please signup on https://oss.gg and then enroll on the Formbricks repository there! Then come here again and use the / assign command so that you can start working on it💪🏻
