### ISSUE TITLE
Stripe Payment Component

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#25]
Provide form component that allows users to receiving payments via Stripe

**Comment by TatisLois** [comment]
I’ve recommend snoops to a few friends who currently use Typeform, this would be the biggest motivator for them to switch! 

I have capacity to pick this up as a contribution, do we have any direction on implementation or can I open a draft PR and kick things off?

**Comment by matthiasnannt** [comment]
@TatisLois Wow, that's awesome 💪
We haven't sketched out this feature in more detail yet, but for users of the platform it should be possible to connect a stripe account and then they should be able to add a question of type stripe payment and select the stripe account and the amount they want to charge. One tricky part here is that for the open-source self-hosted version it could be enough to just link one global stripe account via env variable / hosting config but for the SaaS version and more complex self-hosted setups we need to be able to let different users of the platform connect their own stripe accounts.
It would be very great if you would like to start developing on that feature. I think it could be more complex to develop so hit me up if it's getting complex or you need additional dev support and we can split the feature into smaller chunks and also let people from our team take care of some parts of the code 😊

**Comment by TatisLois** [comment]
Awesome! Yes let me start with setting things up and working towards a first pass at your acceptance criteria. As things progress i'll keep this issue up to date and we can figure out the best next steps. 🚀

**Comment by mattinannt** [comment]
I am closing this issue due to the ongoing migration to Formbricks with a completely new code base. Based on user feedback our focus shifted from an open source typeform alternative for every kind of survey to a micro-survey solution for digital products. Because the stripe integration doesn't fit the current approach I close this issue for now. Maybe we can reopen it when we open up the platform for more usecases again.
