### ISSUE TITLE
[FEATURE] Allow filtering responses based on the options selected

### ISSUE THREAD

**Issue by igniteram** [formbricks/formbricks#252]
**Is your feature request related to a problem? Please describe.**
Currently we get a list of all user responses to a form but we have to go through each response to see which option they selected.

**Describe the solution you'd like**
Let's allow a summary or a filter based on the option selected we get those responses.

**Describe alternatives you've considered**
No alternative as of now as we cannot even download the data in csv

**Comment by mattinannt** [comment]
@igniteram Yes, there is a lot of room for improvement in the current summary and responses pages and we are planning to build and release an update soon.
Do you need this most in the summary page where you get an overview of all responses an can filter e.g. by one multiple choice answer or do you need this more in the responses overview to see all single responses that choose one specific multiple choice answer?

**Comment by igniteram** [comment]
@mattinannt It would be good in summary page. The total responses could be a link for each option. On click of that link we get all the user responses of that option.

**Comment by mattinannt** [comment]
@AmitDigga Sounds great. I just started sketching out my thoughts on how to build a unified filter that works in both the response page and the summary page, and I quickly realized that it gets more complex if we want to allow fine-grained selection based on response type and filter condition.
We also plan to have different types of filters for audience, response content, and tags in the future.
We will come up with a UI mockup over the next week and then we would be very happy if you would like to take on the problem / parts of the problem depending on how complex it gets ;-)

**Comment by AmitDigga** [comment]
One more thing, while trying to add filter in the Response page, I found that typescript type definitions for the response, props were missing. Did I get the project setup wrong?

**Comment by jobenjada** [comment]
new filters are live :)
