### ISSUE TITLE
[UI] Download button has misleading icon 

### ISSUE THREAD

**Issue by davidjalbers** [formbricks/formbricks#2526]
### Is your feature request related to a problem? Please describe.

_Warning: Pedantic UI feedback ahead :)_

At first glance, the download button on the survey response page looks more like a filter than an action due to its chevron icon:

![CleanShot 2024-04-24 at 22 48 13@2x](https://github.com/formbricks/formbricks/assets/62545933/e48043fc-f548-40a7-bc93-26943721d91d)

This might be misleading and resulted in me missing the feature at first.

### Describe the solution you'd like

I understand that the download options presented after clicking are somewhat related to the filters, and that might be why you have opted to give it a chevron icon. 
But as the downloading itself is an action, it would be better suited with a clearly distinguishable icon IMHO.
The dropdown options seem self-explanatory enough to be understood either way. 

I can see you're using Lucide, and I would suggest `arrow-down-to-line` or `harddrive-download`.

**Comment by rushatgabhane** [comment]
i'd like to work on this

**Comment by mittalsam98** [comment]
Hey I would like to pick this up

**Comment by jobenjada** [comment]
hey @davidjalbers - we've made a few small tweaks to make it easier to catch :)

<img width="753" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/f246c9c7-42de-4080-9571-9ceceb080be7">

This was the first open PR so we're merging it:

https://github.com/formbricks/formbricks/pull/2574

Thanks everyone for your help 🙏 🙏 🙏
