### ISSUE TITLE
[FEATURE] Download option for user responses

### ISSUE THREAD

**Issue by igniteram** [formbricks/formbricks#253]
**Is your feature request related to a problem? Please describe.**
There is no way to download the responses of the user in any format.

**Describe the solution you'd like**
Ability to download the responses of the users.

**Describe alternatives you've considered**
No alternative as of now.

**Comment by mattinannt** [comment]
@igniteram What export format would be the best for your usecases? In what tool do you want to process/analyze the responses further?

**Comment by igniteram** [comment]
@mattinannt We could start with `csv` format first. Not thought of any tool other than simple excel to download and filter out the responses based on columns

**Comment by onel** [comment]
this would be a super good idea. I think CSV is perfect initially

**Comment by jobenjada** [comment]
Lovely, thanks for picking up this issue! :)
