### ISSUE TITLE
[FEATURE] Question Timer

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#2559]
### Is your feature request related to a problem? Please describe.

Discord Request:
"For an MCQ for quick assessment than a survey and I would like for the respondent to finish each MCQ within 90seconds "

### Describe the solution you'd like

Add a timer functionality to each question type which forces the participant to answer the question in the given time interval. Otherwise the question will be skipped.

### Additional context

Status: First time request; waiting for more user feedback on this. Also we need to determine if this feature is also needed for experience management which is the core use case of Formbricks.

**Comment by rushatgabhane** [comment]
Hello! I'd love to work on this
