### ISSUE TITLE
[BUG] Copy invite link doesn't copy

### ISSUE THREAD

**Issue by vanquishkuso** [formbricks/formbricks#2571]
### Issue Summary

After inviting a member, when trying copying the invite URL you get an error in the console:
`Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at onClick`
The result is that nothing gets copied.

### Steps to Reproduce

1. Invite member to your team
2. Click on "Share Invite Link"
3. Click on "Copy URL"

### Expected behavior

The URL gets copied when clicking the button.

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/46133585/dd77d1b1-7593-4dd4-a722-9557652a59a2)
![image](https://github.com/formbricks/formbricks/assets/46133585/5af9499e-c56e-49fe-8e18-1282b1f14372)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Linux - Docker latest image
```

**Comment by mattinannt** [comment]
@vanquishkuso Thanks for raising an issue. On what version of self-hosted Formbricks are you currently?

**Comment by vanquishkuso** [comment]
Another colleague did the setup, but from what I see he wrote "ghcr.io/formbricks/formbricks:latest", so should be 1.6.1? Is there any way to confirm version in the frontend UI?

**Comment by vanquishkuso** [comment]
Today when I tried it worked fine, unsure why. In any case I'll close this.

**Comment by mattinannt** [comment]
I'm happy that the issue resolved itself :-D 😊
