### ISSUE TITLE
[BUG] Lots of answer options break logic jump selector

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2578]
### Issue Summary

<img width="151" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/4bc25958-752a-4619-833e-f3ac4888205b">

Can't select the top options for the logic jump.

### Steps to Reproduce

1. Create a select question with lots of options
2. Add a logic jump

### Expected behavior

Make it scrollable (at least).

Better solution:

1. Add an index to each option (1, 2, 3 and up)
2. Add a grip to resort with drag and drop
3. Add the index in the logic jump
4. Replace the dropdown with a combobox so people can search for answer options

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@gupta-piyush19 Please take a look at the solutions that Johannes suggested and judge for yourself what makes sense with a good ratio of effort to result. I think with not too many changes we can drastically improve the usability.
