### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zarevskaya** [formbricks/formbricks#2590]
### Issue Summary

Hello,
I have a fresh install of Debian 12 server with Docker, full updated.

### Steps to Reproduce

Following the tutorial to install Formbricks with docker:
https://formbricks.com/docs/self-hosting/overview

### Expected behavior

Prisma schema loaded from schema.prisma

Datasource "db": PostgreSQL database "formbricks", schema "public" at "postgres:5432"

Error: P1000: Authentication failed against database server at `postgres`, the provided database credentials for `postgres` are not valid.

Please make sure to provide valid database credentials for the database server at `postgres`.

 ELIFECYCLE  Command failed with exit code 1.

 WARN   Local package.json exists, but node_modules missing, did you mean to install?

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Debian 12
```

**Comment by arpitmishra61** [comment]
Hi @zarevskaya 
Try to copy the content of .env to ` apps\web\.env` and should have valid 
ENCRYPTION_KEY
NEXTAUTH_SECRET
in both .env

We need to copy because on some OS `../../.env` this will not work properly

**Comment by zarevskaya** [comment]
Thanks for the answer but I followed this link:
https://formbricks.com/docs/self-hosting/docker

I don't really understand what you mean.

I need to git clone the repo?

**Comment by arpitmishra61** [comment]
No what I'm saying it might be possible that the .env in apps\web is not properly taking the outer(root) .env file content so you have to manually copy paste the content from .env to apps\web\.env.

But first make sure you have proper .env in root to ensure that
Follow this : https://formbricks.com/docs/developer-docs/contributing#local-machine-setup

![image](https://github.com/formbricks/formbricks/assets/37569669/53f41270-193b-4036-b107-386b70ff29f7)

**Comment by zarevskaya** [comment]
I don't have apps\web  because I use this link:
https://formbricks.com/docs/self-hosting/docker
Not the other link.

**Comment by zarevskaya** [comment]
Nobody?
