### ISSUE TITLE
[BUG] Multiple File Uploads in a row put all the files at the beginning

### ISSUE THREAD

**Issue by starlight-akouri** [formbricks/formbricks#2596]
### Issue Summary

If you create a Form that contains several required "file upload" field types in a row. You are able to upload files, but they all appear listed on the first question. The form does not let you continue due to the fact that the currently selected question is "empty"

### Steps to Reproduce

Create a form with multiple file upload types in a row. Take the survey on iOS mobile safari and try adding a few pictures on each question.

### Expected behavior

I expect that the images uploaded for each step of the form will correspond to the proper step in the form.

### Other information

See ID clvyla89702gechzcad5kd7sx

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: iOS 17.4.1
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@starlight-akouri Thanks for raising an issue. We will investigate the issue, try to reproduce it and then come up with a solution for the issue.

@piyushgarg-dev Can you please take a look at what's going wrong here? 😊
