### ISSUE TITLE
[BUG] Error while checking license

### ISSUE THREAD

**Issue by mo6zes** [formbricks/formbricks#2609]
### Issue Summary

After a certain period of time after boot on my self-hosted instance, I see the error "Error: Error while checking license" popping up. This results in all forms being unusable, see screenshot:

![Scherm­afbeelding 2024-05-13 om 10 22 08](https://github.com/formbricks/formbricks/assets/10004251/c606d00a-de1a-43fb-a44d-e405e2784b33)

### Steps to Reproduce

1. Self-host instance (with enterprise license I think)
2. Wait some hours

### Expected behavior

License should work

### Screenshots

![Scherm­afbeelding 2024-05-13 om 10 32 04](https://github.com/formbricks/formbricks/assets/10004251/c1385a68-a495-4917-9080-2a5bc8091965)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: mac
- Node: chrome
- npm: -
```

**Comment by mattinannt** [comment]
@mo6zes Thanks for creating an issue. We will look into it right now and see what the issue is.
Did you provide a Formbricks license key inside your environment variables? And does your instance have internet access?

**Comment by mo6zes** [comment]
Yes to both. And this problem started occurring after the 2.0 update
