### ISSUE TITLE
[BUG] Self-hosted  issue with db 

### ISSUE THREAD

**Issue by zarevskaya** [formbricks/formbricks#2612]
### Issue Summary

Issue Summary

Hello,
I have a fresh install of Debian 12 server with Docker, full updated.
Steps to Reproduce

Following the tutorial to install Formbricks with docker:
https://formbricks.com/docs/self-hosting/overview

Formbricks Cloud (app.formbricks.com)
Self-hosted Formbricks

### Steps to Reproduce

Try to install Formbricks with this tutorial:
https://formbricks.com/docs/self-hosting/docker

### Expected behavior

Prisma schema loaded from schema.prisma

Datasource "db": PostgreSQL database "formbricks", schema "public" at "postgres:5432"

Error: P1000: Authentication failed against database server at postgres, the provided database credentials for postgres are not valid.

Please make sure to provide valid database credentials for the database server at postgres.

 ELIFECYCLE  Command failed with exit code 1.

 WARN  Local package.json exists, but node_modules missing, did you mean to install?
Other information

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Debian 12 server
```

**Comment by mattinannt** [comment]
@zarevskaya We have opened a PR for this issue:
https://github.com/formbricks/formbricks/pull/2623

We can likely merge this tomorrow after the last questions are solved :-)

**Comment by zarevskaya** [comment]
Cool, I had to modify my tutorial to make it work. :D

https://belginux.com/installer-formbricks-avec-docker/

I originally explained your procedure. Good luck.

**Comment by mattinannt** [comment]
Nice, I'm glad to hear that you solved the issue :-) :-) 💪
