### ISSUE TITLE
[FEATURE] Rework the loading.tsx on PEOPLE page

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2619]
### Is your feature request related to a problem? Please describe.

We've reworked parts of our UI but didn't yet update the loading.tsx in the different files.

This creates a weird visual effect with the loading UI looking different than the actual UI.

### Describe the solution you'd like

**Rework the loading.tsx to match the actual UI of the /people page.**

The most important thing is the card styling: `bg-white rounded-xl shadow-sm border border-slate-200`

Since it's loading, pls add a Tailwind animation: `animate-pulse`

The inside of the card isn't super important.

Note: Please only do the loading.tsx of the ticket you are assigned to.

We want to give several contributors the chance to contribute :)

**Comment by Gunjan-vyas** [comment]
Hi @jobenjada, could you please elaborate more on current vs actual/expected ui of the PEOPLE page with a image?

**Comment by jobenjada** [comment]
@lovishduggal please try again :)

**Comment by jobenjada** [comment]
Please have a look here: https://github.com/formbricks/formbricks/pull/2660

They did a good job :)
