### ISSUE TITLE
[BUG] color change after upgrade

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2625]
### Issue Summary

After upgrading to v2.0.1 the brand color changed for all surveys that have custom styling enabled. Instead of `64748b` the default brand color should be used when enabling custom styles.

### Steps to Reproduce

1. Create survey with e.g. progress bar disabled
2. Upgrade your instance to v2.0.1
3. The button color of the survey changed

### Expected behavior

After upgrading the design of the surveys does not change.
Use the default brand color for custom styles not `64748b`.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v2.0.1
```

**Comment by mattinannt** [comment]
@pandeyman can you please take a look and check if you can reproduce the issue?
