### ISSUE TITLE
[BUG] Truncation and popup not present across the product.

### ISSUE THREAD

**Issue by Shubhdeep12** [formbricks/formbricks#263]
### Some Places in the product need truncation and popups.

While going through the product, I found some places where we need truncation:
1. Case when the product name is long.
2. Case when the user's full name is long.

### Steps to Reproduce
1. Add a long username
2. Add a long product name

### Expected behavior

There should be truncation with a popup.

#### Screenshots

![image](https://user-images.githubusercontent.com/43654389/235421116-191406b0-8f98-43a5-95e6-9920a6e6abc8.png)
![image](https://user-images.githubusercontent.com/43654389/235421231-2acd6736-d40e-434c-9f1d-b1c1adec6b76.png)

#### Environment

- [x] Formbricks Cloud (app.formbricks.com)
- [ ] self-hosted Formbricks, version/commit: [please provide]

#### Node.JS version

[e.g. v18.15.0]

#### Anything else?

- Screen recording, console logs, network requests: You can make a recording with [Loom](https://www.loom.com).
- Anything else that you think could be an issue?

**Comment by Shubhdeep12** [comment]
Would love to fix this issue.
Let me know if this is valid.
Thanks

**Comment by mattinannt** [comment]
@Shubhdeep12 Thanks for pointing that out. Sure, we would be happy to have you as a contributor 🤗 I assigned the issue to you :-) 💪 When do you think you'll get to it?

**Comment by Shubhdeep12** [comment]
Hey @mattinannt, Thanks!
This can be done today.

**Comment by Shubhdeep12** [comment]
Hi @jobenjada @mattinannt i think we can close this issue now.

**Comment by mattinannt** [comment]
thanks for the reminder, closing the issue now 😊
