### ISSUE TITLE
[FEATURE] Setting up with nuxt 3

### ISSUE THREAD

**Issue by laportem** [formbricks/formbricks#2632]
### Is your feature request related to a problem? Please describe.

Not a problem but some information

### Describe the solution you'd like

do you have an example or guide on how to set it up with nuxt 3

### Describe alternatives you've considered

vue-form

**Comment by laportem** [comment]
do you have an example or guide how to set it up with nuxt 3

**Comment by mattinannt** [comment]
@laportem We currently only have examples for Vue.js without Remix:
Docs: https://formbricks.com/docs/app-surveys/framework-guides#vue-js
Examples Repository: https://github.com/formbricks/setup-examples

Maybe this already helps to set it up. If you already figured out how to do it, do you mind sharing your insights so we can also add Nuxt instructions to the docs? :-)
