### ISSUE TITLE
[BUG] regression: no card border for simple card arrangement

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2636]
### Issue Summary

When selecting simple card arrangement the border color disappears.
In this example there should be a pink border:
![image](https://github.com/formbricks/formbricks/assets/64426524/bb17d3de-d0cd-402b-ab5f-3cff954d6a2c)

Also "Card border color" and "Add highlight border" seems like a redundant setting...

### Steps to Reproduce

1. open /product/look
2. select border color
3. Select simple card arrangement
4. border disappears

### Expected behavior

Simple card style has a border

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v2.0.1
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich thanks for reporting the issue :-) 

@pandeymangg Can you please take a look and come up with a fix? :-)

**Comment by jonas-hoebenreich** [comment]
PS: it also seems like "App surveys" do not support Card shadow color

and there is an overlap:
![image](https://github.com/formbricks/formbricks/assets/64426524/b35cd206-59f9-417a-a52c-5a9407ad5ac6)

and this switcher should probably say something like "Link Surveys" vs "App / Website Surveys"
![image](https://github.com/formbricks/formbricks/assets/64426524/8f5d4a09-f312-4b54-998c-a6375a809d82)

**Comment by pandeymangg** [comment]
fixed with #2640 😊
