### ISSUE TITLE
[BUG] User is restricted to only have limited content which can fit in screen

### ISSUE THREAD

**Issue by Shubhdeep12** [formbricks/formbricks#264]
### The survey is not scrollable. Which is restricting users to include more content.

On adding 2-3 lines of title and description and then more than 5-6 options, the survey should get a scrollbar, such that the survey can fit on the screen, but seems like the survey wrapper is not scrollable.

### Steps to Reproduce

1. Add more than 5-6 options 
2. Add 2-3 lines of title and description.

### Expected behavior

There should be a scrollbar when the height of the survey becomes at least 60-70% of screen height.

#### Screenshots

![image](https://user-images.githubusercontent.com/43654389/235423794-81d4a1d3-c3aa-4057-a65a-3a385e0f97a6.png)

#### Environment

- [x] Formbricks Cloud (app.formbricks.com)
- [ ] self-hosted Formbricks, version/commit: [please provide]

#### Node.JS version

[e.g. v18.15.0]

#### Anything else?

- Screen recording, console logs, network requests: You can make a recording with [Loom](https://www.loom.com).
- Anything else that you think could be an issue?

**Comment by Shubhdeep12** [comment]
Would love to fix this.
Let me know if this is a valid issue.
Thanks

**Comment by mattinannt** [comment]
@Shubhdeep12 Sure, we would be happy if you like to fix it 🤗
We currently have two survey components:
- in apps/web/components/preview/ (for Survey Preview & Link Survey)
- in packages/js/components (for the embeddable SDK)
Unfortunately at the moment you need to make changes in both places. Very soon we are going to make a unified package for survey displaying that can be used in both places.

**Comment by jobenjada** [comment]
@Shubhdeep12 are you still working on this?

**Comment by jobenjada** [comment]
solved

**Comment by Shubhdeep12** [comment]
Thanks @jobenjada
