### ISSUE TITLE
[FEATURE] Delete products and submissions

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#265]
**Is your feature request related to a problem? Please describe.**
Playing around with Formbricks I have created test products and submissions. I would like to tidy up now.

**Describe the solution you'd like**
Being able to delete products and submissions.

**Comment by Shubhdeep12** [comment]
I would love to work on this.

**Comment by jobenjada** [comment]
Lovely, feel free to work on it. I'll assign it to you. Can you make an estimate, when you'll be ready to finish it? :)

**Comment by Shubhdeep12** [comment]
Thanks @jobenjada,
Since I am new to Formbricks, just want to confirm that this change is having some design and UX changes like a delete button and UX after deleting the particular project. 
So what will be the next steps?
Should I propose the design and UX flow here?
Or the Formbricks team will decide and provide these changes?

**Comment by jobenjada** [comment]
Hey @Shubhdeep12 

It was easier to just create the UI since we have all components built already:

https://github.com/formbricks/formbricks/tree/feature/delete-product-%26-response

Tasks:

- [ ] Update the Response endpoint to add deleteResponse functionality
- [ ] Add the DeleteModal zu the Settings page after "Delete Product"
- [ ] Add deleteProduct functionality to endpoint
- [ ] Add a check that only users type "admin" can delete products. 
- [ ] Only allow deleteing the product if more than 1 products exist. If not, disable the button and add a tooltip or so to explain why users cannot delete their last product.
- [ ] After deletion forward to the Survey page of a different product this user has access to.
- [ ] Edge cases: Someone got invited to work on a product which then gets delete. This leaves a user with an account without any products. What do you suggest we do here?

Thanks for working on this!

**Comment by Shubhdeep12** [comment]
Thanks for the tasks and branch @jobenjada 
I'll think through it and get back to you with the answer to the last question and an estimate.

**Comment by Shubhdeep12** [comment]
> Hey @Shubhdeep12
> 
> It was easier to just create the UI since we have all components built already:
> 
> https://github.com/formbricks/formbricks/tree/feature/delete-product-%26-response
> 
> Tasks:
> 
> * [ ]  Update the Response endpoint to add deleteResponse functionality
> * [ ]  Add the DeleteModal zu the Settings page after "Delete Product"
> * [ ]  Add deleteProduct functionality to endpoint
> * [ ]  Add a check that only users type "admin" can delete products.
> * [ ]  Only allow deleteing the product if more than 1 products exist. If not, disable the button and add a tooltip or so to explain why users cannot delete their last product.
> * [ ]  After deletion forward to the Survey page of a different product this user has access to.
> * [ ]  Edge cases: Someone got invited to work on a product which then gets delete. This leaves a user with an account without any products. What do you suggest we do here?
> 
> Thanks for working on this!


@jobenjada I think we should also think about this also-

* [ ] What will happen to surveys of a deleted product?

**Comment by jobenjada** [comment]
Hey Shubdeep! Any updates on your end?

**Comment by jobenjada** [comment]
thanks for your work! :)
