### ISSUE TITLE
[BUG] new survey sync returns all surveys

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2671]
### Issue Summary

The new survey sync endpoint `/api/v1/client/<environment>/website/sync?version=2.0.2` returns all surveys (regardless of the survey status).
The issue seems to be the filter/transformation logic: https://github.com/formbricks/formbricks/blob/main/apps/web/app/api/v1/client/%5BenvironmentId%5D/website/sync/route.ts#L100C11-L100C26

### Steps to Reproduce

1. Set survey as completed
2. survey is still displayed in frontend

### Expected behavior

Only show running surveys

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v2.0.2
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich thanks for pointing this out :-) We will ship a fix for this asap :-)
