### ISSUE TITLE
[BUG] empty device meta for Desktop

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2674]
### Issue Summary

Desktop devices are not labelled here: https://github.com/formbricks/formbricks/blob/732b8b599fd632dcced0b65f28e79216f53082a1/apps/web/app/api/v1/client/%5BenvironmentId%5D/responses/route.ts#L85
because UAParser does not label desktop devices: https://github.com/faisalman/ua-parser-js/issues/182

### Steps to Reproduce

1. check device type for response from a Desktop device

### Expected behavior

If `agent?.device.type` is undefined it should default to "desktop"

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v2.0.2
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich thanks for pointing this out :-) We will ship a fix for this :-)

**Comment by mattinannt** [comment]
Ah, I just saw your PR :-) Thanks for solving this; we will take a look asap and release a new patch release for Formbricks :-)
