### ISSUE TITLE
[FEATURE] Add calculation field

### ISSUE THREAD

**Issue by NourEdinDarwish** [formbricks/formbricks#2691]
### Is your feature request related to a problem? Please describe.

I usually use scales in my forms, and I want to show people their scores after submitting forms without the need for complex ways like storing responses in Excel sheets and then making calculations, and finally sending emails to responders with their scores. I want it to be more elegant and simple

### Describe the solution you'd like

Add a calculation field like in some other online forms, where you can assign values to choices, make hidden fields to do calculations, and show the values of the hidden fields on the thanks page. To implement this solution, you generally would like to add some calculation fields with advanced logic and enable dynamic text.

**Comment by begench-g** [comment]
Hello! Please assign this issue to me.

**Comment by mattinannt** [comment]
Update: currently in development :-)

**Comment by jobenjada** [comment]
will be solved here https://github.com/formbricks/formbricks/pull/3020
