### ISSUE TITLE
[BUG] User Info Overlay Bug

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2697]
### Issue Summary

The z-index of the user overlay is too low.

I also want to propose that you could add at least some of the info as icons next to the user name. (eg a flag icon for the country, mobile/desktop icon, icon for OS & browser icon)
![image](https://github.com/formbricks/formbricks/assets/64426524/93d137b0-7941-4730-bb0e-e757064d31aa)

### Steps to Reproduce

1.  Open User overview panel

### Expected behavior

You can see the user overlay.

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/64426524/b97459c9-a06c-4599-9a54-d8a0996c8a3b)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich thanks for raising an issue; we will fix that asap :-)
