### ISSUE TITLE
[BUG] Lower & Upper Label Now Required for Star Question

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2698]
### Issue Summary

You cannot save your survey when you have not set the Lower & Upper Label for the star question type. The error message is also not very useful.
I would recommend to mark required fields with an asterisk (or similar).

### Steps to Reproduce

1. Create star question
2. remove lower / upper label
3. try to save

### Expected behavior

Lower & Upper Label are not required fields

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/64426524/7345c294-4edd-4f6d-8da1-1055e959bb09)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich thanks for opening this issue :-) We are currently in the process of changing the validation logic in the survey editor an keep this in account for this 😊

**Comment by mattinannt** [comment]
Was fixed with the updated survey editor validation :-)
