### ISSUE TITLE
[FEATURE] Config fail with SMTP that doesn't require credentials

### ISSUE THREAD

**Issue by paulceli** [formbricks/formbricks#2713]
### Is your feature request related to a problem? Please describe.

On premise, I tried to configure our stmp server that doesn't requires credentials ( user / password ).
When I test a functionnality that tries to send a mail, it fails with : Could not Email :: SMTP not configured

### Describe the solution you'd like

https://github.com/formbricks/formbricks/blob/main/packages/email/index.tsx
IS_SMTP_CONFIGURED verifies that user and password are set in all cases.

It should be possible to set SMTP without credentials.

### Describe alternatives you've considered

I don't see any

**Comment by mattinannt** [comment]
@paulceli Yes, this makes sense :-)
We can make the user and password and only check if `SMTP_HOST && SMTP_PORT` are set :-)
