### ISSUE TITLE
[BUG] The background container alignment on the signup page.

### ISSUE THREAD

**Issue by khwab-41** [formbricks/formbricks#2715]
### Issue Summary

The background container of cal.com in the signup page, is not padded properly with respect to the profile pic. 

I am not sure if it the UI which is designed that way, or a bug. But this can be fixed by just adjusting the alignment.

![image](https://github.com/formbricks/formbricks/assets/128768866/6c0799b0-94dd-41ae-b520-e7b72209bae4)

### Steps to Reproduce

1. Went to the formbricks.com landing page
2. Clicked on "Get Started" button
3. That is where you can find the issue

### Expected behavior

If it is a bug then we just need to fix some css in this div...

![image](https://github.com/formbricks/formbricks/assets/128768866/53230eef-8d32-49b5-934a-242f1b2a766e)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 10, I7
- Browser: Brave
```

**Comment by Aaryansh1** [comment]
Can you assign it to me?

**Comment by mattinannt** [comment]
@khwab-41 Thanks for pointing this out. I'm also not fully sure if this was the intentional design but I get that it's looking a bit odd.

@Aaryansh1 It would be great if you could make a suggestion on how this could look with proper alignment within the box. Then we can iterate on it to make sure it looks sleek :-)

**Comment by Aaryansh1** [comment]
I think just removing the margin would do the trick
![image](https://github.com/formbricks/formbricks/assets/66205352/99740fbe-98b2-4acf-9aae-655d3bb81828)

**Comment by Aaryansh1** [comment]
@mattinannt I have created a PR for this.

**Comment by Aaryansh1** [comment]
@khwab-41 This issue was resolved and merged please close it. Thanks for reporting it 😄.
