### ISSUE TITLE
[FEATURE] Replace 'Show survey to % of users' slider

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2716]
### Is your feature request related to a problem? Please describe.

Users with millions of views need more granular setting (0.1% or even 0.01%)

### Describe the solution you'd like

Replace this slider with an input field (number) which allows 2 decimals:

<img width="951" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/9bb8ef12-e8be-426e-86a0-6e84d668d219">

**Comment by hussaincoder23** [comment]
@jobenjada i have fixed this issue , see this PR [https://github.com/formbricks/formbricks/pull/2721](url)
