### ISSUE TITLE
[BUG] Build error

### ISSUE THREAD

**Issue by sebiweise** [formbricks/formbricks#2743]
### Issue Summary

```
@formbricks/surveys:build: src/components/wrappers/StackedCardsContainer.tsx (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.

@formbricks/web:build: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Error: No serverless pages were built
```

### Steps to Reproduce

1. pnpm install
2. pnpm turbo build --filter=@formbricks/web...

### Expected behavior

web project build successfully.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Linux
- Node:20
- npm: latest
```

**Comment by mattinannt** [comment]
@sebiweise thanks for pointing that out. We are only seeing this error on Vercel and are currently investigating it :-)

**Comment by mattinannt** [comment]
Solved with https://github.com/formbricks/formbricks/pull/2750 :-)
