### ISSUE TITLE
[FEATURE] Option to Disable Mail

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2767]
### Is your feature request related to a problem? Please describe.

We do not have Mail configured and do not wish to configure it as we do not see the additional value. Currently, our logs are getting spammed with messages like: `Could not Email :: SMTP not configured :: [...]`
This clutter makes it harder to identify other important log messages.

### Describe the solution you'd like

Introduce a new environment variable, DISABLE_MAIL. When this variable is set:

- The notification settings related to email are disabled in the frontend.
- The application does not attempt to send emails.

Benefits:

- Cleaner logs without unnecessary error messages.
- A more user-friendly configuration for teams not using the mail feature.

**Comment by devsargam** [comment]
Hey if this issue is valid can I work on it @jonas-hoebenreich?

**Comment by mattinannt** [comment]
@jonas-hoebenreich makes sense.

@devsargam Thanks for offering your help :-) I will assign you to the issue :-) 
We already have a `IS_SMTP_CONFIGURED` variable in `packages/email/index.tsx` that could be used for these checks. We just need to make sure in the `sendEmail` function that we don't print the error. It should be an easy fix :-)

**Comment by devsargam** [comment]
Hey @mattinannt, what is the ideal thing to do?
<img width="1092" alt="image" src="https://github.com/formbricks/formbricks/assets/76874341/ff1cb0b5-c75b-4c22-922f-07ea6601d42c">
Should I remove the else part? or is there some other desired result?

**Comment by jonas-hoebenreich** [comment]
I personally would just remove the else clause. And it would be great to have a notice in the notification settings:
![image](https://github.com/formbricks/formbricks/assets/64426524/76e079ad-b6e5-48de-920e-e6508a80bf5e)

**Comment by devsargam** [comment]
Thanks @jonas-hoebenreich this helps raising a pr with the fix you wanted :)

**Comment by mattinannt** [comment]
@devsargam How is the development going. When do you think you will be able to open a PR for it? :-)

**Comment by devsargam** [comment]
Hey @mattinannt was waiting for your input? Is the approach discussed correct?

**Comment by mattinannt** [comment]
@devsargam Yes, just deleting the else case should be the way to go :-) Thanks for raising a PR 💪🚀
