### ISSUE TITLE
[BUG] Background Tiles not resizing properly

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2784]
### Issue Summary

When going back and forth between tiles, the background tiles sometimes do not resize properly.
(I changed the background to green in this video to increase the contrast)
[scrnli_6_19_2024_4-43-35 PM.webm](https://github.com/formbricks/formbricks/assets/64426524/a57dbae9-4147-4362-a013-8c516cd37972)

### Steps to Reproduce

I was able to reproduce the issue with this setup, I guess it also affects other flows:
1. Create a survey with logic jump and star rating question just like in the video
2. Select 5 stars -> tiles resize properly
3. Go back and select 3 stars (jump to different question) -> tile resizes properly
4. Go back and select 5 stars again -> tiles do not resize properly

### Expected behavior

Background tiles resize properly.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
latest
```

**Comment by Aaryansh1** [comment]
I will be exploring this issue give me a day or so.

**Comment by Aaryansh1** [comment]
I was able to replicate this issue. 
I am currently trying to find a solution.

**Comment by mattinannt** [comment]
@Aaryansh1 awesome! thank you :-) I assigned the issue to you.

**Comment by ShubhamGagare** [comment]
Hi both, I tried a few things and I think i got the solution. But to so had to make changes in indexes. I have tested from my end it works for both logic jumps and normal sequential journey
I added the logic jump cards behind star rating card which avoids the any undefined ref to cardRef

https://github.com/formbricks/formbricks/assets/18760062/d0f5b09d-bf80-4e1e-b53c-3f09b44c6c51

**Comment by gupta-piyush19** [comment]
Thanks, @itsjustaplant for the fix
