### ISSUE TITLE
[BUG]  Unable to Log In: "Email Already Exists" Error

### ISSUE THREAD

**Issue by smritidoneria** [formbricks/formbricks#2803]
### Issue Summary

Unable to log in due to "email already exists" error

### Steps to Reproduce

1.Went to [https://formbricks.com](https://formbricks.com) and get started
2.Log in using google
3.After login encountered an error "An error occurred when logging you in
A user with this email exists already."

### Expected behavior

It should redirect to the dashboard page.

### Screenshots

<img width="1333" alt="Screenshot 2024-06-24 at 1 31 38 PM" src="https://github.com/formbricks/formbricks/assets/109029101/b31ae765-ac41-43bc-8504-57b15a870195">

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:MacOS
- Browser:Safari
-
```

**Comment by mattinannt** [comment]
@smritidoneria Is it possible that you already have another Formbricks account with email credentials or Github SSO?
If the problem continues please reach out to `hola@formbricks.com` and we can check if we already have records of the email address in our database and how we can get you logged in 😊

**Comment by smritidoneria** [comment]
@mattinannt  While I have successfully logged in using GitHub SSO, there is an opportunity to enhance the user experience by providing more informative error messages. For instance, instead of displaying a generic error like "An error occurred when logging you in. A user with this email exists already," the interface could dynamically adjust based on the user's authentication history.

For example, if a user signed up via GitHub and then attempts to sign in through Google, the system could display a message suggesting they sign in using their original authentication method (GitHub in this case). This approach not only clarifies the issue at hand but also guides users towards the appropriate login method, thereby improving clarity and user satisfaction.

**Comment by mattinannt** [comment]
Solved with https://github.com/formbricks/formbricks/pull/3355
