### ISSUE TITLE
[BUG] XSS vulnerability via profile picture

### ISSUE THREAD

**Issue by domibarton** [formbricks/formbricks#2804]
### Issue Summary

Uploading an SVG as profile picture, with XSS payload inside, will allow the execution of vulnerable code.

### Steps to Reproduce

1. Create a new SVG with the payload below
2. Upload the SVG as profile picture

SVG payload:

```xml
<svg width="600" height="400" xmlns="http://www.w3.org/2000/svg" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<foreignObject width="100%" height="100%">
<body xmlns="http://www.w3.org/1999/xhtml">
<iframe src='javascript:confirm(document.domain)'></iframe>
<iframe src='javascript:confirm(document.domain)'></iframe>
</body>
</foreignObject>
</svg>
```

### Expected behavior

XSS code shouldn't be executed, as it can lead to account take over and alike.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: macOS
- Browser: Firefox
```

**Comment by mattinannt** [comment]
@domibarton Thanks for pointing that out :-) 
What would you propose as a solution? We could just exclude `.svg` as a valid extension for image uploads.

**Comment by domibarton** [comment]
Different options:

1. Exclude `.svg` from upload (backend & frontend o.c.) – enforce it or let the admin decide via config flag?
2. Add an svg sanitizer to remove dangerous code (during presentation and upload as well)
3. Inform the user during the upload about the threat

From a security PoV:

1. Might be the most secure thing to do, but svg support will be dropped :) 
2. Might still be secure, but there might be things missing in the sanitizer, which results to vulnerabilities again
3. Not very secure, since humans sometimes are bad at reading warnings, resp. non-techies won't understand the risk

Here are 2 good sources for SVG vulnerabilities, resp. how to use SVG to do SSRF, XSS, etc:

- https://github.com/allanlw/svg-cheatsheet
- https://www.fortinet.com/blog/threat-research/scalable-vector-graphics-attack-surface-anatomy

**Comment by gupta-piyush19** [comment]
Thanks, @domibarton, @mattinannt, for the ticket and its fix.
We've restricted the uploading of SVG for now. 😊

**Comment by STAR-173** [comment]
Hey @mattinannt @gupta-piyush19,
I see that a PR has been mentioned and merged regarding this issue but the issue is not closed. Are you guys thinking of implementing a svg sanitizer later on ?

**Comment by gupta-piyush19** [comment]
Hi, @STAR-173 , We've merged the fix for this. Forgot to close the issue (generally we do close the issue in the end of the internal sprint), closing it now. 
Thanks 😊
