### ISSUE TITLE
[BUG] <iframe> not loading when embedded to HMTL

### ISSUE THREAD

**Issue by bigbeka** [formbricks/formbricks#2826]
### Issue Summary

- Self-hosted Formbricks with `docker compose`
- Website survey and link surveys work perfectly.
- `<iframe>` embed on the same WordPress website is not loading the form, web console spits out this error: 
`Failed to load resource: the server responded with a status of 404 (): https://form.fqdn.io/api/packages/website.umd.cjs.map` - - This URL returns: `{"code":"not_found","message":"package not found","details":{"resource_id":"website.umd.cjs.map","resource_type":"package"}}`
- If the same `iframe` is embedded WITHOUT `<div>` container, then the form loads as expected.

Tested this across different instances of web servers.

### Steps to Reproduce

1. Self-host Formbricks with docker compose
2. Assign FQDN in front of the NGINX as Reverse Proxy
3. Connect Formbricks to a site with HTML embed in <head> (header.php)
4. Create a link survey and embed it with <iframe> to the connected site.

### Expected behavior

The form should load without `Failed to load resource: the server responded with a status of 404 (): https://form.fqdn.io/api/packages/website.umd.cjs.map` error.

### Other information

- Running on: Proxmox > Ubuntu 22.04 LXC
- Formbricks version: 2.3.0

### Screenshots

- OS: Proxmox > Ubuntu 22.04 LXC

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: MacOS
- Browsers tested: Chrome, Safari
- Version: Up-to-date (as of today)
```

**Comment by bigbeka** [comment]
UPDATE:

The issue seems to be in the embed <iframe> that is offered on the share window of formbricks UI:

```
<div style="position: relative; height:100%; max-height:100vh; overflow:auto;"> 
  <iframe 
    src="https://form.fqdn.io/s/abcd?embed=true" 
    frameborder="0" style="position: absolute; left:0; top:0; width:100%; height:100%; border:0;">
  </iframe>
</div>
```

Anyone able to help with this?

**Comment by jobenjada** [comment]
Hey! Can you try removing the `?embed=true` at the end of the URL?

This is new and might break it.

@pandeymangg other ideas?

**Comment by bigbeka** [comment]
This work when height and width set with `px`:
```
<div style="position: relative; width: 400px; height: 500px; overflow: hidden;">
  <iframe 
    src="https://form.nomadist.io/s/clxxit7sd000ibfm4ryhyuo8b?embed=true" 
    frameborder="0" 
    style="width: 100%; height: 100%; border: none;">
  </iframe>
</div>
```

I want to correct myself, the following error does not stop `<iframe>` from loading. `Failed to load resource: the server responded with a status of 404 (): https://form.fqdn.io/api/packages/website.umd.cjs.map`

`<iframe>` loads with or without the above error but the `<div>` height that is set by default on Formbricks UI is not rendering correctly.

When default `<iframe>` is embedded and page is rendered, one can change the height manually in the Web Inspect to see the form and interact with it.

![Screenshot 2024-06-28 at 09 50 23](https://github.com/formbricks/formbricks/assets/53529055/88afb33b-5418-4899-9111-be83eb955a63)


@jobenjada can you suggest a change to the <div> that will rended correctly?

**Comment by jonas-hoebenreich** [comment]
jfyi: website.umd.cjs.**map** is not actually required. This resource is only needed to decompile the `website.umd.cjs` module. So the console warning is just annoying. You can also resolve it by removing the comment `//# sourceMappingURL=website.umd.cjs.map` from the source.

**Comment by bigbeka** [comment]
@jonas-hoebenreich thank you, that makes sense.

Any suggestion on how to resolve the `max-height: 100vh` not rendering correctly? As mentioned, `max-height: 100vh` relies on the parent div's height, most sites don't have that set.

I confirm that formbricks.com embed has the same issue.

**Comment by Dhruwang** [comment]
Hey @bigbeka 😊 , do you have a parent div (with fix height and width) surrounding the iframe code ?

**Comment by bigbeka** [comment]
@Dhruwang Yes, I copied and pasted the code provided from Formbricks UI without changes/including suggested <div> (see below). 
But it is not working, as the div provided from Formbricks UI has `max-height:100vh;` and it expects to get height size from even higher level parent's div height. In my case, page heights can be as small as 0px if there is no content in it.

Solution that needs to be implemented is: Formbricks should set the height of its div instead of relying on the parent div's of the host page.

Original code from Formbricks embed window:
```
<div style="position: relative; height:100%; max-height:100vh; overflow:auto;"> 
  <iframe 
    src="https://FQDN.io/s/clxxit7sd000ibfm4ryhyuo8b?embed=true" 
    frameborder="0" style="position: absolute; left:0; top:0; width:100%; height:100%; border:0;">
  </iframe>
</div>
```

This is how it looks when embedded:
<img width="2599" alt="Screenshot 2024-07-01 at 14 06 55" src="https://github.com/formbricks/formbricks/assets/53529055/e0e3f169-f6ef-4ec8-a2b5-6dba8d29bee5">

**Comment by Dhruwang** [comment]
Hey @bigbeka , we recently made changes to the embed functionality, can you please try it again once ?😊
Here is more information about the embed mode https://formbricks.com/docs/link-surveys/embed-surveys#emebd-mode

**Comment by Dhruwang** [comment]
Hey @bigbeka , you can adjust the height by changing the value of height property here 😊


![Image](https://github.com/user-attachments/assets/b7e99ebd-ea10-4df6-83c8-ebfc9ac963ea)

**Comment by Dhruwang** [comment]
Hey @bigbeka , did it worked for you ? 😊

**Comment by bigbeka** [comment]
Hi @Dhruwang, yes, this seems to have solved the issue of the form not showing at all. But I would not say the solution is ideal. Currently the height of the DIV takes more space than needed for the form. Can div be expanded to the max hight of its content/child div?

**Comment by pandeymangg** [comment]
Hi @bigbeka you can set the height to a custom value, for example, 100% to make it respect the parent container's height:
```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div style="height: 400px; border: 2px red solid">
      <div style="position: relative; height: 100%; overflow: auto">
        <iframe
          src="http://localhost:3000/s/clzjpubhp000cxjnxkna2xdar"
          frameborder="0"
          style="position: absolute; left: 0; top: 0; width: 100%; height: 100%; border: 0">
        </iframe>
      </div>
    </div>
  </body>
</html>
```
do you not have any height on the parent div containers?

**Comment by bigbeka** [comment]
@pandeymangg, No, usually in empty pages, you do not set parent DIV height, as the content inside the DIV decides how big the page should be.

When I set the height to 100%, the form container takes up bigger space then it need, please see below:
I have 100% view set in the browser and I am using MacBook Pro M3 14" native screen.

<img width="1800" alt="Screenshot 2024-08-09 at 16 55 34" src="https://github.com/user-attachments/assets/0ff01e27-a139-4a38-aa15-a9ec98b2465c">

**Comment by jobenjada** [comment]
@bigbeka we won't be able to find a solution which works for everyone out of the box. Our solution has to be a compromise to work for everyone a little but (and for noone perfectly right).

It's very easy to just adapt the height of the parent container to the max height of your specific survey.

Just change what currenlt is set to `height: 100vh` to e.g. 400px or 500px, go through your survey and see if it fits. If it does, you're good to go ;)
