### ISSUE TITLE
[BUG][🕹️] UI Bug on Firefox

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2828]
### Issue Summary

![image](https://github.com/formbricks/formbricks/assets/72809645/fbe9c6d8-8dad-46b2-915a-1baa72a5b8a9)

In the survey editor in the mobile preview we see the corners of the survey lay over the border of the phone mockup

### Steps to Reproduce

Use Firefox
Create a survey
Switch to mobile preview

### Expected behavior

The survey corners should be hidden inside the phone mockup

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by itsjustaplant** [comment]
Hi @jobenjada , i know the issue and have a fix for it, but it makes me wonder how that is working on Chrome.
