### ISSUE TITLE
[BUG] Growing __Secure-next-auth.session-token cookie

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2838]
### Issue Summary

It seems like you are storing way too much information in the session token.
For me the size is now 9.4kB (chunked into 3 separate cookies) causing issues with WAF.

### Steps to Reproduce

1. use Formbricks as a power user
2. session-token grows over time

### Expected behavior

Only store necessary data in the session cookie and keep it to a bare minimum.
I'm not 100% sure if the notificationSettings are the issue but they should definitely not be encoded in the session token.

https://github.com/formbricks/formbricks/blob/c32a358f43b80a41db49e9ffc1ef2f1a26bff49c/packages/types/user.ts#L39

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
v2.3.0
```

**Comment by jonas-hoebenreich** [comment]
@mattinannt any comments on that?

**Comment by mattinannt** [comment]
@jonas-hoebenreich thanks for raising the issue. We will investigate what happens here and why it grows so much in size.

@pandeymangg Can you please check what part in next-auth is responsible for what is stored in the session cookie and make a suggestion how we can reduce the number of information 😊💪

**Comment by jonas-hoebenreich** [comment]
Hi @pandeymangg, any update on this?

**Comment by pandeymangg** [comment]
hi @jonas-hoebenreich apologies for the delays, we'll be picking this up very soon 😊
