### ISSUE TITLE
[BUG] - Cards borders are set to default custom styles after visiting Styling Tab

### ISSUE THREAD

**Issue by itsjustaplant** [formbricks/formbricks#2842]
### Issue Summary

After visiting __Styling__ Tab border of the cards in the preview modal are set to custom styling border color even though __Add Custom Styles__ toggle is not on.

### Steps to Reproduce

1. Go create a survey
2. Observe the border of cards in preview, border-color: rgb(229, 231, 235)
3. Click __Styling__ Tab
4. Observer the cards border, border-color:  rgb(248, 250, 252)

### Expected behavior

Cards should keep the borders if no styling is applied.

### Screenshots

[loom](https://www.loom.com/share/eccc86c8f06747969031ca20b0679e66)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: Chrome & Firefox
- Node:
- npm:
```

**Comment by itsjustaplant** [comment]
Hey all, i also would like to work on this issue 😎 . thx

**Comment by mattinannt** [comment]
@itsjustaplant thanks for raising an issue for this :-)
Great to hear that you would like to work on the issue :-) 💪 I'm going to assign it to you.

**Comment by ShubhamGagare** [comment]
cards in preview, border-color: rgb(229, 231, 235) ----> #e5e7eb
 cards border, border-color: rgb(248, 250, 252) ------> #f8fafc (Comes from default colors for styling as its not getting any border colors from questions tab )

 Simple solution will be setting up same default border color for question and styling tabs. Any reason why both were set tobe different??
 Is it need to handled on Add custom styles toggle??

On setting up same default border color for styling tab same as questions tab

https://github.com/formbricks/formbricks/assets/18760062/fb52a559-d969-4adc-bd52-3ef720c9657f

**Comment by iamitpal** [comment]
Hey, @mattinannt please let me know the Expected behavior for this issue I'd like to resolve this issue.
