### ISSUE TITLE
[FEATURE] Enhance List View for better UX 2.0

### ISSUE THREAD

**Issue by MaxWohlers** [formbricks/formbricks#2844]
### Is your feature request related to a problem? Please describe.

For monitoring multiple surveys at the same time, I am missing key infos in the list view, like number of responses or created by (person) info. both these infos would help in knowing how much traffic a survey gets and who to contact if I have questions about a survey 

### Describe the solution you'd like

add 
- number of responses
- created by person 

<img width="796" alt="Bildschirmfoto 2024-07-03 um 15 04 38" src="https://github.com/formbricks/formbricks/assets/37698250/607cb30d-87b0-4172-9889-aa8c47e485aa">

**Comment by smritidoneria** [comment]
Hey @mattinannt , I want like to work upon this feature

**Comment by smritidoneria** [comment]
hey @mattinannt ,kindly review the pr #2864

**Comment by mattinannt** [comment]
This has been solved with https://github.com/formbricks/formbricks/pull/3318
