### ISSUE TITLE
[BUG] Close survey on date not working

### ISSUE THREAD

**Issue by edersilva78** [formbricks/formbricks#2848]
### Issue Summary

Hi, team.

"Close survey on date" option was set, but the survey did not close.

### Steps to Reproduce

`Survey Settings -> Response Options -> Close survey on date` was set to close on the 28th of june. Today it was still open.
![image](https://github.com/formbricks/formbricks/assets/7780778/e06a89c8-c845-465a-8c1c-968e97729a44)

Had to disable the option to close manualy.
![image](https://github.com/formbricks/formbricks/assets/7780778/f510b04f-e445-483b-a7b7-c1c1f0a52065)

### Expected behavior

Expected the survey to be closed automatically on the 28th.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- Docker 
- Formbricks version: 2.1.0
```

**Comment by mattinannt** [comment]
@edersilva78 Thanks for reporting :-) We are going to try to reproduce the issue and then identify and fix the problem behind this :-)

**Comment by pandeymangg** [comment]
Hi @edersilva78 
I checked by reproducing the issue when I had missing `WEBAPP_URL` environment variable, could you please check that you have the environment variables `WEBAPP_URL` and `CRON_SECRET` set correctly in your docker-compose? The cronjob for the survey status depends on these variables 😊

**Comment by edersilva78** [comment]
> Hi @edersilva78 I checked by reproducing the issue when I had missing `WEBAPP_URL` environment variable, could you please check that you have the environment variables `WEBAPP_URL` and `CRON_SECRET` set correctly in your docker-compose? The cronjob for the survey status depends on these variables 😊

Hi `webapp_url` is set. `cron_secret` is empty. I generated it and restarted the stack. 

That makes sense, thank you @pandeymangg

I created a survey and set it to stop accepting answers tomorrow. I'll let you know.

**Comment by pandeymangg** [comment]
Hi @edersilva78 did it work 🤓

**Comment by edersilva78** [comment]
Yes. Thanks!
