### ISSUE TITLE
[BUG] Local Guide link in Readme file seems broken.

### ISSUE THREAD

**Issue by mrinmay7875** [formbricks/formbricks#2855]
### Issue Summary

In the Readme file under Development --> Local Setup if we click on the Link then it navigates us to the formbricks docs but the docs gives 404 error.

Click on this link:
<img width="477" alt="image" src="https://github.com/formbricks/formbricks/assets/33797909/f312e690-d183-4acc-8a92-b1d780030631">

And it navigates to Formbricks page but gives 404 error.
https://formbricks.com/docs/developer-docs/contributing
<img width="497" alt="image" src="https://github.com/formbricks/formbricks/assets/33797909/540aa0c3-ffe8-4e41-943f-e86d8e9f3ada">

### Steps to Reproduce

Refer to Issues summary section.

### Expected behavior

So when we navigate to this link then we should actually see some content there. But getting 404 as of now.
https://formbricks.com/docs/developer-docs/contributing

### Environment

- [x] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: MacOS Sonoma
- Node: 20
- npm: 10.2
```

**Comment by Swapnil-2502** [comment]
I think this should be the right url: https://formbricks.com/docs/developer-docs/contributing/get-started#local-machine-setup
I may be wrong but after reading there docs it feels like this is correct to me, would like to make changes by creating a PR only after any official maintainer of this repo gives approval.

**Comment by arindam1997007** [comment]
hi @mattinannt @gupta-piyush19 

The issue also exists for **our contribution guide** link. That link is also broken.
Correct url is [https://formbricks.com/docs/developer-docs/contributing/get-started](https://formbricks.com/docs/developer-docs/contributing/get-started)

![image](https://github.com/formbricks/formbricks/assets/23236141/b478166f-a39f-4f81-8b7e-c3ae216f4bb1)
