### ISSUE TITLE
[BUG] Docker Image --> SMTP Mail Config to send Unauthorized //  Error: unable to verify the first certificate 

### ISSUE THREAD

**Issue by rooks88** [formbricks/formbricks#2858]
### Issue Summary

Hi everyone, 

I use several docker images on this particular Docker host. I'm successfully using SMTP to an internal Exchange server as well from different images on this server. Due to the hoster's config I have to send these Mails without auth on port 25. 
In Formbricks I always receive the following error: 

Error: unable to verify the first certificate 

As I found out this error message is thrown due to a missing TLS config: 

 tls: {
            // do not fail on invalid certs
            rejectUnauthorized: false
        },

I cannot find an .env variable in docker-compose.yml to configure rejectUnauthorized. Is there any way for me to fix it, or do I have to fork formbricks, change the index.tsx in packages/email/ and docker-compose the new image?

The rest is working correct, except from the upload of background images (which I do not need). 

Thanks in advance! Cheers

Robin 

### Steps to Reproduce

I used docker-compose.yml to build the container. 
Email config: 
    # Email Configuration
    MAIL_FROM: "xxx@xxx"
    SMTP_HOST: "xxx-xxx.xxx.org"
    SMTP_PORT: 25
    #SMTP_USER: "xxx"
    #SMTP_PASSWORD: "xxx"

    # (Additional option for TLS (port 465) only)
    SMTP_SECURE_ENABLED: 0

On other containers the smtp config is working (SSL false, TLS false, host and port are the same, no auth) 

### Expected behavior

Send email instead of error msg

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: SLES 12 SP5 as Docker Host, container itself from docker image
- Node: from docker image
- npm: from docker image
```

**Comment by mattinannt** [comment]
@rooks88 Hi, thanks for raising an issue :-) I already created a ticket for the team for this and this should be released with the next minor version next week :-)

**Comment by paulceli** [comment]
Hello,
fyi, I'm experiencing similar same error when trying to upload a background image or logo (browser err "Failed to load resource: the server responded with a status of 500").
We are on premise and upgraded to latest 2.3.0. We are using a traefik as reverse proxy with a valide certificate..

thanks

error on backend side :

```
formbricks-1  |  ⨯ TypeError: fetch failed
formbricks-1  |     at node:internal/deps/undici/undici:12502:13
formbricks-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
formbricks-1  |     at async fetchExternalImage (/home/nextjs/apps/web/node_modules/next/dist/server/image-optimizer.js:522:17)
formbricks-1  |     at async NextNodeServer.imageOptimizer (/home/nextjs/apps/web/node_modules/next/dist/server/next-server.js:648:48)
formbricks-1  |     at async cacheEntry.imageResponseCache.get.incrementalCache (/home/nextjs/apps/web/node_modules/next/dist/server/next-server.js:183:65)
formbricks-1  |     at async /home/nextjs/apps/web/node_modules/next/dist/server/response-cache/index.js:90:36
formbricks-1  |     at async /home/nextjs/apps/web/node_modules/next/dist/lib/batcher.js:45:32 {
formbricks-1  |   [cause]: Error: unable to verify the first certificate
formbricks-1  |       at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
formbricks-1  |       at TLSSocket.emit (node:events:519:28)
formbricks-1  |       at TLSSocket._finishInit (node:_tls_wrap:1085:8)
formbricks-1  |       at ssl.onhandshakedone (node:_tls_wrap:871:12)
formbricks-1  |       at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
formbricks-1  |     code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
formbricks-1  |   }
formbricks-1  | }

```

**Comment by paulceli** [comment]
Hey,
Upgraded to the latest minor version released.
Still having the problem mentionned above.

Was it supposed to be fixed in release 2.3.2 ?

thanks

**Comment by stocky789** [comment]
I have a similar issue with the One Click install. When you enable SMTP in the install script you just get a 500 internal error on the web gui then 

But if you do the same setup without enabling SMTP it works fine.

**Comment by mattinannt** [comment]
We introduced a new environment variable `SMTP_REJECT_UNAUTHORIZED_TLS`. When  set to 0 (`SMTP_REJECT_UNAUTHORIZED_TLS=0`), nodemailer will not throw an error on an invalid certificate :-) This should solve the error :-)
