### ISSUE TITLE
Add an option for transparent background to the survey editor

### ISSUE THREAD

**Issue by RashaMou** [formbricks/formbricks#2870]
### Is your feature request related to a problem? Please describe.

When embedding a survey into my website, I'd like the option of not having a background so I can use my own styling.

### Describe the solution you'd like

A `transparent` option added to the `SURVEY_BG_COLORS` array in `constants.ts`.

I am happy to open a PR for this if this solution is acceptable.

**Comment by Nikhil-shukla1** [comment]
so it would be like i just need to modify the survey_bg_colors or add the transparent direct in the object. please clarify this.

**Comment by AnanteshG** [comment]
Hi, I’d like to work on this issue.

**Comment by mattinannt** [comment]
We added an "Embed mode" a few months back that has a transparent background by default to make embedding Formbricks as an iFrame easier :-)
