### ISSUE TITLE
[BUG] ❌ Invalid environment variables: { CRON_SECRET: [ 'Required' ] }

### ISSUE THREAD

**Issue by JamesGrant88** [formbricks/formbricks#2874]
### Issue Summary

Not sure what's happened. Hadn't changed anything on my build. Only difference is one person had filled out the form today. Now the container won't start. Only thing I can assume is maybe an auto update has broke it?
[_Formbricks_logs.txt](https://github.com/user-attachments/files/16169650/_Formbricks_logs.txt)

### Steps to Reproduce

Keep trying to restart container but keeps producing same errors in thet log attached.

### Expected behavior

For container to start.

### Screenshots

![Screenshot 2024-07-10 at 23 56 54](https://github.com/formbricks/formbricks/assets/129697578/a1c9b3fa-ffba-404d-a288-dfb921624ce3)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Synology DSM 7.2
- Docker container
- Deployed using portainer stack
```

**Comment by JamesGrant88** [comment]
Also another log file attached, this looks to be from the start 
[_Formbricks_logs-2.txt](https://github.com/user-attachments/files/16169769/_Formbricks_logs-2.txt)

**Comment by smritidoneria** [comment]
hey @JamesGrant88 , formbricks recently merged a new change  in which CRON_SECRET is required, you can check this in the docs and can fix this by generating a new secret key and just replace it in you env file.
4th point in this:
https://formbricks.com/docs/developer-docs/contributing/get-started#local-machine-setup

**Comment by mattinannt** [comment]
Thanks @smritidoneria for helping out 🚀

**Comment by JamesGrant88** [comment]
Thank you so much! Now fixed.
