### ISSUE TITLE
[BUG] Inappropiate functionality of preview under configuration

### ISSUE THREAD

**Issue by smritidoneria** [formbricks/formbricks#2882]
### Issue Summary

https://github.com/user-attachments/assets/6823dc3d-fa5a-4ed1-875d-b0181ab83528

if clicks upon the restart in the preview, it should only restart the survey, not update the styling.

### Steps to Reproduce

go to config
in look and feel section, change the styling of the survey, and then click on restart

### Expected behavior

on clicking upon restart, the survey only should be restarted but update the styling.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:MacOs
- Node:
- npm:
```

**Comment by smritidoneria** [comment]
I want to work upon this issue

**Comment by mattinannt** [comment]
@smritidoneria thanks for helping out 🚀💪 I assigned you to the issue
