### ISSUE TITLE
[BUG] Tag input appears soon after a tag is created

### ISSUE THREAD

**Issue by vaishak10** [formbricks/formbricks#2884]
### Issue Summary

After receiving a response for a survey, if we try to add a tag to the response a weird bug pops up.
So once a tag is created and text box with the tag name appears for some brief seconds, The issue here is if user tries to create tags using keyboard actions and clicked on return once a tag is created and requested will be made ti create the same tag again for the text box that appears, This causes a issue as tag with same name cannot be created. This is UI issue so that the  text box does'nt appear in the first place

## Preview: 

https://github.com/user-attachments/assets/73cd9b5e-ff46-4814-8181-554e126928c0

### Steps to Reproduce

1. Create a Survey and Publish it
2. Complete the survey which will send a response for the created survey
3. Once the response is received, head back to the survey in dashboard and check the responses for the survey.
4. for the recieved response add a tag
5. after adding a tag a text box appears and later disappears. 

### Expected behavior

Once the tag is created the textbox should not appear, as this can lead to creation of duplicate tag which is not allowed, This will throw an error which will lead to poor User experience.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:MacOS
- Node:
- npm:
```

**Comment by vaishak10** [comment]
Willing to pick this up and raise a fix for the same!

**Comment by Dhruwang** [comment]
Hey @vaishak10 , thank you for raising this issue, I have assigned it to you 😊🙌🏻

**Comment by vaishak10** [comment]
> Hey @vaishak10 , thank you for raising this issue, I have assigned it to you 😊🙌🏻

Hey @Dhruwang have raised the PR for the fix: https://github.com/formbricks/formbricks/pull/2911
Please do review it if any changes are required
