### ISSUE TITLE
[BUG] Delete tags not working once merge operation is completed.

### ISSUE THREAD

**Issue by vaishak10** [formbricks/formbricks#2886]
### Issue Summary

So I created 6 tags, and merged the first tag with the 6th tag. In this process found some issues I wanted to bring up: 
1. Once a tag is merged then why is it still being visible in the UI. What I mean is if `tag1` is merged with `tag6` then only `tag6` should be visible. 
2. Even if `tag1` is visible after merge why is there a delete and merge button next to the tag. As far as I have understood the tag should not have these buttons after merge. The main issue what we face here is even if the user tries to delete the tag it won't be deleted. Only the tag it was merged with can be deleted.
3. Also the toast message needs to updated and needs to send a better message if merge is done again. 

My fix will be is to remove the tag from the UI once it's merged then all these issues won't be reproducible.

## Preview

https://github.com/user-attachments/assets/5029dc7e-f6cd-4142-9fa9-29c88e70a0a7

### Steps to Reproduce

1. Add multiple tags for a response.
2. Edit tags -> Merge one tag with another.
3. Delete a tag once merged or merge the same tag with another tag or same tag again

### Expected behavior

Once a tag is merge it should not be visible in the UI. The user should not be able to delete or merge the tag again

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: MacOS
- Node:
- npm:
```

**Comment by vaishak10** [comment]
I am willing to pick this up and work on it!

**Comment by smritidoneria** [comment]
Hey @vaishak10 , I am not able to reproduce this issue in Mac. It works fine.
Kindly Check this out-

https://github.com/user-attachments/assets/91e947af-2004-4f41-ad45-c6dfc3a73cff

**Comment by Dhruwang** [comment]
Hey @vaishak10 , merging and deletion of tags seems to work well for me too, but one thing that i noticed here is the confirmation modal. In our app we use this Delete Dialog modal (you can find it in `packages/ui/DeleteDialog`)

<img width="741" alt="Screenshot 2024-07-16 at 10 41 40 AM" src="https://github.com/user-attachments/assets/fc16c3f5-6389-49b9-bfa8-04213c20c89e">


But that seems to be missing for tag deletion 

<img width="1306" alt="Screenshot 2024-07-16 at 10 39 32 AM" src="https://github.com/user-attachments/assets/cebd952c-b0a4-46d5-afe0-92fea12d869b">

If you like, you can open a PR fixing that 😊🙌🏻

**Comment by vaishak10** [comment]
> Hey @vaishak10 , I am not able to reproduce this issue in Mac. It works fine. Kindly Check this out-
> 
>  Screen.Recording.2024-07-16.at.1.16.45.AM.mov

I faced this issue multiple times. in some cases the merge was successful but on working with tags multiple times started seeing this behaviour. Try with adding multiple tags and trying merging one after another

**Comment by vaishak10** [comment]
Hey @Dhruwang have raised the PR for the fix: https://github.com/formbricks/formbricks/pull/2912
Please do review it if any changes are required
