### ISSUE TITLE
[FEATURE] Add Card component to Storybook

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#2891]
### Is your feature request related to a problem? Please describe.

We are moving towards a unified design system in Formbricks to make the look and feel within Formbricks more consistent, eliminate duplicate component code, and make it easier for us to design new features.
Our goal is to have all of our UI components in Storybook so that we have a good overview of them all in one place.

### Describe the solution you'd like

To get one step closer to this goal, please add the `packages/ui/Card' component to Storybook by adding a `stories.ts' file to the component folder that shows the different variants and different argument combinations that this component can have.

As an example, take a look at the Button component in `packages/ui/Button'.

### Additional context

You can run storybook by running `pnpm storybook` in the Formbricks monorepo.

**Comment by Trjindal** [comment]
Hey, i  would like to work on this
