### ISSUE TITLE
[BUG] Multi-language: Forced to add label translations to rating question even though original language does not have labels

### ISSUE THREAD

**Issue by MaxWohlers** [formbricks/formbricks#2909]
### Issue Summary

When adding tranlations to a multi-language survey, I am forced to add labels to a rating scale, even though the original does not have any labels written

<img width="620" alt="Bildschirmfoto 2024-07-18 um 16 27 36" src="https://github.com/user-attachments/assets/3afbe3cf-f520-40fb-bfd8-73782280449d">

### Steps to Reproduce

1. Create survey in which original language's rating scale does not have any labels
2. Turn on multi language
3. Add language translations to all questions
4. be forced to add labels to rating scale even though original does not have any

### Expected behavior

Let me translate rating question without needing to create labels

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Dhruwang** [comment]
Thanks for reporting this, we will look into this 😊

**Comment by MaxWohlers** [comment]
Here you go! 

https://github.com/user-attachments/assets/7350cc76-9233-4a4b-934a-1fe404769946

**Comment by Dhruwang** [comment]
Hey @MaxWohlers , I am still not able to reproduce this issue 🙁


https://github.com/user-attachments/assets/7c55286f-4450-4e1a-8551-0f1ea89eb738


- If the problem persists, you can copy the questionId and remove the problematic question.
- Create a new question with the same content and replace its questionId with the original one.
- Then attempt to save it again.

This approach helps ensure your data stays consistent 😊

**Comment by jobenjada** [comment]
@MaxWohlers did this help? 🤓

**Comment by jobenjada** [comment]
@MaxWohlers I can also not replicate the issue, nor can I watch or download the video.

I supposed you don't have an empty space in the input? It's weird that it shows that you should Translate "nothing". Can you check the HTML Dom and see if there's a character here:
![Image](https://github.com/user-attachments/assets/446253bf-06d5-42a9-b5ea-edf1bd6ae756)

And does the issue still persist if you create a new survey instead? And how was this survey created? Maybe duplicated from a previous one? Or did you copy the survey to or from a product which has different language settings?
