### ISSUE TITLE
[BUG] Updated Action is not updated in the survey

### ISSUE THREAD

**Issue by MaxWohlers** [formbricks/formbricks#2916]
### Issue Summary

If I adjust/update an action (e.g. adding/deleting an url), this action within a survey is not automatically updated to the new parameters. I then still have to go into all the surveys and manually remove and add the same action again. 

### Steps to Reproduce

1. Create a new action within a survey
<img width="451" alt="Bildschirmfoto 2024-07-25 um 13 16 36" src="https://github.com/user-attachments/assets/6beb0a4e-8003-4cfc-99cb-db9e83dd2b23">

3. Go to the action section, find the action, adjust your parameters (in this example, I delete 'link2.com') and save updated action
<img width="650" alt="Bildschirmfoto 2024-07-25 um 13 17 21" src="https://github.com/user-attachments/assets/a3488b4c-fe6b-4a9c-a9e3-11d002235ed5">

4. Go into survey again (thinking the action should be updated) and realizing nothing happened and that it has still the old parameter, needing to manually remove and add the same action again
<img width="667" alt="Bildschirmfoto 2024-07-25 um 13 17 48" src="https://github.com/user-attachments/assets/4e0144ea-f9d4-4d62-8367-f525d802393d">

### Expected behavior

Updated actions in the action list should be automatically applied to the surveys that use the action.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@MaxWohlers thanks for raising an issue for this :-)

@pandeymangg I was able to reproduce the issue on Formbricks Cloud. Maybe it's a missing cache invalidation when updating an action. Can you please take a look :-)
