### ISSUE TITLE
[BUG] Filters do not apply to summary impressions

### ISSUE THREAD

**Issue by MaxWohlers** [formbricks/formbricks#2919]
### Issue Summary

I observed that the filters are not functioning as expected for the survey impression scorecard in the summary tab, leading to wrong percentage calculations for for Starts, Completed, and Drop-Offs.

### Steps to Reproduce

1. Create a survey with rating (this issue might extend to other question types).
2. Collect responses to the survey.
3. Go to Summary tab.
4. Apply filters (e.g. by device).
5. Observe that the 'Impressions' do not take effect as intended, leading to wrong percentage calculations in the 'Starts', 'Completed', 'Drop-Offs' scorecard.

### Expected behavior

'Impressions' Scorecard should also change according to filter, giving meaningful percentage calculations for Starts, Completed, Drop-Offs

### Screenshots

<img width="1223" alt="Bildschirmfoto 2024-07-26 um 09 21 25" src="https://github.com/user-attachments/assets/98f299c3-05a2-4d22-abba-8ac20b9e2e82">

<img width="1223" alt="Bildschirmfoto 2024-07-26 um 09 21 40" src="https://github.com/user-attachments/assets/67174210-1615-410e-933b-817c1d9156aa">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@gupta-piyush19 Can you please take a look at it? :-) I think this could be a quick fix :-)

**Comment by mittalsam98** [comment]
Hey @mattinannt can I work on it ? I would like to pick this up
