### ISSUE TITLE
[BUG] Color coding in NPS misplaces text

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2922]
### Issue Summary

text is centered: 

<img width="510" alt="image" src="https://github.com/user-attachments/assets/c51a220b-9b00-4912-8606-319a049fbeff">

text is not centered anymore:

<img width="529" alt="image" src="https://github.com/user-attachments/assets/f4fa8193-2b16-4f8c-bf51-34c18b978908">

### Steps to Reproduce

1. Create a survey with an NPS question
2. Toggle "add color code" on / off

### Expected behavior

The text should be centered in the white space (so ignore the colored space when centering text horizontally) like so:

<img width="535" alt="image" src="https://github.com/user-attachments/assets/252156b5-96f5-4668-a69e-0137592be001">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mittalsam98** [comment]
Hey I want to pick this up

**Comment by jobenjada** [comment]
@mittalsam98 you're assigned, are you working on it?

**Comment by mittalsam98** [comment]
yes I am working on this @jobenjada
