### ISSUE TITLE
[TWEAK] Replace checkbox with AdvancedOptionsToggle

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2923]
### Is your feature request related to a problem? Please describe.

This checkbox in the Schedule a call-question type is inconsistent UI:

<img width="648" alt="image" src="https://github.com/user-attachments/assets/8370a3e2-4209-42ac-859b-cf80f5cd85d0">

Normally, we're using the AdvancedOptionsToggle component which looks like this:

<img width="638" alt="image" src="https://github.com/user-attachments/assets/669d710b-568b-4a60-bf79-ef19f3719ffb">

### Describe the solution you'd like

1. Replace the checkbox with the AdvancedOptionsToggle.tsx component

2. Change the label and placeholder text (as seen in the screenshot).

3. Test thoroughly to make sure it works as it should 🤓

**Comment by Acksout** [comment]
Made a PR updating the styling. https://github.com/formbricks/formbricks/pull/2925 @jobenjada
