### ISSUE TITLE
[FEATURE] Allow only whole number changes when adjusting '% of users seeing survey' when using arrows.

### ISSUE THREAD

**Issue by MaxWohlers** [formbricks/formbricks#2927]
### Is your feature request related to a problem? Please describe.

It has no practical value for me using the arrows for adjusting '% of users seeing survey' since it changes the % to the second decimal point. Thus, I am not using the arrows and type in the number instead. 

### Describe the solution you'd like

Let the % change by a whole number when using the arrows. 

### Additional context

<img width="246" alt="Bildschirmfoto 2024-07-30 um 09 21 19" src="https://github.com/user-attachments/assets/f6502315-d09d-42d7-a010-6ae1e0756b45">
<img width="260" alt="Bildschirmfoto 2024-07-30 um 09 21 28" src="https://github.com/user-attachments/assets/6eaed789-1062-4518-8b27-7a811620693e">

**Comment by jobenjada** [comment]
@mittalsam98 thnaks for picking this up! we still need percentages to be able to set by 2 decimal points. We have customers with hundreds of thousands of visitors, for them it makes a difference.

Agree tho that the usability would be better if the keyboard changes whole percentages instead of percentage points.

**Comment by mittalsam98** [comment]
@jobenjada  sure will make the changes.

**Comment by jobenjada** [comment]
@mittalsam98 are you still working on this? Please fix this so that instead of changing the second decimal behind the comma, we change the first behind the comma. That should do the trick.

**Comment by mittalsam98** [comment]
sorry @jobenjada I forgot about this issue, I will make the changes and raise PR ASAP
