### ISSUE TITLE
[BUG] Redis to LRU fallback

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2931]
### Issue Summary

When the connection to the Redis server times out due to some error (e.g. Redis overloaded etc.) Formbricks does not properly detect that and does not fall back to LRU caching.

### Steps to Reproduce

1. Run Formbricks with Redis
2. Turn off Redis
3. Formbricks no longer usable since it always tries to reconnect to Redis and will throw tons of errors like:
`Failed to update prerender cache for xyz Error: Redis client is not ready yet or connection is lost. Keep trying...`

### Expected behavior

When connection to Redis is lost it should fall back to LRU making sure there is at least one caching option available.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v2.3.2
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich I'm currently not sure if falling back to LRU cache is the desired behaviour for Formbricks. When Redis is configured (e.g. in a cluster setup), Formbricks wouldn't work properly when running with LRU cache and would have different cache states across instances.
So maybe a controlled failure of the instance would make more sense than going into a state that might cause caching issues on the cluster. What do you think?

**Comment by jonas-hoebenreich** [comment]
Good point. 99.9% of requests are just survey syncs, so having those cached in memory should be fine and for the rest maybe a cache is not needed at all when the Redis server is unreachable / unresponsive. But open to discuss this.

**Comment by mattinannt** [comment]
We will release official support for Redis with Formbricks 3.0 and will make sure everything is working properly before making the release :-)
