### ISSUE TITLE
[FEATURE] Enhance Action Overview with Active, Inactive, and Last Triggered Info

### ISSUE THREAD

**Issue by MaxWohlers** [formbricks/formbricks#2934]
### Is your feature request related to a problem? Please describe.

Having hundreds of Actions, it is cumbersome to keep track/clean up all the actions that are not in use anymore or knowing when they have been last used. 
- Is the action currently in an active or inactive survey ? -> needs a click
- When was the action last used/triggered? -> info not available
- Delete action -> Needs two clicks

### Describe the solution you'd like

Add to the Action Overview:
- Column: Active -> Number of active surveys for which action is used (or even a list of surveys)
- Column: Inactive -> Number of inactive surveys for which action was used (or even a list of surveys)
- Column: Last trigged -> Date when action was last triggered
- Three Dots -> Quick action to edit/delete/duplicate etc. the action

### Additional context

<img width="937" alt="Bildschirmfoto 2024-07-31 um 11 26 09" src="https://github.com/user-attachments/assets/94ea150b-85d3-4c07-97fc-5b00ca3b14b9">

**Comment by Danish-Belal** [comment]
@MaxWohlers  Kindly assign Assign this to me

**Comment by jobenjada** [comment]
@Danish-Belal have a go at it :)

**Comment by Danish-Belal** [comment]
Is there time Specify to complete it ?? @jobenjada

**Comment by mattinannt** [comment]
Since we don't store this information in backend we unfortunately are not able to add this information. We removed sending actions to the backend since it is not possible performance-wise with our current infrastructure. Closing this issue for now.
