### ISSUE TITLE
"Add question below" menu does not include all question types

### ISSUE THREAD

**Issue by brandishwar** [formbricks/formbricks#2948]
### Issue Summary

The "Add question below" menu does not include all question types. And what is omitted seems to depend on the question type. For example, if you bring up that menu on a "Free text" question type, the menu will not include "Free text". Try to use that menu on a "Consent" question type, and "Consent" will be excluded.

It looks like "Add question below" is re-using the same menu as the "Change question type" option.

### Steps to Reproduce

1. Create or open a survey
2. Click on the "..." on one of the questions to bring up the menu
3. Hover mouse over "Add question below"

### Expected behavior

"Add question below" should display all question types.

### Screenshots

Example menu showing "Free text" is missing:

![no-free-text](https://github.com/user-attachments/assets/cb3eeeba-7038-4f6a-8e0d-5501a60eaaec)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Ubuntu 24.04 LTS
- Browser: Brave v1.68.131
```

**Comment by mattinannt** [comment]
@brandishwar thanks for raising an issue for this :-) 

@Dhruwang Can you please check on this and add the missing question types :-)

**Comment by brandishwar** [comment]
Pulled latest release this morning and can confirm this is corrected.
