### ISSUE TITLE
Deleting submission does not delete uploaded files

### ISSUE THREAD

**Issue by brandishwar** [formbricks/formbricks#2950]
### Issue Summary

When deleting a survey response, any files uploaded with that response are not deleted with it.

### Steps to Reproduce

1. Identify or create survey with at least one "File upload" question.
2. Complete survey, uploading several files with it. Response shows in dashboard with attached files.
3. Hover mouse over download icon on at least one of the file submissions. Note the filename in the URL.
4. Delete response from step 2.
5. On the server, navigate to the storage folder. Note that the files were not deleted with step 4.

### Expected behavior

All files uploaded with a survey response are deleted when the response is deleted.

### Other information

This looks to be an oversight in the tasks for Feature #265

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
OS: Ubuntu 24.04LTS. Installed using using Docker Compose.
```

**Comment by mattinannt** [comment]
@pandeymangg Would it be possible to implement this? Since this is the expected behaviour when deleting a response, we should find a way to support it :-)
