### ISSUE TITLE
[BUG] Editing Link Surveys Stopped Working

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2962]
### Issue Summary

I'm not sure in what version this issue was introduced but editing of Link surveys is broken for us. When you click on the Edit button the app only shows an error message "Error loading resources - This resource doesn't exist or you don't have the neccessary rights to access it."
The console shows the following error:
```
TypeError: Cannot read properties of undefined (reading 'map')
    at lt (page-3749994ab4cec221.js:1:117680)
    at rE (1dd3208c-89314a785af3694c.js:1:40342)
    at iZ (1dd3208c-89314a785af3694c.js:1:117027)
    at ia (1dd3208c-89314a785af3694c.js:1:95163)
    at 1dd3208c-89314a785af3694c.js:1:94985
    at il (1dd3208c-89314a785af3694c.js:1:94992)
    at oJ (1dd3208c-89314a785af3694c.js:1:92348)
    at oZ (1dd3208c-89314a785af3694c.js:1:91767)
    at MessagePort.T (286-0b8f9a1e5e8d0066.js:1:84217)
```

### Steps to Reproduce

1. Open Link survey
2. Click on "Edit"

### Expected behavior

You can edit link surveys

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v2.4.0 (but I think this issue was introduced earlier)
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich Can you please share the server logs for this issue?

**Comment by jonas-hoebenreich** [comment]
I just checked the logs and it seems like there are no server logs - maybe it's a frontend only error?

**Comment by jonas-hoebenreich** [comment]
Oh sorry for the wrong information. It seems like pods were throwing so many errors that there was a log ingestion lag. While I'm searching for the original error message for the Link-editing issue (which is not that easy since there are so many other errors), this is the error message that was thrown for each survey sync:
```
TypeError: Cannot read properties of undefined (reading '0')
at Array.map (<anonymous>)
at E (/home/nextjs/apps/web/.next/server/chunks/7123.js:1:38987)
at H (/home/nextjs/apps/web/.next/server/chunks/7123.js:1:43091)
at async eR.execute (/home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874)
at async /home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
at async eR.handle (/home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:37512)
at /home/nextjs/apps/web/.next/server/app/api/v1/client/[environmentId]/website/sync/route.js:1:2904
```
(the order of the lines in the error message is probably wrong)

I've rolled back and editing Link surveys is working again.

**Comment by jonas-hoebenreich** [comment]
So I can't find the entire error message that was thrown when editing Link surveys. I found `at p9 (/home/nextjs/apps/web/.next/server/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/page.js:18:290667)` but since our logging tool treats each line as a separate error message it's hard to see weather the other logs correspond to the sync error or the edit error :/
Does this already help to debug the issue?

**Comment by mattinannt** [comment]
Is this happening for all your surveys or only specific ones?
Is this only happening for existing surveys or also for new surveys?
Did you delete the (redis) cache after upgrading Formbricks to the latest version?

**Comment by jonas-hoebenreich** [comment]
Ok, thanks for the tip, clearing the Redis cache fixed the issue. Maybe you could introduce
a) limited cache lifetime
b) introduce a versioned prefix that eliminates the need to restart Redis (which causes downtime)
Closing this issue now and creating a new issue for those two points
