### ISSUE TITLE
[BUG] error occurred during migration UPGRADE_TO_VERSION="v2.4" 

### ISSUE THREAD

**Issue by paulceli** [formbricks/formbricks#2984]
### Issue Summary

Hello,
I got an error during the data-migration step.
```
starting migration
Deleted 0 segments with no surveys
An error occurred during migration: PrismaClientKnownRequestError:
Invalid `tx.survey.findMany()` invocation in
/app/packages/database/data-migrations/20240712123456_segments_cleanup/data-migration.ts:30:56

  27
  28 console.log(`Deleted ${segmentsWithNoSurveys.length.toString()} segments with no surveys`);
  29
→ 30 const appSurveysWithoutSegment = await tx.survey.findMany(
The column `Survey.endings` does not exist in the current database.
    at _n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7749)
    at _n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7057)
    at _n.request (/app/node_modules/@prisma/client/runtime/library.js:121:6741)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9355)
    at async prisma.$transaction.timeout (/app/packages/database/data-migrations/20240712123456_segments_cleanup/data-migration.ts:30:40)
    at async Proxy._transactionWithCallback (/app/node_modules/@prisma/client/runtime/library.js:130:7722)
    at async runMigration (/app/packages/database/data-migrations/20240712123456_segments_cleanup/data-migration.ts:7:3) {
  code: 'P2022',
  clientVersion: '5.18.0',
  meta: { modelName: 'Survey', column: 'Survey.endings' }
}
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

The app is not starting anymore.
Getting logs like : 
```
formbricks-1  | > @formbricks/database@0.1.0 db:migrate:deploy
formbricks-1  | > env DATABASE_URL="${MIGRATE_DATABASE_URL:-$DATABASE_URL}" prisma migrate deploy
formbricks-1  |
formbricks-1  | Error: Can't write to /usr/local/lib/node_modules/prisma/node_modules/@prisma/engines please make sure you install "prisma" with the right permissions.
formbricks-1  | npm error Lifecycle script `db:migrate:deploy` failed with error:
formbricks-1  | npm error code 1
formbricks-1  | npm error path /home/nextjs/packages/database
formbricks-1  | npm error workspace @formbricks/database@0.1.0
formbricks-1  | npm error location /home/nextjs/packages/database
formbricks-1  | npm error command failed
formbricks-1  | npm error command sh -c env DATABASE_URL="${MIGRATE_DATABASE_URL:-$DATABASE_URL}" prisma migrate deploy
```

### Steps to Reproduce

I upgraded from (working) 2.3.2 to 2.4.1 and applied the data migration step 2.4.
( I believe I also previously upgraded from verison 2.3.1 coming from  2.1.1. and also did a data migration upgrade with no problem. I might have jumped over data-mig major version 2.2. But I figured the data migration would handle that .. )

### Expected behavior

no mig error.

### Other information

Here is the full error log :
[2.4.1_migration_log.txt](https://github.com/user-attachments/files/16548740/2.4.1_migration_log.txt)

Also I extracted the "_prisma_migrations" table :
[prisma_migrations_table.txt](https://github.com/user-attachments/files/16561118/prisma_migrations_table.txt)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: rhel 9, docker
- Node: /
- npm: /
```

**Comment by paulceli** [comment]
FYI,
I rolled back the docker-compose to image v2.3.2 and the app works fine.

**Comment by jobenjada** [comment]
hey! Can you try 2.4.2? 🤓

**Comment by paulceli** [comment]
Ah! beautiful.
Data migration completed correctly and all is working fine now. 

Thanks a lot

**Comment by paulceli** [comment]
Hey,
Upgraded to 2.4.3 and I'm still missing the product from the menu.
I tried to add again products that don't appear in this menu and get a "Something went wrong while executing the operation." snackbar error msg.

Any clue ? 
thx

**Comment by jobenjada** [comment]
hey @paulceli are you still having the issue? If so, please open Prisma Studio on your prod db, find the product and update the channel to `null`

Thanks!

**Comment by paulceli** [comment]
Hey @jobenjada Thanks for the update.
Don't know how to launch the Prisma studio on the DB of a container.

I managed to attach to the sql console : docker exec -it formbricks-postgres-1 psql -U postgres formbricks
And to run SELECT * FROM "Product";
I don't see anything that looks like "channel".

In attachment the content of the table: [product_table.txt](https://github.com/user-attachments/files/16977673/product_table.txt)

Thanks again

**Comment by jobenjada** [comment]
hey @paulceli hmm your products all don't have a config, that's why they're not listed. Something must've gotten wrong during the data migration.

So the easiest way to get your products back in the list is to add a config:

```{"channel":null,"industry":null}```

That'll get you the products back into the list.

I'll also talk to the eng team to see if you can ship a patch release which checks products for a config and if there isn't one to add the one above.

Sorry for the inconvenience  🙏

**Comment by paulceli** [comment]
thx @jobenjada !
After updating the DB as mentionned and restarting the app. Problem is fixed.

No worries, 
thx again for the support.

**Comment by jobenjada** [comment]
love it!
