### ISSUE TITLE
[BUG] Ninja emoji not supported on Windows 10

### ISSUE THREAD

**Issue by filiabel** [formbricks/formbricks#3001]
### Issue Summary

Ninja emoji used for "Hidden Fields" is not shown on Windows 10. [Source](https://emojipedia.org/microsoft/windows-10/ninja).
See screenshot below.

### Steps to Reproduce

Use Windows 10, visit survey editor under "Hidden Fields" section.

### Expected behavior

Suggestion would be to switch out the emoji with one that is universially supported across all platforms. Maybe one of these emojis is a nice replacement:
* 🕶️
* 🔍
* ❓
* 🕵️

### Screenshots

![image](https://github.com/user-attachments/assets/bc4b1b2b-e80d-475d-a846-aa307a9b6f4e)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Chrome
- Version: 2.4.2
```

**Comment by jobenjada** [comment]
ahh thanks @filiabel it's probably time to remove all emojis and replace them with icons for a consistent look and feel

**Comment by filiabel** [comment]
> ahh thanks @filiabel it's probably time to remove all emojis and replace them with icons for a consistent look and feel

Sounds way better than replacing with new emoji 🙌

**Comment by jobenjada** [comment]
We are working with Lucide Icons only, so please find all emojis in the app and replace them with a matching Lucide icon :)

If you wanna work on it you can self-assign with "/ assign"
