### ISSUE TITLE
[BUG] Wordpress Plugin uses old version of formbricks-js

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#3008]
### Issue Summary

The Formbricks Wordpress Plugin ( https://github.com/formbricks/wordpress ) uses an old version of `formbricks-js` which leads to it not working with the latest version of Formbricks.
With Formbricks 2.0 we introduces a new approach, where we load the formbricks-js code (`js-core`) on demand from the given app hostname (e.g. `https://app.formbricks.com`).
This leads to the wordpress plugin not supporting the latest features plus sometimes even throwing errors because of compatibility issues.

### Steps to Reproduce

1. Install a new instance of Formbricks
2. Install the Formbricks Wordpress Plugin and configure it to use Formbricks cloud.

### Expected behavior

The Wordpress plugin should also use the new approach for Formbricks > 2.0 loading the js code from the Formbricks instance (Cloud or self-hosted) by accessing the script at `/api/packages/website` (e.g. `https://app.formbricks.com/api/packages/website` for Formbricks Cloud)

In the Wordpress plugin this can happen similar to what we do with the HTML embed ( https://formbricks.com/docs/website-surveys/framework-guides#html ) where the script is loaded from `/api/packages/website` and and init call is made afterwards.

Please update the Wordpress plugin to work with this approach.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by jobenjada** [comment]
@Saurabhchaddha6 Do you have experience with Wordpress?

If so, please try /assign once more, it should work now 🤓

**Comment by mattinannt** [comment]
Solved by @andrewnimmo 🔥
