### ISSUE TITLE
[BUG] Repocloud definition does not include CRON_SECRET generation

### ISSUE THREAD

**Issue by dannyob** [formbricks/formbricks#3009]
### Issue Summary

The repocloud link in the [package description](https://github.com/formbricks/formbricks/pkgs/container/formbricks#cloud-version) on github includes setup for environment variables, but omits CRON_SECRET.

### Steps to Reproduce

1. Went to [package description](https://github.com/formbricks/formbricks/pkgs/container/formbricks#cloud-version), clicked on 
2. Clicked on [repocloud link](https://repocloud.io/details/?app_id=254)
3. Deployed app.
4. App eventually reports a 500 error
5. Check logs -- you will see missing CRON_SECRET variable errors.
6. Manually add CRON_SECRET env variable with value obtained from `openssl rand -hex 32` onto the repocloud instance by going to the settings, choosing project, and selecting env vars option.
7. App will restart and no longer reports 500 error.

### Expected behavior

Formbricks should deploy seamlessly instead of erroring out.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@cosark Are you a RepoCloud member or do you know how to update the template?

**Comment by cosark** [comment]
> @cosark Are you a RepoCloud member or do you know how to update the template?

This bug has now been fixed! Thanks for the heads up.

**Comment by mattinannt** [comment]
@cosark Thanks a lot for the fix :-)
