### ISSUE TITLE
[FEATURE] Info about new Formbricks version

### ISSUE THREAD

**Issue by filiabel** [formbricks/formbricks#3017]
### Is your feature request related to a problem? Please describe.

I would like a small info box a visible place in the admin UI that informs you about a new version of Formbricks being available. This would encourage self-hosters to upgrade, read the changelog and get to know the latest features without having to actively check GitHub or Discord.

### Describe the solution you'd like

See how Outline has solved it here by fetching info directly from GitHub API: https://github.com/outline/outline/blob/main/app/components/Sidebar/components/Version.tsx

It will only show if you are not on the latest version. I am not sure how to take Formbricks Cloud into account, and if it follows the same versioning/release system.

Ugly example sketch: 
![image](https://github.com/user-attachments/assets/71332bee-0f1f-4625-834c-4380539c5a89)

**Comment by mattinannt** [comment]
@filiabel Thanks for raising an issue for this; good suggestion 😊 
Maybe a contributor is up for the challenge :-)

**Comment by Saurabhchaddha6** [comment]
I would like to work on this, i think i can do it

**Comment by mattinannt** [comment]
@Saurabhchaddha6 I assigned the issue to you :-) 🚀

**Comment by RajuGangitla** [comment]
@jobenjada can you assign this to me

**Comment by filiabel** [comment]
Fixed in https://github.com/formbricks/formbricks/pull/3126
