### ISSUE TITLE
[FEATURE] manage path style for s3 compatible service

### ISSUE THREAD

**Issue by sinzyy** [formbricks/formbricks#3023]
### Is your feature request related to a problem? Please describe.

Manage path style for s3 compatible storages.

### Describe the solution you'd like

Configure through an environment variable like "S3_FORCE_PATH_STYLE". It would be disabled by default : 
`S3_FORCE_PATH_STYLE=0`

Use it when the client is instantiated in s3 service with the `s3ForcePathStyle` constructor parameter

### Additional context

By default, AWS S3 use virtual host. But some alternatives like Minio use path style(by default).

More details here : 
https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access

**Comment by mattinannt** [comment]
@sinzyy thanks for raising an issue for this :-) Can you explain in a bit more detail what we would need to change in order to make everything work for you?

**Comment by sinzyy** [comment]
Sure. I have never try Next, but you should be able to configure the s3 client with a boolean parameter here : https://github.com/formbricks/formbricks/blob/49d4f436520e1f0bf7f4e57fcc8f2d369f11d970/packages/lib/storage/service.ts#L42-L46

With something like :

```
s3ClientInstance = new S3Client({
  credentials,
  forcePathStyle: S3_FORCE_PATH_STYLE
  region: S3_REGION,
  ...(S3_ENDPOINT_URL && { endpoint: S3_ENDPOINT_URL }),
 });

```

You can see a spec from the AWS SDK sour code here : 
https://github.com/aws/aws-sdk-js-v3/blob/143a7ae4c7be09eb2d960a8df689e4ecbeba3a92/packages/s3-presigned-post/src/createPresignedPost.e2e.spec.ts#L21

Thanks for your work :)

**Comment by mattinannt** [comment]
@sinzyy Thanks for sharing more details on this :-)
