### ISSUE TITLE
[BUG] Products and surveys not showing in menu

### ISSUE THREAD

**Issue by edersilva78** [formbricks/formbricks#3026]
### Issue Summary

Some surveys and Products were not available via the menu. Only via direct link.

This erros was present in the log.

[
formbricks-1  |   {
formbricks-1  |     "expected": "'link' | 'app' | 'website'",
formbricks-1  |     "received": "undefined",
formbricks-1  |     "code": "invalid_type",
formbricks-1  |     "path": [
formbricks-1  |       "config",
formbricks-1  |       "channel"
formbricks-1  |     ],
formbricks-1  |     "message": "Required"
formbricks-1  |   },
formbricks-1  |   {
formbricks-1  |     "expected": "'eCommerce' | 'saas' | 'other'",
formbricks-1  |     "received": "undefined",
formbricks-1  |     "code": "invalid_type",
formbricks-1  |     "path": [
formbricks-1  |       "config",
formbricks-1  |       "industry"
formbricks-1  |     ],
formbricks-1  |     "message": "Required"
formbricks-1  |   }
formbricks-1  | ]
formbricks-1  | Action error: Data validation of product failed

### Steps to Reproduce

Normal operation.

### Expected behavior

The surveys ans products should be available.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
Docker. Version 2.4.2
```

**Comment by edersilva78** [comment]
Fixed the issue by updating the database.

`formbricks=# update "Product" set config = '{"channel": "link", "industry": "other"}' where config = '{}`

Maybe some issue with data migration.

**Comment by mattinannt** [comment]
@edersilva78 thanks for the update :-) We will investigate what went wrong here :-)

**Comment by mattinannt** [comment]
With the data migrations shipped with this feature plus additional hotfix after the release this should be solved :-)
