### ISSUE TITLE
[BUG] Content Security Policy (CSP) Header Not Set

### ISSUE THREAD

**Issue by gupta-piyush19** [formbricks/formbricks#3032]
### Issue Summary

The department of health in Hong Kong reported the following issue:

**Content Security Policy (CSP) Header Not Set**

```
Content Security Policy (CSP) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross Site Scripting (XSS) and data injection attacks. These attacks are used for everything from data theft to site defacement or distribution of malware. CSP provides a set of standard HTTP headers that allow website owners to declare approved sources of content that browsers should be allowed to load on that page — covered types are JavaScript, CSS, HTML frames, fonts, images and embeddable objects such as Java applets, ActiveX, audio and video files.
```

Please fix the issue using these chatGPT suggestions:

To address the issue of the Content Security Policy (CSP) header not being set, you need to configure your web server or application to include a CSP header in HTTP responses. This header helps protect your site from a variety of attacks, including Cross-Site Scripting (XSS) and data injection attacks.

Here's how you can set the CSP header in a Next.js application and at the proxy level using Traefik.

### Setting CSP in Next.js

1. **Open or create** the `next.config.js` file at the root of your Next.js project.

2. **Add the headers configuration** to set the `Content-Security-Policy` header. Here's an example:

```javascript
// next.config.js

module.exports = {
  async headers() {
    return [
      {
        // Apply these headers to all routes in your application
        source: "/(.*)",
        headers: [
          {
            key: "Content-Security-Policy",
            value: "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self'; frame-src 'none'; object-src 'none';",
          },
        ],
      },
    ];
  },
};
```

### Explanation of CSP Directives

- **default-src 'self'**: Allows content only from the origin site.
- **script-src 'self'**: Allows scripts only from the origin site.
- **style-src 'self'**: Allows styles only from the origin site.
- **img-src 'self' data:**: Allows images from the origin site and data URIs.
- **font-src 'self'**: Allows fonts only from the origin site.
- **frame-src 'none'**: Prevents embedding the site in iframes.
- **object-src 'none'**: Disallows embedding objects like Flash or Java applets.

### Summary

1. **Determine the required CSP**: Identify the sources of content your application needs to load (scripts, styles, images, etc.).
2. **Set the CSP Header**: Configure the CSP header in your Next.js application.
3. **Test the CSP**: Use browser developer tools to verify that the CSP header is being applied and monitor for any violations.

By properly setting the CSP header, you add an important layer of security to your web application, helping to prevent XSS and other injection attacks.

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

CSP header should be present

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
Solved with a simple implementation of CSP headers.
