### ISSUE TITLE
[BUG] unable to upload logos & backgrounds (on premise)

### ISSUE THREAD

**Issue by paulceli** [formbricks/formbricks#3036]
### Issue Summary

Hello,
We can't upload logos & backgrounds to our formbricks instance.
We are on premise and are using the standard docker-compose.

Here is the behavior in the front :

![bug_upload_logo](https://github.com/user-attachments/assets/b9045254-1588-4c95-9180-f2a517bf058a)

we get the following error logs in the formbricks container :

```
formbricks-1  |  ⨯ TypeError: fetch failed
formbricks-1  |     at node:internal/deps/undici/undici:13178:13
formbricks-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
formbricks-1  |     at async fetchExternalImage (/home/nextjs/node_modules/next/dist/server/image-optimizer.js:580:17)
formbricks-1  |     at async NextNodeServer.imageOptimizer (/home/nextjs/node_modules/next/dist/server/next-server.js:650:48)
formbricks-1  |     at async cacheEntry.imageResponseCache.get.incrementalCache (/home/nextjs/node_modules/next/dist/server/next-server.js:182:65)
formbricks-1  |     at async /home/nextjs/node_modules/next/dist/server/response-cache/index.js:90:36
formbricks-1  |     at async /home/nextjs/node_modules/next/dist/lib/batcher.js:45:32 {
formbricks-1  |   [cause]: Error: unable to verify the first certificate
formbricks-1  |       at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
formbricks-1  |       at TLSSocket.emit (node:events:519:28)
formbricks-1  |       at TLSSocket._finishInit (node:_tls_wrap:1085:8)
formbricks-1  |       at ssl.onhandshakedone (node:_tls_wrap:871:12)
formbricks-1  |       at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
formbricks-1  |     code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
formbricks-1  |   }
formbricks-1  | }
```

### Steps to Reproduce

Upload a picture

### Expected behavior

Pictures uploads

### Other information

We are on version 2.4.3 ( upgraded ) and have set the new following option:

    # If set to 0, the server will accept connections without requiring authorization from the list of supplied CAs (default is 1).
    SMTP_REJECT_UNAUTHORIZED_TLS: 0

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: rhle 9
- Node: /
- npm: /
```

**Comment by mattinannt** [comment]
@paulceli Thanks for raising an issue for this. Are you using the default local file upload or S3?

@pandeymangg Can you please take a look? :-)

**Comment by paulceli** [comment]
The default local file upload.
thx

**Comment by thewebchameleon** [comment]
having the same issue

**Comment by pandeymangg** [comment]
hey! @paulceli, in my testing the local uploads work fine with the latest version of formbricks (`2.5.3`) as well as (`2.4.3`) with the `SMTP_REJECT_UNAUTHORIZED_TLS: 0` option. Do you have any other information that can help us reproduce this? like from which version did you upgrade formbricks to `2.4.3`?

**Comment by CarefulGuru** [comment]
I'm having the same issue on my on-prem instance. I have set the following environment variables:

```
DATABASE_URL=postgres://p
NEXTAUTH_SECRET=
ENCRYPTION_KEY=
CRON_SECRET=
WEBAPP_URL=https://$(PRIMARY_DOMAIN)
NEXTAUTH_URL=https://$(PRIMARY_DOMAIN)
EMAIL_VERIFICATION_DISABLED=1
PASSWORD_RESET_DISABLED=0
SIGNUP_DISABLED=0
EMAIL_AUTH_DISABLED=0
INVITE_DISABLED=0
ONBOARDING_DISABLED=0
GOOGLE_SHEETS_CLIENT_ID=
GOOGLE_SHEETS_CLIENT_SECRET=
GOOGLE_SHEETS_REDIRECT_URL=
SMTP_HOST=
SMTP_PORT=25
SMTP_USER=
SMTP_PASSWORD=
MAIL_FROM=
SMTP_SECURE_ENABLED=0
```

The error in console is just a generic Internal Server Error, 500, no additional details attached. I can upload a logo fine on individual surveys, but it fails when I try to upload it in the look & feel page under configuration.
