### ISSUE TITLE
[BUG] Environment / Product disappeared after updating

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#3045]
### Issue Summary

We have an environment / product "Booking Funnel" that just disappeared from the list of products after upgrading to the latest version of Formbricks. It's still possible to access the product via the direct URL but switching to this product no longer works.

The product just disappeared:
![image](https://github.com/user-attachments/assets/7e67eec2-48ff-4d23-835b-f521859ea9de)

When accessing the product directly it looks like this:
![image](https://github.com/user-attachments/assets/bcf4e710-7992-4a33-97d1-e578963f026a)

I've restarted Redis and ran all migrations.

### Steps to Reproduce

1. Try to access our main Formbricks product

### Expected behavior

All products are selectable from the product switcher.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v2.4.3
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich thanks for raising an issue for this. We are looking into this and will publish a fix asap 😊

**Comment by jobenjada** [comment]
Hey @jonas-hoebenreich 

Can you have a look in Prisma Studio what your product.config of Booking Funnel says?

Seems like you have both website and app surveys in one product so it should be `channel:null`

<img width="424" alt="image" src="https://github.com/user-attachments/assets/19ad48f3-40d2-46c4-afa3-b4c3c1036a97">

The Product Changer is handled in the `MainNavigation.tsx` file in case you have a minute to debug it yourself 🤓

**Comment by jonas-hoebenreich** [comment]
The config for the product in the database looks like this:

```
      name      | config 
----------------+--------
 Booking Funnel | {}
(1 row)
```

Can I safely set this to e.g. `{"channel": "website", "industry": "eCommerce"}` to resolve the issue?

**Comment by jobenjada** [comment]
If you only have `Website Surveys` and `Link Surveys` in your product than that's the way to go. It'll only affect the UI slightly: Based on the channel we reduce the survey types and by industry we filter the templates

**Comment by jonas-hoebenreich** [comment]
Thank you, it works now 👍
