### ISSUE TITLE
[FEATURE] Replace loading spinner with loading skeleton

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3051]
### Is your feature request related to a problem? Please describe.

<img width="1179" alt="image" src="https://github.com/user-attachments/assets/fe1505b6-27b3-4e78-ac51-20603064be80">

### Describe the solution you'd like

This doesn't use a skeleton loader but a loading spinner. 

Replace this with a loading skeleton. Research how we do it on other places and follow the same patterns like the Survey Editor or the Summary and Response pages.

**Comment by ekansh2** [comment]
Hi @jobenjada, I would like to take up this issue. Please assign me.

**Comment by SaiSawant1** [comment]
hi @ekansh2, I have started working on it and I am halfway done. I am sorry but can I work on this PR.
![swappy-20240826_235645](https://github.com/user-attachments/assets/ba246d08-e74b-4227-a2e8-67e0caae35e7)

**Comment by ekansh2** [comment]
@SaiSawant1 no issues.

**Comment by SaiSawant1** [comment]
That's my PR, should I make any changes to it.

**Comment by SaiSawant1** [comment]
hey, @jobenjada is the PR ok? Do you have any suggestions?

**Comment by w0wayush** [comment]
Is this PR completed??
