### ISSUE TITLE
[BUG] Rounded corners have gap

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3052]
### Issue Summary

<img width="390" alt="image" src="https://github.com/user-attachments/assets/02933e41-6655-4da3-9a4f-24ea14cc6f8b">

Theres a little gap between the rounded corners of the background card and the grounded corners of the border.

### Steps to Reproduce

1. Create a survey
2. Change background color for high contrast
3. See the gap

### Expected behavior

Find out why the gap exists and align the border radius so the gap is no more.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by SaiSawant1** [comment]
isn't that space for the border color?

**Comment by jobenjada** [comment]
@SaiSawant1 what do you mean? You can see that due to the different radius the background color shines through (red in this case)
