### ISSUE TITLE
[FEATURE]: Add Logic to Date 

### ISSUE THREAD

**Issue by Arian1192** [formbricks/formbricks#3059]
### Is your feature request related to a problem? Please describe.

When I want to discern between certain logics using the Question type : Date , it is not possible because it does not have the logic component.

### Describe the solution you'd like

I would like to have the same behaviour for what we have for a simple Question type in Date

This would facilitate the logic in certain use cases as well as facilitate the flow of information in the form. 

### Describe alternatives you've considered

The alternative I have considered is to make use of a Plain Text which is not very efficient considering that there is a Question Type: Date.

### Additional context

As a context I am making an onboarding form for a group of companies, of which I need to be able to handle the date logic.

**Comment by jobenjada** [comment]
hey @Arian1192 we're currently shipping advanced logic which gives you a lot more flexibility including the following options
<img width="144" alt="image" src="https://github.com/user-attachments/assets/925fc20c-3c6d-457d-ae57-5d1fcb4ea959">


Here's a complete overview of whats going to be possible:
<img width="965" alt="image" src="https://github.com/user-attachments/assets/2883bf4a-d89a-40b3-bd7e-d5d1aeb755b5">

We're working hard to get it merged before the end of the week :)
