### ISSUE TITLE
[BUG] New Survey Button Visible to Viewers

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#3062]
### Issue Summary

Users with the role "Viewer" should not have the option to add surveys. Currently, the header displays a "New Survey" button for all users, including those with Viewer roles. When a Viewer tries to create a survey on the template overview page, they encounter a loading spinner that never resolves.
![image](https://github.com/user-attachments/assets/21b0e755-a5fe-4ddf-bbe4-9d80b24b4b8d)
![image](https://github.com/user-attachments/assets/7df3f426-7bdc-4463-b66a-23d18aed41c4)

### Steps to Reproduce

1. Log in as a user with the "Viewer" role.
2. "New Survey" (Plus) button visible in the header.
3. Click the "New Survey" button.
4. On the template overview page, attempt to create a survey.

### Expected behavior

- `TopControlButtons` Component:
Update the component to only show the "New Survey" button to users who have edit rights.
- Template Overview Page:
In `/apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/templates/page.tsx`, display an error message when a user with the Viewer role attempts to access the page.
- Improve the error message for users with Viewer rights attempting to perform restricted actions.
Current message: "This resource doesn't exist or you don't have the necessary rights to access it."
Proposed message: "You have the user role Viewer and cannot access this resource." or "This resource doesn't exist or you don't have the necessary rights to access it. Current user role: Viewer."

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v2.4.3
```

**Comment by jobenjada** [comment]
Good catch, we'll ship a fix asap :)

**Comment by gupta-piyush19** [comment]
Hi @jonas-hoebenreich,
I've removed the button from the topbar for the viewer role users and added the redirect from the template page to the survey listing page.
Regarding the error message, We have a reusable error component, which is being used for many different use cases(if a resource is deleted, if the user doesn't have permission to access the resource, if the API call fails, etc.). It would be better if we fix this in a separate PR 😊

**Comment by jonas-hoebenreich** [comment]
Ok, thanks 🙏 
Yes, improving the error messages it probably a separate task that needs some refinement to make sure that users get useful error messages while not compromising security
