### ISSUE TITLE
[BUG] Input Fields in a Form should be auto-focussed

### ISSUE THREAD

**Issue by sachinjain024** [formbricks/formbricks#3089]
### Issue Summary

- When I submit any input field, the form loads up the next field but the input isn't focussed so I have to click manually and then start typing

### Steps to Reproduce

Here is a Requestly Session to showcase the Issue - https://app.requestly.io/sessions/saved/2O20CoXLlpPT6Bc5w1Q9

### Expected behavior

Input should be auto-focussed similar to Typeform

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: MacOS

Please find my browser, OS and other Information in the Session - https://app.requestly.io/sessions/saved/2O20CoXLlpPT6Bc5w1Q9
```

**Comment by ag-gaphp** [comment]
This is working for me, confirmed both in v2.5.1 and v2.5.3. I confirmed in v2.5.1 on both Arch and Windows 10 using Firefox.

Video is v2.5.3 in Arch/Firefox:

https://github.com/user-attachments/assets/26e2c587-6e8a-4440-933a-a15b558f4ad3
