### ISSUE TITLE
[BUG] Can't login. Password not recognised and no option to reset.

### ISSUE THREAD

**Issue by JamesGrant88** [formbricks/formbricks#3105]
### Issue Summary

Not sure what has gone on but I can no longer log in to my form bricks user area. I had been signed in on my laptop with password saved in keychain but any device I use is now logged out including my laptop. All passwords I can think of, including the one in keychain aren't working.

I've got the docker container set to allow password reset but the option isn't there. 

I have reinstalled the image and pulled the latest version.

### Steps to Reproduce

Tried everything I can, different browsers etc.

### Expected behavior

Able to either log in or reset password.

### Other information

Using a portioner stack on a Synology NAS.

### Screenshots

![Screenshot 2024-09-05 at 23 45 07](https://github.com/user-attachments/assets/cff386e8-8b31-4f12-9022-759d833a40f7)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Synology NAS
- Node:
- npm:
```

**Comment by jobenjada** [comment]
mhh, that's odd. @Dhruwang will try to help you debug. Are you in our Discord? formbricks.com/discord

**Comment by Dhruwang** [comment]
Hey @JamesGrant88 , did you tried changing value of `PASSWORD_RESET_DISABLED` to 0 in your `docker-compose.yml` ? 😊


![Screenshot 2024-09-06 at 1 00 16 PM](https://github.com/user-attachments/assets/8d265f7f-4110-42f4-9867-1d384cd22023)

**Comment by JamesGrant88** [comment]
> Hey @JamesGrant88 , did you tried changing value of `PASSWORD_RESET_DISABLED` to 0 in your `docker-compose.yml` ? 😊
> 
> ![Screenshot 2024-09-06 at 1 00 16 PM](https://private-user-images.githubusercontent.com/67850763/365074938-8d265f7f-4110-42f4-9867-1d384cd22023.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzM2MjgsIm5iZiI6MTcyNTYzMzMyOCwicGF0aCI6Ii82Nzg1MDc2My8zNjUwNzQ5MzgtOGQyNjVmN2YtNDExMC00MmY0LTk4NjctMWQzODRjZDIyMDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE0MzUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0N2NmMDcyMDZhYjdjMmJiZTM2NTVhZjc1MzQwNTIyNDI0OGQxN2Y0N2FlNjQ4NzE1OWY1OWIwYjU5YWY5YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rr1-p5DXDrhrVE-7lOn10oiGhRUAvT8J5JLdY8y6Kd0)
> 
> Also you would see the option to reset your password, only when password input field is focused
> 
>  Screen-Recording-2024-09-06-at-1.04.20.PM.mp4

Thank you!

I feel so stupid. In my config file, it says to set to 1 to enable reset (has this changed recently?) - anyway I had tried 0 just in case before but didn't realise the password field has to be highlighted and I assumed when it returned wrong password it would say about forgot password there :)
