### ISSUE TITLE
[BUG] Upgrade to v2.4.3 from v2.2.2

### ISSUE THREAD

**Issue by sommarnatt** [formbricks/formbricks#3109]
### Issue Summary

Skipped migration in 2.3 as it didnt apply to us. Ran upgrade to 2.4.3 image and then migrations.
Formbricks seems to be ok but threw this error during migration.

### Steps to Reproduce

```
Status: Downloaded newer image for ghcr.io/formbricks/data-migrations:v2.4.0

> @formbricks/database@0.1.0 data-migration:v2.4 /app/packages/database
> pnpm data-migration:segments-cleanup && pnpm data-migration:multiple-endings && pnpm data-migration:simplified-email-verification


> @formbricks/database@0.1.0 data-migration:segments-cleanup /app/packages/database
> ts-node ./data-migrations/20240712123456_segments_cleanup/data-migration.ts

starting migration
Deleted 0 segments with no surveys
Found 0 app surveys without a segment
Migration completed

> @formbricks/database@0.1.0 data-migration:multiple-endings /app/packages/database
> ts-node ./data-migrations/20240801120500_thankYouCard_to_endings/data-migration.ts

/app/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
data-migrations/20240801120500_thankYouCard_to_endings/data-migration.ts(28,13): error TS2322: Type '{ id: string; redirectUrl: string | null; thankYouCard: unknown; }[]' is not assignable to type 'Survey[]'.
  Type '{ id: string; redirectUrl: string | null; thankYouCard: unknown; }' is not assignable to type 'Survey'.
    Types of property 'thankYouCard' are incompatible.
      Type 'unknown' is not assignable to type '{ enabled: boolean; title: string; description: string; } | null'.

    at createTSError (/app/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/app/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/app/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/app/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {
  diagnosticCodes: [ 2322 ]
}
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

```

### Expected behavior

Expected to get an output without errors.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by pandeymangg** [comment]
Hey! @sommarnatt thanks for opening this issue, we'll look into it and get back 😊

**Comment by jobenjada** [comment]
hey mate! We'll look into it next week, sorry for the inconvenience!

**Comment by pandeymangg** [comment]
hey! @sommarnatt could you pls tell me the exact steps that you did to debug this better? I tried going from v2.2.2 directly to v2.4.3, and also making some surveys in v2.3.0 in between (without running the migration) but I couldn't reproduce the error unfortunately 😞 

Were you using app survyes? or was it just website surveys before you ran the migration?

**Comment by sommarnatt** [comment]
@pandeymangg 
Yes, only using app surveys (and only 3) - they didnt have ending cards, I tried adding them to see if it would make any difference but that was a no go.
Any database entries I should be looking for?

**Comment by pandeymangg** [comment]
> @pandeymangg Yes, only using app surveys (and only 3) - they didnt have ending cards, I tried adding them to see if it would make any difference but that was a no go. Any database entries I should be looking for?

got it, thanks for the reply 😊 
I'll debug this furthur, seems like this could have been caused by the thank you card not being there, will keep you posted 👍

**Comment by mattinannt** [comment]
With the current approach for data migrations users unfortunately need to run all data migrations from the version they are upgrading from. We are currently working on a new approach for data migrations that solves this.
