### ISSUE TITLE
[BUG] Notes not appearing

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3116]
### Issue Summary

When a note is added, it's not displayed in the notes section

### Steps to Reproduce

1. Create a response
2. Try to add a note
3. where is the note huh? where is it? look for the note!

https://github.com/user-attachments/assets/744c181f-9d44-49ec-bda9-e8ecac24aa8a

### Expected behavior

find the note

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mdm317** [comment]
@jobenjada 
Can I give it a try? If not, I’ll look for another issue.
