### ISSUE TITLE
[BUG] Display Creation Fails with invalid CUID 🚨 

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#3128]
### Issue Summary

I'm currently investigating why the display count is broken for some surveys.
I will take the survey `ign1eyhugb9xouy1986peg0m` as an example. The cuid of this survey has been generated by Formbricks but the validation within `ZDisplayCreateInput` fails.

https://github.com/formbricks/formbricks/blob/c53b58c64f8b9fcefa9c31694913077e09a7b96b/packages/types/displays.ts#L15

### Steps to Reproduce

1. Send the following CURL request:
```
curl --request POST \
  --url https://app.formbricks.com/api/v1/client/cm0xtgl0u000008jv560ed7qq/displays \
  --data '{"surveyId":"ign1eyhugb9xouy1986peg0m"}'
```
(Note that the environmentID `cm0xtgl0u000008jv560ed7qq` does not exist and I just generated it on https://www.getuniqueid.com/cuid)
Request fails with the following error message although `ign1eyhugb9xouy1986peg0m` is the id of a survey in our instance:
```
{
	"code": "bad_request",
	"message": "Fields are missing or incorrectly formatted",
	"details": {
		"surveyId": "Invalid cuid"
	}
}
```

2. The cuid validation works when testing it with a different cuid:
```
curl --request POST \
  --url https://app.formbricks.com/api/v1/client/cm0xtgl0u000008jv560ed7qq/displays \
  --data '{"surveyId":"cm0xtgl0u000008jv560ed7qq"}'
```
This request will lead to an internal server error (but the request validates successfully)
```
{
	"code": "internal_server_error",
	"message": "\nInvalid `prisma.display.create()` invocation:\n\n\nAn operation failed because it depends on one or more records that were required but not found. No 'Survey' record(s) (needed to inline the relation on 'Display' record(s)) was found for a nested connect on one-to-many relation 'DisplayToSurvey'.",
	"details": {}
}
```

### Expected behavior

When providing a valid environment ID and a valid survey ID the request validates.

When providing an invalid environment ID or invalid survey ID the request does not validate.

Currently you can create a Display for any survey (even with a bogus environment ID) and when providing a bogus survey ID it still tries to create the Display (which leads to an internal server error).

### Other information

I guess that `prisma` sometimes generates cuids that are marked as invalid by `zod`.

**Please fix as soon as possible as this is a major bug for us.** ‼️ 

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v2.5.1
```

**Comment by jobenjada** [comment]
hey Jonas! Thanks for the report, we'll look into it and get back asap
