### ISSUE TITLE
[FEATURE] Make Matrix types wider on Desktops

### ISSUE THREAD

**Issue by ag-gaphp** [formbricks/formbricks#3140]
### Is your feature request related to a problem? Please describe.

Users of our surveys conveyed how difficult it is to pick options in the matrix questions on Desktop, due to the width.

I also have frustrations with it since you have to constantly scroll left/right to read the row's text and pick one of the last options.

IMO, the row text is also clunky looking due to being split up into several lines when there is plenty of real-estate on the screen for most of it to fit without scrollbars. It's fine if the row labels break to newlines, but the width shouldn't be limited to 50px.

### Describe the solution you'd like

Allow the width of the Matrix containers to expand to fit its content better

### Additional context

Example matrix from one of my surveys. There are 6 columns in this one, but we have another matrix with 10 columns.

Note the constricted row labels and imagine being a less-than-savvy computer user having to scroll around all the time just to pick an option. Most people don't know that SHIFT+Scroll will scroll horizontally to make it easier, but even using that it is cumbersome to fill out the matrices.

![image](https://github.com/user-attachments/assets/9ba9bd82-3b87-4ef3-899c-01f6141dc3a3)

I would expect that container to expand way more to the left/right of the screen since there is plenty of room available.

**Comment by jobenjada** [comment]
hey Alex,

we're planning to make surveys more versatile in layout incl. adding more than 1 question per page. This includes what you're requesting.

Until than, you can use the Embed Mode to get a full-screen survey without any cards:

https://formbricks.com/docs/link-surveys/embed-surveys#emebd-mode

We have a few more pressing things on the roadmap but will get to this as well :)

**Comment by ag-gaphp** [comment]
Awesome, since it's on your radar already I'll close this out

@jobenjada is there a public facing version of your roadmap by chance?
