### ISSUE TITLE
[FEATURE] 'Back to Top' button on Summary screen

### ISSUE THREAD

**Issue by ag-gaphp** [formbricks/formbricks#3142]
### Is your feature request related to a problem? Please describe.

Scrolling through data can be sped up a bit by adding a floating "Back to Top" button on the summary page. This way, if I am viewing one of the questions near the end of my survey and decide I need to add a filter, I can very quickly get back to the top of the page without affecting any other filters I might have applied.

### Describe the solution you'd like

Floating 'Back to Top' button on Summary page

### Describe alternatives you've considered

A more complicated alternative could be to add a few floating buttons that not only allow you to scroll back to the top quickly, but also apply filters directly from the location you are on the page.

Although that would be nice, I think at least a scroll to top button is something that could be useful for everyone.

**Comment by jobenjada** [comment]
Thanks for opening the issue, good idea! Do you wanna pick it up @ag-gaphp ? :)

**Comment by ag-gaphp** [comment]
Hmmm. I can certainly take a crack at it! I'm a backend guy that only knows the bare minimum of node, so no guarantees it'll be pretty 😅

**Comment by alok14598** [comment]
Hello @jobenjada and @ag-gaphp, I was looking into the Issue and I found it very simple, but no updates from many days, so I think I can fix it, Can I take it Up ??
I was able to setup this project locally, and made a very small ICON change locally, I will be posting the video here, I have done it to SHOWCASE my skill that I can take this up, 

https://github.com/user-attachments/assets/2ad1d137-ae93-4def-8553-c4ff9bd672a0


https://github.com/user-attachments/assets/daa1a7f8-fda3-485c-a634-9420df4470f0

**Comment by alok14598** [comment]
HI @ag-gaphp Request you to please provide the exact route or path or Page you are expecting this "Back to Top Button" , and If you can post a video that will be helpful, Thankyou

**Comment by jobenjada** [comment]
hey @alok14598 this is meant for the Summary page, not the survey editor.

I've assigned you, please open a PR within 48h

**Comment by alok14598** [comment]
Created a PR, Please have a review and provide feedback

**Comment by alok14598** [comment]
Thankyou
