### ISSUE TITLE
[FEATURE] Randomize row order for Matrix questions

### ISSUE THREAD

**Issue by filiabel** [formbricks/formbricks#3156]
### Is your feature request related to a problem? Please describe.

I think it would be nice to be able to randomize row order in matrix questions. This is already available for select question types.
It is very useful to not introduce any bias in your surveys.
![image](https://github.com/user-attachments/assets/cbe33ca2-3621-47a0-94eb-97316417b8a2)

### Describe the solution you'd like

Add the randomize order similar to select questions. 
![image](https://github.com/user-attachments/assets/c52dc915-c0b6-42f5-aded-041c6904f26e)

**Comment by jobenjada** [comment]
what do you need this for? 🤓

**Comment by filiabel** [comment]
@jobenjada One of the analysts making surveys want this feature to not introduce bias of any sorts. 
They have used SurveyMonkey previously where this is supported: https://help.surveymonkey.com/en/surveymonkey/create/matrix-rating-scale/ (see under additional options)

Please feel free to close the issue if it seems irrelevant 👌

**Comment by jobenjada** [comment]
hey! Not at all, just helpful for us to understand the requests better :)  It's a great issue for our upcoming community hackathon, I'll include and incentivize it starting 1st of October 🚀

**Comment by SaiSawant1** [comment]
Hey @jobenjada , is this up for grabs? I've got something working. Should I create a pull request now, or should I wait until October?

**Comment by jobenjada** [comment]
wait until october pls :)

**Comment by SaiSawant1** [comment]
\assign
