### ISSUE TITLE
[BUG] 52% Pixel File Size Due to Buffer Polyfill

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#3159]
### Issue Summary

The `website.umd.cjs` pixel file is larger than necessary at 54KB, with 52% of the file size coming from the Buffer polyfill, which is being imported from `packages/api/client/storage`. Since the pixel does not require file upload functionality right away, this code can be relocated to the surveys package, where it's actually needed.

Proposal:

- Adjust the imports to prevent the inclusion of the Buffer polyfill in the website.umd.cjs pixel file.
- Consider adding `rollup-plugin-visualizer` to the vite config to help visualize the sources contributing to the file size. This plugin generates a visualization without modifying the compiled code, making it easier to identify unnecessary bloat.

Before (54KB):
![image](https://github.com/user-attachments/assets/1cacb412-99c3-4759-a022-7d7a68fd76aa)

After (26KB):
![image](https://github.com/user-attachments/assets/575975c9-d5e5-4e59-9aa8-9b4fa57576d3)

### Steps to Reproduce

1. Build the pixel using Vite.
2. Observe the resulting file size of website.umd.cjs.

### Expected behavior

The pixel file size should be reduced significantly by excluding the unnecessary Buffer polyfill.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich Thanks for bringing this up :-) Looping in @pandeymangg to evaluate this and come up with a solution :-)
