### ISSUE TITLE
[BUG] 50% scroll action doesn't trigger survey

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3170]
### Issue Summary

A user flagged that the 50% scroll option doesn't trigger surveys.

it works with a different trigger though.

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

trigger survey

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@Dhruwang Please investigate this issue and update this ticket if the bug is reproducable 😊
