### ISSUE TITLE
[BUG] Wrong Product Redirect

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#3171]
### Issue Summary

When sharing a link to a specific product the user is automatically redirected to the last visited product.
 product.https://github.com/formbricks/formbricks/blob/01ceaa13ec876cf9a862c0734bf5a099528e8fa0/apps/web/app/(app)/environments/%5BenvironmentId%5D/components/MainNavigation.tsx#L122 

### Steps to Reproduce

1. Open product, eg https://app.formbricks.com/environments/cm1f5ukud000008mhfnbv6g7m/surveys
2. Open the direct link for a different product, eg https://app.formbricks.com/environments/cm1f5vc7h000108mheo6eb6rw/surveys
3. User is redirected to https://app.formbricks.com/environments/cm1f5ukud000008mhfnbv6g7m/

### Expected behavior

User is only redirected to the last product when the environment id is not specified or invalid. It should also redirect the user directly to https://app.formbricks.com/environments/{environment}/surveys instead of just https://app.formbricks.com/environments/{environment}/.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v2.5.3
```

**Comment by jobenjada** [comment]
@gupta-piyush19 pls take into account when working on your current ticket :)

**Comment by gupta-piyush19** [comment]
Hey, @jonas-hoebenreich, I've shipped a fix for this. Can you please check if it's working fine for you?
Thanks for pointing out the bug  🙌

**Comment by jonas-hoebenreich** [comment]
Yes, seems to be working now :)
