### ISSUE TITLE
[🕹️] Build a template section for formbricks.com

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3192]
### What side quest or challenge are you solving?

Build a template section for formbricks.com

### Points

1500

### Description

Build a template library for formbricks.com

Objective: 
1. Copy the template folder we have in our main repo
2. Build an overview page on formbricks.com/templates
3. Build a subpage which is programmatically generated for each template e.g. formbricks.com/templates/nps

This subpage renders the current template using our survey packages and includes additional information around it, very similar to the best practices pages but programmatically for all our templates:

https://formbricks.com/interview-prompt

### [Apply here](https://app.formbricks.com/s/cm1nxig3k0001lsou303bih6h)

**Comment by RajuGangitla** [comment]
@jobenjada can you assign this issue to me

**Comment by RajuGangitla** [comment]
@jobenjada can you please assign this issue to me

**Comment by mohitjoping** [comment]
Hi @jobenjada, How have you been?
I did a couple of projects in nextJS and TypeScript.
Could you please assign this issue to me? I’m eager to get started and contribute to this project.

**Comment by jobenjada** [comment]
hey @mohitjoping Raju filled in the survey and commented first, so he'll work on it. Any of the other open issues or challenges interesting for you?

**Comment by mohitjoping** [comment]
can you assign me #3195 ?
which is writing an article on How to use Formbricks with Webflow.
