### ISSUE TITLE
[🕹️] Add on-page menu to blog layout

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3193]
### What side quest or challenge are you solving?

We currently do not have an on-page menu on blog articles like [this one](https://formbricks.com/blog/qualtrics-alternatives) or [this one](https://formbricks.com/blog/best-open-source-survey-software). However, we’d want that for better accessibility of the articles content. Needs to be responsive.

### Points

750

### Description

It should auto-generate the menu based on the h2 and h3 tags of the article. We have something similar in our docs app built by a contributor 🚀 

### [Apply here](https://app.formbricks.com/s/cm1nxig3k0001lsou303bih6h)

**Comment by jobenjada** [comment]
hey @SxxAq - looks like you've contributed to OS quite a bit so far - very cool!

Please ping me on Discord, then I'll give you access to the repo of our Landing page and you can get started 🚀

**Comment by aakashraj01** [comment]
@jobenjada , if this issue is still pending , can you assign it to me . I will quickly pick it up and close it  :)

**Comment by Anurag-Singh-Yadav** [comment]
can you assign to me

**Comment by Preetibansal08** [comment]
unassign
