### ISSUE TITLE
[🕹️] Article: How to survey sign ups in-app and get pinged on Slack

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3197]
### What side quest or challenge are you solving?

Article name:  How to survey sign ups in-app and get pinged on Slack

### Points

1500

## This gives A LOT of points because writing a high quality technical article with good instructions, screenshots, etc. can take a full day or more 🤓

Here is the [Formbricks Writing Guide](https://formbricks.notion.site/FormTribe-Content-Writing-Guide-f6464ee837364785afdc6c88ef8bfd51?pvs=74)

### [Apply here](https://app.formbricks.com/s/cm1nxig3k0001lsou303bih6h)

**Comment by thefool76** [comment]
hey Jobenjada can you please assign it.

**Comment by RajuGangitla** [comment]
@jobenjada is it not up for grabs ?

**Comment by thefool76** [comment]
@jobenjada is it open for work would like to work on it.

**Comment by Khaan25** [comment]
@jobenjada Can I work on this?
