### ISSUE TITLE
[🕹️] Article: How to survey only power users in your NextJS app

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3199]
### What side quest or challenge are you solving?

Article: How to survey only power users in your NextJS app

### Points

1500

## This gives A LOT of points because writing a high quality technical article with good instructions, screenshots, etc. can take a full day or more 🤓

Here is the [Formbricks Writing Guide](https://formbricks.notion.site/FormTribe-Content-Writing-Guide-f6464ee837364785afdc6c88ef8bfd51?pvs=74)

### [Apply here](https://app.formbricks.com/s/cm1nxig3k0001lsou303bih6h)

**Comment by manya706** [comment]
\assign

**Comment by manya706** [comment]
hey @jobenjada ! could you assign this to me?

**Comment by abhayofc** [comment]
@jobenjada can you assign it to me,
here are some of my articles: [Link](https://abhayvis.medium.com/)

**Comment by jobenjada** [comment]
please comment with your previous experience or other examples of why you're up for this article to get assigned :)

**Comment by codermks** [comment]
here are some of the articles [LINK](https://dev.to/manish7107)

**Comment by DeepaPrasanna** [comment]
may I work on this? you can check my article [here](https://annee.vercel.app/blog/rate-limiter)

**Comment by DeepaPrasanna** [comment]
> may I work on this? you can check my previous work on an article [here](https://annee.vercel.app/blog/rate-limiter)

Hello @jobenjada may I have a chance to work on this?
