### ISSUE TITLE
[🕹️] Article: How to add a contact form to any website and get notified for free

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3200]
### What side quest or challenge are you solving?

Article: How to add a contact form to any website and get notified for free

### Points

1500

## This gives A LOT of points because writing a high quality technical article with good instructions, screenshots, etc. can take a full day or more 🤓

Here is the [Formbricks Writing Guide](https://formbricks.notion.site/FormTribe-Content-Writing-Guide-f6464ee837364785afdc6c88ef8bfd51?pvs=74)

**Comment by Suraj-kumar00** [comment]
Hi @jobenjada, how have you been?
Let's do this. 
You can check here my blogs: blog.devsuraj.me

**Comment by jobenjada** [comment]
@Suraj-kumar00  its yours :)

**Comment by thefool76** [comment]
Hey @jobenjada is open for work? Please assign it thanks

**Comment by Suraj-kumar00** [comment]
Hi @jobenjada, how have you been?
What is this behaviour, I was assigned this issue on working on it but you have assigned to someone else? Is this a community standard?

**Comment by Vardhaman619** [comment]
@Suraj-kumar00 I wasn’t aware that you were working on this issue since it had no assignee when I checked. To avoid any confusion, please make sure to assign it to yourself. I’ve unassigned myself, so go ahead and assign it to yourself.

**Comment by Suraj-kumar00** [comment]
Hi @Vardhaman619 actually @jobenjada assigned it to me you see on this issue conversation.
Anyway it's okay.

@jobenjada can you please assign again?

**Comment by jobenjada** [comment]
the submission from @geraldmaboshe is good - will close this once the article is live :)

**Comment by geraldmaboshe** [comment]
Hello @manasCodes13, sorry this issue has already been worked on. It will be closed as soon as the article is published

**Comment by manasCodes13** [comment]
ok sure @geraldmaboshe I will unassign myself from it then.

**Comment by adityatakharya** [comment]
@nikhiludayy it has already been worked on.

**Comment by Anjalisharma3463** [comment]
@jobenjada please assign this issue to me. I will try to solve this.🤗

**Comment by Aditya-PS-05** [comment]
@jobenjada 
Where should I include the created article ? By default, I am considering to add it under the best practices section.

**Comment by Aditya-PS-05** [comment]
@jobenjada 
Please review my pull request.

**Comment by Aditya-PS-05** [comment]
Is the issue solved by a pull request or it's unsolved but still closed.
