### ISSUE TITLE
[🕹️] Article: Supabase + NextJS: How to run a targeted in-app survey for free

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3202]
### What side quest or challenge are you solving?

Article: Supabase + NextJS: How to run a targeted in-app survey for free

### Points

1500

## This gives A LOT of points because writing a high quality technical article with good instructions, screenshots, etc. can take a full day or more 🤓

Here is the [Formbricks Writing Guide](https://formbricks.notion.site/FormTribe-Content-Writing-Guide-f6464ee837364785afdc6c88ef8bfd51?pvs=74)

### [Apply here](https://app.formbricks.com/s/cm1nxig3k0001lsou303bih6h)

**Comment by Dumebii** [comment]
Hi @jobenjada, I'd like to work on this. Thank you.

**Comment by jobenjada** [comment]
@Dumebii how is it going? 🤓

**Comment by Dumebii** [comment]
Hi @jobenjada, going well. Had a bit of an issue integrating formbricks, but I'm good now. Article should we ready today or tomorrow.
Thanks for checking in!

**Comment by Dumebii** [comment]
Hi @jobenjada, you can check out the first draft of the [article](https://dev.to/dumebii/supabase-nextjs-how-to-run-a-targeted-in-app-survey-for-free-using-formbricks-4f6e-temp-slug-8840466).

Let me know what you think and if there are any corrections to be made.

**Comment by Khaan25** [comment]
@jobenjada, Is this still open? Can I write a article on it?
