### ISSUE TITLE
[🕹️] Remove scrollbars from rich text window

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3203]
### Is your feature request related to a problem? Please describe.

In the survey editor we use Rich Text editor and the windows has x and y scrollbars
<img width="678" alt="image" src="https://github.com/user-attachments/assets/f93301e6-be4f-4e38-a643-80dc6efafa28">

### Describe the solution you'd like

Remove the scrollbars.

Add a max-height and add scroll when it's hit

### Additional context

you can self-assign on Oct 1st

**Comment by Prathamesh0901** [comment]
I would like to work on this issue.

**Comment by smritidoneria** [comment]
Hey @jobenjada , I would like to work on this.
