### ISSUE TITLE
[🕹️] Duplicate Toasts on Publish Survey

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3204]
### Issue Summary

Almost all the times when publishing a survey we see the success toast twice.

Investigate why, don't just treat the symptom with a hack 😉

### Steps to Reproduce

1. Create a new survey, publish it
2. Check the toast messages bottom left

### Expected behavior

Only show once.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by smritidoneria** [comment]
Hey @jobenjada , I would like to work on this

**Comment by smritidoneria** [comment]
Hey @maintainers, I am attached the pr for this issue kindly review it

**Comment by jobenjada** [comment]
@jobenjada will do so asap, definitely today :)
