### ISSUE TITLE
[🕹️] Docs: Create one page for each question type we support

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3207]
### What side quest or challenge are you solving?

Docs: Create one page for each question type we support

### Points

750

### Description

Create a docs page for each question type we currently support.

1. Create a new dropdown in the Navigation under Core Features called "Question Types". Add all of the new pages there (so in `/global/` )
2. Make sure all pages follow the same structure
3. Explain all features specific to each question type
4. Add both a screenshot of the question form (left side) as well as the question itself in the survey (right side). Make sure the content in the questions is somehow related to Customer Experience surveys.
⚠️ All images need to be in .webp - compress and convert using tinypng.com

That should be it :)

### Provide proof that you've completed the task

open a PR for it

**Comment by Ionfinisher** [comment]
Hi @jobenjada, I would love to work on this. can I have more context please?

**Comment by Vanshii** [comment]
Hi @jobenjada can you please assign i want to work on this.

**Comment by jobenjada** [comment]
Big one @syedbarimanjan - excited to see your submission :)

**Comment by marwinburesch** [comment]
Cheers, looking forward to it :) curious how tough this one will be

**Comment by jobenjada** [comment]
@marwinburesch just saw that the auto reminder comes after 12h, not 36. I'll update that now but not sure if the github app will still unassign you automatically. Mind opening a draft PR within the next 12h? Doesn't have to have a lot of content yet 🙌

**Comment by Shaik-mohd-huzaifa** [comment]
Assign me this one please?

**Comment by jobenjada** [comment]
This is up for grabs again!

**Comment by jobenjada** [comment]
https://github.com/formbricks/formbricks/pull/3285

feel free to use this content here to get started ⬆️

**Comment by adityadeshlahre** [comment]
Hey Everyone don't pick this issue up I am working on this couldn't get assigned due to some bug of the bot :slightly_smiling_face: Thank You for understanding
