### ISSUE TITLE
[🕹️] Fix template search

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3208]
### Issue Summary

Currently, the search isn't working proplery. If you search for "NPS" you don't find the Net Promoter Score template even though it contains "NPS" in the title

### Steps to Reproduce

1. Go to template overview
2. Search for NPS. Then search for "Net" and you'll find it

### Expected behavior

Search complete template title string for the search input

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by NawinKumarSharma** [comment]
@jobenjada  please check my pr #3230

**Comment by NawinKumarSharma** [comment]
@jobenjada please check my pr #3243
