### ISSUE TITLE
[🕹️] Fix height & width of survey preview when loading

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3210]
### Issue Summary

when the survey editor is loading, the preview window looks off because the survey package wasn't loaded yet:

<img width="711" alt="image" src="https://github.com/user-attachments/assets/cf5bcf48-b574-49ef-9c2f-d68f1da9acc1">

### Steps to Reproduce

1. Throttle your loading speed in Inspect tools
2. load survey editor
3. look at the right side

### Expected behavior

It should max out height and width to look less broken

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Vanshii** [comment]
hey i would love to work upon this
