### ISSUE TITLE
[🕹️] Fix React Email preview of NPS question

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3211]
### Issue Summary

If you have a NPS question as the first question in your survey and you want to embed it in an email, it looks like this:
<img width="761" alt="image" src="https://github.com/user-attachments/assets/ae277f5d-37c0-4549-bc60-b65fcbb2ef31">

A rating question on the other hand looks like this:
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/c149363d-b936-4fc8-9039-1afe5c9769ad">

### Steps to Reproduce

1. create a survey with first question NPS or rating
2. Go to "Embed" to see email preview

### Expected behavior

- Add rounded corners on :first and :last of rating and NPS
- Make NPS full width
- Remove double borders of NPS question

Please make a video that everything works well in your PR

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by lakshay-saini-au8** [comment]
@jobenjada I would like to work on this issue 
Please assign

**Comment by jobenjada** [comment]
@Pushan2005 are you still working on this? :)

**Comment by Pushan2005** [comment]
> @Pushan2005 are you still working on this? :)

Yes I am, had my exams going on so could no make as much progress as i had hoped

**Comment by jobenjada** [comment]
all good just didn't want it to go stale :)

**Comment by Pushan2005** [comment]
> Assigned to @Pushan2005! Please open a draft PR linking this issue within 48h ⚠️ If we can't detect a PR from you linking this issue in 48h, you'll be unassigned automatically 🕹️ Excited to have you ship this 🚀

Hey could someone please verify if https://github.com/formbricks/formbricks/pull/3248 is a valid draft PR as requested by @oss-gg
