### ISSUE TITLE
[🕹️] Update CSAT template

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3212]
### Is your feature request related to a problem? Please describe.

Our CSAT template is fairly simple. Instead, we want to include a number of different questions and the user then deletes the ones they don't want.

### Describe the solution you'd like

[This one is a good one for inspiration](https://www.surveymonkey.com/templates/customer-satisfaction-survey-template/)

### Describe alternatives you've considered

In your PR, please add video proof that your template does not break the editor cause it fails to meet validation

**Comment by Vanshii** [comment]
Hey @jobenjada  can you please assign

**Comment by jobenjada** [comment]
reviewing asap, thanks for your contribution :)
