### ISSUE TITLE
[🕹️] Loading skeletons for Configuration pages

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3213]
### Is your feature request related to a problem? Please describe.

We currently don't have a loading skeleton for the product config pages

### Describe the solution you'd like

Add one :)

### Task
1. Look at how we handled it on the People page with the tabs for Segments and Attributes. Use the same approach to not reload the tab bar for a better effect
2. For each of the subpages (general, look & feel, etc..) it's enough to reuse the same loading.tsx of a single card

Please familiarize yourself with best practices of loading skeletons in NextJS before working on this task 🤓

**Comment by NawinKumarSharma** [comment]
hey @jobenjada , can i work on this? please assign

**Comment by smritidoneria** [comment]
hey @jobenjada , I want to work upon this

**Comment by jobenjada** [comment]
@PratikAwaik is backkkkk! Good to see you around again :D
