### ISSUE TITLE
[🕹️] Unify all context menus UI

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3214]
### Is your feature request related to a problem? Please describe.

Our contact menus look slightly different throughout the app:

<img width="706" alt="image" src="https://github.com/user-attachments/assets/b36d9ce8-3402-4195-98fb-38846d9986e6">

The differ in: 
- font
- strokeWidth of icons
- roundeness
- border
- border color
- shadow

### Describe the solution you'd like

The should alllll look the same!

Like this:
<img width="297" alt="image" src="https://github.com/user-attachments/assets/66a3f30c-788a-4d91-9b83-ab08a6f3bfac">

### Attention
When you refactor, please make sure that you follow the DRY principle. Don't add the same CSS to all instances of the dropdown. Instead, style the base Radix component correctly and remove all overwriting CSS 💪

**Comment by lakshay-saini-au8** [comment]
@jobenjada Please assign

**Comment by Vanshii** [comment]
Please assign

**Comment by adarshmalviya12** [comment]
@jobenjada I tried the project setting up locally multiple times even with gitpod. But I cannot do so you can assign this issue to someone else.  I will try with the new issue if my setup is done.

**Comment by adityadeshlahre** [comment]
Hey @jobenjada would like to get it assigned :slightly_smiling_face: 
Thank You
/assign

**Comment by SaiSawant1** [comment]
Hey @adarshmalviya12 , you can unassign yourself. Pretty sure their is  option for that next to your name in the Assignees
