### ISSUE TITLE
[🕹️] Replace `-brand` with `-brand-dark`

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3215]
### Is your feature request related to a problem? Please describe.

We have a few places throughout the app where we still use the old `-brand` color

### Describe the solution you'd like

Find them and replace them with `-brand-dark`

**Include before:after screenshots for each change that you make in the PR description!**

**Comment by theavitw** [comment]
I will do this

**Comment by NawinKumarSharma** [comment]
@jobenjada , please check the pr #3229 !

**Comment by jobenjada** [comment]
closing this issue already so you can pick up another one :)
