### ISSUE TITLE
[🕹️] Add paddings to "Your feedback is stuck" UI

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3216]
### Issue Summary

This issue was highlighted by a user, but couldn't reproduce: 

<img width="673" alt="image" src="https://github.com/user-attachments/assets/fbac7ba8-44c3-4489-ae6e-bcabf6e43a8a">

### Steps to Reproduce

see above

### Expected behavior

If you can reproduce it, pls investivate why the normal padding isn't applied here.

If you can reproduce it, you'll get 50 points for looking into it :)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by kalpesh0487** [comment]
Hello, could you please assign me this issue? I'd be happy to work on it.

**Comment by Dhruwang** [comment]
Hey @prajyot004 , did you solve this ? :)

**Comment by prajyot004** [comment]
@Dhruwang not yet

**Comment by jobenjada** [comment]
up for grabs :)
