### ISSUE TITLE
[🕹️] Rework Survey Summary CTA bar

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3217]
### Is your feature request related to a problem? Please describe.

Currently, we have these CTAs:
<img width="461" alt="image" src="https://github.com/user-attachments/assets/1861e217-1f00-4d3a-af1b-e2f677bbedae">

### Describe the solution you'd like

Update as follows:

<img width="1006" alt="image" src="https://github.com/user-attachments/assets/21b7b9f6-68a6-4efc-a85a-e3da93a2a528">

Embed: Opens the Embed modal
<img width="1077" alt="image" src="https://github.com/user-attachments/assets/8d81265e-8bfd-42c9-b756-ae986e8bc646">

Preview: Opens survey link in new tab with `preview=true` appended to the end

Edit: unchanged, opens editor

Context menu options:
- Copy survey link *CopyIcon* → copy URL to clipboard and show success Toast
- Send to panel *PeopleIcon* → Open modal with Panel
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/8cb795b6-090f-407d-912f-4c497fbc1acd">
- Configure alerts *BellIcon* → Forward to `/environments/${envId}/settings/notifications`

Later on, we'll add "Reset survey" here and more

---

Please use `/assign` to assign the issue to yourself if you want to work on it 😊

**Comment by smritidoneria** [comment]
hey, I want to work upon this issue

**Comment by Vanshii** [comment]
hey, I want to work upon this issue
