### ISSUE TITLE
[🕹️] Align date picker look & feel

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3218]
### Is your feature request related to a problem? Please describe.

In the Response Options we have Schedule and Close survey on specific date:
<img width="592" alt="image" src="https://github.com/user-attachments/assets/e6b81c38-c512-4308-80be-dd141e773da2">

The date picker looks broken:

<img width="377" alt="image" src="https://github.com/user-attachments/assets/e5e76809-2430-4598-9a76-e7489c9efaeb">

In the survey editor, we use the same package but with a different config:
<img width="478" alt="image" src="https://github.com/user-attachments/assets/4cfc7203-769b-466d-abbb-2b099688e86b">

### Addition

The date picker in the date range picker on the summary page also look broken, please fix as well :)

### Describe the solution you'd like

Align the date pickers by making the on in the survey editor look and feel like the one in the survey package.

**Comment by adarshmalviya12** [comment]
I want to work on this. Please assign this to me.

**Comment by theavitw** [comment]
Can I work on this?

**Comment by theavitw** [comment]
\assign

**Comment by NawinKumarSharma** [comment]
hey @jobenjada ,can you assign me?

**Comment by jobenjada** [comment]
starting tomorrow guys! :)

**Comment by smritidoneria** [comment]
hey @jobenjada , I want to work upon this issue

**Comment by mattinannt** [comment]
Please use `/assign` to assign the issue to yourself if you want to work on it 😊

**Comment by jobenjada** [comment]
up for grabs again :)

**Comment by SaiSawant1** [comment]
hey @jobenjada ,
does this look good
![swappy-20241010_203929](https://github.com/user-attachments/assets/354606e9-709b-4cfb-8207-a04f1650975c)

this is what it looks like now
![swappy-20241010_203936](https://github.com/user-attachments/assets/bebabd60-2a2e-44d5-8979-da85ba594693)

This isn't done yet, just wanted to know if I am going in correct direction.

**Comment by AkashJana18** [comment]
Hey @SaiSawant1 Have you resolved this issue ?
If not I would like to give it a try, please unassign yourself

**Comment by SaiSawant1** [comment]
> Hey @SaiSawant1 Have you resolved this issue ?
> 
> If not I would like to give it a try, please unassign yourself

I have created a pr but it's not reviewed yet. So technically yeah I have resolved this from my side just waiting for review.
