### ISSUE TITLE
[BUG] Keyboard Unexpectedly Opening on Mobile Devices

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#3239]
### Issue Summary

On mobile devices, the keyboard is unexpectedly opening for some questions, even when there is no immediate need for user input. We observed this behavior in a multi select question, below you find a video where it happens for a rating question.

### Steps to Reproduce

1. Add a rating question to your survey.
2. Go through the survey on a mobile device.
3. Observe the keyboard opening unexpectedly.

### Expected behavior

The keyboard should only appear when the user actively has to enter text.

### Screenshots

https://github.com/user-attachments/assets/dc22b201-ffe3-40e5-85bd-af05363dac8c

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v2.5.3
- happens in Chrome, Safari & Firefox an mobile
```

**Comment by devcodes9** [comment]
Hi @jobenjada  @Dhruwang I am unable to reproduce this issue, I tried it on Android device(Oneplus Nord) and IOS device(Iphone 15) both. Am I missing something?

**Comment by jobenjada** [comment]
@jonas-hoebenreich any pointers?

**Comment by jonas-hoebenreich** [comment]
@devcodes9, can you try it with this survey? https://app.formbricks.com/s/cly48h6vo0c6w6r48gg5soaoc

**Comment by devcodes9** [comment]
@jonas-hoebenreich Yes, that does get reproduced on android phone (not on Iphone though)
