### ISSUE TITLE
[🕹️] Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by Jemeni11** [formbricks/formbricks#3254]
### What side quest or challenge are you solving?

Like & [Re-Tweet oss.gg Launch Tweet](https://x.com/ossgoodgame/status/1841019549183066552)

### Points

50 points

### Provide proof that you've completed the task

https://x.com/jemeni11_/status/1841442504094151060

**Comment by jobenjada** [comment]
looks good, adding to merge queue :)
