### ISSUE TITLE
[🕹️] Write listicle for oss.gg repos 

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3259]
### What side quest or challenge are you solving?

https://dev.to/jaysaadana/top-hacktoberfest-projects-to-contribute-to-in-2024-1811

write a similar article but listing all oss.gg repos. Mention about oss.gg at the beginning and the end of the article :)

### Points

750

### Provide proof that you've completed the task

Share the article on dev.to and the link here :) share it on your socials tagging all oss.gg repos

**Comment by adityadeshlahre** [comment]
- [x] Blog : https://dev.to/adityadeshlahre/hacktoberfest-side-hack-write-code-win-a-macbook-ps5-or-iphone-16-4h75

**Comment by Ionfinisher** [comment]
Dev.to blog post: [My article](https://dev.to/ion_finisher/hacktoberfest-ossgg-code-conquer-and-win-big-5931)

**Comment by adityadeshlahre** [comment]
> @adityadeshlahre can you unassign yourself please if you have submitted this.

sure @thefool76
