### ISSUE TITLE
[🕹️] Remove border from tab in Segment filter modal

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3263]
### Is your feature request related to a problem? Please describe.

<img width="607" alt="image" src="https://github.com/user-attachments/assets/031de7b1-ba89-4e94-84f5-1f136c2c7e86">

The border around the tabs looks off

### Describe the solution you'd like

Remove it :) please don't edit the root component though (we use it in many other spots)

**Comment by abhayofc** [comment]
I can't find this filter modal on the site, can you please tell the location (URL)?

**Comment by Pratham271** [comment]
I have already raised the pr for this

**Comment by abhayofc** [comment]
@Pratham271 Can you please share the screenshot of fix?
