### ISSUE TITLE
[🕹️] Incorrect error toast for ending card

### ISSUE THREAD

**Issue by Dhruwang** [formbricks/formbricks#3266]
### Issue Summary

When a survey with a faulty ending card is saved, it shows an incorrect error toast message saying `The note on the Redirect to Url 1 is missing` even though it is not of type redirect to URL

### Steps to Reproduce

1. Create a survey with end screen card
2. Erase headline from end screen card
3. Save the survey

### Expected behavior

Toast message should say "The note on the Ending card 1 is missing"

### Screenshots

<img width="866" alt="Screenshot 2024-10-03 at 9 32 09 AM" src="https://github.com/user-attachments/assets/03a9b325-646e-4203-abef-2018ccddaf14">

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Abhi-Bohora** [comment]
I'd like to take this if anyone is not working on this.

**Comment by Abhi-Bohora** [comment]
@ebe25 please pick this issue
