### ISSUE TITLE
GitPod is not been able to spin up due to some error caused in files.

### ISSUE THREAD

**Issue by Abhi-Bohora** [formbricks/formbricks#3270]
### Issue Summary

If we press the `open in GitPod` button and wait for some time to finish up the build process. Then we encounter errors in the middle and run will fail and exit. It is caused by the file `surveys/types.ts` and `surveys/validation.ts`. you can see in the screenshot.
![err-gitpod](https://github.com/user-attachments/assets/865964f1-a50d-41aa-802d-51bcd909e03f)
the 

### Steps to Reproduce

1. Click on `Open in GitPod`
2. Wait for build to finish

### Expected behavior

To be able to run build successfully and be able to visit: [http://localhost:3000](url) 

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@FurquanAnwer I assigned you to the issue :-)
