### ISSUE TITLE
[🕹️] Add an copy icon and functionality to all Code Snippets

### ISSUE THREAD

**Issue by nilesh-fatfatwale** [formbricks/formbricks#3276]
### Is your feature request related to a problem? Please describe.

In the Leave Your Engineers in Peace section there are two codes so I want to add a feature a copy icon and when a user click then it will copy all the text codes in each section NPM and HTMLclicks

### Describe the solution you'd like

this feature is handy when it comes to copying the entire code manually.
![image](https://github.com/user-attachments/assets/b1578d1b-0262-4bc7-853f-bd32bcccfbc6)

**Comment by jobenjada** [comment]
Hey Nilesh

please build it into our reusable Code View component so its available on all code views 🙌

**Comment by nilesh-fatfatwale** [comment]
Sure

**Comment by PratikAwaik** [comment]
@jobenjada is this related to homepage, because in product there's already a copy snippet icon

**Comment by tsahil01** [comment]
@jobenjada it's been 4 days. Can you assign me the task.

**Comment by Harsh-007-max** [comment]
@jobenjada please reassign the issue

**Comment by DeepaPrasanna** [comment]
Hey @PratikAwaik are you still working on this issue?  If not, may I take up :)
