### ISSUE TITLE
[BUG] Matrix Question preview and question editor not  synchronized

### ISSUE THREAD

**Issue by SaiSawant1** [formbricks/formbricks#3281]
### Issue Summary

In Matrix Questions while deleting the bottommost row the Editor and preview are in sync. However, when we delete from the top or middle there is inconsistency in survey preview and editor row options.

### Steps to Reproduce

1. Add a matrix question to your survey
2. remove the top or any middle element
3. check the survey preview and option on the editor 

### Expected behavior

The options on the preview and editor should be same

### Screenshots

![swappy-20241004_024348](https://github.com/user-attachments/assets/182a9255-4ac3-450c-9730-845ab61e9faf)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Arch Linux x86_64 
- Node: v21.4.0
- npm: 10.8.3
```

**Comment by jobenjada** [comment]
Thanks for opening the issue Sai! 

@Dhruwang pls have a look as you just worked on this :)
