### ISSUE TITLE
[🕹️] deleteSubmissionToolTip hidden behind Overlay

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#3286]
### Issue Summary

When trying to delete a survey that is still in progress you will see a tooltip saying "This response is in progress.". This tooltip is cut off and produces weird overflow issues.

### Steps to Reproduce

1. Start responding to a survey.
2. Go to the "Responses" tab of the survey.
3. Click on you response (that is still in progress).
4. Try to delete the response.
5. Tooltip is cut off

### Expected behavior

The tooltip is fully visible and not cut off.

### Screenshots

![image](https://github.com/user-attachments/assets/f1095775-b099-47ce-b50c-f7a9844f9e74)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- Chrome & Firefox on Desktop
```

**Comment by vidhikapadia2799** [comment]
@jonas-hoebenreich I would like to work on this issue.Can you please assign to me

**Comment by jobenjada** [comment]
/award 50

for finding the bug 🙌

**Comment by jobenjada** [comment]
whoops will remove one of these point transactions for finding the bug 😃
