### ISSUE TITLE
[🕹️] Write listicle for oss.gg repos

### ISSUE THREAD

**Issue by gazjones00** [formbricks/formbricks#3288]
### What side quest or challenge are you solving?

Write listicle for oss.gg repos

### Points

350

### Description

Create a list of all repos in the 2024 oss.gg Hacktoberfest

Asked to open this issue from @jobenjada

### Provide proof that you've completed the task

https://dev.to/gaz_dev/top-open-source-projects-to-contribute-to-in-the-ossgg-hackathon-2024-1kfi

**Comment by jobenjada** [comment]
thanks mate! :)
