### ISSUE TITLE
[🕹️] Increase card size for link surveys

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3293]
### Is your feature request related to a problem? Please describe.

There isn't really a need to squeeze **link surveys** in such a small card for link surveys:

<img width="1675" alt="image" src="https://github.com/user-attachments/assets/82328d53-d87e-43cf-aa47-dee63cf7c58f">

### Describe the solution you'd like

Increase the card size a bit for link surveys:

<img width="1669" alt="image" src="https://github.com/user-attachments/assets/d0e626f7-7920-4894-b8a8-41a7a6dabf7f">

check if increasing `max-w-md` to `max-w-lg` based on survey type works. If it's too wide, choose custom value `32rem`

**Comment by piyushgarg-dev** [comment]
Interesting Issue

**Comment by silentboy-07** [comment]
The current issue is that link surveys are displayed in a card that's too small, making them look cramped. I propose increasing the card size slightly for link surveys, either by adjusting max-w-md to max-w-lg or using a custom value of 32rem if necessary. I'd like to work on this task.

**Comment by Anjali655** [comment]
/assign

Please assign this task to me
Thanks
