### ISSUE TITLE
[BUG] Signup Process throws error for existing user

### ISSUE THREAD

**Issue by piyushgarg-dev** [formbricks/formbricks#3296]
### Issue Summary

When I try to log in with Google OAuth provider I get an error saying `An error occurred when logging you in \n
A user with this email exists already.` Although I am on the login page, this error is irrelevant in this context.

### Steps to Reproduce

1. Visit [Formbricks Login Page](https://app.formbricks.com/auth/login)
2. Clicked on `Continue with Google`
3. Complete the Google Auth Flow
4. Got the error `A user with this email exists already.`

### Expected behavior

If the user already exists, it should log me in without any error.

### Screenshots

https://github.com/user-attachments/assets/e55c11b5-1ddd-44e8-af1c-e99cfa01fc38

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: MacOS 15.0
- Node:
- npm:
```

**Comment by jobenjada** [comment]
Thanks Piyush! Big one, we'll look into it 🤓

/award 150

**Comment by vidhikapadia2799** [comment]
Hi @jobenjada , can you please assign this issue to me

**Comment by NitinPSingh** [comment]
hi @piyushgarg-dev , is this issue same as #2803 ?

**Comment by kalpesh0487** [comment]
Heyy @jobenjada, can you please assign this issue to me I would like to work on it.

**Comment by jobenjada** [comment]
up for self-assignment now :)
