### ISSUE TITLE
[🕹️] Fix UI on 2nd Onboarding Step

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3299]
### Issue Summary

<img width="759" alt="image" src="https://github.com/user-attachments/assets/1b329dc2-0ddc-4afd-bea7-8e27636c8015">

### Steps to Reproduce

1. Zoom out a lot ( you can do that in the browser with CTRL - )
2. Go to Product -> Add product to open the Onboarding
<img width="454" alt="image" src="https://github.com/user-attachments/assets/b65ed574-f4b0-4fc2-a7fb-b1ab22075f84">
3. Choose "Surveys" to see the screen

### Expected behavior

The boxes should sit a lot closer together

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by RajuGangitla** [comment]
@jobenjada can you assign this issue

**Comment by Aakansha-Chavan** [comment]
@jobenjada can I work on it, can you assign it to me?

**Comment by ishaancreates** [comment]
congrats abhay
