### ISSUE TITLE
[BUG] Landing page has extra scroll bar

### ISSUE THREAD

**Issue by 4F24L** [formbricks/formbricks#3303]
## Landing page has extra scroll bar

- Digital product user journey section has this issue 

https://github.com/user-attachments/assets/9470cb8b-5839-4db8-9d07-200a87c685f7

### Steps to Reproduce

1. Went to ... https://formbricks.com/
2. scroll ...
3. see error

### Expected behavior

There should be no scroll bar. To improve the UI

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Node: 20.10.0
- npm: 10.8.2
```

**Comment by jobenjada** [comment]
what kind of computer are you using? This aspect ratio looks crazy!

**Comment by 4F24L** [comment]
Actually, the task bar and nav bar is out of the recording

**Comment by 4F24L** [comment]
Okay, can you assign me for this issue!!

**Comment by 4F24L** [comment]
Why is the issue closed now ?
