### ISSUE TITLE
[🕹️] [Side Quest Submission] Upvote and comment on Reddit launch thread 

### ISSUE THREAD

**Issue by PratikAwaik** [formbricks/formbricks#3307]
### What side quest or challenge are you solving?

Upvote and comment on [Reddit launch thread](https://www.reddit.com/r/opensource/comments/1ftwbl9/weve_spent_a_few_months_building_ossgg_to_gamify/)

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/6390e9b9-2500-4854-b9cd-5cf675df70b8)

**Comment by PratikAwaik** [comment]
@jobenjada

**Comment by abhayofc** [comment]
Task Done

![image](https://github.com/user-attachments/assets/498dc662-6ed3-48e8-a5ce-830de54a0a4a)
![image](https://github.com/user-attachments/assets/ab8d1334-af22-4210-8517-2c6251120858)

**Comment by jobenjada** [comment]
@abhayofc please open your own issue, otherwise I cannot award points to you

**Comment by jobenjada** [comment]
@thefool76  please have a look here to understand what they are doing :) 

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
