### ISSUE TITLE
[BUG] Getting 2 errors while running on Gitpod.

### ISSUE THREAD

**Issue by itzabhinavarya** [formbricks/formbricks#3309]
### Issue Summary

When we run the project on the gitpod then we get 2 Error.
-------------------------------
First Error 
-------------------------------
Type 'ZodIssue | undefined' is not assignable to type 'ZodIssue'.
@formbricks/api:build:     Type 'undefined' is not assignable to type 'ZodIssue'.
@formbricks/api:build: 
@formbricks/api:build: 2013   return filteredActionIssues;

-------------------------------
Second Error 
-------------------------------
Type 'undefined' is not assignable to type '{ id: string; label: Record<string, string>; }'.
@formbricks/surveys:build: 
@formbricks/surveys:build: 51   const [unsortedItems, setUnsortedItems] = useState<TSurveyQuestionChoice[]>(() => {
@formbricks/surveys:build:    

### Steps to Reproduce

1. Run the project using Gitpod.

### Expected behavior

Shouldn't throws these error.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by jobenjada** [comment]
i think its solved
