### ISSUE TITLE
[BUG] Not able to redirect on the website/landing page. from the Docs Section.

### ISSUE THREAD

**Issue by itzabhinavarya** [formbricks/formbricks#3315]
### Issue Summary

Basically, When we navigate to the docs section, from the landing page. we are not able to come back again on the website by clicking on some short links. like on the formbricks logo or if some new introduce.
One perspective is making good that when we click on the logo of the formbricks then it moves to the very first question/option that is good. but there should be an option to navigate back to the website landing page . https://formbricks.com/ 
By clicking on some button or on the same logo is the question is first . or first side nav.

Issue describe with visuals : 
Loom Video : https://www.loom.com/share/986e8047fc654689a208a8601aa72948

### Steps to Reproduce

1. Head to https://formbricks.com/
2. Click on the Docs 
3. now try getting back on the https://formbricks.com/ [Landing Page] without pressing back button or changing URL.

### Expected behavior

There should be an option to get back on the https://formbricks.com/ [Landing page] by clicking some button/icon.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Prathamesh0901** [comment]
I would love to work on this issue. Please assign!

**Comment by itzabhinavarya** [comment]
@rajvinder-kaur @Prathamesh0901 During Hacktoberfest 2024, we are unable to access the Formbricks landing page or website to contribute. As a result, we can't contribute to the webpage. If necessary, the Formbricks team will internally address these issues. I believe the repository might be private.

**Comment by jobenjada** [comment]
the landing page is not part of the hackathon this year :)
