### ISSUE TITLE
[BUG] Dark/Light toggle button missing on the landing page. 

### ISSUE THREAD

**Issue by itzabhinavarya** [formbricks/formbricks#3316]
### Issue Summary

If we are giving dark/light theme toggle button on the docs section , then we should also give an similar option on the landing page as well.

Issue describe with visuals :
Loom Video :
https://www.loom.com/share/0e38b8703fa746be81c5c4ba7ca04ef8

### Steps to Reproduce

1. Head to https://formbricks.com/
2. Click on the Docs, You will see an option to toggle between dark and light theme.
3. Navigate back to landing page. there is no option to toggle between dark and light theme.

### Expected behavior

1. On the https://formbricks.com/ [Landing page], there should be an option to toggle between dark and light theme.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by abhayofc** [comment]
I think we need to redesign for the dark mode theme of landing page

**Comment by itzabhinavarya** [comment]
@abhayofc Let me know, if the requirement then i can redesign the dark theme for the landing page. If so then i request you to assign this issue to me.

**Comment by Pratham271** [comment]
@abhayofc I think I picked it up first

**Comment by jobenjada** [comment]
the landing page is not part of the hackathon this year :)
