### ISSUE TITLE
[BUG] Issue in navigation links active selection : In the docs section

### ISSUE THREAD

**Issue by itzabhinavarya** [formbricks/formbricks#3317]
### Issue Summary

Basically when we are initially on the docs section. https://formbricks.com/docs/introduction/what-is-formbricks 
then there is a beautiful slick light green border color is showing on the active navigation links. 
<img width="959" alt="image" src="https://github.com/user-attachments/assets/097a352c-0d8d-4c7e-8412-704bc38ccff5">

But when we changed to another section like App Surveys or Website Surveys questions. then that styles gones.
![image](https://github.com/user-attachments/assets/5e052152-9878-4fbe-b444-986be1f12136)

Issue describe with visuals :
Loom Video :
https://www.loom.com/share/d4c41cdbdcd747e79b518663439c2f9e

### Steps to Reproduce

1. Navigate to docs section of the landing page. 
2. try changing the question from the left hand side options.

### Expected behavior

That active selected style should be remains on the all active parent links.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by abhayofc** [comment]
This is because on "What is formbricks" page, there is something like a hero section with a CTA button and that is why there is that green effect there and I don't think that adding this to every page looks good.

**Comment by itzabhinavarya** [comment]
@abhayofc No actually i am talking about, this navigation green effect.
<img width="221" alt="image" src="https://github.com/user-attachments/assets/992be993-091b-451f-81c0-ae381e6017bf">

**Comment by codervinod123** [comment]
@mattinannt @pandeymangg  please assign it to me

**Comment by Abhaysoft-inc** [comment]
> @abhayofc No actually i am talking about, this navigation green effect. Navigate through the links you'll get to know about that is an issue with the active navigation. <img alt="image" width="221" src="https://private-user-images.githubusercontent.com/95561280/374129162-992be993-091b-451f-81c0-ae381e6017bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTcxNDcsIm5iZiI6MTcyODM5Njg0NywicGF0aCI6Ii85NTU2MTI4MC8zNzQxMjkxNjItOTkyYmU5OTMtMDkxYi00NTFmLTgxYzAtYWUzODFlNjAxN2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE0MTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NWNkMTI5MzI2M2FkNzRkNzg2ZTNlNzg2OTZjMmYyOTI3NmNiZTQxODE4ZjM5OTQzZDhhZTJlYzdmMDkzNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x5zekH0yC8joAAT7fl74HwYJ10SYYRdVxpNqEbjcQ6o">
> 
> here is no effect but the navigation/link is selected/active. <img alt="image" width="302" src="https://private-user-images.githubusercontent.com/95561280/374231192-4c7623f8-3258-4c3b-b3dc-3bd309b716e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTcxNDcsIm5iZiI6MTcyODM5Njg0NywicGF0aCI6Ii85NTU2MTI4MC8zNzQyMzExOTItNGM3NjIzZjgtMzI1OC00YzNiLWIzZGMtM2JkMzA5YjcxNmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE0MTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZDI5YzJmMDI1NTU5ZTMxOGFjOWNkYWUyZDRhYTU2YTk1NDI4OTdkNzk1NjA0OGUxZmQxOGI2YTI4NThlNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Glol4KxfsTsBBFdOrbVYAGmcLIgn1VY1ng2im278q9Y">

got it

**Comment by Khareayushh** [comment]
If I provide the solution first, would that be considered?

**Comment by Nikhilj007** [comment]
@abhayofc Hey 48 hours are over. If you are not interested in this issue can you please delete you assigned.

**Comment by abhayofc** [comment]
> @abhayofc Hey 48 hours are over. If you are not interested in this issue can you please delete you assigned.

I am working on it, I am just out of city that's why I haven't created a PR, will open one by tomorrow

**Comment by amit0-01** [comment]
> ### Issue Summary
> Basically when we are initially on the docs section. https://formbricks.com/docs/introduction/what-is-formbricks then there is a beautiful slick light green border color is showing on the active navigation links. <img alt="image" width="959" src="https://private-user-images.githubusercontent.com/95561280/374082805-097a352c-0d8d-4c7e-8412-704bc38ccff5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDUyMDIsIm5iZiI6MTcyODc0NDkwMiwicGF0aCI6Ii85NTU2MTI4MC8zNzQwODI4MDUtMDk3YTM1MmMtMGQ4ZC00YzdlLTg0MTItNzA0YmMzOGNjZmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDE0NTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZjBlNTllNDUyNDk5NTQwYjlkNzMwZmQ2Y2JiZDliNjE3OTUwYTRjMjBjNzkwZGQ0YTlkMDRlZjAzYWIyZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.61_Mb63D00-BXkavu-nMhKGioDh2BgsQcaPWIsSpgEA">
> 
> But when we changed to another section like App Surveys or Website Surveys questions. then that styles gones. ![image](https://private-user-images.githubusercontent.com/95561280/374140472-5e052152-9878-4fbe-b444-986be1f12136.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDUyMDIsIm5iZiI6MTcyODc0NDkwMiwicGF0aCI6Ii85NTU2MTI4MC8zNzQxNDA0NzItNWUwNTIxNTItOTg3OC00ZmJlLWI0NDQtOTg2YmUxZjEyMTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDE0NTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNzAwMGUyZTlkMWRmYTdjYjY5YTI3YWNmYjA5ODk4OThhYzQ3YWQwNDkwZTgzMjIzMzUwMzJiYmNhODI0YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NiSPkEG1Sotr51AayafDsA7p4ZJNGUTeLPGBkoG9p_I)
> 
> Issue describe with visuals : Loom Video : https://www.loom.com/share/d4c41cdbdcd747e79b518663439c2f9e
> 
> ### Steps to Reproduce
> 1. Navigate to docs section of the landing page.
> 2. try changing the question from the left hand side options.
> 
> ### Expected behavior
> That active selected style should be remains on the all active parent links.
> 
> ### Other information
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Environment
> * [ ]  Formbricks Cloud (app.formbricks.com)
> * [ ]  Self-hosted Formbricks
> 
> ### Desktop (please complete the following information)
> ```
> - OS:
> - Node:
> - npm:
> ```

/assign
