### ISSUE TITLE
[BUG] Issue with Discord icon at the bottom left organization sub-menu.

### ISSUE THREAD

**Issue by itzabhinavarya** [formbricks/formbricks#3320]
### Issue Summary

Both the Documentation and Join Discord sections have the same icon. Since lucide-react doesn’t support the Discord icon, I created a custom Discord icon that matches the style of the other icons.

<img width="366" alt="image" src="https://github.com/user-attachments/assets/84c81eb9-f39c-4355-974d-664b40112f48">

### Steps to Reproduce

1. Click on the bottom-left Organization profile
2. then you will see the sub menu .
3. Check the Join Discord Icon.

### Expected behavior

<img width="356" alt="image" src="https://github.com/user-attachments/assets/571ef1ec-6c2e-4a8b-8384-dbc86a5df436">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by alwaysahustler** [comment]
I am working on this issue

**Comment by naaa760** [comment]
would i create pull request for this issue?
