### ISSUE TITLE
[🕹️] Write listicle for oss.gg repos 

### ISSUE THREAD

**Issue by adityadeshlahre** [formbricks/formbricks#3322]
### What side quest or challenge are you solving?

What side quest or challenge are you solving?
Write listicle for oss.gg repos

### Points

750

### Description

Description
Curated a list of all repos in the 2024 oss.gg Hacktoberfest and written a blog on it how to get most out of oss.gg event.

### Provide proof that you've completed the task

https://dev.to/adityadeshlahre/hacktoberfest-side-hack-write-code-win-a-macbook-ps5-or-iphone-16-4h75

Thank You :slightly_smiling_face:

**Comment by jobenjada** [comment]
thanks mate :)
