### ISSUE TITLE
[🕹️]Follow on linkedin side quest

### ISSUE THREAD

**Issue by Ionfinisher** [formbricks/formbricks#3326]
### What side quest or challenge are you solving?

Solving the following on linkedIn challenge

### Points

50

### Description

Followed the Foembrick account on lInkedIn

### Provide proof that you've completed the task

<img width="893" alt="Screen Shot 2024-10-04 at 15 36 38" src="https://github.com/user-attachments/assets/a4cd7c40-c2ec-46f0-97b1-2d57f6a96f0d">

**Comment by abhayofc** [comment]
Completed the quest!

![image](https://github.com/user-attachments/assets/5c72d2e0-c877-44e1-8078-588f1b7488e6)

**Comment by Abhaysoft-inc** [comment]
@Ionfinisher Should I need to make changes in some file ??

**Comment by jobenjada** [comment]
@abhayofc pls open your own issue, otherwise I cant award you points :)

/award 50
