### ISSUE TITLE
[🕹️]Gif magic and brickify someone challenges

### ISSUE THREAD

**Issue by Ionfinisher** [formbricks/formbricks#3332]
### What side quest or challenge are you solving?

Solving both the gif magic side quest and the brickify someone side quest

### Points

300

### Description

Created a gif and uploaded it to giphy
Posted the brickified version of Luke Skywalker on X

### Provide proof that you've completed the task

Link to giphy: https://giphy.com/gifs/BuMkZTna0cG8EvhGms
Link to the X post: https://x.com/ion_finisher/status/1843588775307575515

**Comment by harshsbhat** [comment]
hey what AI did you use to brickify?

**Comment by jobenjada** [comment]
thanks :))
