### ISSUE TITLE
[BUG] All Survey Types are not "compatible" now in Survey Copy Form

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#3335]
### Issue Summary

2 issues with the Survey copy form in https://github.com/formbricks/formbricks/blob/c01c00ce2e025d89a3cf5f93446d980b4aae0f04/packages/ui/components/SurveysList/components/CopySurveyForm.tsx#L73

1) All environment names show a tooltip: "This product is not compatible with the survey type."
2) When you click on any environment name the form is submitted

### Steps to Reproduce

1. Click on "Copy..." for a survey
2. Hover over an environment name to see the misleading popup
3. Click on an environment name to submit the form

### Expected behavior

No tooltip and the form is not submitted on click.

### Screenshots

[scrnli_32h0AgZSmpbqNN.webm](https://github.com/user-attachments/assets/3ad187fb-b504-46ab-92f6-1b7b69d7d2af)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by jonas-hoebenreich** [comment]
I can fix this
/assign

**Comment by Rajeev1253** [comment]
I can fix this
/assign
