### ISSUE TITLE
[BUG] Broken Redirects on `Developer Docs` -> `Contributing` Page

### ISSUE THREAD

**Issue by naineel1209** [formbricks/formbricks#3344]
### Issue Summary

Several broken redirect links were identified on the `Developer Docs` page. These links currently point to incorrect paths, causing users to get 404 error.

### Steps to Reproduce

1. **Developer Docs -> Overview Page Redirect**:
   On the page `https://formbricks.com/docs/developer-docs/overview`, under the section `Contributing to Formbricks`, the redirect link `/developer-docs/contributing` is broken.

2. **Developer Docs -> Contributing Section Redirects**:
   On the page `https://formbricks.com/docs/developer-docs/contributing/get-started`, under the section `Setup Dev Environments`, the redirects for Gitpod and GitHub Codespaces are broken.

### Expected behavior

1. **Developer Docs -> Overview Page Redirect**:
    `/developer-docs/contributing` should point to `/developer-docs/contributing/get-started`.

2. **Developer Docs -> Contributing Section Redirects**:
   - For Gitpod: The link `/docs/developer-docs/contributing/gitpod` should be updated to `/developer-docs/contributing/gitpod`.
   - For GitHub Codespaces: The link `/docs/developer-docs/contributing/codespaces` should be updated to `/developer-docs/contributing/codespaces`.

### Other information

These URL issues occur because the `basePath` is set to `/docs`, and the current links unnecessarily include `/docs` in the redirect path, leading to broken routes.

### Screenshots

1. For Overview Page:
![image](https://github.com/user-attachments/assets/68890631-ca70-4151-baa9-0b9459e2a2d1)

2. For Getting Started Page:
![image](https://github.com/user-attachments/assets/6ab9e6fa-fa15-495f-afcc-cd59a374284f)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: Brave
```

**Comment by jobenjada** [comment]
/award 150 thanks for spotting these!

Who is up to fix them for another 150?

**Comment by adityadeshlahre** [comment]
> /award 150 thanks for spotting these!
> 
> Who is up to fix them for another 150?

he solved this himself here 
- #3343
