### ISSUE TITLE
[🕹️] Last Used indicator on login page

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3347]
### Is your feature request related to a problem? Please describe.

people get confused how they signed up last time

### Describe the solution you'd like

<img width="544" alt="image" src="https://github.com/user-attachments/assets/bccfc390-6baa-47da-a417-128d1b27e319">

add a subtle "Last used" indicator

**Comment by jobenjada** [comment]
@Sara2706 last time you didn't work on the issue. Are you commited this time? 🤓 

also have a look at the Hanko and Cal.com Repositories, they also this :)

**Comment by Khaan25** [comment]
Hey @Sara2706, if you aren't working on this, could you assign this to me? I've done this previously as well so it won't be an issue @jobenjada?
