### ISSUE TITLE
[🕹️] Leaderboard for oss.gg

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3348]
### Is your feature request related to a problem? Please describe.

we need a global leaderboard

### Describe the solution you'd like

pls make sure to implement basic caching

**Comment by jobenjada** [comment]
@anandaashish74711 hey mate! are you familiar with the oss.gg repo? if not, I'd be happy for Raju to ship this as he has worked on the repo already and I dont have a lot of capacity to onboard new contributors to oss.gg these days.

if you're up for the job, great! If not, pls forward it to Raju :)

**Comment by anandaashish74711** [comment]
I was about to ask for examples of what kind of leaderboard you want it to look like, but if you prefer, you can assign it to someone else.

**Comment by adityadeshlahre** [comment]
@jobenjada what about me giving it a try :slightly_smiling_face:

**Comment by jobenjada** [comment]
thanks @anandaashish74711 for understanding :) Raju shipped the template section at formbricks.com/survey-templates without much guidance which I really appreciate cause im super busy these days.

will open more issues later today, stay around (also @adityadeshlahre :) )
