### ISSUE TITLE
[🕹️] ossgg: 6 Side Quest Solved

### ISSUE THREAD

**Issue by adityadeshlahre** [formbricks/formbricks#3352]
## San Francisco Billboard Ad
![3rd itteration](https://github.com/user-attachments/assets/384b6c1e-0c46-4837-859b-d22e35fa27b7)
![formbrickBillboard2](https://github.com/user-attachments/assets/4842c44d-55cd-4c01-905c-6338dc7dc0fa)
![formbrickBillboardUpdate](https://github.com/user-attachments/assets/c17f8b09-8bf6-4f88-bdf4-a7fcc8f10008)
- [tweet link](https://x.com/adityadeshlahre/status/1844151260896952600)

## Meme Magic
- [tweet Link](https://x.com/adityadeshlahre/status/1844152096482083116)

## GIF Magic
- [tweet link](https://x.com/adityadeshlahre/status/1844152951855775772)
- [giphy link](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMHNnN3Q2NzE0b29pMHozcWkyNzlqcHp2NjVubWlmbHc2cWMxMTUzZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/KsdJDb93EbaPfjnI7p/giphy-downsized-large.gif)

## Follow On LinkedIn
![image](https://github.com/user-attachments/assets/ab9cca1d-ece7-42ed-8ace-81128d0ce57f)

## Brickify someone famous with AI
- [tweet link](https://x.com/adityadeshlahre/status/1844154258318557649)

## Spread the word to cover oss.gg OSS event
![image](https://github.com/user-attachments/assets/4ff8ed7b-d164-4809-843f-b7d7151bbf1a)
![image](https://github.com/user-attachments/assets/8358d05c-dbd9-45dc-8ed3-cffa8a6ec5e4)
![image](https://github.com/user-attachments/assets/0b3f9e70-55d1-436d-b679-55a914718152)

### Points

- AD : 300
- Meme : 150
- GIF : 150 
- Follow LinkedIn : 50
- Brickify someone famous with AI : 150 
- Spread the word : 50 x 3 = 150

### Description

- create a BILLBOARD ad for formbricks
- crafted a meme & gif
- Followed on LinkedIn
- brikified someone famous with AI
- spread word about ossgg to cover event 

### Thank You :slightly_smiling_face:

**Comment by adith-suhas-sv** [comment]
@Bisha18 should i unassign me so u can work on this?

**Comment by jobenjada** [comment]
/award 950 thanks mate! You've figured the game out, love to see that! :D 

--------

### Please open your own issue, I can only award the AUTHOR of an issue with points

@2DELTA7 @faheem2312 @adith-suhas-sv @Bisha18 

-------

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

---------

all side quests here, get em allll 👇

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74

**Comment by faheem2312** [comment]
- Created billboard Ad
![billboard ad](https://github.com/user-attachments/assets/05640e7a-f93c-44ac-8d6c-5439c9f1c7d2)

- Crafted Meme
![meme](https://github.com/user-attachments/assets/43b6e5dc-33b2-4a0c-8f80-7a50b4fdea75)

- Crafted gif
![giffy](https://github.com/user-attachments/assets/824b0b1b-624d-4ef8-913a-71c3ab93cb2e)

- Followed on LinkedIn
![Linkedin](https://github.com/user-attachments/assets/d3f4f16b-ca05-4337-8e02-b11e52d5c7ed)

- Brickify someone famous with AI
![brickify](https://github.com/user-attachments/assets/93d42e8f-ed1d-4f3b-9389-a5cc682be0cc)

- Spread the word about oss.gg
![video#1](https://github.com/user-attachments/assets/ee759755-af5f-4465-b5c6-175efa87723c)
![video#2](https://github.com/user-attachments/assets/b2d870c2-c036-4b5d-8485-1daea74fa91a)
![video#3](https://github.com/user-attachments/assets/6c9b5194-8998-4916-a7ac-57607f2591b0)

Thanks!!!
