### ISSUE TITLE
[🕹️] oss.gg 2 side quests

### ISSUE THREAD

**Issue by Ionfinisher** [formbricks/formbricks#3353]
### What side quest or challenge are you solving?

Write a listicle on dev.to about oss.gg hacktoberfest
Design a billboad Ad for Formbricks

### Points

Write a listicle on dev.to about oss.gg hacktoberfest -> 750
Design a billboad Ad for Formbricks -> 300
**Total points: 1050**

### Description

Wrote a listicle on dev.to about oss.gg hacktoberfest. Actually did a while ago but didn't got the points for it.
Designed a billboad Ad for Formbricks

### Provide proof that you've completed the task

Dev.to article : https://dev.to/ion_finisher/hacktoberfest-ossgg-code-conquer-and-win-big-5931

![Formbricks_billboard](https://github.com/user-attachments/assets/11a9144f-c22d-4380-b551-03857b61b672)

**Comment by Suraj-kumar00** [comment]
Hi @Ionfinisher, how have you been?
Can I work on this issue?

**Comment by Ionfinisher** [comment]
Hello @Suraj-kumar00 @Abhishekkumar60818 this Is actully my submission for these side quests. I forgot to assign myself. If you want to work on these, open you're own issues and submit proof f work there.

**Comment by Suraj-kumar00** [comment]
but this issue is assined to @Abhishekkumar60818 ?

**Comment by Ionfinisher** [comment]
Yes, I would like @Abhishekkumar60818 to unassign himself so that I can assign myself

**Comment by jobenjada** [comment]
/award 300 for the billboard, its funny! :D 

where did you find the other one? We already have 2 listicles, and 1 would've been enough tbh :D

**Comment by Ionfinisher** [comment]
> /award 300 for the billboard, its funny! :D
> 
> where did you find the other one? We already have 2 listicles, and 1 would've been enough tbh :D

I wrote It the 4th October and made a PR but you didn't noticed it at all 🥲

**Comment by Harsh9485** [comment]
how to complete the side quests
plz give me a guide
