### ISSUE TITLE
[🕹️]Like & Re-Tweet oss.gg Launch Tweet with  a “🧱” emoji

### ISSUE THREAD

**Issue by AnshMehta24** [formbricks/formbricks#3362]
### What side quest or challenge are you solving?

![Screenshot 2024-10-10 184028](https://github.com/user-attachments/assets/e96ec783-c24b-40cc-a063-daeb37b6d340)

### Provide proof that you've completed the task

![Screenshot 2024-10-10 184028](https://github.com/user-attachments/assets/bf55789c-9f67-496c-a10f-799a74b9b9cc)

**Comment by tsahil01** [comment]
![image](https://github.com/user-attachments/assets/9d977419-2ae6-4f86-80ac-f1daf444dc23)

@AnshMehta24  done!

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

--------

### Please open your own issue, I can only award the AUTHOR of an issue with points

@Vinit1014 @aryan7412 @Anjalisharma3463 @Anjalisharma3463 @dineshsutihar @tsahil01

-------

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

---------

all side quests here, get em allll 👇

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
