### ISSUE TITLE
[🕹️]Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by hiralvavadiya** [formbricks/formbricks#3363]
### What side quest or challenge are you solving?

Like and Re-Tweet oss.gg Launch Tweet
<img width="615" alt="Screenshot 2024-10-10 at 6 55 02 PM" src="https://github.com/user-attachments/assets/f8f9ffd6-fd5f-4647-933e-e64f96c604bb">
<img width="601" alt="Screenshot 2024-10-10 at 6 56 32 PM" src="https://github.com/user-attachments/assets/5a29cde2-0608-454f-8289-472cd8a8370b">

### Points

50 points

### Description

- Like the oss.gg Launch tweet
- Retweet oss.gg Launch tweet with a “🧱” emoji 

### Provide proof that you've completed the task

<img width="615" alt="Screenshot 2024-10-10 at 6 55 02 PM" src="https://github.com/user-attachments/assets/160626df-dc07-4cf2-bcb3-c542f1791173">
<img width="601" alt="Screenshot 2024-10-10 at 6 56 32 PM" src="https://github.com/user-attachments/assets/c6be0327-4d81-4939-8bb9-803e397edce5">

**Comment by Studycode001** [comment]
![image](https://github.com/user-attachments/assets/8483873f-a687-4876-a89a-6a9236785626)
![image](https://github.com/user-attachments/assets/a8bb0d8f-b48a-4762-8cbb-302dde22aa47)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

--------

### Please open your own issue, I can only award the AUTHOR of an issue with points

@Studycode001 

-------

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

---------

all side quests here, get em allll 👇

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
