### ISSUE TITLE
[🕹️]Liked, Followed and Re-Tweet Lauch Tweet 

### ISSUE THREAD

**Issue by rishipatel9** [formbricks/formbricks#3366]
### What side quest or challenge are you solving?

![Screenshot 2024-10-10 at 7 07 32 PM](https://github.com/user-attachments/assets/9a81de4c-8275-4a58-81fc-d65ae28d331a)

### Points

50

### Description

Proof 

### Provide proof that you've completed the task

![Screenshot 2024-10-10 at 7 07 32 PM](https://github.com/user-attachments/assets/f69e194c-6b81-4f87-b2b9-4898928c3164)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

--------

### Please open your own issue, I can only award the AUTHOR of an issue with points

@tanayk-svg 

-------

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

---------

all side quests here, get em allll 👇

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
