### ISSUE TITLE
[🕹️]Upvote and comment on Reddit launch thread 

### ISSUE THREAD

**Issue by hiralvavadiya** [formbricks/formbricks#3367]
### What side quest or challenge are you solving?

Upvote and comment on Reddit launch thread

### Points

50 points

### Description

- Upvote the Reddit launch thread
- Added an comment for engage with a thread on Reddit about the launch.

### Provide proof that you've completed the task

<img width="1226" alt="Screenshot 2024-10-10 at 7 09 45 PM" src="https://github.com/user-attachments/assets/83b02ef1-bc6d-474e-a55d-d73d369e8eb6">
<img width="829" alt="Screenshot 2024-10-10 at 7 10 26 PM" src="https://github.com/user-attachments/assets/6ce13edb-5555-4848-8ca0-18fa8901f35e">

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

--------

### Please open your own issue, I can only award the AUTHOR of an issue with points

@hiralvavadiya @rishipatel9 @husna3249

-------

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

---------

all side quests here, get em allll 👇

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
