### ISSUE TITLE
[🕹️]Spread the word 

### ISSUE THREAD

**Issue by hiralvavadiya** [formbricks/formbricks#3368]
### What side quest or challenge are you solving?

Spread the word

### Points

50 points each influencer (max 3)

### Description

- Comment under a video of my 3 favorite developer influencer to cover the oss.gg hackathon in their next video.
- On their latest videos

### Provide proof that you've completed the task

https://youtu.be/fGkXjQkXzW8?si=40y58-bXTDJWDcMG
<img width="984" alt="Screenshot 2024-10-10 at 7 23 27 PM" src="https://github.com/user-attachments/assets/b6d2d373-7151-4b7f-b13a-23929f71893d">

https://youtu.be/E6tAtRi82QY?si=CR60TxwI95EJq7AR
<img width="989" alt="Screenshot 2024-10-10 at 7 21 23 PM" src="https://github.com/user-attachments/assets/03f387df-e3c9-49da-932e-9859686612a5">

https://www.youtube.com/watch?v=mkHgwPkfqmw
<img width="1004" alt="Screenshot 2024-10-10 at 7 33 24 PM" src="https://github.com/user-attachments/assets/f567f9e5-a660-401c-b39d-2f3b5d39f498">

**Comment by GrowthCoder7** [comment]
**### What side quest or challenge are you solving?**
Spread the word

**Points**
50 points each influencer (max 3)

**Description**

- Comment under a video of my 3 favorite developer influencer to cover the oss.gg hackathon in their next video.
- On their latest videos

Provide proof that you've completed the task
![WhatsApp Image 2024-10-10 at 19 46 39_2d3da153](https://github.com/user-attachments/assets/ef2527a0-8af6-4a55-b95c-fce3c36e2abd)
https://www.youtube.com/watch?v=q3fktcOEU3M

![WhatsApp Image 2024-10-10 at 19 47 48_6bfa6e37](https://github.com/user-attachments/assets/11588d62-7b52-44e9-92d1-0d1fcdbf5871)
https://www.youtube.com/watch?v=zdZjr_ODWC8

![WhatsApp Image 2024-10-10 at 19 49 37_cdc54733](https://github.com/user-attachments/assets/00664b6f-654f-4378-8feb-fc77eb064b72)
https://www.youtube.com/watch?v=zvbTDUSz8Cc

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

--------

### Please open your own issue, I can only award the AUTHOR of an issue with points

@GrowthCoder7 

-------

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

---------

all side quests here, get em allll 👇

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
