### ISSUE TITLE
[🕹️] Liked, Followed and Re-Tweet Lauch Tweet

### ISSUE THREAD

**Issue by Anjalisharma3463** [formbricks/formbricks#3369]
### What side quest or challenge are you solving?

 
![Capture23232](https://github.com/user-attachments/assets/2a0cdf75-5dee-4bb1-8472-ec31c6cd295e)

### Points

50

### Provide proof that you've completed the task

![Capture23232](https://github.com/user-attachments/assets/e0e039ec-26cc-4b35-a10d-2331b9a2f24c)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

--------

### Please open your own issue, I can only award the AUTHOR of an issue with points

@Sulochan-khadka

-------

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

---------

all side quests here, get em allll 👇

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74

**Comment by Sulochan-khadka** [comment]
> /award 50 thanks mate! Happy to have you participate :)
> 
> ### Please open your own issue, I can only award the AUTHOR of an issue with points
> @Sulochan-khadka
> 
> ### check out this hack to make 1050 points in 5 minutes:
> https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74
> 
> all side quests here, get em allll 👇
> 
> https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74

Sure... Checkout my issues @jobenjada
