### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page 

### ISSUE THREAD

**Issue by Kali-13** [formbricks/formbricks#3370]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page

### Points

50

### Description

Followed and liked the Formbricks LinkedIn Page.

### Provide proof that you've completed the task

![Screenshot 2024-10-10 at 7 40 15 PM](https://github.com/user-attachments/assets/2ad1c5bd-1063-42e6-94c9-1573b2c8366b)
![Screenshot 2024-10-10 at 7 40 40 PM](https://github.com/user-attachments/assets/1e8ff5f8-b310-40a0-8bd8-2a1d703c4479)

**Comment by BadriVishalPadhy** [comment]
what is going on

**Comment by Madan1500** [comment]
As part of the task, I followed Formbricks' LinkedIn page and liked post #3370. I also uploaded a screenshot of the like.

![follow](https://github.com/user-attachments/assets/53684954-2c24-4e28-8ffd-6b2bff34c9b4)


![liked](https://github.com/user-attachments/assets/6cbd5a66-0e2d-46a3-b68a-83db12970ee4)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

--------

### Please open your own issue, I can only award the AUTHOR of an issue with points

@Kali-13  @Madan1500

-------

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

---------

all side quests here, get em allll 👇

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
