### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page 

### ISSUE THREAD

**Issue by hiralvavadiya** [formbricks/formbricks#3371]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page

### Points

50 points

### Description

- followed formbricks linkedIn page and like the launch post

### Provide proof that you've completed the task

<img width="433" alt="Screenshot 2024-10-10 at 7 50 34 PM" src="https://github.com/user-attachments/assets/f9f1d308-8bb0-4570-84d4-0ab369ef2025">

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

--------

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

---------

all side quests here, get em allll 👇

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74

**Comment by samarsrivastav** [comment]
wont i get the points ? @jobenjada
