### ISSUE TITLE
[🕹️] Followed Linkedin page

### ISSUE THREAD

**Issue by swamimalode07** [formbricks/formbricks#3372]
### What side quest or challenge are you solving?

![image](https://github.com/user-attachments/assets/4e6b69e9-f819-4c74-a670-87c668657b6f)
Followed Linkedin page

### Points

50

### Description

Followed Linkedin page

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/87ffbdf3-3145-491c-865b-6aa3988d27be)

**Comment by BadriVishalPadhy** [comment]
this not an issue bruh
?

**Comment by BadriVishalPadhy** [comment]
lol xd

**Comment by sandeep-sarma-24** [comment]
I don't think this is the issue itself

**Comment by swamimalode07** [comment]
how is this a issue and how is someone going to solve this

**Comment by mohan8git** [comment]
Followed Linkedin page

Points
50

Description
Followed Linkedin page

<img width="832" alt="Screenshot 2024-10-10 at 11 01 20 PM" src="https://github.com/user-attachments/assets/5401e17c-7107-4974-9a92-a4a132d2693d">

**Comment by mohan8git** [comment]
@jobenjada

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

--------

### Please open your own issue, I can only award the AUTHOR of an issue with points

@sandeep-sarma-24 @BadriVishalPadhy @swamimalode07

-------

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

---------

all side quests here, get em allll 👇

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
