### ISSUE TITLE
[🕹️] Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by aditya242401** [formbricks/formbricks#3373]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page

### Points

50

### Description

<img width="1066" alt="image" src="https://github.com/user-attachments/assets/a7a61f2f-a6c9-4764-b259-4f9139646069">

### Provide proof that you've completed the task

<img width="1066" alt="image" src="https://github.com/user-attachments/assets/1e6b89b4-465d-4212-925f-386bc82d6919">

**Comment by sandeep-sarma-24** [comment]
side quest or challenge : Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page
 Here is the screenshot & my profile is (https://www.linkedin.com/in/sandeep24sarma/) 
<img width="1504" alt="image" src="https://github.com/user-attachments/assets/9ba51a26-2c64-488d-bc3a-5966f64e1c80">

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

--------

@sandeep-sarma-24 @hinakamal555 @ Please open your own issue, I can only award the AUTHOR of an issue with points

-------

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

---------

all side quests here, get em allll 👇

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
