### ISSUE TITLE
[🕹️]Spread the word

### ISSUE THREAD

**Issue by GrowthCoder7** [formbricks/formbricks#3374]
### What side quest or challenge are you solving?

Spread the word

### Points

50 per influencer, max. 3 influencers

### Provide proof that you've completed the task

![WhatsApp Image 2024-10-10 at 19 46 39_d4c18d73](https://github.com/user-attachments/assets/64be722d-0445-475e-a8d6-eef5624bed31)
https://www.youtube.com/watch?v=q3fktcOEU3M

![WhatsApp Image 2024-10-10 at 19 47 48_3ccdde96](https://github.com/user-attachments/assets/0b353686-c5d0-4a4c-9de6-42ed9409f55e)
https://www.youtube.com/watch?v=zdZjr_ODWC8

![WhatsApp Image 2024-10-10 at 19 49 37_03f64980](https://github.com/user-attachments/assets/37d81bd5-496a-4dcf-8abc-100dc48b61ba)
https://www.youtube.com/watch?v=zvbTDUSz8Cc

**Comment by phoenixdev100** [comment]
What side quest or challenge are you solving?
Spread the word

Points
50 per influencer, max. 3 influencers

Description
No response

Provide proof that you've completed the task

https://www.youtube.com/watch?v=yoX7NzVpX8w&t=1534s
![image](https://github.com/user-attachments/assets/4c6a0fd7-424d-4482-9306-ad0d951764c4)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

-------

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

@phoenixdev100 Please open your own issue, I can only award the AUTHOR of an issue with points

---------

all side quests here:

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74

**Comment by phoenixdev100** [comment]
I have opened issue https://github.com/formbricks/formbricks/issues/3420

@GrowthCoder7

**Comment by swamiabhishek45** [comment]
![Screenshot 2024-10-11 093625](https://github.com/user-attachments/assets/9e45144a-3521-4df8-9f28-06b7643cd2c9)
