### ISSUE TITLE
[🕹️] Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by rohitdhakane6** [formbricks/formbricks#3375]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page

### Points

50

### Description

I followed frombriks LinkedIn page nad my username is https://www.linkedin.com/in/rohit-dhakane/

### Provide proof that you've completed the task

![Screenshot from 2024-10-10 19-57-45](https://github.com/user-attachments/assets/28cddc11-408d-4d0a-bb12-2e3c7edf0640)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

@rohitdhakane6 @iitzIrFan 

Please CREATE YOUR OWN ISSUE! I can only award points to the AUTHOR of an issue!

all side quests here:

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
