### ISSUE TITLE
[🕹️]Spread the word

### ISSUE THREAD

**Issue by GrowthCoder7** [formbricks/formbricks#3377]
### What side quest or challenge are you solving?

Spread the word

### Points

- 50 per influencer
- max. 3 influencers

### Provide proof that you've completed the task

![WhatsApp Image 2024-10-10 at 19 46 39_e31f6c6d](https://github.com/user-attachments/assets/ad0e760d-87d9-4a29-8feb-433d7f067b15)
https://www.youtube.com/watch?v=q3fktcOEU3M

![WhatsApp Image 2024-10-10 at 19 47 48_a563ef25](https://github.com/user-attachments/assets/8d1ed6ae-8db8-474c-ac02-793359c897a2)
https://www.youtube.com/watch?v=zdZjr_ODWC8

![WhatsApp Image 2024-10-10 at 19 49 37_c84e5f64](https://github.com/user-attachments/assets/8e7a2514-5a7b-48d2-b1d2-1d9ef37bb16e)
https://www.youtube.com/watch?v=zvbTDUSz8Cc

**Comment by YatinSharma37** [comment]
I complete my task

![Screenshot from 2024-10-10 19-41-45](https://github.com/user-attachments/assets/a878b0bd-48cc-4896-8416-ac4da8bb12cd)
![Screenshot from 2024-10-10 19-43-32](https://github.com/user-attachments/assets/5991107d-15dd-42a4-b800-bde7e840249e)
![Screenshot from 2024-10-10 19-43-32](https://github.com/user-attachments/assets/726b32f5-c58d-475f-a4c6-c2707a8b3654)
