### ISSUE TITLE
[🕹️] Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by sandeep-sarma-24** [formbricks/formbricks#3378]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page

### Points

50

### Description

I have followed the [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page through the profile (https://www.linkedin.com/in/sandeep24sarma/) 

### Provide proof that you've completed the task

here is the screenshot : 
<img width="1504" alt="image" src="https://github.com/user-attachments/assets/8acd8bb7-5197-4d30-9e04-cbd72e38615e">

**Comment by ashwinmenghar** [comment]
<img width="1707" alt="Screenshot 2024-10-10 at 8 21 03 PM" src="https://github.com/user-attachments/assets/0ad47bf7-3d19-4678-87df-92af20508dde">

**Comment by andigwandi** [comment]
![image](https://github.com/user-attachments/assets/0d7013e6-9743-49f6-803a-48e99dc1e234)

Task complete.

**Comment by Tufailahmed-Bargir** [comment]
![image](https://github.com/user-attachments/assets/331186c0-6a10-49c5-9da1-41af021c249d)
completed the task

**Comment by ahemadrazak11** [comment]
### [🕹️] Follow Formbricks LinkedIn Page #3380 

Completed #3380 
**Description**
I have followed the [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page through the profile (https://www.linkedin.com/in/ahemad-raza-khan/)

I have provided the proof of task completion

**screenshot:**
![linkedIn](https://github.com/user-attachments/assets/1853fa49-8f33-4494-a48b-6efad15ff276)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

@andigwandi @sandeep-sarma-24 @ashwinmenghar @Aditya3815 @ArifRahaman 

Please open your own issue with your proof. I can only award points to the CREATOR of an issue.

all side quests here 👇 get 'em all!

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
