### ISSUE TITLE
[🕹️] Retweet and 🩷 SIDE QUEST

### ISSUE THREAD

**Issue by shreykx** [formbricks/formbricks#3383]
### What side quest or challenge are you solving?

I liked the official oss.gg launch [post](https://x.com/ossgoodgame/status/1841019549183066552) on X and retweeted it with a brick '🧱' emoji as instructed!

### Points

50

### Description

I liked and retweeted the oss.gg launch tweet with a '🧱' emoji

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/570e6b65-340c-40ad-8494-33c6a5436e44)

Take [this](https://x.com/shreykx/status/1844399961167053122) link lol

**Comment by PredictiveManish** [comment]
I liked the official oss.gg launch [post](https://x.com/compmanish/status/1844413504113299736) on X and retweeted it with a brick '🧱' emoji as instructed!
![Ack](https://github.com/user-attachments/assets/0ed3d394-6349-4ad9-a415-ec764fb8bbba)

**Comment by thesumitkrsingh** [comment]
Assign me

**Comment by thesumitkrsingh** [comment]
#I liked the official oss.gg launch on X and retweeted it with a brick '🧱' emoji as instructed!
![Screenshot from 2024-10-10 22-15-14](https://github.com/user-attachments/assets/689f0d2f-d488-4016-acda-9f12f74cdf45)

**Comment by Neeraj-2525** [comment]
I liked the official oss.gg launch [post](https://x.com/ossgoodgame/status/1841019549183066552) on X and retweeted it with a brick '🧱' emoji as instructed!
![Screenshot 2024-10-10 223411](https://github.com/user-attachments/assets/f0bfe2e5-05a5-41ef-b119-ddc40d0e898c)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

@Pratikbhatkulkar23 @PredictiveManish @Neeraj-2525 @yogeshmlv @aryan7412 

please open your own issues with your submissions. I can only award the author of an issue with points!

all side quests here 👇

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
