### ISSUE TITLE
[🕹️]Retweet and like side quest

### ISSUE THREAD

**Issue by HimanshuGaur14** [formbricks/formbricks#3385]
### What side quest or challenge are you solving?

I liked the official oss.gg launch [post](https://x.com/ossgoodgame/status/1841019549183066552) on X and retweeted it with a brick '🧱' emoji as instructed!

### Points

50 

### Description

I liked and retweeted the oss.gg launch tweet with a '🧱' emoji

### Provide proof that you've completed the task

<img width="701" alt="oss" src="https://github.com/user-attachments/assets/6e3861be-f7b0-4e60-ac22-12a226863994">

**Comment by thebinij** [comment]
I have liked and retweeted the tweet.


<img width="548" alt="Screenshot 2024-10-10 at 22 52 16" src="https://github.com/user-attachments/assets/8ed774e9-9cf9-4373-9361-6c511651f4bc">

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here:

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
