### ISSUE TITLE
[🕹️] Retweet and like Side Quest

### ISSUE THREAD

**Issue by Khaan25** [formbricks/formbricks#3386]
### What side quest or challenge are you solving?

I liked the official oss.gg launch [post](https://x.com/ossgoodgame/status/1841019549183066552) on X and retweeted it with a brick '🧱' emoji as instructed!

### Points

50

### Description

I liked and retweeted the oss.gg launch tweet with a '🧱' emoji

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/77828a40-9add-4d58-9809-5ca828934699)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here:

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
