### ISSUE TITLE
[🕹️]  Selected Question not showing inside New Survey !

### ISSUE THREAD

**Issue by soamn** [formbricks/formbricks#3387]
### What side quest or challenge are you solving?

[ BUG FIX ] Inside New Survey creation, Selected question is not showing on the preview screen when switching the devices !

### Points

150

### Description
**Steps For you to follow to Navigate to the Issue:**
Create a new Survey Form
1. Surveys > New Survey+
2. Start From Scratch > Create Survey
3. Add Any Question
4. Inside Preview Window switch screens from Desktop to mobile 

it shows the first question , not the one that is selected , even going back and forth between questions when switching devices the selected question goes away

### Provide proof that you've completed the task

https://github.com/user-attachments/assets/98df80fd-a7ee-41b5-86ef-c55d5924d166

**Comment by jobenjada** [comment]
/award 150

good catch!
