### ISSUE TITLE
[🕹️] Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by Khaan25** [formbricks/formbricks#3388]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page

### Points

50

### Description

I followed Formbricks LinkedIn page & my username is https://www.linkedin.com/in/professional-frontend-web-developer/

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/6c08010c-4a1b-45a0-ab0f-0c808fedad8d)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here: @Khaan25 @soummyaanon @Avibhatnagar10 @sahilpate-221s @chetan 

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
