### ISSUE TITLE
[FEATURE] Enhance border and visibility of Back button

### ISSUE THREAD

**Issue by ArifRahaman** [formbricks/formbricks#3389]
### Is your feature request related to a problem? Please describe.

The Back button's border in the survey file upload form is not clearly visible, which could lead to confusion for users trying to navigate back. The lack of a distinct border can cause usability concerns, especially for users with visual impairments or when the background is of a similar color.
![Screenshot from 2024-10-10 22-11-16](https://github.com/user-attachments/assets/480195b0-27d2-44ef-ba19-13b201a849f3)

### Describe the solution you'd like

Please enhance the visibility of the Back button by adding a more prominent border (e.g., a darker or thicker border). Alternatively, consider using a contrasting color for the border to improve the overall user experience.

**Comment by jobenjada** [comment]
this is not a bug, but thanks for taking part!

feel free to work on any of the side issues for open bug tickets 🤓
