### ISSUE TITLE
[🕹️] Spread the word

### ISSUE THREAD

**Issue by Khaan25** [formbricks/formbricks#3390]
### What side quest or challenge are you solving?

I'm solving "Spread the word" side quest.

### Points

- 50 per influencer
- max 3 influencers

### Provide proof that you've completed the task

https://www.youtube.com/watch?v=h52AGGNkX5M
![image](https://github.com/user-attachments/assets/269c6438-63dc-4226-9351-c75446011b27)

https://www.youtube.com/watch?v=moCTbU3iPZc&t=1222s
![image](https://github.com/user-attachments/assets/0ebff2a0-7bc2-4832-9258-43d762e7ea92)

https://www.youtube.com/watch?v=uZTBdWSvx8U
![image](https://github.com/user-attachments/assets/cd02616c-bfef-42e0-819b-882afbaf297c)

**Comment by jobenjada** [comment]
/award 150 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here @Khaan25  @Avibhatnagar10  

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
