### ISSUE TITLE
[🕹️] Retweet and like side quest

### ISSUE THREAD

**Issue by thebinij** [formbricks/formbricks#3391]
### What side quest or challenge are you solving?

I liked the official oss.gg launch [post](https://x.com/ossgoodgame/status/1841019549183066552) on X and retweeted it with a brick '🧱' emoji as instructed!

### Points

50

### Provide proof that you've completed the task

<img width="548" alt="Screenshot 2024-10-10 at 22 52 16" src="https://github.com/user-attachments/assets/f3e9500e-ee6c-4c7a-814a-7bc508367bd7">

**Comment by Shazzy911** [comment]
Can you please let me know how can I complete the task

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here @Shazzy911 its all explained down here ⬇️ 

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
