### ISSUE TITLE
[🕹️]Retweet and Like Side Quest

### ISSUE THREAD

**Issue by dineshsutihar** [formbricks/formbricks#3392]
### What side quest or challenge are you solving?

Like & [Re-Tweet oss.gg Launch Tweet ](https://x.com/ossgoodgame/status/1841019549183066552)(50 Points)

### Points

50 Points

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/97f5ef62-6bfb-4d5e-8baf-6b7c7ce4f68d)
[Tweet Link](https://x.com/DineshSutihar/status/1844430281635397863)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here: @abbi4code @dineshsutihar @chetan 

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
