### ISSUE TITLE
[🕹️] Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by Kritikaadhikarii** [formbricks/formbricks#3393]
### What side quest or challenge are you solving?

Like & Re-Tweet oss.gg Launch Tweet

### Points

50

### Description

I've liked, retweeted and left a commit !!

### Provide proof that you've completed the task
retweet link  :
https://x.com/kritikaadhikar/status/1844436053903687753

screenshots:
![image](https://github.com/user-attachments/assets/b80d0883-654b-4dc9-8d05-5abc27aeccd0)
![image](https://github.com/user-attachments/assets/2ddb36de-aca1-4168-9c68-9b277c64e445)

**Comment by sahilpate-221s** [comment]
I've liked, retweeted and left a commit !!

![Screenshot 2024-10-10 233028](https://github.com/user-attachments/assets/a9ec644d-13ec-407a-8b35-10f081cce540)
![Screenshot 2024-10-10 232848](https://github.com/user-attachments/assets/d1f68d3c-7e6b-4ab4-9889-10c1c21e922e)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here: @sahilpate-221s 

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
