### ISSUE TITLE
[🕹️] Upvote and comment on Reddit launch thread

### ISSUE THREAD

**Issue by Kritikaadhikarii** [formbricks/formbricks#3395]
### What side quest or challenge are you solving?

[🕹️] Upvote and comment on Reddit launch thread

### Points

50

### Description

I upvoted and commented on the reddit thread !

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/1eb02060-2a71-4bf5-8c24-fc8965f82398)

https://www.reddit.com/r/opensource/comments/1ftwbl9/comment/lraax1m/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here: @azad52786  @Kritikaadhikarii  @ahmad-bsds  @chetan 

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
