### ISSUE TITLE
[🕹️] Brickify someone famous with AI

### ISSUE THREAD

**Issue by Kritikaadhikarii** [formbricks/formbricks#3396]
### What side quest or challenge are you solving?

[🕹️] Brickify someone famous with AI

### Points

150

### Description

I bricified diddy in a party background.

### Provide proof that you've completed the task

https://x.com/kritikaadhikar/status/1844439316623462766

**Comment by jobenjada** [comment]
/award 50 thanks! why diddy tho? :D 

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here: @aryan7412 @azad52786  @

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
