### ISSUE TITLE
[🕹️] Bulk Delete Created surveys

### ISSUE THREAD

**Issue by soamn** [formbricks/formbricks#3397]
### What side quest or challenge are you solving?

[ Feature ]  Option to select surveys and perform Bulk delete on created Surveys

### Points

50-150

### Description

Navigate to the Survey screen , Create multiple surveys, You will have to manually delete each of  the surveys if you wish to :(

Note:
I was testing the UI and  ended up creating bunch of surveys It felt annoying to manually delete each of the surveys , Don't know if it is a worth it Issue , but I think If you have options to sort the surveys might as well add bulk delete of surveys for smoother experience. 

### Provide proof that you've completed the task

![Screenshot 2024-10-10 233709](https://github.com/user-attachments/assets/4857e913-c816-40e3-a294-a15bfec026a8)

**Comment by pateldivyesh1323** [comment]
I would like to work on this.

**Comment by soamn** [comment]
hey @pateldivyesh1323 You can use /assign to ask to work on an issue, I'm not sure if i can solve this , so please use assign so that it get assigned to you in case I'm unable to do it withing 48hrs

**Comment by ahemadrazak11** [comment]
hey @soamn you can unassigned it. See the option at the top right corner. for **unassigned**

**Comment by jobenjada** [comment]
hey! we wont ship this because the list view does not support bulk changes. Thanks tho! :)
