### ISSUE TITLE
[🕹️] Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by azad52786** [formbricks/formbricks#3400]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page

### Points

50

### Description

Follow The Formbricks LinkedIn Page At (https://linkedin.com/company/formbricks)

Provide Proof That You've Completed The Task.

Screenshot

### Provide proof that you've completed the task

![follo](https://github.com/user-attachments/assets/641f047c-5405-453c-8d06-8076ec498a49)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here:

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
