### ISSUE TITLE
[🕹️] I have Followed  Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by soummyaanon** [formbricks/formbricks#3402]
### What side quest or challenge are you solving?

 I have folowed The **Formbricks** **Linkedin**  Page as a Side quest

### Points

50

### Description

I followed [Formbricks LinkedIn page](https://www.linkedin.com/company/formbricks/posts/?feedView=all) & my username is https://www.linkedin.com/in/soumyapanda12/

### Provide proof that you've completed the task

![Screenshot 2024-10-11 at 12 12 29 AM](https://github.com/user-attachments/assets/d1ecdd8a-2a9d-4155-9b68-0321eae9844d)

**Comment by luciferx77** [comment]
What side quest or challenge are you solving?
I have folowed The Formbricks Linkedin Page as a Side quest

Points
50

Description
I followed [Formbricks LinkedIn page](https://www.linkedin.com/company/formbricks/posts/?feedView=all) & my username is https://www.linkedin.com/in/ombhanushaliii/

Provide proof that you've completed the task
![image](https://github.com/user-attachments/assets/8e7c3584-e65e-42a9-90ba-a4ac2c82b8f5)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here @Sakshi525  @soummyaanon  @luciferx77  @chetan  @kof 

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
