### ISSUE TITLE
[🕹️] Upvote and comment on Reddit launch thread

### ISSUE THREAD

**Issue by aritradevelops** [formbricks/formbricks#3403]
### What side quest or challenge are you solving?

 Upvote and comment on Reddit launch thread

### Points

50

### Description

I upvoted and commented on the reddit thread !

### Provide proof that you've completed the task

https://www.reddit.com/r/opensource/comments/1ftwbl9/comment/lralp1y/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/b313980d-0c82-4555-bc97-14253c5fddd4">

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here @aryanbansal73  and @Vikas350 

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
