### ISSUE TITLE
[🕹️] Completed Formbricks Side Quest - LinkedIn

### ISSUE THREAD

**Issue by luciferx77** [formbricks/formbricks#3404]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page

### Points

50

### Description

I followed the formbricks LinkedIn page and completed a side quest

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/0546a16f-32eb-49c0-bbee-711249eb6076)

**Comment by NitinSingh07** [comment]
![3404](https://github.com/user-attachments/assets/71836290-0ead-412e-a802-acdd229a3439)
Task Completed as I have followed the formbricks LinkedIn page and completed a side quest

**Comment by NitinSingh07** [comment]
![3404](https://github.com/user-attachments/assets/681323c6-53dc-42ea-a07d-b9251267a525)
![Repost](https://github.com/user-attachments/assets/07c196ec-d473-43dc-b249-4bd47127af43)
I followed the formbricks LinkedIn page and completed a side quest

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here:

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74

**Comment by jobenjada** [comment]
@NitinSingh07 pls open your own submission issue otherwise I cant award you the points :)

**Comment by NitinSingh07** [comment]
How can I open my own submission issue?
