### ISSUE TITLE
[🕹️]Completed side quest - Brickify

### ISSUE THREAD

**Issue by luciferx77** [formbricks/formbricks#3405]
### What side quest or challenge are you solving?

Completed side quest - Brickify someone famous with AI 

### Points

150

### Description

Brickified Dominick Toretto aka Vin diesel to Brick Toretto

### Provide proof that you've completed the task

https://x.com/ombhanushaliii/status/1844459228276347296
![image](https://github.com/user-attachments/assets/8893202d-abb5-4929-85f8-39f3f2ee9c12)

**Comment by ri-pandey2396** [comment]
\assign

**Comment by jobenjada** [comment]
/award 150 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here:

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74

**Comment by rohitja26** [comment]
how I can show the images in the pull request
