### ISSUE TITLE
[🕹️]Upvote and comment on Reddit launch thread

### ISSUE THREAD

**Issue by luciferx77** [formbricks/formbricks#3408]
### What side quest or challenge are you solving?

Complete Side quest - Upvote and comment on [Reddit launch thread](https://www.reddit.com/r/opensource/comments/1ftwbl9/weve_spent_a_few_months_building_ossgg_to_gamify/)

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/28e785a5-d0aa-4292-9953-074b68e274e3)

**Comment by NitinSingh07** [comment]
I have submitted my resolved issue. Please assign me this issue.

**Comment by NitinSingh07** [comment]
Please assign me this issue. I have completed my previous one.

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here:

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
