### ISSUE TITLE
[🕹️]Spread the word

### ISSUE THREAD

**Issue by luciferx77** [formbricks/formbricks#3409]
### What side quest or challenge are you solving?

Completed side quest - Spread the word, Comment under a video of your favorite developer influencer

### Points

50 per influencer(3 max)

### Provide proof that you've completed the task

https://youtu.be/Hp9sTsiTZ_I?si=SKEstya1FTKF8cLY

https://youtu.be/_uQrJ0TkZlc?si=KBAXx2mx-s0zKF_y

https://youtu.be/dqlO6_5rZSQ?si=EvTKqkwefs3HZvrZ

![WhatsApp Image 2024-10-11 at 01 22 29_6a70006e](https://github.com/user-attachments/assets/52810ff1-2d73-4694-ba48-7c8fb448c94c)
![WhatsApp Image 2024-10-11 at 01 23 47_097a5def](https://github.com/user-attachments/assets/ac917c3d-1300-4f6f-845e-2f5c7ea2c852)
![WhatsApp Image 2024-10-11 at 01 25 08_cc4940e1](https://github.com/user-attachments/assets/df0372f6-e915-4bfe-9c20-0ffb99f862c2)

**Comment by jobenjada** [comment]
/award 150 thanks mate! Happy to have you participate :)

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here:

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
