### ISSUE TITLE
[🕹️]Meme Magic - Side Quest

### ISSUE THREAD

**Issue by luciferx77** [formbricks/formbricks#3410]
### What side quest or challenge are you solving?

Meme Magic 
Craft a meme where a brick plays a role.

### Points

150

### Provide proof that you've completed the task

https://x.com/ombhanushaliii/status/1844468474560774203

![image](https://github.com/user-attachments/assets/a8874bd6-bf77-43f3-87aa-e21c9299a889)

**Comment by jobenjada** [comment]
nah man, how is that a meme for Formbricks? :D pls try again!
