### ISSUE TITLE
[🕹️] Follow Formbricks LinkedIn Page - Side Quest

### ISSUE THREAD

**Issue by CoderSwarup** [formbricks/formbricks#3411]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page And, if you like, like and comment on the launch post that you’re competing.

### Points

50

### Description

Follow Formbricks LinkedIn Page and Like the Posts

### Provide proof that you've completed the task

![Screenshot 2024-10-11 014417](https://github.com/user-attachments/assets/7b832f0f-76ad-4e03-85b4-40a81ddfb7b7)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :) 

check out this hack to make 1050 points in 5 minutes: https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

all side quests here:

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74
