### ISSUE TITLE
[🕹️]Like & Retweet oss.gg launch tweet 

### ISSUE THREAD

**Issue by Sahil-Gupta584** [formbricks/formbricks#3412]
### What side quest or challenge are you solving?

Like and retweet [Like & Re-Tweet oss.gg Launch Tweet](https://x.com/ossgoodgame/status/1841019549183066552)

### Points

50

### Provide proof that you've completed the task

![Screenshot 2024-10-11 013520](https://github.com/user-attachments/assets/4a5789f1-5cb0-4eff-8e10-f4dadfa14f5e)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :) 

check out this hack to make 1050 points in 5 minutes: https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74
