### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by ViditJain123** [formbricks/formbricks#3414]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page

### Points

50

### Description

Followed and liked the Formbricks LinkedIn Page.

### Provide proof that you've completed the task

![Screenshot from 2024-10-11 08-32-45](https://github.com/user-attachments/assets/130f1e6e-2937-4ca7-96f8-6e96c4b91d5c)
![Screenshot from 2024-10-11 08-36-41](https://github.com/user-attachments/assets/610079c0-c222-491b-b96e-3f9600dbb43c)

**Comment by jobenjada** [comment]
/award 50 thanks mate! Happy to have you participate :)

-------

### check out this hack to make 1050 points in 5 minutes: 

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74

---------

all side quests here, get em allll 👇

https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74

**Comment by ViditJain123** [comment]
@jobenjada how am I supposed to submit for this 1050 points side quest? I have opened an issue for that but seems like its not working..
