### ISSUE TITLE
[BUG] Error Loading Resources

### ISSUE THREAD

**Issue by PinHubGG** [formbricks/formbricks#3416]
### Issue Summary

Error Loading Resources
"This resource doesn't exist or you don't have the necessary rights to access it."

![image](https://github.com/user-attachments/assets/4cee1683-2028-4a6d-9438-087ed5201294)
![image (3)](https://github.com/user-attachments/assets/0f657524-a959-4457-9569-ce05c5d52048)

### Steps to Reproduce

Actions taken:
- Click new question in survey
- Start typing the question - after about 5-10 seconds it crashes. 

### Expected behavior

Expected to be able to add a new question without it failing. 

### Other information

Cleared cache/logged back in.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Node:
- npm:
```

**Comment by adityadeshlahre** [comment]
Hey @PinHubGG can you tell which route(URL) it is giving error ??

**Comment by PinHubGG** [comment]
> Hey @PinHubGG can you tell which route(URL) it is giving error ??

The URL i'm on when it crashes is:https://survey.pinhub.gg/environments/cm175gq57000611ymf65abqfb/surveys/cm19wc64c000010kb2hba7fns/edit

I never had this issue before - I've been able to create multiple surveys and edit them repeatedly. Not sure what changed....

**Comment by jobenjada** [comment]
@PinHubGG  is the issue showing up after an update?

pls try to remove the application storage (inspect -> Application -> Clear storage) and try again

**Comment by BadriVishalPadhy** [comment]
hey @jobenjada if the issue still persists plz assign this to me

**Comment by PinHubGG** [comment]
Issue resolved on its own...
