### ISSUE TITLE
[🕹️]Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by dehydrated-bear** [formbricks/formbricks#3418]
### What side quest or challenge are you solving?

Like & Re-Tweet oss.gg Launch Tweet

### Points

50

### Description

Like & Re-Tweet oss.gg Launch Tweet

### Provide proof that you've completed the task

![Screenshot 2024-10-11 071800](https://github.com/user-attachments/assets/81a7c24b-48e5-4962-9753-6878ebe035fe)

**Comment by heygogu** [comment]
![image](https://github.com/user-attachments/assets/04595f90-b7cf-4a6c-b6f0-a09f6cfdbaa6)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
