### ISSUE TITLE
[🕹️] Retweet and like side quest

### ISSUE THREAD

**Issue by heygogu** [formbricks/formbricks#3419]
### What side quest or challenge are you solving?

Like & Re-Tweet oss.gg Launch Tweet #3418

### Points

50

### Description

Just liked and retweeted the hacktoberfest launch tweet.

### Provide proof that you've completed the task

![Screenshot from 2024-10-11 07-39-42](https://github.com/user-attachments/assets/a88bc38c-ecc6-446e-950d-94e82d660caa)

**Comment by zakir19** [comment]
![Screenshot_2024-10-11-09-15-40-52_0b2fce7a16bf2b728d6ffa28c8d60efb](https://github.com/user-attachments/assets/16f2fb27-9481-4c3c-9d7c-28813f9c38c2)
done

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
