### ISSUE TITLE
[🕹️]Spread a word

### ISSUE THREAD

**Issue by phoenixdev100** [formbricks/formbricks#3420]
### What side quest or challenge are you solving?

Spread the word

### Points

50 per influencer

### Description

No response

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/82cb99c7-2548-4620-8bbb-9fae37a803ce)
@GrowthCoder7

**Comment by swamiabhishek45** [comment]
![Screenshot 2024-10-11 093625](https://github.com/user-attachments/assets/bbb835c4-1999-4a6f-986b-bb5e39793de5)

**Comment by jobenjada** [comment]
he already made the video, that doesnt count :D
