### ISSUE TITLE
[🕹️]Spread the word

### ISSUE THREAD

**Issue by Afsar16** [formbricks/formbricks#3422]
### What side quest or challenge are you solving?

Completed side quest - Spread the word, Comment under a video of your favorite developer influencer

### Points

50 per influencer(3 max)

### Description

![WhatsApp Image 2024-10-11 at 9 21 09 AM](https://github.com/user-attachments/assets/ea2c3e28-1d38-402f-b801-738a1b4c1dc1)
![WhatsApp Image 2024-10-11 at 9 21 09 AM (1)](https://github.com/user-attachments/assets/2b9f8e18-e35e-40c8-9fca-d19cf61841bb)
![WhatsApp Image 2024-10-11 at 9 21 10 AM](https://github.com/user-attachments/assets/0e73c131-b73e-4e8b-9432-25d9cdf2b601)

### Provide proof that you've completed the task

https://youtu.be/dqlO6_5rZSQ?si=EvTKqkwefs3HZvrZ

https://youtu.be/_uQrJ0TkZlc?si=KBAXx2mx-s0zKF_y

https://youtu.be/Hp9sTsiTZ_I?si=SKEstya1FTKF8cLY

**Comment by aryan7412** [comment]
<img width="1440" alt="Screenshot 2024-10-11 at 9 27 02 PM" src="https://github.com/user-attachments/assets/c3fe17ac-7f7c-4a83-b1be-66b8d17fcdc1">
https://www.youtube.com/watch?v=B-4eN1Pb7qo&t=2s

<img width="1440" alt="Screenshot 2024-10-11 at 9 26 29 PM" src="https://github.com/user-attachments/assets/9c628eb0-eca4-44d3-8e48-664f66b23144">
https://www.youtube.com/watch?v=zdZjr_ODWC8&t=1s

<img width="1440" alt="Screenshot 2024-10-11 at 9 25 14 PM" src="https://github.com/user-attachments/assets/8344d75b-99ad-4552-830c-39f5c71d32f1">
https://www.youtube.com/watch?v=S9CGGtwmdeE&t=70s

**Comment by aryan7412** [comment]
@Afsar16 Is this good to go?

**Comment by jobenjada** [comment]
/award 150

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
