### ISSUE TITLE
[🕹️] Sec Side Quest

### ISSUE THREAD

**Issue by luciferx77** [formbricks/formbricks#3423]
### What side quest or challenge are you solving?

ProductHunt & Alternative

### Points

150 + 150 ->  300

### Provide proof that you've completed the task

completed the quest :)

**Comment by atul-5242** [comment]
@luciferx77 Can you please provide more context about the issue.

**Comment by atul-5242** [comment]
Okay, @luciferx77, I understand your point about my contribution. I’m working on a small feature for ProductHunt, specifically for this page: https://www.producthunt.com/products/formbricks.

A minor issue is with the button text collapsing in the mobile view. The buttons should be displayed in a flex column on mobile devices:


![image](https://github.com/user-attachments/assets/a7865cb9-3ec0-453e-bec1-4f41c46a0cdd)

I plan to raise a PR for this within a few hours.

**Comment by luciferx77** [comment]
> Okay, @luciferx77, I understand your point about my contribution. I’m working on a small feature for ProductHunt, specifically for this page: https://www.producthunt.com/products/formbricks.
> 
> A minor issue is with the button text collapsing in the mobile view. The buttons should be displayed in a flex column on mobile devices:
> 
> ![image](https://private-user-images.githubusercontent.com/103453238/375627376-f016506e-4f1d-4f37-85d4-2f96fd135ac7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTk0OTEsIm5iZiI6MTcyODY1OTE5MSwicGF0aCI6Ii8xMDM0NTMyMzgvMzc1NjI3Mzc2LWYwMTY1MDZlLTRmMWQtNGYzNy04NWQ0LTJmOTZmZDEzNWFjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxNTA2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmIwNWQyY2Q2MjNlMDQ2ZmRjOGVhMDIzZDEwYzE5ZDljNWNkZWUxYjBlMmRhYjA3YjI0NzIyZDQ0ZjQ5ZmI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3HwSWzyTYqafLpDDAFzyge1Xp6jJgOcnHUa4R9yObk8)
> 
> I plan to raise a PR for this within a few hours.

bruh i raised this issue for my quest completion no need to raise a PR for this
