### ISSUE TITLE
[🕹️]Side Quest - Meme Magic

### ISSUE THREAD

**Issue by luciferx77** [formbricks/formbricks#3424]
### What side quest or challenge are you solving?

Craft a meme where a brick plays a role.

### Points

150

### Description

created a meme for formbricks where brick plays a role

### Provide proof that you've completed the task

https://x.com/ombhanushaliii/status/1844592421759484384

![image](https://github.com/user-attachments/assets/6e6e454b-dd7c-4ded-b9ff-f20bf1c1fc8f)

**Comment by vishalkhoje** [comment]
/assign

Please assign to me

**Comment by NitinSingh07** [comment]
Created a meme for formbricks where brick plays a role.

Proof : https://x.com/NitinThakur_07/status/1844605497753714816

![tweetimage](https://github.com/user-attachments/assets/f3be13a4-e4f3-49ac-8ec3-f694232bfe41)

**Comment by jobenjada** [comment]
/award 150

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
