### ISSUE TITLE
[BUG] I am going through formbricks website and at the last in Customer Highlights there 2 options are disable 

### ISSUE THREAD

**Issue by zakir19** [formbricks/formbricks#3425]
### Issue Summary

i have gone through website of Formbricks and i acknowledge that at the last ending of the page  in Customer Highlights section there are 2 option diasble remove them.

### Steps to Reproduce

1. Went to FormBrickswebsite
2. Clicked on Opinodo FLIX
3. Option is disable remove them

### Expected behavior

remove them

### Screenshots

![image](https://github.com/user-attachments/assets/e42cfab8-4bdb-4ca9-aaf2-e777933046fb)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Ayush-1110** [comment]
how can i get this page code from this repository

**Comment by zakir19** [comment]
> how can i get that home page code from this repository

This is submission if you want to access repo fork it

**Comment by zakir19** [comment]
> /assign
> Thnx for the rply but this is submission of bug as you can see

**Comment by zakir19** [comment]
This is submission of bug

**Comment by zakir19** [comment]
This is submission of bug
