### ISSUE TITLE
[🕹️] Formbricks Side Quest

### ISSUE THREAD

**Issue by NitinSingh07** [formbricks/formbricks#3426]
### What side quest or challenge are you solving?

Follow Formbricks page on LinkedIn and completing one side quest.

### Points

50

### Description

Completed my task by following Formbricks page on LinkedIn and retweeted the oss.gg tweet on X. 

### Provide proof that you've completed the task

![3404](https://github.com/user-attachments/assets/cf8d1b04-a615-4b90-bd0e-37faad7459f9)
![Repost](https://github.com/user-attachments/assets/15f0af33-e1c2-4577-994e-1b344479392a)

**Comment by jobenjada** [comment]
/award 100

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
