### ISSUE TITLE
[BUG] Loading Spinner inside a button

### ISSUE THREAD

**Issue by Khaan25** [formbricks/formbricks#3428]
### Issue Summary

When I logged into the app and went to create an organization.
When I clicked submit button, the loader spinner was over the text. 

Here's the URL: https://app.formbricks.com/setup/organization/create

I've attached a video of it as well.

https://github.com/user-attachments/assets/5b536152-6b1e-481a-ad45-1d04192c484a

### Steps to Reproduce

1. Login the app first time
2. create organization (https://app.formbricks.com/setup/organization/create)
3. You'll see loader spinner

NOTE: I've also seen similar behaviour when I invite any person to my organization and button has same spinner over the text. I believe it appears on all buttons.

### Expected behavior

We could go with one of the following:
- Spinner should be next to text inside button with a space between it and update the text from "Continue" -> "Saving" or "Submitting"
- Completely hide the text so we've spinner in the center.

### Screenshots

![image](https://github.com/user-attachments/assets/a39bf73d-8cc2-4de5-a10e-2e05b346c78c)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: Chrome
```

**Comment by Khaan25** [comment]
@jobenjada I can fix it as well - if you could assign this to me and allocate points because it's crucial and appears on almost every place. I can make sure it doesn't have again.

**Comment by Pushan2005** [comment]
This doesn't look like a bug, looks very intentional and in-place in my opinion. 

The loading spinner is doing it's intended job of indicating that the app is in a loading state.

The choice of having such a loading indicator is debatable but ultimately the decision lies with the design team/maintainers

**Comment by Khaan25** [comment]
but what if we hide the text behind it? Won't that look good?

**Comment by jobenjada** [comment]
whats the issue? I can see the loading spinner in the screenshot. Not sure I understand the issue

**Comment by jobenjada** [comment]
I agree, this is intentional, even your cursor changes :)
