### ISSUE TITLE
[🕹️] Side Quest : Design a Background

### ISSUE THREAD

**Issue by Tushnik1** [formbricks/formbricks#3429]
### What side quest or challenge are you solving?

Design a Background.

### Points

300

### Description

Created custom background in webp format, within the specific size.

To Download: https://raw.githubusercontent.com/Tushnik1/Hacktober-Background/refs/heads/main/Hacktober_Violet-sky.webp

File:  https://github.com/Tushnik1/Hacktober-Background/blob/main/Hacktober_Violet-sky.webp

### Provide proof that you've completed the task

![Screenshot 2024-10-11 101853](https://github.com/user-attachments/assets/da723c5e-7515-4dcc-acbe-b70f05db6597)

**Comment by jobenjada** [comment]
where did you find this image? Im asking to check copyrights

**Comment by Tushnik1** [comment]
@jobenjada I found the image from pexels free images section. Sorry I couldn't reply early because of some personal issue
