### ISSUE TITLE
[🕹️]Formbricks Side Quests

### ISSUE THREAD

**Issue by faheem2312** [formbricks/formbricks#3430]
### What side quest or challenge are you solving?

Formbricks quest not only will bring the support to the community but also makes us to learn how to be a good contributor for a non-code folks.

### Points

- Draft a billboard add:- 300
- Meme:-150
- Gif:-150
- LinkedIn(Social):-50
- Brickify famous personality:-150
- Spread the word(Youtube/X/LinkedIn):-150

### Description

I performed all the tasks as per my skillset

### Provide proof that you've completed the task

**Created billboard Ad**
![billboard ad](https://github.com/user-attachments/assets/aa75dcb3-bdcd-43d4-9a42-4f5b44f70755)

**Crafted Meme**
![meme](https://github.com/user-attachments/assets/e36b4e27-7cd7-44bd-8013-4766b2876875)

**Crafted gif**
![giffy](https://github.com/user-attachments/assets/85aee3db-cb84-4689-a2ae-7483d1185e0c)

**Followed on LinkedIn**
![Linkedin](https://github.com/user-attachments/assets/6cccd30d-f52b-4c99-ba8b-992e2a5607ca)

**Brickify someone famous** 
![brickify](https://github.com/user-attachments/assets/e8b49246-15b5-4359-b53d-7f42d861b4fd)

**Spread the word about oss.gg**
![video#1](https://github.com/user-attachments/assets/84cdf7a2-7fed-4529-be63-e82831ed10cb)
![video#2](https://github.com/user-attachments/assets/663e53ff-e04b-4aa2-9064-cd9d974940e4)
![video#3](https://github.com/user-attachments/assets/aa377181-ca03-46bb-bf0f-0126ec6d35df)

_**Thanks!!!**_

**Comment by faheem2312** [comment]
p

**Comment by jobenjada** [comment]
duplicate issue
