### ISSUE TITLE
[🕹️] Side Quest - Meme Magic

### ISSUE THREAD

**Issue by NitinSingh07** [formbricks/formbricks#3431]
### What side quest or challenge are you solving?

Craft a meme where a brick plays a role.

### Points

150

### Description

Created a meme for formbricks where brick plays a role

### Provide proof that you've completed the task

https://x.com/NitinThakur_07/status/1844605497753714816

![tweet](https://github.com/user-attachments/assets/c8e65f2f-047b-42b4-9b89-b3a9a82813bb)

**Comment by jobenjada** [comment]
how is that a meme? :D
