### ISSUE TITLE
[FEATURE] Use URL as state management

### ISSUE THREAD

**Issue by Khaan25** [formbricks/formbricks#3432]
### Is your feature request related to a problem? Please describe.

I've attached a video below.

If you select any industry or role, I would expect it to add that text to URL, maybe `?industry=SaaS` or `?role=sales`

https://github.com/user-attachments/assets/b762d08b-4cb2-4be4-8194-13dca21a1944

### Describe the solution you'd like

If I mistakenly refresh the page while I had filters, then it would be a tedious job to add all filters again.
We might wanan share the URL with someone, I could see exact filters as they have.

We can add state to URL, for example: 
I was on this page: https://app.formbricks.com/environments/cm24aeb7m0006swupqpi5bzft/surveys

so

https://app.formbricks.com/environments/cm24aeb7m0006swupqpi5bzft/surveys?industry=SaaS&role=sales

**Comment by jobenjada** [comment]
not really an issue 🤓  just adds complexity
