### ISSUE TITLE
[FEATURE] Reduce number of clicks

### ISSUE THREAD

**Issue by Khaan25** [formbricks/formbricks#3433]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/953140bc-ff43-4210-8c37-ad78f7abd1ed)

I wanted to create a survey and found myself clicking the card twice, which might annoy users who expect things to happen right away.

On this page [Survey Templates](https://app.formbricks.com/environments/cm24aeb7m0006swupqpi5bzft/surveys/templates), the button makes sense. But on this page [Surveys](https://app.formbricks.com/environments/cm24aeb7m0006swupqpi5bzft/surveys) (when we don't have any survey), it feels unnecessary. Removing it would make the process smoother.

### Describe the solution you'd like

I’d prefer to have the button visible inside the card by default instead of having to click to make it appear.

Alternatively, we could remove the button altogether and redirect to the relevant URL when the card is clicked. That would align better with my expectations.

We can use a boolean to determine whether to show the button by default or not. (for 2 pages above)

**Comment by jobenjada** [comment]
hey :) we need the second click because normally we show the template on the right hand side. Just the first time we dont. But thanks for thinking along :)
