### ISSUE TITLE
[🕹️] Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by PraveenRepswal** [formbricks/formbricks#3434]
### What side quest or challenge are you solving?

I have completed the Like & Re-Tweet oss.gg Launch Tweet side quest

### Points

50

### Description

Link of the twitter post: https://x.com/P_K_REPSWAL/status/1844623546905133327

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/7766d5e9-d10b-4d51-a394-103aafa70d4d)

Link of the twitter post: https://x.com/P_K_REPSWAL/status/1844623546905133327

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
