### ISSUE TITLE
[🕹️] Side Quest - Meme Magic 

### ISSUE THREAD

**Issue by Suryadev78** [formbricks/formbricks#3435]
### What side quest or challenge are you solving?

Craft a meme where a brick plays a role.

### Points

150

### Description

Created a meme for formbricks where brick plays a role

### Provide proof that you've completed the task

https://x.com/suryadev_78/status/1844625026277884187
![Screenshot (68)](https://github.com/user-attachments/assets/427461a3-dd28-4184-8703-2fac02195d15)

**Comment by ishwarthecodddr** [comment]
but what is the issue

**Comment by jobenjada** [comment]
/award 150

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
