### ISSUE TITLE
[🕹️] Retweet and sidelike Quest

### ISSUE THREAD

**Issue by Suryadev78** [formbricks/formbricks#3436]
### What side quest or challenge are you solving?

Retweet and Sidelike Quest

### Points

50

### Description

I have successfully completed the Retweet and sidelike quest

### Provide proof that you've completed the task

https://www.linkedin.com/posts/suryadev-pandey_hacktoberfest-activity-7250396153408634880-WAqr?utm_source=share&utm_medium=member_desktop

![Screenshot (69)](https://github.com/user-attachments/assets/3807e25a-e7e2-48e6-9e2e-6248b94b75f0)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
