### ISSUE TITLE
[🕹️]Retweet and Like Side Quest

### ISSUE THREAD

**Issue by Sulochan-khadka** [formbricks/formbricks#3437]
### What side quest or challenge are you solving?

Retweet and Like

### Points

50 points

### Description

Link for the reference:
https://x.com/Sulochan_khadka/status/1844633028544385119

### Provide proof that you've completed the task

Like Proof:
<img width="1435" alt="Screenshot 2024-10-11 at 12 26 13 PM" src="https://github.com/user-attachments/assets/00aee2ab-2de2-4031-aaec-389487816ddb">

Retweet Proof:
<img width="1435" alt="Screenshot 2024-10-11 at 12 26 40 PM" src="https://github.com/user-attachments/assets/8037757e-736e-493f-8667-9f17db16a643">

**Comment by azamshaikh1103** [comment]
Hey @Sulochan-khadka, will it be counted as hactoberfest contribution?

**Comment by himanjalsaha** [comment]
![image](https://github.com/user-attachments/assets/212c7819-8ea7-4c65-9544-ccdbe7732989)

liked and retweeted!!

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
