### ISSUE TITLE
[🕹️]Upvote and comment on Reddit launch thread

### ISSUE THREAD

**Issue by Sulochan-khadka** [formbricks/formbricks#3438]
### What side quest or challenge are you solving?

Upvote and comment on Reddit launch thread

### Points

50

### Description

Upvoted and commented

### Provide proof that you've completed the task

<img width="1435" alt="Screenshot 2024-10-11 at 12 36 34 PM" src="https://github.com/user-attachments/assets/6e6da57a-606d-4f36-b6e5-6f885713f204">
<img width="1435" alt="Screenshot 2024-10-11 at 12 37 05 PM" src="https://github.com/user-attachments/assets/4cbe6a30-f56d-489e-81d2-25895afd0159">

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
