### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by Sulochan-khadka** [formbricks/formbricks#3439]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page

### Points

50

### Description

Followed as mentioned

### Provide proof that you've completed the task

<img width="1435" alt="Screenshot 2024-10-11 at 12 44 30 PM" src="https://github.com/user-attachments/assets/f8e69ecd-88aa-48ac-9b46-b37337532970">

**Comment by Souvik-tech** [comment]
![Screenshot 2024-10-11 125322](https://github.com/user-attachments/assets/36177d74-b6f2-427c-90e8-a96c26569792)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
