### ISSUE TITLE
[🕹️]Get 5 friends to star our repos

### ISSUE THREAD

**Issue by ViditJain123** [formbricks/formbricks#3441]
### What side quest or challenge are you solving?

I made 5 of my friends star all the 7 repos

### Points

1050

### Description

I made 5 of my friends star all the 7 repos

### Provide proof that you've completed the task

![IMG-20241011-WA0078](https://github.com/user-attachments/assets/09c430a0-7cca-4731-bb7a-d2db7b8650ca)
![IMG-20241011-WA0079](https://github.com/user-attachments/assets/a82f4fa9-7f37-4738-a098-27c340cc7349)
![WhatsApp Image 2024-10-11 at 11 28 28_bdc4d2f6](https://github.com/user-attachments/assets/3557d1c9-429e-49fb-9261-d6a00aad0bee)
![WhatsApp Image 2024-10-11 at 11 28 29_d5719841](https://github.com/user-attachments/assets/bb1a642d-5123-44de-8d05-ad3bb98179e3)
![WhatsApp Image 2024-10-11 at 13 28 22_bb87f025](https://github.com/user-attachments/assets/0494ac1d-bf28-4283-b9ba-7a94a804510b)
![WhatsApp Image 2024-10-11 at 13 28 23_e321ddc9](https://github.com/user-attachments/assets/c89a15ad-ee90-47a2-999b-c546565ec451)
![WhatsApp Image 2024-10-11 at 13 29 30_90ca3991](https://github.com/user-attachments/assets/5290809b-1364-4f67-81c4-498bf286221e)
![IMG-20241011-WA0039](https://github.com/user-attachments/assets/ab5e136d-7c1d-4273-a482-4cbd8c661728)
![IMG-20241011-WA0040](https://github.com/user-attachments/assets/1a50430d-6d0c-4b0d-92cf-358eea0569d2)
![IMG-20241011-WA0041](https://github.com/user-attachments/assets/010f43d1-6334-41ba-91d5-f922af9fb108)
![IMG-20241011-WA0042](https://github.com/user-attachments/assets/2c040723-cc7c-48ff-b5cd-cf0fa3761fda)
![IMG-20241011-WA0043](https://github.com/user-attachments/assets/c7e3d020-5679-4d90-934e-9b6acf6c286e)
![IMG-20241011-WA0049](https://github.com/user-attachments/assets/2f30b214-5455-4b86-881e-706f1117a68f)
![IMG-20241011-WA0050](https://github.com/user-attachments/assets/20b6b6f6-1c21-46da-953a-a4fbffb8c08d)
![IMG-20241011-WA0051](https://github.com/user-attachments/assets/919ce1b5-3736-4d4d-bc8b-1b107abe57c6)
![IMG-20241011-WA0052](https://github.com/user-attachments/assets/949dcb1d-378e-43bb-97a2-51b20a38dd09)
![IMG-20241011-WA0053](https://github.com/user-attachments/assets/9086c5fe-eb71-4666-9b7b-9d807260868a)
![IMG-20241011-WA0054](https://github.com/user-attachments/assets/fc1eb307-e6c0-4cfc-8fdc-296caff2067b)
![IMG-20241011-WA0055](https://github.com/user-attachments/assets/9868e652-6402-4825-a6e8-b3a7aeddfa1d)
![IMG-20241011-WA0066](https://github.com/user-attachments/assets/1d74d319-56fb-47ef-863c-ac602c294461)
![IMG-20241011-WA0067](https://github.com/user-attachments/assets/3723722b-174e-4f81-bce8-4686a94e63a0)
![IMG-20241011-WA0068](https://github.com/user-attachments/assets/0ac858d7-511c-48db-9863-0112c2b80c36)
![IMG-20241011-WA0069](https://github.com/user-attachments/assets/f26bb74a-f163-4275-b2ff-b5a76b46f4e9)
![IMG-20241011-WA0070](https://github.com/user-attachments/assets/24060400-d252-4d5f-b148-490f11506d3e)
![IMG-20241011-WA0071](https://github.com/user-attachments/assets/cdee3792-78b7-4c24-8b67-d5785ffd244b)
![IMG-20241011-WA0072](https://github.com/user-attachments/assets/3bd6b73b-d1a2-4200-93f9-a6d4efe158e0)
![IMG-20241011-WA0073](https://github.com/user-attachments/assets/c88b1ac1-da9b-4994-930e-a5479ce6ac1c)
![IMG-20241011-WA0074](https://github.com/user-attachments/assets/6091077d-18d1-465a-9e18-19e86a04401c)
![IMG-20241011-WA0075](https://github.com/user-attachments/assets/a3d99416-a013-4d94-a288-7266de0a728f)
![IMG-20241011-WA0076](https://github.com/user-attachments/assets/393d1bb2-410c-4f72-ad43-acbcad238303)
![IMG-20241011-WA0077](https://github.com/user-attachments/assets/c21bccb4-67a6-4a43-945b-67a581afd559)

**Comment by jobenjada** [comment]
/award 1050

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
