### ISSUE TITLE
[🕹️]  Follow Formbricks LinkedIn Page and  Gif Magic 

### ISSUE THREAD

**Issue by naaa760** [formbricks/formbricks#3442]
### What side quest or challenge are you solving?

Followed Formbricks LinkedIn, Twitter Page, and GIF Magic on GIPHY.

### Points

200

### Description

https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdW9oMDQwaTdyZjNoY283a2I1aWsxdG9jY3JsaXJja245anhyM2R3bCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/B4EmOYAx9jjmLS7krh/giphy.gif

### Provide proof that you've completed the task

Linkedln Screenshot

![Screenshot from 2024-10-11 13-32-21](https://github.com/user-attachments/assets/61af2240-fb6b-4024-b495-108df5769e7a)

GIPHY ScreenShot

![Screenshot from 2024-10-11 13-24-22](https://github.com/user-attachments/assets/d7aa2190-8649-4585-8c71-0e0a2cd7a8eb)

**Comment by ish-gpt** [comment]
![Screenshot from 2024-10-11 15-10-20](https://github.com/user-attachments/assets/5ea1f1b7-6e6d-46e6-9077-2be8de8a7592)
![Screenshot from 2024-10-11 14-51-25](https://github.com/user-attachments/assets/4f580729-fafc-47c1-b245-4088783af7d6)

**Comment by jobenjada** [comment]
/award 250

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
