### ISSUE TITLE
[🕹️]Upvote and comment of reddit post!

### ISSUE THREAD

**Issue by ViditJain123** [formbricks/formbricks#3443]
### What side quest or challenge are you solving?

I upvoted and commented on reddit post!

### Points

50

### Description

I upvoted and commented on reddit post!

### Provide proof that you've completed the task

![Screenshot (52)](https://github.com/user-attachments/assets/c9a919ed-f403-40c0-a719-e5b5e4fb2b0e)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
