### ISSUE TITLE
[🕹️] UI Breaks for Input Type Options in Survey Creation

### ISSUE THREAD

**Issue by Devmanwani** [formbricks/formbricks#3445]
### What side quest or challenge are you solving?

Bug Hunter

### Points

150

### Description

When creating a survey and selecting the option to create a survey from scratch, I've encountered a responsive design issue. Specifically, the input type UI breaks when viewed on screen widths between 770px and 930px.

Steps to Reproduce:

Navigate to the survey creation page.
Select "Create Survey from Scratch."
Observe the input type options.

### Provide proof that you've completed the task

![formbricks](https://github.com/user-attachments/assets/027771b2-af52-4191-b4db-7d98c5c4aedf)

**Comment by jobenjada** [comment]
/award 50

there are looooots of responsiveness issues, we will tackle them all at once down the line :)
