### ISSUE TITLE
[🕹️]Retweet and Like Side Quest

### ISSUE THREAD

**Issue by ishwarthecodddr** [formbricks/formbricks#3446]
### What side quest or challenge are you solving?

Retweet and Like

### Points

50 points

### Description

Retweeted and liked the launch post by oss.gg
Link for the reference:
 https://x.com/IThecoder32719/status/1844669189753077996

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/443b431b-5e4e-4c33-822b-266fdd95241f)

**Comment by SayanBasani** [comment]
![Uploading Screenshot 2024-10-11 152429.png…]()

**Comment by shindebhavika** [comment]
![WhatsApp Image 2024-10-11 at 15 26 31](https://github.com/user-attachments/assets/425efc78-f8c2-4f3e-8a53-c805ab79cd52)
![WhatsApp Image 2024-10-11 at 15 27 04](https://github.com/user-attachments/assets/16240383-823c-40fb-a12d-c1a1f46ddd69)

**Comment by shindebhavika** [comment]
@ishwarthecodddr  is this okay, actually i am new to open source. guide me if i am wrong.

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
