### ISSUE TITLE
[🕹️]Upvote and comment on Reddit launch thread

### ISSUE THREAD

**Issue by ishwarthecodddr** [formbricks/formbricks#3447]
### What side quest or challenge are you solving?

Upvote and comment on [Reddit launch thread](https://www.reddit.com/r/opensource/comments/1ftwbl9/weve_spent_a_few_months_building_ossgg_to_gamify/)

### Points

50

### Description

Upvoted and commented on the reddit post by oss.gg

### Provide proof that you've completed the task

Upvote-proof:
![image](https://github.com/user-attachments/assets/1ea73517-e897-4e8b-8b91-bd0d5644df3e)
Comment-proof:
![image](https://github.com/user-attachments/assets/3131c121-42a6-4689-900c-284671355071)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
