### ISSUE TITLE
[BUG] Issue with dropdowns on the docs page

### ISSUE THREAD

**Issue by DivyanshuLohani** [formbricks/formbricks#3451]
### Issue Summary

When on this page https://formbricks.com/docs/introduction/what-is-formbricks if we try to click two headers with same name and one is open then the previous one is closed and new one is not opened it behaves as a reference to that element
Also the blue stick navigation issue is already mentioned in #3317

https://github.com/user-attachments/assets/d4504278-869a-4f02-bb08-5bf4b48852bf

### Steps to Reproduce

Step 1: Go To the docs page
Step 2: Open Features header listed under the Link Surveys
Steo 3: Click on Fetures header listed under the Websites and App Surveys

### Expected behavior

The features header under Link Surveys should close and the features header under Websites and App surveys should open 

But first one closes and nothing happens and new one stays in a glitched state

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Aryant01** [comment]
I am interested to work on this issue.

**Comment by DivyanshuLohani** [comment]
Sorry but I forgot to mark this for OSS.gg I can you please do that?
