### ISSUE TITLE
[🕹️]Upvote and comment on Reddit launch thread

### ISSUE THREAD

**Issue by Sahil-Gupta584** [formbricks/formbricks#3452]
### What side quest or challenge are you solving?

Upvote and comment on [Reddit launch thread](https://www.reddit.com/r/opensource/comments/1ftwbl9/weve_spent_a_few_months_building_ossgg_to_gamify/)

### Points

50

### Provide proof that you've completed the task

Upvote:-
![Screenshot_20241011_153543](https://github.com/user-attachments/assets/37cc6277-2434-46a5-9872-cbada191ec49)

Comment(last one) :-
![Screenshot_20241011_153559](https://github.com/user-attachments/assets/ba7aa5ef-f702-4a57-a83a-63b15feec03a)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
