### ISSUE TITLE
[🕹️]Retweeet and like Side Quest

### ISSUE THREAD

**Issue by sohelhussain** [formbricks/formbricks#3454]
### What side quest or challenge are you solving?

like and retweeting

### Points

50 points

### Description

By retweeting and liking my post, you're not only supporting me but also helping spread the word about the importance of open-source contributions! Together, we can inspire more people to join this incredible movement! 

### Provide proof that you've completed the task

<img width="702" alt="Screenshot 2024-10-11 at 3 47 25 PM" src="https://github.com/user-attachments/assets/f092683b-e4da-426f-acb8-74a89aa5a9d9">

**Comment by swamiabhishek45** [comment]
![Screenshot 2024-10-11 161652](https://github.com/user-attachments/assets/4a605161-1439-4d75-8205-7fb5ad22b45c)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
