### ISSUE TITLE
[🕹️]Retweet and like the launch post

### ISSUE THREAD

**Issue by AAvi09** [formbricks/formbricks#3455]
### What side quest or challenge are you solving?

retweet and like side quest

### Points

50

### Description

retweeted and liked the launch post and side quest

### Provide proof that you've completed the task

link for reference
https://x.com/Avinash28876705/status/1844686203104252011
![proof sq](https://github.com/user-attachments/assets/72087773-ad7a-4d2c-9970-2780e805970c)

**Comment by shindebhavika** [comment]
@AAvi09  can you please kindly close this issue.

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
