### ISSUE TITLE
[🕹️]Retweet and like side Quest

### ISSUE THREAD

**Issue by muaaz-raza-dev** [formbricks/formbricks#3458]
### What side quest or challenge are you solving?

![Screenshot Capture - 2024-10-11 - 15-48-40](https://github.com/user-attachments/assets/2a28fdd1-b597-4b30-b79f-26877709525f)

### Points

50

### Description

By retweeting and liking my post, you're not only supporting me but also helping spread the word about the importance of open-source contributions! Together, we can inspire more people to join this incredible movement!

### Provide proof that you've completed the task

![Screenshot Capture - 2024-10-11 - 15-48-40](https://github.com/user-attachments/assets/2a28fdd1-b597-4b30-b79f-26877709525f)

**Comment by muaaz-raza-dev** [comment]
\assign

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)

**Comment by syedahmedrz** [comment]
@muaaz-raza-dev 

> @muaaz-raza-dev, Just a little reminder: Please open a draft PR linking this issue within 12 hours. If we can't detect a PR in 12h, you will be unassigned automatically.
