### ISSUE TITLE
[🕹️]Retweet and Like Side Quest

### ISSUE THREAD

**Issue by omprakash987** [formbricks/formbricks#3461]
### What side quest or challenge are you solving?

Retweet and Like

### Points

50

### Description

Retweeted and liked the launch post by oss.gg
Link for the reference:

### Provide proof that you've completed the task

https://x.com/Omprakash82627/status/1844695195398328747

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
