### ISSUE TITLE
[🕹️]Spread the word (50 per influencer, max. 3 influencers): Comment under a video of your favorite developer influencer to cover the oss.gg hackathon in their next video.

### ISSUE THREAD

**Issue by Sahil-Gupta584** [formbricks/formbricks#3464]
### What side quest or challenge are you solving?

Spread the word (50 per influencer, max. 3 influencers): Comment under a video of your favorite developer influencer to cover the oss.gg hackathon in their next video.

### Points

150

### Description

Commenting under a video of favorite developer influencer to cover the [oss.gg](http://oss.gg/) hackathon in their next video.

### Provide proof that you've completed the task

My you tube profile:-
![Screenshot_20241011_171852](https://github.com/user-attachments/assets/edb591d3-231c-4225-af87-fce44aa30cba)

Developer 1:-
Video link: https://youtu.be/q3fktcOEU3M?si=4wngZ7efk_suz0bI

![Screenshot_20241011_171401](https://github.com/user-attachments/assets/ef4d180a-df3a-4a17-b22f-8f607197eb21)

Developer 2:-
 Video link : https://youtu.be/lxqHg7Uckmg?si=MnzpXmd3kgasz-1j

![Screenshot_20241011_171300](https://github.com/user-attachments/assets/c1bfe90d-84d8-4822-92b6-f960d699782c)

Developer 3:-
Video link:https://youtu.be/mkHgwPkfqmw?si=QXTTx1dtHc4no5tP

![Screenshot_20241011_155221](https://github.com/user-attachments/assets/6ed60190-f4d4-45c7-bd6e-a11a5eed0aa7)

**Comment by jobenjada** [comment]
/award 150

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
