### ISSUE TITLE
[🕹️]Meme Magic (150 Points):  Craft a meme where a brick plays a role. Tweet it, and tag us @formbricks to submit.

### ISSUE THREAD

**Issue by Sahil-Gupta584** [formbricks/formbricks#3466]
### What side quest or challenge are you solving?

Meme Magic (150 Points): 
Craft a meme where a brick plays a role. Tweet it, and tag us @formbricks to submit.

### Points

150

### Provide proof that you've completed the task

Tweet :-
Link: https://x.com/guptas3067/status/1844711481360929130

![Screenshot_20241011_173756](https://github.com/user-attachments/assets/21335335-bc77-4dc0-a4c8-abf31181fcd0)

**Comment by jobenjada** [comment]
whattt? 😂
