### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page (50 Points):

### ISSUE THREAD

**Issue by Sahil-Gupta584** [formbricks/formbricks#3467]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page (50 Points):

### Points

50

### Provide proof that you've completed the task

![Screenshot_20241011_174403](https://github.com/user-attachments/assets/a6ea003d-af21-4dd9-a1df-0879df2ca174)

**Comment by prathamesh0987** [comment]
[🕹️] Follow Formbricks LinkedIn Page Completed #3467

Description
I have followed the Formbricks LinkedIn Page through the profile (https://www.linkedin.com/in/prathamesh-vagare-63968b210/)

I have provided the proof of task completion

screenshot:
![screenshot](https://github.com/user-attachments/assets/e290a1b7-6df3-42d0-9450-ae3ac82b2cb9)

**Comment by vdhruvannaidu** [comment]
![Uploading Screenshot_2024-10-11-22-14-11-341_com.linkedin.android.jpg…]()

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
