### ISSUE TITLE
[🕹️]  Like & Retweet oss.gg launch tweet 

### ISSUE THREAD

**Issue by aritradevelops** [formbricks/formbricks#3468]
### What side quest or challenge are you solving?

Like and retweet [Like & Re-Tweet oss.gg Launch Tweet](https://x.com/ossgoodgame/status/1841019549183066552)

### Points

50

### Description

Liked the oss.gg Launch Tweet and Re-twitted it.

### Provide proof that you've completed the task

<img width="606" alt="image" src="https://github.com/user-attachments/assets/600f2bfa-f40a-4c29-b281-f166b10bda4d">

[link to post](https://x.com/AritraDevelops/status/1844716329284088014)

**Comment by aritradevelops** [comment]
@konarksharma2001 why are you assigning yourself?

**Comment by konarksharma2001** [comment]
By mistake added comment here @aritradevelops

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
