### ISSUE TITLE
[🕹️]Retweet and like Side Quest

### ISSUE THREAD

**Issue by rohitmak** [formbricks/formbricks#3469]
### What side quest or challenge are you solving?

![image](https://github.com/user-attachments/assets/0b7f431b-b33a-42e3-b441-78388a429dbe)

### Points

50 Points

### Description

Retweeted and liked the oss launch tweet.

### Provide proof that you've completed the task

Link to the Retweet: https://x.com/ossgoodgame/status/1841019549183066552

**Comment by SanjuRohilla** [comment]
![Screenshot 2024-10-11 182017](https://github.com/user-attachments/assets/8c0dc3c0-eef8-4912-88a9-d7b3d22a66cd)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
