### ISSUE TITLE
[IMPROVEMENT] Revamp Question Card UI

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#347]
We discussed the neede changes in the [Formbricks Design Repository](https://github.com/formbricks/design/issues/16).

Here is the final version of changes we'll make this time:

![grafik](https://github.com/formbricks/formbricks/assets/72809645/c9342ab3-50a7-4f86-bcf4-f18441b82c04)

**Note:** The UI is a mock up. Keep the overall look of the current Question Card and only make the following changes:

1. Create new top card menu with 4 actions: Duplocate, Delete, Move Up, Move Down
2. Hide the "Description" by default **unless the Template contains a description.** Also reuse the input field from the Options with the Trash Icon so that users can remove the description field again:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/215f0342-8bd3-4ec1-a7e2-44a3e85f40a5)
3. Next to the Trash can, add a button with a Plus icon. This button adds an option directly below the option where the button was clicked.
4. Change the styling and copy of the "Add Other with specify" button accordingly
5. Move the following in the Advanced settings: Button text, Add Logic Button, Question ID. When the user chose to Add logic, add it **above** the "Advanced settings" collapsible where it currently is positioned.
6. Add the "Required" toggle to the bottom of the card.

If you get an idea during the development, feel free to reach out on Discord to discuss it :)

Thanks for taking up this issue! 🙌

**Comment by Ashutosh-Bhadauriya** [comment]
@jobenjada can you please assign this issue to me?
