### ISSUE TITLE
[🕹️]Retweet and Like the side Quest

### ISSUE THREAD

**Issue by Devang0907** [formbricks/formbricks#3470]
### What side quest or challenge are you solving?

![x](https://github.com/user-attachments/assets/fd1daaf4-4826-4e31-91ad-0ad23887f7ef)

### Points

50

### Provide proof that you've completed the task

![x](https://github.com/user-attachments/assets/a493a9cb-2cce-40ad-af03-7614c2cae114)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
