### ISSUE TITLE
[🕹️] Like & Retweet oss.gg launch tweet

### ISSUE THREAD

**Issue by Emmarie-Ahtunan** [formbricks/formbricks#3471]
### What side quest or challenge are you solving?

[Like & Re-Tweet oss.gg Launch Tweet](https://x.com/shemmariea/status/1844740034664255756)

### Points

50

### Description

Liked the oss.gg Launch Tweet and Reposted it.

### Provide proof that you've completed the task

![Screenshot 2024-10-11 at 10 01 29 AM](https://github.com/user-attachments/assets/f7147318-8a3d-43ed-865f-415604c3d6e3)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
