### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page - Side Quest

### ISSUE THREAD

**Issue by Nisarg-Sha** [formbricks/formbricks#3472]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page

### Points

50

### Provide proof that you've completed the task

<img width="1506" alt="Screenshot 2024-10-11 at 7 41 29 PM" src="https://github.com/user-attachments/assets/b53def73-bc2b-44c9-ba73-294f82e599f3">

**Comment by Krish-Prajapati** [comment]
> Assigned to @Krish-Prajapati! Please open a draft PR linking this issue within 48h ⚠️ If we can't detect a PR from you linking this issue in 48h, you'll be unassigned automatically 🕹️ Excited to have you ship this 🚀

3472
I have completed this step. 
You can check the screenshot clipped below and you can also checkout my profile ( www.linkedin.com/in/krish-prajapati-0b765a256 )
![image](https://github.com/user-attachments/assets/9dd37a87-dc87-4c7a-a7b0-18033769f873)

**Comment by vdhruvannaidu** [comment]
@Nisarg-Sha I have also completed the task. Will every person get the points or only the first person completing the task?
![image](https://github.com/user-attachments/assets/5b6cd547-7ef5-4283-9565-1ee0971d283e)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
