### ISSUE TITLE
[🕹️] Design a background

### ISSUE THREAD

**Issue by Kritikaadhikarii** [formbricks/formbricks#3473]
### What side quest or challenge are you solving?

[🕹️] Design a background

### Points

300

### Description

I've manually designed a wallpaper, using figma, if required, I can provide the design file too. For now, I've attached the image

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/d2e510c7-2670-4bf5-923c-4af5ee2dbf4f)

Since,webp files weren't supported here, for now, I'll upload a png file.
![Desktop - 1 (5)](https://github.com/user-attachments/assets/5938ffc6-e281-431d-b9a0-efec55e5e00d)

**Comment by jobenjada** [comment]
hey :) Thanks!!

Where did you find this pattern? Or did you make it?

**Comment by Kritikaadhikarii** [comment]
> hey :) Thanks!!
> 
> Where did you find this pattern? Or did you make it?

It was made by taking inspiration of WhatsApp and telegram. I made it manually; I can share the Figma link of if you'd want that.

**Comment by jobenjada** [comment]
/award 300 

great work, will add it later on!

thanks for playing :) keep collecting points to increase your chances of winning!
