### ISSUE TITLE
[🕹️]Follow Formbricks X (twitter) Page - Side Quest

### ISSUE THREAD

**Issue by Nisarg-Sha** [formbricks/formbricks#3474]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://x.com/formbricks) Page

### Points

50

### Provide proof that you've completed the task

<img width="1512" alt="Screenshot 2024-10-11 at 7 55 20 PM" src="https://github.com/user-attachments/assets/ce2e4c20-cb8c-4e9f-ae9c-e2acf8abe99d">

**Comment by prtkjakhar** [comment]
### Proof:
![Screenshot 2024-10-11 at 7 58 36 PM](https://github.com/user-attachments/assets/e6b234b4-857c-4077-9fb6-7814a9a3ddc6)

**Comment by SrinivasReddy78** [comment]
![image](https://github.com/user-attachments/assets/72a81934-355c-46ca-a88f-2d0364296202)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
