### ISSUE TITLE
[🕹️] San Francisco Billboard Ad

### ISSUE THREAD

**Issue by Kritikaadhikarii** [formbricks/formbricks#3477]
### What side quest or challenge are you solving?

[🕹️] San Francisco Billboard Ad

### Points

300

### Description

I've designed a San Francisco Billboard Ad. Content can be changed as per preference. Also, I made it in figma.

### Provide proof that you've completed the task

![Group 1148](https://github.com/user-attachments/assets/87d8f2df-8878-4132-aacd-f9c8d51973cd)

**Comment by jobenjada** [comment]
/award 300

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
