### ISSUE TITLE
[BUG] Make "Imprint | Privacy Policy | Report Survey" link on product example on the Landing page Labels: oss.gg

### ISSUE THREAD

**Issue by jerry-xon** [formbricks/formbricks#3478]
### Issue Summary

On the Landing page of Formbricks, under the form example section 3 links are not visible 
1.Imprint
2.Privacy Policy
3.Report Survey

<img width="1440" alt="Screenshot 2024-10-11 at 20 04 20" src="https://github.com/user-attachments/assets/9423395e-b96e-4c51-a97e-1cce149d29f3">

Make these link visible and add some padding at top for positioning.

### Steps to Reproduce

1. Visit the Formbricks.com 
2. Scroll down to see Digital Product User Journey (Example form)
3. Focus on the bottom of the form to see 3 links

### Expected behavior

The expected behaviour should make the links visible to the user and should not intersect the form, should be more below the form.

### Screenshots

<img width="1440" alt="Screenshot 2024-10-11 at 20 04 20" src="https://github.com/user-attachments/assets/7b0aab50-25c8-440e-9185-7ef0e85168bb">

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: MacOs
- Browser: safari
```

**Comment by jobenjada** [comment]
the landing page is not part of the hackathon!
