### ISSUE TITLE
[🕹️] Added Retweet Link for oss.gg Hackathon Kick-off 🧱

### ISSUE THREAD

**Issue by sucessdy** [formbricks/formbricks#3479]
### What side quest or challenge are you solving?

Like & Re-Tweet oss.gg Launch Tweet (50 Points)

<img width="488" alt="Screenshot 2024-10-11 at 8 17 14 PM" src="https://github.com/user-attachments/assets/8f1bccc5-0b29-4b54-825d-3a02284d852e">

### Points

50

### Description

I completed the task of liking and retweeting the oss.gg Hackathon kick-off tweet with a 🧱 emoji as part of the Hacktoberfest side quest.

### Provide proof that you've completed the task

<img width="488" alt="Screenshot 2024-10-11 at 8 17 14 PM" src="https://github.com/user-attachments/assets/a8fbeba6-8f5a-4577-9804-5bfa212c1399">

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
