### ISSUE TITLE
[🕹️]  Like & Re-Tweet oss.gg Launch Tweet (50 Points)   

### ISSUE THREAD

**Issue by Sundaram-rathor** [formbricks/formbricks#3480]
### What side quest or challenge are you solving?

Like & Re-Tweet oss.gg Launch Tweet (50 Points)

### Points

Points 50 

### Description

I completed the task of liking and retweeting the oss.gg Hackathon kick-off tweet with a 🧱 emoji as part of the Hacktoberfest side quest.

### Provide proof that you've completed the task

![Screenshot 2024-10-11 203428](https://github.com/user-attachments/assets/56d919ea-124b-42b0-8cc7-787dd1a2776d)

**Comment by vdhruvannaidu** [comment]
@Sundaram-rathor I have Liked & Re-Tweet oss.gg Launch Tweet. How do i submit a proof. Just a screenshot or anything else i need to do?
![image](https://github.com/user-attachments/assets/f64dfc1b-738f-4f27-ad85-e8cba80d7052)

**Comment by Anil7083** [comment]
🚀 Excited to announce the launch of OSS.gg! 🎉
Your go-to platform for open-source contributions and projects. Let's build together and make an impact! 💻✨
Like ❤️ & Re-Tweet 🔁 to spread the word! #OSS #OpenSource #TechCommunity

Feel free to adjust it to fit your style!
![hack](https://github.com/user-attachments/assets/9504511c-ee74-4354-bd20-c0abaee55acc)

**Comment by Ritesh2351235** [comment]
![Image 11-10-24 at 9 50 PM](https://github.com/user-attachments/assets/cb36b0e2-2c29-4968-9bb3-d8cfd38587aa)
I have Liked & Re-Tweet oss.gg Launch Tweet @Sundaram-rathor

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
