### ISSUE TITLE
[🕹️] Like & Retweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by AliYar-Khan** [formbricks/formbricks#3484]
### What side quest or challenge are you solving?

Like and retweet the oss.gg launch tweet

### Points

50

### Description

I completed the task of liking and retweeting the oss.gg as part of the Hacktoberfest side quest.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/ec5732af-4c65-425c-a110-e5ee65ae89f1)

**Comment by mitgajera** [comment]
What side quest or challenge are you solving?
retweet and like side quest

Points
50

**Description**
retweeted and liked the launch post and side quest

Provide proof that you've completed the task
link for reference: https://x.com/ossgoodgame/status/1841019549183066552

![Screenshot 2024-10-11 222801](https://github.com/user-attachments/assets/f1595e7b-133d-4634-889b-5e21fd7eaac8)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
