### ISSUE TITLE
[🕹️] Upvote and comment on Reddit launch thread

### ISSUE THREAD

**Issue by AliYar-Khan** [formbricks/formbricks#3489]
### What side quest or challenge are you solving?

Upvote and comment on [Reddit launch thread](https://www.reddit.com/r/opensource/comments/1ftwbl9/weve_spent_a_few_months_building_ossgg_to_gamify/)

### Points

50

### Description

I have upvoted and commented on the reddit launch post

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/d33af4a5-cb0e-4ede-8ec9-cc996f161afa)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
