### ISSUE TITLE
[FEATURE] As a user I want to delete my account

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#349]
**Is your feature request related to a problem? Please describe.**
Add an option to Profile Settings to delete the account.

**Describe the solution you'd like**
Delete Account Option

**Additional context**
The tricky part is the handling of memberships and teams. If the user is the only member of a team, delete the team with the user but if the account has multiple members:

Solution: Make the first admin that can be found to the new owner of the team.

If no admin is in the team, reject the delete account request with the reason that he needs to appoint an admin to the team first.

**Comment by fdis111** [comment]
Hi @jobenjada, can you assign me this task please.

**Comment by jobenjada** [comment]
Assgined. Please let me know approx. we you think you can finish your contribution :)
