### ISSUE TITLE
[🕹️] UPVOTE and COMMENT on REDDIT LAUNCH THREAD

### ISSUE THREAD

**Issue by shreykx** [formbricks/formbricks#3490]
### What side quest or challenge are you solving?

I UPVOTED and COMMENTED on the oss.gg LAUNCH THREAD 

### Points

50

### Description

I UPVOTED and COMMENTED on the oss.gg LAUNCH THREAD at `r/opensource`

### Provide proof that you've completed the task

![Screenshot 2024-10-11 222254](https://github.com/user-attachments/assets/5fea9e0a-9441-4957-9de8-b54dcd04fed6)
With 🩷 from SHREY

**Comment by gauravkumar7294** [comment]
Done
![formbricks](https://github.com/user-attachments/assets/ae75dd21-5d2a-4eb3-8f76-7109706cdbd4)

**Comment by gauravkumar7294** [comment]
Upvoted and Commented on Reddit Launch Thread 
![formbricks](https://github.com/user-attachments/assets/0e0470b4-b67e-49fe-ae21-152e28eb0773)
#3490

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue:
@gauravkumar7294 @shreykx 

please open your own issues with your submissions. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
