### ISSUE TITLE
[🕹️] Follow Formbricks Linkedin page

### ISSUE THREAD

**Issue by AliYar-Khan** [formbricks/formbricks#3491]
### What side quest or challenge are you solving?

Follow the linkedin page of Formbricks

### Points

50

### Description

I have followed the Formbricks linkedin page

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/ce5495b3-a780-45b1-ae39-ea8b9dfeefad)

**Comment by Super-Admin5** [comment]
![image](https://github.com/user-attachments/assets/21c295e1-729d-4a45-b0d2-ee7040b30584)
here

**Comment by Super-Admin5** [comment]
@AliYar-Khan  i have followed Formbricks on linkedin

**Comment by arpan595jain** [comment]
![Screenshot 2024-10-11 223532](https://github.com/user-attachments/assets/516e98df-964f-4ffc-b798-acd16105f327)
@arpan595jain i hava followed formbricks on linkedin

**Comment by vishwarajk** [comment]
I have followed the Formbricks linkedin page
![Screenshot_20241012_011219_LinkedIn](https://github.com/user-attachments/assets/f7d5b65f-0bcb-4b7b-a6ba-be3127b3221f)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
