### ISSUE TITLE
[🕹️] Follow formbricks on linkin

### ISSUE THREAD

**Issue by DChitale** [formbricks/formbricks#3492]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page

### Points

50

### Description

Followed and liked the Formbricks LinkedIn Page.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/d6769b7e-fed2-45d4-93bc-921055980a89)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue:
@elic4vet @jitendrakumar025 @DChitale 

please open your own issues with your submissions. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
