### ISSUE TITLE
[🕹️]Submitted the Retweet oss.gg Launch tweet

### ISSUE THREAD

**Issue by Ritesh2351235** [formbricks/formbricks#3493]
### What side quest or challenge are you solving?

Like and retweet the oss.gg launch tweet

### Points

50

### Description

I completed the retweet and like of the oss.gg launch tweet

### Provide proof that you've completed the task

![Image 11-10-24 at 9 50 PM](https://github.com/user-attachments/assets/e117a6c3-cc04-4904-bd89-c11e92a918ab)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue:
@Preetibansal08 

please open your own issues with your submissions. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
