### ISSUE TITLE
[BUG] Unable to REMOVE PROFILE PICTURE 

### ISSUE THREAD

**Issue by shreykx** [formbricks/formbricks#3494]
### Issue Summary

I'm unable to change my account picture on the account config page.

### Steps to Reproduce

1. Go to Formbricks DASHBOARD
2. CLICK on your NAME on bottom LEFT
3. Choose ACCOUNT
4. TRY REMOVING DP

### Expected behavior

It should've changed the profile picture. **Does not change even on a reload**.

### Other information

# SCREEN RECORDING
https://github.com/user-attachments/assets/11daa8ff-ea05-47dd-9923-6b574ac70ada

### Screenshots

![image](https://github.com/user-attachments/assets/6245d566-dc3d-4a9e-be05-b575163b8f7f)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: WEB
- Browser: Chrome
- Version: 129.0.6668.100
```

**Comment by Akash-9794** [comment]
It is not a bug it works properly in my browser please check it out again it's a Bug

**Comment by DivyanshuLohani** [comment]
Looks like your browser's problem if you have any ad blockers please remove them and then try

**Comment by shreykx** [comment]
Okay!

**Comment by shreykx** [comment]
Okay!
