### ISSUE TITLE
[🕹️]Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by balamt** [formbricks/formbricks#3495]
### What side quest or challenge are you solving?

Like & Re-Tweet oss.gg Launch Tweet with “🧱” emoji to Join the Party

### Points

50 Points

### Description

**Liked and Retweet with  “🧱” emoji**

### Provide proof that you've completed the task

[Link to the Retweet with  “🧱” emoji ](https://x.com/balamt_in/status/1844792091823529997)

Here is the Screenshot of Like and Retweet
![retweet](https://github.com/user-attachments/assets/5d21e86a-5a40-4a2f-adfa-ac06348720b7)

**Comment by Rohankashid** [comment]
![Screenshot (6)](https://github.com/user-attachments/assets/23a80a9b-ba54-4b6b-a2e2-d749edf59c7f)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue:
@balamt @Rohankashid 

please open your own issues with your submissions. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)

**Comment by Rohankashid** [comment]
I didn't got 50 points even after completing the task why so
