### ISSUE TITLE
[🕹️] Retweeted the oss.gg launch tweet

### ISSUE THREAD

**Issue by dhanyamd** [formbricks/formbricks#3497]
### What side quest or challenge are you solving?

retweeted and also quote tweeted the official oss.gg launch tweet on X along using the brick emoji

### Points

50

### Description

Liked and Retweet with “🧱” emoji

### Provide proof that you've completed the task

![hack](https://github.com/user-attachments/assets/4fb03349-1d7f-478e-9ee8-eeca041f43f5)

![hack1](https://github.com/user-attachments/assets/5fbd8724-81cd-44fc-8ead-c99744888caf)

link : 

https://x.com/dhanya13_md/status/1844797411950022826

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue:
@DurgeshCodes 

please open your own issues with your submissions. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
