### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#35]
### Add File-upload question type

As a user, I want to enable respondents to upload and attach a file to their submission. For this we need to add an UploadQuestion Type to the No-Code Editor, be able to store files of the users and let the form creator download the provided files.

**Comment by fdis111** [comment]
Hi @mattinannt , can you assign me this task?

**Comment by mattinannt** [comment]
@fdis111 Very happy that you like to build this feature. We have now decided that it's best to halt contirbutions until the transition to Formbricks (new name for snoopForms) is complete in 2-3 weeks. We are also changing parts of the core functionality with database-schema, submission handling and APIs and we don't want you to build on top of a deprecated API and then need to change everything again. After the rebuild we are happy to have you as a contributor again for this and other features 🤗

**Comment by 7PH** [comment]
Hi guys, thank you for this awesome tool,
Now that the transition is complete, is there any plans to work on this? 
I'm currently looking for an alternative to Typeform. Formbricks checks all the boxes that I need but the ability to upload files.

**Comment by mattinannt** [comment]
@7PH Glad that you like what we are working on 😊 We are still in the process of finding our niche with an open-source survey tool. In the future of course file upload is also a part of that, we currently skipped it because it wasn't one of the most requested features and for a great file upload we would like to support local server upload as well as a connector to S3 what makes development more time-consuming.
If you are a developer yourself and would like to add a pull request to build the feature yourself please feel very welcomed to contribute 😊

**Comment by fdis111** [comment]
Hi  @mattinannt , I hope you are doing well, 
I would like to know if I can work on this task.

**Comment by fdis111** [comment]
Hi  @mattinannt , I hope you are doing well, 
I would like to know if I can work on this task.

**Comment by mattinannt** [comment]
Hey @fdis111 
We are still looking for the right direction with Formbricks and building a product that solves the needs of our early customer. For that we are moving more into the direction in-app survey tool to fulfil the different needs. File upload hasn't been a requirement so far for our current users and we don't know yet if we need to and will officially support this feature in the future.
But if you need it for your use case, please don't be held back and feel free to implement a solution for it, and depending on the direction we choose for formbricks, we would also love to include it in the official branch if it fits.
