### ISSUE TITLE
[BUG] username overflow in survey overview

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#3500]
### Issue Summary

Thanks for improving the survey list table :)
Currently column with the usernames is overflowing when using a long username:
![image](https://github.com/user-attachments/assets/58d02efb-bd3f-418d-ab69-313d347ebf82)

### Steps to Reproduce

1. Change your username to something a bit longer
2. Navigate to survey list view
3. Your username will overflow the limited column space

### Expected behavior

First row: How it should look like for long usernames
Second row: How it currently looks like for long usernames

![image](https://github.com/user-attachments/assets/f83f0110-35b3-4ed3-bbca-eea47ad54aa6)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by jonas-hoebenreich** [comment]
I will fix this
/assign

**Comment by shivpratikhande** [comment]
Is this issue still open?
/assign
