### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by jitendrakumar025** [formbricks/formbricks#3502]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page

### Points

50

### Description

Followed and liked the Formbricks LinkedIn Page.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/dcdc5934-1b3c-479f-b3b8-5bf2fa65c406)

**Comment by jitendrakumar025** [comment]
Followed the linkedIn page

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue:
@Shaurya045 @DipeshK47 

please open your own issues with your submissions. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
