### ISSUE TITLE
[🕹️] Two secret side quests 

### ISSUE THREAD

**Issue by Sahil-Gupta584** [formbricks/formbricks#3503]
### What side quest or challenge are you solving?

Secret quests 

### Points

Total:300

### Provide proof that you've completed the task

1.
![Screenshot_20241012_012454](https://github.com/user-attachments/assets/3d435542-6be9-4cd1-859a-45494ffd0749)

2.
![IMG-20241012-WA0000](https://github.com/user-attachments/assets/4c0c86c4-10da-4b5a-9bb0-20620e47c051)

**Comment by jobenjada** [comment]
/award 300

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue:
@nilaygit-10721 

please open your own issues with your submissions. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
