### ISSUE TITLE
[🕹️] Design a background 

### ISSUE THREAD

**Issue by Ionfinisher** [formbricks/formbricks#3504]
### What side quest or challenge are you solving?

Design a background for the form styling

### Points

750

### Description

This is actually a free Canva video template and I provided the link to the template down below.

### Provide proof that you've completed the task

Screenshot of the background in Formbricks:
<img width="1280" alt="Screen Shot 2024-10-11 at 20 59 46" src="https://github.com/user-attachments/assets/1600b0a9-8c2a-4fe8-9bf4-fbf97cdc0830">

Link to source video:
https://www.canva.com/templates/EAGOcWKPsPM-gradient-color-and-style-video-background-in-peach-ash-grey-abstract-style/

**Comment by jobenjada** [comment]
we cant use the Canva video due to copyright issues :(

you have to make your own!
