### ISSUE TITLE
[🕹️] Brickify someone famous with AI

### ISSUE THREAD

**Issue by aryany9** [formbricks/formbricks#3507]
### What side quest or challenge are you solving?

Brickify someone famous with AI [3505]

### Points

150

### Description

Tweeted the AI Image tagging @Formbricks on it to complete the challenge.

### Provide proof that you've completed the task

https://x.com/aryan9y/status/1844915203114402051

<img width="581" alt="Screenshot 2024-10-12 at 7 21 13 AM" src="https://github.com/user-attachments/assets/8a44114e-cc1c-4d78-b31f-2fd5fcce6624">

**Comment by jobenjada** [comment]
/award 150

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
