### ISSUE TITLE
[🕹️]Retweet and like Side Quest

### ISSUE THREAD

**Issue by Kuzuri247** [formbricks/formbricks#3508]
### What side quest or challenge are you solving?

Reposting the launch tweet and liking it

### Points

50 points

### Provide proof that you've completed the task

https://x.com/ossgoodgame/status/1841019549183066552

**Comment by Kuzuri247** [comment]
![Screenshot 2024-10-12 105422](https://github.com/user-attachments/assets/e7313916-6257-44ad-a778-acae18e563ae)

**Comment by ShubhamGond105** [comment]
![Uploading Screenshot 2024-10-12 110213.png…]()

**Comment by ShubhamGond105** [comment]
![Screenshot 2024-10-12 110213](https://github.com/user-attachments/assets/6b755a0c-8648-4f70-8be7-39689b8ce28f)

**Comment by TechWithAkash** [comment]
![repost like_launchpost](https://github.com/user-attachments/assets/ae377c12-c7ee-49a1-a198-0a6971c80d47)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
