### ISSUE TITLE
[🕹️]Like & Re-Tweet oss.gg Launch Tweet (50 Points)

### ISSUE THREAD

**Issue by matinshaikh31** [formbricks/formbricks#3511]
### What side quest or challenge are you solving?

Reposting the launch tweet and liking it

### Points

50

### Description

https://x.com/ossgoodgame/status/1841019549183066552

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/283cd407-c0c2-471b-bba2-3b13a2eb8bed)

**Comment by ShubhamGond105** [comment]
![Screenshot 2024-10-12 110213](https://github.com/user-attachments/assets/60a53faf-3953-4681-be36-737accc03dc4)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
