### ISSUE TITLE
[🕹️] Like & Re-Tweet oss.gg Launch Tweet (50 Points) : Complete

### ISSUE THREAD

**Issue by Chirag8023** [formbricks/formbricks#3513]
### What side quest or challenge are you solving?

 Like & Re-Tweet oss.gg Launch Tweet (50 Points)

### Points

50

### Provide proof that you've completed the task

![Screenshot (12)](https://github.com/user-attachments/assets/0d04f072-ff03-4247-aa84-9566aef52d5e)

**Comment by Harsh9485** [comment]
like and Re Tweet
![Screenshot 2024-10-12 114801](https://github.com/user-attachments/assets/906d0032-a414-48cd-98c3-a13528bd4e47)

**Comment by Harsh9485** [comment]
how to complete the side quests
plz give me a guide

**Comment by Harsh9485** [comment]
<details><summary>Details</summary>
<p>



</p>
</details>

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)

**Comment by prathmesh-jagtap** [comment]
Like & Re-Tweet oss.gg Launch Tweet (50 Points)

Points
50

Description
No response

Provide proof that you've completed the task

![Screenshot 2024-10-12 154512](https://github.com/user-attachments/assets/458a7617-8164-43de-9f78-e425f77b57c5)
