### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by Sa1-Codes** [formbricks/formbricks#3515]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page.

### Points

50

### Description

followed the Formbricks LinkedIn page.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/fa653925-aa59-485e-97a0-78c4a276502e)

**Comment by Subhajit-garai** [comment]
I have already followed the formbricks linkedin page 
![Screenshot_2024-10-12-11-53-08-83_254de13a4bc8758c9908fff1f73e3725](https://github.com/user-attachments/assets/331dc7ba-d873-4bff-bc6d-8ed3bab939e8)

**Comment by jobenjada** [comment]
/award 150

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
