### ISSUE TITLE
[🕹️]Product hunt and alternativeTo reviews

### ISSUE THREAD

**Issue by Ionfinisher** [formbricks/formbricks#3517]
### What side quest or challenge are you solving?

Product hunt and alternativeTo reviews

### Points

300

### Description

Let a review on product hunt and alternativeTo

### Provide proof that you've completed the task

AlternativeTo
<img width="709" alt="Screen Shot 2024-10-12 at 06 49 14" src="https://github.com/user-attachments/assets/ae44f336-d6a4-41a2-a01b-c58a87e4553d">

Product hunt
<img width="829" alt="Screen Shot 2024-10-05 at 03 49 40" src="https://github.com/user-attachments/assets/9456f2f3-c9a6-4d3c-bae7-0ca50d0984cc">

**Comment by Ionfinisher** [comment]
### This is my player submission. No need to assign yourself here. Please open your own issues.

**Comment by jobenjada** [comment]
/award 300

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
