### ISSUE TITLE
[🕹️]Alternativeto.net Review 

### ISSUE THREAD

**Issue by FelixFelicis99** [formbricks/formbricks#3522]
### What side quest or challenge are you solving?

wrote a review on Alternativeto.net

### Points

150

### Provide proof that you've completed the task

liked listing on AlternativeTo.net
![image](https://github.com/user-attachments/assets/9e099db8-3bf6-47ad-9664-3167379e2ac5)

commented and rated:
![image](https://github.com/user-attachments/assets/0f5a765b-6b39-4590-ae72-c0de084f729c)

**Comment by jobenjada** [comment]
/award 300 thanks a lot mate :)
