### ISSUE TITLE
[🕹️]Followed Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by A10-g** [formbricks/formbricks#3523]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page (50 Points)

### Points

50

### Description

I followed Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/0ced829e-3bef-4554-a3e6-c5a1f6c184c7)

**Comment by ray837** [comment]
![Screenshot (175)](https://github.com/user-attachments/assets/6c92456f-e984-4c58-aef0-a2d6298c14f4)

**Comment by ray837** [comment]
I have followed  formbricks linkedin page PFA proof screenshot above

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
