### ISSUE TITLE
Follow Formbricks LinkedIn Page 

### ISSUE THREAD

**Issue by Subhajit-garai** [formbricks/formbricks#3524]
### What side quest or challenge are you solving?

[🕹️]Follow Formbricks LinkedIn Page 

### Points

50

### Description

I have followed formbricks linkedin page

### Provide proof that you've completed the task

![Screenshot_2024-10-12-11-53-08-83_254de13a4bc8758c9908fff1f73e3725](https://github.com/user-attachments/assets/c864ffe0-b994-47c9-a1eb-fa5f76bd3eb3)

**Comment by hurairamuzammal** [comment]
https://github.com/user-attachments/assets/ad3e9b0d-7bed-4870-a31f-5ac17700e88c

My name is Huraira and I have followed Formbricks LinkedIn page.

**Comment by hurairamuzammal** [comment]
I have followed the Formbricks LinkedIn page. Please find the attached screen recording as proof.

https://github.com/user-attachments/assets/4cb7cf51-fb9f-469d-b126-8e6c711ca7d4

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
