### ISSUE TITLE
[🕹️]Follow Dub on Twitter (50 Points)

### ISSUE THREAD

**Issue by A10-g** [formbricks/formbricks#3526]
### What side quest or challenge are you solving?

Followed [Dub on Twitter](https://twitter.com/dubdotco) (50 Points)

### Points

50

### Description

Follow [Dub on Twitter](https://twitter.com/dubdotco) (50 Points)

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/5e6b1d8f-4ca0-440a-bece-d6f65c383e0f)

**Comment by fsagrahari23** [comment]
> Assigned to @fsagrahari23! Please open a draft PR linking this issue within 48h ⚠️ If we can't detect a PR from you linking this issue in 48h, you'll be unassigned automatically 🕹️ Excited to have you ship this 🚀

![Screenshot 2024-10-12 145524](https://github.com/user-attachments/assets/c8f605ab-a317-4500-9e20-0aa3beb4c51f)
As i have followed on twitter now

**Comment by jobenjada** [comment]
wrong repo mate :)
