### ISSUE TITLE
[🕹️]Follow Dub's LinkedIn Page (50 Points)

### ISSUE THREAD

**Issue by A10-g** [formbricks/formbricks#3527]
### What side quest or challenge are you solving?

Follow [Dub's LinkedIn](https://www.linkedin.com/company/dubinc) Page (50 Points)

### Points

50

### Description

Followed [Dub's LinkedIn](https://www.linkedin.com/company/dubinc) Page (50 Points)

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/7f3eb231-e59f-4434-9175-8d0ffc95290e)

**Comment by jobenjada** [comment]
wrong repo
