### ISSUE TITLE
[🕹️]Following Linkedin Page of FormBricks

### ISSUE THREAD

**Issue by Vaibhavghugretkar** [formbricks/formbricks#3528]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page (50 Points):
And, if you like, like and comment on the launch post that you’re competing.

### Points

50 points

### Description

- Followed Linked in Page of FormBricks

### Provide proof that you've completed the task

![Screenshot (35)](https://github.com/user-attachments/assets/4c8baad0-3a64-452d-8013-653468f7330d)

**Comment by sidhantrajput1** [comment]
When I set-up vs code then occurred this type of error.
I don't have any idea, can you resolve it ?

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue: I can only award the author of an issue with points!

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
