### ISSUE TITLE
[🕹️]  Follow Formbricks LinkedIn Page 

### ISSUE THREAD

**Issue by hurairamuzammal** [formbricks/formbricks#3530]
### What side quest or challenge are you solving?

 Follow Formbricks LinkedIn Page 

### Points

50

### Description

I have followed Formbricks from my profile 

### Provide proof that you've completed the task

https://github.com/user-attachments/assets/b31ee87c-6996-4c00-99a0-7d9ad29f1a5e

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
