### ISSUE TITLE
[🕹️]Followed Dub on twitter

### ISSUE THREAD

**Issue by fsagrahari23** [formbricks/formbricks#3537]
### What side quest or challenge are you solving?

Follow dub on twitter

### Points

50

### Description

I have followed dub on provided link.

### Provide proof that you've completed the task

![Screenshot 2024-10-12 145524](https://github.com/user-attachments/assets/dcf5a828-a1f3-457d-9074-09946759fac4)

**Comment by harshsbhat** [comment]
Hey @fsagrahari23 this needs to be on https://github.com/dubinc/dub

**Comment by jobenjada** [comment]
wrong repo :) pls go to dub repo
