### ISSUE TITLE
[🕹️] Fix js integration docs link

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#3539]
### Issue Summary

<img width="432" alt="Screenshot 2024-10-12 at 11 59 22" src="https://github.com/user-attachments/assets/ff262ec9-4843-478c-808a-d48f0cd9617d">

docs link is pointing to the nextjs docs instead the general docs.

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

"docs" link should be pointing to the quickstart at https://formbricks.com/docs/app-surveys/quickstart

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Asymtode712** [comment]
@mattinannt Please assign me this issue
