### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by milanp19** [formbricks/formbricks#3540]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page

### Points

50

### Description

Followed formbricks linkedin page

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/086434a1-86d3-40ca-bca9-93ea2d68a2c6)

**Comment by namansharma3007** [comment]
- I have successfully followed Formbricks on LinkedIN

![Screenshot 2024-10-12 153633](https://github.com/user-attachments/assets/98b62043-ccb0-4609-86fa-3468e41c555b)

**Comment by chandkaurati** [comment]
![Screenshot 2024-10-12 154036](https://github.com/user-attachments/assets/957d2ff3-da11-4d24-a096-4591efb12e04)
done

**Comment by chandkaurati** [comment]
![Screenshot 2024-10-12 154036](https://github.com/user-attachments/assets/dc09b8df-c30f-48cc-b46c-18de0c98e1b4)


followed successfully 😊

**Comment by namansharma3007** [comment]
I have followed Formbricks on LinkedIN
![image](https://github.com/user-attachments/assets/e2e4159c-19df-434c-9973-c5e735af29d4)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue: @nikhilmehra14 @milanp19 @Nikhildevnikhil @namansharma3007 @Deepanshu907 

please open your own issues with your submissions. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
