### ISSUE TITLE
[🕹️] Move Integrations in Formbricks Docs to Core Features

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#3541]
### Issue Summary

Integrations are currently part of the Developer Docs in the Formbricks Docs.

<img width="314" alt="Screenshot 2024-10-12 at 12 02 39" src="https://github.com/user-attachments/assets/3661fbf1-a1d8-4bc2-ad0e-4bde14f67af5">

### Expected behavior

Setting up integrations is not a developer task so we should move them to `Core Features`.
For this task just updating the `navigation.ts` file is sufficient.

**Comment by iamitpal** [comment]
hey, @mattinannt  but I raised the PR first why is my PR not merged and the person raied his PR 1hr after my PR got merged?
