### ISSUE TITLE
[BUG] Debug Mode Link in Website & App Connection page is broken

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#3544]
### Issue Summary

The link to the docs for the debug mode in Formbricks App `Configuration` -> `Website & App Connection` is broken and leads to a 404 page.

<img width="1028" alt="Screenshot 2024-10-12 at 12 14 52" src="https://github.com/user-attachments/assets/7c9d87d1-7c2e-483b-9aaa-700a24c474a4">

This affects both the links for NPM and HTML setup:
<img width="943" alt="Screenshot 2024-10-12 at 12 18 13" src="https://github.com/user-attachments/assets/d436ef2e-815d-4c65-8e65-7ccd0a8d6ff8">

### Steps to Reproduce

1. Open `Website & App Connection` page
2. Click on the `Read docs` link for the debug mode.

### Expected behavior

Please fix the link to point to the correct page(`https://formbricks.com/docs/developer-docs/js-sdk#debug-mode`).

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Pranavx1** [comment]
@mattinannt Pls close this issue as my PR has been merged.
