### ISSUE TITLE
[🕹️] Finished four sidequests

### ISSUE THREAD

**Issue by harshsbhat** [formbricks/formbricks#3550]
### What side quest or challenge are you solving?

I have already sent the mail from harsh121102@gmail.com for side quest submission 

Meme 150
 
SF Billboard 300

Brickify someone famous 300

Two Secret sidequests 300 ( 150 each )

### Points

1050

### Provide proof that you've completed the task

Billboard:

 https://x.com/HarshBhatX/status/1845013251370705037

Brickified: Bricktiano ronaldo:

https://x.com/HarshBhatX/status/1844993902857568407

MEME:

https://x.com/HarshBhatX/status/1844776831326568562

Secret side quests:

![image](https://github.com/user-attachments/assets/298cd17e-4728-4e9b-9d54-ac21ab40cc84)

![image](https://github.com/user-attachments/assets/3e2b185a-562b-4bef-8ede-dbdbc95b9b98)

**Comment by jobenjada** [comment]
/award 1050 

damn son raking in those points! 🔥

**Comment by harshsbhat** [comment]
> /award 1050
> 
> damn son raking in those points! 🔥

Gotta maintain that # 1 at all costs.  (github thought # 1 was an issue lol )

**Comment by harshsbhat** [comment]
> You are not allowed to award points! Please contact an admin.

lol. not doing that either
