### ISSUE TITLE
[🕹️] Starry-eyed supporter

### ISSUE THREAD

**Issue by krbappy00** [formbricks/formbricks#3552]
### What side quest or challenge are you solving?

1050 Points 🔥 Get 5 friends to star our repos, one of my friend give star to this repo

### Points

150

### Provide proof that you've completed the task

![c17b10ff-d79e-4e15-8608-55e19540e56e](https://github.com/user-attachments/assets/0a91311d-544a-4a59-903b-a4432be7fa24)

**Comment by jobenjada** [comment]
wheres the proof? 🤓
