### ISSUE TITLE
[🕹️] Starry-eyed supporter

### ISSUE THREAD

**Issue by krbappy00** [formbricks/formbricks#3553]
### What side quest or challenge are you solving?

1050 Points 🔥 Get 5 friends to star our repos, one of my friend give star to this repo

### Points

150

### Provide proof that you've completed the task

![462536897_981389440455939_4051955369286275543_n](https://github.com/user-attachments/assets/d6790213-385b-441c-aaf3-9e3139375807)

**Comment by FurquanAnwer** [comment]
How do I do this ? @krbappy00
I mean do I need to share screenshots that my friend has starred this repo. How do I achieve this ?

**Comment by jobenjada** [comment]
you need to share screenshots of you asking them, sharing the links and them agreeing to do it :)

**Comment by jobenjada** [comment]
<img width="715" alt="image" src="https://github.com/user-attachments/assets/48555ca2-0461-4151-914b-d9de98633b74">

**Comment by Ionfinisher** [comment]
Hey @jobenjada Do we need to do that on each repo respectively?

**Comment by jobenjada** [comment]
@Ionfinisher yes
