### ISSUE TITLE
[🕹️] Billboard Ad

### ISSUE THREAD

**Issue by EzyHow** [formbricks/formbricks#3556]
### What side quest or challenge are you solving?

San Francisco Billboard Ad

### Points

300

### Provide proof that you've completed the task

![Formbricks](https://github.com/user-attachments/assets/891b21b7-90f2-41c0-80e3-aa8d7071b957)

![formbricks](https://github.com/user-attachments/assets/457d0a6c-ca3b-4d47-a462-844df842537f)

**Comment by Krushna-fullstack** [comment]
@EzyHow where should I be looking in the codebase for this task? Is there a specific module, file, or service ?

**Comment by jobenjada** [comment]
hey! 

this is fine, thanks :)

/award 300
