### ISSUE TITLE
[🕹️]Formbricks Side Quests 

### ISSUE THREAD

**Issue by faheem2312** [formbricks/formbricks#3557]
### What side quest or challenge are you solving?

Formbricks quest not only will bring the support to the community but also makes us to learn how to be a good contributor for a non-code folks.

### Points

- Draft a billboard add:- 300
- Meme:-150
- Gif:-150
- LinkedIn(Social):-50
- Brickify famous personality:-150
- Spread the word(Youtube/X/LinkedIn):-150

Total:-950

### Provide proof that you've completed the task

**### Created Billboard Ad**
![billboard ad](https://github.com/user-attachments/assets/dd614715-46a0-4ae8-93d6-25cfea732f42)

**### Crafted Meme**
![meme](https://github.com/user-attachments/assets/82faea23-fc19-4438-b4f8-0b2e182425e0)

**### Crafted Gif**
![giffy](https://github.com/user-attachments/assets/114f4b73-43f7-4026-a694-92355f8c31ba)

**### Followed on LinkedIn**
![Linkedin](https://github.com/user-attachments/assets/dfb08dff-7d3b-45dc-bd4b-83b140be5a64)

**### Brickify someone famous with AI**
![brickify](https://github.com/user-attachments/assets/aa488458-99b3-4601-bd45-2ded079cfbe5)

**### Spread the word about oss.gg**
![video#1](https://github.com/user-attachments/assets/d574e9d3-97fc-4e3c-ab4c-88cabd0bd012)
![video#2](https://github.com/user-attachments/assets/66bab48d-e6d9-4965-b01d-e27d6ddcf59c)
![video#3](https://github.com/user-attachments/assets/6766de16-31fe-47f0-bf88-22f907d259b3)

_**Thanks!!!**_

**Comment by faheem2312** [comment]
@jayaraut you have to create your own issue to contribute

**Comment by jobenjada** [comment]
hey mate thanks for playing!

billboard ad: This isn't a billboard ad, sorry :D we're looking for something like this:
https://x.com/HarshBhatX/status/1845013251370705037

GIF: please upload the GIF to giphy as requestes
Meme: Pls tweet it and tag @formbricks

awarding you 350 already for the rest :)

/award 350

**Comment by omaware-gg** [comment]
assign

**Comment by shuvishma** [comment]
![formbricks-linkedin](https://github.com/user-attachments/assets/9d0e7ae7-3b7b-4b2d-9f86-213bb9686ee5)
