### ISSUE TITLE
[🕹️] Designed a BACKGROUND for SURVEY ENTHUSIASTS

### ISSUE THREAD

**Issue by shreykx** [formbricks/formbricks#3560]
### What side quest or challenge are you solving?

I found a **cool** background for **NATURE-based SURVEYS** on [formbricks](app.formbricks.com)

### Points

300

### Description

# What's missing from the image database of Formbricks? 
The **RETRO** **Bliss** wallpaper image from the OG Win-XP. Let that sink in.

### Provide proof that you've completed the task

# Preview
![image](https://github.com/user-attachments/assets/b886589f-b06e-43ff-8a8d-44cdbcd77e68)
# Download `(.webp)` (297KBs)
Open it [here](https://raw.githubusercontent.com/shreykx/opendash-streamlit/refs/heads/main/wp9084948.webp).

Sorry! I downloaded this very far back so could not find the original image.

**Comment by jobenjada** [comment]
haha love it! /award 300

wanna open a PR where you add it to the list of images we provide? I'll add 150 points then

**Comment by shreykx** [comment]
> haha love it! /award 300
> 
> wanna open a PR where you add it to the list of images we provide? I'll add 150 points then

Alryy will do it!
