### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by eyeaadil** [formbricks/formbricks#3562]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page

### Points

50

### Description

Follow Formbrick LinkedIn page

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/00fef8ee-05f9-436e-9af8-d8e8ed3f3d4f)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue **I can only award the author of an issue with points!**

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
