### ISSUE TITLE
[🕹️]Retweet and like Side Quest

### ISSUE THREAD

**Issue by Superlilosint** [formbricks/formbricks#3569]
### What side quest or challenge are you solving?

Like & Re-Tweet oss.gg Launch Tweet 

### Points

50 points 

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/a545363f-46d5-43f5-b812-7fbed3ea15e5)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue **I can only award the author of an issue with points!**

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
