### ISSUE TITLE
[FOR-760] [BUG] Not able to view whole question content in Safari on iOS

### ISSUE THREAD

**Issue by onel** [formbricks/formbricks#357]
### Issue Summary

There seems to be a problem on iOS Safari where formbricks shows a header that cuts the scroll ability of the page.
The user is not able to view the question at the top.

### Steps to Reproduce

1. open a formbricks survey using the public link and using Safari on iOS
2. Go to a question that is longer the current viewport
3. See that top question text is cut in half.

### Expected behavior

To be able to view the whole question

#### Screenshots

![WhatsApp Image 2023-06-10 at 14 43 49](https://github.com/formbricks/formbricks/assets/1862405/510965d0-f702-4c67-bf57-d60e85025b3a)

#### Environment

- [x] Formbricks Cloud (app.formbricks.com)
- [ ] self-hosted Formbricks, version/commit: [please provide]

#### Desktop (please complete the following information):

- OS: iOS
- Browser Safari
- Version -

<sub>[FOR-760](https://linear.app/formbricks/issue/FOR-760/[bug]-not-able-to-view-whole-question-content-in-safari-on-ios)</sub>

**Comment by mattinannt** [comment]
@onel Thanks for the bug report. We are looking into it 😊
