### ISSUE TITLE
[🕹️]Reddit Upvote and comment

### ISSUE THREAD

**Issue by Superlilosint** [formbricks/formbricks#3570]
### What side quest or challenge are you solving?

Comment and Upvote the oss.gg post 

### Points

50 points

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/e10df213-0703-497b-9233-deaa59857933)

**Comment by RaghavMangla** [comment]
![image](https://github.com/user-attachments/assets/9f2d5929-f4dc-47af-b74e-b3fb40570fa2)

my comment is by the name AdAdorable5019

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

to every one else commenting: pls open your own issue **I can only award the author of an issue with points!**

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
