### ISSUE TITLE
[🕹️]Retweet and like Side Quest 

### ISSUE THREAD

**Issue by mdaatifayman786** [formbricks/formbricks#3571]
### What side quest or challenge are you solving?

Like & Re-Tweet oss.gg Launch Tweet

### Points

50 points

### Description

🚀 Excited for #Hacktoberfest 2024! 🎉 It’s the perfect time to dive into open source, contribute to amazing projects, and earn cool rewards! 🌍💻

Plus, shoutout to #OSS.gg for hosting their version with Old School RuneScape! ⚔️ Complete PRs for exclusive swag, in-game rewards, and more!

Let’s code, learn, and make an impact together! 🌱 #OpenSource #OSS #Hacktoberfest2024

### Provide proof that you've completed the task

![Screenshot 2024-10-12 233930](https://github.com/user-attachments/assets/79a9a084-8c5f-4046-a61c-8ce4a715a29e)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue:
@nilaygit-10721 

please open your own issues with your submissions. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
