### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by mdaatifayman786** [formbricks/formbricks#3572]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page

### Points

50 points

### Description

Follow Formbrick LinkedIn page

### Provide proof that you've completed the task

![Screenshot 2024-10-12 234351](https://github.com/user-attachments/assets/28713ee2-9299-48f8-abe0-0a166145d585)

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue:
@nilaygit-10721 

please open your own issues with your submissions. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)
