### ISSUE TITLE
[🕹️]twitter like and retweet

### ISSUE THREAD

**Issue by jagdishjadeja** [formbricks/formbricks#3575]
### What side quest or challenge are you solving?

like and retweet oss.gg tweet

### Points

50

### Provide proof that you've completed the task

<img width="668" alt="Screenshot 2024-10-13 at 1 18 36 AM" src="https://github.com/user-attachments/assets/6944340f-50b2-433f-89ee-52b8f058ce7e">

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)

### also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)

to every one else commenting: pls open your own issue:
@nilaygit-10721 

please open your own issues with your submissions. I can only award the author of an issue with points!

### all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)

**Comment by AnsariQamar** [comment]
/award 50
thanks mate! Happy to have you participate :)

also, check out this hack to make [1050 points in 5 minutes 🔥](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)
to every one else commenting: pls open your own issue:
@nilaygit-10721

please open your own issues with your submissions. I can only award the author of an issue with points!

all [Formbricks side quests here 👇](https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf?pvs=74)

**Comment by AnsariQamar** [comment]
![WhatsApp Image 2024-10-13 at 1 38 14 AM](https://github.com/user-attachments/assets/728e647f-8baf-4d81-9a57-804f5af2721d)
#3575
