### ISSUE TITLE
[BUG]  UI Glitch in the Create new Survey Trigger

### ISSUE THREAD

**Issue by DivyanshuLohani** [formbricks/formbricks#3577]
### Issue Summary

When user clicks the `Add Action` button present on the `Survey Settings page` under `Survey Trigger` on screens 1366x768 the dialog seems to be overflowed on  the screen and there no way to access the Create action button and X button also sometimes

### Steps to Reproduce

- Step 1: Go to the survey settings page by creating a new survey or selecting the existing one
- Step 2: Click on `Survey Triggers`
- Step 3: Click `add action`
- Step 4: Switch to `Capture new Action` tab

### Expected behavior

The buttons Create action and Cancel should be visible or the user must have a way to access the buttons by scrolling

### Screenshots

https://github.com/user-attachments/assets/30e80839-2729-42a2-923a-3b655c6e065b

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Ubuntu/Windows
- Browser: All Browsers
```

**Comment by BadriVishalPadhy** [comment]
is this open?

**Comment by BadriVishalPadhy** [comment]
@DivyanshuLohani  can u assign this to me

**Comment by Studycode001** [comment]
I want to fix this bug

**Comment by Pushpender1122** [comment]
I would like to work on intersecting issues. Please assign this task to me.
