### ISSUE TITLE
[🕹️] Follow formbricks LinkedIn Page

### ISSUE THREAD

**Issue by heygogu** [formbricks/formbricks#3578]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page

### Points

50

### Description

Follow Formbricks LinkedIn Page

### Provide proof that you've completed the task

![Screenshot from 2024-10-13 02-16-16](https://github.com/user-attachments/assets/0eba4d79-df8c-488b-9563-4d921adea980)

**Comment by heygogu** [comment]
@jobenjada hello sir, thankyou for improving the bot so it does not assign submission of someone to others (so confusing). Had a call with Ms. Merci(Community Manager) on discord regarding the same. Really appreciate it. Thankyou.

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
