### ISSUE TITLE
[🕹️]Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by omaware-gg** [formbricks/formbricks#3579]
### What side quest or challenge are you solving?

Like & retweeting the launch tweet

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/902e767a-9a63-4c5e-a4e6-f3e93ba2ce4d)

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
