### ISSUE TITLE
[🕹️] Article: How to add a contact form to any website and get notified for free

### ISSUE THREAD

**Issue by geraldmaboshe** [formbricks/formbricks#3582]
### What side quest or challenge are you solving?

Article: How to add a contact form to any website and get notified for free

### Points

1500

### Description

Wrote and published an article to formbricks.com/blog

### Provide proof that you've completed the task

https://github.com/formbricks/formbricks-com/pull/18
https://formbricks.com/blog/how-to-add-a-contact-form-to-any-website-and-get-notified-for-free

**Comment by shivang-tripati** [comment]
assign

**Comment by jobenjada** [comment]
/award 1500 thanks a lot mate, good work!
