### ISSUE TITLE
[🕹️]Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by Sa1-Codes** [formbricks/formbricks#3587]
### What side quest or challenge are you solving?

Like & [Re-Tweet oss.gg Launch Tweet](https://x.com/ossgoodgame/status/1841019549183066552)

### Points

50

### Description

liked and retweeted the oss.gg launch post on tweeter

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/754b624c-fee9-42a4-b055-03fb95e6b790)

**Comment by yogendrarana** [comment]
![Screenshot from 2024-10-13 09-57-10](https://github.com/user-attachments/assets/5a5f77c5-1fdf-4992-a4b3-b322a40e8694)
