### ISSUE TITLE
[🕹️] Bug in the docs navigation

### ISSUE THREAD

**Issue by DivyanshuLohani** [formbricks/formbricks#3589]
### What side quest or challenge are you solving?

Bug Hunter

### Points

100

### Description

I found a bug on the docs page When on this page https://formbricks.com/docs/introduction/what-is-formbricks if we try to click two headers with same name and one is open then the previous one is closed and new one is not opened it behaves as a reference to that element

### Provide proof that you've completed the task

Checkout #3451
![image](https://github.com/user-attachments/assets/8fd7e153-83dd-4d13-93fe-cbba69992a5e)

**Comment by jobenjada** [comment]
awarded on other issue :)
