### ISSUE TITLE
[FEATURE] As a user I'd like to prefill the first answer via URL

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#359]
**Is your feature request related to a problem? Please describe.**

- Email surveys: If a user clicks on e.g. a star rating and is then forwarded to the survey, they shouldn't have to chose the star rating again
- Data in different apps: For a churn survey, once you closed the account you'd want to forward to a survey link which includes data you have in your app but not on the page where the user fills out the churn survey (e.g. account type)

**Describe the solution you'd like**
Prefill the answer of the first question via URL e.g. formbricks.com/s/123?question_id=5 adds a rating of 5 to the first question. The survey displays the second question if the first was prefilled succesfully.

**How it's supposed to work:**
Currently, users can change the question ID of each question how they see fit:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/dc013568-30f3-435c-aaf6-7e1a80832657)

Users should be able append `?question_id=answer` at the end of the URL to prefill the first question.

**Task**

1. Rework SurveyPage.tsx so that it can consume the URL param, fill it in the schema and send it to the API
2. Make sure that the respondent sees the LoadingSpinner.tsx while the first question is prefilled. Forward automatically to the second question, if the Create Response call was successful. If the call wasn't successful or the answer **doesn't match the expected type for a question type,** let the user respond to the first question manually.
3. Validation: Make sure to validate the content of the URL with the expected type per question:

-  E.g. if the question is Rating or NPS then you have to parse the response as a number and check if it is accepted by the schema.
-  For question type CTA the values are "clicked" (main CTA) and "dismissed" (skip CTA).
-  All other question types are strings

Account for all question types:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/8bf03c9d-829e-4577-b957-f1f458a45fb8)
5. Test it to make sure that no wrong data gets sent to the API which would lead to faulty display of response data
6. Use chatGPT to write docs which follow the same schema of the other docs pages. Add it to the docs (same repo)

**Comment by gupta-piyush19** [comment]
@jobenjada I'd like to work on this issue. Could you please assign this to me?
