### ISSUE TITLE
[🕹️] Billboard Ad

### ISSUE THREAD

**Issue by Khaan25** [formbricks/formbricks#3593]
### What side quest or challenge are you solving?

San Francisco Billboard Ad

### Points

300

### Provide proof that you've completed the task

![san-francisco-billboard](https://github.com/user-attachments/assets/91125a4f-51a4-401f-b08a-879b2e3637b3)
![billboard-example](https://github.com/user-attachments/assets/c5d70e65-fb35-4276-89c3-189b1bf6abbb)

**Comment by jobenjada** [comment]
/award 300

thanks for playing :) keep collecting points to increase your chances of winning!
