### ISSUE TITLE
[🕹️] Add on-page menu to blog layout #3193

### ISSUE THREAD

**Issue by SxxAq** [formbricks/formbricks#3594]
### What side quest or challenge are you solving?

We currently do not have an on-page menu on blog articles like [this one](https://formbricks.com/blog/qualtrics-alternatives) or [this one](https://formbricks.com/blog/best-open-source-survey-software). However, we’d want that for better accessibility of the articles content. Needs to be responsive

Issue : #3193 

### Points

750

### Description

added on page menu in the blog layout for better navigation throughout the page.
PR : https://github.com/formbricks/formbricks-com/pull/16

### Provide proof that you've completed the task

![Screenshot 2024-10-13 103920](https://github.com/user-attachments/assets/b77937a8-f2f2-406d-9d91-93f84e4eb449)

**Comment by SxxAq** [comment]
@jobenjada /reward

**Comment by jobenjada** [comment]
/award 750 

thanks for playing :) keep collecting points to increase your chances of winning!
