### ISSUE TITLE
[🕹️] Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by Shubham-Mi** [formbricks/formbricks#3595]
### What side quest or challenge are you solving?

Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page

### Points

50

### Description

Follow the [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page

### Provide proof that you've completed the task

<img width="1202" alt="image" src="https://github.com/user-attachments/assets/36762867-7bd3-4785-9272-69d26359a40d">

**Comment by Gourang12332** [comment]
![Screenshot 2024-10-13 141753](https://github.com/user-attachments/assets/23dc74d3-7c7b-424a-9dc1-a684a73304ef)

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
