### ISSUE TITLE
[🕹️]Design a Background for Formbricks

### ISSUE THREAD

**Issue by Atharva-3000** [formbricks/formbricks#3597]
### What side quest or challenge are you solving?

Design background for Formbricks Forms.

### Points

300

### Description

Designed two background, one for the **ANIMAL LOVERS** and the other which focuses on the artistic design of gen-z.
Both are royalty free !!

Here is the link to download both of them via drive in .webp format:
https://drive.google.com/drive/folders/1sXQhN18Ar3EisMn3KJtmvvWyo-ndIrgQ?usp=drive_link

### Provide proof that you've completed the task

Here is the desktop preview for the image mentioned

![Catto Run](https://github.com/user-attachments/assets/c9ab6cea-4a16-4f46-b72a-0d99bd0ae29c)
<br/>
![awesome](https://github.com/user-attachments/assets/48657574-7e87-404d-8507-e4b22be4de2d)

**Comment by jobenjada** [comment]
hey! sorry, but the quality of the designs is quite low :( we cant really offer that to our users...

Ill award you /award 100 for trying :)
