### ISSUE TITLE
[BUG] [🕹️] Bug Hunter : App Look & Feel Preview for Card Style Background color not changing after first selection

### ISSUE THREAD

**Issue by balamt** [formbricks/formbricks#3599]
### What side quest or challenge are you solving?

Bug Hunter 

### Points

150 Points
Can give more as well 😂

### Description

**### Bug Hunter**

As Bug Hunter, visited [app.formbricks.com](app.formbricks.com) to find bugs, glitches, ui/ux.

Found this one when playing around the configuration section of the app.
Took time to in reproducing in couple of browsers, 
tried to check if it is really an issue. 

Once I felt this need to be fixed, I've decided to capture the evidences as screen recording and created this bug for #oss.gg #hacktoberfest #bug

I've provided more information under the proof section.

### Issue Summary
Formbrick App -> Configuration -> Look & Feel ->  Card Style Background Colour not changing after selected 1st time.

### Steps to Reproduce

1. Open Website : https://app.formbricks.com/
2. Login/Signup [After successful creation of product]
3. Navigate to Configuration 
4. Click Look & Feel Tab
5. Expand the "Card Styling"
6. Card background color
7. Click Color picker tool
8. Change the color to any color (example lightblue), Background color of Card background inside the "Preview window" will change the color accordingly
9. Close the Color picker or don't close the color picker, But Choose different color now. Background color of Card background inside the "Preview window" will not reflect the color change.

#### - Behaviour 1

1. Randomly Choose Color(s) using color picker for Card background.
2. Preview must change Card background according to the color picker selection.

#### - Behaviour 2
1. Randomly type/paste color hex code inside the text box for Card background.
2. Preview must change Card background according to the color hex code.

Other information
No response

### Screenshots/Recordings

https://github.com/user-attachments/assets/e458ccf0-54be-46bc-a369-05503c09ed1d

Environment

- [x] Formbricks Cloud (app.formbricks.com)

Desktop (please complete the following information)
- OS Name:                   Microsoft Windows 10 Pro
- OS Version:                10.0.19045 N/A Build 19045
- Browser: Google Chrome, Microsoft Edge
- Chrome Browser Version: 129.0.6668.100 (Official Build) (64-bit)
- Edge Browser Version 129.0.2792.89 (Official build) (64-bit)
- Node: N/A
- npm: N/A

**Comment by DarshanBorse** [comment]
Please assign me

**Comment by jobenjada** [comment]
the video isn't working, what is the issue? 

Please keep your description more to the point, aint nobody got time for that ;)
