### ISSUE TITLE
Google SSO

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#36]
### Implement Google SSO

As a user I want to use my Google account - including my Google Workspaces account - to log in to the hosted snoopForms.

**Comment by alokthakur142** [comment]
+1

**Comment by alexanderadam** [comment]
I guess it would be nice if there would be general support for OpenID Connect — not only for a single provider.
If URLs and secrets could be defined via ENV variables, it should be possible for anyone to use the OIDC provider of your choice.
