### ISSUE TITLE
[FEATURE] As a user I'd like to archive Attributes

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#360]
**Is your feature request related to a problem? Please describe.**
After having used Formbricks for a while the list with Attributes can get messy.

**Describe the solution you'd like**
Allow users to tidy up their lists by archiving attributes.

**Describe alternatives you've considered**
Delete attributes but this would cause issues when the attributes are used to create segments in live surveys.

**Tasks:**
![grafik](https://github.com/formbricks/formbricks/assets/72809645/03ba0679-5d84-4888-84fb-b855228bf53f)

1. Create toggle to show or hide archived Attributes / Actions (use Switch.tsx in packages/ui)
2. Mark archived Attributes / Actions in the list as archived using the Badge.tsx in packages/ui
3. Add UI to the Attributes Details Modal to archive attributes / actions.
![grafik](https://github.com/formbricks/formbricks/assets/72809645/9f84e11d-1c5f-4d79-b721-5b9c906ad07c)
4. Add UI to **unarchive** Attributes / Actions when a user looks at the details of an archived Attribute / Action
5. Update the model "Attributes" in the file schema.prisma in packages/database for the attributes "archived" with default false.
6. Create a new database migration, name it properly
7. Make the UI update the corresponding database
8. Test

**Comment by Ashutosh-Bhadauriya** [comment]
@jobenjada can you please assign this issue to me.
