### ISSUE TITLE
[ 🕹️] Brickify someone famous with AI

### ISSUE THREAD

**Issue by heygogu** [formbricks/formbricks#3600]
### What side quest or challenge are you solving?

Brickify someone famous with ai

### Points

150

### Description

I brickified weekend singer with AI

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/929a3447-c43c-44d2-a2a9-bdf922234450)

**Comment by jobenjada** [comment]
/award 150 

thanks for playing :) keep collecting points to increase your chances of winning!
