### ISSUE TITLE
[🕹️] Follow Formbricks Linkedin Page

### ISSUE THREAD

**Issue by Dhairyash-1** [formbricks/formbricks#3603]
### What side quest or challenge are you solving?

Follow Formbricks Linkedin Page

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/7206409b-631a-4fa5-9c5c-c1e7e358cfa8)

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
