### ISSUE TITLE
[🕹️] Retweet and like side quest

### ISSUE THREAD

**Issue by rajeevDewangan** [formbricks/formbricks#3604]
### What side quest or challenge are you solving?

3587

### Points

50

### Provide proof that you've completed the task

![Screenshot (1235)](https://github.com/user-attachments/assets/9a4e282f-5d1c-43bb-abcd-ab6b4c2d7716)

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
