### ISSUE TITLE
[🕹️]Retweet & Like Side Quest

### ISSUE THREAD

**Issue by tushar110302** [formbricks/formbricks#3605]
### What side quest or challenge are you solving?

Retweet & Like Side Quest

### Points

50

### Provide proof that you've completed the task

<img width="1318" alt="Screenshot 2024-10-13 at 12 31 48 PM" src="https://github.com/user-attachments/assets/52f6c303-3daf-4600-b4a7-ac788148ee4d">

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
