### ISSUE TITLE
[🕹️]Follow Formbricks Linkedin Page

### ISSUE THREAD

**Issue by tushar110302** [formbricks/formbricks#3607]
### What side quest or challenge are you solving?

Follow Formbricks Linkedin Page

### Points

50

### Provide proof that you've completed the task

<img width="1237" alt="image" src="https://github.com/user-attachments/assets/2cddec33-02f3-4f78-a849-bc5e8aa2b360">

**Comment by priyankashah3107** [comment]
![formbricks](https://github.com/user-attachments/assets/1e58d0b9-1577-4be4-9496-6c02300e89f3)

Task Completed 👍

**Comment by KunalChhetri14** [comment]
![image](https://github.com/user-attachments/assets/8e68e499-32bc-48ac-90b5-4e5cd865fa31)

Followed linkedIn page

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
