### ISSUE TITLE
[🕹️] Retweet and liked side quest 

### ISSUE THREAD

**Issue by Jivanjamadar** [formbricks/formbricks#3608]
### What side quest or challenge are you solving?

Like & [Re-Tweet oss.gg Launch Tweet]

### Points

50

### Description

Liked & Retweeted the post on X(twitter)

### Provide proof that you've completed the task

![Screenshot 2024-10-13 124818](https://github.com/user-attachments/assets/ccbefbc4-cfed-4307-af88-053eb3af72e3)

**Comment by Atul090** [comment]
should I share the screenshot for proof to earn the first 50 points?

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
