### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page #3607

### ISSUE THREAD

**Issue by priyankashah3107** [formbricks/formbricks#3609]
### What side quest or challenge are you solving?

Following Formbricks LinkedIn Page

### Points

50

### Provide proof that you've completed the task

![formbricks](https://github.com/user-attachments/assets/2f9a4b78-cac0-426f-bd1e-95033d02d2db)

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
