### ISSUE TITLE
Spread the word (50 per influencer, max. 3 influencers)

### ISSUE THREAD

**Issue by antilpiyush89** [formbricks/formbricks#3610]
### What side quest or challenge are you solving?

Spread the word (50 per influencer, max. 3 influencers)

### Points

150 points, 50 per influencer

### Description

Commented on 3 influencer channels about oss.gg hackathon that they should cover this topic in their upcoming videos

### Provide proof that you've completed the task

![Screenshot_20241013_125855_Chrome](https://github.com/user-attachments/assets/b2d5fa83-8906-470f-9af1-374d85393e77)
![Screenshot_20241013_125837_Chrome](https://github.com/user-attachments/assets/371703ae-c76f-4ae1-9212-05ff236b92c7)
![Screenshot_20241013_125821_Chrome](https://github.com/user-attachments/assets/ff1abdf5-c63d-40b6-848a-6d3c73bd8d8f)

**Comment by jobenjada** [comment]
/award 150 

thanks for playing :) keep collecting points to increase your chances of winning!
