### ISSUE TITLE
[🕹️]Linkedin follow and Liked & commented on launch page

### ISSUE THREAD

**Issue by Jivanjamadar** [formbricks/formbricks#3611]
### What side quest or challenge are you solving?

Linkedin follow

### Points

50

### Description

Followed the Linkedin page of formbricks and liked & commented on launch page 

### Provide proof that you've completed the task

![Screenshot 2024-10-13 125951](https://github.com/user-attachments/assets/39fe4476-8d91-4eaa-9610-f518cda54489)
![Screenshot 2024-10-13 130012](https://github.com/user-attachments/assets/1b953195-4f95-4d41-a643-bcf98e33cd51)

**Comment by Harish-Shejokar** [comment]
![Screenshot 2024-10-13 141026](https://github.com/user-attachments/assets/4ea68f50-426a-4b7a-a0f5-7a12e44926cf)
![Screenshot 2024-10-13 141206](https://github.com/user-attachments/assets/a9d08f3e-f444-47de-8598-40c62050642d)

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
