### ISSUE TITLE
[🕹️] Follow Formbricks Linkedin Page 

### ISSUE THREAD

**Issue by SiddikMulla** [formbricks/formbricks#3612]
### What side quest or challenge are you solving?

Follow Formbricks Linkedin Page

### Points

50

### Description

Followed formbricks Linkdein account

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/c439e856-62ae-4428-93d9-ad42f8fdcbbc)

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
