### ISSUE TITLE
[🕹️]BUG : There should be a smooth transition of navbar when user scrolls the page.

### ISSUE THREAD

**Issue by shreyabajaj12** [formbricks/formbricks#3613]
### What side quest or challenge are you solving?

Sliding of the navbar when user scrolls the page.

### Points

150 Points

### Description

Sliding the page

### Provide proof that you've completed the task

https://github.com/user-attachments/assets/46ce80da-3eff-4e74-a351-3612028481db

**Comment by manishkumar123456** [comment]
can you please  elobrate the the issue more  , that what have to fix

**Comment by jobenjada** [comment]
video is not loading, which nav bar?

**Comment by jobenjada** [comment]
hey! the landing page is not part of the hackathong (as explicitly stated in the doc). Pls pick a different issue!
