### ISSUE TITLE
[🕹️] Feedback Fanatic

### ISSUE THREAD

**Issue by naaa760** [formbricks/formbricks#3614]
### What side quest or challenge are you solving?

 Fill out our feedback survey after the hackathon with suggestions for improvement

### Points

150

### Provide proof that you've completed the task

![Screenshot from 2024-10-13 12-33-09](https://github.com/user-attachments/assets/872b544e-7d3f-492a-a473-b1530d473338)

**Comment by jobenjada** [comment]
/award 150 

thanks for playing :) keep collecting points to increase your chances of winning!
