### ISSUE TITLE
[🕹️] FOLLOWING Formbricks LinkedIn PAGE

### ISSUE THREAD

**Issue by shreykx** [formbricks/formbricks#3615]
### What side quest or challenge are you solving?

I FOLLOWED the OFFICIAL **[Formbricks](app.formbricks.com)** LinkedIn PAGE.

### Points

50

### Description

# Task?
I FOLLOWED THE OFFICIAL PAGE OF [Formbricks](app.formbricks.com) on [LinkedIn](linkedin.com)

### Provide proof that you've completed the task

![Screenshot_2024-10-13-13-24-02-877_com linkedin android](https://github.com/user-attachments/assets/d302ecf7-6a22-4ff9-b149-797cd059a23e)
With ♥️ from SHREY

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
