### ISSUE TITLE
[🕹️]The horizontal scroller below "Measure satisfaction continuously" cards goes to the beginning after the last slide.

### ISSUE THREAD

**Issue by sahiladit** [formbricks/formbricks#3617]
### What side quest or challenge are you solving?

Bug Hunter

### Points

50-150

### Description

The slider starts from the beginning after the last slide which does not feel smooth,it should be infinite to increase user experience.

### Provide proof that you've completed the task

https://github.com/user-attachments/assets/e0333de1-ed45-4eb6-8076-13ea628c294a

**Comment by jobenjada** [comment]
hey! the landing page is not part of the hackathong (as explicitly stated in the doc). Pls pick a different issue!
