### ISSUE TITLE
[🕹️] Brickifying SOMEONE FAMOUS

### ISSUE THREAD

**Issue by shreykx** [formbricks/formbricks#3618]
### What side quest or challenge are you solving?

I **BRICKIFIED** someone **FAMOUS** AND **TAGGED** **[@formbricks](x.com/formbricks)**

### Points

150

### Description

**I BRICKIFIED SOMEONE.**

### Provide proof that you've completed the task

![Screenshot_2024-10-13-14-02-07-318_com twitter android](https://github.com/user-attachments/assets/44378173-1194-4bf4-98c5-d80c25d030fa)
Find it [here](https://x.com/shreykx/status/1845380549205987527?t=oV5yKXlHbzYFAfz-vFcc2Q&s=19).

**Comment by jobenjada** [comment]
"Adele in front of bricks" ≠ "Brickified Adele" :D
