### ISSUE TITLE
[🕹️] Retweet and like submission

### ISSUE THREAD

**Issue by arijitdn** [formbricks/formbricks#3620]
### What side quest or challenge are you solving?

Liked and retweeted the oss.gg twitter post

### Points

50

### Description

Liked & Retweeted the post on X(twitter)

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/99c9f66e-999d-4457-a606-850810f96f58)

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
