### ISSUE TITLE
[🕹️] Follow Formbricks Linkedin Page

### ISSUE THREAD

**Issue by arijitdn** [formbricks/formbricks#3621]
### What side quest or challenge are you solving?

Follow Formbricks Linkedin Page

### Points

50

### Description

Followed Formbricks Linkedin account

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/5835fcf9-4fbc-498d-a1c1-8d006ef1437d)

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
