### ISSUE TITLE
[🕹️] Secret Side Quest

### ISSUE THREAD

**Issue by mitgajera** [formbricks/formbricks#3622]
### What side quest or challenge are you solving?

Product Hunt Revie

### Points

150

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/df3bf5a7-902f-465d-a0b6-19c7dc2e44be)

**Comment by jobenjada** [comment]
/award 150 

thanks for playing :) keep collecting points to increase your chances of winning!
