### ISSUE TITLE
[🕹️] Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by Kritikaadhikarii** [formbricks/formbricks#3624]
### What side quest or challenge are you solving?

[🕹️] Follow Formbricks LinkedIn Page

### Points

50

### Description

I've followed Formbricks Linkedln Page.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/f8b2b722-f569-4f49-bed4-df0ad1d0a737)

**Comment by 2div** [comment]
I've followed Formbricks Linkedln Page.

![XRecorder_Edited_13102024_140040](https://github.com/user-attachments/assets/25039d89-19c4-4080-ac67-e5b06b442f5b)

**Comment by satyagithub23** [comment]
![image](https://github.com/user-attachments/assets/77a4bb99-7136-4069-995c-835c0407b574)
I have followed Formbricks Linkedln Page

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
