### ISSUE TITLE
[🕹️] Follow formbricks on Linkedin

### ISSUE THREAD

**Issue by DivyanshuLohani** [formbricks/formbricks#3626]
### What side quest or challenge are you solving?

Following Formbricks' Linkedin page

### Points

50

### Description

I followed the linkedin page of formbricks

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/bfb9e04b-3861-45d0-aced-ef2c46b9a203)

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
