### ISSUE TITLE
[🕹️] Like & Retweet oss.gg launch tweet

### ISSUE THREAD

**Issue by antilpiyush89** [formbricks/formbricks#3627]
### What side quest or challenge are you solving?

[Like & Re-Tweet oss.gg Launch Tweet](https://x.com/antil_piyush101/status/1844850573423804573)

### Points

50

### Description

Liked the oss.gg Launch Tweet and Reposted it.

### Provide proof that you've completed the task

![Screenshot 2024-10-12 024855](https://github.com/user-attachments/assets/f47209b4-7879-4ffa-b46d-35c1058d2982)
![Screenshot 2024-10-12 025047](https://github.com/user-attachments/assets/a9ba8f00-ce81-48df-98c2-b795990822d1)

**Comment by nakul-py** [comment]
\assign

**Comment by Ayush30s** [comment]
![Screenshot 2024-10-13 200613](https://github.com/user-attachments/assets/22c40885-b34a-444b-8bed-6a59ea2facbb)
🚀🚀

**Comment by jobenjada** [comment]
/award 50 

thanks for playing :) keep collecting points to increase your chances of winning!
