### ISSUE TITLE
[🕹️] Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by utsavdotdev** [formbricks/formbricks#3630]
### What side quest or challenge are you solving?

Like & Re-Tweet oss.gg Launch Tweet

### Points

50 

### Description

I just like and repost the tweet posted by oss.gg

### Provide proof that you've completed the task

<img width="1402" alt="Screenshot 2024-10-13 at 4 10 33 PM" src="https://github.com/user-attachments/assets/495c9fca-c1a4-4dbd-851c-cbe75966be55">

**Comment by jobenjada** [comment]
/award 50

thanks mate! Happy to have you participate :)
