### ISSUE TITLE
[🕹️]Get 5 friends to star our repos #3441

### ISSUE THREAD

**Issue by FaheemOnHub** [formbricks/formbricks#3634]
### What side quest or challenge are you solving?

I made 5 of my friends star all the 7 repos

### Points

1050

### Description

I made 5 of my friends star all the 7 repos

### Provide proof that you've completed the task

<img width="1440" alt="28" src="https://github.com/user-attachments/assets/dbea4fbe-d41e-47d0-9d4b-553fb32c066f">
<img width="1440" alt="27" src="https://github.com/user-attachments/assets/b0591c5d-3cbd-48fc-9cc9-6f42e555929d">
<img width="1440" alt="26" src="https://github.com/user-attachments/assets/badbd44e-df36-4b71-98a4-6ea57cc501b2">
<img width="1440" alt="25" src="https://github.com/user-attachments/assets/33d7756c-b3f5-45f5-a39a-b78784bea93e">
<img width="1440" alt="24" src="https://github.com/user-attachments/assets/7943ef92-ee29-476a-8f03-30ecf33d91a6">
<img width="1440" alt="23" src="https://github.com/user-attachments/assets/4b61b02d-3211-4f94-b818-03a55d9cbd4b">
<img width="1440" alt="22" src="https://github.com/user-attachments/assets/212c43d5-4e04-4989-a3c8-e797393d44e0">
<img width="1440" alt="21" src="https://github.com/user-attachments/assets/e5efc5ca-fd19-4e25-8344-c9e5351e3736">
<img width="1440" alt="20" src="https://github.com/user-attachments/assets/3de7cb55-ac92-4293-9f7c-0ad91d9199c4">
<img width="1440" alt="19" src="https://github.com/user-attachments/assets/fe7122fb-6a8a-40d5-83a9-1712b08f04bf">
![WhatsApp Image 2024-10-13 at 12 40 52 PM](https://github.com/user-attachments/assets/da59b0d0-465e-496b-8e02-b1ef2eda7495)
![WhatsApp Image 2024-10-13 at 12 40 28 PM](https://github.com/user-attachments/assets/ce8e1c61-0ab2-4475-8974-ad51fed3ee25)
![WhatsApp Image 2024-10-13 at 12 39 58 PM](https://github.com/user-attachments/assets/f5967808-3dea-4c45-876d-55a9292f6d5a)
<img width="1440" alt="18" src="https://github.com/user-attachments/assets/564b1a68-d985-443f-83a1-684acf69531e">
![WhatsApp Image 2024-10-13 at 12 38 28 PM](https://github.com/user-attachments/assets/2b00e75c-ad76-479d-bee6-0b61a415e5b0)
![WhatsApp Image 2024-10-13 at 12 37 24 PM](https://github.com/user-attachments/assets/fc376974-8269-4ec4-a556-efed3b0bdf2f)
![WhatsApp Image 2024-10-13 at 12 37 59 PM](https://github.com/user-attachments/assets/75d3da85-a0c2-4660-8972-3cb0b5ebf0c3)
![WhatsApp Image 2024-10-13 at 12 36 44 PM](https://github.com/user-attachments/assets/2871f793-a839-4a6c-b495-f3aa5941f346)
<img width="1440" alt="17" src="https://github.com/user-attachments/assets/44efea05-f908-4ea0-88d1-aa31dbbfbc01">
<img width="1440" alt="16" src="https://github.com/user-attachments/assets/f5d3b2f9-2d84-4e57-b489-4cbe534da234">
<img width="1440" alt="15" src="https://github.com/user-attachments/assets/ccb852ea-3f37-4cd6-992d-6fdbadac09bd">
![IMG_0825](https://github.com/user-attachments/assets/c9b9be60-7684-49ac-a373-2fa5dc392af4)
<img width="1440" alt="14" src="https://github.com/user-attachments/assets/10c3e35e-8bb0-46b8-8394-2a9f96d7119c">
![IMG_0824](https://github.com/user-attachments/assets/651ae3ff-0948-4475-a4b4-a061cd6e59cd)
<img width="1440" alt="13" src="https://github.com/user-attachments/assets/a9ca2670-c98b-4455-97ad-a85d9e513e45">
<img width="1440" alt="12" src="https://github.com/user-attachments/assets/cce9c732-2320-4e0d-bc0d-ad4fa067d4d5">
<img width="1440" alt="11" src="https://github.com/user-attachments/assets/91d7cbba-b989-40c4-9519-ac1e6bf80145">
<img width="1440" alt="10" src="https://github.com/user-attachments/assets/09ec1b1f-2178-459d-980f-41e7d17d70d2">
<img width="1440" alt="9" src="https://github.com/user-attachments/assets/269633d8-eaae-4ba5-8a81-8182aac67f0b">
<img width="1440" alt="8" src="https://github.com/user-attachments/assets/df6ecbdd-d5d2-443e-8fbd-f26f98b044c1">
<img width="515" alt="7" src="https://github.com/user-attachments/assets/a280e9aa-9341-4065-b673-76d55c41e563">
![IMG_0823](https://github.com/user-attachments/assets/62e99917-9696-42b2-a543-9c82de999405)
<img width="511" alt="6" src="https://github.com/user-attachments/assets/00e57230-1229-467b-8c93-ec0cd3b8f3fa">
![IMG_0822](https://github.com/user-attachments/assets/4e58ed34-c955-4fae-b0ad-4a71aa7b9bfd)
![IMG_0821](https://github.com/user-attachments/assets/233fd9ec-fde0-4c23-8ab7-3e15e418ac61)
![IMG_0820](https://github.com/user-attachments/assets/b7b3d408-e77e-49ea-be35-b2aba4997863)
<img width="512" alt="5" src="https://github.com/user-attachments/assets/96ca5ab1-fd87-4ed8-b182-fd1a03acbce7">
![IMG_0819](https://github.com/user-attachments/assets/7eccd09c-9240-4749-83d9-80e358473432)
<img width="512" alt="4" src="https://github.com/user-attachments/assets/56fb4eef-412a-470c-9877-aa21eb9f2c51">
<img width="511" alt="3" src="https://github.com/user-attachments/assets/880d9e5b-c3f6-405b-a669-077de84d102a">
<img width="510" alt="2" src="https://github.com/user-attachments/assets/88360fe3-28f3-4007-8134-a84147756b58">
<img width="509" alt="1" src="https://github.com/user-attachments/assets/7b56fe84-e888-4489-b3ab-9c0dc54a37d6">
![IMG_0818](https://github.com/user-attachments/assets/5c4eb03c-16b1-4051-b9f5-497d436ffd15)
![IMG_0817](https://github.com/user-attachments/assets/1309a7fc-2946-4b0a-9588-d2ad01e6ba7c)
![IMG_0816](https://github.com/user-attachments/assets/835f1d99-8a1f-4da8-abf4-274140a562cf)
![IMG_0815](https://github.com/user-attachments/assets/35b2ac12-55d6-4074-a6e7-7848f418d5b2)
![IMG_0814](https://github.com/user-attachments/assets/261b5d34-0cb5-4dae-ae8e-5144a5c3e4f7)
![IMG_0813](https://github.com/user-attachments/assets/33987530-f826-437b-a79d-1b357d4d070d)
![IMG_0812](https://github.com/user-attachments/assets/aa6f4a87-90d6-407b-bfc3-c694295fbdc6)

**Comment by jobenjada** [comment]
/award 150

please open the proof submission issue in the other 6 repos as well. we might change that but right now, this is how its supposed to work
