### ISSUE TITLE
[🕹️]Formbricks Background Design

### ISSUE THREAD

**Issue by EzyHow** [formbricks/formbricks#3635]
### What side quest or challenge are you solving?

Video background for Formbricks forms.

### Points

750 for video

### Provide proof that you've completed the task

**MP4 File:**

https://github.com/user-attachments/assets/7e039239-ad2b-41ac-b16b-4fa6118700af

**MOV File:**

https://github.com/user-attachments/assets/1d754c07-1325-487e-8f8d-177aee96afd5

**Comment by jobenjada** [comment]
hey! Where did you find that file? 🤓

**Comment by EzyHow** [comment]
> hey! Where did you find that file? 🤓

I have used it as the background of a login page in one of my projects. Actually it was created using a JavaScript library.

For formbricks, I removed other elements and recorded my screen.

**Comment by jobenjada** [comment]
smart way to go about it! 

we wont be able to use it in our app as it is too hectic for a background but I'll award you 300 points for your creative problem-solving!

/award 300
