### ISSUE TITLE
[🕹️]Formbricks Background Design - Cloud Background Video

### ISSUE THREAD

**Issue by EzyHow** [formbricks/formbricks#3637]
### What side quest or challenge are you solving?

Cloud Background Video for Formbricks forms

### Points

750 for video

### Provide proof that you've completed the task

https://github.com/user-attachments/assets/cd456bf2-ca14-4985-80c7-69ed24eeeffe

**Comment by Theory903** [comment]
/assign

Hi @EzyHow, 
I'd like to contribute to this task. Could you provide more details regarding the cloud background video, such as preferred dimensions, style, and format? 
Thanks!

**Comment by EzyHow** [comment]
> /assign
> 
> Hi @EzyHow, I'd like to contribute to this task. Could you provide more details regarding the cloud background video, such as preferred dimensions, style, and format? Thanks!

Please check this official post from Formbricks: [https://formbricks.notion.site/Formbricks-Background-Design-56a1da9c92cb469db62b0e31a530bf97](https://formbricks.notion.site/Formbricks-Background-Design-56a1da9c92cb469db62b0e31a530bf97)

**Comment by jobenjada** [comment]
you can only do it once. I like the clouds more so pls close the other issue.

Where did you find that file?

**Comment by EzyHow** [comment]
> you can only do it once. I like the clouds more so pls close the other issue.
> 
> Where did you find that file?
Got it. I will close other issue with background.

**Source:** https://www.vantajs.com/?effect=clouds

**Comment by Anjali655** [comment]
/assign

Hi @EzyHow ,
I'd like to contribute to this task. Could you provide more details regarding the cloud background video, such as preferred dimensions, style, and format?
Thanks!
