### ISSUE TITLE
[🕹️]Formbricks Background Design

### ISSUE THREAD

**Issue by EzyHow** [formbricks/formbricks#3638]
### What side quest or challenge are you solving?

Background image for Formbricks

### Points

300

### Provide proof that you've completed the task
![Form Background](https://github.com/user-attachments/assets/569a43bb-2076-47b9-8f11-570b5849ab2c)

Webp:
[Form Background.webp.zip](https://github.com/user-attachments/files/17355706/Form.Background.1.webp.zip)

(Zipped because GitHub doesn't allow Webp format)

**Comment by jobenjada** [comment]
cool one! Where did you find that file? asking for copyright reasons

**Comment by EzyHow** [comment]
> cool one! Where did you find that file? asking for copyright reasons

**Source:** https://www.vantajs.com/?effect=fog

But closing this issue as suggested by you in another issue: https://github.com/formbricks/formbricks/issues/3637#issuecomment-2409087864
