### ISSUE TITLE
[🕹️] Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by ayyash1** [formbricks/formbricks#3639]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page

### Points

50

### Description

I followed the Linkedin page of Formbricks.

### Provide proof that you've completed the task

My Linkedin name is : Ayyash Fous

![new](https://github.com/user-attachments/assets/32b87e82-bdc0-4ea3-bcd9-cf7ef9bb09a1)

**Comment by c0d3h01** [comment]
![Screenshot_20241013_190421](https://github.com/user-attachments/assets/d8f22c3b-cbda-4e88-9f2f-71126264a14c)

What side quest or challenge are you solving?
I followed the Formbricks LinkedIn page as requested.

Proof of completion:
Please see the attached screenshot showing that I have successfully followed the Formbricks LinkedIn page.

**Comment by c0d3h01** [comment]
Thank you for creating this task! 🙌 Here's my screenshot showing I've followed the Formbricks LinkedIn page as requested:

![Screenshot_20241013_190421](https://github.com/user-attachments/assets/c6443793-c4b8-44c1-854a-4eac24fc59f9)

What side quest or challenge are you solving?
I followed the Formbricks LinkedIn page as requested.

Proof of completion:
Please see the attached screenshot showing that I have successfully followed the Formbricks LinkedIn page.

**Comment by ayyash1** [comment]
> 50 thanks mate :)
