### ISSUE TITLE
[🕹️] Follow Formbricks Linkedin Page 

### ISSUE THREAD

**Issue by Theory903** [formbricks/formbricks#3640]
### What side quest or challenge are you solving?

Follow Formbricks Linkedin Page

### Points

50

### Description

I just went to the Formbricks linkedin page and followed it!

### Provide proof that you've completed the task

<img width="1440" alt="Screenshot 2024-10-13 at 6 47 54 PM" src="https://github.com/user-attachments/assets/5e743bb5-10cd-4d02-87a6-c705be20a8d4">

**Comment by c0d3h01** [comment]
![Screenshot_20241013_190421](https://github.com/user-attachments/assets/02ead5fc-a671-4f0c-a515-508e83b84d69)

What side quest or challenge are you solving?
I followed the Formbricks LinkedIn page as requested.

Proof of completion:
Please see the attached screenshot showing that I have successfully followed the Formbricks LinkedIn page.

**Comment by c0d3h01** [comment]
Thank you for creating this task! 🙌 Here's my screenshot showing I've followed the Formbricks LinkedIn page as requested:
