### ISSUE TITLE
[🕹️] Quest Submission: Spread the word about oss.gg to influencers

### ISSUE THREAD

**Issue by Chirag8023** [formbricks/formbricks#3644]
### What side quest or challenge are you solving?

Spread the word (50 per influencer, max. 3 influencers):

### Points

50 x 3 = 150

### Provide proof that you've completed the task

1. [What is a REST API - HTTP Methods and API Types](https://www.youtube.com/watch?v=T71J7KzFN-E&ab_channel=FrancescoCiulla)
![Screenshot (23)](https://github.com/user-attachments/assets/c313eeae-5afb-4ec7-b231-901ea0066f0c)

---
2. [Mock out OAuth Provider using MswJS (NextJS and Next-Auth)](https://www.youtube.com/watch?v=C1IKFYwSMM0&ab_channel=EddieJaoude)
![Screenshot (24)](https://github.com/user-attachments/assets/2c88eef7-c860-497f-b3c4-141d2a138428)

---
3. [My 2024 AI Terminal setup | I'm never going back to iTerm | Warp features](https://www.youtube.com/watch?v=FNlQZqeQyzc&ab_channel=KunalKushwaha)
![Screenshot (25)](https://github.com/user-attachments/assets/2914e065-14b3-42c8-8839-7c81838cfe70)

**Comment by jobenjada** [comment]
very cool, thanks! /award 150
