### ISSUE TITLE
[🕹️] Follow formbricks Linkedin page

### ISSUE THREAD

**Issue by DevGajjar28** [formbricks/formbricks#3645]
### What side quest or challenge are you solving?

Follow [formbricks on Linkedin](https://www.linkedin.com/company/formbricks/)

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/b87ab0cd-7e85-4b24-bd6a-a382fccf6220)

**Comment by Sourav-nitj** [comment]
done
<img width="1349" alt="Screenshot 2024-10-13 at 9 35 17 PM" src="https://github.com/user-attachments/assets/47e574cf-35f9-4c96-a933-d022f5dba04b">
