### ISSUE TITLE
[🕹️] Following Formbricks Linkdin page #3645

### ISSUE THREAD

**Issue by ayushcodes0** [formbricks/formbricks#3646]
### What side quest or challenge are you solving?

I am following Linkdin page of Formbricks

### Points

50 points

### Description

Following Formbricks Linkdin page

### Provide proof that you've completed the task

<img width="1416" alt="Screenshot 2024-10-13 at 8 32 38 PM" src="https://github.com/user-attachments/assets/5895b2b7-d56b-4df3-a428-019e04ec403e">

**Comment by ArpitShukla3** [comment]
could you explain why did you open this as an issue ??

**Comment by ayushcodes0** [comment]
It is mentioned in the non coding contribution section that you have to
make an issue that's why I created that
