### ISSUE TITLE
[🕹️]Follow Dub on Twitter 

### ISSUE THREAD

**Issue by sweets-11** [formbricks/formbricks#3647]
### What side quest or challenge are you solving?

![image](https://github.com/user-attachments/assets/4a6d5ae5-d062-4e18-8302-ba3cfc78368f)

### Points

50

### Description

![image](https://github.com/user-attachments/assets/de1d2608-3056-4a7e-b928-19e0ae72ef44)

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/65e664dc-6fc6-4673-8d4b-c72ab4e11374)

**Comment by jobenjada** [comment]
wrong repo mate :)
