### ISSUE TITLE
[🕹️]San Francisco Billboard Ad

### ISSUE THREAD

**Issue by Sourav-nitj** [formbricks/formbricks#3650]
### What side quest or challenge are you solving?

San Francisco Billboard Ad of formbrick

### Points

300 points

### Description

San Francisco Billboard Ad of formbrick

### Provide proof that you've completed the task

![formbricks_billboard_ad](https://github.com/user-attachments/assets/cdc91de0-4066-4359-8aa9-080efbf6278b)

**Comment by jobenjada** [comment]
wellll I dont think this qualifies, looks like it was made from clay :D
