### ISSUE TITLE
[🕹️] San Francisco Billboard Ad

### ISSUE THREAD

**Issue by Manjinder-Tech** [formbricks/formbricks#3651]
### What side quest or challenge are you solving?

San Francisco Billboard Ad

### Points

300

### Provide proof that you've completed the task

![Billboard](https://github.com/user-attachments/assets/6a4caae1-87fc-414f-b314-eea1e6cec59e)

![On Billboard](https://github.com/user-attachments/assets/24d74417-3f9c-4ed8-bded-2343a49a3e55)

**Comment by jobenjada** [comment]
love the effort! /award 300
