### ISSUE TITLE
[🕹️] Like & Re-Tweet oss.gg Launch Tweet 

### ISSUE THREAD

**Issue by EzyHow** [formbricks/formbricks#3654]
### What side quest or challenge are you solving?

Liked and retweeted oss.gg launch tweet...

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/f25ae25d-464e-43a3-86de-142f527e39aa)

[Check here](https://x.com/EzyHow/status/1845510341717032975)

**Comment by ram-9047** [comment]
<img width="981" alt="Screenshot 2024-10-13 at 11 38 36 PM" src="https://github.com/user-attachments/assets/d801618e-4ae7-40b4-baa0-687123f4dac8">
