### ISSUE TITLE
[🕹️]Retweet and like submission on X

### ISSUE THREAD

**Issue by Aishwarya-S-Sharma** [formbricks/formbricks#3659]
### What side quest or challenge are you solving?

Liked and retweeted the oss.gg twitter post

### Points

50 points

### Description

Liked & Retweeted the post on X(twitter)

### Provide proof that you've completed the task

![Screenshot 2024-10-14 010656](https://github.com/user-attachments/assets/282996b3-b88f-4cd0-a574-01c2c0fe890e)

**Comment by shashankpatil28** [comment]
### What side quest or challenge are you solving?
Liked and retweeted the oss.gg twitter post

**Points**
50 points

**Description**
Liked & Retweeted the post on X(twitter)

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/920c87ae-29db-4b05-8901-006b4fa937bc)
