### ISSUE TITLE
[🕹️] Followed Twitter of Formbricks & oss.gg

### ISSUE THREAD

**Issue by awesome-pro** [formbricks/formbricks#3663]
### What side quest or challenge are you solving?

Following Twitter of [Formbricks](https://x.com/formbricks) and [oss.gg](https://x.com/ossgoodgame)

### Points

/50

### Description

Put a lot of efforts to click the `Follow` button, and finally after thousands of nanoseconds, I successfully achieved my goal to follow Formbricks and oss.gg :)

### Provide proof that you've completed the task

<img width="979" alt="Screenshot 2024-10-14 at 8 52 10 AM" src="https://github.com/user-attachments/assets/f2ceef53-32c4-4fa2-be71-fe015d011b9e" width="600">

<img width="981" alt="Screenshot 2024-10-14 at 8 48 56 AM" src="https://github.com/user-attachments/assets/2be25d22-67cb-498b-ade0-f362db47c088">

**Comment by ritikpal1122** [comment]
Put a lot of efforts to click the Follow button, and finally after thousands of nanoseconds, I successfully achieved my goal to follow Formbricks and oss.gg :)

![osstwi](https://github.com/user-attachments/assets/e5794b85-9066-4b68-84c5-f1777304b50b)
![famtwi](https://github.com/user-attachments/assets/2c77d859-3903-4dc7-b609-42a3cacfb9ca)
