### ISSUE TITLE
[🕹️] Like and Repost the oss.gg lauch Tweet

### ISSUE THREAD

**Issue by awesome-pro** [formbricks/formbricks#3665]
### What side quest or challenge are you solving?

Liking ❤️ & Reposting the [oss.gg launch tweet](https://x.com/ossgoodgame/status/1841019549183066552)

### Points

150

### Description

This work of toughest oss contribution of my life, even YC backed start-ups haven't assigned me such a complex task ;)

### Provide proof that you've completed the task

Finally, I liked and reposted the oss.gg launch tweet with smile 😊 on my face 

<img width="975" alt="Screenshot 2024-10-14 at 8 53 31 AM" src="https://github.com/user-attachments/assets/30947f53-b774-4b4e-b4c1-2c18e952b264">

**Comment by jobenjada** [comment]
/award 50 thanks mate - hope it wasn't too hard for you ;)
