### ISSUE TITLE
[🕹️]The quest to follow Frombricks on LinkedIn

### ISSUE THREAD

**Issue by rajeevDewangan** [formbricks/formbricks#3670]
### What side quest or challenge are you solving?

The quest to follow Frombricks on LinkedIn

### Points

50

### Description

Followed formbricks on LindedIn

### Provide proof that you've completed the task

![Screenshot 2024-10-14 094523](https://github.com/user-attachments/assets/ec44e69d-338e-4205-a61c-e361f0e89a5e)

**Comment by ritikpal1122** [comment]
Followed formbricks on LindedIn

![ssform](https://github.com/user-attachments/assets/15db405f-6a31-4a61-8201-18d2c0a0aecd)

**Comment by Shreyasaraf01** [comment]
![WhatsApp Image 2024-10-14 at 9 36 30 PM](https://github.com/user-attachments/assets/72955e04-a428-45dd-a968-03815f163308)
I have followed your page on LinkedIn

**Comment by Shreyasaraf01** [comment]
![WhatsApp Image 2024-10-14 at 9 36 30 PM](https://github.com/user-attachments/assets/e5484e49-0c5f-4346-82f7-f6c9c49c396d)
I have followed your page on Linkedin
