### ISSUE TITLE
[🕹️]Like and Repost the oss.gg lauch Tweet

### ISSUE THREAD

**Issue by GAURAV8520** [formbricks/formbricks#3671]
### What side quest or challenge are you solving?

Liking ❤️ & Reposting the [oss.gg launch tweet](https://x.com/ossgoodgame/status/1841019549183066552)

### Points

150

### Description

I liked and reposted the oss.gg launch tweet 

### Provide proof that you've completed the task

![Screenshot 2024-10-14 093109](https://github.com/user-attachments/assets/94596762-5d8e-4762-8cc4-6e829fa5c84a)

**Comment by ritikpal1122** [comment]
I liked and reposted the oss.gg launch tweet

![oss](https://github.com/user-attachments/assets/e2ab14c3-2fe5-459a-b27e-a39a5dee85fe)
