### ISSUE TITLE
[🕹️] Quest Submission: Spreading the word of oss.gg to Tech Influencers

### ISSUE THREAD

**Issue by awesome-pro** [formbricks/formbricks#3672]
### What side quest or challenge are you solving?

I am taking **The Great Task** to **Spread the word of oss.gg** to tech Influencers

### Points

50 * 4 = 200

### Description

It was a relatively harder task, but I gulped some bowls  of Asiprin 200mg with Hot Alcohol and performed it successfully 
Thanks to @jobenjada  sir,

So I spread the word of mouth to Tech Influencers latest videos (bcz they have most traffic, and creator's attention)

### Provide proof that you've completed the task

<br />
<br />

> https://www.youtube.com/watch?v=qYslH4BZTsY

<img width="989" alt="Screenshot 2024-10-14 at 9 41 35 AM" src="https://github.com/user-attachments/assets/e5374c31-6605-45d9-90ec-9251f4fc9ab3" width="400px" >

<br />
<br />

> https://www.youtube.com/watch?v=S7XpTAnSDL4&t=1s
<img width="997" alt="Screenshot 2024-10-14 at 9 37 41 AM" src="https://github.com/user-attachments/assets/6f4d6acb-074e-4219-8cba-35c03eef3a5d">

> https://www.youtube.com/watch?v=pN-fA9CvJBk&t=4s
<img width="1001" alt="Screenshot 2024-10-14 at 9 33 48 AM" src="https://github.com/user-attachments/assets/ffebcfb8-007d-4c70-b6e4-f683c700cef3">

> https://www.youtube.com/watch?v=uegGGlQX3Ns&t=1s
<img width="1440" alt="Screenshot 2024-10-14 at 9 28 46 AM" src="https://github.com/user-attachments/assets/9e628057-fb9a-40b1-85ce-8a3221f91f1e">

**Comment by jobenjada** [comment]
hey :)

thanks a lot! max 3 is possible per player -> /award 150
