### ISSUE TITLE
[🕹️]Meme Magic

### ISSUE THREAD

**Issue by rajeevDewangan** [formbricks/formbricks#3673]
### What side quest or challenge are you solving?

Meme Magic

### Points

150

### Description

meme of a brick

### Provide proof that you've completed the task

![Screenshot 2024-10-14 100547](https://github.com/user-attachments/assets/eccc4def-c29d-4d16-a25b-c2aa2122b75d)

**Comment by jobenjada** [comment]
what is that? 🤓  can you explain how it is a meme?

**Comment by rajeevDewangan** [comment]
“When they least expect it” The phrase is a classic setup in meme culture.
And If this catches on, people might start sharing the brick-cat or create similar memes, like a "dog potato," using the same caption. It could become a running joke where everyday objects are mixed with animal traits and posted unexpectedly.
