### ISSUE TITLE
[🕹️] San Fransico Bill Board Ad 

### ISSUE THREAD

**Issue by awesome-pro** [formbricks/formbricks#3674]
### What side quest or challenge are you solving?

Creating a SF Bill Board for Formbricks

### Points

300

### Description

I made day-night efforts and finally crafted this masterpiece :)

### Provide proof that you've completed the task

![formbricks](https://github.com/user-attachments/assets/788c74a7-0e00-46de-8adc-d8f485de36fd)

**Comment by jobenjada** [comment]
text is not readable - pls try again :)
