### ISSUE TITLE
[🕹️]Followed on linkedin

### ISSUE THREAD

**Issue by aimun-naharr** [formbricks/formbricks#3675]
### What side quest or challenge are you solving?

![image](https://github.com/user-attachments/assets/b8badf3d-4b3f-4279-b405-7ba82e669f48)

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/a5fc55ba-a3f4-4787-a913-43d60bd215f8)

**Comment by smitpatel004** [comment]
![Screenshot 2024-10-14 120424](https://github.com/user-attachments/assets/9a817c97-9551-40e3-9e9f-bd7f331bc8e2)
I followed LinkedIn page of Formbricks
