### ISSUE TITLE
[🕹️] Followed LinkedIn page

### ISSUE THREAD

**Issue by itzdanishsalmani** [formbricks/formbricks#3678]
### What side quest or challenge are you solving?

Followed LinkedIn page

### Points

50

### Description

I followed LinkedIn page of Formbricks

### Provide proof that you've completed the task

![Screenshot from 2024-10-14 12-17-24](https://github.com/user-attachments/assets/3b714a9b-326c-4b27-84c4-0fd6e6907f5a)

**Comment by sankethl27** [comment]
### What side quest or challenge are you solving?
Followed LinkedIn page

Points
50

### Description
I followed LinkedIn page of Formbricks

### Provide proof that you've completed the task
![Screenshot 2024-10-14 195237](https://github.com/user-attachments/assets/937b11f1-4049-4ade-b13c-269c2a535f3c)
