### ISSUE TITLE
[🕹️] Liked and retweeted the oss.gg on X

### ISSUE THREAD

**Issue by itzdanishsalmani** [formbricks/formbricks#3679]
### What side quest or challenge are you solving?

Liked and retweeted the oss.gg twitter post

### Points

50

### Description

Liked & Retweeted the post on X(twitter)

### Provide proof that you've completed the task

![Screenshot from 2024-10-14 12-23-27](https://github.com/user-attachments/assets/768367f9-7f71-4d84-83ab-acedf7a96d83)

**Comment by Tarandeep-singh1** [comment]
where to provide proof

**Comment by Tarandeep-singh1** [comment]
![oss](https://github.com/user-attachments/assets/8dc06aef-f8df-4e07-b22b-c542b6899bae)
