### ISSUE TITLE
[BUG] Survey still shown after timeout despite URL mismatch

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#3681]
### Issue Summary

When triggering a survey with a condition such as "show on pages that include '/search'" and adding a delay (e.g., 10 seconds), the survey still pops up after the timeout even if the user navigates to a different page. This behavior occurs only in a single-page application (SPA) environment, where the URL no longer matches the condition.

### Steps to Reproduce

1. Set up a trigger with the condition: "Show on pages that include '/search'."
2. Add a delay of 10 seconds to the survey.
3. In a single-page application, navigate to a page that includes '/search'.
4. Before the 10-second delay completes, navigate to another page that doesn't match the trigger condition.

### Expected behavior

The survey should not be shown if the user navigates to a page that doesn't match the trigger condition, even after the delay.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
Single-page application (SPA)
```

**Comment by raggettii** [comment]
Can you please assign this issue to me so thar I can work on this issue.
