### ISSUE TITLE
[🕹️]Followed the formbricks linkedin page.

### ISSUE THREAD

**Issue by Kiran-F** [formbricks/formbricks#3684]
### What side quest or challenge are you solving?

The side quest which gives 50 points for following the LinkedIn page of formbricks.

### Points

This contribution has 50 points.

### Description

I've followed the linkedin page of formbricks to get the 50 points.
My linkedin : https://www.linkedin.com/in/kiran-fatima-6566622a7/

### Provide proof that you've completed the task

![Screenshot (674)](https://github.com/user-attachments/assets/19209a63-7935-49a8-ba1a-16e6de5b5489)

**Comment by chavarahul** [comment]
![Screenshot 2024-10-14 153951](https://github.com/user-attachments/assets/cd207830-2231-4e99-9d2a-41cf4cd902f5)
my linkedin profile: https://www.linkedin.com/in/chava-rahul-b99a62253/
