### ISSUE TITLE
[🕹️] Design a background Side Quest

### ISSUE THREAD

**Issue by adityadeshlahre** [formbricks/formbricks#3686]
### Description

Create my own background image and an animated video slightly oss.gg inspired!
Locally tested 

### Preview Video
https://drive.google.com/file/d/1BISB832exG0u2luOOEjdpZYrGWrL1RhS/view?usp=sharing

### Preview Image
https://drive.google.com/file/d/1GQFNzhJYynBA8z-0exAP6MUFTVMrcDhL/view?usp=sharing

### Version A
https://drive.google.com/file/d/1GGAClkKZMbe8WWmT3Y_HiYjn-N-AsUmi/view?usp=sharing

### Version B
https://drive.google.com/file/d/1TupJbHoENh4RwuG2ogirBNgTA1gjQknZ/view?usp=sharing

## Note : No copywrited thing I have used to create this Video/Image!

Thank You :slightly_smiling_face:

**Comment by jobenjada** [comment]
hey mate :)

i like that you put in the work, but an oss.gg themed background doesn't make soo much sense for Formbricks as a product.

Secondly, I thin the game controllers aren't really animated, they just pop up and it kinda looks like a bug.

I'll award you 300 points for your effort and creativity but don't think we'll use that for our product.

/award 300

thanks! :))
