### ISSUE TITLE
[🕹️] Brickifying SOMEONE FAMOUS

### ISSUE THREAD

**Issue by shreykx** [formbricks/formbricks#3687]
### What side quest or challenge are you solving?

I **BRICKIFIED** someone **FAMOUS** AND **TAGGED** [@formbricks](x.com/formbricks)

### Points

150

### Description

**I BRICKIFIED SOMEONE**

### Provide proof that you've completed the task

![Screenshot_2024-10-14-14-26-51-271_com twitter android](https://github.com/user-attachments/assets/7c50065b-caca-4f9c-acf6-ba0187f3371b)
Find it [here](https://x.com/shreykx/status/1845749698436497743?t=FoqeuvfJpF58G0AJzJDAmg&s=19).

**Comment by shreykx** [comment]
So this is the revised one @jobenjada 😅

**Comment by jobenjada** [comment]
/award 150 thanks mate, much better :)
