### ISSUE TITLE
[FEATURE] As a user I want to see who is the owner of a team

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#369]
**Is your feature request related to a problem? Please describe.**
Currently, it is unclear who has which role in a team:

![grafik](https://github.com/formbricks/formbricks/assets/72809645/503f0b24-7dba-4ef0-a6b9-1a0f73ae0e52)

**Describe the solution you'd like**
Display the team role with a badge.

**Additional context**

**Comment by Ashutosh-Bhadauriya** [comment]
@jobenjada can you please assign this issue to me.
