### ISSUE TITLE
[🕹️] Followed the formbricks linkedin page.

### ISSUE THREAD

**Issue by prtkjakhar** [formbricks/formbricks#3692]
### What side quest or challenge are you solving?

The side quest which gives 50 points for following the LinkedIn page of formbricks.

### Points

50

### Description

I've followed the linkedin page of formbricks.
My linkedin: https://www.linkedin.com/in/prateek-jakhar-a64a04197/

### Provide proof that you've completed the task

![Screenshot 2024-10-14 at 3 20 38 PM](https://github.com/user-attachments/assets/def6afbb-f5c8-4445-8b71-569d2960c2c1)

**Comment by PankajKumarAgrawal1729** [comment]
\assign

**Comment by PankajKumarAgrawal1729** [comment]
<img width="959" alt="formbrick-followed-proof" src="https://github.com/user-attachments/assets/20bfaf2c-cddc-4bde-af8a-e522c409e01a">

**Comment by chavarahul** [comment]
![Screenshot 2024-10-14 153951](https://github.com/user-attachments/assets/9470dc33-bac2-4045-9812-8ddf266ecdf1)
I've followed the linkedin page of formbricks.
My linkedin:  https://www.linkedin.com/in/chava-rahul-b99a62253/
