### ISSUE TITLE
Add URL Question Type [FEATURE]

### ISSUE THREAD

**Issue by atulmedpiper** [formbricks/formbricks#3694]
### Is your feature request related to a problem? Please describe.

Add URL Question Type

### Describe the solution you'd like

Addition of a URL Question type to enhance form functionality, enabling users to provide and validate website links efficiently. This feature will streamline the collection of web addresses, ensure accurate data, and improve the overall user experience when working with URLs.

**Comment by jobenjada** [comment]
hey! in the free text question you can choose type URL :)
