### ISSUE TITLE
[🕹️]Add URL Question Type

### ISSUE THREAD

**Issue by atulmedpiper** [formbricks/formbricks#3696]
### What side quest or challenge are you solving?

Addition of a URL Question type to enhance form functionality, enabling users to provide and validate website links efficiently. This feature will streamline the collection of web addresses, ensure accurate data, and improve the overall user experience when working with URLs.

### Points

1000

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/26955000-7569-4b74-ade4-a1b52d9840fd)

**Comment by jobenjada** [comment]
in the free text question we have type URL :)
