### ISSUE TITLE
[🕹️] oss.gg related Side Quests & Formbricks Side Quests Multiple

### ISSUE THREAD

**Issue by thefool76** [formbricks/formbricks#3699]
### What side quest or challenge are you solving?

oss.gg side quest and form brick side quest multiple

### Points

1350

### Provide proof that you've completed the task

Oss.gg related side Quest
1. Like & [Re-Tweet oss.gg Launch Tweet ](https://x.com/ossgoodgame/status/1841019549183066552)(50 Points):
![Screenshot 2024-10-14 at 2 46 17 PM](https://github.com/user-attachments/assets/d17edf20-8000-42ee-969e-94e1c6c7f995)
2. upvote and comment on [Reddit launch thread](https://www.reddit.com/r/opensource/comments/1ftwbl9/weve_spent_a_few_months_building_ossgg_to_gamify/) (50 Points): [Post is Locked by Mods so upvoted]

![WhatsApp Image 2024-10-14 at 14 42 22](https://github.com/user-attachments/assets/6fbeb870-abbc-4657-a691-b89cb5d3cbaa)
3. Spread the word (50 per influencer, max. 3 influencers):  150 points
![Screenshot 2024-10-14 at 2 55 13 PM](https://github.com/user-attachments/assets/cae0db4f-5d4d-4ca3-a53c-ab01a683cbf7)
![Screenshot 2024-10-14 at 2 56 22 PM](https://github.com/user-attachments/assets/9945a080-f430-4412-9f26-8fa726825579)

![Screenshot 2024-10-14 at 2 57 49 PM](https://github.com/user-attachments/assets/c7478ba9-b823-4b27-b031-19fd4dca6d5c)

4.San Francisco Billboard Ad (300 Points):
[Click here](https://drive.google.com/file/d/1em2Hn7zi1np_Zu-WZtmd8DrLvzG7VCoM/view?usp=sharing)

5.Meme Magic (150 Points)
[Click here](https://x.com/thefool1135/status/1845766451824820279)

6.Gif Magic (150 Points)
[Click here](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbDd6b2kyZWtrMG9lYWNjZjg1bHhicDZpZmtpaWFxejk5a3Jxc2t5biZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/0Bivpi43iVeoBoZ509/giphy.gif)

7.Follow [Formbricks LinkedIn](https://linkedin.com/company/formbricks) Page (50 Points):
![Screenshot 2024-10-14 at 3 51 11 PM](https://github.com/user-attachments/assets/7beacfc6-89a6-4b59-8346-6cc5f7c50fba)

8.Brickify someone famous with AI (150 Points)
[Click Here](https://x.com/thefool1135/status/1845774688754270402)

9.Design a background (300 Points for Images, 750 Points for Videos): 
Image web [Download](https://drive.google.com/file/d/1TUiAlRcpSfzKustQO-aEAWLOyZLvG4be/view?usp=sharing)
source link for use [Click here](https://www.pexels.com/photo/closeup-photo-of-brown-and-black-dog-face-406014/)
points- 300
![Screenshot 2024-10-14 at 5 25 51 PM](https://github.com/user-attachments/assets/99bebcdb-3294-449c-a4fd-5388077fd55f)

**TOTAL POINTS - 1350**

**Comment by jobenjada** [comment]
/award 1350

good job mate!

wanna make another 150 points? Open a PR where you add this image to the list :)

**Comment by thefool76** [comment]
> /award 1350
> 
> good job mate!
> 
> wanna make another 150 points? Open a PR where you add this image to the list :)

Sure I'll do it I am also doing a shader gradient effect animation video should I add it too to the PR ? Is there any requirement I saw there are some 4K mp4 videos as well
