### ISSUE TITLE
[BUG] Example links in the docs are broken

### ISSUE THREAD

**Issue by harshsbhat** [formbricks/formbricks#3701]
### Issue Summary

https://formbricks.com/docs/app-surveys/framework-guides#

Links are broken for examples in the above link. 

### Steps to Reproduce

1. Go to https://formbricks.com/docs/app-surveys/framework-guides#
2. Click on any of the examples from next, vue, etc. 
3. Notice that link redirect to github 404 page

### Expected behavior

It should redirect to a proper example. You will need to ask one of the maintainers for where the examples are relocated

### Screenshots

![image](https://github.com/user-attachments/assets/bc6243b3-1c35-40ca-8228-48417509141f)
 
these examples specifically

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by AbhishekCS3459** [comment]
Hey I want to work on this issue please assign it to me.

**Comment by DivyanshuLohani** [comment]
I belive no examples are yet written on which you can be redirected so I guess the links are just placeholders for now

**Comment by jobenjada** [comment]
works for me :)

**Comment by harshsbhat** [comment]
@jobenjada I am pretty sure there is some sort of misunderstanding here. Here is the video for the same issue please check:

https://www.loom.com/share/7c51ae2fb2e2452d96d3a630c4b9ecc0?sid=765790bf-6081-4834-9a0d-aa958b4019d8
