### ISSUE TITLE
[BUG] Header Overlaps Account Settings in Scrollable Views

### ISSUE THREAD

**Issue by r0x5r** [formbricks/formbricks#3714]
### Issue Summary

When scrolling on the "Account Settings" page, the header overlaps the "Account" section, making it hard to see. The header is the same color as the page, which causes the content to get hidden and hard to differentiate.

### Steps to Reproduce

1. Go to the "Account Settings" page.
2. Scroll down.
3. Notice that the "Account" section gets cut off because of the header.

### Expected behavior

The header should not hide the content, and it should be a different color to stand out from the page.

### Other information

1. Change the header color to something different from the rest of the page.
2. Make sure the header doesn’t overlap the content when scrolling.

### Screenshots

![account](https://github.com/user-attachments/assets/c22d85e4-cf1e-4fec-85a5-fe0e48c296eb)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by jobenjada** [comment]
who can fix this properly?

**Comment by GodParticle1996** [comment]
> who can fix this properly?

I can give it a try. Thanks

**Comment by Khaan25** [comment]
Hey, I know this issue - I saw this while fixing another PR.

Can I work on this one?

**Comment by Lonka-Pardhu** [comment]
@Khaan25 that is already assigned to @GodParticle1996
