### ISSUE TITLE
[🕹️]Meme Magic 

### ISSUE THREAD

**Issue by ishwarthecodddr** [formbricks/formbricks#3717]
### What side quest or challenge are you solving?

Craft a meme where a brick plays a role.

### Points

150

### Description

Crafted a meme where a brick plays a role.

### Provide proof that you've completed the task

proof:
https://x.com/IThecoder32719/status/1845902745020027332/photo/1

**Comment by jobenjada** [comment]
dont get it 🤓

**Comment by ishwarthecodddr** [comment]
it means that brick thought itself to be powerful as it is used to build great monuments but it was alone it realised it is not as strong as it thought it was 😊
