### ISSUE TITLE
[🕹️]Gif Magic 

### ISSUE THREAD

**Issue by ishwarthecodddr** [formbricks/formbricks#3718]
### What side quest or challenge are you solving?

Create a branded gif related to Formbricks.

### Points

150

### Description

Created a branded gif related to Formbricks where, A brick is sitting sad realizing it is not as strong as it thought.

### Provide proof that you've completed the task

Giphy link:
https://giphy.com/gifs/CiRFv5dLoboGXkfYe9

**Comment by jobenjada** [comment]
also dont get it ;)

**Comment by ishwarthecodddr** [comment]
it means that brick thought itself to be powerful as it is used to build great monuments but it was alone it realised it is not as strong as it thought it was 😊
