### ISSUE TITLE
[🕹️] Quest Submission: Brickify someone with AI

### ISSUE THREAD

**Issue by awesome-pro** [formbricks/formbricks#3731]
### What side quest or challenge are you solving?

One of the hardest task to brickify someone using the AI present on earth

### Points

just 150 

### Description

Brickified a famous personality, now the task is yours to find who is this, (think carefully a decade or two back)

### Provide proof that you've completed the task

![Firefly generate a brickified image (image made of bricks ) of any famous personality like steve job](https://github.com/user-attachments/assets/85c922d9-5e58-4b07-9765-dc8be5e39cde)

**Comment by Ayushkumarsinha123** [comment]
![theRock_bricks](https://github.com/user-attachments/assets/d251320f-6dd3-4eee-b684-93db6f6fdbab)

-->Brickified Dwayne Douglas Johnson(The Rock)

**Comment by Ayushkumarsinha123** [comment]
@awesome-pro reward..?

**Comment by jobenjada** [comment]
who dat @awesome-pro  ??

@Ayushkumarsinha123 you need to open your own issue for the points
