### ISSUE TITLE
[🕹️] Follow Formbricks LinkedIn Page (50 Points)

### ISSUE THREAD

**Issue by Chirag8023** [formbricks/formbricks#3733]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page (50 Points):

### Points

50

### Provide proof that you've completed the task

ID: https://www.linkedin.com/in/chirag-chirag-013068333/
---
![Screenshot (35)](https://github.com/user-attachments/assets/5e12533e-023a-4936-9f16-53f7f45496dc)

**Comment by Warfare-athens** [comment]
![Screenshot 2024-10-15 124648](https://github.com/user-attachments/assets/9fd8b194-f5c0-4de8-aa03-2973978b2375)
follow done
