### ISSUE TITLE
[🕹️] Brickify someone famous with AI (150 Points)

### ISSUE THREAD

**Issue by Khaan25** [formbricks/formbricks#3734]
### What side quest or challenge are you solving?

 Brickify someone famous with AI (150 Points)

### Points

150

### Description

Here's a picture of elon musk! (Tried my best with AI)

I know it doesn't look exactly like him. lol

### Provide proof that you've completed the task

![elon musk brickify](https://github.com/user-attachments/assets/f3637dcf-561e-482c-960b-824801c37bf9)

**Comment by Rohan-Rathod** [comment]
What side quest or challenge are you solving?
Brickify someone famous with AI (150 Points)

Points
150

Description
Here's a picture of narendra modi! (Tried my best with AI)


Provide proof that you've completed the task
![image](https://github.com/user-attachments/assets/e783e2fa-7997-4514-b56a-135949a13ca9)

**Comment by jobenjada** [comment]
these are not brickyfied versions of famous people but famous people in front of brick walls :D

**Comment by Khaan25** [comment]
Right. From where do I create something like that? I've tried many AIs to get it done but this was one of the best output? 😅

**Comment by Khaan25** [comment]
@jobenjada Here's brickified version of Quaid e Azam

![quaid-e-azam](https://github.com/user-attachments/assets/e46c5220-e801-4957-a82f-1947e8a2ceb4)
