### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page (50 Points)

### ISSUE THREAD

**Issue by sangram20** [formbricks/formbricks#3736]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page (50 Points)

### Points

50

### Provide proof that you've completed the task

**ID : https://www.linkedin.com/in/sangram-ghadage-b32a2b257/**

![Screenshot 2024-10-15 114513](https://github.com/user-attachments/assets/58ff3f5b-2f82-4ca9-a6d4-57b65eff3d2f)

**Comment by Ayushkumarsinha123** [comment]
![Screenshot 2024-10-15 115821](https://github.com/user-attachments/assets/d760d564-1893-4727-8131-3b3494696576)
ID : https://www.linkedin.com/in/ayush-kumar-sinha-1592882a8/

**Comment by abhi267266** [comment]
![IMG_1116](https://github.com/user-attachments/assets/38f38e9e-05d6-4061-afdc-197cb90eeea4)
id: [https://www.linkedin.com/in/abhishek-pathak-b04108250?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app](url)

**Comment by Rohan-Rathod** [comment]
![image](https://github.com/user-attachments/assets/e79ffe4d-974a-4448-bdb6-82b7d62a66ba)
ID: https://www.linkedin.com/in/rathodrohan222/

**Comment by SinuKumar069** [comment]
![Screenshot 2024-10-15 152619](https://github.com/user-attachments/assets/d8d7fb38-68e8-4419-86db-ba05058cd4f3)
ID : https://www.linkedin.com/in/sinu-kumar-6788902a8/
