### ISSUE TITLE
[🕹️] Meme Magic (150 Points) + Gif Magic (150 Points) 

### ISSUE THREAD

**Issue by Khaan25** [formbricks/formbricks#3738]
### What side quest or challenge are you solving?

Meme Magic (150 Points) + Gif Magic (150 Points) 

### Points

150 + 150

### Provide proof that you've completed the task

![supermeme_11h37_51](https://github.com/user-attachments/assets/b71c378d-c6f1-4468-9fb9-d3fcbacdd8ac)
![supermeme_11h39_8](https://github.com/user-attachments/assets/50e56836-3f80-4d74-855c-9ffe3288d10a)

**Comment by chavdarohit** [comment]
![Uploading 7f2eeac26d68474f02ef41b17969816b.jpg…]()

**Comment by jobenjada** [comment]
pls post on FB and upload to giphy to get ponts :)

**Comment by Khaan25** [comment]
What do you mean by FB :)

**Comment by Khaan25** [comment]
I've uploaded to giphy

https://giphy.com/gifs/LxWM4tERngPSPTphIx
![image](https://github.com/user-attachments/assets/b99ac2aa-6bed-4000-8c14-de949f51c2aa)

**Comment by Khaan25** [comment]
Posted on X: https://x.com/zia_webdev/status/1846407778207686694

![image](https://github.com/user-attachments/assets/a228d54d-ae88-4ac3-9c4a-f437f3f9440e)

**Comment by Khaan25** [comment]
@jobenjada
