### ISSUE TITLE
[🕹️] oss.gg side quest

### ISSUE THREAD

**Issue by Agnibaan** [formbricks/formbricks#3740]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page

### Points

50 points

### Description

i have followed the linkedln page of formbricks

### Provide proof that you've completed the task

![Screenshot 2024-10-15 121621](https://github.com/user-attachments/assets/17cc502e-4fd3-4eaf-98bc-681f477251d9)

**Comment by Gautam7352** [comment]
i have followed the linkedln page of formbricks
![Screenshot 2024-10-16 002451](https://github.com/user-attachments/assets/aab31dbe-23f3-40e7-a34d-8b3bb8f6e475)
