### ISSUE TITLE
Starry-eyed Supporter (150 Points)

### ISSUE THREAD

**Issue by antilpiyush89** [formbricks/formbricks#3741]
### What side quest or challenge are you solving?

Get five friends to star our repository.

### Points

150 points

### Provide proof that you've completed the task

![IMG-20241015-WA0002](https://github.com/user-attachments/assets/7075b256-0e1d-4db8-bd5b-4e0add7838d0)
![IMG-20241015-WA0003](https://github.com/user-attachments/assets/4597e38a-024d-4eca-9df9-fa8e1391c41c)
![IMG-20241014-WA0024](https://github.com/user-attachments/assets/6d0a39cd-7dbf-4be6-8aaf-333f7ba150cb)
![IMG-20241015-WA0009](https://github.com/user-attachments/assets/eafae720-2415-4833-b23c-b35b3ed8bd66)
![IMG-20241015-WA0010(1)](https://github.com/user-attachments/assets/bb0fc135-d7fa-4416-b0c7-8d39d04e55fb)

**Comment by jobenjada** [comment]
legend!! /award 150
