### ISSUE TITLE
[🕹️] Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by ayyash1** [formbricks/formbricks#3748]
### What side quest or challenge are you solving?

Like & Re-Tweet oss.gg Launch Tweet. Retweet it with a “🧱” emoji

### Points

50

### Description

I like and repost the post of oss.gg launch post on X.

### Provide proof that you've completed the task

![Screenshot 2024-10-15 141218](https://github.com/user-attachments/assets/13a48945-b878-4df1-b7c6-b5c1b10735f3)

username : @AyyashFous
link : https://x.com/AyyashFous/status/1846116539231002894

**Comment by chavdarohit** [comment]
https://x.com/CodeDesk13/status/1846245193659600899
<img width="1447" alt="Screenshot 2024-10-15 at 11 12 48 PM" src="https://github.com/user-attachments/assets/94c39694-3e5a-4c6c-b956-1e2014a80b35">
