### ISSUE TITLE
[🕹️] Follow Dub on Twitter

### ISSUE THREAD

**Issue by ayyash1** [formbricks/formbricks#3749]
### What side quest or challenge are you solving?

Follow Dub on Twitter

### Points

50

### Description

I followed Dub on X.

### Provide proof that you've completed the task

![Screenshot 2024-10-15 142341](https://github.com/user-attachments/assets/6cb40a44-d261-4e21-8b0d-7776a05d5282)

Username: AyyashFous

**Comment by kiinshuk** [comment]
assign

**Comment by jobenjada** [comment]
wrong repo mate
