### ISSUE TITLE
[🕹️] Follow Dub's LinkedIn Page

### ISSUE THREAD

**Issue by ayyash1** [formbricks/formbricks#3750]
### What side quest or challenge are you solving?

Follow Dub's LinkedIn Page.

### Points

50

### Description

I followed the Dub's linkedin page

### Provide proof that you've completed the task

![Screenshot 2024-10-15 142819](https://github.com/user-attachments/assets/5783058c-cc28-41f4-b224-123b6ef9560f)

username : Ayyash Fous

**Comment by jobenjada** [comment]
wrong repo mate
