### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page (50 Points)

### ISSUE THREAD

**Issue by PreethiMaddikunta** [formbricks/formbricks#3753]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page (50 Points):

### Points

50

### Provide proof that you've completed the task

ID: https://www.linkedin.com/in/preethi-m-26a599104/

![Screenshot ](https://github.com/user-attachments/assets/d7c44a10-2044-45c7-a26a-99b9e4ef77f0)

**Comment by SaidSafwan** [comment]
What side quest or challenge are you solving?
Follow Formbricks LinkedIn Page (50 Points):

Points
50

Description
No response

Provide proof that you've completed the task
ID: https://www.linkedin.com/in/mohdseyyedsafwan/

Screenshot 
![Screenshot (5)](https://github.com/user-attachments/assets/3ab9e304-8151-443e-8066-7c1f261654e4)
