### ISSUE TITLE
[🕹️] Follow Paper Mark Linkedin Page

### ISSUE THREAD

**Issue by ayyash1** [formbricks/formbricks#3755]
### What side quest or challenge are you solving?

Follow Paper Mark Linkedin Page

### Points

50

### Description

I followe papermark page on linkedin

### Provide proof that you've completed the task

![Screenshot 2024-10-15 143850](https://github.com/user-attachments/assets/f754f07a-3b7c-4452-9cc1-c2a44ab4ce7b)

username : Ayyash Fous

**Comment by jobenjada** [comment]
wrong repo mate
