### ISSUE TITLE
[🕹️] Follow Hanko LinkedIn Page

### ISSUE THREAD

**Issue by PreethiMaddikunta** [formbricks/formbricks#3756]
### What side quest or challenge are you solving?

Follow Hanko LinkedIn Page

### Points

50

### Description

I followed Hanko page in Linkedin

### Provide proof that you've completed the task

![Screenshot](https://github.com/user-attachments/assets/5b03301b-63dc-4a42-b06c-c0f54d0d7bb1)

**Comment by THuNDeR-001** [comment]
![Screenshot 2024-10-15 at 20 21 36](https://github.com/user-attachments/assets/307a18b7-b9ce-40e7-bd3c-a8395b7dfb23)
done

**Comment by jobenjada** [comment]
wrong repo mate
