### ISSUE TITLE
[🕹️] Accessibility Advocate 

### ISSUE THREAD

**Issue by DevGajjar28** [formbricks/formbricks#3762]
### What side quest or challenge are you solving?

Found UI bug at enterprise-survey-software page . UI is not responsive in small devices , found that the company trust label is issue for that.

### Points

50 - 300

### Description

Steps to reproduce : 
Footer >  Best Practices > click [Enteprise Survey Software](https://formbricks.com/enterprise-survey-software) 

I would like to resolve this if you assigned to me  under oss.gg and Hacktoberfest with code Quest point 

### Provide proof that you've completed the task

![Screenshot 2024-10-15 170030](https://github.com/user-attachments/assets/b72f2a32-28d9-455c-8b67-54daa4c714b9)
![Screenshot 2024-10-15 170042](https://github.com/user-attachments/assets/1b7836b8-2cb6-44de-b08c-591c9c9dc62c)

**Comment by jobenjada** [comment]
good catch! Will fix :)

/award 50 for spotting, even though the LP is not part of the hackathon so pls focus on the product 🤓
