### ISSUE TITLE
[BUG]: Scroll to Top Button Missing on All Pages Except Home Page

### ISSUE THREAD

**Issue by rajgharat07** [formbricks/formbricks#3769]
## Summary : 
The "Scroll to Top" button, which allows users to quickly return to the top of the page, only appears on the Home Page. It is missing from all other pages across the website, leading to inconsistent user experience and navigation difficulties when scrolling through longer content on other pages.

### Steps to Reproduce

- 1.(for example) Went to https://formbricks.com/pricing, https://formbricks.com/open-source-form-builder
- 2.Scroll down the page, and observe that the "Scroll to Top" button does not appear.
- 3.Note that the button should be visible, as it is on the Home Page.

### Expected behavior

The "Scroll to Top" button should be consistently visible and functional across all pages of the website, not just the Home Page. When a user scrolls down a page, the button should appear, and upon clicking, it should smoothly scroll back to the top of the current page.

### Other information

- Ensure that the button design and functionality are uniform across all pages.
- Check for any CSS or JavaScript conflicts that might be causing the button to be restricted to the Home Page.
- Test the button on different devices and browsers to ensure responsiveness and compatibility.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Node: any
- npm: any
```

**Comment by tejodeepmitraroy** [comment]
Hi @rajgharat07, I want to work on this issue, you all ready started ??

**Comment by jobenjada** [comment]
this landing page is not part of the hackathon :)
