### ISSUE TITLE
[🕹️] San Francisco Billboard Ad

### ISSUE THREAD

**Issue by shreykx** [formbricks/formbricks#3770]
### What side quest or challenge are you solving?

I have designed the SF billboard Ad for **Formbricks**.

### Points

300

### Provide proof that you've completed the task

![Green and White Conceptual New Season Billboard](https://github.com/user-attachments/assets/983a109f-d5d6-4cb2-81df-40de05ab4b81)
Here's SF
![image](https://github.com/user-attachments/assets/dbe246c7-fe65-46b1-a896-bc28e057bad0)

**Comment by DhruvWebDev** [comment]
can you explain what is the issue

**Comment by jobenjada** [comment]
/award 300 haha extreme but definitely techy :D
