### ISSUE TITLE
[🕹️]   Spread the word

### ISSUE THREAD

**Issue by DevGajjar28** [formbricks/formbricks#3776]
### What side quest or challenge are you solving?

Spread the word to favorite developer influencer

### Points

150 (50 each)

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/afe7a553-7d98-4cf5-9786-36da4de00a0e)
![image](https://github.com/user-attachments/assets/5b3a4fea-ee20-46b2-815b-8b9cdd22032f)
![image](https://github.com/user-attachments/assets/4d19cd9c-756c-4bb9-aab8-b4f50b1c6a72)
![image](https://github.com/user-attachments/assets/81899791-27f8-4622-a465-7edb2e93113b)

**Comment by jobenjada** [comment]
piyush already made a video on oss.gg :D 

/award 100 thanks!
