### ISSUE TITLE
[🕹️] Side Quest Submission: Followed on LinkedIn and X

### ISSUE THREAD

**Issue by Afridi-haque7** [formbricks/formbricks#3786]
### What side quest or challenge are you solving?

1. LinkedIn Page follow
2. X Account follow

### Points

100 points

### Description

Followed the LinkedIn and X account of Formbricks.

### Provide proof that you've completed the task

<img width="564" alt="image" src="https://github.com/user-attachments/assets/9834505e-1db4-4b54-8b55-115dd0e89168">
<img width="854" alt="image" src="https://github.com/user-attachments/assets/f3e13d28-25ee-4da7-87e3-385985825807">

**Comment by jobenjada** [comment]
/award 100 

thanks mate!
