### ISSUE TITLE
[🕹️] Background and GIF

### ISSUE THREAD

**Issue by harshsbhat** [formbricks/formbricks#3787]
### What side quest or challenge are you solving?

Design a background double points for video (600)

GIF and upload it to GIFY (150)

### Points

750

### Provide proof that you've completed the task

1. Making an animated background for formbricks. Since we don't allow to upload it yet I had to take screenshot to see how it looks : (SOURCE: animated by me so no need to worry about credits )

Video: 

https://github.com/user-attachments/assets/08401b74-eb2e-43cc-88c9-e5058f18e605

![Untitled design (1)](https://github.com/user-attachments/assets/70823e0d-eb6d-49fb-9b7b-28da8481c7f2)

2.  GIF:

https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHF6bjZnc2d3anFkbG9hMXJ0dXVjd2NraDBydHVxbDNmb2JjZmtkcSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/dTYLxu0dV1uYxM056V/giphy.gif

**Comment by harshsbhat** [comment]
Damn the bot is improving day by day

**Comment by jobenjada** [comment]
thats very cool! where did you find the root file for it? asking for copyright reasons :)

**Comment by harshsbhat** [comment]
@jobenjada I haven't used any root file here. Its just made from 4 color gradient. Created with after effects, I can email you the `.aep` file.

**Comment by jobenjada** [comment]
can you export a fullHD version?

/award 300

**Comment by harshsbhat** [comment]
> can you export a fullHD version?
> 
> 
> 
> /award 300

Sure. Github doesn't allow 10MB+ files. I will either mail you or upload on the drive/cloud and share the link

**Comment by harshsbhat** [comment]
Here is the link to the uncompressed 30 MB file.

https://drive.google.com/file/d/1LHHiNVMG_3MlWODJY4s-W5ThbohBXG-O/view

**Comment by jobenjada** [comment]
smoooth af - great work! /award 750
