### ISSUE TITLE
[🕹️] Side Quest Submission: Following LinkedIn and X account of Dub

### ISSUE THREAD

**Issue by Afridi-haque7** [formbricks/formbricks#3789]
### What side quest or challenge are you solving?

1. Following LinkedIn account of Dub
2. Following X account of Dub

### Points

100 points

### Description

Followed LinkedIn and X account of Dub

### Provide proof that you've completed the task

<img width="872" alt="image" src="https://github.com/user-attachments/assets/98bb8c4c-0187-4fc9-818d-0a864dd0ce5a">
<img width="826" alt="image" src="https://github.com/user-attachments/assets/9f115b2b-1445-4869-ba98-2f7dc437c97e">

**Comment by jobenjada** [comment]
wrong repo mate :)
