### ISSUE TITLE
[BUG] Inconsistent Loader Color for "Save" and "Save & Close" Buttons

### ISSUE THREAD

**Issue by sajidbashir123** [formbricks/formbricks#3792]
### Issue Summary

The loader color for the "Save" and "Save & Close" buttons is not consistent after clicking either button. The expectation is that both buttons should display the same loader color, but currently, they are showing different colors during the loading process.

### Steps to Reproduce

1. Go to the edit survey page with the "Save" and "Save & Close" buttons.
2. Click on the "Save" button and observe the loader color.
3. Click on the "Save & Close" button and observe the loader color.

### Expected behavior

 Both buttons should have the same loader color after clicking. I think it should be same as in overall app light dark or make as with Save & Close button.

### Screenshots

<img width="1432" alt="image (6)" src="https://github.com/user-attachments/assets/aea8a373-61a5-4346-81ed-76f236096dea">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Mac
- Browser: Chrome
- Version: latest
```

**Comment by chrahman** [comment]
Please /assign to me

**Comment by chrahman** [comment]
Please /assign this issue to me

**Comment by jobenjada** [comment]
good catch mate!
