### ISSUE TITLE
[FEATURE] Add Smooth Transition Effect to Navbar on Scroll

### ISSUE THREAD

**Issue by harshalhonmote** [formbricks/formbricks#3794]
### Is your feature request related to a problem? Please describe.

When scrolling on the website, the navbar visibility changes suddenly and appears instantly without a smooth transition.

https://github.com/user-attachments/assets/64d1c8d1-6040-44eb-95b6-3de32ae4bff8

### Describe the solution you'd like

The navbar should appear and disappear with a smooth transition when scrolling, creating a more visually appealing effect. Adding a transition property to the navbar will make it gradually visible or hidden, rather than suddenly.
 transition: top 0.3s;

**Comment by jobenjada** [comment]
hey! The landing page is not part of the bug hunting and accessibility programme :)
