### ISSUE TITLE
[🕹️] Change the button size in all modals to size "sm"

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3796]
### Is your feature request related to a problem? Please describe.

the buttons in the modals are very big

### Describe the solution you'd like

we want them in `size="sm"`

**Comment by Harish-Shejokar** [comment]
intresting issue

**Comment by silentboy-07** [comment]
//assign

**Comment by SwapnaneelR** [comment]
/assign 
please assign me this issue
