### ISSUE TITLE
[FEATURE] Add character limitations to free text question

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3798]
### Is your feature request related to a problem? Please describe.

we ned character limitations for the free text field

### Describe the solution you'd like

add min and max limits to the free text field question (should be possible to add both)

@mattinannt if you have time to write a ticket

**Comment by heygogu** [comment]
@jobenjada can you please explain where this free text question is in formbrickd

**Comment by rajgupta-ml** [comment]
I am solving this issue, will generate a PR in 24 hrs
