### ISSUE TITLE
Email notification after submission

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#38]
### Email notifications for each submission

As a user I want to get an email notification whenever a form was submitted.

**Comment by matthiasnannt** [comment]
@fdis111 Sure, awesome that you like to work on this feature 😊
I think the best way to integrate this is as a Pipeline (like a webhook). Currently we only have an event for a partial submission (pageSubmission). We don't have an event yet for a completed form. I would say you have the two options to calculate if this event should be triggered yourself when you receive a page submission (and check if it's the last page). or trigger this as a separate event in the react library.

**Comment by mattinannt** [comment]
closed with eee3ea5ed35ef822064e5bdd0e12d0f8d920e1ee
