### ISSUE TITLE
[BUG] Formbricks logo is not visible when the side bar is collapsed

### ISSUE THREAD

**Issue by abhignakumar** [formbricks/formbricks#3801]
### Issue Summary

When we collapse the side bar, them the logo is not visible. It is would be better if the logo is visible at all times.

### Steps to Reproduce

Open and close the side bar.

### Expected behavior

Logo should be visible when the side bar is collapsed.

### Screenshots

<img width="766" alt="Screenshot 2024-10-15 at 11 28 16 PM" src="https://github.com/user-attachments/assets/d27106ba-f23c-4cd3-a8c9-79cc14b16282">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: MacOS
- Node: 20.9.0
- npm: 10.1.0
```

**Comment by harshitcodez19** [comment]
Can I take a look at this issue ?

**Comment by jobenjada** [comment]
not a bug :)
