### ISSUE TITLE
[🕹️] Two Secret Side quests

### ISSUE THREAD

**Issue by Khaan25** [formbricks/formbricks#3804]
### What side quest or challenge are you solving?

Unlock two secret side quests (150 Points each)

### Points

300 (150 each)

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/7b692782-0332-47dc-afcc-5e813d50e6dc)
![image](https://github.com/user-attachments/assets/33c24788-8718-43c8-8369-e65dd4febf91)

**Comment by jobenjada** [comment]
removing duplicate points
