### ISSUE TITLE
[🕹️] Follow Dub.com on Twitter 

### ISSUE THREAD

**Issue by kiinshuk** [formbricks/formbricks#3805]
### What side quest or challenge are you solving?

Follow Dub on Twitter

### Points

50

### Description

I followed Dub on X.

### Provide proof that you've completed the task

![Screenshot (116)](https://github.com/user-attachments/assets/830e0b64-8534-4416-92ba-49d3c633b435)

**Comment by jobenjada** [comment]
wrong repo mate :)
