### ISSUE TITLE
[🕹️] Follow Dub.co on Linkedin

### ISSUE THREAD

**Issue by kiinshuk** [formbricks/formbricks#3806]
### What side quest or challenge are you solving?

Follow Dub.co on Linkedin

### Points

50

### Description

I followed Dub on Linkedin

### Provide proof that you've completed the task

![Screenshot (118)](https://github.com/user-attachments/assets/dad69016-3f8a-498d-acfc-87876106b9d5)

**Comment by jobenjada** [comment]
wrong repo mate :)
