### ISSUE TITLE
[🕹️]Followed Dub's LinkedIn Page

### ISSUE THREAD

**Issue by PranavS1604** [formbricks/formbricks#3809]
### What side quest or challenge are you solving?

Follow [Dub's LinkedIn](https://www.linkedin.com/company/dubinc) Page

### Points

50

### Description

I started following Dub's LinkedIn Page.

### Provide proof that you've completed the task

![Screenshot_20241016_141108](https://github.com/user-attachments/assets/d60de360-3002-4f95-8572-ccade0afed49)

**Comment by jobenjada** [comment]
wrong repo mate :)
