### ISSUE TITLE
[🕹️]🌟 Starry-eyed Supporter - [Tarandeep-singh1]

### ISSUE THREAD

**Issue by Tarandeep-singh1** [formbricks/formbricks#3810]
### What side quest or challenge are you solving?

I am solving the "Starry-eyed Supporter" side quest.

This involves getting 5 friends to star the repositories participating in the oss.gg hackathon and submitting screenshots as proof in each repository's issues.

### Points

1050

### Description

Hi team!

I've completed the "Starry-eyed Supporter" side quest by getting 5 friends to star this repository! 🎉
Thanks for this awesome opportunity to support your project and participate in the oss.gg hackathon!

### Provide proof that you've completed the task

![WhatsApp Image 2024-10-16 at 14 05 04_4c49a29b](https://github.com/user-attachments/assets/b85f2332-23e9-4927-a4be-f632a7cd3cc4)
![WhatsApp Image 2024-10-16 at 14 05 04_9c3b08d4](https://github.com/user-attachments/assets/7dc16b12-6a89-4731-a917-a7af6462d2df)
![WhatsApp Image 2024-10-16 at 14 05 04_8233c3ea](https://github.com/user-attachments/assets/e42183a0-447c-4e5b-9cba-0cd77eb33b41)
![WhatsApp Image 2024-10-16 at 14 05 05_c9190f0e](https://github.com/user-attachments/assets/4547ed1d-dca1-4d37-935d-0fc2bdf0a554)
![WhatsApp Image 2024-10-16 at 14 05 05_ca33668f](https://github.com/user-attachments/assets/a9028696-ed7d-4ba9-8102-9f612dd39b49)

**Comment by jobenjada** [comment]
the task is not to create 5 accounts and star the repo but to invite friends to do it.

❌ we have a 0 tolerance policy for cheating so you're disqualified to win any prizes ❌

**Comment by Tarandeep-singh1** [comment]
> the task is not to create 5 accounts and star the repo but to invite friends to do it.
> 
> ❌ we have a 0 tolerance policy for cheating so you're disqualified to win any prizes ❌

I didn't know.i think it was fine of creating friends new accounts.it is my first time i didn't know about rules.i understand my mistake and will not perform such type of actions again
