### ISSUE TITLE
[🕹️]Follow Dub on Twitter

### ISSUE THREAD

**Issue by PranavS1604** [formbricks/formbricks#3811]
### What side quest or challenge are you solving?

Follow [Dub on Twitter](https://twitter.com/dubdotco)

### Points

50 Points

### Description

Started following Dub on Twitter.

### Provide proof that you've completed the task

![Screenshot_20241016_142914](https://github.com/user-attachments/assets/24627547-d052-40ce-9a6c-176375caf62d)

**Comment by jobenjada** [comment]
wrong repo mate
