### ISSUE TITLE
[🕹️]Formbricks Side Quests [Gif Magic (150 Points): Create a branded gif related to Formbricks]

### ISSUE THREAD

**Issue by Rohan-Rathod** [formbricks/formbricks#3815]
### What side quest or challenge are you solving?

Gif Magic (150 Points): Create a branded gif related to Formbricks. Upload it to Giphy.

### Points

150

### Description

Giphy ID: https://giphy.com/channel/rathodrohan

<div style="width:100%;height:0;padding-bottom:67%;position:relative;"><iframe src="https://giphy.com/embed/sOf68B88nnXVXbQI37" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/sOf68B88nnXVXbQI37">via GIPHY</a></p>

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/28194170-56aa-492a-99b3-683cc5b7a506)

**Comment by Rohan-Rathod** [comment]
https://media.giphy.com/media/sOf68B88nnXVXbQI37/giphy.gif

**Comment by jobenjada** [comment]
haha nice! /award 150

can you tag #formbricks and #feedback ?
