### ISSUE TITLE
[🕹️]Follow Dub.co on Linkedin

### ISSUE THREAD

**Issue by Rohan-Rathod** [formbricks/formbricks#3817]
### What side quest or challenge are you solving?

ID: https://www.linkedin.com/in/rathodrohan222/

Follow Dub.co on Linkedin

### Points

50

### Description

I followed Dub on Linkedin

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/1fcfe220-2eb3-4003-a242-1c9082ee0502)

**Comment by jobenjada** [comment]
wrong repo mate
