### ISSUE TITLE
[🕹️] Completed side quest - Brickify #3405

### ISSUE THREAD

**Issue by rohitja26** [formbricks/formbricks#3818]
### What side quest or challenge are you solving?

Completed side quest - Brickify #3405
![Doctor Strange as a full brick figure, racing through the streets with brick muscle energy waves](https://github.com/user-attachments/assets/69db87ca-affc-40bf-970c-047eef609e3e)

### Points

150

### Description

Made the bricky doctor strange to complete the challange

### Provide proof that you've completed the task

![Screenshot 2024-10-16 170023](https://github.com/user-attachments/assets/3c3bb854-2d1d-45e7-bd4e-cb924d3cbb21)

**Comment by g76728443** [comment]
Please assign me this issue
