### ISSUE TITLE
[🕹️] Completed Side Quest: 5 Friends Starred Repositories

### ISSUE THREAD

**Issue by chrahman** [formbricks/formbricks#3820]
### What side quest or challenge are you solving?

1050 Points 🔥 Get 5 friends to star our repos

### Points

150

### Description

I have completed the side quest by having 5 of my friends star the required repositories. Below are the screenshots from their GitHub profiles as proof.

### Provide proof that you've completed the task

![5](https://github.com/user-attachments/assets/ceac56d9-9b2a-4dca-804d-645276460732)
![4](https://github.com/user-attachments/assets/ccf19543-a597-4f4f-a10b-6ae40d1632ff)
![1](https://github.com/user-attachments/assets/77dd90a2-6442-4c3e-a987-2a425b0879f3)
![2](https://github.com/user-attachments/assets/3e2bb0ad-8cde-4a8d-9966-0bb7ca8d1546)
![3](https://github.com/user-attachments/assets/fd621778-09fa-47bc-8b08-4960ef0bbf5f)

**Comment by jobenjada** [comment]
well done! You get 150 here and pls open the same issue in the other 6 repos

/award 150
