### ISSUE TITLE
[🕹️] Side Quest Submission: Brickify image of a famous person

### ISSUE THREAD

**Issue by Afridi-haque7** [formbricks/formbricks#3822]
### What side quest or challenge are you solving?

Brickify image of a famous person - Cristiano Ronaldo

### Points

150

### Description

Brickify image of a famous person with AI

### Provide proof that you've completed the task

![Untitled design](https://github.com/user-attachments/assets/77d908c4-5257-4507-af82-8088c10dc9f9)

**Comment by jobenjada** [comment]
please post that on Twitter and tag @formbricks
