### ISSUE TITLE
[BUG] Back button label text gets overridden

### ISSUE THREAD

**Issue by francescocan** [formbricks/formbricks#3835]
### Issue Summary

I am using Formbricks cloud. 

**Problem:**
When creating or editing cards in a Formbricks Cloud form, the back button label text for all cards is consistently overwritten with the text used on the last card saved. This occurs despite assigning unique back button text to each step of the form.

**Specific Behavior**:

Next Button: The next button label text remains as intended for each card.
Back Button: The back button label text for all cards is replaced with the text used on the most recently saved card.

### Steps to Reproduce

1. create different cards
2. edit the second card "Next" Button Label and "Back" Button Label with different names "Pluto" and "Mouse". Save.
3. edit the third card  "Next" Button Label and "Back" Button Label with NEW different names "Jerry" and "Tom"
when saving, Mouse is overwritten by Tom. Both cards now have the same "Back" Button Label but two different "Next" Button Labels (Pluto and Jerry).

### Expected behavior

Every "Back" Button Label should maintain its own value

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Firefox 128.3.1esr (64-bit)
```

**Comment by jobenjada** [comment]
thanks for flagging it! @Dhruwang pls have a look 🤓 

/award 150 for flagging the bug :)
