### ISSUE TITLE
[🕹️]Meme Magic

### ISSUE THREAD

**Issue by rajeevDewangan** [formbricks/formbricks#3838]
### What side quest or challenge are you solving?

Meme Magic

### Points

150

### Description

meme of brick

### Provide proof that you've completed the task

![Screenshot 2024-10-17 103444](https://github.com/user-attachments/assets/81bd11e5-bda0-4e84-9dbb-4d1203611fd8)

**Comment by jobenjada** [comment]
that was a good one! :D 

/award 150
