### ISSUE TITLE
[FEATURE] Identify users in link surveys with URL parameter

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#384]
**Is your feature request related to a problem? Please describe.**
As a user I cannot connect link survey responses to Persons in the Formbricks database. To be able to merge all feedback touch points, this is essential.

**Describe the solution you'd like**
Pass a user ID in the URL to connect a response with a person in the database. If there is not person existing with this user ID, create one.

**Note**

Users are called Persons in Formbricks.

Each Person has a unique Formbricks Id.

Each Person can have an attribute called User Id:

![grafik](https://github.com/formbricks/formbricks/assets/72809645/fc14f243-ef18-478d-9304-50133b0d0f77)

The user Id is the ID which the Formbricks users assign to their users in their applications. This external user ID is important to identify users across different apps e.g. when you want to send an email via [customer.io](http://customer.io) etc.

This feature deals with this external user ID which is passed to Formbricks via the URL parameter.

**Tasks**

1. Create a new API endpoint called “getOrCreate” under  /api/v1/client/environments/environmentId/people
    1. Pass the user ID from the URL parameter to it ( "?userId=ABC123" )
    2. The endpoint checks if a Person with this user ID exists:
        1. If person exists in db: get this Person
        2. If person does not exist: create new Person
    3. Return Person
2. Add the logic to LinkSurvey to check for “?userId=ABC123”
3. On page load, before the display gets created, send a request to the newly created endpoint and wait for the person to be sent back. Show loading spinner while waiting.
4. Use the internal Formbricks Id you got from the API to connect the response with the respondent
5. Show survey
6. Create display
7. Update the UI in the Responses tab to not display “Anonymous”  but the user ID which links to the User Detail Page:

![grafik](https://github.com/formbricks/formbricks/assets/72809645/a2ccfb6d-c945-4291-9120-550c7d701428)

## How to code for Formbricks

1. Make sure everything is type-safe
2. If you run `pnpm dev` you'll find a demo app to test in-app surveys at `localhost:3002`
3. When your code is done and working, paste it to chatGPT and ask for refactoring ideas. Apply what makes sense to you (GPT-4 is a lot better). Try out our new [Formbricks-Prompt](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) ✨

**Comment by joe-shajan** [comment]
Hey @jobenjada can I get this assigned. Will start working on it.

**Comment by Zorig** [comment]
@jobenjada i want to work on this one
