### ISSUE TITLE
[🕹️] San Francisco Billboard Ad

### ISSUE THREAD

**Issue by rajeevDewangan** [formbricks/formbricks#3842]
### What side quest or challenge are you solving?

San Francisco Billboard Ad

### Points

300

### Description

Designed an ad of Formbricks for San Francisco Billboard

### Provide proof that you've completed the task

![formbricksBanner](https://github.com/user-attachments/assets/a930e4d6-3222-42af-b43c-97c13e6fb562)
On the Billboard
![FormbricksBillboard](https://github.com/user-attachments/assets/c1e70e42-5e86-4dcb-a424-6ebd04b1a608)

**Comment by jobenjada** [comment]
wut? did you make that on your Atarti computer? :D

**Comment by rajeevDewangan** [comment]
😅 Well what now

**Comment by jobenjada** [comment]
sorry but I cant accept this. You can try again ;)
