### ISSUE TITLE
[🕹️] Followed Formbricks LinkedIn Page 

### ISSUE THREAD

**Issue by Abedee** [formbricks/formbricks#3845]
### What side quest or challenge are you solving?

Followed Formbricks LinkedIn Page

### Points

50 Points

### Provide proof that you've completed the task

![Screenshot 2024-10-17 144434](https://github.com/user-attachments/assets/b933e9bb-17a4-4798-914d-8fafcaa7a3ae)

**Comment by Nayakyash005** [comment]
proof of completed task
![Screenshot 2024-10-17 151303](https://github.com/user-attachments/assets/e9720b29-24a1-47e2-a9c0-db8f971305a1)
