### ISSUE TITLE
[BUG] Add User Action Form doesnot have a smooth transition when switching to code form non code

### ISSUE THREAD

**Issue by abhayofc** [formbricks/formbricks#3846]
### Issue Summary

There is a issue on the transition which does not looks smooth while switching to code from node code action

https://github.com/user-attachments/assets/48731b62-e8bc-4a43-b86c-773be575a287

### Steps to Reproduce

1. Go to actions
2. Click in Add action button
3. Try to change action type to code from non code

### Expected behavior

There must be a smooth transition.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Subhajit-garai** [comment]
I am solving this issue

**Comment by jobenjada** [comment]
not a bug, but thanks for looking into it!
