### ISSUE TITLE
[FEATURE] Add user roles to invite and allow changing roles

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#385]
**Is your feature request related to a problem? Please describe.**
As a team owner I cannot assign different roles to my team mates. Nor can I change roles of existing members.

**Describe the solution you'd like**

- Allow setting a role for new members in the invite process.
- Allow admins and owners to change roles of existing users

**Tasks**

1. In the invitation form add the option to assign a role to invitess using [shadcn UI:](https://ui.shadcn.com/docs/components/accordion)
    1. Admin
    2. Editor
    3. Developer
    4. Viewer

Leave out owner, because every team only has one owner.

![grafik](https://github.com/formbricks/formbricks/assets/72809645/2b90bdf0-cdd9-4522-a139-a72b21decd8c)

1. Adjust the invite stored in the db accordingly
2. Add role to session object
3. Client side: Display “Add member” button only for owner + admin
4. Server side: Prevent sending "Add member" from by checking for the right role in the API before creating the invite
5. Build UI to update roles of existing team members. Consider all implications: Prevent not being able to change your own role and only admin and owner can change roles. Etc. Use [shadcn UI](https://ui.shadcn.com/) to build cool way to do it
6. Change the variant of the “Add member” button to “darkCTA”

## How to code for Formbricks
1. Make sure everything is type-safe
2. If you run `pnpm dev` you'll find a demo app to test in-app surveys at `localhost:3002`
3. When your code is done and working, paste it to chatGPT and ask for refactoring ideas. Apply what makes sense to you (GPT-4 is a lot better). Try out our new [Formbricks-Prompt](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) ✨

**Comment by neilchauhan2** [comment]
@jobenjada Please assign this to me.

**Comment by jobenjada** [comment]
You got it :) Have fun 🥳
