### ISSUE TITLE
[🕹️] Improve preview of surveys shared on social

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3854]
### Is your feature request related to a problem? Please describe.

Currently, if a survey link gets shared on social, it sometimes looks like this:

<img width="646" alt="image" src="https://github.com/user-attachments/assets/df0af10b-5736-46c3-ae33-5b101fb3924d">

We have a different preview:
<img width="653" alt="image" src="https://github.com/user-attachments/assets/9cf8f3b8-8558-4bd5-836f-7d4b1866ca7f">

### Tasks

1. Find out what this card like preview is (the first image)
2. Look at how we built the second preview
3. Combine that knowledge and do the following:

- If a survey has a logo set, take that logo and place it on a light grey background (#f1f5f9)
- If it does not have a logo set, take the brandColor and add the Formbricks logo (attached)

![white-mono-base](https://github.com/user-attachments/assets/2b0a90e0-645f-4834-8683-efd9ed0f373b)

This is a research intensive task. It gives quite a lot of points so make sure to take your time, work closely with GPT to refactor your code 🙌

**Comment by HSRAKTU** [comment]
I'd like to start working on this right away

**Comment by rameshguditalu** [comment]
/assign
hey @jobenjada , need more details to generate the second preview

**Comment by kaif969** [comment]
![Screenshot 2024-10-18 010240](https://github.com/user-attachments/assets/fa9524e1-c5c2-4eb3-b429-de225e8ec431)

**Comment by Sayan650** [comment]
Where is the social post section I can't find it. Can anyone help me ?

**Comment by jobenjada** [comment]
closing for now, will look into it in the PR

**Comment by Khaan25** [comment]
Sure!
