### ISSUE TITLE
[FEATURE] Add user agent data to in-app responses

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#386]
**Is your feature request related to a problem? Please describe.**
I have no idea on which device my respondents reply to **in-app surveys**.

**Describe the solution you'd like**
Store and display the user agent along with the response.

**Tasks**
- Request userAgent when a survey is triggered via the Formbricks Widget. Write the userAgent data into the `meta` object in the response model (the meta object already exists in the Prisma schema)
- Type the meta object correctly with ZOD in packages/types/v1/responses
- Display the meta data in the response overview when hovering over the Avatar using the [Tooltip](https://ui.shadcn.com/docs/components/tooltip) in packages/ui. Make use of [UAParser.js](https://www.npmjs.com/package/ua-parser-js)

![grafik](https://github.com/formbricks/formbricks/assets/72809645/d863b3b0-6c0e-42e5-b00d-90eb5ece0d40)

## How to code for Formbricks
1. Make sure everything is type-safe
2. If you run `pnpm dev` you'll find a demo app to test in-app surveys at `localhost:3002`
3. When your code is done and working, paste it to chatGPT and ask for refactoring ideas. Apply what makes sense to you (GPT-4 is a lot better). Try out our new [Formbricks-Prompt](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) ✨

**Comment by G3root** [comment]
@jobenjada I'd like to work on this issue ?
