### ISSUE TITLE
[🕹️] Get all Vanta backgrounds as videos for animated background

### ISSUE THREAD

**Issue by Khaan25** [formbricks/formbricks#3867]
### What side quest or challenge are you solving?

Cloud Background Video for Formbricks forms

### Points

750 for a video

### Provide proof that you've completed the task

https://github.com/user-attachments/assets/4762bc3f-08ad-4ae7-8eff-2feddbf472f8

**Comment by jobenjada** [comment]
where did you get that from? I saw that before actually, I think it looks pretty cool!

**Comment by Khaan25** [comment]
Yes, it really looks cool. I thought I'll share it with you to add in the code, or create a new issue and assign to me 😄

I got this from https://www.vantajs.com/?effect=clouds2 (version 2)

Open source animation library

**Comment by karanghuge01** [comment]
> This is a submission of a different player for a side quest, you cannot get assigned to that.
> 
> If you also want to complete it, here is the [list of all side quests](https://oss.gg/side-quests)
> 
> If you want to make e.g. 1050 points in 5 minutes without touching code, do the [Starry-eyed Supporter quest](https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a?pvs=74)
> 
> As a reminder, this is how side quest submissions work:
> 
> 1. Complete the quest, gather proof (as described [here](https://formbricks.notion.site/How-to-submit-a-non-code-contributions-via-GitHub-81166e8c948841d18209ac4c60280e60?pvs=74)
> 2. Open a oss.gg submission issue in the respective repository
> 3. Wait for a maintainer to review, award points and close the issue
> 4. In the meanwhile, you can work on all other side quests 🚀
> 
> Thanks for playing 🕹️ OPEN SOURCE LETS GOOOO!

**Comment by jobenjada** [comment]
love it! /award 750

I'm happy to award you 750 more points if you take all of the animations they have and create a video out of them in a high resoltuion (like the clouds)

**Comment by Khaan25** [comment]
Sure, I'll add a google drive link with high quality animations.

**Comment by Khaan25** [comment]
Hey @jobenjada, Here's the drive link 😄

https://drive.google.com/drive/folders/1v7Bt8gY9rIX3_aXnQ26QbS8eOtnXZJW5?usp=sharing

It's all 30 seconds video and UHD.

Let me know.

**Comment by jobenjada** [comment]
/award 750

very cool! thanks a ton :)
