### ISSUE TITLE
[FEATURE] Store current respondent attributes with response

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#387]
**Is your feature request related to a problem? Please describe.**
In the analysis it will be possible to filter submissions based on user attributes. However, we currently do not store the **user attributes at the time of survey reponse. The problem: It's really important to store the current state of attributes for a good analysis (e.g. when a user was a free user before and now is a paid user, you want to know if a user was “free” or “paid” when sending a certain feedback)

**Describe the solution you'd like**
To prepare for the filtering we need to store the user attributes along with the response.

**Tasks**
Please note that this only applies to **in-app** responses created with the Formbricks Widget at the moment. The reason is, that we currently do not create a user when a survey is submitted via link.

1. Augment “Model Response” in the Prisma schema with a JSON field “Person Attributes” and store all attributes of the person as a key value pair. E.g. “Plan”, “free”
2. Make sure to update the types via ZOD packages/types/v1/responses
3. In the Response view, display the metadata on hover over the user avatar using the [Tooltip](https://ui.shadcn.com/docs/components/tooltip) in packages/ui:

![grafik](https://github.com/formbricks/formbricks/assets/72809645/6e937af3-36ba-4fa5-8482-67dbd17c1867)

## How to code for Formbricks
1. Make sure everything is type-safe
2. If you run `pnpm dev` you'll find a demo app to test in-app surveys at `localhost:3002`
3. When your code is done and working, paste it to chatGPT and ask for refactoring ideas. Apply what makes sense to you (GPT-4 is a lot better). Try out our new [Formbricks-Prompt](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) ✨

**Comment by Pradumn27** [comment]
Hey Johannes, I'd like to work on the issue can you please assign it to me.

**Comment by jobenjada** [comment]
You got it, have fun 🤸  :)
