### ISSUE TITLE
[🕹️] Follow formbricks on linkedin - side quest

### ISSUE THREAD

**Issue by techwizard31** [formbricks/formbricks#3871]
### What side quest or challenge are you solving?

I followed formbrick on linkedin

### Points

50

### Provide proof that you've completed the task

![Screenshot (48)](https://github.com/user-attachments/assets/0c431fbd-7eec-4b7c-a9fa-761153b16d37)

**Comment by 5AIPAVAN** [comment]
will these come under hacktober fest(will they get accepted)? just asking i am new to open source :-)

**Comment by techwizard31** [comment]
i think so, not sure

**Comment by jobenjada** [comment]
@5AIPAVAN I think hacktoberfest only awards merged PRs
