### ISSUE TITLE
[🕹️] San Francisco Billboard Ad -- side quest

### ISSUE THREAD

**Issue by techwizard31** [formbricks/formbricks#3872]
### What side quest or challenge are you solving?

San Francisco Billboard Ad 

### Points

300

### Provide proof that you've completed the task

![formbricks](https://github.com/user-attachments/assets/dcc1672f-4e6b-409c-ab93-e4c56755d38f)

**Comment by jobenjada** [comment]
hahaha well done! :D please post on twitter and tag us! or even better on LinkedIn!

/award 300
