### ISSUE TITLE
[🕹️]Follow dub on lindein

### ISSUE THREAD

**Issue by Vikgithuberit** [formbricks/formbricks#3874]
### What side quest or challenge are you solving?

Followed dub on linkdein

### Points

50

### Description

I had simply been in to the linkdein and search for dub and then followed it,

### Provide proof that you've completed the task

![Screenshot (411)](https://github.com/user-attachments/assets/37be308d-9e44-4110-95f4-793720d0d550)

**Comment by jobenjada** [comment]
wrong repo :)

**Comment by Vikgithuberit** [comment]
> wrong repo :)

h;ow
