### ISSUE TITLE
[🕹️] Formbricks Background 

### ISSUE THREAD

**Issue by techwizard31** [formbricks/formbricks#3876]
### What side quest or challenge are you solving?

Making a good background for surveys

### Points

300

### Provide proof that you've completed the task

![Screenshot (49)](https://github.com/user-attachments/assets/e2f7e07c-edc1-4092-9535-2691da2b2d36)

and the link of the image is -- https://media.istockphoto.com/photos/the-rabbit-picture-id1370481100?b=1&k=20&m=1370481100&s=170667a&w=0&h=LNu4ajpz7YBY2MnrzsXYKtGAMUlI3OV1hrzPBQOZQ_M=

**Comment by kanhaiyadav** [comment]
@techwizard31 does the issue say, the provided image has to be added as the background image for the surveys?

**Comment by jobenjada** [comment]
pls open a new issue if you still wanna submit something :)
