### ISSUE TITLE
[🕹️] Followed dub on linkdein

### ISSUE THREAD

**Issue by ShivaMahipal** [formbricks/formbricks#3877]
### What side quest or challenge are you solving?

Following dub on LinkedIn

### Points

50

### Description

I searched for the dub on LinkedIn and followed it!

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/2130652a-eb54-47f7-a139-02ea64969024)

**Comment by jobenjada** [comment]
wrong repo :)
