### ISSUE TITLE
[FEATURE] Add Active and Inactive Surveys to Attribute List

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#388]
## Update the UI for active and inactive surveys

**Is your feature request related to a problem? Please describe.**
As a user I cannot see in which surveys attributes are currently used or were used in the past.

**Describe the solution you'd like**
Display the correct information in the existing UI.

![grafik](https://github.com/formbricks/formbricks/assets/72809645/e3c57d7e-e195-4624-9ce1-d2f61dcb8db5)

**Tasks**

- The UI is there, but its not wired up.
- You can refer to the Actions tab, its working there 🤓

## How to code for Formbricks
1. Make sure everything is type-safe
2. If you run `pnpm dev` you'll find a demo app to test in-app surveys at `localhost:3002`
3. When your code is done and working, paste it to chatGPT and ask for refactoring ideas. Apply what makes sense to you (GPT-4 is a lot better). Try out our new [Formbricks-Prompt](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) ✨

**Comment by joe-shajan** [comment]
Can you assign this to me? @jobenjada
