### ISSUE TITLE
[🕹️] BRICK MEMING

### ISSUE THREAD

**Issue by shreykx** [formbricks/formbricks#3880]
### What side quest or challenge are you solving?

making a meme relating to a brick, posted it on X, tagged @formbricks

### Points

150

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/b91f78db-6456-4afb-a3bb-f8435d331429)
**[here](https://x.com/shreykx/status/1847301784706105537)**

**Comment by jobenjada** [comment]
do you need someone to talk to? :)

please make a meme about something funny :D
