### ISSUE TITLE
[🕹️] Design a background for form brick

### ISSUE THREAD

**Issue by thefool76** [formbricks/formbricks#3881]
### What side quest or challenge are you solving?

**Task**
- Find a cool image or graphic online
- Edit it so that it works well with the survey cards in the middle of the screen. Often it’s enough to just change the frame so that the key element is not centered (see dog or lollipop)
I have already submitted my background Image now I have made a animated one.

### Points

750

### Description

Here I have made this using Canvas Html and WebGL2 to generate perlin noise animation that can be used in form brick background below is my work. 

### Provide proof that you've completed the task

Video below
[Click here ](https://drive.google.com/file/d/165L9KICzc0YCwX0UVvZ6LNSqQB8qijHg/view?usp=sharing)

**Comment by thefool76** [comment]
copyright free. If need can share the code

**Comment by jobenjada** [comment]
this is sick! great work! 🔥

can you make two separate videos without the transition between the darkish one and the brightish one? so one video which is dark and one which is bright.

please also slow down the animation 50% if possible and export in a higher resolution.

thanks!

**Comment by thefool76** [comment]
> this is sick! great work! 🔥
> 
> can you make two separate videos without the transition between the darkish one and the brightish one? so one video which is dark and one which is bright.
> 
> please also slow down the animation 50% if possible and export in a higher resolution.
> 
> thanks!

Today I tried to separate the animation  but unfortunately the canvas output broke :( But I was able to slow down the animation a bit lower and for the recording actually I am using a 1001 to record it on Mac at 4k I have the file how some how if I share it on drive the resolution gets lower so should I zip and share it?

**Comment by jobenjada** [comment]
so you did not make it yourself? 🤓  i think than it wouldn't be a problem to remove the window fade. Or what am I missing?

**Comment by thefool76** [comment]
> so you did not make it yourself? 🤓  i think than it wouldn't be a problem to remove the window fade. Or what am I missing?

I got caught my bad I'll close this and let just animate it on Adobe after effects apologise 🙇
