### ISSUE TITLE
[🕹️] San Francisco Billboard Ad

### ISSUE THREAD

**Issue by Afridi-haque7** [formbricks/formbricks#3885]
### What side quest or challenge are you solving?

San Francisco Billboard Ad

### Points

300

### Provide proof that you've completed the task

![download](https://github.com/user-attachments/assets/03dea8a8-5001-4e7c-9465-94281c78a77e)
![outdoor-billboard-mockup](https://github.com/user-attachments/assets/b69dd5cf-5158-4dbf-844c-2abd6b0801b4)

**Comment by jobenjada** [comment]
hey! It'd need to say "building A better future" but I think its good enough :) /award 300 thanks!!
