### ISSUE TITLE
[🕹️] Side Quest Submission: Meme Magic

### ISSUE THREAD

**Issue by Afridi-haque7** [formbricks/formbricks#3888]
### What side quest or challenge are you solving?

Side Quest Submission: Meme Magic. Craft a meme where brick plays a role.

### Points

150

### Provide proof that you've completed the task

<img width="520" alt="image" src="https://github.com/user-attachments/assets/3fcd488c-785b-432f-9c82-aaeefb6fd8e1">

**Comment by jobenjada** [comment]
haha fair /award 150 :D
