### ISSUE TITLE
[BUG] fix styling of open text summary card  

### ISSUE THREAD

**Issue by gupta-piyush19** [formbricks/formbricks#3896]
### Issue Summary

Fix the styling of the open text summary card, it seems off maybe when a response has a very large text in it

### Steps to Reproduce

1. Create a survey with an open-text question in it
2. Fill it a few times with various length values
3. see the user name wraps in multiple lines

### Expected behavior

- table should look good, text shouldn't wrap(at least up to a certain width) 
- please don't use `white-space: nowrap` directly, either wrap the text if it reaches some width that you can test with different user names, or else add ellipsis.

### Screenshots

![image](https://github.com/user-attachments/assets/3c06643d-087a-4af6-bc75-b03efbd4eaeb)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by DeepaPrasanna** [comment]
Hey @gupta-piyush19 , it seems this has been fixed. Tried locally and the username text doesn't seems to wrap up.
https://www.loom.com/share/7751cb19e74e4ae0b8c774292705abb9?sid=1e0569ad-7465-44f8-83a5-6debae4897d0

**Comment by gupta-piyush19** [comment]
This bug is already fixed in some PR, thanks everyone for trying.
