### ISSUE TITLE
[🕹️]Side Quest Submission: Meme Magic and Gif Magic

### ISSUE THREAD

**Issue by Naprila** [formbricks/formbricks#3897]
### What side quest or challenge are you solving?

Meme Magic and Gif Magic

### Points

150 + 150

### Description

Created a meme and a gif about Formbrick

### Provide proof that you've completed the task

<img width="1369" alt="Screenshot 2024-10-19 at 1 55 20 PM" src="https://github.com/user-attachments/assets/8a202418-5be6-4656-9f80-832cbc604365">

https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExazM4MGRmZWh5YWZqbzg2NjA0YnVqZXAzNXJ2b2xmMWVucW11ZWU3dyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/QCmTthWjFnR3pE6lqT/giphy.gif

**Comment by Anonymous-RD** [comment]
interesting what are we doing in this issue exactly can someone explain

**Comment by jobenjada** [comment]
/award 300

@Anonymous-RD all side quests on oss.gg/side-quests
