### ISSUE TITLE
Send confirmation email to respondent

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#39]
### Confirmation emails to respondents

As a user, I want to send my respondents an email after they completed the form. I want to change the content of the confirmation. Ideally, I can update the layout so it fits my corporate design.

This only applies when the form has an email field.

**Comment by eprovst** [comment]
Could it be that this feature was removed since then? Or did I wholly overlook this option or another (still open) feature request?

If not, I'd like to reopen this feature request :slightly_smiling_face:

**Comment by ASpelt89** [comment]
Is there an update on this request? I would love to have this as well!
