### ISSUE TITLE
[🕹️]Starry-eyed Supporter (150 Points)

### ISSUE THREAD

**Issue by tejaslakade99** [formbricks/formbricks#3900]
### What side quest or challenge are you solving?

Starry-eyed Supporter (150 Points)

### Points

150

### Description

Completed the task

### Provide proof that you've completed the task

![Ankit-git](https://github.com/user-attachments/assets/18b64dbb-756b-4221-a619-fb759560635f)
![Screenshot 2024-10-17 at 3 46 52 PM](https://github.com/user-attachments/assets/1d05a175-2486-4e25-9437-5be473abc52f)
![Screenshot 2024-10-17 at 3 52 52 PM](https://github.com/user-attachments/assets/8ff68d6f-71d1-4417-99f0-84dfb19b3525)
![Pratik-Git](https://github.com/user-attachments/assets/fe2c92d6-7bbf-4e3e-a636-1191782bfac7)
![Shantanu-git](https://github.com/user-attachments/assets/fcac218b-63e7-4a9c-a4ee-bbc60d6c80e7)

**Comment by jobenjada** [comment]
very cool, thanks for spreading the word! /award 150
