### ISSUE TITLE
[🕹️]San Francisco Billboard Ad (300 Points)

### ISSUE THREAD

**Issue by tejaslakade99** [formbricks/formbricks#3901]
### What side quest or challenge are you solving?

San Francisco Billboard Ad (300 Points)

### Points

300

### Description

Completed the task

### Provide proof that you've completed the task

# Billboard
![1](https://github.com/user-attachments/assets/03854239-e582-4d9e-b6c1-66f549d2ca71)

![Untitled design-2](https://github.com/user-attachments/assets/607192ac-b04c-45d2-81b0-d36f4ec28637)

**Comment by jobenjada** [comment]
thats cool! :) /award 300 thanks a lot!
