### ISSUE TITLE
[🕹️]Meme Magic (150 Points), Gif Magic (150 Points) and Brickify someone famous with AI (150 Points):

### ISSUE THREAD

**Issue by tejaslakade99** [formbricks/formbricks#3903]
### What side quest or challenge are you solving?

Meme Magic (150 Points), Gif Magic (150 Points) and Brickify someone famous with AI (150 Points)

### Points

150+150+150 = 450 

### Description

Created meme,gif and brickified harry potter

### Provide proof that you've completed the task

# Meme:
![supermeme_15h45_20](https://github.com/user-attachments/assets/e26ad12a-d5aa-495a-a4c5-b01e7538ac0e)
# Giffy:
![supermeme_15h46_58](https://github.com/user-attachments/assets/feed769f-2e59-4bb3-9646-5763dc5f79e4)
# Brickfy: Harry Potter
![c550a5a5804ec081078e2319996b584f-2](https://github.com/user-attachments/assets/09bdb086-db9f-4559-8ff4-d14e263420ab)

**Comment by jobenjada** [comment]
hey :) /award 150 for harry potter!

the other two are anti ads 😬
