### ISSUE TITLE
[BUG] Calendar dates not centred upon hovering on them

### ISSUE THREAD

**Issue by Yarlord** [formbricks/formbricks#3906]
### Issue Summary

UI issue. Upon selecting New Survey and selecting Release Survey on date, the Pick a date option does not have centered selection upon hovering on dates. 

### Steps to Reproduce

1. Added a product. 
2. Went to Surveys option in Web.  
3. Clicked on New survey.
4. Selected "Start from scratch".
5. Went to settings tab.
6. Selected release survey on date, hovered over a date. 
7.  Observed that the element was not centered.

### Expected behavior

The element must be centered when hovered over. 

### Screenshots

![image](https://github.com/user-attachments/assets/b1308c6e-bf38-4f9c-8479-1bfd7e39f5d9)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Linux
- Node:v20.17.0
- npm: 10.8.2
```

**Comment by jobenjada** [comment]
yeah this is a known one, idk why no one is able to fix it properly :D

**Comment by SaiSawant1** [comment]
@jobenjada ,
#3382 I opened this PR about a week ago. No one reviewed it yet. Fixed the date picker and was looking for feedback if any.
Please look into it.
