### ISSUE TITLE
[🕹️] Formbricks GIF

### ISSUE THREAD

**Issue by shreykx** [formbricks/formbricks#3907]
### What side quest or challenge are you solving?

![image](https://github.com/user-attachments/assets/dcac79b1-f4f7-402e-9b36-d588111e65ae)

### Points

150

### Provide proof that you've completed the task

**Link to [giphy](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExb3Exbm03czJtbmRobnNhcmR3MDgzdGVmOGRpNzRyc3oyMTlxYWdxZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/2yPXCU84HWygDNPcfj/giphy-downsized-large.gif).**

**Comment by jobenjada** [comment]
/award 150 even though I dont think it makes sense 🫠
