### ISSUE TITLE
[FEATURE] Display survey on generic actions

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#391]
## Name: Display on generic actions

**Is your feature request related to a problem? Please describe.**
As a user I have to set up specific user actions to be able to trigger a survey. This is quite a hurdle which lowers user activation.

**Describe the solution you'd like**
As a user I want to trigger surveys on generic user actions:

- Scroll depth and
- Exit intent (on desktop)

**Tasks**

Part 1:

These triggers are listened to in the JS Widget at packages/js. Add two new listeners to the widget:

1. Exit intent
2. Scroll depth. You can set a default of 50%, down the line we will allow users to set a custom scroll depth in %.

Part 2: 

When a Product gets created, the Actions and Attribtues are created with it. In the same way we have Automatic Attributes (email and userID) we will create Automatic Actions on Product Creation. Currently, a Product is created on three occasions:

1. Add new team → adds new product
2. Google + GitHub Auth → adds new product
3. Create user (Email) → adds new product

Add two Automatic Actions in the Product Creation:

1. **Exit Intent**
Description: A user on Desktop leaves the website with the cursor.
2. 50% Scroll
Description: A user scrolled 50% of the current page

Part 3: Test it 😊

## How to code for Formbricks
1. Make sure everything is type-safe
2. If you run `pnpm dev` you'll find a demo app to test in-app surveys at `localhost:3002`
3. When your code is done and working, paste it to chatGPT and ask for refactoring ideas. Apply what makes sense to you (GPT-4 is a lot better). Try out our new [Formbricks-Prompt](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) ✨

**Comment by Ashutosh-Bhadauriya** [comment]
@jobenjada can you please assign this issue to me
