### ISSUE TITLE
[🕹️] Accessibility Advocate

### ISSUE THREAD

**Issue by rajeevDewangan** [formbricks/formbricks#3910]
### What side quest or challenge are you solving?

Accessibility Advocate

### Points

50 - 300 Points dependent what you found

### Description

While giving the survey the border of form is not visible with my white background
It should be darker so that the form can be more visible
while making the form its real good but while giving the survey it clutches my ocd 😬

### Provide proof that you've completed the task

![Screenshot 2024-10-19 191945](https://github.com/user-attachments/assets/9c019f55-5983-480a-8c72-04d78aec3021)

**Comment by jobenjada** [comment]
thats a feature, not a bug. Some people dont want the card :)
