### ISSUE TITLE
[🕹️] Follow Formbricks LinkedIn Page (50 Points)

### ISSUE THREAD

**Issue by ahemadrazak11** [formbricks/formbricks#3911]
### What side quest or challenge are you solving?

What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page Completed

### Points

50

### Description

I have followed the **Formbricks Page** https://linkedin.com/company/formbricks Page through the profile (https://www.linkedin.com/in/ahemad-raza-khan/)

### Provide proof that you've completed the task

![linkedIn](https://github.com/user-attachments/assets/1853fa49-8f33-4494-a48b-6efad15ff276)

**Comment by shivamkumarsingh28** [comment]
I have followed the Formbricks Page [formbricks](https://www.linkedin.com/company/formbricks/) through my profile [shviamsaeeam](https://www.linkedin.com/in/shivamsaeeam/)
![Screenshot 2024-10-19 204352](https://github.com/user-attachments/assets/16ca68b7-c954-46a7-9b03-abf3caa7b80a)



i do this task #3911
