### ISSUE TITLE
[🕹️]San Francisco Billboard Ad

### ISSUE THREAD

**Issue by ArSenic04** [formbricks/formbricks#3915]
### What side quest or challenge are you solving?

San Francisco Billboard Ad

### Points

300

### Description

Completed the task

### Provide proof that you've completed the task

![378069528-03854239-e582-4d9e-b6c1-66f549d2ca71](https://github.com/user-attachments/assets/ec8cab06-530f-4746-a2b8-733377d753c4)
![378069547-607192ac-b04c-45d2-81b0-d36f4ec28637](https://github.com/user-attachments/assets/1e29df9f-78ae-4faa-971c-d2a524d46b39)

**Comment by jobenjada** [comment]
someone else submitted this as well 🤔 pls provide proof that you created this

**Comment by Shashankk99** [comment]
That was an error, this was not submitted by me.

**Comment by jobenjada** [comment]
@Shashankk99 who are you now? :)

**Comment by Shashankk99** [comment]
@jobenjada I joined in as a contributor. Kindly ignore the above action. Thanks!
