### ISSUE TITLE
[🕹️] Starry-eyed Supporter

### ISSUE THREAD

**Issue by aritradevelops** [formbricks/formbricks#3917]
### What side quest or challenge are you solving?

Starry-eyed Supporter

### Points

150

### Description

# Profiles
1. https://github.com/finallyRaunak/
2. https://github.com/arijit192/
3. https://github.com/suparnacodes/
4. https://github.com/Biprodipnh/
5. https://github.com/Reyden49q1/

### Provide proof that you've completed the task

# Screenshots that they confirmed

<img width="630" alt="Screenshot 2024-10-17 at 9 44 56 PM" src="https://github.com/user-attachments/assets/1cc27c79-ec38-4788-b7da-4f250a8efd24">
<img width="924" alt="Screenshot 2024-10-17 at 9 46 23 PM" src="https://github.com/user-attachments/assets/7584c121-8e23-4c84-b000-1b2e1f980f16">
<img width="939" alt="Screenshot 2024-10-17 at 9 52 13 PM" src="https://github.com/user-attachments/assets/8739b44c-8946-4a7d-89b2-79da2eec24c4">
<img width="949" alt="Screenshot 2024-10-17 at 9 54 09 PM" src="https://github.com/user-attachments/assets/2df689ee-4c33-444f-9add-36b13120c33b">
<img width="924" alt="Screenshot 2024-10-17 at 9 55 36 PM" src="https://github.com/user-attachments/assets/4728b12e-0418-4023-b77e-e3ac9baf5787">

# Proof (Screenshots from their end)

<img width="1428" alt="image_2024_10_13T10_28_50_072Z" src="https://github.com/user-attachments/assets/b97e3d37-ed3a-407a-b594-ac9d4b54761c">
<img width="1429" alt="Screenshot 2024-10-11 at 4 29 20 PM" src="https://github.com/user-attachments/assets/a3a8a5eb-d267-487c-b28e-284198705146">

![2](https://github.com/user-attachments/assets/52957ca9-c6e0-47e5-a1bc-596e2c0e758e)
![3](https://github.com/user-attachments/assets/6ac4160a-1dcf-4b4f-9d45-ce4742e75da8)
![1](https://github.com/user-attachments/assets/8df7b56e-9199-4a3d-b34f-6ebe16192980)

**Comment by jobenjada** [comment]
legend, thanks! :) /award 150
