### ISSUE TITLE
[🕹️]Design a background

### ISSUE THREAD

**Issue by Sam-at-code** [formbricks/formbricks#3918]
### What side quest or challenge are you solving?

Design a background

### Points

300-750

### Description

Handcrafted The Background. Do give feedback

Link : https://www.canva.com/design/DAGUBbnbyjk/0vR0ZER308jbBC6_wisy8w/edit?utm_content=DAGUBbnbyjk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

### Provide proof that you've completed the task

![Screenshot 2024-10-19 225829](https://github.com/user-attachments/assets/253e830f-e562-4f2e-89c5-1b418588b3d3)
![Untitled design (3)](https://github.com/user-attachments/assets/f342f2ca-f007-465a-9d97-9f840d5b495c)

**Comment by jobenjada** [comment]
naahh man, cant offer that to our users :D

**Comment by Sam-at-code** [comment]
Ok will do another one
