### ISSUE TITLE
[🕹️] Meme Magic

### ISSUE THREAD

**Issue by Sa1-Codes** [formbricks/formbricks#3919]
### What side quest or challenge are you solving?

Craft a meme where a brick plays a role. Tweet it, and tag us @formbricks to submit.

### Points

150

### Description

crafted a meme where brick plays a role, tweeted it and tagged formbricks.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/acfde835-a33b-4212-b14d-4f55a804123b)

**Comment by imAkshayDarji** [comment]
@Sa1-Codes I have tweet the meme where a bricks play role on X. Here is the proof you can see:

![image](https://github.com/user-attachments/assets/7858b9ee-810a-4af6-a66b-9f73285e65a5)

**Comment by jobenjada** [comment]
ooooooh haha fire!!! we should definitely make that a thing :D 

/award 200 cause its extra good!
