### ISSUE TITLE
[🕹️] Gif Magic

### ISSUE THREAD

**Issue by sateshcharan** [formbricks/formbricks#3926]
### What side quest or challenge are you solving?

Gif Magic

### Points

150

### Description

https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZDZ1NXg4N2tnMTU5bGhxbDE3ZTQxcGlkN3NlYmk4eWR2enI1dTE0YiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/iyncZf02MTeBPe3bjN/giphy.gif

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/a4167896-2c49-4209-9d15-703ddfda2270)

**Comment by jobenjada** [comment]
/award 150 thats how it usually is :P
