### ISSUE TITLE
[🕹️] Starry-eyed Supporter

### ISSUE THREAD

**Issue by sateshcharan** [formbricks/formbricks#3927]
### What side quest or challenge are you solving?

Starry-eyed Supporter

### Points

150

### Description

Starry-eyed Supporter Completed

### Provide proof that you've completed the task

![stary eye 1](https://github.com/user-attachments/assets/d2a8f9b5-c232-44a1-a3ce-297c51afb7b3)
![stary eye 2](https://github.com/user-attachments/assets/05711cd8-9c31-4506-96ca-e7ba866be3f4)
![stary eye 3](https://github.com/user-attachments/assets/be30833b-838d-463d-ab1d-f84082dddb03)
![stary eye 4](https://github.com/user-attachments/assets/7d7bf65a-2188-4aee-8d7d-c5dda69f60c6)
![stary eye 5](https://github.com/user-attachments/assets/ed010618-6a5e-4c9d-aeb9-2c21be560f98)

**Comment by preeti13456** [comment]
Completed the task Username : Preeti13456

![Screenshot (5)](https://github.com/user-attachments/assets/67df3a7d-fb54-4f96-af78-c45681c533d8)
![Screenshot (6)](https://github.com/user-attachments/assets/526095f3-d4db-41b6-85cc-e8f59ce7e76a)
![Screenshot (7)](https://github.com/user-attachments/assets/a723c4aa-bddd-4f9f-85d0-aaf377accb04)

**Comment by preeti13456** [comment]
Sorry for noticing it later here's the URL for twitter post 
https://x.com/Leovarmak1/status/1848289160551121022
