### ISSUE TITLE
[🕹️] San Francisco Billboard Ad

### ISSUE THREAD

**Issue by sateshcharan** [formbricks/formbricks#3929]
### What side quest or challenge are you solving?

San Francisco Billboard Ad

### Points

300

### Description

San Francisco Billboard Ad

### Provide proof that you've completed the task

![billboard-formblocks](https://github.com/user-attachments/assets/60a38a7e-b440-4bfc-873b-e4089e3f621c)

**Comment by preeti13456** [comment]
In which file it needs to be contributed nd do we have to create to create a sample billboard app for Formbrick

**Comment by sateshcharan** [comment]
@preeti13456  https://formbricks.notion.site/Formbricks-Hacktoberfest-Side-Quests-Challenges-798855c705cc4474ba63ceefbe048abf

**Comment by jobenjada** [comment]
pls post it on Twitter, its part of the challenge, isn't it?

**Comment by sateshcharan** [comment]
> pls post it on Twitter, its part of the challenge, isn't it?

I apologize for not noticing earlier, but I've posted it here: https://x.com/sateshcharans/status/1848204388952596768 Would it be possible to receive the remaining 150 points? Thank you for your understanding!
