### ISSUE TITLE
[🕹️] Follow formbricks on linkedin

### ISSUE THREAD

**Issue by r0x5r** [formbricks/formbricks#3932]
### What side quest or challenge are you solving?

Follow formbricks on linkedin

### Points

50 points

### Description

Followed formbricks on linkedin

### Provide proof that you've completed the task

Provide proof that you've completed the task
![image](https://github.com/user-attachments/assets/78f5f2ce-1fb6-4f1c-beb8-0615dca93fd8)

**Comment by Afza-Khursheed123** [comment]
What side quest or challenge are you solving?
Follow formbricks on linkedin

Points
50 points

Description
Successfully Followed formbricks on linkedin


Provide proof that you've completed the task
![Screenshot 2024-10-21 002028](https://github.com/user-attachments/assets/8c36e3a4-31e8-4a21-aaf8-bcbe5bf63717)
