### ISSUE TITLE
[BUG] No Error Shown When User Enters Incorrect 2FA Code

### ISSUE THREAD

**Issue by r0x5r** [formbricks/formbricks#3933]
### Issue Summary

When a user enters an incorrect 2FA code, the frontend does not display any error message. The error is only visible in the developer console. This causes confusion for the user, as they are not informed that their 2FA code is invalid.

### Steps to Reproduce

1:- go to account 
2:- on two factor authentication 
3:-enter password  and click on confirm
4:- click on next 
5:- Enter an incorrect 2FA code.
6:- click on confirm 

### Expected behavior

An error message should be displayed on the frontend, informing the user that the 2FA code is incorrect.

### Other information

Display a clear error message on the frontend when an incorrect 2FA code is entered, like “Invalid 2FA code. Please try again.”

### Screenshots

![image](https://github.com/user-attachments/assets/bdefaec1-5ef0-4deb-b759-1a22061df4ba)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by BreakTos** [comment]
Please assign this to me ?

**Comment by jobenjada** [comment]
/award 150 thanks for flagging this :)
