### ISSUE TITLE
[🕹️] Formbricks Side Quests

### ISSUE THREAD

**Issue by adilkadivala** [formbricks/formbricks#3942]
### What side quest or challenge are you solving?

The Formbricks quest not only supports the community but also teaches us how to become valuable contributors, even for those without coding experience.

### Points

Draft a billboard add:- 300
Meme:-150
Gif:-150
LinkedIn(Social):-50
Brickify famous personality:-150
Spread the word(Youtube/X/LinkedIn):-150

### Description

linkedin profile
https://www.linkedin.com/in/adilkadival/

### Provide proof that you've completed the task

**Billboard**

![billboardformbricks](https://github.com/user-attachments/assets/9972abe4-a5be-4889-b167-caf65e0de565)

**Meme + taged on x**

https://x.com/adil_kadival/status/1848234656677921275

![formbricks meme](https://github.com/user-attachments/assets/a4038fb9-3f69-4003-b01e-821fc331092c)

**gif with giphy link**

https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExeWtxdmxqZTR6d3ZwbHhuYjQwNDE3NG8zbDBib3QydmNnaHFyMzZjbyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/laLv9kbkZuvqG8TPcV/giphy.gif

![formbricks-gif](https://github.com/user-attachments/assets/6fd18817-b5f3-4c9f-af33-846f9fd4d37d)

**linkedin**

![formbrickslinkedin](https://github.com/user-attachments/assets/bf71dcb2-7a3e-46e6-810c-c5ab442562e9)

**Brickify suresh raina**

![avatar](https://github.com/user-attachments/assets/66b4fd4e-9915-494a-a11b-b5d16c4d2785)

**Spread the word**

![yt4](https://github.com/user-attachments/assets/9cfc6222-808a-474f-8b32-1e1878bd99c7)

![yt1](https://github.com/user-attachments/assets/a7163b03-e42a-4daf-a775-11e7748e9ae9)

![yt2](https://github.com/user-attachments/assets/170758df-1b1d-4cf7-b85f-6f8d451e026e)

![yt3](https://github.com/user-attachments/assets/484f5192-2a1b-4a4b-af27-6540bc0e4ac4)

![yt5](https://github.com/user-attachments/assets/8b04c351-cebe-411b-b4c1-cf7853932d76)

**Comment by jobenjada** [comment]
/award 800 

no points for the meme cause thats not a meme :)
