### ISSUE TITLE
[BUG] Reported 4 Security Issues in the Last Few Days

### ISSUE THREAD

**Issue by r0x5r** [formbricks/formbricks#3945]
### Issue Summary

I have reported 4 security issues in the last few days related to the Formbricks project.

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
Thanks for opening the issue. @jobenjada will award you 600 points for that (150 points for each security report) :-)
