### ISSUE TITLE
[🕹️] Bug Hunter 

### ISSUE THREAD

**Issue by Kritikaadhikarii** [formbricks/formbricks#3946]
### What side quest or challenge are you solving?

[🕹️] Bug Hunter 

### Points

(50 - 150 Points for every bug)

### Description

https://formbricks.notion.site/How-to-make-1050-points-without-touching-code-in-5-minutes-e71e624b5b9b487bbac28030d142438a

When you go this website, and this section:
![image](https://github.com/user-attachments/assets/05c2902f-6b11-4abb-bcdd-b81e5b16198d)

When you click the repo link of unkey, the above message is shown, which means that there's some mistake in the link.
![image](https://github.com/user-attachments/assets/ec1c14e7-7c90-41d3-a5c0-b284cdde82be)

### Provide proof that you've completed the task

Please read the description for details.

**Comment by jobenjada** [comment]
thats not a really a bug. we only accept bug submission around our core product :)
