### ISSUE TITLE
docs: [🕹️] Enhance Docs (50-300 Points) 

### ISSUE THREAD

**Issue by sateshcharan** [formbricks/formbricks#3949]
### What side quest or challenge are you solving?

Enhance Docs

### Points

50-300

### Description

have enhanced local setup docs at #3941

### Provide proof that you've completed the task

 apps/docs/app/developer-docs/contributing/get-started/page.mdx 
 at  #3941

**Comment by ezDecode** [comment]
Can I start working on it??

**Comment by sateshcharan** [comment]
@ezDecode this issue refers to a pr which is my oss submission, please find a different issue to work on, thanks for understanding.

**Comment by jobenjada** [comment]
merged, thanks :)
