### ISSUE TITLE
[BUG] [🕹️] Bug Hunter (50 - 150 Points for every bug)

### ISSUE THREAD

**Issue by sateshcharan** [formbricks/formbricks#3950]
### Issue Summary

The local development setup crashes if the Docker Compose plugin is not installed when using "pnpm go".

### Steps to Reproduce

1. only with docker-compose(no docker compose plugin) installed from root folder run "pnpm go"
2. It fails if the Docker Compose plugin is not present.

### Expected behavior

dev environment should be setup successfully 

### Other information

Suggested fix:
Implement a fallback in the code using docker compose || docker-compose to ensure compatibility with both versions.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: wsl2 ubuntu / win10
- Node: v20.18.0
- npm: v10.8.2
- Browser: Brave
```

**Comment by jobenjada** [comment]
are you sure this is a bug? i dont think I have the plugin installed. Any proof?

**Comment by sateshcharan** [comment]
https://github.com/user-attachments/assets/8c036319-5873-44cc-9f36-6da72d3d0d8e

@jobenjada pfa video for reference

**Comment by jobenjada** [comment]
It's not a bug but the different version of docker compose has different APIs, previously it was docker-compose, now it's docker compose . We can support running the old command || new command but the old one is already deprecated.
