### ISSUE TITLE
[🕹️] Quest Wizard

### ISSUE THREAD

**Issue by sateshcharan** [formbricks/formbricks#3951]
### What side quest or challenge are you solving?

Quest Wizard

### Points

300

### Description

Completed all Formbricks side quests

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/0d0dbc59-4074-49df-aed4-515c2697d6d9)
![image](https://github.com/user-attachments/assets/ef4b31e8-8e64-4a65-a01e-dee1f456170c)
![image](https://github.com/user-attachments/assets/5f30f17b-1203-4634-bb84-432444fd4062)

**Comment by jobenjada** [comment]
legend!!! /award 400

got 100 points extra for being the first ;)
