### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page 

### ISSUE THREAD

**Issue by sahiladit** [formbricks/formbricks#3953]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn Page

### Points

50

### Provide proof that you've completed the task

<img width="1440" alt="Screenshot 2024-10-21 at 5 43 39 PM" src="https://github.com/user-attachments/assets/6dcffdf8-80f0-4beb-840f-0b2a82be7968">

**Comment by HKMANOJ** [comment]
Hi following your page on Linkedin
<img width="1440" alt="Screenshot 2024-10-21 at 5 49 02 PM" src="https://github.com/user-attachments/assets/ee30d8d7-e7ea-4163-ac42-fc571c4fc866">

**Comment by AranavMahalpure** [comment]
I am following Formbricks On LinkedIn 
![image](https://github.com/user-attachments/assets/a64e219a-60cb-4648-83d3-65cf14b9aeba)
