### ISSUE TITLE
[FEATURE] As a user I want to tag responses and filter by tag

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#396]
**Is your feature request related to a problem? Please describe.**
When you receive a lot of submissions the response list can get messy and getting an overview is difficult.

**Describe the solution you'd like**
Allow tagging and filtering by tag.

**Note**
We built tagging for a previous iteration of Formbricks. However, since then a few things have changed:
- We switched Tailwind Headless UI with [shadcn interpretation of Radix.](https://ui.shadcn.com)
- We added a few more data layers.
- Tags should be connected with **Products** so that teams can use the same tags on prod and dev environments.

This is the [Tagging.tsx](https://github.com/formbricks/formbricks/blob/c13547af1adda99a622b1882480b18dfe72d5635/apps/web/src/components/forms/shared/Tagging.tsx), this is a [file where we used it](https://github.com/formbricks/formbricks/blob/c13547af1adda99a622b1882480b18dfe72d5635/apps/web/src/components/forms/pmf/PMFTimeline.tsx), here is how we [filtered by tags](https://github.com/formbricks/formbricks/blob/c13547af1adda99a622b1882480b18dfe72d5635/apps/web/src/components/forms/shared/FilterNavigation.tsx) and this is [the overall commit](https://github.com/formbricks/formbricks/tree/c13547af1adda99a622b1882480b18dfe72d5635) in case you'd like to spin it up and see how it worked.

**Tasks**
1. Review the tagging and filter by tag functionality linked above
2. Previously, tags were an array of strings in the Response model. Decide if its better to add a model Tag to be able to edit and merge tags (see below)
3. Decide to use the [shadcn combobox ](https://ui.shadcn.com/docs/components/combobox)or this [fancy box](https://craft.mxkaske.dev/post/fancy-box) to build a tagging UX similar to this:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/51de5119-9777-4bd7-93c6-6c6bfbecaeec)
4. You're free to make the look & feel match our UI. It's not super essential so no need to get lost in details :)
5. In terms of functionality, refer to [this demo](https://demo.delighted.com/dashboard)
- Allow typing for a tag and filter the selection in the dropdown based on the typed string. On ENTER, if a tag is selected, select it.
- If you hit enter and no tag is selected in the dropdown, create a new one
6. Add a "Tags" page to manage tags in the Settings under Team -> Tags with a list of tags which contains:
- The tags name with an editable input field which auto updates (we have this functionality in the SurveyEditor.tsx for the survey name). When the name change was saved, show a toast.
- A count how often this tag was assigned.
- A delete button. Add toasts on success and err.
- A merge button: You can merge two tags together. The merge UI allows users to select a second tag and then the tag that was selected is merged into the first tag where the user hit the "Merge" button. You could wrap the Fancy or Combobox in a Tooltip which opens on "Merge" click to select the second tag. Make sure to add toasts.
7. Add a little settings icon on the right hand side at the bottom of the response card which links to the Tags settings page.

**Comment by pandeymangg** [comment]
@jobenjada Could you please assign this to me
