### ISSUE TITLE
[🕹️] San Francisco Billboard Ad

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#3965]
### What side quest or challenge are you solving?

San Francisco Billboard Ad

### Points

300

### Provide proof that you've completed the task

![2-ratio-1-outdoor-billboard-mockup-template-6716cf6db8773f8d4aed3124-@2x](https://github.com/user-attachments/assets/9aac09b5-28a9-4978-9aeb-d7bbc97f6b0d)

**Comment by jobenjada** [comment]
showing the product, nice touch! 

/award 300
