### ISSUE TITLE
[🕹️]Article: How to use Formbricks with Webflow 

### ISSUE THREAD

**Issue by mohitjoping** [formbricks/formbricks#3967]
### What side quest or challenge are you solving?

Its an Article: How to use Formbricks with Webflow.

### Points

1500 Points.

### Description

I wrote an article on How to use Formbricks with Webflow.

### Provide proof that you've completed the task

[ Formbricks ](https://formbricks.com/blog/How-to-use-formbricks-with-webflow)
[ dev.to ](https://dev.to/mohitjoping/embed-formbricks-forms-in-webflow-in-minutes-no-code-just-magic-5cik)

**Comment by jobenjada** [comment]
/award 1500 

thanks a lot! :)
