### ISSUE TITLE
[🕹️]Retweeted and Like Side Quest

### ISSUE THREAD

**Issue by piyusdev2006** [formbricks/formbricks#3968]
### What side quest or challenge are you solving?

- Follow the twitter page of @dubinc/dub
  
![Screenshot 2024-10-22 084308](https://github.com/user-attachments/assets/91fcef46-1beb-4599-848a-2a0e4efa2954)

- Follow the Linkedin page of @dubinc/dub

![Screenshot 2024-10-22 085936](https://github.com/user-attachments/assets/c7365cba-7e85-4346-9500-4670a3cd77c6)

### Points

- 50

### Provide proof that you've completed the task

- Twitter page

![Screenshot 2024-10-22 090544](https://github.com/user-attachments/assets/87e2c43a-a2fb-4ff0-bde3-ea67e6dbc7d9)

- Linkedin page 

![Screenshot 2024-10-22 090611](https://github.com/user-attachments/assets/25769ee4-6820-44af-8af8-a3743e3c65b7)

**Comment by jobenjada** [comment]
youll get /award 50 for sharing the tweet, the rest you have to submit in the dub repo
