### ISSUE TITLE
[🕹️] follow on X and Brickify famous personality and youtube and spread the words

### ISSUE THREAD

**Issue by AshishViradiya153** [formbricks/formbricks#3969]
### What side quest or challenge are you solving?

Ashish Viradiya

total Points: 450

150points
https://x.com/Ashish129570796/status/1848576856326390056
<img width="606" alt="Screenshot 2024-10-22 at 9 38 23 AM" src="https://github.com/user-attachments/assets/a15d0ffb-7bf3-458d-b9af-c8a4c41a0fa0">

100points
<img width="606" alt="Screenshot 2024-10-22 at 9 38 46 AM" src="https://github.com/user-attachments/assets/f926dfa2-17f5-4650-8b61-4a5970138e55">
<img width="1216" alt="Screenshot 2024-10-22 at 9 40 10 AM" src="https://github.com/user-attachments/assets/14ba9427-8842-48fc-9a36-0192fc5af29a">

150 points
<img width="909" alt="Screenshot 2024-10-22 at 10 11 22 AM" src="https://github.com/user-attachments/assets/6a89eced-f642-4960-8ffa-7412febd36b9">
<img width="667" alt="Screenshot 2024-10-22 at 10 14 01 AM" src="https://github.com/user-attachments/assets/ed1d1261-d1e5-4be1-a35e-9e5a008d0437">
<img width="667" alt="Screenshot 2024-10-22 at 10 17 31 AM" src="https://github.com/user-attachments/assets/4ad4e6b9-d3f4-4290-ab86-dd92b17ba7a8">

Like & [Re-Tweet oss.gg Launch Tweet ](50 Points)
<img width="534" alt="Screenshot 2024-10-22 at 10 21 37 AM" src="https://github.com/user-attachments/assets/63a660d5-283a-4132-a0aa-e74cb3e93aeb">

### Points

?

### Provide proof that you've completed the task

screenShort

**Comment by jobenjada** [comment]
Following Formbricks Twitter wasn't a side quest, you listed 100 points here for you.

**Comment by DeepaPrasanna** [comment]
> Following Formbricks Twitter wasn't a side quest, you listed 100 points here for you.

He worked on my assigned issue without notifying me (my 48 hour limit was not over too) and gained points. :)

**Comment by jobenjada** [comment]
he is disqualified
