### ISSUE TITLE
[FEATURE] Redirect on link survey completion

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#397]
**Is your feature request related to a problem? Please describe.**
As a user I want to redirect users from a link survey after completion.

**Tasks**
1. Build UI to allow users to toggle "Redirect on completion" and added a URL in an input field into ResponseOptions.tsx - only display if Survey Type === "link"
2. Build logic into "LinkSurvey.tsx"
3. Test

**Comment by Dhruwang** [comment]
would like to work on this !

**Comment by jobenjada** [comment]
thanks a lot mate! 🙌
