### ISSUE TITLE
[🕹️] Design a background

### ISSUE THREAD

**Issue by Khaan25** [formbricks/formbricks#3970]
### What side quest or challenge are you solving?

Design a background

### Points

300 - 750

### Description

I've webp format as well, I'll email you

I crafted this image carefully so that we've cloud themed image, center area is kinda empty because that's where the form is gonna be and these soft round clouds give a nice vibe. It may be usefull for some surveys :)

### Provide proof that you've completed the task

![cloud image](https://github.com/user-attachments/assets/00ef062c-5895-4c1e-929a-b92d5bb432e7)

Preview:
![image](https://github.com/user-attachments/assets/d23c94a3-b843-43e3-82ed-f3ad752c896e)

**Comment by jobenjada** [comment]
love it, very cool!  /award 300

Can you open a PR where you add this to the list for an additional 150 points? make sure its high resolution but .webp

**Comment by Khaan25** [comment]
Sure, I'll link the PR to this issue.

**Comment by Khaan25** [comment]
@jobenjada Where do I add to the list? :)

**Comment by Khaan25** [comment]
@jobenjada :)
