### ISSUE TITLE
[🕹️]San Francisco Billboard side quest + meme (0 points)

### ISSUE THREAD

**Issue by AshishViradiya153** [formbricks/formbricks#3972]
### What side quest or challenge are you solving?

Total points: 450

Creating a SF Bill Board for Formbricks and MEME on x

points : 300
![image](https://github.com/user-attachments/assets/e5590ead-d983-4f11-96f3-8285b6873411)

points: 150 X meme
https://x.com/Ashish129570796/status/1848670752276422718
![image](https://github.com/user-attachments/assets/e383d4d1-952d-4150-ac39-b3a860fef6a9)

### Points

?

### Provide proof that you've completed the task

Image

**Comment by jobenjada** [comment]
hey mate! 

The billboard isn't a billboard ad and the meme isn't a meme 😬  sorry, wont accept, feel free to try again!
