### ISSUE TITLE
[BUG] Reported 2 more  Security Issues in the Last Few Days

### ISSUE THREAD

**Issue by r0x5r** [formbricks/formbricks#3986]
### Issue Summary

I have reported 2 more  security issues in the last few days related to the Formbricks project. 

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by jobenjada** [comment]
/award 750

thanks a lot!
