### ISSUE TITLE
[🕹️]oss.gg related Side Quests & Formbricks Side Quests Multiple

### ISSUE THREAD

**Issue by r0x5r** [formbricks/formbricks#3987]
### What side quest or challenge are you solving?

oss.gg side quest and form brick side quest multiple

### Points

550

### Provide proof that you've completed the task

Provide proof that you've completed the task
Oss.gg related side Quest
1:- Like &[Re-Tweet oss.gg Launch Tweet ](https://x.com/ossgoodgame/status/1841019549183066552)(50 Points):  https://x.com/ossgoodgame/status/1841019549183066552 
![Screenshot 2024-10-23 133454](https://github.com/user-attachments/assets/4272383c-991e-463e-b361-af1fdd6d324d)

2:- San Francisco Billboard Ad (300 Points):
![image](https://github.com/user-attachments/assets/17060053-032e-4357-bc6c-ebb6908fca5c)

3:- upvote and comment on[Reddit launch thread](https://www.reddit.com/r/opensource/comments/1ftwbl9/weve_spent_a_few_months_building_ossgg_to_gamify/) (50 Points): [Post is Locked by Mods so upvoted]
![image](https://github.com/user-attachments/assets/9f8adcda-333f-4005-b5b8-f4a16f05a0f3)

4:- Meme Magic (150 Points)
![tweet](https://github.com/user-attachments/assets/9ccd56e1-9fd4-4f5d-badb-874c42e542d7)

TOTAL POINTS - 550

**Comment by jobenjada** [comment]
hey mate! thanks a lot but I can only /award 50 you these points.

The billboard is hardly a billboard add, the meme isn't a meme and the Reddit task is crossed out (not available anymore)
