### ISSUE TITLE
[BUG] Broken Redirects on `Developer Docs` -> `Contributing 

### ISSUE THREAD

**Issue by naineel1209** [formbricks/formbricks#3999]
### Issue Summary

Several broken redirect links were identified on the `Self Hosting` page. These links currently point to incorrect paths, causing users to get 404 error.

### Steps to Reproduce

On the page [Self - Hosting > Integratios](https://formbricks.com/docs/self-hosting/integrations) , all of the integrations have a broken redirect to `/docs/integrations#<specific-integration>`.

![image](https://github.com/user-attachments/assets/7d5b1870-7c32-4d3f-9fa5-0936fc603d8e)

### Expected behavior

On the page [Self - Hosting > Integratios](https://formbricks.com/docs/self-hosting/integrations) , all of the integrations should redirect to correct endpoint - `/docs/developer-docs/integrations/<specific-integration>`.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: Brave
```

**Comment by jobenjada** [comment]
/award 150 thanks a lot for spotting :)

you'll get 150 more after the merge
