### ISSUE TITLE
[BUG] Request to update twitter to x icon in docs site.

### ISSUE THREAD

**Issue by sarthak-kumar-shailendra** [formbricks/formbricks#4000]
### Issue Summary

The Twitter logo has been changed and has been updated on https://formbricks.com/ but hasn't been updated on the docs site https://formbricks.com/docs/introduction/what-is-formbricks.

### Steps to Reproduce

1. Go to https://formbricks.com/docs/introduction/what-is-formbricks and see the footer
2. 
3. 

### Expected behavior

The Twitter logo should be changed to X.

### Screenshots

<img width="177" alt="Screenshot 2024-10-24 at 12 51 17 AM" src="https://github.com/user-attachments/assets/9dd730ca-0cc1-4522-a78b-be1aefd314bd">
<img width="273" alt="Screenshot 2024-10-24 at 12 51 22 AM" src="https://github.com/user-attachments/assets/fad8d08c-29dd-4d6d-86d1-fa8cd096b23c">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: mac 
- Node: latest build
- npm: latest build
```

**Comment by jobenjada** [comment]
good catch /award 150 thanks! :)
