### ISSUE TITLE
[🕹️] Docs: Add image and video to question

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#4004]
### Is your feature request related to a problem? Please describe.

we're missing docs for the feature to add images and videos to each question:

icon on the right side:

<img width="682" alt="image" src="https://github.com/user-attachments/assets/85338b60-6d48-407c-9faa-315cd7ce2b3c">

### Describe the solution you'd like

add the docs incl. screenshots

add the content in the "global" directory in the docs, and then add it to the navigation for both  Link and Website and App Surveys

make sure all images are .webp (convert with tinypng.org )

thanks!!

**Comment by RajuGangitla** [comment]
you guys are fast @adityadeshlahre @DeepaPrasanna 

because im working on another task im not able to focus on this one 
leaving it to you guys ...
