### ISSUE TITLE
[BUG] Fix Webhook ping check

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#4005]
### Issue Summary

The webhook ping reports a success non non-sensical input:

<img width="730" alt="image" src="https://github.com/user-attachments/assets/c5da219e-4796-47d8-aff8-66b14baa549a">

<img width="561" alt="image" src="https://github.com/user-attachments/assets/0fe7650a-0920-4172-b9f1-f7ee1ee7d2ff">

### Steps to Reproduce

add a new webhook

type random string into Test URL field

### Expected behavior

check if its a URL and return error if not

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by gagan-bhullar-tech** [comment]
@jobenjada already created PR for this. Can you please assign it to me.

**Comment by DeepaPrasanna** [comment]
Hey @gagan-bhullar-tech this isn't how it works. One who gets assigned should raise the PR
