### ISSUE TITLE
[FEATURE] As a user I want to be reminded about changes when clicking out of the Survey Editor

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#401]
**Is your feature request related to a problem? Please describe.**
![grafik](https://github.com/formbricks/formbricks/assets/72809645/649e5c69-dcc5-43b4-8020-12e822fd2503)

**Describe the solution you'd like**
If changes are made and not saved, open a Dialoge to either save or discard changes:

**Unsaved Changes** 
You have unsaved changes in your survey. Would you like to save them before leaving?
Option 1: "Discard Changes"
Option 2: "Save Changes"

**Comment by joe-shajan** [comment]
Hey, @jobenjada I would like to work on this.

**Comment by jobenjada** [comment]
great, thanks :))
