### ISSUE TITLE
[🕹️]Follow Formbricks LinkedIn Page

### ISSUE THREAD

**Issue by arg387** [formbricks/formbricks#4011]
### What side quest or challenge are you solving?

I have started to follow Formbricks Linkedin Page from today.

### Points

50

### Description

[my github link](https://github.com/arg387?tab=overview&from=2024-09-01&to=2024-09-30)
[my linkedin profile](https://www.linkedin.com/in/argha-saha-baa275272/)

### Provide proof that you've completed the task

![Screenshot 2024-10-24 151529](https://github.com/user-attachments/assets/83aa3043-e766-4b72-ad1d-3e07a5c36d27)

**Comment by AshishPal18** [comment]
I have started to follow Formbricks Linkedin Page.

My Github :  https://github.com/AshishPal18
My Linkedin :  https://www.linkedin.com/in/ashish-pal-b4bb541b6/

<img width="434" alt="image" src="https://github.com/user-attachments/assets/adb85cfc-add3-46a3-9fd9-cdd8eff130ca">
