### ISSUE TITLE
[🕹️]Side Quests Bug Hunter

### ISSUE THREAD

**Issue by adilkadivala** [formbricks/formbricks#4019]
### What side quest or challenge are you solving?

Bug Hunter

### Points

50 - 150 Points for every bug

### Description

Themes option
having dark theme  is more helpful for some user

### Provide proof that you've completed the task

I got just one theme in a main website,  

![themeformbricks](https://github.com/user-attachments/assets/4d1c1ac7-bc2f-461c-9374-9f40960c212d)

**Comment by jobenjada** [comment]
not a bug :)
