### ISSUE TITLE
[BUG] spaces are not validated on People Page

### ISSUE THREAD

**Issue by adityadeshlahre** [formbricks/formbricks#4025]
### Spacey Submission

![emptyNessformFinal](https://github.com/user-attachments/assets/6e7b3426-b5ea-4c26-bba0-752c5574aa2e)

### Steps to Reproduce

1. On the people page [ click on Create Segment + button ]
2. Fill the spaces on [ Title, Description & (Targeting Options)]
3. Final Save button click [Create segment]

### Expected behavior

It should keep the [create segment] button disabled and only it should enable on the character ENTRY!
Targeting Filters should have a valid have minimal validation of
- [ ] USERID = spaces
- [ ] EMAIL = zod for email & spaces 
- [ ] Language = spaces

![image](https://github.com/user-attachments/assets/ce63e0ed-fd3a-474c-a06a-0383e8af97ea)

### Screenshots

![image](https://github.com/user-attachments/assets/ce63e0ed-fd3a-474c-a06a-0383e8af97ea)

_No response_

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Arch
- Node: latest
- npm: latest
```

**Comment by adityadeshlahre** [comment]
@pandeymangg 

![image](https://github.com/user-attachments/assets/3e3ef97b-7bd6-462d-aa9e-a44f92490f18)

![image](https://github.com/user-attachments/assets/f440f186-c677-46f0-8ea4-5aecae4bc886)

### take a look at Action Page

**Comment by jobenjada** [comment]
will review PR to solve this :)
