### ISSUE TITLE
[BUG] Cant upload images (avatar, logo, etc.) (using Nginx)

### ISSUE THREAD

**Issue by ratte1303** [formbricks/formbricks#4029]
### Issue Summary

When trying to upload/view any image I am getting the following error in the console and the images are not loading. I am using nginx as reverse proxy and have set the correct host names in the .env file. 

### The error
 ⨯ TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchExternalImage (/home/nextjs/node_modules/next/dist/server/image-optimizer.js:589:17)
    at async NextNodeServer.imageOptimizer (/home/nextjs/node_modules/next/dist/server/next-server.js:649:48)
    at async cacheEntry.imageResponseCache.get.incrementalCache (/home/nextjs/node_modules/next/dist/server/next-server.js:182:65)
    at async /home/nextjs/node_modules/next/dist/server/response-cache/index.js:90:36
    at async /home/nextjs/node_modules/next/dist/lib/batcher.js:45:32 {
  [cause]: AggregateError [ECONNREFUSED]:
      at internalConnectMultiple (node:net:1118:18)
      at internalConnectMultiple (node:net:1186:5)
      at afterConnectMultiple (node:net:1685:7)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error], [Error] ]
  }
}

### My nginx config (short version)
location / {

  proxy_pass        http://127.0.0.1:3000;
  proxy_redirect    off;
  proxy_set_header  Host $host;
  proxy_set_header  X-Real-IP $remote_addr;
  proxy_set_header  X-Forwarded-Proto $scheme;
  proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header  X-Forwarded-Host $host;
  proxy_set_header  X-Forwarded-Port $server_port;
  
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";

}

### Steps to Reproduce

1. Click on upload
2. Short loading time
3. Image is not showing and getting Error 500 in the browser console

### Expected behavior

Image is uploading and showing

### Other information

I have the latest version installed via docker and already tried reinstalling. 

### Screenshots

![grafik](https://github.com/user-attachments/assets/2cdff128-12a5-4ec9-93b2-5bb262633ccb)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [x] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Debian 11
```

**Comment by arg387** [comment]
![Screenshot 2024-10-25 194835](https://github.com/user-attachments/assets/6838e629-6bbe-42d9-ac71-2f30a37b47a4)
Bro logo is working
![Screenshot 2024-10-25 195010](https://github.com/user-attachments/assets/dff2d24e-9e7b-42f8-ba3e-2ed1f934a3b7)
