### ISSUE TITLE
[🕹️]Spread the word

### ISSUE THREAD

**Issue by Vikgithuberit** [formbricks/formbricks#4033]
### What side quest or challenge are you solving?

spread the knowledge about the oss.gg hacktoberfest.

### Points

150

### Provide proof that you've completed the task

![Uploading Screenshot (421).png…]()
![Uploading Screenshot (420).png…]()
![Screenshot (419)](https://github.com/user-attachments/assets/552faea8-6bf5-4754-92fd-1dabdd6ffce4)

**Comment by jobenjada** [comment]
thanks! :) /award 150
