### ISSUE TITLE
[🕹️]Design a Survay background: 

### ISSUE THREAD

**Issue by mehdi621-git** [formbricks/formbricks#4035]
### What side quest or challenge are you solving?

Design a background 

### Points

300 Points

### Description

Create a New background for Surveys.
=> Merge different images and Craft a new image
=> This looks attractive especially for dark background lovers .Instead it is intresting itself
Source to download : 
https://raw.githubusercontent.com/mehdi621-git/mumbaigit/refs/heads/main/Black%20and%20White%20Simple%20Easel%20Background.webp

### Provide proof that you've completed the task

Source Link from Canva: https://www.canva.com/design/DAGUmfz_BZU/2o4IPOJX5zLBNmmI-qReVg/view?utm_content=DAGUmfz_BZU&utm_campaign=share_your_design&utm_medium=link&utm_source=shareyourdesignpanel

Completion Proof:
![background webp](https://github.com/user-attachments/assets/8d030c00-c5d6-4703-848d-0a0d9b368629)

**Comment by jobenjada** [comment]
hey! Im sorry but Canva stuff is not copy right free so we cannot use it in our product :( or where did you get the images from?
