### ISSUE TITLE
[🕹️] feat: Add rich text to questions and descriptions in survey 

### ISSUE THREAD

**Issue by RajuGangitla** [formbricks/formbricks#4039]
### What side quest or challenge are you solving?

this not side quest 

### Points

1500

### Provide proof that you've completed the task

[screen-capture (25).webm](https://github.com/user-attachments/assets/c50aa801-364e-451f-bc1b-e022acc1b35d)

**Comment by Shrinivasdumbali** [comment]
if solved: pass
else: /assign
