### ISSUE TITLE
[🕹️] Bug Hunter

### ISSUE THREAD

**Issue by rajeevDewangan** [formbricks/formbricks#4043]
### What side quest or challenge are you solving?

Bug Hunter

### Points

50 - 150

### Description

In the formbricks docs section, opening one dropdown shouldn't close the another opened one.

### Provide proof that you've completed the task

video : 
https://github.com/user-attachments/assets/90ab7ac4-2d16-4746-a7cf-922134980cb1

**Comment by jobenjada** [comment]
that keeps it more tidy :)
