### ISSUE TITLE
[🕹️]Supabase + NextJS: How to run a targeted in-app survey for free

### ISSUE THREAD

**Issue by Dumebii** [formbricks/formbricks#4046]
### What side quest or challenge are you solving?

Technical Article involving formbricks. 

### Points

1500

### Description

I wrote an article on how to integrate formbricks in a Next.Js + Supabase app. 

### Provide proof that you've completed the task

https://dev.to/dumebii/supabase-nextjs-how-to-run-a-targeted-in-app-survey-for-free-using-formbricks-23bo

**Comment by jobenjada** [comment]
great work, thanks a lot! /award 1500
