### ISSUE TITLE
[🕹️] Starry-eyed Supporter

### ISSUE THREAD

**Issue by Dehelaan** [formbricks/formbricks#4048]
### What side quest or challenge are you solving?

Get five friends to star

### Points

150

### Provide proof that you've completed the task

![WhatsApp Image 2024-10-26 at 21 09 25_6f92659b](https://github.com/user-attachments/assets/63ba18a2-48a5-45dc-9d84-bfb6bbedebc6)
![Screenshot 2024-10-26 211440](https://github.com/user-attachments/assets/824e7dd0-67d8-4e89-8fa5-45ca0172408b)
![Screenshot 2024-10-26 211634](https://github.com/user-attachments/assets/a7507db0-d80e-4dcc-875e-c2589f946dd4)
![Screenshot 2024-10-26 214922](https://github.com/user-attachments/assets/749238d7-fe0d-4261-ab2c-2797f0416ac1)
![Screenshot 2024-10-26 215706](https://github.com/user-attachments/assets/e0ef3dc2-66cd-46d4-b19f-d9fee2142880)

**Comment by dev-daizy** [comment]
![Screenshot 2024-10-27 011408](https://github.com/user-attachments/assets/f5fe3773-1db1-402c-bde9-dfad4ae571b4)
![Screenshot 2024-10-27 011322](https://github.com/user-attachments/assets/36b406ca-05e2-499e-84ec-e3146c8f92b5)
![Screenshot 2024-10-27 011140](https://github.com/user-attachments/assets/00b5d354-b7f2-48d9-862f-e450dbe38876)
![Screenshot 2024-10-27 011033](https://github.com/user-attachments/assets/9310504b-f27a-4138-bb36-0ac1d758c80b)
![Screenshot 2024-10-27 010947](https://github.com/user-attachments/assets/d9ccbaba-2cb3-40d3-a711-218b0156a9ae)
