### ISSUE TITLE
[🕹️] Follow Formbricks LinkedIn 

### ISSUE THREAD

**Issue by Dehelaan** [formbricks/formbricks#4050]
### What side quest or challenge are you solving?

Follow Formbricks LinkedIn

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/6cf89bbe-a938-412f-b624-2d94a049f891)

**Comment by dev-daizy** [comment]
![image](https://github.com/user-attachments/assets/d22d9f37-1f87-4d8c-9321-56fe3b4290af)
