### ISSUE TITLE
[🕹️] Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by dev-daizy** [formbricks/formbricks#4056]
### What side quest or challenge are you solving?

 Re-Tweet oss.gg Launch Tweet
 https://x.com/ossgoodgame/status/1841019549183066552

### Points

50

### Provide proof that you've completed the task

![Screenshot 2024-10-27 122910](https://github.com/user-attachments/assets/0ddf4024-34c6-43ad-808a-4ca7ffaec6cb)

**Comment by uditjainstjis** [comment]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/642eff34-d28c-46e4-9b86-73784348e04f">
Done, just this?

**Comment by i-m-soumya** [comment]
![image](https://github.com/user-attachments/assets/f5785c2c-7dac-463c-9fe8-196137beb549)

**Comment by i-m-soumya** [comment]
@dev-daizy done!
