### ISSUE TITLE
[🕹️]Completed 5 side quests.

### ISSUE THREAD

**Issue by arg387** [formbricks/formbricks#4057]
### What side quest or challenge are you solving?

- San Francisco Billboard Ad(300 Points)
- Meme Magic (150 Points)
- Gif Magic (150 Points)
- Design a background (300 Points)(double bonus points for animated background)
- Brickify someone famous with AI (150 Points)

### Points

1450 (including 300 bonus points for animated background )

### For verification
[My Twitter Link](https://x.com/crazygamer651)
[My Github Link](https://github.com/arg387)

### Provide proof that you've completed the task

- San Francisco Billboard Ad (300 Points)
![image(2)](https://github.com/user-attachments/assets/588d3b10-fc1e-49b0-bf53-7b1b482b85a8)

- Meme Magic (150 Points)
  [meme Link](https://x.com/crazygamer651/status/1850411794395013189)
- Gif Magic (150 Points)
[giphy Link](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNnZ3aWZ1MzdxbG1rZ250NGx2bm1zemR2cGx4aDA4MWRyY3E3M3F2YSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/C4jbNUlyRA1dQTwST9/giphy.gif)
- Design a background (300 Points)(double bonus points for animated background)
(made with ai)
![Recording 2024-10-27 141506](https://github.com/user-attachments/assets/476304b4-9777-4b54-810a-f069645154ec)
[google drive link](https://drive.google.com/file/d/1SoeNJ2FYcglKTTacYTu_nX5AFl4CkeMd/view?usp=drive_link)
- Brickify someone famous with AI (150 Points)
 Brad Pitt has become my target.
![Screenshot 2024-10-27 113822](https://github.com/user-attachments/assets/72f22b7d-c15c-4d8b-a3e8-2f79d9757277)

**Comment by jobenjada** [comment]
hey mate! 

/award 300 for brad pitt and the gif

Background: If you have a look at the product it becomes clear what we're looking for
Billboard: ...
Meme: I dont get it (:

**Comment by arg387** [comment]
Meme: Craft a meme where a brick plays a role. Tweet it, and tag us @formbricks to submit.(This is the rule there)
Billboard : Is there any problem with its quality???
Background: These are the rule i followed as instructed..
![Screenshot 2024-10-28 095255](https://github.com/user-attachments/assets/6dc38fc8-e24a-4a2e-91fe-4afc178a4a9c)
