### ISSUE TITLE
[🕹️] oss.gg : Technical Article Challenge

### ISSUE THREAD

**Issue by adilkadivala** [formbricks/formbricks#4059]
### What side quest or challenge are you solving?

Technical Article around Formbricks

### Points

1,500 Points

### Description

i have wrote a detailed Article on Frombricks 

### Provide proof that you've completed the task

Article [Link](https://dev.to/k-adi/how-to-survey-only-power-users-in-your-nextjs-app-with-formbricks-39e)

![formbricksarticle](https://github.com/user-attachments/assets/7948294d-e634-4dc1-af33-ce8a82576da9)

**Comment by kumawatvaibhav** [comment]
can you explain what is task actually here you have not mentioned it clearly

**Comment by adilkadivala** [comment]
I think now it is clear

**Comment by jobenjada** [comment]
In the article it becomes clear that you never really got the app running. Its not a tutorial on how to do it, its just a write up generated by AI based on publicly available information. Sorry, but cant give you points for that.

**Comment by jobenjada** [comment]
also, please unpublish this article, as it might confuse people

**Comment by adilkadivala** [comment]
post deleted
