### ISSUE TITLE
[🕹️]Design a background

### ISSUE THREAD

**Issue by Ionfinisher** [formbricks/formbricks#4081]
### What side quest or challenge are you solving?

Design a background for the form styling

### Points

750

### Description

Just found this video from guy called Rostislav Uzunov on pexels. The source video link is here: https://www.pexels.com/video/close-up-video-of-a-wavy-plastic-9150545/  
and you can get the gif version i made here:
https://drive.google.com/file/d/1n0KUrl3ewfmwl_5hDtWqgDOwrVtM1NxH/view?usp=sharing

I recommend looking at this guy work, he has ton of background material videos that you can use. Here is his pexels account link: https://www.pexels.com/video/close-up-video-of-a-wavy-plastic-9150545/

### Provide proof that you've completed the task

<img width="1280" alt="Screen Shot 2024-10-28 at 08 21 41" src="https://github.com/user-attachments/assets/60131e6b-3e68-4be3-afea-d987dce0921d">

**Comment by jobenjada** [comment]
thats actually a cool video :)

can you loop it and open a PR to add it to the right place so that people can use it in the product?

**Comment by Ionfinisher** [comment]
Hey @jobenjada Hope you're doing well. Sure can
