### ISSUE TITLE
[🕹️] Starry Eyed Supporter

### ISSUE THREAD

**Issue by prachhii31** [formbricks/formbricks#4083]
### What side quest or challenge are you solving?

starred the repository

### Points

150

### Provide proof that you've completed the task

![Screenshot 2024-10-28 125442](https://github.com/user-attachments/assets/ee01f4d6-981b-4b42-97fe-a560f74dd515)
![Screenshot 2024-10-28 125948](https://github.com/user-attachments/assets/cbe1b111-0c92-47e3-a219-4ed79f14ac83)
![Screenshot 2024-10-28 130048](https://github.com/user-attachments/assets/8f0cc38b-b0ab-43d9-816e-384cdc80ce31)

**Comment by jobenjada** [comment]
hey!  you need to get 5 friends to do that, not do it yourself :)
