### ISSUE TITLE
[FEATURE] Assign answer value to variable

### ISSUE THREAD

**Issue by ratte1303** [formbricks/formbricks#4084]
### Is your feature request related to a problem? Please describe.

I want to create an advanced calculator to help users calculating their maximum rent they have to pay. 
For that I need a way for the user to input a number and have this number assignes to a variable for further calculations. 

### Describe the solution you'd like

Add a field in conditional logic to allow varaibles to be set by a previous answer the user has given. 

Example: 
The user is asked how much rent he is paying. The users answers. The answer is being calculated and a result appears based on the users number input.

**Comment by jobenjada** [comment]
<img width="1089" alt="image" src="https://github.com/user-attachments/assets/293c8b44-9d75-4812-b195-6e3e492b43fa">

so here we'd need "Assign field value to variable" - that would solve your issue, right? @ratte1303

**Comment by ratte1303** [comment]
@jobenjada Yeah, that would be great! 

do you think the feature can be implemented soon? :)

**Comment by jobenjada** [comment]
hey @ratte1303 we're currently busy getting 2.7 out of the door. I've assigned Piyush who built the Logic Feature to look into it as soon as he can :) We do our best, but are a small team with a lot of requests. 

While your request definitely makes sense and we will build it eventually, we prioritize things our paying customers request.
