### ISSUE TITLE
[🕹️] oss.gg: Share your experience about oss.gg

### ISSUE THREAD

**Issue by rajeevDewangan** [formbricks/formbricks#4085]
### What side quest or challenge are you solving?

oss.gg: Share your experience about oss.gg

### Points

750

### Description

Shared my experience of participation at Hacktoberfest and the oss.gg hackathon in an article on dev.to

### Provide proof that you've completed the task

link to article : https://dev.to/rajeevdewangan/my-journey-with-the-ossgg-hackathon-a-fulfilling-open-source-experience-36k3
![Screenshot 2024-10-28 200823](https://github.com/user-attachments/assets/414faccd-7d46-46d2-b566-6a1b33a6d2b9)

**Comment by rajeevDewangan** [comment]
@jobenjada where is my point 😞

**Comment by aritradevelops** [comment]
hey @rajeevDewangan may be you should assign yourself with /assign , then he can credit. I'm not sure though.
