### ISSUE TITLE
[🕹️] Feedback Fanatic

### ISSUE THREAD

**Issue by rajeevDewangan** [formbricks/formbricks#4086]
### What side quest or challenge are you solving?

Fill out our feedback survey after the hackathon with suggestions for improvement

### Points

150

### Provide proof that you've completed the task

![Screenshot 2024-10-18 121846](https://github.com/user-attachments/assets/dc73e802-b84e-4f36-b0fc-6a1544477d2c)

**Comment by jobenjada** [comment]
whups, you already got points for that review :( 

sorry, we have a 0% tolerance for cheating......

**Comment by rajeevDewangan** [comment]
@jobenjada I remember I had done secret side quest and it was one of them but Feedback fanatic is a separate task. If you want I can do any other task for the point you awarded to me.

**Comment by jobenjada** [comment]
I think its pretty clear that this is a different task, isn't it?

<img width="750" alt="image" src="https://github.com/user-attachments/assets/47d04c8f-9f3b-4b2e-8a49-c8f994845cc8">

**Comment by rajeevDewangan** [comment]
@jobenjada by the time I was doing it the survey form was not available so I searched it a little and came across #3614, Now that you have shared the form I will open an issue and do it for 0 points

**Comment by jobenjada** [comment]
got it, you can keep playing!

**Comment by rajeevDewangan** [comment]
Please give points for #4085
