### ISSUE TITLE
[🕹️]Design a Background 

### ISSUE THREAD

**Issue by arg387** [formbricks/formbricks#4088]
### What side quest or challenge are you solving?

Design a background for the form styling

### Points

600

### Provide proof that you've completed the task

[Link of the animation video in Pixabey](https://pixabay.com/videos/animation-letters-characters-3d-7529/)
This one is free to use. 
![Recording 2024-10-28 221815](https://github.com/user-attachments/assets/e053132a-4e5a-4da4-8f20-b4b658eafb25)
![Screenshot 2024-10-28 221919](https://github.com/user-attachments/assets/530a2fac-813f-4a11-aa69-cbe5e983fd33)
If the quality is bad this time, it may be because of webp conversion(I am doing mp4 to webp conversion from online).

**Comment by jobenjada** [comment]
it looks very cool! 

can you make sure that its a loop of 5 seconds length?  and export it as an .mp4 ?

in the format right now we cant really add it to the product

**Comment by arg387** [comment]
this is the video in mp4 format with 5sec length
https://github.com/user-attachments/assets/18ab3190-fb82-48c1-9e4c-fd433ecc7b3c

**Comment by jobenjada** [comment]
/award 600 thanks, i'll sort it out at some point and add it to the list :)
