### ISSUE TITLE
[🕹️][oss.gg hackathon] Starry-eyed Supporter (150 Points)

### ISSUE THREAD

**Issue by naaa760** [formbricks/formbricks#4094]
### What side quest or challenge are you solving?

[🕹️] Starry-eyed Supporter (150 Points)

### Points

150

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/d0964813-481f-4a2f-a4b8-7cbab393d16d)
![image](https://github.com/user-attachments/assets/5fd440aa-7c84-4385-adef-310e503389bd)
![WhatsApp Image 2024-10-28 at 8 17 30 PM](https://github.com/user-attachments/assets/3dc0243c-a318-45b7-ac8c-74c060f0fa21)
![WhatsApp Image 2024-10-28 at 9 01 24 PM](https://github.com/user-attachments/assets/259a2428-63f3-4c5f-8c9f-d7c86a474bcc)
![WhatsApp Image 2024-10-27 at 11 00 25 PM](https://github.com/user-attachments/assets/b021aa1e-085f-4ed2-ad85-f2a11663b1d0)

**Comment by Shrinivasdumbali** [comment]
![1](https://github.com/user-attachments/assets/338422a0-0687-4f84-99e1-52a8d4ae9165)
![2](https://github.com/user-attachments/assets/ba872dd0-28fc-4669-be5e-a27c7415b680)
![3](https://github.com/user-attachments/assets/7ee9fde9-98b4-4f8e-9554-92d6e4b79099)
![4](https://github.com/user-attachments/assets/d1fa810c-de8a-4f90-8cda-77507c2f4ea2)
![5](https://github.com/user-attachments/assets/b4592262-8e88-4444-bf1a-4472f79991cc)
Thanks to my friends for helping me to do side quests.
