### ISSUE TITLE
[🕹️] Article: How to survey only power users in your NextJS app

### ISSUE THREAD

**Issue by Khaan25** [formbricks/formbricks#4098]
### What side quest or challenge are you solving?

Article: How to survey only power users in your NextJS app #3199

### Points

1500

### Provide proof that you've completed the task

Here's the [link](https://medium.com/@ziaurzai/how-to-survey-only-power-users-in-your-nextjs-app-formbricks-93a556916381) to the article.

Here's the [GitHub repo](https://github.com/Khaan25/survey-power-users-only) as well for full source code.

**Comment by Khaan25** [comment]
@jobenjada

**Comment by jobenjada** [comment]
hey! Its a good write up of how to integrate Formbricks but it's not dealing with how to only survey power users. You would've needed to include any form of attribute-based targeting.

**Comment by Khaan25** [comment]
We've attributes-based targeting? No?
Here's an image of settings attributes:
![image](https://github.com/user-attachments/assets/1a79ee8f-2f9e-45b5-b2cb-24656ce5ed3d)


We're settings some attributes and only showing the form to a power user. If a user falls under category of power user, he's shown the form, otherwise user isn't.

@jobenjada
