### ISSUE TITLE
[🕹️] Meme Magic 

### ISSUE THREAD

**Issue by Dehelaan** [formbricks/formbricks#4100]
### What side quest or challenge are you solving?

Craft a meme where a brick plays a role

### Points

150

### Provide proof that you've completed the task

![formb](https://github.com/user-attachments/assets/ce781ed4-1efb-413c-bfa6-db5cc0a668bf)

**Comment by jobenjada** [comment]
im not sure if I get it :D feel free to open a new issue if you wanna try again :)
