### ISSUE TITLE
[🕹️] Gif Magic

### ISSUE THREAD

**Issue by Dehelaan** [formbricks/formbricks#4101]
### What side quest or challenge are you solving?

 Create a branded gif related to Formbricks

### Points

150

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/97372972-1d46-4867-afac-bd04bd9a1c6c)

link: https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExM3hmdnlwanl2dHI3bmljbmx3aXVuM2RqMng5ZWw5OGFhZnYzMHRwMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/8f1SSR3aVS7Hdqtdyr/giphy.gif

**Comment by Vikgithuberit** [comment]
yes
please assign me

**Comment by jobenjada** [comment]
whattt? :D how does this make sense? :)
