### ISSUE TITLE
[🕹️] BUG Found an animation bug  on formbrick configuration page

### ISSUE THREAD

**Issue by thefool76** [formbricks/formbricks#4109]
### What side quest or challenge are you solving?

So this Bug is Live on the website 

Bug - Typo in 36_4I.mp4 Filename Causing Animation Bug on Live Website  & Some User Deleted the 40_4k.mp4 file by mistake
![Screenshot 2024-10-29 at 7 26 41 PM](https://github.com/user-attachments/assets/06c93508-b3d0-4e59-babb-f051db6430eb)

The selected file animation is not playing because of wrong typo

it's on the repo as well
![Screenshot 2024-10-29 at 7 24 19 PM](https://github.com/user-attachments/assets/6af6e544-8c51-445d-b7b8-acd4237dc2ba)

### Points

Need to be assigned

### Provide proof that you've completed the task

I will be fixing it

**Comment by thefool76** [comment]
lol I just fix it

**Comment by jobenjada** [comment]
we have that one already :)
