### ISSUE TITLE
[🕹️] Starry-eyed Supporter (150 Points)

### ISSUE THREAD

**Issue by Subash-Lamichhane** [formbricks/formbricks#4112]
### What side quest or challenge are you solving?

Starry-eyed Supporter (150 Points):

### Points

150 Points

### Description

Starred formbricks repo

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/209b1c1a-9a2a-45bd-a77f-2ca407ef855d)
![image](https://github.com/user-attachments/assets/22aa92b1-d255-4e63-87b6-1501601e24bc)
![image](https://github.com/user-attachments/assets/78e2ef44-79fe-4be8-8f97-30002f577cc1)
![image](https://github.com/user-attachments/assets/23c45cf3-0001-4fb9-8f11-40a6d6fc7d9e)
![image](https://github.com/user-attachments/assets/98b04a62-9ed7-4611-bb35-113acd113498)

**Comment by HareeshDhruva** [comment]
assign
