### ISSUE TITLE
[🕹️]Accessibility Advocate

### ISSUE THREAD

**Issue by Atharva-3000** [formbricks/formbricks#4115]
### What side quest or challenge are you solving?

Conduct an accessibility audit of the Formbricks UI and provide recommendations for improvements. 

### Points

50-300

### Description

Did an audit to find out various UI improvements here and there.

### The multiple button cards on the landing page on **MOBILE DEVICES**.
![image](https://github.com/user-attachments/assets/fb723e7e-c75a-40a9-a785-bf4c65de688e)
![image](https://github.com/user-attachments/assets/169a7dea-27ee-443e-a2ac-fe9ddcd7ce47)
![image](https://github.com/user-attachments/assets/9d026931-bba1-4e2c-a2fd-58098d34eaea)
<br>
### Top Padding when the banner for Dev Mode is Present:
![image](https://github.com/user-attachments/assets/6e23089a-d7b7-4a17-ba39-c0e4253ee623)
### How it should be:
![image](https://github.com/user-attachments/assets/0c97c6d5-b5e6-4174-9635-6355456043f2)

**Comment by jobenjada** [comment]
hey! The landing page isn't part of the bug and accessibility hunting this year :) 

here is /award 100 for the top bar
