### ISSUE TITLE
[BUG] Flickering animation preview + form data reset on settings

### ISSUE THREAD

**Issue by Vardhaman619** [formbricks/formbricks#4121]
### What side quest or challenge are you solving?

Accessibility Advocate

### Points

50-300

### Description

I've identified two accessibility and usability issues in the Formbricks that could benefit from improvements:

**1. Preview Form Reset:**
When clicking "Restart" in the form preview, the input values aren’t clearing as expected. Instead, the fields retain the previous values, which can be confusing for users expecting a fresh start.
 
**2. UI Flashing in Background Animation Settings:**
In the "Look and Feel" settings under the "Background Styling" section, selecting any animation style in the "Animation" tab causes a UI flash and a re-render of all animation options. This visual disruption feels unintended and may negatively impact user experience.

### Provide proof that you've completed the task

[form-input-values-not-resetting-after-restart.webm](https://github.com/user-attachments/assets/7dac93b8-9f06-4e4e-821d-87a157d7d269)

[card-background-animation-setting-UI-flashing.webm](https://github.com/user-attachments/assets/a350ea48-6c46-4d02-a072-77b7114237e5)

**Comment by jobenjada** [comment]
good catches :) /award 150

**Comment by jobenjada** [comment]
feel free to open a PR to fix these (each 150 points)
