### ISSUE TITLE
[🕹️] Two articles: Experience sharing and Quiz with Formbricks

### ISSUE THREAD

**Issue by harshsbhat** [formbricks/formbricks#4126]
### What side quest or challenge are you solving?

Article writing

### Points

1500

### Provide proof that you've completed the task

QUIZ:
https://www.harshbhat.me/blog/formbricks-quiz

Experience:
https://www.harshbhat.me/blog/oss-gg

**Comment by adityadeshlahre** [comment]
from where this QUIZ blog side quest came @harshsbhat ? :slightly_smiling_face: Means where this side quest mentioned

**Comment by harshsbhat** [comment]
Hope you liked it. Lemme know if there are any suggestions from your side 🙂

**Comment by jobenjada** [comment]
please also open a PR with the boiled down version for the docs 🤓

**Comment by harshsbhat** [comment]
@jobenjada created a PR
