### ISSUE TITLE
[🕹️] Article:  My Unfiltered Experience at the OSS.GG Hackathon

### ISSUE THREAD

**Issue by thefool76** [formbricks/formbricks#4128]
### What side quest or challenge are you solving?

First of all, I truly appreciate the hard work of the Formbricks team and other OSS repository maintainers. Managing such a high volume of issues and pull requests every day for an entire month is no small feat

I have write a Blog on hash node about my Unfiltered Experience at the OSS.GG Hackathon

### Points

750

### Provide proof that you've completed the task

Please read it thanks
[click here](https://k5lo7h.hashnode.dev/ossgg-made-my-hacktoberfest-productive)

**Comment by jobenjada** [comment]
hey! Great write up, thanks :)

Please add a backlink to the project landing pages in the last paragraph 🚀 

/award 750
