### ISSUE TITLE
[BUG] Test Endpoint fails to test the webhook 

### ISSUE THREAD

**Issue by DeepaPrasanna** [formbricks/formbricks#4140]
### Issue Summary

While working on mattermost, I have observed that the test endpoint gives a success message even when the test endpoint api fails internally. 
![image](https://github.com/user-attachments/assets/d0bced05-c73a-45f0-b765-c3a9960855cc)
![image](https://github.com/user-attachments/assets/3abaf599-6766-4b51-baa6-d097be7417e5)

### Steps to Reproduce

1. Run the app locally to check for the error
2. Give any endpoint that fails to test the webhook
3.  The error toast doesn't shows and the test endpoint shows a success message

### Expected behavior

If the ping for a health check of a webhook endpoint fails, show a failure message.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by gupta-piyush19** [comment]
fixed with https://github.com/formbricks/formbricks/pull/3463
