### ISSUE TITLE
[BUG] Back Button is Autofocused with No Margin in Modal

### ISSUE THREAD

**Issue by JeevaRamanathan** [formbricks/formbricks#4156]
### Issue Summary

When opening an embedded modal (or any modal), the back button in the top left is automatically focused, and it has no margin.

### Steps to Reproduce

Attached the video

### Expected behavior

he back button should not be focused by default when a modal is opened, and it should have appropriate margin for spacing.

### Other information

(screen flickering happens due to the recorder when modal is opened)

https://github.com/user-attachments/assets/aec9cfd1-17cc-419e-9c1b-3e41439997ca

### Screenshots

![image](https://github.com/user-attachments/assets/5e993c82-2fba-4db4-916b-7956dd92da97)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: Chrome
```

**Comment by Surajsuthar** [comment]
@jobenjada  can i work on this ?

**Comment by khAja13** [comment]
This is fixed in the pull request #4226
