### ISSUE TITLE
[FOR-807] [FEATURE] Rebuild client displays endpoints

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#416]
**Is your feature request related to a problem? Please describe.**
We are currently in the process of revamping our client APIs to get ready for Formbricks v1.0. The client endpoints are used in the link survey as well as the formbricks-js widget. On top of that developers use those APIs to build their own survey frontends and then send the responses to Formbricks. That's why we need good and stable APIs for the this functionality.

We have two important client endpoints:

* responses: create and update responses (link survey + formbricks-js)
* displays: create and update display events (link survey + formbricks-js)

We already rewritten the responses endpoints for our new (zod + database service-layer + next.js route handlers) infrastructure but now need new displays endpoints as well.

**Describe the solution you'd like**
With our new infrastructure we make a few improvements:

* Use a data abstraction layer plus data retrieval services (e.g. `getSurveys()` method instead of prisma call) to make data retrieval easier and introduce a modified data model that's easier to handle in the frontend.
* Use Zod to build types that can be used both for Typescript annotation as well as runtime validation.
* Use Next.JS Route handlers (app-directory) to have all our code in one place

Please build this infrastructure for the displays endpoints. The current production displays endpoints can be found in `apps/web/pages/v1/client/environments/[environmentId]/displays`). I already transformed this endpoint in a route handler that can be found in `apps/web/app/v1/client/displays` but this was only the first part of the revamp. Please make the following changes:

* Add a Zod Schema for Displays. A Display that is returned in the API should have this type:

```
interface Display {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  surveyId: string;
  person: Person | null;
  status: "seen" | "responded";
}

interface Person {
  id: string;
  attributes: Record<string, string | number>;
}
```

You can use the response schema `apps/web/packages/types/v1/responses` as reference.

* Add a service to get, update & create a new display in `apps/web/packages/lib/services`
* Update the displays api route handlers to validate the input using zod (decide for a zod-based input schema). The API endpoint should return the full display. Please use the new service instead of prisma calls (add new services if necessary)
* Add docs for the new endpoint (see responses docs in `apps/formbricks-com/pages/docs/client-api/create-response` for reference)

Please feel free to challenge the current approach and get in touch with me if you have further ideas or suggestions how to better structure and build the endpoints.

<sub>From [SyncLinear.com](https://synclinear.com) | [FOR-807](https://linear.app/formbricks/issue/FOR-807/[feature]-rebuild-client-displays-endpoints)</sub>

**Comment by Ashutosh-Bhadauriya** [comment]
@mattinannt I can take this up 🙂

**Comment by subh-cs** [comment]
Hi @mattinannt, I think I'm the contributor you mentioned. Please assign this to me. Thanks!!
