### ISSUE TITLE
[🕹️]Proof of Feedback form

### ISSUE THREAD

**Issue by Fz-Faiz** [formbricks/formbricks#4165]
### What side quest or challenge are you solving?

Filling the Feedback form 
![Thank you](https://github.com/user-attachments/assets/daac6d48-b622-4793-aa22-02b67c1e8dc5)

### Points

150

### Description

Nothing major

### Provide proof that you've completed the task

[
![Thank you](https://github.com/user-attachments/assets/e3762243-4ea8-4177-9762-e21519712f36)
](url)

**Comment by jobenjada** [comment]
sorry, you hardly played so you cant provide feedback
