### ISSUE TITLE
[🕹️]Feedback Fanatic Side Quest

### ISSUE THREAD

**Issue by Vanshdeepsingh-2232** [formbricks/formbricks#4168]
### What side quest or challenge are you solving?

for the Feedback Fanatic side quest

### Points

150

### Description

Filled the feedback form.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/95b82858-5b24-4ff8-9cdf-a18cdd78c7e5)

**Comment by jobenjada** [comment]
sorry you have too little points to provide feedback
