### ISSUE TITLE
[BUG] "Other" Option in Single-Select Auto-Selects Choices, Blocking Custom Input

### ISSUE THREAD

**Issue by JeevaRamanathan** [formbricks/formbricks#4169]
### Issue Summary

The form question, "What's your favorite mode of transport?" is set up as a single-select with radio buttons, including an "Other" option for custom input. When a user selects "Other" and begins typing a specific choice, like "Car," the form automatically selects the "Car" option from the list, preventing the user from typing additional choices (e.g., "Car and Train"). This issue makes it difficult to provide multiple custom answers in the "Other" field.

Although using a multi-select input could resolve this, if the creator intends to keep radio buttons with an "Other" option I think this is an issue in that scenario. Ideally, the "Other" field should allow users to type any custom response without automatically selecting predefined options.

This issue was encountered recently in the feedback form—side quest as well.

### Steps to Reproduce

Attached the video

### Expected behavior

It should allow any custom response.

### Screenshots

https://github.com/user-attachments/assets/41928400-c77c-4670-b60b-a86bafc21807

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: chrome
```

**Comment by jobenjada** [comment]
thats not a bug
