### ISSUE TITLE
[🕹️]Complete the feedback form

### ISSUE THREAD

**Issue by Student-PrangyaParamita** [formbricks/formbricks#4175]
### What side quest or challenge are you solving?

Feedback Fanatic side quest

### Points

150 Points

### Description

Fill out Feedback Form

### Provide proof that you've completed the task

![Uploading Screenshot 2024-10-31 110145.png…]()

**Comment by Student-PrangyaParamita** [comment]
![Screenshot 2024-10-31 110145](https://github.com/user-attachments/assets/7ab1abd1-94e2-478f-9182-1e3bc3acedd8)

**Comment by jobenjada** [comment]
youre not a registered player it seems
