### ISSUE TITLE
[FOR-808] [FEATURE] Add weekly summary functionality

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#418]
**Is your feature request related to a problem? Please describe.**
In Formbricks we currently have email notifications that notify the user of every new response to a survey. Our users have asked for a weekly summary that gives them an overview of what has happened in their project over the past week.

**Describe the solution you'd like**
In the notification settings in Formbricks, a user can opt-in to the weekly recap for each product they are a part of.
Every Monday at 12pm PDT, they will receive an email for each project that has opted in to the weekly recap with an overview of what has happened in the last 7 days.

![](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/ebf4f643-b5d6-4464-af04-7e34b85faf1e/85b50c5e-eb89-4a1b-89d8-fe5a0fe8e110)

The email contains 3 elements: Big Picture Insights and the most recent response per active survey.

Big Picture Insights:

* Count of live surveys
* Count of total displays
* Count of total responses
* Count of completed responses
* Overall completion rate

Logic: 

The Weekly Summary will be sent out once a week. The content is dependent on the following condition:

If the production environment in the Product has any survey which has a response that is 6 days or younger, display it in the summary. Include all surveys which have a response which is 6 days or younger.

In all other cases display the NO LIVE SURVEY content (see below).

Mail Subject: "*Product Name* User Insights - Last Week by Formbricks"

---

Please update the UI and data handling in the Formbricks settings to allow users to opt-in to the weekly summary for different projects on their teams.
Please build an API endpoint (using Next.js route handlers in the app directory) that can be called every Monday at 12pm PDT (we will handle the cronjob in a separate ticket) and send out all weekly summaries for all projects and their subscribers.

The current email functionality for sending notification emails can be found in `apps/web/lib/email/email.ts`.
Please also make sure that the endpoint is secured and cannot be called by unauthorized callers.

<sub>From [SyncLinear.com](https://synclinear.com) | [FOR-808](https://linear.app/formbricks/issue/FOR-808/[feature]-add-weekly-summary-functionality)</sub>

**Comment by Pradumn27** [comment]
Hey @mattinannt can you assign me this feature?

**Comment by mattinannt** [comment]
@Pradumn27 Thank you for your enthusiasm 💪🎉, but this ticket was written for another contributor who wanted to take on the challenge 😊.

**Comment by singhbhaskar** [comment]
Hi @mattinannt ,

Can you assign this ticket to me?

**Comment by singhbhaskar** [comment]
Hey
What do you mean by this statement, can explain what's the requirement here?

> If the surveys the account manages does not have received any response yet: Send a reminder which contains the name of the started survey and a CTA to complete it

**Comment by singhbhaskar** [comment]
Hi,
Can you also tell the Email subject for reminder notification?
Also will this part of the same API which will send out weekly summaries or a different API? Because from one API request we would be sending 2 different emails at the same time. We wouldn't have any control over the second email notification for reminder like frequency of this email.

Also I can see that in notification settings there only 2 buttons for notification one for survey responses and another for weekly updates and not button for reminders.

**Comment by jobenjada** [comment]
Subject: "Product Name: Weekly Report" 
Usethis subject line for the Weekly Report, no matter of the content.

I think I didnt explain the logic well:

The Weekly Summary will be sent out once a week. The **content** is dependent on the following conditions:

If the `production environment in the Product` has any survey which has a response that is 6 days or younger, display the summary. Include all surveys which have a response which is 6 days or young. 

In all other cases display the NO LIVE SURVEY content (see below). 

When you write this check you can check if there is a survey of status `inProgress`, `completed` or `paused` and if not, you can jump to the next condition. 

Here is the updated mockup for the case "NO LIVE SURVEY":
![grafik](https://github.com/formbricks/formbricks/assets/72809645/64a2068f-3191-432a-aaab-984cf6ef37e5)

Here is the text:

´´´
We’d love to send you a Weekly Summary, but you currently there are no surveys running for *PRODUCT NAME*. 

Don’t let a week pass without learning about your users.

BUTTON: Setup a new survey

Need help finding the right survey for your product?

Pick a 15 minute slot with in our CEOs calendar or reply to this email :)

All the best 
The Formbricks Team
´´´

Does this make it more clear?

**Comment by singhbhaskar** [comment]
Thanks. This make alot of sense now.

**Comment by jobenjada** [comment]
hey @singhbhaskar 

Thanks a lot for your contribution - I finally had some time to review the UX of it. Here is my feedback:

1. UI: I have updated the UI to make more sense. Sorry this should've come at the beginning of the issue:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/6bcea18a-55c6-4602-a4f1-fab5a1cd782e)

Here is the branch: https://github.com/formbricks/formbricks/tree/Feat-FOR-808-add-weekly-summary-functionality

I think you have built the endpoint correctly (one weekly summary per Product, **not** one weekly summary per Survey).

2. Loading Time: The endpoint loads quite a long time (1min+) - where do you see potential to update this?
3. Update the subject line for the NO SURVEY LIVE: Keep the same subject line as if the summary has a survey

Hope this makes sense!

Thanks a lot 🙏 😊
