### ISSUE TITLE
[BUG] Cannot save "Schedule a meeting" with self hosted Cal.com instance 

### ISSUE THREAD

**Issue by SystemFuchs** [formbricks/formbricks#4183]
### Issue Summary

When entering the slug & the hostname the correct preview is rendered. When i try to save I'm getting an error:

```Question no x must have a valid hostname```

The URI of the selfhosted instance is calcom.cloud-fuchs.de

### Steps to Reproduce

1. Add question type "Schedule a meeting"
2. Enter event
3. Enter the mentioned URI & try to save

### Expected behavior

I'm able to save the existing correct self hosted cal.com instance 

### Screenshots
![image](https://github.com/user-attachments/assets/74ef3272-0aca-4718-bdf6-08d373722c20)
_No response_

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [x] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: docker compose (latest)
- Node:
- npm:
```

**Comment by pbmagnet4** [comment]
Was this ever resolved? I am having the same issue.e

**Comment by gupta-piyush19** [comment]
@pbmagnet4 We fixed this issue on formbricks cloud; you'll get the change in our next release.

**Comment by gupta-piyush19** [comment]
Hey! I checked this again; we pushed this fix in the last release; you can update your instance to see the change. Please follow our updation guide to do the same.

**Comment by SystemFuchs** [comment]
I can confirm that the feature is working now 🙌

**Comment by pbmagnet4** [comment]
@gupta-piyush19 
interesting - i am on 2.7.1 and am still getting the issue. i will update and see if that fixes things.

**Comment by pbmagnet4** [comment]
![Image](https://github.com/user-attachments/assets/3226d091-b988-43e0-bcc7-961c611e928a)

**Comment by pbmagnet4** [comment]
[_Formbricks_logs (1).txt](https://github.com/user-attachments/files/18011208/_Formbricks_logs.1.txt)

**Comment by gupta-piyush19** [comment]
Did you run all the data-migrations correctly? please try deleting local storage and cookies then try again.

**Comment by pbmagnet4** [comment]
@gupta-piyush19 
Started with a fresh install just the other day. Not sure if that is the issue here. Ill have to look further into this. Thank you
