### ISSUE TITLE
[BUG] Date Picker Selected Month.  

### ISSUE THREAD

**Issue by SaiSawant1** [formbricks/formbricks#4190]
### Issue Summary

When selecting a month in data-picker, the selected month's background and text go white and is only displayed if hovered over it.  

### Steps to Reproduce

1. In edit go to settings
2. Under response options click on survey release date
3. select a month and date.
4. change the month.

### Expected behavior

Should highlight text selected month as it does for the selected date.

### Other information

I worked on that component when it was broken earlier. I don't know what broke it but I am happy to fix it. It would require a little bit of time since I have exams.

### Screenshots

![swappy-20241031_160043](https://github.com/user-attachments/assets/219806e8-24cc-4a94-b516-a3f8d5871bcc)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by jobenjada** [comment]
/award 100 thanks - can you fix it?

**Comment by SaiSawant1** [comment]
@jobenjada , happy to fix it.
