### ISSUE TITLE
[🕹️]

### ISSUE THREAD

**Issue by Kuzuri247** [formbricks/formbricks#4205]
### What side quest or challenge are you solving?

Feedback fanatic sidequest

### Points

150

### Description

Completed the feedback form fanatic task  

### Provide proof that you've completed the task

![Screenshot 2024-10-31 194430](https://github.com/user-attachments/assets/6bd7af83-1cbd-4c95-9719-f59193607825)

**Comment by Kuzuri247** [comment]
@jobenjada

**Comment by jobenjada** [comment]
you hardly played, cant provide feedback :(
