### ISSUE TITLE
[FEATURE] Allow aliases for filtering responses

### ISSUE THREAD

**Issue by ratte1303** [formbricks/formbricks#4213]
### Is your feature request related to a problem? Please describe.

When filtering the responses it is inconvenient to only be able to filter results by question name and not by an alias. 

### Describe the solution you'd like

Add option to set an alias for a question. This alias is then used inside the repsonses tab instead of the full question for better usability.

**Comment by jobenjada** [comment]
hey!  why is it inconvenient? can you share more details? an alias might complicated things so maybe there is another solution. the better we understand the problem, the easier to brainstorm other solutions :)
