### ISSUE TITLE
[FEATURE] why no n8n trigger?

### ISSUE THREAD

**Issue by dg9999cn** [formbricks/formbricks#4217]
### Is your feature request related to a problem? Please describe.

I see you docs. n8n have trigger of formbricks. 
but Why I can't find it in n8n?

### Describe the solution you'd like

I see you docs. n8n have trigger of formbricks. 
but Why I can't find it in n8n?

**Comment by jobenjada** [comment]
hey! 

n8n is a bit annoying with how they handle their nodes. if you can get us listed there, that'd be super appreciated!

**Comment by dg9999cn** [comment]
I found how to do it now. 
I need to go to Settings -> Community Nodes -> Install @formbricks/n8n-nodes-formbricks. 
It's not straightforward.
