### ISSUE TITLE
[FEATURE] Expand the options for time periods in filters

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#4218]
### Is your feature request related to a problem? Please describe.

Currently, we only offer these
<img width="193" alt="image" src="https://github.com/user-attachments/assets/c2033026-1295-4b66-bc8d-a6db32eb95e9">

### Describe the solution you'd like

Augment them to add the following:

This month (note: not 30 days, actual month)
Last month (note: not 30 days, actual month)
This quarter
Last quarter
Last 6 months 
This year
Last year

**Comment by khAja13** [comment]
@jobenjada can you please tell me on how to get that offers dropdown?

**Comment by khAja13** [comment]
Found it @jobenjada does it has to change for both summary and responses?

**Comment by khAja13** [comment]
@jobenjada can you please review the PR? Thank you.

**Comment by khAja13** [comment]
Also fixes: #4226 

This is how it will if someone opens the modal, added padding and made autofocus on the tabs

![image](https://github.com/user-attachments/assets/dc58a85e-073e-4491-b04c-934af65a3c1a)
