### ISSUE TITLE
[FEATURE] Filter by Date Range

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#422]
**Is your feature request related to a problem? Please describe.**
As a user I can only see all submissions at once.

**Describe the solution you'd like**
Allow filtering by date range. A mockup:

![grafik](https://github.com/formbricks/formbricks/assets/72809645/38e48595-df93-45f4-99ea-f159bbf96578)

**Tasks**
1. Write a new component which is implemented in both Summary and Responses. Embed this component in both the Summary and Responses tab. It contains the following:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/97685996-c038-4d58-a146-a576b375c594)
Date Range dropdown (to be written), Revamped Download Button (to be written), Share Btn, Survey Status Dropdown and Edit Btn
3. Create Date Range Dropdown:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/29d22276-043a-4116-95c8-1d4be45ac24e)

The first two options are self-explanatory.

On "Custom Range..." the [shadcn date range picker](https://ui.shadcn.com/docs/components/date-picker) opens. 
- Create a new component in formbricks/ui package
- The date range picker replaces the open dropdown so it is placed directly under the Select field.
- When the second date is selected, the range picker closes and the responses are filtered accordingly.
- The Select looks as follows:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/9cb6f80b-c67e-4989-9219-fae9254de2f7)
- On click, the same dropdown opens again (Last 7 days, last 30 days, Custom Range...)

4. Create Download Dropdown:
- Remove the "Export to CSV" Button from the Responses page
- Create a Select field which opens on click on the Download icon:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/dca49112-9dea-4f49-86f5-6574c603914f)

The two actions are self-explanatory :)

Thanks a lot! 🙌

**Comment by Pradumn27** [comment]
Hey @jobenjada , can you assign me this issue?

**Comment by joe-shajan** [comment]
Hey, @jobenjada can I work on this? or is this specifically for gitstart users

**Comment by jobenjada** [comment]
its live now
