### ISSUE TITLE
[BUG]:people/[personId] page client side error

### ISSUE THREAD

**Issue by SaiSawant1** [formbricks/formbricks#4231]
### Issue Summary

in people, a client-side error occurs when clicking on a single user inside the table to navigate to the people/[personId] page.

### Steps to Reproduce

1. go to people
2. click on any value of the table.

### Expected behavior

render the page.

### Other information

I would love to fix it.

### Screenshots

https://github.com/user-attachments/assets/32682597-cdde-4b8c-81d2-94d59bb62dcf

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by jobenjada** [comment]
uh thanks for flagging, we'll look into it!
