### ISSUE TITLE
Caching not disabled for formbricksDebug

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#4238]
### Issue Summary

A Discord user mentioned that changes to surveys and the product took around 20minutes to be reflected in the own app using `@formbricks/js`; even with `?formbricksDebug=true`

<img width="1001" alt="image" src="https://github.com/user-attachments/assets/728f5ca4-22f0-4d2a-bf1b-08fe78b42c3b">

Please try to reproduce the issue and find out what caching is causing the delay.

### Your Environment

None

**Comment by gupta-piyush19** [comment]
Hey! It is working fine for me. 
`formbricksDebug=true` sets the cache to `no-cache` and shows updated results instantly.
and `formbricksDebug=false` caches the data for 600s(10mins). 

https://github.com/user-attachments/assets/280ac8dd-f7b5-41f6-9c11-0638dcb00e8a

@jobenjada  Can you please provide some more context to debug the issue further?
