### ISSUE TITLE
[BUG] Unable to see Title in a form with long description

### ISSUE THREAD

**Issue by niteshseram** [formbricks/formbricks#427]
### Issue Summary
I have created a form where there is a description which has a very long description. When I viewed that form, I am unable to see the title at the top. It is getting hidden at the top.

(Write your answer here.)

### Steps to Reproduce

1. Create a survey form with a question title and description
2. Give a very long description
3. Publish the survey
4. View the survey 
5. You won't be able to see the Question title
### Expected behavior
It should be scrollable and the title shouldn't be hidden at the top

#### Screenshots
https://app.formbricks.com/s/clivvfkvx0usomx0htzg5g7u7

#### Environment

- [x] Formbricks Cloud (app.formbricks.com)
- [ ] self-hosted Formbricks, version/commit: [please provide]

#### Desktop (please complete the following information):

- OS: Windows 11
- Browser: Chrome
- Version 114.0.5735.134

**Comment by niteshseram** [comment]
Can I fix this?

**Comment by jobenjada** [comment]
You got it ;) Make sure to test your fix:

- in the survey editor
- in link surveys
- in in-app surveys

Thanks a lot!

**Comment by jobenjada** [comment]
@niteshseram are you still working on this? :)

**Comment by niteshseram** [comment]
I am almost half way there @jobenjada. I have been very busy from last week so couldn't work on it.
