### ISSUE TITLE
Upgrade 2.6 to 2.7: Access Lost

### ISSUE THREAD

**Issue by tobru** [formbricks/formbricks#4278]
### Issue Summary

After upgrading from 2.6 to 2.7 I lost access to products:

```
Your account doesn't have access to any products yet.

Reach out to your organization owner to get access to products. Or create an own organization to get started.
```

Before, I had access to this data with the same account I'm using now.

### Your Environment

Self-hosted Formbricks

**Comment by mattinannt** [comment]
We are currently working on a new automatic upgrade process and will release it with Formbricks 3.0 in the near future :-)
