### ISSUE TITLE
Show multiple times functionality is not working

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#4282]
### Issue Summary

Users are reporting that the "Show multiple times" functionality is not working properly

![image](https://github.com/user-attachments/assets/9fd91c42-3147-4411-8d94-b4a9e22e0415)

_"I've tested this settings, the survey appeared in all connected test projects. In one of them, I tried closing the survey to make sure it would only show up 4 times, but it showed up again and again. After a few hours, the survey disappeared from all projects, even those where I didn't close it."_

### Your Environment

Formbricks Cloud (app.formbricks.com)

**Comment by pandeymangg** [comment]
> @mattinannt can you please let me know where can i find the UI of this exactly?
> 
> Thanks

you can find it under the "Recontact Options" in the survey editor settings

**Comment by mattinannt** [comment]
Please test with and without debug mode to make sure it doesn't depend on the network cache

**Comment by dhruv1707** [comment]
@pandeymangg @mattinannt 
this is what i am seeing in the editor settings:
![Image](https://github.com/user-attachments/assets/dfd257be-92fe-44d4-b6ac-2838a489bb16)

Could you please maybe send the exact screenshot of where it can be located?

**Comment by mattinannt** [comment]
> [@mattinannt](https://github.com/mattinannt) can you please let me know where can i find the UI of this exactly?
> 
> Thanks

The UI is in the survey editor. When App & Website surveys are selected you can see the "Recontact Options" below the survey type card.

![Image](https://github.com/user-attachments/assets/b39dde36-20c9-4910-be72-d54a6ecd1fdb)

**Comment by dhruv1707** [comment]
@mattinannt is this still a bug or it was resolved?

**Comment by dhruv1707** [comment]
@mattinannt just following up here :)

**Comment by pandeymangg** [comment]
@dhruv1707 thanks for your investigation on the issue, this is also what I found in my testing as well, the feature works fine for me, I tested with both network cache enabled and disabled and it seems to work fine everytime, closing this for now
