### ISSUE TITLE
Error after doing clean reinstall

### ISSUE THREAD

**Issue by gltched-usr** [formbricks/formbricks#4284]
### Issue Summary

Today I decided to reinstall my formbricks instace. I deleted the volumes and all their data, pulled the latest image version and updatd the `postgres:15-alpine` to `pgvector/pgvector:pg15`. 

But after starting the docker compose stack I get this error when opening the page:
```
Falling back to LRU handler because Redis client is not available.

You haven't read the `locale` param that was passed to `getRequestConfig` and also haven't returned one from the function. This is likely an error, please ensure that you're consistently using a setup with or without i18n routing: https://next-intl-docs.vercel.app/docs/getting-started/app-router

Unable to find `next-intl` locale because the middleware didn't run on this request. See https://next-intl-docs.vercel.app/docs/routing/middleware#unable-to-find-locale. The `notFound()` function will be called as a result.
```

### Your Environment

Self-hosted Formbricks

**Comment by mattinannt** [comment]
Thanks for raising an issue for this. Is the page still loading correctly or also showing an error?

**Comment by khAja13** [comment]
@gltched-usr @mattinannt Even I received this error today morning, I have done everything I could do but nothing worked. And then at last opened in incognito, then it worked fine.

**Comment by mattinannt** [comment]
Maybe you still have cookies in your browser from your last install. Can you try to delete your browsers site storage in the browsers inspect window?

<img width="531" alt="Screenshot 2024-11-11 at 17 38 19" src="https://github.com/user-attachments/assets/24b008a1-0b09-4cdc-9a51-688a942e1241">

**Comment by hassansaadat** [comment]
> Maybe you still have cookies in your browser from your last install. Can you try to delete your browsers site storage in the browsers inspect window?
> 
> <img alt="Screenshot 2024-11-11 at 17 38 19" width="531" src="https://private-user-images.githubusercontent.com/675065/384998019-24b008a1-0b09-4cdc-9a51-688a942e1241.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTQyMzEsIm5iZiI6MTczMTg1MzkzMSwicGF0aCI6Ii82NzUwNjUvMzg0OTk4MDE5LTI0YjAwOGExLTBiMDktNGNkYy05YTUxLTY4OGE5NDJlMTI0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxNDMyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTBmYWRjYWFlOTMzYzVlNWQ1MDhlMzQ2MTM4OGEwNmU4ZjJkNmI2MDA4ZDIyM2NjNGFkYzY1NzIyNTllMWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ViEZqqs6H3gP-s4fFbUZuU48w7Nl-AQO9ZMDPdIBXGo">

This worked for me! Thanks.
