### ISSUE TITLE
Letters outside a-z not allowed in name

### ISSUE THREAD

**Issue by filiabel** [formbricks/formbricks#4324]
### Issue Summary

Names with e.g. Norwegian letters `æøå` letters is not allowed, as set up in [Zod schema](https://github.com/formbricks/formbricks/blob/762a3ca6264600309786ea285a5eeef22ef1483b/packages/types/user.ts#L29) with regex `/^[a-zA-Z0-9\s]+$/`. This would apply to all letters with accents etc. as well.

Is this intentional?

### Expected Behavior

I would assume all "normal" letters that you can find in names should be allowed?

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

Names are fetched from Microsoft Entra/Azure AD. Discovered when coworker with `æ` in name could not log in.

Docker logs:
```js
[
	{
		validation: 'regex',
		code: 'invalid_string',
		message: 'Name should only contain letters, numbers, and spaces',
		path: ['name']
	}
];
```

### Your Environment

Self-hosted Formbricks

**Comment by Dhruwang** [comment]
Hey @filiabel , thank your for reporting this issue, we now have a PR fixing this (#4328 ), should be fixed soon 😊
