### ISSUE TITLE
[UX BUG] Teams not clickable

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#4331]
### Issue Summary

Teams are not clickable in Organization > Teams. The rows should link to /environments/{environmentId}/settings/teams/{teamId}

![Image](https://github.com/user-attachments/assets/286eaff6-bead-4874-825b-aca178236088)

### Expected Behavior

You can easily edit teams by clicking on the Team name in the Organization > Teams overview.

### Your Environment

Self-hosted Formbricks

**Comment by jonas-hoebenreich** [comment]
PS: "1 Members" is grammatically wrong ;)

**Comment by dhruv1707** [comment]
@jonas-hoebenreich this is what i see on my end :) 

I don't see any teams option?

![Image](https://github.com/user-attachments/assets/0f8c999a-0325-4557-91b8-2cbc3e827fe6)

**Comment by mattinannt** [comment]
Issue will be closed today with the merge of https://github.com/formbricks/formbricks/pull/4448
