### ISSUE TITLE
[FOR-819] [FEATURE] Extensive Filtering of Responses

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#434]
**Is your feature request related to a problem? Please describe.**

As a user I cannot filter my submissions based on tags, user-attributes or answers to questions

**Describe the solution you'd like**

Comprehensive filtering

**Tasks**

This is what we're building:

![](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/6eab51cf-b2d8-43c8-ba74-000ac8b133ac/c806f711-6403-4f81-b50f-db48fa2828d2)

**Notes**

* To build this UI, you have to reorganize the Summary and Responses pages so that the filter applies to both lists. Please follow next.js best practices :)
* We're in the process of reworking our data handling in the app. We've already applied the new way of pulling data in the Summary and Response pages, just FYI.
* Please filter the responses in a client component in the browser. We get all responses from the server and then would like to filter these responses on the client based on the filters selected.
* In a previous ticket, GitStart built the Date Range Picker. **(PR currently in review)**
* It doesn't have to be pixel-perfect. For colors, always choose `slate`
* UI components you find in `formbricks/ui` and if you need something else use [shadcn UI](https://ui.shadcn.com/docs/components/accordion)
* Please make sure the filtering works in accordance with the Date Range Select
* Please make sure its responsive.

---

**Let's dive in 👇**

**It works as follows:**

**"Filters":** Toggles the large gray rectangle on and off

The filtering itself is done in Filters which consists of two Input fields:

![](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/fbdbbf1a-024d-4ab4-b70e-8bb33b2ffcea/196497ff-7fe0-45d8-b1bc-16ca8959ac4e)

`Add filter` adds a new Filter

`Clear all` removes all filters

Let's look at the filter in more detail. The first field looks like this:

![](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/ec8d5cc1-0d89-4014-ad20-a17351cd2e0c/5f682ace-1b96-4cc2-a67e-c7892e1f1fb8)

The Dropdown contains three sections for now: Questions, Tags and User Attributes

At the top of the Selection is a Search Bar. Adjust [shadcn ComboBox](https://ui.shadcn.com/docs/components/combobox) from formbricks/ui

**Questions:** In the Questions Section all questions of the current survey are listed. The type of the question is indicated by the icon. The label is the actual question (like in the first line of the screen shots). The question type is indicated by the icons which match the icons in the Survey Editor.

**User Attributes:** Will contain the attributes which were recorded during the submission of the response. In the data model of the response you'll find ab object called `personAttributes` which contains the user attributes recorded at the point of the submission. You'll need to write a function to gather all unique key:value pairs in the `personAttributes` object.

**Tags:** All tags. If the environment does not have tags yet, the category will be left out.

The second field: It's dependent on the Selection in the first field

![](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/9c756b55-03d2-4a63-a011-cfa56defbd57/364e96ca-5d7a-4457-8bf5-b67e789d4ddd)

**Open Text:** Select field with "Filled Out" and "Skipped"

**Single Select Type:** Combobox where several of the answers can be selected. Logical Connection is "OR"

**Multi Select Type:** The first half is a Select to choose between "AND" and "OR". The second half is a Combobox to select several of the Options

![](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/35a13a75-8259-4500-a6c0-542198373118/357018ea-1a91-4932-b259-2402ae6d1b51)

**NPS & Rating:** First half is a Select between the options mentioned: Is equal to, Is less than, Is more than, Submitted and Skipped. The second half is dependent on the Selection of the first: In the first three options, a Select field comes up where people can choose from the range of the question.

If "Submitted" or "Skipped" is selected, the second half is disabled / hidden.

Only display "Skipped" when the question is not required

**CTA Question Type:** Three way toggle between "Clicked", "Skipped" and "No value"

![](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/bd62decc-06a3-43f0-b654-db319ecb626f/60504a75-6702-4b98-be05-b81d256660df)

**Tags:** It's a Select with two fields. For simplicity we went with a Select instead of a Toggle.

**User Attributes:** Select with "Equals" and "Not equals" and a dropdown with all unique values recorded in all submissions meta objects:

**Responsiveness**

Please make sure that the filters are responsive:

![](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/ff249663-d1ea-48e1-b49a-1fc4b4b2fbad/085199a6-d957-475a-9d62-b08fdc69468a)

**Figma File:**

[https://www.figma.com/file/S7mYzd9PXHdT6s4uetkdTF/Filtering?type=design&node-id=6%3A251&mode=design&t=10G0J0hpTdjRm7ht-1](https://www.figma.com/file/S7mYzd9PXHdT6s4uetkdTF/Filtering?type=design&node-id=6%3A251&mode=design&t=10G0J0hpTdjRm7ht-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [FOR-819](https://linear.app/formbricks/issue/FOR-819/[feature]-extensive-filtering-of-responses)</sub>

**Comment by jaysoni-ash42** [comment]
@mattinannt  @jobenjada  i am from gitstart team currenlty working on this issue faced some blockers.

 
<img width="374" alt="Screen Shot 2023-06-30 at 17 40 54" src="https://github.com/formbricks/formbricks/assets/68722497/eb8e9b37-bc61-4734-ba3d-3c7dd9fa4beb">

1. on cta filtering when we post a response if it is clicked it gives the value to be "clicked" and for skipped it is "dismissed" but what is the case when it has no value 

<img width="298" alt="Screen Shot 2023-06-30 at 17 50 09" src="https://github.com/formbricks/formbricks/assets/68722497/e4ba136a-be59-418c-9170-3461f0d6e161">


2.   on desktop version it has three buttons share select and edit button but for mobile version in  figma it has three dots but there is no design on how it will look inside the dropdown so some rough design would be helpful 

3.i am trying to get the persons attribute in the response object but it has value undefined is there any other configurations that needs to be done to get the attribute .

**Comment by jaysoni-ash42** [comment]
@mattinannt  one more thing in question type rating and nps there is a field as submitted how would that work like it should filter out those reponse of rating and nps who have values?

**Comment by mattinannt** [comment]
> 

Yes, `submitted` leaves only the responses behind, that have a value in this nps/rating question
Yes, multiple choice single select only has the `Includes either` option which is not a dropdown / not changeable because it's the only option.
<img width="418" alt="Screenshot 2023-06-30 at 16 06 44" src="https://github.com/formbricks/formbricks/assets/675065/e4b690bc-2d54-4637-864d-10c84b1bf73d">

**Comment by jaysoni-ash42** [comment]
@mattinannt  i just checked there is a new question type named as consent form  so can i get the condition and option on how it can be filtered?

**Comment by jobenjada** [comment]
Hey @jaysoni-ash42 

Please follow this format:

![grafik](https://github.com/formbricks/formbricks/assets/72809645/bd525852-03ea-479a-84c0-3000d3968f1e)

![grafik](https://github.com/formbricks/formbricks/assets/72809645/8b08b15f-90aa-4756-b9a9-2e97f9e432f5)

Feel free to get back with open questions!
