### ISSUE TITLE
Add French translation

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#4368]
### Task description

The reviewed version of the French translation can be found here [Formbricks_fr-FR_2024-11-26.json](https://github.com/user-attachments/files/17921453/Formbricks_fr-FR_2024-11-26.json) as well as in Tolgee.

Please include the French translation to Formbricks and add the missing translation (fr-FR, formal) to the language file. Since the language file is based on an export that is two weeks old there might unfortunately be many keys that are missing.

**Comment by dhruv1707** [comment]
@mattinannt I made the changes to the language file and added the necessary translation. However, am I supposed to add all the keys in the JSON file manually or will, you be sending an updated one?

Thanks
