### ISSUE TITLE
Caching Issue Team Access Roles

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#4371]
### Issue Summary

After updating a user's permissions, the cache does not refresh correctly, causing the user to encounter an error message when attempting to access resources they should now have access to.

### Expected Behavior

Cache refreshed automatically.

### Your Environment

Self-hosted Formbricks

**Comment by mattinannt** [comment]
@gupta-piyush19 Can you please try to reproduce it and then fix the bug? :-)

**Comment by gupta-piyush19** [comment]
@jonas-hoebenreich, can you please provide some steps to reproduce this? Or is there any particular flow where I can see this issue?

**Comment by gupta-piyush19** [comment]
https://github.com/user-attachments/assets/eb481a0a-3686-4df2-b6c1-23e477099b0a

I tried updating the team role, and it is working fine; mainly, the team role differs in the team operations; please explain what issue you face exactly.

**Comment by mattinannt** [comment]
Closing this for now due to inactivity 😊
