### ISSUE TITLE
Impression count not updating with filters

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#4378]
### Issue Summary

Impression count is not correctly showing when choosing a time frame different from "All time".

![Image](https://github.com/user-attachments/assets/a130936c-751c-47aa-991c-efb5bb2c1579)

![Image](https://github.com/user-attachments/assets/b2110f92-80a7-4886-a45b-f383f69b239f)

### Expected Behavior

The Impression count should show correctly how many times the survey has been displayed in the selected time frame.

### Your Environment

None

**Comment by dhruv1707** [comment]
![Image](https://github.com/user-attachments/assets/0a0a4a6b-16a9-4aef-9363-06e6e874d1f2)

Hey @mattinannt I think it's showing correctly on my end! :)
