### ISSUE TITLE
URGENT Formbricks CSP is breaking embedded form

### ISSUE THREAD

**Issue by Sytten** [formbricks/formbricks#4385]
### Issue Summary

Check your own main site, the frame-ancestors is set tot `'none'` leading to CSP error:
```
Refused to frame 'https://app.formbricks.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```

### Your Environment

Formbricks Cloud (app.formbricks.com)

**Comment by Sytten** [comment]
This is the commit that broke it https://github.com/formbricks/formbricks/commit/a3bea3b7daf4d6321c70ee839b214fbcd000699b

**Comment by Sytten** [comment]
I guess its funny that a form business whose only job is to render the form has broken forms on its marketing site
![Image](https://github.com/user-attachments/assets/2e2405fa-8d75-4d40-91e0-de968fbcc37b)

**Comment by gupta-piyush19** [comment]
Hi, @Sytten! Thanks for opening the issue; we've fixed this and it works fine now.
Thanks 🙂
