### ISSUE TITLE
Deleting own user account always deletes whole organization

### ISSUE THREAD

**Issue by salim-b** [formbricks/formbricks#4419]
### Issue Summary

1. Create a new self-hosted Formbricks instance (community edition) and create your default admin user.
2. Invite a new user to your team (only role `owner` is possible in community edition).
3. Finish creation of the new user account and log in as the new user.
4. Logged in as the new user, go to `Account settings` and click `Delete Account`.

   The following disclaimer is displayed:

   ![Image](https://github.com/user-attachments/assets/a8662e4e-a9d0-4305-8415-50e50ab618e8)

5. Enter the new user's e-mail address and click `Delete`.

   Instead of just deleting the new user account, ***the whole organization together with all products and surveys is deleted***.

   On the Formbricks server's console, the following is printed (dunno if it's actually related):

   ```
   You haven't read the `locale` param that was passed to `getRequestConfig` and also haven't returned one from the function. This is likely an error, please ensure that you're consistently using a setup with or without i18n routing: https://next-intl-docs.vercel.app/docs/getting-started/app-router
   Unable to find `next-intl` locale because the middleware didn't run on this request. See https://next-intl-docs.vercel.app/docs/routing/middleware#unable-to-find-locale. The `notFound()` function will be called as a result.

   ```

### Expected Behavior

Only the user account should be deleted without deleting the organization.

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

Formbricks v2.7.2.

Possibly related to:
- https://github.com/formbricks/formbricks/issues/3936

### Your Environment

Self-hosted Formbricks

**Comment by mattinannt** [comment]
@salim-b Thanks for reporting this issue. This is definitely not what should happen. We will investigate the issue and also take a look at the implementation of the fix by @melvinjariwala
