### ISSUE TITLE
Janky Auto-Zoom Behavior in Contact Info Question on iOS

### ISSUE THREAD

**Issue by Risinggoblin** [formbricks/formbricks#4429]
### Issue Summary

When interacting with a Formbricks form on an iPhone, text input fields in the Contact Info question type exhibit unusual zoom behavior:

- The form randomly zooms in when a user manually taps on a text field or presses return to move to another field.
- This zooming does not occur when the cursor automatically enters the first text field upon pressing the “Start” button.
- Once the zoom-in occurs, the zoom level persists across subsequent questions, even when no text field is active.
- Manually pinching out restores the view to a clean and well-aligned state.

This inconsistent behavior makes the interface appear buggy and unpolished, disrupting the UX by hiding parts of the form

### Expected Behavior

The form should maintain a consistent zoom level throughout the interaction, defaulting to a visually clean and modern layout (similar to the pinched-out state as mentioned in last bullet point in the issue summary).

- Tapping on a text field or moving to the next field using the return key should not cause random zooming.
- The form should adjust smoothly to ensure the active text field is visible without obstructing other elements or requiring manual zoom adjustments.

### Steps to Reproduce

- Create a Contact Info question in Formbricks.
- Open the form on an iPhone using Safari.
- Start the form and note that the cursor automatically enters the first text field without causing any zoom issues.
- Manually tap a text field or press the return key to move to the next field.
- Observe the sudden and persistent zoom-in behavior.
- Manually pinch out and notice how the layout appears correct in this state.

### Other Information

Device: iPhone (tested on iPhone 13 Pro, iOS 17.1)
Browser: Safari, Chrome (latest versions)

### Your Environment

Formbricks Cloud (app.formbricks.com)

**Comment by mattinannt** [comment]
@Risinggoblin thanks for opening an issue for this :-) @Dhruwang will look into this and check for a quick solution to fix this :-)
