### ISSUE TITLE
[BUG] Wrong button label Cart Abandonment Survey

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#4447]
### Issue Summary

two times "Finish" label

<img width="745" alt="Image" src="https://github.com/user-attachments/assets/28480256-7669-47e3-8deb-95bcd0bf417e" />

### Expected Behavior

Back + Finish

### Your Environment

None

**Comment by Surajsuthar** [comment]
@jobenjada  can i take this??

**Comment by Dhruwang** [comment]
Sure, you can give that a try @Surajsuthar 😊
