### ISSUE TITLE
[BUG] Loading of response page gets stuck

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#4457]
### Issue Summary

some users experience and issue with the response list page data not getting loaded (even for as little as 25 responses). A hard reload solves the issue. Pls investigate.

### Your Environment

None

**Comment by gupta-piyush19** [comment]
@jobenjada, I am not able to reproduce this issue. It always worked fine for me. Tested for surveys with thousands of responses.
The reason for this could be the server latency or slow internet connection. Can you please help me reproduce this?
