### ISSUE TITLE
[FEATURE] Add example file for CSV import

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#4465]
### Is your feature request related to a problem? Please describe.

A user struggled to import contacts

### Describe the solution you'd like

1. Reduce the width of the modal
2. Let them download an example CSV

Use button type minimal:
<img width="670" alt="Image" src="https://github.com/user-attachments/assets/22d8eeba-2a02-437c-a9b7-e032defb1527" />

**Comment by SxxAq** [comment]
@jobenjada can i get the issue?

**Comment by jobenjada** [comment]
also, this should issue a toast or spin the icon or have some other feedback (right now it feels broken):

<img width="146" alt="Image" src="https://github.com/user-attachments/assets/b97cd5b3-b02a-43dd-9201-5510d7230190" />
