### ISSUE TITLE
"source" hidden field ID is not allowed

### ISSUE THREAD

**Issue by SimonChampetier** [formbricks/formbricks#4495]
### Issue Summary

i'am trying a "source" hidden field ID into my survey. For some reason it is not allowed and i have a " hidden field is not allowed" error message 

### Expected Behavior

possibility to add a "source" hidden field ID 

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

<img width="1380" alt="Image" src="https://github.com/user-attachments/assets/c52e89cd-5bad-4e4d-8cc4-282f56703edd" />

### Your Environment

None

**Comment by Dhruwang** [comment]
Hey @SimonChampetier , we use `source` as a query param in our link surveys and that is why it is not allowed as a hidden field 😊
