### ISSUE TITLE
[FOR-900] Group Events of same Type in Activity Timeline

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#453]
**Problem / Need**

As a user, I want to have an overview of the events tracked in the Acivity Timeline on the Person Detail page. The Exit Intent event spams the timeline.

**Describe the solution you'd like**

If the same event is fired repeatedly, group it and display a count indicator instead.

(see screenshot below)

**Tasks**

* If 3 or more events are of the same type, group them
* Show a count indicator
* Show the timeSince of the most recent event recorded

### How we code at Formbricks 🤓

* Everything is type-safe
* All UI components are in the package `formbricks/ui`
* Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
* We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

<sub>From [SyncLinear.com](https://synclinear.com) | [FOR-900](https://linear.app/formbricks/issue/FOR-900/group-events-of-same-type-in-activity-timeline)</sub>

**Comment by jobenjada** [comment]
@mattinannt kannst mal gucken warum das nicht bei GitHub landet?

**Comment by jobenjada** [comment]
![grafik](https://github.com/formbricks/formbricks/assets/72809645/285d4ebd-1781-49b7-98cb-3380fb5d1640)

**Comment by Ashutosh-Bhadauriya** [comment]
@jobenjada can you please assign this to me

**Comment by kuluruvineeth** [comment]
@mattinannt i have implemented this enhancement, please review and let me know if any changes are needed to be considered.

**Comment by jobenjada** [comment]
reopened issue for FormTribe Hackathon https://github.com/formbricks/formbricks/issues/1282
