### ISSUE TITLE
Remove Branding should hide logo in survey loading

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#4538]
### Task description

A customer pointed out, that even though remove branding is enabled, they still see the Formbricks logo in the survey loading screen.

<img width="581" alt="Image" src="https://github.com/user-attachments/assets/5242056f-b203-47d9-9259-01b4a041697d" />

Please only show this logo if Formbricks branding is enabled and hide it otherwise.

**Comment by vineeth-0509** [comment]
@mattinannt can u go throw my pr, may be it resolves the issue!!
