### ISSUE TITLE
[REFACTOR] Unify SingleResponse Card and increase UX

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#454]
**Is your feature request related to a problem? Please describe.**
Currently, the single response card on the Person Detail page differs from the single response card in the Responses tab in the survey summary. Furthermore, skipped questions are not displayed in a user-friendly way and the tagging functionality is missing on the Person Detail page.

**Describe the solution you'd like**
- Rework the data handling to the new Services
- Create one, reusable component
- Update the UX as suggested below
- Use [Server Components](https://nextjs.org/docs/getting-started/react-essentials#server-components) & [Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions). Use Client Components only when necessary.

## Rework data handling
We're moving to Services and we need a new Service that returns all responses per user called "getPersonResponses". You find "getSurveyResponses" in "package/lib/services/response.ts" which you can copy and adapt.
Please use a server action to mutate data (when creating a new responseNote).

## Rework data passed to component
Currently, the SingleResponse is passed a `data` object, a survey and an environmentId. It needs to be rewritten so that we can pass a `response` and a `survey` to the component for it to display the data. The `survey` object contains the questions and the environmentId for linking and the `response` object the answers and person details.

## Rework UI
Here is an overview of the elements the Single Response Card needs on the Response Tab:

![grafik](https://github.com/formbricks/formbricks/assets/72809645/e738fd75-efd3-4a6e-bd53-dc7d8c82ebf9)

- Respondent (id or email) or Anonymous (see SingleResponse.tsx)
- Date
- Delete icon
- Notes
- Tags

Here is an overview of the elements the Single Response Card needs on the Person Detail page:

![grafik](https://github.com/formbricks/formbricks/assets/72809645/5b25fc91-eb85-49cf-9beb-8d0e2de075b1)

- Survey Name (linked to survey summary)
- Date
- Delete icon
- Tags

Make sure to design the component accordingly with the necessary props.

For displaying the questions, there are several cases to consider. Here is a list:

1. Survey completed, all questions answered:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/0b9c4633-4567-4802-811e-9bfd34f0c11c)

2. Survey completed, one or some questions skipped in the middle. Please note that only **if there are two or more questions** skipped in a row, the icon will appear. It is the `chevrons-right` icon from the lucide icons package:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/1c615af4-4615-4c03-91b2-80d8f282551c)
![grafik](https://github.com/formbricks/formbricks/assets/72809645/879e00f4-210b-4b48-a1bf-74027e97bd68)

3. Survey completed and last question skipped:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/547000c7-7cae-4a79-9020-e4f47a44d38f)

5. Survey closed after filling question:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/dd2e3f58-b05c-4742-adbb-03792a810b3a)

7. Survey aborted after skipping question:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/83d7d7ec-cb32-46c1-9132-15f719ec16ac)

Please note that the `border-l` goes from `dashed` if the question is skipped to `dotted` if the survey was closed before

### How we code at Formbricks 🤓
- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by Dhruwang** [comment]
Would like to work on this!

**Comment by neilchauhan2** [comment]
@jobenjada would love to work on this, please assign this to me as discussed earlier.

**Comment by jobenjada** [comment]
@Dhruwang whats the status here? :)

**Comment by Dhruwang** [comment]
Yeah its still work in progress
