### ISSUE TITLE
[FEATURE] Update the page title with survey data

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#455]
**Is your feature request related to a problem? Please describe.**
So far, the page titles are always "Formbricks"
![grafik](https://github.com/formbricks/formbricks/assets/72809645/dbd7cf82-e913-4437-8c05-2233fcb97401)

**Describe the solution you'd like**
Update them sensefully. On the Summary page, add the current responses to the page title:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/6dfc7ed4-d0ef-4be7-b511-71723b87c4ca)

### How we code at Formbricks 🤓
- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by Dhruwang** [comment]
Would like to work on this !
