### ISSUE TITLE
[FEATURE] Close survey on specific date

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#456]
**Is your feature request related to a problem? Please describe.**
As a user I want to close a survey on a specfic date

**Describe the solution you'd like**
Close survey on specific date.

**Tasks**
Add "Close survey on date" toggle to Response Options. Use shadcn date picker to pick the date of closure.

Build an endpoint which is triggered by a CRON to close all surveys which are limited to a specific date.

We don't have a CRON yet but will build it soon :)

### How we code at Formbricks 🤓
- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by gupta-piyush19** [comment]
@jobenjada I'd like to work on this. Can you please assign this to me?
