### ISSUE TITLE
[FOR-914] Custom 'Survey Closed' message and CTA

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#457]
**Is your feature request related to a problem? Please describe.**
When a link survey is completed, respondents are faced with this screen:
![grafik (1)](https://github.com/formbricks/formbricks/assets/675065/4de383e3-9812-4618-a52e-78799d03dc2a)

**Describe the solution you'd like**
As a user I'd like to control the headline, subheadline, CTA text and link destination.

**Tasks**

* If  surveyType="link" add a Toggle called "Adjust 'Survey Closed' Message" with description "Change the message visitors see when the survey is closed." in the Response Options card.
* If it's active, display two input fields incl. description. Make sure to use the input field from formbricks/ui:
  * Headline
  * Subheadline

![grafik (2)](https://github.com/formbricks/formbricks/assets/675065/acd15bcb-0ab6-4818-b17b-f806affabb0e)

* Make sure these fields are pre-filled with the default values
* Update LinkSurvey component to display custom messages if set. If a Custom Survey Closed message is set, don't render the Create your own Button.

### How we code at Formbricks 🤓

* Everything is type-safe
* All UI components are in the package `formbricks/ui`
* Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
* We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

<sub>From [SyncLinear.com](https://synclinear.com) | [FOR-914](https://linear.app/formbricks/issue/FOR-914/custom-survey-closed-message-and-cta)</sub>

**Comment by Pradumn27** [comment]
I can take this up @jobenjada .
