### ISSUE TITLE
[REFACTOR] Rewrite Templates page to Server Components & Services

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#473]
**Is your feature request related to a problem? Please describe.**
The "Templates" page where you can select a template to create a survey with is using the old data handling.

**Describe the solution you'd like**
Please use the approach of Server-Components & Server-Actions to rewrite the Templates page at `/environments/[surveyId]/surveys/templates`

- Use our internal services for data fetching and data mutation at `packages/lib/services` - create new services or zod schemas if necessary.
- Server components are the default, only use client components if needed
- Use Server-Actions when data mutation is needed

See Next.js documentation for examples and explanations: https://nextjs.org/docs/getting-started/react-essentials

### How we code at Formbricks 🤓
- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by Ankur-Datta-4** [comment]
Hey @jobenjada, I'd like to work on this
