### ISSUE TITLE
[BUG] Display user email in Single Reponse view if available

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#477]
**Is your feature request related to a problem? Please describe.**
As a user seeing the user ID does not help me much:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/325cd208-5d71-49b6-a13f-853bd2ff1051)

**Describe the solution you'd like**
Display the user email if the user has the attribute `èmail` filled.

**Additional context**
This used to work before:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/b347e5e0-9eb6-46cf-b891-253972e50e22)

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by Dhruwang** [comment]
Would like to work on this !

**Comment by joe-shajan** [comment]
I would like to fix this issue. Can I get this assigned, @jobenjada?
