### ISSUE TITLE
[BUG] QuestionID field should not allow spaces

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#483]
### Issue Summary

![grafik](https://github.com/formbricks/formbricks/assets/72809645/4f216aab-4bd8-4747-b1e6-576134a1246f)

This field in Survey Editor -> Question Card -> Advanced Settings has no validation but the questionId can be used for link prefilling. Hence, it needs validation as follows:

- If the input string contains a space, change border color to red
- and disable button

Thanks!

**Comment by Meetcpatel** [comment]
Hi @jobenjada, can you please assign it to me?
I would like to work on it.

**Comment by Meetcpatel** [comment]
Hi, @jobenjada How is this?

border color in the video is `border-red-300`


https://github.com/formbricks/formbricks/assets/26919832/a2e34328-7f55-4745-a227-d28ff200e15a
