### ISSUE TITLE
[BUG] The Full Name, Product Name, and Team Name fields should not be empty.

### ISSUE THREAD

**Issue by shubhamkhunt04** [formbricks/formbricks#499]
### Issue Summary

The Full Name, Product Name, and Team Name fields should not be empty.

### Steps to Reproduce
![formbricks](https://github.com/formbricks/formbricks/assets/55044317/ee1e8006-efcd-43d3-9945-791a33722fce)

### Expected behavior

There should be no option for the user to leave the Full Name, Product Name, and Team Name fields blank.

#### Environment

- [x] Formbricks Cloud (app.formbricks.com)
- [ ] self-hosted Formbricks, version/commit: [please provide]

#### Desktop (please complete the following information):

- OS: iOS
- Browser: Brave
- Version: 1.52.129

#### Node.JS version

v18.15.0

**Comment by shubhamkhunt04** [comment]
Can someone please assign me this? I would like to work on this :))

**Comment by jobenjada** [comment]
You got it :) Please checkout how it was done here:

https://github.com/formbricks/formbricks/blob/main/apps/web/app/environments/%5BenvironmentId%5D/surveys/%5BsurveyId%5D/edit/UpdateQuestionId.tsx

**Comment by jobenjada** [comment]
Thanks a lot, great work! 🚀
