### ISSUE TITLE
[BUG] Optimize Update Operations to Avoid Unnecessary Network Calls

### ISSUE THREAD

**Issue by shubhamkhunt04** [formbricks/formbricks#503]
### Issue Summary

Currently, when a user clicks the "Update" button without modifying the existing value, an API call is triggered unnecessarily, resulting in redundant network requests. This can lead to increased network calls and potential performance issues. To enhance the user experience and minimize unnecessary calls, it would be beneficial to display a message to the user instead of making the API call in such scenarios. This improvement would optimize the update operations and reduce unnecessary network calls/network round trips.

### Solution

To optimize update operations and prevent unnecessary network calls, a potential solution is to implement data validation by comparing the existing data with the received server data. By performing this comparison, it is possible to determine if the data provided by the user is identical to the existing data.

If the data is found to be the same, instead of making an API call, a user-friendly message can be displayed to prompt the user to modify at least one field before proceeding with the update. The message can be tailored to each specific field, such as "Please modify the {fieldName} to proceed with the update."

By implementing this approach, the application can provide more meaningful guidance to the user, ensuring that update operations only occur when there are actual modifications. This helps reduce unnecessary network traffic and enhances the overall efficiency and performance of the application.

### Steps to Reproduce

![apicall](https://github.com/formbricks/formbricks/assets/55044317/5d0fce97-634d-4a5b-9fcf-d8572edf934a)

### Expected behavior

Before calling the API, it should first validate the current value against the old value and if the two are not the same, then it should call the API.

#### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] self-hosted Formbricks, version/commit: [please provide]

#### Desktop (please complete the following information):

- OS: iOS
- Browser: Brave
- Version: 1.52.129

#### Node.JS version
v18.15.0

**Comment by Dhruwang** [comment]
Or we can initially disable the button and enable it only when a change is made

**Comment by shubhamkhunt04** [comment]
Can someone please assign me this? I would like to work on this :))

**Comment by jobenjada** [comment]
Hey! Since it's related to the other issue, please solve both in one PR 🙌

**Comment by jobenjada** [comment]
Thanks a lot, great work! 🚀
