### ISSUE TITLE
[BUG] Padding on delete confirmation modal seems inconsistent

### ISSUE THREAD

**Issue by shubhamkhunt04** [formbricks/formbricks#504]
### Issue Summary

When we go to the Teams member section and click on the delete button, it will open the modal for delete operation confirmation, in that model the padding looks more as compared to the other modal

### Steps to Reproduce

![padding](https://github.com/formbricks/formbricks/assets/55044317/cf4d0912-6daa-4855-a18f-44b21cfcdc7c)

### Expected behavior

The padding should be the same for reusable modal component

#### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] self-hosted Formbricks, version/commit: [please provide]

#### Desktop (please complete the following information):

- OS: iOS
- Browser: Brave
- Version: 1.52.129

#### Node.JS version
v18.15.0

**Comment by shubhamkhunt04** [comment]
Can someone please assign me this? I would like to work on this :))

**Comment by jobenjada** [comment]
Thanks for spotting this :) Please add it to the same PR like the other two issues to keep our reviewing overhead small ;)

Thanks!!

**Comment by jobenjada** [comment]
Thanks a lot, great work! 🚀
