### ISSUE TITLE
[FEATURE] GitPod One Click Setup

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#509]
**Is your feature request related to a problem? Please describe.**
Running Formbricks on GitPod is not working out of the box:

![grafik](https://github.com/formbricks/formbricks/assets/72809645/cfdb0656-be3c-4b48-a4ad-1d2c91279a32)

**Describe the solution you'd like**
As a developer I'd love to use GitPod to run Formbricks with one click.

**Additional context**
Ideally, it also works for GitHub Code Spaces :)

**Comment by Ashutosh-Bhadauriya** [comment]
@jobenjada please assign me this 🙂

**Comment by Ashutosh-Bhadauriya** [comment]
Hi, So following the development setup guide given in docs, the project starts to run, but while email verfication instead of the URL provided by the github, it takes us to the localhost. 

Workaround:
It works if we manually replace the localhost url with the one provided by gitpod.

What do we need:
It should automatically replace the localhost url with the one provided by gitpod.

**Comment by Palanikannan1437** [comment]
> Workaround:
> It works if we manually replace the localhost url with the one provided by gitpod.

Hey @Ashutosh-Bhadauriya, a Gitpod Hero here 👋, this can be easily done via shell scripting using Gitpod CLI, please let me know if you have any queries on the exact implementation details 🙌

**Comment by Palanikannan1437** [comment]
Hey @Ashutosh-Bhadauriya, it'd be really awesome if you could open up a PR and we could test, debug and collaborate on more things over there! 🙌

**Comment by Ashutosh-Bhadauriya** [comment]
Hey Palani, nice to meet you 🙂 Yes, I'm doing the changes in gitpod.yml. Thanks a lot will raise a pr soon 🚀

**Comment by Ashutosh-Bhadauriya** [comment]
@Palanikannan1437 I had raised the pr, can you please take a look when you get a chance.

Also, how can I test these changes on gitpod, is it possible to open this branch in it and it performs the tasks provided in gitpod.yml automatically?

Please also let me know the next steps to change the default url's to one provided by gitpod while email verification

**Comment by Ashutosh-Bhadauriya** [comment]
Figured out the first part, but I guess pnpm install not working 

![image](https://github.com/formbricks/formbricks/assets/62984427/65acf02a-ae5a-4d30-9539-dfed90fc569d)

**Comment by Ashutosh-Bhadauriya** [comment]
@Palanikannan1437 I'm encountering an issue related to the database. I suspect the problem might be associated with the port selection. Presently, I've set port 5432 for the database (in gitpod.yml) as it's the designated port for its operation. However, I'm uncertain as to what's causing the problem.

![Screenshot (4)](https://github.com/formbricks/formbricks/assets/62984427/24f41207-b33b-4e3f-8fa4-b63a46c0ba2a)

**Comment by Palanikannan1437** [comment]
> @Palanikannan1437 I had raised the pr, can you please take a look when you get a chance.
> 
> Also, how can I test these changes on gitpod, is it possible to open this branch in it and it performs the tasks provided in gitpod.yml automatically?

Hey @Ashutosh-Bhadauriya, let's continue the discussion on your PR, but yes, you can test out changes to gitpod.yml using "gp validate" command in your terminal

https://www.gitpod.io/docs/references/gitpod-cli#validate
