### ISSUE TITLE
[FEATURE] "pnpm go" as initial prompt to set up & start dev environment

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#510]
**Is your feature request related to a problem? Please describe.**
As a developer I want to get rolling with Formbricks as easily as possible.

**Describe the solution you'd like**
Enable new developers to set up and start the whole environment with one command: `pnpm go`

It should include:

- Start the database in Docker (currently done as a manual step)
- Migrate db (currently done as a manual step)
- Start Formbricks app (without the demo app)

Here [is how Cal does it](https://github.com/calcom/cal.com/blob/main/packages/prisma/package.json) with their `yarn dx` command in the prisma package:

```  "scripts": {
    "clean": "rm -rf .turbo && rm -rf node_modules",
    "db-deploy": "yarn prisma migrate deploy",
    "db-migrate": "yarn prisma migrate dev",
    "db-nuke": "docker compose down --volumes --remove-orphans || docker-compose down --volumes --remove-orphans",
    "db-reset": "run-s db-nuke db-setup",
    "db-seed": "yarn prisma db seed",
    "db-setup": "run-s db-up db-deploy db-seed",
    "db-studio": "yarn prisma studio",
    "db-up": "docker compose up -d || docker-compose up -d",
    "dx": "yarn db-setup",
    "generate-schemas": "prisma generate && prisma format",
    "post-install": "yarn generate-schemas",
    "seed-app-store": "ts-node --transpile-only ./seed-app-store.ts",
    "delete-app": "ts-node --transpile-only ./delete-app.ts",
    "seed-insights": "ts-node --transpile-only ./seed-insights.ts"
  },
```

**Comment by Dhruwang** [comment]
Would like to take this up 🤗

**Comment by mattinannt** [comment]
@Dhruwang awesome, thank you 💪 I assigned the issue to you 😊🚀
