### ISSUE TITLE
[FEATURE] filter responses by "completed only"

### ISSUE THREAD

**Issue by PeerRich** [formbricks/formbricks#513]
![CleanShot 2023-07-10 at 14 49 27@2x](https://github.com/formbricks/formbricks/assets/8019099/a5f5e6f2-4670-4783-a1b0-b7b3d7f8296d)

**Comment by mattinannt** [comment]
@PeerRich PR for this ( https://github.com/formbricks/formbricks/pull/474 ) is currently in Review and will be merged within the next few days 😊💪
