### ISSUE TITLE
[Improvement] Relocate Files from components to app directory

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#527]
**Is your feature request related to a problem? Please describe.**
In the previous versions of next.js pages went into the `/pages` directory and by convention if you build components you put them into a `/components` folder.
But with next.js 13 and the app directory you can put all the components next to the pages in the `app` directory to have everything at one place and show where these files are used. It's a much cleaner approach.
We already store our reusable UI components in `packages/ui` and for us currently there isn't much need for `components` directory, but we still have files there.

**Describe the solution you'd like**
We still have a lot of files in the `apps/web/components` folder. Please move them into the `apps/web/app` directory into the routes where they are needed / referenced.
In an ideal world, we can get rid of the `components` folder completely 😊

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by singhbhaskar** [comment]
Hey
Can I pick this up?

**Comment by mattinannt** [comment]
@singhbhaskar Sure, thank you 😊💪 I assigned the issue to you 😊
The `/components/shared` folder is more complex than the others as we maybe need to put some of these components into `packages/ui` or other places. Maybe it makes sense that you first raise a PR without cleaning the `shared` folder so we can make progress faster 😊

**Comment by Anshul1811** [comment]
Hi @mattinannt , is the issue still open ? I would like to work on this .

**Comment by mattinannt** [comment]
@Anshul1811 Bhaskar assigned the issue a few weeks back.

@singhbhaskar what's the current status? 😊🤗

**Comment by singhbhaskar** [comment]
Hi @mattinannt ,
I have moved `/components/shared` to `/app/shared`. Doing some testing.

**Comment by singhbhaskar** [comment]
Hi @mattinannt ,
Raised the PR for first set of changes to move `/components/shared` to `/app/shared`.

**Comment by Vishrut19** [comment]
Is anyone working on it? Or can I work on it?

**Comment by mattinannt** [comment]
@Vishrut19 we already have a PR for it by @ShubhamPalriwala . But we need to do some adjustments because we ran into a lot of merge conflicts with it.
But Shubham will take care of it 😊

Starting tomorrow we will release a lot of new tickets for our FormTribe hackathon 😊

**Comment by khadeshyam** [comment]
Is this issue still open? If so, please assign it to me.

**Comment by Aakashdeep-Srivastava** [comment]
Is it still open ??

**Comment by mattinannt** [comment]
Closed this to avoid confusion. Sorry, it's not open for contributions.
