### ISSUE TITLE
[ENHANCEMENT] Deal with edge case of Close Survey on Date

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#528]
**Is your feature request related to a problem? Please describe.**
Currently, a user can change the status of a surve to "in progress" after it was closed by the "Close on Date" feature. This can lead to confusion, because the behaviour can be unpredictable e.g. user finds a running survey, checks the date and finds it to be in the past -> Thinks its broken.

**Describe the solution you'd like**
To keep it consistent, a survey status should not be updateable when the "Close on Date" is active and the date is in the past.

**Tasks**
- Add an efficient way to check if the Close on Date is checked and if so, if the date is in the future
- If so, disable the SurveyStatusDropdown.tsx and add a Tooltip, something like this:

![grafik](https://github.com/formbricks/formbricks/assets/72809645/957040a4-b897-423f-b496-67d7e9577d9d)

- It doesnt have to be pixel perfect, e.g. if the disable state of the Select looks different, thats fine.
- Please use the Tooltip in formbricks/ui

Thanks! 🙌 

### How we code at Formbricks 🤓
- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by gupta-piyush19** [comment]
Hey @jobenjada , I'd like to pick this up. Can you please assign me this issue?
