### ISSUE TITLE
NPS-type question

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#53]
### NPS-type question

As a user I want to have a good way to measure if users like my business. To do this a standardized way is to use an NPS (Net promoter score) question. The way a NPS question works is always the same, e.g.

`On a scale of 0 to 10, how likely are you to recommend our business to a friend or colleague?`

For that the user needs to be presented with 11 buttons (0-10) and need to select one. In the React-Library we already have the question type `cards` for these buttons.

For analysis, the NPS question needs to present an NPS score and the number of detractors and promoters in the summary:
https://delighted.com/nps-calculator

**Comment by Dynnammo** [comment]
If possible, it'll be great to have a default number of possibilities for this question type, and let the admin modify it following its need : the default number of possibilities are 11 as you said, and the admin can modify it to be between a lower and a upper level (to discuss)

**Comment by matthiasnannt** [comment]
@Dynnammo Do you use NPS with other number configurations?
The advantage of always having the scale from 0-10 (even across companies and industries) is that the scores are comparable. If you change the scale, e.g from 1-5 you can also get different results like this article suggests: https://www.loop11.com/nps/

**Comment by Dynnammo** [comment]
No I don't. What I was thinking about is what if people wants to use such question type but for other things. As instance, what if the asked answer is a percentage, a rank, a number of years of experience in a company etc. Maybe this need is not clear and therefore starting with a NPS scale is the way to go. What I'm suggesting is that by implementing such question we could think of making it modulable if future needs arrive.

**Comment by mattinannt** [comment]
I am closing this issue due to the ongoing migration to Formbricks with a completely new code base. Formbricks now supports NPS questions via the schema and will continue the integration into frontend components once the visual editor will ship.
