### ISSUE TITLE
[FEATURE] Add current url to meta data for link-survey and in-app survey

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#533]
**Is your feature request related to a problem? Please describe.**
This feature was requested by a Formbricks user.
A formbricks user running an in-app survey may want to filter the responses based on the page the survey was shown on. Also a formbricks user sending a link survey might want to filter responses based on where users came from by using a self-placed `?utm_source=blog` into the link-url.

**Describe the solution you'd like**
Add the current `url` to the meta data of the response that currently already house the userAgent information:
```
interface Meta = {
  url: string;
  userAgent: {
    browser: string;
    device: string;
    os: string;
  }
};
```

Please make sure to add this to the link-survey as well as the formbricks-js (`packages/js`) in-app client.

The filtering is not part of this issue. This will be done in a later issue as the response filtering is currently being built in a separate PR.

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by Meetcpatel** [comment]
Hi!
Can you please assign it to me, I would like to work on this?

**Comment by mattinannt** [comment]
Sure, thanks @Meetcpatel for solving this 💪💪
