### ISSUE TITLE
[FEATURE] Make in-app surveys mobile friendly + preview in survey editor

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#544]
**Is your feature request related to a problem? Please describe.**
As a user, I want to be sure that the widget looks good on mobile phones as well.

**Describe the solution you'd like**
1. Make sure the widget is fully responsive on all devices and mobile browsers
2. Build a mobile preview toggle into the survey editor

**Full Responsiveness**
![grafik](https://github.com/formbricks/formbricks/assets/72809645/b48552db-e4eb-4c6a-86c9-5fd7c7cadcb6)
![grafik](https://github.com/formbricks/formbricks/assets/72809645/d71082cb-8228-41dc-a030-b2ce247e2f19)

- Make sure all question types look good
- Test several device widths
- Maybe this helps (free & open-source): [Responsively App](https://responsively.app/)
- Make sure the breakpoint to Tablets is done well
- It should slide in up from the bottom of the phone and slide out down on close
- The Multi / Single Select options should have less paddings to make it fit smaller screens better

**Update Survey Editor with Preview**
![grafik](https://github.com/formbricks/formbricks/assets/72809645/bdf4ecca-4dee-4073-a409-7b513a4ed49e)
![grafik](https://github.com/formbricks/formbricks/assets/72809645/757cdfe1-d4ed-421a-9e44-b826d6b52be8)

- Build a toggle to switch between desktop and mobile view in the Survey Editor. [Maybe this helps.](https://ui.shadcn.com/docs/components/tabs)
- Make sure it works for both types of surveys (in-app and link survey)

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by Dhruwang** [comment]
Would like to work on this !
