### ISSUE TITLE
[FIX] Close survey on X responses to check for current number of responses

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#561]
**Is your feature request related to a problem? Please describe.**
As a user I want to Formbricks to stop me from making faulty inputs. Currently, the "Close survey after X responses" allows me to set a number lower than the current count of responses.

![grafik](https://github.com/formbricks/formbricks/assets/72809645/43be4df5-a9bf-4be4-b8d6-8e4382921d92)

**Describe the solution you'd like**
If the status of the survey is "inProgress" the input should check the current number of responses and only accept a higher number.

**Additional context**
- We did a similar validation for the QuestionId input in the Survey Editor, for reference.
- **Additionally**: Please widen the input a bit so that 3 numbers can fit in easily

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by joe-shajan** [comment]
Hi @jobenjada  can I work this?

**Comment by Pradumn27** [comment]
I'll pick this up @jobenjada
