### ISSUE TITLE
[BUG] Conversion Rate in Weekly not calculated correctly

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#562]
### Issue Summary

The conversion rate in the Weekly isn't being calculated correctly.

Example 1: Wrong calculation
![grafik](https://github.com/formbricks/formbricks/assets/72809645/9b5ed850-671b-4863-90a0-ae74670bed82)

Example 2: Infinity not sure exactly when it happens
![grafik](https://github.com/formbricks/formbricks/assets/72809645/2f9a1892-689e-4ada-a535-1556d327fb5a)

Survey itself has these KPIs
![grafik](https://github.com/formbricks/formbricks/assets/72809645/ec26b027-d147-4c65-a424-b14079852d97)

### Expected behavior

Calculate the overall completion rate of all surveys.

#### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] self-hosted Formbricks, version/commit: [please provide]

**Comment by singhbhaskar** [comment]
Hi,
Can I work on this?

**Comment by jobenjada** [comment]
fixed it here - was a quick one :)

https://github.com/formbricks/formbricks/pull/584
