### ISSUE TITLE
[FEATURE] Overwrite global position and brand color settings

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#564]
**Is your feature request related to a problem? Please describe.**
As a user I want to display different surveys in different positions of the app.

**Describe the solution you'd like**
Overwrite global positioning setting

**Tasks**
1. Add another Settings card called "Styling" to the Setttings tab in the Survey Editor
![grafik](https://github.com/formbricks/formbricks/assets/72809645/7d8d6475-4dea-428e-b278-8bcea86f675b)

2. Add two toggles: Brand Color and Widget Positoning. Make sure to display "Widget Positioning" only for surveyType "web"

3. When active, display UI from the global product settings:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/1cf4d130-8663-4c02-9920-a50d42d51630)
![grafik](https://github.com/formbricks/formbricks/assets/72809645/9ea3611a-7d99-44be-a90d-5a0d408f52ba)

- Please try to match this look with the light gray boxes for the two inputs.
![grafik](https://github.com/formbricks/formbricks/assets/72809645/adf3d75b-aad6-49e8-a5f8-c0b54128299a)

- Make the current inputs in the global settings a component and reuse it to keep code DRY

4. Have the setting overwrite the global setting. I'm not entirely sure when the widget pulls the global setting, so you likely have to extend the Prisma schema with a boolean to prevent the settings from being overwritten by the global settings :) But you'll figure that out ;)

Thanks a lot for picking this up! 🙌 

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by joe-shajan** [comment]
Can I get this assigned?
