### ISSUE TITLE
[ENHANCEMENT] Creating new team takes 20 seconds + Refactor Team Creation + Demo Product for new sign ups

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#569]
### Issue Summary

- Due to the new Demo Product creation, creating a new team takes 20s
- New sign ups do not have a Demo Product (but they should)
- Currently, we have several point where a new team is created. This can be refactored

The main issue is the for loop that runs a lot of prisma call that are all awaited.
<img width="562" alt="Screenshot 2023-07-17 at 10 10 14" src="https://github.com/formbricks/formbricks/assets/675065/1e5fca6e-48b5-4d1e-825e-3fcfe29f856a">
Please find a way to reduce the prisma calls as well as only block execution if necessary and await the rest before returning the response.

### Steps to Reproduce

1. Create a new Team loads very long
![grafik](https://github.com/formbricks/formbricks/assets/72809645/021bd020-e3e2-42e3-8ed0-16958c98b03d)

### Tasks

1. Optimize the Prisma calls to create the team + demo data (consult with GPT :). It's in `environments > [environmentId] > actions.ts`
2. Find a smooth, non-blocking way so that new sign ups also find a second "Demo Product" when signing up. Maybe sideload it while they click through the Onboarding?

**Comment by pandeymangg** [comment]
I can take this up @jobenjada
