### ISSUE TITLE
[FEATURE] Delete Team

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#570]
**Is your feature request related to a problem? Please describe.**
As a user I want to delete teams

**Notes**
1. Only allow team deletion if the logged in user has memberships to another team. We have a similar functionality of the "Delete Product" functionality you can refer to:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/398244f1-6b34-4fee-8aba-26828a190d1b)
![grafik](https://github.com/formbricks/formbricks/assets/72809645/dd9ee5c8-5b0f-4925-9d06-3764c735e8bd)

2. Make sure to confirm that they know what they are doing: We have good confirmation UI for the "Delete Account" in Profile:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/51a933be-3e03-42a0-ba96-17a43e680e63)

Here is the text:

```
Before you proceed with deleting this team, please be aware of the following consequences:

- Permanent removal of all **products linked to this team**. This includes all surveys, responses, user actions and attributes associated with these products.
- If you are the owner of a team with other admins, the ownership of that team will be transferred to another admin.
- If you are the only member of a team or there is no other admin present, the team will be irreversibly deleted along with all associated data.
- This action cannot be undone. If it's gone, it's gone.

Please enter *insert team name here* in the following field to confirm the definitive deletion of this team:
```

**Consequences**
- There will be team members who have only the membership with the team which is about to be deleted. If they login, they will face an error. This why we need a screen that is displayed when a user is logged in who doesn't have a membership to a team.

We have these screens for the invitation management:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/9bca8127-59d6-41d7-99c8-8b1984f73c6b)

Adapt it as follows:

### You're currently not assigned to a team.
Please create a team to keep working with Formbricks.
[Create Team]

Thanks! :))

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by gupta-piyush19** [comment]
I want to work on this @jobenjada . Can you please assign this to me?
