### ISSUE TITLE
[FEATURE] Enhance Github Issue Templates for better usability

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#587]
**Is your feature request related to a problem? Please describe.**
The current Github Issue templates for creating bugfixes and feature request are one editor window with comments indicating where to fill information.
<img width="957" alt="Screenshot 2023-07-19 at 17 55 09" src="https://github.com/formbricks/formbricks/assets/675065/32b09949-7062-4271-896e-aa2bc5114b17">

This isn't very easy to handle for first time users or less technical users.

**Describe the solution you'd like**
While filling out a bug report in the [gitpod-repo](https://github.com/gitpod-io/gitpod) I noticed they were able to show a better editor to the user with multiple input field. This is much easier to understand and fill out by the users.
<img width="959" alt="Screenshot 2023-07-19 at 17 58 22" src="https://github.com/formbricks/formbricks/assets/675065/ec0810db-e05a-442b-9e7d-a2ec5cc85f3e">
The template can be found here: https://github.com/gitpod-io/gitpod/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml

Please update the Formbricks Templates in `.github/ISSUE_TEMPLATE/` to also have multiple input fields for the different questions that are asked.

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by yashhhguptaaa** [comment]
Hey @mattinannt , I would like to work on this issue. Can you please assign this to me ??
