### ISSUE TITLE
[FEATURE] Add n8n support for Formbricks

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#595]
**Is your feature request related to a problem? Please describe.**
![grafik](https://github.com/formbricks/formbricks/assets/72809645/01b4963c-6187-430f-ba48-bffed4621edd)

**Describe the solution you'd like**
We designed our API to work well with Zapier. All things should be in place to add a N8N integration 🚀 

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by PratikAwaik** [comment]
@jobenjada i can pick this up
