### ISSUE TITLE
[FEATURE][FormTribe 🔥][1000 Points] Build direct Notion integration

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#598]
**Is your feature request related to a problem? Please describe.**
As a user I want to pipe my insights directly to Notion

**Describe the solution you'd like**
Build a direct Notion integration

**Tasks**
- Look at how other tools do their Notion integrations and see what you like from an UX point of view
- Take the best from everything and ship it :)
- Add it to the Integrations page on Formbricks

Thanks for picking this up! 🚀

**Additional context**

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by yashhhguptaaa** [comment]
Hey @jobenjada Please assign it to me

**Comment by joe-shajan** [comment]
I would like to take this up

**Comment by PratikAwaik** [comment]
@jobenjada I'll be happy to pick this up :)
