### ISSUE TITLE
[FEATURE] Build make.com integration

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#599]
**Is your feature request related to a problem? Please describe.**
As a user I want to pipe my insights directly to Google Sheets

**Describe the solution you'd like**
Build a direct Make.com integration

**Tasks**
1. Look at how other tools do their Make.com integrations and see what you like from an UX point of view
2. Take the best from everything and ship it :)
3. Add it to the Integrations page on Formbricks

Thanks for picking this up! 🚀

**Additional context**

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by Dhruwang** [comment]
Would like to work on this 🤗
