### ISSUE TITLE
[FEATURE] Search Template Library

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#602]
**Is your feature request related to a problem? Please describe.**
As a user I want to search the template library

**Tasks**
- Add a basic search which searches the title and description of all templates:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/f2a96689-98d3-442b-8462-7a55d56efb22)

**Additional context**

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by Meetcpatel** [comment]
@jobenjada  I would like to work on this please assign me. 
Thank You!🙏🏻
