### ISSUE TITLE
[FEATURE] Setup public API for OSS Friends

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#603]
**Is your feature request related to a problem? Please describe.**
We have a group of OSS companies supporting each other. I created the backlink squad at https://formbricks.com/oss-friends

Its a bit tedious to update it on all other pages whenever someone new joins.

**Describe the solution you'd like**
Create a public API endpoint where the rest of the teams can pull the JSON with the Name, Description and URL of the other companies.

You can find the current object here

https://github.com/formbricks/formbricks/blob/main/apps/formbricks-com/pages/oss-friends.tsx

**Tasks**
- Setup a public endpoint in the Formbricks API
- Implement it on the oss-friends page
- Get appreciation for all the product teams bc they dont have to update it manually anymore :D

**Additional context**

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

**Comment by mattinannt** [comment]
please assign this one to me 🙋‍♂️
