### ISSUE TITLE
[FEATURE] Advanced User Targeting

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#612]
### Is your feature request related to a problem? Please describe.

The current approach for user filtering / targeting to qualify them for an in-product survey is very simple and a user can only be targeted based on their attribute values. But one of the great values of Formbricks is that it should allow very fine granular user targeting based on the user behaviour in the past. To solve this we want to introduce a new user targeting.

### Describe the solution you'd like

You can inspect the planned UI for the Advanced User Targeting in this Figma file: https://www.figma.com/file/YnPME8Jo5HWCE5Uvzvxs7X/Advanced-User-Targeting?type=whiteboard&node-id=0-1&t=Ww7cecUOp8V9XYZp-0

We introduce `User Segments` that are a set of rules how to filter users. The rules for the User Segments are very flexible and vary from simple attribute filtering to fine granular action filtering (past behaviour within the app).

The idea with the segment is that it is a separate model in the database where the filters are stored. So every survey has a segment, but only when a user saves this segment it is visible in the list of segments (indicated by a flag inside the model).
If we really allow segment filtering (e.g. user is in "Power User"), we will have to see later if this is too complicated to implement. But we want to plan with it first, so we know what the ideal structure should look like.

Please inspect the Figma file in detail as it includes all the structure of this feature, different rules and qualifiers.

### Additional context

Because this feature is very complex and introduces not only a complex UI but also new database entries and data structures within the Formbricks application, we split this issue into two steps:

1. Data Model Concept for User Segments
2. Implementation of Concept and UI

For the first step, please come up with a Zod Schema that we can use internally to store the User Segment filter information. If its easier for you, you can also first create a Json representation of an example User Segment that we discuss and in the next step derive a Zod Schema from it.

After the Zod Schema is set we can move over to the UI implementation.

**Comment by Ankur-Datta-4** [comment]
I'd like to work on this issue @mattinannt

**Comment by jobenjada** [comment]
PR is up
