### ISSUE TITLE
[BUG] The "Share URL" does not work on Safari on Mobile

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#617]
### Issue Summary

A user reported that the "Share URL" functionality on the Survey Summary page does not work on mobile phones.

The issue is that the modal closes on every click before the user can perform an action.

### Steps to Reproduce

1. Login on an mobile phone
2. Create a new Link Survey
3. Publish it
4. Try to share the link to it via the Share Link feature:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/c5c23dfd-cc13-49d7-b9b7-c185e30af7e9)

### Expected behavior

- The modal should contain the "Embed" button
- The modal should not close on every click

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by VARUN949** [comment]
would like to work on this!!!

**Comment by pandeymangg** [comment]
I can pick this up @jobenjada

**Comment by jobenjada** [comment]
hey @VARUN949 - thanks a lot for your motiviation to contribute! Due to our limited capacity to review community contributions, we're prioritizing vetted contributors. Will loop you in once we have more capacity to facilitate more community contributions :)

Thanks!!
