### ISSUE TITLE
[BUG] Invite email contains wrong (localhost) URL

### ISSUE THREAD

**Issue by domibarton** [formbricks/formbricks#663]
### Issue Summary

We're running Formbricks on Docker, behind Traefik. Thus, the public-facing URL is routed through traffic and we're not accessing the container directly. Everything works fine, but there's an error when inviting a user to an existing team:

The invite URL in the email always points to `http://localhost:3000` instead of the URL defined in `NEXT_PUBLIC_WEBAPP_URL`. This only happens in the email. When I copy the share link via the UI, the URL is correct.

### Steps to Reproduce

1. Fetch the suggested [Compose file](https://raw.githubusercontent.com/formbricks/formbricks/main/docker/docker-compose.yml)
2. Add `NEXTAUTH_SECRET`
3. Add public-facing URL to `NEXTAUTH_URL` and `NEXT_PUBLIC_WEBAPP_URL` (e.g. `https://forms.example.net`)

### Expected behavior

The URL points to the URL defined in `NEXT_PUBLIC_WEBAPP_URL`.

### Other information

Reverse Engineering
---------------------

I did a bit of reverse engineering. It seems that the email is sent in [email.ts](https://github.com/formbricks/formbricks/blob/main/apps/web/lib/email.ts#L87) and there's verifyLink generated in [email.ts#91](https://github.com/formbricks/formbricks/blob/main/apps/web/lib/email.ts#L91):

```javascript
const verifyLink = `${WEBAPP_URL}/invite?token=${encodeURIComponent(token)}`;
```

`WEBAPP_URL` is a constant imported at [email.ts#3](https://github.com/formbricks/formbricks/blob/main/apps/web/lib/email.ts#L3):

```javascript
import { WEBAPP_URL } from "@formbricks/lib/constants";
```

`WEBAPP_URL` is defined in [constants.ts#L10-16](https://github.com/formbricks/formbricks/blob/main/packages/lib/constants.ts#L10-L16):

```javascript
export const WEBAPP_URL =
  process.env.NEXT_PUBLIC_WEBAPP_URL ||
  VERCEL_URL ||
  RAILWAY_STATIC_URL ||
  HEROKU_URL ||
  RENDER_URL ||
  "http://localhost:3000";
```

So it seems that it should be read from the `NEXT_PUBLIC_WEBAPP_URL` env var, with fallback to the other values.

Environment Variables
----------------------

I checked the set environment variables in the container. Of course under the currently run user:

```
$ export | grep URL
export DATABASE_URL='postgres://user:password@db-container:5432/forms?schema=public'
export NEXTAUTH_URL='https://forms.example.net'
export NEXT_PUBLIC_WEBAPP_URL='https://forms.example.net'
```

It seems, the env vars are correct. Apart from the link in the email, every other customisation via environment variable works fine (e.g. SMTP settings). Also, the share link in the UI also provides the correct URL – it's just wrong in the email.

What next?
-----------

Did I miss something? What can I do next? :)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- Docker image: `formbricks/formbricks:1.0.1`
```

**Comment by mattinannt** [comment]
@domibarton Are you building the docker image yourself (using our git repository) or are you using the pre-built docker images? 😊

**Comment by mattinannt** [comment]
If you build the docker image yourself: I noticed an issue that different env files were used at build time than at runtime. I now fixed this issue and only the values from the `.env.docker` environment file are used in both build-time and runtime.

**Comment by jobenjada** [comment]
@domibarton hey! Does this solve your issue? :)

**Comment by domibarton** [comment]
> @domibarton hey! Does this solve your issue? :)

hello, thanks for your response :)

nope, because I don't build it myself – I use the pre-built image.
So if I interpret this correctly, there will be files changed during the build time of the Docker image, and one of those files include the base URL in question? This would mean, nobody could use the pre-built image because the URL will never be correct, since it can't be overwritten during runtime?

Is that correct? :)

**Comment by domibarton** [comment]
> > @domibarton hey! Does this solve your issue? :)
> 
> hello, thanks for your response :)
> 
> nope, because I don't build it myself – I use the pre-built image. So if I interpret this correctly, there will be files changed during the build time of the Docker image, and one of those files include the base URL in question, respectively the base URL is hardcoded after the build? This would mean, nobody could use the pre-built image because the URL will never be correct, since it can't be overwritten during runtime?
> 
> Is that correct? :)

I checked [the docs](https://formbricks.com/docs/self-hosting/deployment) again and it seems you CAN use the pre-built image [as documented](https://github.com/formbricks/formbricks/blob/main/apps/formbricks-com/pages/docs/self-hosting/deployment/index.mdx#L53). However, there are limitations, like not having the correct configuration / URL's, since you can't overwrite them during build time. But from a "user perspective", this sounds more like a bug / design flaw than a feature. Why having a pre-built image, but you can't overwrite the URL – which might be one of the more important settings in self-hosted deployments ;) Is this, by any chance, a bug?

Apart from the [«Fast Setup with a Pre-built Docker Image»](https://github.com/formbricks/formbricks/blob/main/apps/formbricks-com/pages/docs/self-hosting/deployment/index.mdx#L53) section, I read along to the [«Build-time Variables»](https://github.com/formbricks/formbricks/blob/main/apps/formbricks-com/pages/docs/self-hosting/deployment/index.mdx#L162-L187). You describe them as «build-time», but a lot of them can be overwritten during run-time. For example, with the pre-built image, I can overwrite `NEXT_PUBLIC_SIGNUP_DISABLED` and it works :)

Is it hard to change all build-time variables to run-time variables, so that the pre-built image can be used and configured?

**Comment by mattinannt** [comment]
@domibarton Yeah, it's definitely not a feature 😅 Our docker support is still very fresh and we need to work around next.js limitations that specify what variables are used during build time and what are used during runtime.
I will investigate the issue with the pre-build images and find a way to use the right variable in the email sending functionality.

**Comment by domibarton** [comment]
> @domibarton Yeah, it's definitely not a feature 😅 Our docker support is still very fresh and we need to work around next.js limitations that specify what variables are used during build time and what are used during runtime. I will investigate the issue with the pre-build images and find a way to use the right variable in the email sending functionality.

Thanks! :) Let me know when I can help somewhere…

**Comment by ShubhamPalriwala** [comment]
Hey @domibarton, did you get things working now? I'd request you to give our newly published docker image a try. We have moved most of our environment variables to runtime to allow for user customisation even in our pre-built image. Let me know if you face any issues with the same, thanks! 🚀

**Comment by domibarton** [comment]
> Hey @domibarton, did you get things working now? I'd request you to give our newly published docker image a try. We have moved most of our environment variables to runtime to allow for user customisation even in our pre-built image. Let me know if you face any issues with the same, thanks! 🚀

I tried the `1.1.2` Docker image, but the email still contains the wrong link (`http://localhost:3000`). I set both variables, `NEXTAUTH_URL` and `NEXT_PUBLIC_WEBAPP_URL`. Is there something missing on my side? :)

**Comment by domibarton** [comment]
@ShubhamPalriwala now it's getting worse, because formbricks no longer works. I get an error when I submit a form:

```
Failed to send response: {
  "finished": true,
  "data": {
    "qp6mefql3zsy6pc7fnre8zf6": "fsdf",
    "inputType": "text"
  }
}
```

JS console shows: 

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/api/v1/client/displays. (Reason: CORS request did not succeed). Status code: (null).
```

I also see that results will be sent to localhost via `POST`. Can I downgrade? :/

**Comment by domibarton** [comment]
> @domibarton Please check the migration guide for Formbricks 1.1: https://formbricks.com/docs/self-hosting/migrating-to-1.1 We changed a lot of env variables to ensure that they can be set in the docker container at runtime.

Oops, that's a PEBKAC issue then, resp. RTFM :)  
Sorry!

Updated the env vars, tested it and it works! :) THANKS!
