### ISSUE TITLE
[FEATURE] Wordpress Plugin for Formbricks

### ISSUE THREAD

**Issue by ShubhamPalriwala** [formbricks/formbricks#675]
### Is your feature request related to a problem? Please describe.

A Formbricks wordpress plugin would make it easy for wordpress developers to integrate formbricks natively in their applications! 

### Describe the solution you'd like

A Potential Approach can be to:
- Enqueue the Formbricks JavaScript package using WordPress best practices.
- Create a settings page to set the Formbricks environment ID and API host under the Wordpress plugin settings and ask the user to pass their own values!
- Include links to the Formbricks documentation and core platform.
- Implement a display for the Formbricks embed status if possible. Ideally, the plugin is able to display an embed status similar to the Setup Checklist.
- A version control with release documentation would help maintain consistency!

### Additional context

The Wordpress plugin guide: https://developer.wordpress.org/plugins/

You need not need to go through the entire book, use GPT for help!

**Comment by mcnaveen** [comment]
https://github.com/mcnaveen/formbricks-wp

**Comment by mattinannt** [comment]
Update: We just released formbricks-js 1.2.0 with support for public-facing websites. Thanks to @mcnaveen for the wordpress plugin. We will now go ahead and test the plugin :-)

**Comment by mcnaveen** [comment]
That's great to hear @mattinannt! 🎉

**Comment by mattinannt** [comment]
Update: We tested and improved the plugin together with @mcnaveen 🙏. We submitted it for review earlier this month and got back a list of improvements by the Wordpress team we need to make. We will resubmit after we have made the improvements.

In the meantime, the plugin is already usable via zip installation:
https://github.com/formbricks/wordpress
