### ISSUE TITLE
[FEATURE] Survey Creation via API

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#700]
### Is your feature request related to a problem? Please describe.

Customer: "We're a traing company and we use WebEx Polls to get daily snapshots of our student's progress and if they are happy with the pace of the course.  The instructors dynamically generate the survey questions from a pool of provided relevant questions and then the students answer them.  We'd like to move away from the webex implementation to something we have more control over.  That's why were were looking at Formbricks to intract with the User API to create the dynamic surveys."

### Describe the solution you'd like

Customer: "Right now I'm building a solution that uses SurveyJS as the schema and display mechinsm for the survey. Simply storing the entire survey definition as json which is what our instructors would input into the survey creation part of the app. Then the display/recording will render the survey and record the results."

Please create an new API endpoint to create a new survey using our service. The API endpoint should do the following:
- Accept and API Key for authentication or a nextauth session (when called by the frontend) (our new APIs should work for both cases)
- Have a POST endpoint that accepts a survey as JSON
- Validate this Survey JSON using Zod
- Return the newly created survey

Please see existing endpoints like the `Webhook` endpoint (`apps/web/app/api/v1/webhooks/route.ts`) for reference 😊

### Describe alternatives you've considered

-

### Additional context

-

**Comment by Dhruwang** [comment]
Would take this up 🚀
