### ISSUE TITLE
Add numerical slider question type

### ISSUE THREAD

**Issue by penyuan** [formbricks/formbricks#73]
### Is your proposal related to a problem?

I want respondents to express degrees of importance, e.g. from 0 to 5 with 5 being most important

### Describe the solution you'd like

Add a mobile-friendly question type where the respondent can drag a numerical slider to give a quantitative answer. The range of the numbers can be arbitrarily set, and can optionally include decimal digits.

### Describe alternatives you've considered

I don't like making the user type in a number!

**Comment by matthiasnannt** [comment]
Hi @penyuan
thanks for the feature request 😊 A contributor is currently working on a rating question type, where you can vote with stars or with hearts. Would that also be something that solves your problem that you want the slider for?

<img width="423" alt="Screenshot 2022-08-25 at 22 22 19" src="https://user-images.githubusercontent.com/675065/186761158-a7744f50-5dd6-4cc2-96e9-e12bbf86e1c4.png">

**Comment by penyuan** [comment]
Hi @matthiasnannt thanks for getting back to me so quickly.

The stars/hearts feature you describe is a big step and very helpful. However, there are three things important to what I'm suggesting: 

1. Drag instead of click UX.
2. Support for arbitrary numerical ranges. For example, a range of 0 - 50 can be draggable, but probably impractical to display as 50 hearts/stars!
3. Support for decimals such as `2.5` which can also be a draggable thing but harder to implement with hearts/stars.

Also, in some situations hearts/stars simply do not fit the tone of the survey.

Hope this helps!

**Comment by gotjoshua** [comment]
> currently working on a rating question type,

is there any progress visible on this PR?

i am very eager for an open source survey tool with sliders, and i could very quickly code it up.

**Comment by matthiasnannt** [comment]
@gotjoshua Unfortunately the feature with the star rating isn't ready yet. I will check back with the contributor on the current progress.

if you want to make a contribution with a slider, that would be awesome.

**Comment by mattinannt** [comment]
Update: Is on the todo list for a release very soon with new Formbricks.

**Comment by penyuan** [comment]
Great news, many thanks to the developers!

> Rating Question with numbers (1-n)

Instead of (1-n), may I suggest (0-n)? It makes a big difference in some use cases.

**Comment by mattinannt** [comment]
Update: Last week we released the Rating Scale Question Type with numbers, smileys and stars with v0.12 https://github.com/formbricks/formbricks/releases/tag/v0.12 🎉
This will enable many different new usecases and we will test over the next few weeks with our users if this is already enough for the current surveys they run with Formbricks or if e.g. a slider or "start rating at zero" toggle is still required.

**Comment by heysagnik** [comment]
Is this issue still open ?

**Comment by mattinannt** [comment]
Our users currently seem satisfied with the different types of rating questions. So I'm closing this issue for now.

**Comment by kartikprakash1** [comment]
Is this implemented? I was looking at the online form version, I couldn't configure a rating question with limit higher than 10 or a slider?
