### ISSUE TITLE
[FEATURE] Railway One Click Setup

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#734]
### Is your feature request related to a problem? Please describe.

Setting up Formbricks on Railway requires some tinkering.

### Describe the solution you'd like

Allow people to setup Formbricks on Railway with one click

**Comment by Meetcpatel** [comment]
Hi @jobenjada !
I would like to work on this, can you please assign me?

**Comment by AIABHISHEK** [comment]
Hello @jobenjada can you tell me about this Feature, I want to work on it.

**Comment by jobenjada** [comment]
[Railway](https://railway.app/) facilitates One Click Hosting, if you set it up correctly.

Your task is to research what we have to do to allow people to host Formbricks with One Click on Railway :)

Cheers!
Johannes

**Comment by AIABHISHEK** [comment]
@railwayapp Provides feature of templates which lets deploy in one click.

[![Deploy on Railway](https://railway.app/button.svg)](https://railway.app/new/template/PPDzCd)
Here is [Link](https://railway.app/new/template/PPDzCd) of template which uses [formbricks](https://hub.docker.com/r/formbricks/formbricks) docker image for deployment.
It also allow to create your own template and also convert existing project into template.

**Comment by jobenjada** [comment]
Thanks! :)
