### ISSUE TITLE
[BUG] Privacy Policy & Imprint links missing despite .env variable set

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#738]
### Issue Summary

Community Member Sascha is missing the links to the Privacy Policy and the Imprint in link surveys.

He set the corresponding env variables as follows:

`NEXT_PUBLIC_PRIVACY_URL=https://bonn.digital/datenschutz
NEXT_PUBLIC_TERMS_URL=https://bonn.digital/kontakt
NEXT_PUBLIC_IMPRINT_URL=https://bonn.digital/impressum

PRIVACY_URL=https://bonn.digital/datenschutz
TERMS_URL=https://bonn.digital/kontakt
IMPRINT_URL=https://bonn.digital/impressum`

Link to survey without links:

https://formular.bonn.digital/s/clluzn3f60000o32h6jdwkfdp

Pls investigate. Contact @saschafoerster directly in Discord for follow up questions

### Steps to Reproduce

1. Set env variables
2. Spin up Docker 
3. Check if links are there or not

### Expected behavior

Links show up

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by ShubhamPalriwala** [comment]
@jobenjada as discussed, these are build-time variables that cannot (currently) be overwritten without rebuilding the image! Sascha has been informed about the same and the steps they can take to get it working as they want!

Will soon revisit the env vars and see what can be done! I think we can close this for now? What do you think?

**Comment by saschafoerster** [comment]
This is my upgrade procedure: 
```
git pull
git checkout v1.0.2
docker compose build
docker compose up -d
```
I still can't see the privacy links.

**Comment by saschafoerster** [comment]
Okay, I think I got it:
I was still using .env, but you changed it to .env.docker, which didn't get copied: 
 [formbricks installer 5/8] COPY .env.docker /app/apps/web/.env
 
 https://github.com/formbricks/formbricks/commit/33b3887b84d9a3df70013460aaebbf8263765f3a
 
 Now it works. For everyone else: just use .env.docker and not .env, if you are building the container.

**Comment by saschafoerster** [comment]
@jobenjada Please close. thank you!
