### ISSUE TITLE
[BUG]: Validation error causes auto close of survey to not work.

### ISSUE THREAD

**Issue by ty-kerr** [formbricks/formbricks#764]
### Issue Summary

Close survey on response limit feature has a bug.

Given the survey has a Free Text question and a user is filling out the last response before the survey will auto close. i.e. user is filling out the 5th survey response and auto close is set to 5. When the user inputs a numerical string e.g. "1234" as the answer of the free test question and submits that response. A zod validation error occurs in the POST /pipeline request as there is a function that converts the numerical string to a date. Any subsequent response will also not trigger the survey to close event if they are valid. 

<img width="414" alt="image" src="https://github.com/formbricks/formbricks/assets/17407010/0a759984-61d3-4d09-8d57-eec1b4d2e797">

Issue is suspected to be from convertDatesInObject() function used in line 20 of `apps/web/app/api/pipeline/route.ts`

### Steps to Reproduce

1. Create a survey with with X response limit to close the survey, including a free text question.
2. On the Xth response, input a numerical string (e.g. 1234) as the answer of the free text question and submit.
3. Complete the rest of the survey as usual.
4. Check the survey cummary page, the status does not automagically update to completed.

### Expected behavior

When entering a numerical string as the answer of the free text question in the last response for a survey with autoClose enabled. The suryvey should close after that response is fully completed.

### Screenshots

https://www.loom.com/share/751c5cb81cb5445db67d1eb1d6206763?sid=b064c3a0-546a-4f0d-a8c8-a3cc8c5b03e5

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: 13.3.1
- Browser: Chrome 116
- Node: 18.6
- npm: 9.5.1
```

**Comment by kussshhhh** [comment]
I would like to work on this issue.

**Comment by mattinannt** [comment]
@ty-kerr thanks for the bug report.
@kussshhhh thanks for volunteering :-) I assigned the issue to you 💪 When can we expect a fix from you? 🤗

**Comment by xnsei** [comment]
Hey @mattinannt, lemme quickly send a PR to fix this
