### ISSUE TITLE
Support for HTML Formdata

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#77]
Give users the option to send data from a simple HTML form to snoopForms. These forms don't have a schema at that point and so the user miss out on additional features/analytics that the schema provides.

**Comment by fdis111** [comment]
Hi @mattinannt , can you assign this task to me?

**Comment by mattinannt** [comment]
@fdis111 sorry for the late response
We are currently in the process of rethinking our current approach and are planning a more open and universal platform. That still includes html formdata of course but in the coming weeks we want to restructure the core of snoopforms.
Because of that I don't think it makes sense to let you build the feature now when the underlying database and APIs will change.
In a few weeks with the updated core this feature will be much easier to build and maybe will also be included already in the core. We will keep you updated on this 💪

**Comment by mattinannt** [comment]
I am closing this issue due to the ongoing migration to Formbricks with a completely new code base. Sending data from HTML forms is now possible via the Formbricks API.
