### ISSUE TITLE
[BUG]: Invite expired - Github Auth

### ISSUE THREAD

**Issue by RA9** [formbricks/formbricks#778]
### Issue Summary

I tried creating an account on the Formbricks platform and got invite expired when I used the Github single-sign on method.

### Steps to Reproduce

1. (for example) Went to https://formbricks.com/
2. Clicked on the get started link
3. Selected the Github Sign in  button

### Expected behavior

I was expecting to be logged in or invited to log in, but got this:

![image](https://github.com/formbricks/formbricks/assets/20514920/deeb102e-8916-4203-b6ea-23ef1cb67fb3)

### Other information

There are some misspellings here and there

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/20514920/228e84f5-7201-4cee-a6ff-0bb888df90a5)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by shawshankkumar** [comment]
The token = null. Was this the original URL?

**Comment by RA9** [comment]
> Hey @RA9, apologies that you faced this issue! I just followed the steps you mentioned to reproduce the bug and surprisingly, it worked for me! Could you do me a favour and try once again please?

I am currently logged in. I am guessing that happened when you are signing up using the social login. However, there are some spelling errors like it is spelled `invies` instead of `invite`.

**Comment by ShubhamPalriwala** [comment]
Oh okay, I tried signup and signin both, and they worked for me! I'll keep an eye on this, thanks for pointing out the typos, will fix that tomorrow 🤞🏼

**Comment by ShubhamPalriwala** [comment]
@pandeymangg has opened a PR for the same in #803! This should solve this ideally 🤞🏼

**Comment by noahnoahk** [comment]
invite expired

**Comment by jobenjada** [comment]
@noahnoahk Do you still have the issue?

**Comment by noahnoahk** [comment]
checked... its all good now

**Comment by ShubhamPalriwala** [comment]
Closing this then! Apologies to everyone who faced this issue! Cheers to @pandeymangg for fixing this!
