### ISSUE TITLE
[BUG] `localhost:3000` survey share URL with v1.0.3

### ISSUE THREAD

**Issue by salim-b** [formbricks/formbricks#799]
### Issue Summary

The Formbrick [v1.0.3 release](https://github.com/formbricks/formbricks/releases/tag/v1.0.3) introduced a regression in the  [pre-built `formbricks/formbricks` Docker image](https://hub.docker.com/r/formbricks/formbricks/): The survey share URL domain is now erroneously set to the app's internal `localhost:3000` URL instead of the configured `WEBAPP_URL` environment variable value.

### Steps to Reproduce

Set the necessary runtime environment variables and deploy the [pre-built `formbricks/formbricks` Docker image](https://hub.docker.com/r/formbricks/formbricks/).

### Expected behavior

The survey share URL should start in the value of the `WEBAPP_URL` environment variable instead if `localhost:3000`.

### Screenshots

with v1.0.2:

![Bildschirmfoto vom 2023-09-11 15-30-50-obfuscated](https://github.com/formbricks/formbricks/assets/20040931/a9888b8f-87de-4a4b-9d2f-857daadee581)

with v1.0.3:
![Bildschirmfoto vom 2023-09-11 15-31-05](https://github.com/formbricks/formbricks/assets/20040931/314f505f-864d-48d2-a4f5-26b2406b8420)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [x] Self-hosted Formbricks

### System / OS

[Pre-built `formbricks/formbricks` Docker image](https://hub.docker.com/r/formbricks/formbricks/) deployed as micro VM to [Fly.io](https://fly.io/docs/app-guides/run-a-global-image-service/#deploying-docker-images-to-fly). See the `fly.toml` config file in [our repo](https://gitlab.com/votelog/apps/forms/) for details.

**Comment by ShubhamPalriwala** [comment]
Hey, thanks for opening the ticket! Apologies that you are facing this issue, I have just replicated it locally and looking into the same! Will keep you updated when there's some substantial progress! 🙏🏼
