### ISSUE TITLE
Red asterisk for required fields shows for optional fields

### ISSUE THREAD

**Issue by ohemelaar** [formbricks/formbricks#80]
### Issue Summary

Making a field optional still shows the red asterisk when coming back to the form.

### Steps to Reproduce

1. create form with no-code builder
2. mark a field as optional (for example the default field when a new form is created)
3. refresh

The red asterisk is back again. However, the field is still considered optional (form can be submitted without it, "click to tune" shows the mandatory button asterisk in black instead of blue)

## Environment

- [ ] snoopForms Cloud (app.snoopforms.com)
- [x] self-hosted snoopForms, version/commit: 64d84b69db283ec8faa897052b7657d39609de26

### Additional Context

Firefox 104.0 (64-bit)

**Comment by matthiasnannt** [comment]
Thank you for the bug report. We currently have issues with the saving routine for the editor that probably also causes this issue because the new state isn't saved at that moment. Over the next week I will build a new saving routine that should fix this issue.
