### ISSUE TITLE
Survey is not displaying on website [BUG]

### ISSUE THREAD

**Issue by ViddyozeK** [formbricks/formbricks#814]
### Issue Summary

HTML code is installed and formbricks recognizes this and my account shows that is receiving data however no survey is displayed on the website and no responses have been recieved. What could the issue be? 

### Steps to Reproduce

HTML code is installed and formbricks recognizes this and my account shows that is receiving data however no survey is displayed on the website

### Expected behavior

survey is displayed for users to complete 

### Screenshots

<img width="542" alt="image" src="https://github.com/formbricks/formbricks/assets/145041372/b26ff710-9976-4b15-a1da-b88b004ae398">

<img width="1259" alt="image" src="https://github.com/formbricks/formbricks/assets/145041372/2f343179-a07a-438d-a7d8-0cbfa7e162fb">

<img width="777" alt="image" src="https://github.com/formbricks/formbricks/assets/145041372/f269dab5-77f7-477d-9277-26bdf1dce0f3">

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm: 

all
```

**Comment by mattinannt** [comment]
@ViddyozeK We are currently experiencing performance issues on Formbricks Cloud and have disabled the web application survey endpoints that register users for the time being.
We are still working on a solution for this issue and hope to release the fix within the next day or two. Sorry for the interruption in service. I will post an update as soon as we release the fix.

**Comment by ViddyozeK** [comment]
@mattinannt do you know when this will be fixed? it still seems to be an issue

**Comment by mattinannt** [comment]
@ViddyozeK The main issue we were facing is fixed. Can you please share more details about the error you are facing and how the survey was setup and is being tested :-)

**Comment by ViddyozeK** [comment]
@mattinannt please see screenshots above, there has been no change and no responses

**Comment by mattinannt** [comment]
To debug this issue we need more information on your integration and the survey:
- Please inspect the page you integrated Formbricks in (in the browser: right click -> inspect). Is the “Console” tab showing any error messages? Are requests failing in the “Network” tab?
- Are users showing up on the Peoples page in Formbricks?
- How are your Survey trigger configured and the recontacting options configured?

**Comment by c-delouvencourt** [comment]
Same problem here in self-hosted env

**Comment by mattinannt** [comment]
@c-delouvencourt Can you please share more information about the survey you want to display (trigger and recontact options)? :-)

**Comment by adityadeshlahre** [comment]
@c-delouvencourt As per my reading setup in local host you have to setup your account **[NEXT_PUBLIC_FORMBRICKS_ENVIRONMENT_ID]** on **app/demo/.env** for seeing the form for testing purpose !

I haven't tested on cloud environment **Formbricks Cloud (app.formbricks.com)** 

But on local environment u can test something like this after setting your .env ! 
[Video] Attached
https://github.com/formbricks/formbricks/assets/132184385/633076c1-4b66-43a8-a1f7-bc89374168dc

**Comment by jobenjada** [comment]
@ViddyozeK and @c-delouvencourt is the issue still persisting? If not, I'll close this issue tomorrow :)

**Comment by c-delouvencourt** [comment]
Resolved thank you

**Comment by ShubhamPalriwala** [comment]
Closing this! If anybody witnesses this again, please feel free to re-open it!

**Comment by Yoffic** [comment]
@ShubhamPalriwala Hi! 

I ran into the same issue yesterday. The survey has been displaying normally for about 3 weeks. But yesterday it stopped showing the widget. The integration is Formbricks Cloud. Debug shows everything is connected fine. I can see created container in DOM. Even widget status saying it's fine. But still no widget with survey.


<img width="657" alt="Screenshot 2023-10-24 at 7 32 55 AM" src="https://github.com/formbricks/formbricks/assets/17614226/12c34d23-eb06-4205-a844-35a667ca6c52">
<img width="666" alt="Screenshot 2023-10-24 at 7 33 24 AM" src="https://github.com/formbricks/formbricks/assets/17614226/e81ef8ab-c247-4a70-ab81-c984f7cec570">
<img width="970" alt="Screenshot 2023-10-24 at 7 33 46 AM" src="https://github.com/formbricks/formbricks/assets/17614226/f297522b-cc87-497e-b1f2-074d95a3d41e">

**Comment by mattinannt** [comment]
> @ShubhamPalriwala Hi!
> 
> I ran into the same issue yesterday. The survey has been displaying normally for about 3 weeks. But yesterday it stopped showing the widget. The integration is Formbricks Cloud. Debug shows everything is connected fine. I can see created container in DOM. Even widget status saying it's fine. But still no widget with survey.
> 
> <img alt="Screenshot 2023-10-24 at 7 32 55 AM" width="657" src="https://user-images.githubusercontent.com/17614226/277550033-12c34d23-eb06-4205-a844-35a667ca6c52.png"> <img alt="Screenshot 2023-10-24 at 7 33 24 AM" width="666" src="https://user-images.githubusercontent.com/17614226/277550039-e81ef8ab-c247-4a70-ab81-c984f7cec570.png"> <img alt="Screenshot 2023-10-24 at 7 33 46 AM" width="970" src="https://user-images.githubusercontent.com/17614226/277550043-f297522b-cc87-497e-b1f2-074d95a3d41e.png">

@Yoffic What is the survey configuration you are using? Do you filter your audience? When gets the survey triggered and are you overwriting the recontact options?

**Comment by Yoffic** [comment]
@mattinannt this is the current config, formbricks/js 1.0.7. I've updated to version 1.1.0 and it has started to appear. This is odd


<img width="704" alt="Screenshot 2023-10-24 at 9 49 23 AM" src="https://github.com/formbricks/formbricks/assets/17614226/9d918593-1267-4cca-80e6-718bef381cba">
<img width="703" alt="Screenshot 2023-10-24 at 9 49 36 AM" src="https://github.com/formbricks/formbricks/assets/17614226/4441410f-e93f-45b0-a496-e2a35e2f3112">

<img width="689" alt="Screenshot 2023-10-24 at 9 49 02 AM" src="https://github.com/formbricks/formbricks/assets/17614226/85c3f99c-080d-476f-8ae6-b01e25237f90">
<img width="698" alt="Screenshot 2023-10-24 at 9 49 11 AM" src="https://github.com/formbricks/formbricks/assets/17614226/25403a0d-c1e2-4685-b360-ede784235e0b">

**Comment by mattinannt** [comment]
@Yoffic thanks for sharing; I will try to reproduce the issue.

**Comment by mattinannt** [comment]
@Yoffic I tested it in our development environment and it worked for me.
A new session is only triggered after one hour of inactivity; and in the first screenshot you shared the session was still valid so it shouldn't get triggered.
To test this properly, you can delete the local storage object in the browsers inspect window and reload the page.
<img width="740" alt="Screenshot 2023-10-24 at 09 02 18" src="https://github.com/formbricks/formbricks/assets/675065/1ae0dd23-8a58-467f-9e1e-e59ddc8a8966">

**Comment by Yoffic** [comment]
@mattinannt this is working as you described with version 1.1.0. However, with 1.0.7 even deleting storage object doesn't help. It sends status that it is displaying and mount DOM elements for survey, but they are empty and the widget isn't displaying.

**Comment by mattinannt** [comment]
@Yoffic But it's good when it's working with the newer version :-) The current version is [`1.1.3`](https://www.npmjs.com/package/@formbricks/js). Please make sure you are using the latest version while testing; so we can check if it's a technical issue with the current version.
