### ISSUE TITLE
[BUG]: ` pnpm dev --filter=demo` , demo app fails, @formbricks/js not found

### ISSUE THREAD

**Issue by amitanshusahu** [formbricks/formbricks#847]
### Issue Summary

i followed the official documentation (https://formbricks.com/docs/contributing/setup) and tried to start the demo app using `pnpm dev --filter=demo` but it fails. 

### Steps to Reproduce

1. go to root folder 
2. run pnpm dev --filter=demo

### Expected behavior

should start the demo app

### Other information

@formbricks/js module not found

### Screenshots

https://github.com/formbricks/formbricks/assets/83657737/cb29272c-2bf7-402a-b83b-27894b5dab2a

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: ubuntu(linux)
- Node: 18.17.1
- npm: 9.6.7
```

**Comment by Dhruwang** [comment]
Hey @amitanshusahu 😊
Can you try this:
1. Open packages/js
2. Run `pnpm run build` in that folder

**Comment by amitanshusahu** [comment]
works
