### ISSUE TITLE
[FormTribe 🔥][500 Points] URL Shortener

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#880]
### Welcome to the FormTribe!

This issue will get you **500 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

----------

### Issue

We allow to add a lot of information via URL parameters which creates long links. 

### Solution

**Solution**: Allow people to use a link shortener

### Tasks

Add a new menu item "Link Shortener" with hero icon "Link" to the dropdown on the right hand. Add it above Developer Docs in the same section (so below the divider):

<img width="276" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/af42215e-1daf-4a33-8468-505a8f69dfe1">

If clicked, open a modal which looks as follows:

<img width="692" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/9b9ef569-ef06-4efb-98d4-b0e3245996f3">

1. Please use the existing modal component like you can find it for the Create Team functionality.
2. The "Short URL" field you can take from the Share survey modal:

<img width="473" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/583ff42a-45b8-4ba5-bca8-332997d7fb46">

Make sure to validate the link before shortening: Only allow links which start with "https://formbricks.com/i/" (SURVEY_BASE_URL from constants) to make sure people don't misuse it for spamming or phishing

Validate on blur with a toast. You can see the UI when you test a URL match in a No Code Action:

<img width="540" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/402d7167-141d-4882-becd-03a9d2eedc30">

The toast message should say: Only formbricks links allowed.

Addon: In a different ticket, someone is working on slick link previews. In case the previews are already shipped, make sure that they are still rendered, when the link got shortened.

Use package [nanoId](https://github.com/ai/nanoid) for the new, short URL. Create the short Url server side using server actions. You likely need to add a new database model ShortUrl for storing the long url, short Url pairs. Please do not access prisma directly but build a new service in packages/lib/services. The short Url should look like this:

https://formbricks.com/i/U3ks02kdl2 (length 10, alphanumeric upper+lowercase). Add a new environment variable  SHORT_SURVEY_BASE_URL as well as a constant for this.

Make sure requests to /i/[shortUrl] are redirected properly.

### Thanks!

**Comment by Shubhdeep12** [comment]
Love to work on this @jobenjada

**Comment by raysubham** [comment]
@jobenjada I can build this too. Please let me know.

**Comment by surajgjadhav** [comment]
Hi,
can I take this up ?
or if anyone who is working on this needs help
do let me know 👍

**Comment by jobenjada** [comment]
Hey! Thanks for your interests: Generally, everyone can open a PR for this issue and we will review them in the same order they come in. We will let you know in here when a promising PR is already opened so you don't spend your time working on issues which are already covered :)

**Comment by surajgjadhav** [comment]
Hi, do we have figma design link for this modal ?

**Comment by rohan9896** [comment]
Hey @jobenjada, I would love to take this up.

**Comment by ykburda** [comment]
It will be amazing , If we have an option in environment or product settings to enable/disable for auto shorten url. Here i saw a manual action but  I would like to get all urls shortened if enabled in system. This will be a woow point :)

**Comment by raysubham** [comment]
> Hey @jobenjada, I would love to take this up.
> 
> Edit - Adding progress here
> 
> 1. Done with Project setup and creating an account.
> 2. Added MenuItem "Link Shortener" in navigation items.
> 3. Done with the UI of Link Shortener Modal.
> 
> <img alt="Screenshot 2023-10-01 at 11 43 45 PM" width="1440" src="https://user-images.githubusercontent.com/56235204/271846161-a9e697f1-3625-458f-95ee-23de313a9e71.png">

Hey @rohan9896 Co-incidently I have been also working on this & raised a PR already.

**Comment by ykburda** [comment]
Hi,
For testing purposes we need to not forget userID&suID&otherhiddenattributes.
**sample:**
https://formbricks.com/clmgepwa106g5pb0gdlgotoib?suID=3f23ebc2-b22b-401d-9c3b-151dfc303d43&userID=f0a4a98a4f3f416ea74b0e076463adb6&hidden1=abcde&hidden2=defgh

Also are we using kind of url shorten library. What will happen not found etc.

**Comment by jobenjada** [comment]
⚠️ PLEASE DONT OPEN ANOTHER PR FOR THIS ISSUE! ⚠️

We have 3 PRs open for this issue right now and are working @raysubham to get his ready to merge because he was the first to ship it.

**Comment by ShubhamPalriwala** [comment]
Superrrr work @raysubham! 🚀 closing this issue now since your work is now live on production via https://github.com/formbricks/formbricks/pull/895!
