### ISSUE TITLE
[FormTribe 🔥][500 Points] Keyboard Usability

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#882]
### Welcome to the FormTribe!

This issue will get you **500 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------
### Issue

Currently, the surveys are not properly keyboard accessible.

### Describe the solution you'd like

Provide a good keyboard UX

The easiest to get an understanding of the UX issue is experiencing it yourself. Here is a survey with one question of each question type:

https://formbricks.com/cln3gj0c77119od0ffeuvd4cu

### Tasks

Build a keyboard UX which consists mostly of TAB, ENTER and typing. Here is the walk through:

1. Welcome Page (and CTA question): ENTER to go to next question:

<img width="405" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/b72cd246-8973-401a-9e09-a55372ff5ed7">

2. Free Text: 
- Default focus in text area (already works)
- TAB to jumps to NEXT button
- ENTER to go to next question
- hitting TAB a second time before ENTER the focus shifts to Back button before jumping to other elements on the page

<img width="523" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/e59f0064-cac5-47e3-90cd-62960e90c45e">

3. Single Select: 
- Default: no option focussed 
- TAB to focus first option: Currently, the focus state is not shown but you can use the current hover state as the focus state.
- with every TAB jump through all options
- ENTER on any option selects it
- If possible, next TAB should directly jump to NEXT button instead of having to loop through all options
- after last option, jump to NEXT button
- ENTER goes to next question

<img width="513" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/7bdd2e78-3bf4-4269-bd55-f769c7b85486">

4. Multi Select: Same UX like above just without jumping to Next button after selecting an option

<img width="521" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/c630582a-fc47-4453-a9f7-29a5a6fb25ad">

5.  NPS Question: 
- Default: no option focussed
- TAB: Focus jumps to 1 (also needed to add current hover state as focus state)
- Every TAB jumps to next option
- ENTER selects option and goes to next question

<img width="530" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/c36da657-37db-4cec-98a5-fe797c61dcd5">

6. Rating Question: Same UX

<img width="584" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/482ed147-ebcb-4538-8037-96fd8bc2cb85">

7. Consent Question: 
- Default: Nothing selected
- TAB focusses checkbox. Here we're missing both a hover and a focus state, please make a suggestion that matches the overall UI
- Enter checks box
- TAB to select button, ENTER to submit

<img width="587" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/1fb29eab-3a95-419c-9927-a68d27cad4c1">

### Technical requirements

The keyboard accessibility will be part of our survey package (@formbricks/surveys) which is part of formbricks-js. Formbricks-js is not only used to the link survey but also for in app surveys. This is why we are very cautious about the package size of formbricks-js.

**Any solution which does NOT install a bloated 3rd party lib to handle keyboard accessibility is heavily favoured. We want to keep the bundle size as tiny as possible.**

Please also make sure that the keyboard usability work in both web-app surveys and link surveys.

**Comment by shreyashsingh-101** [comment]
Hey @jobenjada, I would like to work on this.

**Comment by yashgangwar7558** [comment]
I would love to work on this @jobenjada.

**Comment by jobenjada** [comment]
@yashgangwar7558  

Lovely! Please open a draft PR with your current work within the next 24h.

This allows us to see if your work goes in the right direction.

And in case you dont open a PR, we can hand it over to a different community member :)

**Comment by xnsei** [comment]
hey @jobenjada @yashgangwar7558 I'd be happy to help here if you need any🙂

**Comment by adityadeshlahre** [comment]
Hey @yashgangwar7558 @xnsei 
i would like to proceed with you guys on this feature/issue :smile:
thankyou

**Comment by xnsei** [comment]
@jobenjada since there are many people interested in this issue, should we increase its scope to include usability for disabled people? e.g. by using screen readers

**Comment by anjy7** [comment]
Hey @jobenjada , I would like to work on this as well..

**Comment by jobenjada** [comment]
Hey @xnsei not sure if it makes sense to bloat the scope right now, lets first get something functional shipped.

And so far @yashgangwar7558 hasnt shipped anything so youre up next anyways :)
