### ISSUE TITLE
[FormTribe 🔥][250 Points] Mandatory Question Indicator

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#885]
### Welcome to the FormTribe!

This issue will get you **250 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------
### Issue

Currently, we don't have a mandatory field indicator

### Describe the solution you'd like

Add one :)

<img width="684" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/9d08b46a-e31b-411d-9e9e-68c3f9735ddb">

As you can see, we're going with an inverted approach: Marking optional fields. We do this for a handful of reasons:

- In surveying, its a good practice to only ask what's really needed so by default a question is mandatory
- We use a text-based indicator for accessibility reasons (instead e.g. a red * )

### Tasks: 

1. Surveys are being rendered by the Formbricks survey package @formbricks/surveys packages. This is where you need to add this indicator. Please create a reusable component for all question types.

2. Please test in the preview as well as end-user facing surveys

**Comment by heysagnik** [comment]
I want to work on this issue
