### ISSUE TITLE
[FormTribe 🔥][500 Points] Full Screen Link Survey Preview

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#886]
### Welcome to the FormTribe

This issue will get you **500 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------

On small screens, its difficult to get a grasp of what you're designing, especially when layouting comes into play soon.

### Describe the solution you'd like

We let people scale up the preview to a almost a full-screen pop-over, like Arc browser does:

<img width="740" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/480d19a4-2430-47f4-9c50-04ecea143b6a">

### Tasks

1. Add a button to the top right of the preview window, use Hero Icon ArrowsPointingOut
<img width="750" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/10be3fd7-b3a6-48b7-97eb-a85f44895aed">

2. Scale up the window to 90vw and 90vh with a smooth animation. Add dark backdrop, blur and slight shadow to give it a plastic look and feel. Ideally, you can perform the animation without any library. If you have to choose one, use Framer Motion:
<img width="1426" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/83a97ca7-871a-4211-9197-4121320e8b30">

**Comment by yatharth1706** [comment]
Hi @jobenjada I am interested for working on this issue. I am working on the solution for this

**Comment by jobenjada** [comment]
sweet, excited to see it!

**Comment by pratik-codes** [comment]
You can also use a modal of 90vh when the user clicks on preview to show in full screen mode right?

**Comment by pratik-codes** [comment]
https://github.com/formbricks/formbricks/assets/64960569/fdbc26ee-08a6-4717-8e54-51ad574ded42

I have some progress on this but for backdrop spread, there is no utility in tailwind css. Let me know if this looks fine to you? @jobenjada

**Comment by yatharth1706** [comment]
Hi @jobenjada, I have tried to create this full screen using framer motion. It looks like this. Let me know what you think.

https://github.com/formbricks/formbricks/assets/32243289/ea218023-d5a7-47bc-ab66-fcc54aa5272d

**Comment by pratik-codes** [comment]
Can I work on this @jobenjada ?

**Comment by jobenjada** [comment]
@yatharth1706 has opened a PR which looks promising but isnt perfect yet!

https://github.com/formbricks/formbricks/pull/898

@pratik-codes if you can help achieve the effect that we're looking for (please read the comments in the PR) we're happy to give you points as well 🚀

**Comment by pratik-codes** [comment]
@jobenjada sure let me give it a shot.

**Comment by jobenjada** [comment]
@pratik-codes since you're already working on hidden fields, please prioritize this. Would love to get hidden fields merged asap  🚀
