### ISSUE TITLE
[FormTribe 🔥][750 Points] Hidden Fields

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#887]
### Welcome to the FormTribe

This issue will get you **750 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------

Users want to submit additional (meta-) data along with a link survey without having to set an attribute

### Describe the solution you'd like

We allow custom hidden fields in link surveys that can be set via search parameters in the URL.

### Feature Description

- A user adds a hidden field to a survey in the survey editor.
In the settings, the user assigns a name to the hidden field (make sure they are unique and don't conflict with current features and forbid names like userId& suid and the questionIds of the current survey.
- In link surveys, the content of the hidden field can be set via an URL search param follow this schema: "?hiddenfieldname=hiddenfieldcontent"
- We only support this in link surveys for now. We can add an option for web-app surveys later.
- The content is stored in the response data and displayed in the Summary and Response tabs

### Notes

- This is only for link surveys, not for in app surveys 
- We already have the whole logic to take data from the URL and add it to the submission in the Link Prefilling feature built by Piyush. Reuse as much of this logic as possible.
- Add the string to the submission via URL parameters

### Tasks

1. Add a new Card called "Hidden Field" with Hero Icon EyeSlash which is only visible  if the `survey type === "linkSurvey"` below the `Thank You Card` in the Survey Editor.  In this card, users can add several hidden fields by adding a hidden field Id:
<img width="901" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/a6f1da48-8690-4db0-b7fe-94af6ea1be0d">

2. We built the UI you need already for our tagging system:
<img width="555" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/0410222d-8e8f-49c1-9ecf-2954ae469475">

While building this, make sure to validate the inputs as follows:

- Do not allow spaces
- Do not allow `userId` & `suid`
- Do not allow any of the question Ids of the current survey since they can be used for link prefilling

User can add and remove hidden fields with the UI.

3. Now that the settings are complete, let's make it possible to attach a value to the hidden field Id. To be able to do that, allow people to prefill the hidden fields via URL parameters in the LinkSurvey.tsx. We already have quite some link prefilling logic in the file, it should be pretty straight forward 👍 

7. Test extensively with User Identification, Single Use Links, Prefilling of first question

**Comment by hariscs** [comment]
Hey @jobenjada I'm working on this

**Comment by jobenjada** [comment]
sweet, excited to see your submission!

**Comment by ykburda** [comment]
Burning functionality 💯

**Comment by pratik-codes** [comment]
@jobenjada are these issue first come first basis or the person should be assigned and he/she will only work this?

**Comment by pratik-codes** [comment]
Hey, @jobenjada what happens when on the right preview survey when the user clicks on the hiddenlinks dropdown. Nothing right? We should not be showing anything in this case?

**Comment by pratik-codes** [comment]
![Screenshot 2023-10-02 at 3 58 59 AM](https://github.com/formbricks/formbricks/assets/64960569/89bc990a-3b7c-47a7-9f7b-7daac97cf757)

I have created a custom component from button this is how its looking.

**Comment by jobenjada** [comment]
@hariscs what is the status? 

We're changing our process a bit to prevent redundant work.

**@hariscs  and @pratik-codes  please open a draft PR to see your current progress asap.**

We will then decide if we work closely with you to get it merged or give the issue up for another contribution again 🙏

**Comment by United1l** [comment]
@jobenjada what's the status of this issue?

**Comment by pratik-codes** [comment]
@jobenjada sharing updates here have made the component of hidden fields it gets added to the survey payload we have in where all the other details for survey is stored. But the when clicked on save the api gives 500. I think there would be changes required in the api as well. sharing the pr and progress here.

**Comment by United1l** [comment]
@pratik-codes I think the issue was assigned to @hariscs therefore a status update should at least come from him or @jobenjada no offense.

**Comment by hariscs** [comment]
Hey guys, sorry for not being very active here recently. It's been an incredibly busy week at work. I will definitely open a PR this weekend and complete this task ✌️

**Comment by United1l** [comment]
@hariscs don't worry man, take your time. And if you're inconvenienced, @pratik-codes and I got you :)

**Comment by jobenjada** [comment]
@hariscs @United1l  and @pratik-codes Love the collaborative spirit here! Would love to see a PR ready for review over the weekend :) We will make sure to assign points to all of you dependent on your contribution 🙏

**Comment by jobenjada** [comment]
@hariscs Would be super happy for you to take the lead on this one, the current draft PR is showing a lack of relevant experience 🙏

**Comment by jobenjada** [comment]
@United1l I have updated the description to be more clear and added the mock ups you're asking for. Please let me know if this is sufficient!

I have also incread the number of points to 750. Please let me know if you need help getting this shipped then we can find someone from the community to get you rolling :)

**Comment by United1l** [comment]
Copy that @jobenjada, I'm getting on it. Appreciate the mock ups

**Comment by United1l** [comment]
@jobenjada In the new mockup you've added the "QuestionDropDown" component which moves, duplicates or delete a field.
I get the duplicate and deleting part but I'm not quite sure how to add the moving logic since technically the HiddenFieldCard will be displayed under the ThankYouCard and not as part of the QuestionCard

**Comment by United1l** [comment]
And I'm not familiar with the tagging system you're talking about. Is it the link prefilling feature? Searched the docs and couldn't find any info. Anyways other than the UI information, I'd like to know the type of questions that can be asked in a hidden survey.

**Comment by United1l** [comment]
Most of the UI features have already been established I just need to get a clear grasp of the functionalities and I'll complete it

**Comment by United1l** [comment]
Yes I'm on the Discord server @jobenjada. And after the draft I haven't opened any PR yet because of the above questions. I now understand the hidden fields and their purpose better. And I'll take note of UI information you gave above. Thanks :)

**Comment by mattinannt** [comment]
Updated the ticket description: after intensive discussion we decided against a question type for hidden fields to avoid unnecessary custom logic that is different from other question types.
Please check the ticket description for further information 😊

**Comment by gupta-piyush19** [comment]
Hi @jobenjada, this issue is long stacked up and seems to be inactive now. I'd love to pick this up.

**Comment by jobenjada** [comment]
its live :)
