### ISSUE TITLE
[FormTribe 🔥][500 Points] Integration: Airtable

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#888]
### Welcome to the FormTribe

This issue will get you **500 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------

### Is your feature request related to a problem? Please describe.

Users want to send submission data directly to Airtable instead of going via Zapier etc. Privacy-focussed users want to keep the number of companies touching their data to a minimum.

### Describe the solution you'd like

Build native Airtable integration using OAuth.

### Notes

- We have a Google Sheets integration which can be copied and adapted.
- Here are [Sheets integration docs](https://formbricks.com/docs/integrations/google-sheets)

#### Tasks

- Develop a direct Airtable Integration which has all the capabilities the Google Sheets integration has
- Make sure to add the needed env variables etc. for self-hosters to be able to use it

**Comment by Vishrut19** [comment]
Can I work on this issue?

**Comment by jobenjada** [comment]
Its yours!

**Comment by G3root** [comment]
Started working on this

**Comment by Vishrut19** [comment]
I am already assigned and working on it bro !

**Comment by jobenjada** [comment]
@Vishrut19  and @G3root  please open a draft PR with your current progress.

We will then decide who we will work closely with to get this shipped asap.

Thanks!! :)
