### ISSUE TITLE
[FormTribe 🔥][500 Points] Display Drop-Offs better

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#891]
### Welcome to the FormTribe

This issue will get you **500 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------

### Is your feature request related to a problem? Please describe.

Users want to know when respondents drop out of surveys. Currently, we are not displaying this info in an intuitive way.

### Describe the solution you'd like

Build a more intuitive way to understand drop offs

<img width="1339" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/d5b0fbdf-5c76-4fbe-a701-97028844f8fe">

### How drop off is calculated

When a question remains unanswered we assume that the user dropped off during that question. For example when the page is loaded and a display is created but the first question did not get answered, the user dropped out on the first question. Similarly, when we have answers for Q1 and Q2 but not Q3, we assume the user dropped out on Q3.

Generally drop off is calculated like so: All who answered Q1/all who answered Q2. So if 100 people start the survey and 80 people answer Q2 we have 100/80. In the screenshot you can see this in practice: Even though on the 1st and 3rd question 20 people dropped out, in Q1 it's 20% drop-off while in Q3 it increased to 25% drop-off.

For the calculation of the drop off per question we only take into account the number of people who reached this specific questions. Since we don't track if a question was displayed, we 'reverse engineer' this KPI based on the assumption described above.

### Notes

We store the submission in the local storage. If a user comes back to continue filling out a survey on the same device and browser, the drop off is recalculated. With every new answer, the drop-off consequently moves to the back. If the survey gets completed, there is no more drop off 😃

**Comment by kelvinparmar** [comment]
Hey @jobenjada I am interested in this issue

**Comment by Ashu999** [comment]
how to make more intuitive:
1. Add tooltip icon right next to the column name, to concisely define what it means.
example: - Views: no. of people who saw this question
                - Drop-off: no. of people who didn't answer this question
2. Add similar tooltips to the InfoCards (Displays, Stats, Responses etc.)
3. Drop-off and Drop-off percentage should be separate columns

here is an example of tooltip icon: 
![image](https://github.com/formbricks/formbricks/assets/28844854/a8e003e0-c12d-4b6f-a1f5-365caca93ba2)

let me know what you think @jobenjada

**Comment by gupta-piyush19** [comment]
![image](https://github.com/formbricks/formbricks/assets/56182734/2ee1e0ce-fe23-402a-9935-a0cef6ff59cd)
@jobenjada What's the logic for this overall dropoff % card?

**Comment by jobenjada** [comment]
@kelvinparmar great, looking forward to your PR!

@Ashu999 We do have tooltips, check them out :)

@gupta-piyus19 Dhru will follow up shortly

**Comment by Dhruwang** [comment]
Hey @gupta-piyush19 😊
If you want to calculate overall drop off percentage, its just number of people who started but didn't completed the survey(also includes peoples that have seen the survey but didn't respond)

Mathematically it can be calculate as ((Number of displays - Number of completed responses)/Number of displays )x100%

**Comment by kelvinparmar** [comment]
> @kelvinparmar great, looking forward to your PR!


But where is the file in that i have to change i am not able to find it

**Comment by ykburda** [comment]
Very interesting and confusing. Maybe this is because of sample ui design. All KPIs need perfect clearification.

**Comment by jobenjada** [comment]
We have promising PR up from Piyush 🚀 Will work with him to get it merged.

⚠️ Please dont work on this until further notice ⚠️

**Comment by kelvinparmar** [comment]
I am working on this PR @jobenjada

**Comment by gupta-piyush19** [comment]
@kelvinparmar Is there anything that you think is remaining in my PR? I'll probably add that if the changes are minor.

**Comment by kelvinparmar** [comment]
so are you working on this PR ? @gupta-piyush19

**Comment by gupta-piyush19** [comment]
@kelvinparmar I am done from my side; nothing major remains, per my understanding. You can work on any other issue to avoid creating the same feature.

**Comment by kelvinparmar** [comment]
Ohk @gupta-piyush19

**Comment by ykburda** [comment]
It seems this is merged to main and live in cloud. But it is calculating totally wrong. Just to inform.
![image](https://github.com/formbricks/formbricks/assets/141973350/21044ce3-b552-44fb-9c16-cfb75caed48e)
