### ISSUE TITLE
[FormTribe 🔥][250 Points] Add corresponding icons to type indicator

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#892]
### Welcome to the FormTribe

This issue will get you **500 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------

On the survey summary page, the different question types are not easily distinguishable

### Describe the solution you'd like

Add the corresponding icons

Here you can see the hero icons we're using for the different question types:

<img width="690" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/9ba464f4-8271-4d18-a892-03bebcf4b0d9">

And here you can see where they are missing:

<img width="1415" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/2b4b0b2e-ab0e-41ff-aa66-1d44a27bbb6b">

### Please note!
We already have a central place at apps/web/lib/questions.ts to store the information about all question types including name, description and icon. Please make sure to use this single-source-of-truth for every display of the question type + icon.

### Task

- Add them for all question types

**Comment by probablyArth** [comment]
I'd like to get assigned!

**Comment by jobenjada** [comment]
just ship it! :)

**Comment by adityadeshlahre** [comment]
If any further fix is required please let me know. Its my first contribution 
May have done silly mistakes :smile: 
Thank You

**Comment by jobenjada** [comment]
Hey @adityadeshlahre you're the first to ship and it looks pretty good. Please make the refactoring I requested in the PR so that I can merge and give you the points :)

**Comment by heysagnik** [comment]
I want to work on this issue
