### ISSUE TITLE
[BUG] Add action not working for app surveys

### ISSUE THREAD

**Issue by gupta-piyush19** [formbricks/formbricks#896]
### Issue Summary

`Add Action` action is not working in Survey Trigger for web app surveys.

### Steps to Reproduce

1. Open survey editor for any survey
2. Click on settings tab
3. Select `Web App` under `How to ask`.
4. Click on `Survey Trigger` and click on Empty box after 'When', then click on `Add Action`
5. App will break.

### Expected behavior

It should open the modal to create/select Action.

### Other information

<details><summary>Error</summary>
<p>
 Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
</p>
</details> 

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/56182734/2efd3fae-dacb-47d5-b392-5d1aa7e99375)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: macOS
- Node:v18.16.0
- npm: 9.5.1
```

**Comment by ShubhamPalriwala** [comment]
Thanks a ton for finding that out @gupta-piyush19, we have made a potential fix and once it's merged, you should be able to add actions directly from the survey editor again

**Comment by gupta-piyush19** [comment]
Got it! Thanks, @ShubhamPalriwala for the quick response.
