### ISSUE TITLE
[FormTribe 🔥][BUG][150 Points] Multi Select Question not skippable when optional

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#901]
### Welcome to the FormTribe

This issue will get you **150 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------

When a multi select question is not set to required, it is still not skippable:

https://tella.video/johanness-video-6fat

### Steps to Reproduce

1. Create a survey with a multi select question
2. Toggle off "Required"
3. Try to skip to next question

### Expected behavior

Skipping to next question

### Other information

You can see how its done at the Single Select question type :)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Mac
- Browser: Arc / Chrome
```

**Comment by Dhoni77** [comment]
Hi @jobenjada  can I take up this issue

**Comment by heysagnik** [comment]
I would love to work on this issue

**Comment by Vishrut19** [comment]
Hey @jobenjada can I raise another PR on this or this is the final PR?

**Comment by jobenjada** [comment]
@Vishrut19 generally, you can! We will comment here, when we have a promising PR open which is close to being merged. 

But with 2 PRs open now, its not very likely to get yours merged. Fancy a different ticket? 🤓

**Comment by Vishrut19** [comment]
okay got it thanks for letting me know
