### ISSUE TITLE
Input Validation (Code)

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#91]
### Is your proposal related to a problem?

A snoopForms user needs customizable input validation for text & number fields.

### Describe the solution you'd like

Add option for custom regex to input (text, textarea, number) fields

**Comment by eunbin777** [comment]
I want to solve this issue. 
It seems difficult to proceed with the input validation only by implementing additional options to input custom regular expressions in the input field. I wonder if I need to write the code for the part that performs the input validation to solve the issue.
