### ISSUE TITLE
[BUG] Single Use Link Preview is not correctly functioning

### ISSUE THREAD

**Issue by ykburda** [formbricks/formbricks#935]
### Issue Summary

System has missing character "&" in the link. It is causing real survey not preview mode.

### Steps to Reproduce

Create a single use survey and try to preview.

### Expected behavior

Link will not be counted and will no post db survey results. It should only preview.

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/141973350/cab3e702-5dea-45fe-adbd-1b6ee624b918)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:windows 10
- Node:
- npm:
```

**Comment by heysagnik** [comment]
I would love to work on this issue

**Comment by heysagnik** [comment]
I have followed the steps to reproduce the issue, but not able to reproduce it. 
![image](https://github.com/formbricks/formbricks/assets/70798495/22dfb13d-0767-4fe5-b5c9-a34a44bcb6ee)
I also checked the code it is also correctly done.
![image](https://github.com/formbricks/formbricks/assets/70798495/bfb1984f-4393-466e-99a6-4c661c0cf1d3)

**Comment by ykburda** [comment]
Singleuse survey link should be enabled.
![image](https://github.com/formbricks/formbricks/assets/141973350/4d7c8046-cc6c-4a73-b1a9-bf07e36e3dd8)

**Comment by jobenjada** [comment]
@heysagnik want to open a PR to fix this? :) I've assigned you!
