### ISSUE TITLE
[BUG] Link Button Different Behaviour on different tabs

### ISSUE THREAD

**Issue by ykburda** [formbricks/formbricks#936]
### Issue Summary

System is showing two different link page based on selected tab on survey. This happens if singleuse survey is enabled.

### Steps to Reproduce

*Select "summary" tab and click "Link" button.
![image](https://github.com/formbricks/formbricks/assets/141973350/2b1b2f79-7d8b-4ef6-89d4-b0d8f7632d65)

-You will see below page which one is correct.
![image](https://github.com/formbricks/formbricks/assets/141973350/9e45cd4e-1279-419f-a623-aa5989b595c4)

* Select "Responses" tab and click "Link" button.
![image](https://github.com/formbricks/formbricks/assets/141973350/e8fa7a3f-542e-4db8-aa35-f1afcdc4ce5b)

-You will see below page which one is not correct.
![image](https://github.com/formbricks/formbricks/assets/141973350/25ffea19-816a-45ab-b47c-d6ac4e62cb61)

### Expected behavior

Singleuse Survey link popup should be shown in both cases.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by heysagnik** [comment]
I am interested

**Comment by jobenjada** [comment]
@Dhruwang is fixing it, its related to our new single survey link feature :)

**Comment by jobenjada** [comment]
@ykburda Thanks for sharing! Are you participating in the Formtribe Hackathon?

Would award you +50 Points for sharing this ⭐

**Comment by heysagnik** [comment]
@jobenjada can we add a beacon text "`expired`" when someone uses a link 
And replace "`regenerate`" with "`Generate a new link`" _[which just add a new link to the list]_

**Comment by jobenjada** [comment]
@heysagnik we're not storing the links we generate if I recall correctly. So your UX tweak would require quite some technical overhead which wouldnt be worth it :)

**Comment by heysagnik** [comment]
> @heysagnik we're not storing the links we generate if I recall correctly. So your UX tweak would require quite some technical overhead which wouldnt be worth it :)

Ok

**Comment by jobenjada** [comment]
We have a new embedding xp and we didnt design a signle link UI yet

<img width="1006" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/2252261b-97b1-418d-92b2-3d89298a7753">
