### ISSUE TITLE
[BUG][FormTribe 🔥][100 Points] Changing Twitter logo to X

### ISSUE THREAD

**Issue by Roar022** [formbricks/formbricks#941]
### Issue Summary

As twitter has changed its logo to **X**. Therefore it is necessary for website to change twitter logo wherever it is used. 

### Steps to Reproduce

1. went to `https://formbricks.com/`
2. Move to footer section of website.

### Expected behavior

Twitter logo should be changed to **`X`**.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Linux
- Node:v20.6.1
- npm:10.1.0
```

**Comment by Roar022** [comment]
Please assign this issue to me. I would like to solve this issue.

**Comment by Shahidkhatrii** [comment]
Hi @jobenjada I would like to work on this issue

**Comment by jobenjada** [comment]
@Roar022 you got it :) For the merged PR I'll assign you +100 points :)

**Comment by Archit5655** [comment]
Please assign it to me If the other person doesn't revert back 😄.

**Comment by ratishjain12** [comment]
@jobenjada assigne me this issue if it is still open I can send the PR quickly thank you :)

**Comment by jobenjada** [comment]
Merged, thanks!
