### ISSUE TITLE
[BUG] Url Shortener is not functioning in Single use Surveys

### ISSUE THREAD

**Issue by ykburda** [formbricks/formbricks#961]
### Issue Summary

I have seen url shortener is added to navigation. I just tested a simple url and got "only formbricks surveys allowed" messages wrongly. Maybe it is relevant with singleuse link enabled in settings of survey. Because it is starting with app.formbricks.com
I tested with "https://app.formbricks.com/s/clkgksh641bzlo20huhdlagb2?suId=530c34419c24ee9ffbcde84e96873179571a7c12072fa2b4b3b1b7283ad91ce2" url address.

### Steps to Reproduce

1-Select url shortener from navbar.
2-Paste https://app.formbricks.com/s/clkgksh641bzlo20huhdlagb2?suId=530c34419c24ee9ffbcde84e96873179571a7c12072fa2b4b3b1b7283ad91ce2
3-get error.

### Expected behavior

Url must be shortened correctly

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/141973350/bc716bb5-e907-4bdd-9620-e805cd161284)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by jobenjada** [comment]
@Dhruwang is investigating and working on a fix :)
