### ISSUE TITLE
[FEATURE] API Requests: Shorten URL, Responses by People ID, Responses by Date

### ISSUE THREAD

**Issue by ykburda** [formbricks/formbricks#963]
### Is your feature request related to a problem? Please describe.

It will be good to get below API's.
1- shortenurl api
2-responses by people id api
3-responses by date api

### Describe the solution you'd like

1-Shortenurl api : We will give long url as input  and get short url as output 
2-Responses by people id api : We will give people id as input and get all responses as output
3-Responses by date api : We will give date as input and get all responses of that date as output. Kind of request daily responses.

### Describe alternatives you've considered

1-Shortenurl api : Now we can only manually get shortened url from app. There is no way to get it. 
2-Responses by people id: Now we can only get all responses of a survey id. If we get 100k responses. We will download all and filter it somehow.
3-Responses by date : Now we can only get all responses of a survey id. If we get 100k responses. We will download all and filter it somehow. So if we try to get daily ,it will be hardened day by day.Maybe 30 days later 300k responses download to get 1000 for a daily basis.

**Comment by jobenjada** [comment]
@ykburda this is not a priority for us because we aim to offer all of the analysing capability within Formbricks

**Comment by mattinannt** [comment]
Closing this for now due to inactivity. We will open this again when one of the APIs is requested for a production use case.
