### ISSUE TITLE
[BUG][100 Points] I can't proceed with the form

### ISSUE THREAD

**Issue by EduardoNoronha31** [formbricks/formbricks#964]
### Issue Summary

When I click on the next button nothing happens. This error appears on the console: 
**Uncaught TypeError: Cannot read properties of null (reading 'includes')**

### Steps to Reproduce

1. Follow the documentation using [Vue.js](https://formbricks.com/docs/getting-started/framework-guides#vue-js)

![image](https://github.com/formbricks/formbricks/assets/78568517/5f98df89-08a6-4b9d-9b43-992e822f4cfa)

2. Click the next button and check the console

### Expected behavior

I expected the normal navigation flow in the form

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/78568517/a1fa151a-c1bb-41b1-a7fb-41d2148d09ee)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Linux Ubuntu
- Node: 16.17.0
- npm: 8.15.0
- Browser: Google Chrome - Version 117.0.5938.132 (Official Build) (64-bit)
- @formbricks/js: 1.0.4
```

**Comment by jobenjada** [comment]
hey @EduardoNoronha31 thanks for letting us know 🙏 Are you participating in the FormTribe hackathon? Would award you +100 points for sharing this bug with us :)

@Dhruwang please investigate and fix

**Comment by jobenjada** [comment]
@Dhruwang any updates? :)

**Comment by prasoonmhwr** [comment]
@jobenjada if it is open may i work on this

**Comment by jobenjada** [comment]
@prasoonmhwr it should be solved already, just confirming :)

**Comment by prasoonmhwr** [comment]
> @prasoonmhwr it should be solved already, just confirming :)

ok no problem

**Comment by 3xp10it3r** [comment]
Hey @jobenjada, Its active ?
