### ISSUE TITLE
[BUG]  Question Advanced Settings: Linked button label and Back label

### ISSUE THREAD

**Issue by edersilva78** [formbricks/formbricks#965]
### Issue Summary

When editing `Button Label`  on the Advanced Settings section of a survey  question the `Back Label` text also is changed.
Tested with a new survey and an existing one.
Changes to the `Back Label` field are not linked to the first field.

Also, new questions are created with the "Back Label" pre filled with Finish.

### Steps to Reproduce

1. Edit a question
2. Click on "Show Advanced Settings"
3. Click on the edit "Button Label" and type something
3.1. If it is the first time, the same text is entered in the "Back Label" edit.
3.2. If not, the "Button Label" edit text does not change. To the "Back Label" edit a single characther is appended and changes as you type. (the length does not change, besides the new character)

### Expected behavior

The edit componnents are not linked. The Back Label default is "Back"

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/7780778/71eb2311-34ff-44d7-a998-5f1ac768b64d)
![image](https://github.com/formbricks/formbricks/assets/7780778/63256800-ec7e-4a33-b6b9-64d59341b342)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Pop!_OS 22.04 LTS
- Browser: Chrome
- Version 117.0.5938.132 (Official Build) (64-bit)
```

**Comment by jobenjada** [comment]
@edersilva78 its fixed,  thanks for letting us know!

@ShubhamPalriwala thanks!! :)
