### ISSUE TITLE
[BUG][FormTribe 🔥][200 Points] Survey preview rerenders when name updates

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#968]
### Welcome to the FormTribe

This issue will get you **200 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Issue Summary

The survey preview in the survey editor rerenders on every key stroke in the survey name field:

https://tella.video/johanness-video-6xtg

If you type fast, it dies.

### Steps to Reproduce

1. Go to the survey editor
2. Type in a new name
3. Watch the preview flicker and die :)

### Expected behavior

Don't rerender when the name changes

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by zaCKoZAck0** [comment]
I would like to work on it.

**Comment by Dhoni77** [comment]
Hi can I take this task @jobenjada

**Comment by jobenjada** [comment]
@zaCKoZAck0 you got it! Please open a draft PR within 24h for us to follow your progress :)
