### ISSUE TITLE
[BUG][FormTribe 🔥][150 Points] New teams are not listed in teams list

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#969]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Issue Summary

When creating a new team, it is not listed in the teams overview in the top menu:

https://tella.video/johanness-video-57q7

### Steps to Reproduce

1. Create a new team
2. Look for it in the team switch

### Expected behavior

Each new team should appear in the team switch

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by adityadeshlahre** [comment]
i would i like to work on this :smile:

**Comment by jobenjada** [comment]
damn son have you been camping on our issue page? :P It's yours, love the speed!

**Comment by anjy7** [comment]
Hey, @adityadeshlahre - while I was having a look at this issue after the discord mention, I tried to reproduce this and I think I might know what's the issue - currently we are using the unstable_cache function provided by nextjs to cache the all teams that we fetch. I know this is efficient but it seems this api function is still under development and not recommended to use in prod, as stated in the docs here -
![Screenshot from 2023-10-06 21-19-57](https://github.com/formbricks/formbricks/assets/92802904/3c082866-1251-41ed-ae69-8b66d6a0296b)

I confirmed it by removing this function and I am able to get all the teams as the desired behavior. Although removing the function might not be the best approach, I would suggest you to try out alternative methods to cache..

This is the file I'm talking about - /workspace/formbricks/packages/lib/team/service.ts

**Comment by adityadeshlahre** [comment]
@jobenjada i was trying to implement prefetching at `<TTeam>` it was breaking the application. As props of Navigations.tsx [workspace/formbricks/apps/web/app/(app)/environments/[environmentId]/components/Navigation.tsx ] 
using unstable_cache method i m not able implement it. Could you please help me with some information so that i can proceed !

Thank You

**Comment by jobenjada** [comment]
@anjy7 I think unstable cache could be the culprit. Do you see any downside of disabling it for the teams endpoint?

**Comment by adityadeshlahre** [comment]
@jobenjada @anjy7  yes, i was implemented the same but number of fetches could go up! thats the only down side of that !

**Comment by anjy7** [comment]
> @jobenjada @anjy7 yes, i was implemented the same but number of fetches could go up! thats the only down side of that !
> 
> ![image](https://user-images.githubusercontent.com/132184385/273298860-af6870cd-0e26-4ac4-91c9-debde4c629de.png)

I'll try to find a work around and let you know @adityadeshlahre

**Comment by adityadeshlahre** [comment]
@anjy7 and @jobenjada by running [ pnpm clean && pnpm build ] by running this some how this issue is resolved ! :smile:
