### ISSUE TITLE
Refactor NumberQuestion

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#97]
Refactor/Rewrite the NumberQuestion Component of EditorJS/NoCode-Editor to be better maintainable.

The NumberQuestion Component (`snoopforms/components/editorjs/tools/NumberQuestion.tsx`) was build using an old pattern for EditorJS. New Components like the MultipleChoiceQuestion use a new approach which works much better with React. The old components needs to be refactored / rewritten to work using the newer approach.
For that you can copy a newer component as a scaffolding and insert the logic and UI components of the NumberQuestion.

**Comment by kymppi** [comment]
Hey, im currently working on this. PR in an hour :P

**Comment by kymppi** [comment]
https://github.com/formbricks/snoopforms/pull/120
