### ISSUE TITLE
[DOCS][FormTribe 🔥][200 Points] Docs for Single Use Links

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#971]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Is your feature request related to a problem? Please describe.

We have shipped single use links for link surveys to make sure that each person can only submit a survey once.

As of now, we're lacking documentation for this feature.

### Describe the solution you'd like

1. Write concise but complete documentation of the Single Use Links feature incl. Screenshots.
2. Add it to the Link Survey chapter in our Docs

<img width="261" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/5f52bbe4-510a-4326-a744-bb3de5b7c3d5">

Notes:
- The UI explains the feature quite well
- Make sure to explain how URL encryption works via the corresponding env variable:
<img width="526" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/4306d7b4-3258-455c-8d58-369e4e0a0413">

- Currentl, the suID sits next to the completed tag:
<img width="1361" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/864aca27-d3f7-4c4b-9534-c02052e71fd5">

We are currently reworking our response cards and it will move into the metadata section which opens on hovering over the Avatar:
<img width="448" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/e000317d-444a-4085-a30b-18fb8da3d8d2">

Additionally, we're updating the embedding modal for Single Use Links: https://github.com/formbricks/formbricks/pull/952

This is why you'll need to update 2 screenshots, once the corresponding PRs are merged :)

But 95% of the work you can do already, so we decided to open the issue today.

### Thanks!

**Comment by aman44444** [comment]
@jobenjada i want to work on this feature can you please assign this to me?

**Comment by jobenjada** [comment]
It's yours! Please submit a draft PR within the next 24h for us to have a look at the progress :)

**Comment by Vishrut19** [comment]
If @jobenjada @aman44444 is working then its fine else please assign me
