### ISSUE TITLE
[FEATURE][FormTribe 🔥][150 Points] Add a not-connected state to the survey state indicator

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#972]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Is your feature request related to a problem? Please describe.

Currently, we do not indicate a status of an in-app survey when the enduser app is not connected with Formbricks:

<img width="258" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/ef73e242-0fc9-47ce-93a4-677e1a548501">

Just to illustrate, this is the draft state:
<img width="253" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/1cef4058-5150-46d2-be3c-277d225a104f">

And this is the connected state:
<img width="248" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/b8fecc97-d6f8-41bf-889f-0e015174e058">

### Describe the solution you'd like

This is the state we want, if the Formbricks widget setup was not yet completed:

<img width="594" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/5cc39b1f-dd69-4ed9-8020-19f50aeeb5c6">

### Additional context

1. In our codebase, we have a file called `SurveyStatusIndicator` - this is where you add it.

2. The condition which this is based on is a global variabale called `widgetSetupComplete` which is used like so: `environment.widgetSetupCompleted` - just search for this expression to see how to use it.

3. The icon is exclamation-triangle from HeroIcon solid

Should be pretty straightforward! :)

**Comment by prasoonmhwr** [comment]
May I work on this

**Comment by anjy7** [comment]
I would like to take this one @jobenjada

**Comment by jobenjada** [comment]
@prasoonmhwr it's yours :) Please do this within 24h, shouldnt take long ;)

**Comment by prasoonmhwr** [comment]
@jobenjada just to confirm we need to show this only for in-app product survey and not for linked survey right?

**Comment by jobenjada** [comment]
correct!

**Comment by prasoonmhwr** [comment]
Here is the draft PR https://github.com/formbricks/formbricks/pull/975

**Comment by jobenjada** [comment]
its merged, thanks! :)
