### ISSUE TITLE
[FEATURE][FormTribe 🔥][500 Points] Setup Storybook in our monorepo

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#973]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Is your feature request related to a problem? Please describe.

We plan to develop our upcoming component system within Storybook. This allows us to move the complete app to the new components within a short amount of time.

### Describe the solution you'd like

Follow Storybook setup best practices to set it up in our monorepo.

Please note ⚠️
This task requires quite some experience and knowledge around mono repos, turbo repo, etc. It's likely not super easy to get right 🤓 

Tasks

- Add a new folder in our apps directory called `storybook`
- Setup an instance of Storybook which runs smoothly locally and hosted on Vercel
- Do not start the storybook app with `pnpm go`
- Let users start it with `pnpm dev --filter=storybook`
- To setup Storybook, find the `Button` component in `@formbricks/ui` and transfer it to Storybook. Make senseful setup decision based on best practices or your own experience.

### Thanks!

**Comment by anjy7** [comment]
Can I have a try at this?

**Comment by jobenjada** [comment]
Have you worked with Storybook before? Feel free to open a draft PR once you made relevant progress. However, I'll keep the issue open for now to signal to someone with relevant experience that we're still open for support :) 

Maybe (s)he can help you get the job done - we love a good collab!

**Comment by anjy7** [comment]
> Have you worked with Storybook before? Feel free to open a draft PR once you made relevant progress. However, I'll keep the issue open for now to signal to someone with relevant experience that we're still open for support :)
> 
> Maybe (s)he can help you get the job done - we love a good collab!

I have had worked on a project that used storybook, will try to open a draft PR. And yeah Collab sounds great..
