### ISSUE TITLE
[BUG]: No Contributors are mentioned in documentation( readme file)

### ISSUE THREAD

**Issue by mohitd404** [formbricks/formbricks#974]
### Issue Summary

No Contributors are mentioned in the documentation ( readme file) 

### Steps to Reproduce

1.  will use src="https://contrib.rocks website to update contributors lively.

### Expected behavior

contributors will be shown in the documentation section !

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: windows
- Node:
- npm:
```

**Comment by mohitd404** [comment]
@chetan @kof please assign this issue to me !

**Comment by jobenjada** [comment]
Nice idea! +100 points for you once this is merged ❤️

**Comment by mohitd404** [comment]
@jobenjada I have made the changes! please review it!  Thank you so much!
