### ISSUE TITLE
[BUG][50 Points] The navbar buttons for github and go to app are not responsive

### ISSUE THREAD

**Issue by ratishjain12** [formbricks/formbricks#977]
### Issue Summary

@jobenjada I want to improve this part 
![image](https://github.com/formbricks/formbricks/assets/43003421/3fb5adce-d789-4e2a-8742-9508d115d860)

Kindly assign me this issue thank you :)

### Steps to Reproduce

-

### Expected behavior

the button size should not be changing and github button should not disappear I would like to fix it.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by abhay-raj19** [comment]
pls assign me @ratishjain12 i will make it look more interesting. and will enhance up the UI with latest good logo for the same

**Comment by ratishjain12** [comment]
@abhay-raj19 I want to solve this issue thats why I have opened it I am not the maintainer

**Comment by abhay-raj19** [comment]
but i liked your issue more interesting and insightful and I will give good outputs for it in less time that's why I commented on it

@chetan pls assign me up the issue for good and fast changes

**Comment by ratishjain12** [comment]
@abhay-raj19 go somewhere else or create your own issues buddy I think you are new to open source

**Comment by jobenjada** [comment]
@ratishjain12 sorry for the delay, have been traveling. Please go for it! 

+50 points for flagging this issue 🙏

**Comment by ratishjain12** [comment]
> @ratishjain12 sorry for the delay, have been traveling. Please go for it! 
> 
> +50 points for flagging this issue 🙏 

On it 👍

**Comment by jobenjada** [comment]
its solved
