### ISSUE TITLE
[FEATURE] Change Twitter logo to X

### ISSUE THREAD

**Issue by blindaks** [formbricks/formbricks#978]
### Is your feature request related to a problem? Please describe.

I wish to change the twitter logo to X.

### Describe the solution you'd like

Remove the old logo.

**Comment by blindaks** [comment]
Please assign this issue to me.

**Comment by prasoonmhwr** [comment]
@blindaks  this is a duplicate issue same , you can find the original one here https://github.com/formbricks/formbricks/issues/941

**Comment by AniketP04** [comment]
I would like to contribute on this issue .kindly assign it to me

**Comment by jobenjada** [comment]
its solved :)
