### ISSUE TITLE
Refactor WebsiteQuestion Component

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#98]
Refactor/Rewrite the WebsiteQuestion Component of EditorJS/NoCode-Editor to be better maintainable.

The WebsiteQuestion Component (`snoopforms/components/editorjs/tools/WebsiteQuestion.tsx`) was build using an old pattern for EditorJS. New Components like the MultipleChoiceQuestion use a new approach which works much better with React. The old components needs to be refactored / rewritten to work using the newer approach.
For that you can copy a newer component as a scaffolding and insert the logic and UI components of the WebsiteQuestion.

**Comment by kymppi** [comment]
Hey im currently working on this. PR in an hour :P

**Comment by kymppi** [comment]
https://github.com/formbricks/snoopforms/pull/120
