### ISSUE TITLE
[BUG][FormTribe 🔥][100 Points] Removed user from Team, but user can select team

### ISSUE THREAD

**Issue by edersilva78** [formbricks/formbricks#983]
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Issue Summary

The team is available via the user menu
![image](https://github.com/formbricks/formbricks/assets/7780778/03ed16ff-6048-4997-a8c0-a98b9cc0098d)

If the user tries to select it, the server throws an error 500

### Steps to Reproduce

1. Remove the user "U" from a team "T"
2. Login with the user "U" credentials
3. Select the team "T" from the user menu

### Expected behavior

The team "T" should not be listed in the user's Teams

### Other information

Formbricks version: 1.1.0, official docker image

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by anjy7** [comment]
Yeah I think this is because of the same thing I mentioned in issue #969. Shall I take this one? @jobenjada @edersilva78

**Comment by edersilva78** [comment]
> Yeah I think this is because of the same thing I mentioned in issue #969. Shall I take this one? @jobenjada @edersilva78

I think it is.
I just added myself to a new team and it did not show on the menu.
A logged out (again) and it is there, but I've got an error message

```
Error loading resources
This resource doesn't exist or you don't have the neccessary rights to access it.
```

![image](https://github.com/formbricks/formbricks/assets/7780778/b3e19e20-a51d-4439-ab01-828a2a873a9b)

**Comment by anjy7** [comment]
> > Yeah I think this is because of the same thing I mentioned in issue #969. Shall I take this one? @jobenjada @edersilva78
> 
> I think it is. I just added myself to a new team and it did not show on the menu. A logged out (again) and it is there, but I've got an error message
> 
> ```
> Error loading resources
> This resource doesn't exist or you don't have the neccessary rights to access it.
> ```
> 
> ![image](https://user-images.githubusercontent.com/7780778/273302815-b3e19e20-a51d-4439-ab01-828a2a873a9b.png)

Yup, thanks for letting us know

**Comment by adityadeshlahre** [comment]
@anjy7 and @edersilva78 you guys are right this issue is fixed with changes on the PR #985 ! :smile: 

Here is the video with that fix !

https://www.loom.com/share/67f22827e03d4a0eb4ff1c532257570f?sid=5bd1389a-6651-4eb1-8368-cee97dc6921f

**Comment by adityadeshlahre** [comment]
Hey @ShubhamPalriwala i would look to take this issue up !
please assign me :smile:

**Comment by ShubhamPalriwala** [comment]
All yours! Looking forward

**Comment by adityadeshlahre** [comment]
Hey guys UPDATE !

LOOM VIDEO : 
https://www.loom.com/share/7032f78c179541bf835872eaa62cb9d4?sid=ac93c34b-8660-4a38-b615-db75baadd7ba

I have tried to fix it but got some issue !
on the way to fix them and open PR.
Thank You :smile:
