### ISSUE TITLE
[FEATURE] Public url with access to survey results

### ISSUE THREAD

**Issue by edersilva78** [formbricks/formbricks#984]
### Is your feature request related to a problem? Please describe.

Not related to a problem

### Describe the solution you'd like

The option to enable access to the responses to `anyone with the url`, read only.
One option/section on the survey settings.
![image](https://github.com/formbricks/formbricks/assets/7780778/a6d04235-5b7f-4559-a138-22e49c4408f1)

What to share/grant access to.
![image](https://github.com/formbricks/formbricks/assets/7780778/661285af-dced-4aec-97eb-886e0e6d30ea)

### Describe alternatives you've considered

Adding a single user as `viewer`, but it is impractical for a large group of users (pool)

**Comment by jobenjada** [comment]
We have thought about that before!

It's a great idea however not trivial from a security perspective. Will assign someone from the team to make a concept :)

**Comment by mattinannt** [comment]
@edersilva78 The feature was finished with https://github.com/formbricks/formbricks/pull/1469 went live a few weeks ago 🚀 It's now available in Formbricks Cloud as well as the self-hosted version 🔥

**Comment by edersilva78** [comment]
@mattinannt  thanks! Already tested. You are the best!
