### ISSUE TITLE
Refactor PhoneQuestion Component

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#99]
Refactor/Rewrite the PhoneQuestion Component of EditorJS/NoCode-Editor to be better maintainable.

The PhoneQuestion Component (`snoopforms/components/editorjs/tools/PhoneQuestion.tsx`) was build using an old pattern for EditorJS. New Components like the MultipleChoiceQuestion use a new approach which works much better with React. The old components needs to be refactored / rewritten to work using the newer approach.
For that you can copy a newer component as a scaffolding and insert the logic and UI components of the PhoneQuestion.

**Comment by kymppi** [comment]
Hey im currently working on this. PR in an hour :P
