### ISSUE TITLE
[BUG][100 Points] Multi select Other option selected automatically when come back

### ISSUE THREAD

**Issue by joyal007** [formbricks/formbricks#995]
### Issue Summary

Other option in Multi Select is auto selected when coming back to the survey

### Steps to Reproduce

1. (for example) go to https://formbricks.com/clleljrog0050my0h1dn9kcrh
2. Select any options other than 'Other'
3. Click Next
4. Come Back
5. Other option is auto selected

### Expected behavior

Only the options which are selected by the user should be shown as selected

### Other information

https://www.loom.com/share/18d7981ebc6644fcbe8ff577cfd38ee4?sid=3e4d4280-5324-4a9d-b097-bf02bacd061e

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by rohan9896** [comment]
@jobenjada Can you assign this to me? Would love to work on this.

**Comment by KapadiaNaitik** [comment]
I think this is a simple fix by modifying

`  const [otherSelected, setOtherSelected] = useState(
    !!value && !question.choices.find((c) => c.label === value)
  );`
  
  to 
  
  ` const [otherSelected, setOtherSelected] = useState(
    !!value && (value as string[]).some(val => !question.choices.some(choice => choice.label === val))
  );`
  
  Do let me know if there would be any better approach then this : )

**Comment by jobenjada** [comment]
Good catch, +50 points! :)

**Comment by ShubhamPalriwala** [comment]
Completed via #1004
